### ISSUE TITLE
Have `iplot` return static image format of the plotly plot

### ISSUE THREAD

**Issue by ellisonbg** [plotly/plotly.py#1]
The `iplot` function produces an HTML representation of a plotly plot for usage in the IPython notebook. IPython also supports converting notebooks to LaTeX/PDF documents through `IPython.nbconvert`. To get this to work, iplot would have to also display a static image format of the plot. It would be as simply as a call to `display(Image(raw_image_data))` to include that in the notebook.

We (IPython dev team) is super excited about plotly and are more than willing to answer questions, etc. about the IPython integration.

**Comment by calumroy** [comment]
I seem to be having problems with this. Your example didn't work for me the pdf showed 
<plotly.tools.PlotlyDisplay object> instead of the plot in the output pdf.

I am running OSX el captain 10.11.2.
I ran the command with the option --to pdf as the option --to latex --post PDF didn't work it returned ```No module named PDF```.
```
ipython nbconvert test_to_pdf.ipynb --to pdf
[NbConvertApp] Converting notebook test_to_pdf.ipynb to pdf
[NbConvertApp] Writing 19096 bytes to notebook.tex
[NbConvertApp] Building PDF
[NbConvertApp] Running pdflatex 3 times: [u'pdflatex', u'notebook.tex']
[NbConvertApp] PDF successfully created
[NbConvertApp] Writing 46214 bytes to test_to_pdf.pdf

```

**Comment by FayeL37** [comment]
It seems the PDF version doesn't show the plotly graph. @chriddyp

**Comment by FayeL37** [comment]
When I type display(Image(raw_image_data)) into Jupyter Notebook, there is an error rising and saying Image is not defined. Any suggestion? Thanks @ellisonbg
