### ISSUE TITLE
Passing 'None' for config raises error since not itterable

### ISSUE THREAD

**Issue by milicag** [plotly/plotly.py#1001]
https://github.com/plotly/plotly.py/blob/86002912d856798b09cadf2a9dea3937386894f0/plotly/offline/offline.py#L211

```[None]``` works, but if ```None``` is a recommended default (looking at ```iplot``` method), I feel that passing ```None``` should work. In addition, using ```Kwargs``` may also be easier.

**Comment by jonmmease** [comment]
Hi @milicag , could you add an example of code using the public API that hits this error? 

The public `offline.iplot` method guards against this with `config = dict(config) if config else {}` before calling the internal `_plot_html` method.  Thanks!

**Comment by milicag** [comment]
I see, that explains it. I think I was calling `_plot_html` on `data`, with `[None]` passed for `config`, not through `iplot(data)`, something like:
```
plot_html, plotdivid, width, height = _plot_html(data, [None], True, '100%', '100%', False)
```
