### ISSUE TITLE
Could not change line edge color 'later'

### ISSUE THREAD

**Issue by parthi2929** [plotly/plotly.py#1004]
Hi
I am trying to create a map like below (famous Arad Bucharest problem for Search algorithms) in plotly.

![newplot](https://user-images.githubusercontent.com/11896263/39753218-9ba8a0f8-52db-11e8-9974-b0befddb88f2.png)

I want to change few edges(lines) colors. for eg, to show the chosen path. I could not find how to access the edges after Scatter object created. 

```
...
edge_trace = Scatter(
    x=[],
    y=[],   
    line=Line(width=0.5,color='#888'),
    hoverinfo='none',
    mode='lines+text',
    text= []
    )
...
for node, adjacencies in enumerate(G.adjacency()):
    node_trace['marker']['color'].append(len(adjacencies))
    node_info = 'Node: '+str(node)
    node_trace['text'].append(node_info)
    edge_trace['line]['color'].append(3)             #THIS DID NOT WORK
...
```

**Comment by empet** [comment]
@parthi2929 Please address questions on Plotly Forum.  Here [https://community.plot.ly/t/network-graph-set-each-edge-with-different-color/2805](https://community.plot.ly/t/network-graph-set-each-edge-with-different-color/2805) I explained how to color some network edges.

**Comment by parthi2929** [comment]
Hi

Can we do after we create node_trace and edge_trace. Edge traces have been suitably connecting the node_traces and plot is successful. Only that, after I create, i want to selectively color a part of the edge. 

Please find entire code [here](https://gist.github.com/parthi2929/27168746d6bfe10a350227c277b2a9c8)

Illustration of color requirement (red lines in below):
![image](https://user-images.githubusercontent.com/11896263/39857842-6b351942-5452-11e8-8814-50bba6483332.png)

My current plotly output:
![image](https://user-images.githubusercontent.com/11896263/39857871-7f79abca-5452-11e8-93b7-78916de03901.png)

**Comment by cldougl** [comment]
Hi there,
Thanks for using Plotly! 
Please post questions in our community forum: https://community.plot.ly
