### ISSUE TITLE
Consistently clarify latest release

### ISSUE THREAD

**Issue by Juanlu001** [plotly/plotly.py#1006]
Since #841 (@jvalhondo) and #397 (@nehalecky) were reported, the situation of Plotly releases has worsened considerably:

* GitHub latest release is 2.0.0 https://github.com/plotly/plotly.py/releases/tag/v2.0.0
* GitHub latest tag is 2.2.0 https://github.com/plotly/plotly.py/releases/tag/v2.2.0
* PyPI latest package is ~~2.5.1~~ 2.6.0 https://pypi.org/project/plotly/2.6.0/
* Changelog latest release is 2.6.0 https://github.com/plotly/plotly.py/blame/master/CHANGELOG.md#L5
* PyPI latest development release is 3.0.0rc1 https://pypi.org/project/plotly/3.0.0rc1/

This is important because when users are asked in forums whether they have "tried updating to the latest version" ([example](https://community.plot.ly/t/unable-to-maintain-aspect-ratio-in-2d-plots/10119/4?u=astrojuanlu), cc @etpinard) it's not clear what does this even mean.

Is there anything we can do to help?

cc @shreyasbapat

**Comment by shreyasbapat** [comment]
True! I have been struggling to understand why my 2.5.1 does not upgrade!

**Comment by Juanlu001** [comment]
Update: Plotly 2.6.0 has been released to PyPI.

**Comment by Juanlu001** [comment]
The situation has considerably improved now, so this issue makes no sense anymore. Thanks and keep up with the great work!

**Comment by jonmmease** [comment]
Thanks for following up @Juanlu001 ! I'm glad you've noticed the improvement 🙂
