### ISSUE TITLE
Column Reordering in Scatterplot Matrix when passed 'marker' argument

### ISSUE THREAD

**Issue by mattyarri** [plotly/plotly.py#1013]
I came across an odd error when building a Scatterplot Matrix in Plotly: the addition of a formatting argument (ie marker opacity) causes the plots for each column to become misaligned. Here is the code and output for his error:

**Correct Ordering**
![image](https://user-images.githubusercontent.com/5790281/40146205-79f66884-5919-11e8-9b25-4b47ed944366.png)

![image](https://user-images.githubusercontent.com/5790281/40146217-89ef91c0-5919-11e8-87e9-c1bcc8f6bb68.png)

**Incorrect Ordering:Addition of marker argument**
![image](https://user-images.githubusercontent.com/5790281/40146247-a930a524-5919-11e8-8853-9b544b7edb83.png)

![image](https://user-images.githubusercontent.com/5790281/40146256-b377bf04-5919-11e8-9931-815e1ccc4f22.png)

**Comment by rysktky** [comment]
im not sure if i am good enough to help, but could you share the full code? 
maybe pull from your repo?

**Comment by jonmmease** [comment]
I'm going to close this for now, but if you're interested in pursuing this further feel free to add the requested full example that we can run to replicate the problem.  Thanks!
