### ISSUE TITLE
Y-axis Range not updating correctly when using subplot with shared 'yaxes'

### ISSUE THREAD

**Issue by AmourKarir** [plotly/plotly.py#1016]
Some bars were sticking out of my bar chart (I don't think this is desired behaviour) so I set the range manually. Despite doing this and setting autorange=False, the error persists.

Additionally, the top gridline for the subplots in row 2 is not showing. Could it be a scaling issue?

`from plotly import tools
fig = tools.make_subplots(rows=2, cols=2, subplot_titles=['A', 'B'], shared_xaxes=False, shared_yaxes=True)

data = [[10, 4, 15, 20.5], [3, 12, 22.2], [6.5, 12, 26.2], [18, 4.2, 22.2]]
traces = [go.Bar(x=['Type A', 'Type B', 'Type C'], y=d) for d in data]

fig.append_trace(traces[0], 1, 1)
fig.append_trace(traces[1], 1, 2)
fig.append_trace(traces[2], 2, 1)
fig.append_trace(traces[3], 2, 2)

fig['layout']['yaxis1'].update(title='', range=[0, 25], autorange=False)
fig['layout']['yaxis2'].update(title='', range=[0, 30], autorange=False)

py.iplot(fig)`

**Comment by rysktky** [comment]
hi, I tried your sample code with offline.plot() and it did not look too bad.
Am I seeing the same figure as you? 
Sorry for my poor English understanding, I was not really sure how your graph looked...
![original](https://user-images.githubusercontent.com/39027949/40586503-d27befc8-61fd-11e8-91a4-90f463323121.png)



`.`

*I commented out these two lines and it still look like almost identical to the one above.
```
 #fig['layout']['yaxis1'].update(title='', range=[0, 25], autorange=False)
 #fig['layout']['yaxis2'].update(title='', range=[0, 30], autorange=False)
```
![commented_out](https://user-images.githubusercontent.com/39027949/40586522-fb2c6e0c-61fd-11e8-9c62-bc5f9c8569e9.png)

`.`

Probably this kind of grid layout may meet your requirements?
![ntick20_fiontsize9](https://user-images.githubusercontent.com/39027949/40586651-ee5836e6-61ff-11e8-8df0-d69c6f210c0d.png)
I added these lines to your code
```
fig['layout'].update(yaxis2=dict(nticks = 20,tickfont=dict(size=9)))
fig['layout'].update(yaxis1=dict(nticks = 20,tickfont=dict(size=9)))

#you might not need to adjust the fontsize, if screen size is not small
```

**Comment by AmourKarir** [comment]
Hello,

I should have provided a picture, apologies. Yes, our graphs look alike.

The reason I find my graphs unsuitable is that not every bar are contained within the axes of the graph. Additionally, setting setting a range with autorange=False should actually change the graph, but as you pointed out, removing those lines made no difference. Why does this happen? 
` #fig['layout']['yaxis1'].update(title='', range=[0, 25], autorange=False)
 #fig['layout']['yaxis2'].update(title='', range=[0, 30], autorange=False)`

I tried your idea and it works as you showed. Unfortunately, I do not think that I can present these graphs as they are not visually pleasing. Setting nticks to values in between 5 and 20 did not help either. 

Thank you,
Amour

**Comment by cldougl** [comment]
Hi there,
Perhaps you'd like to use the `tick0` (https://plot.ly/python/reference/#layout-yaxis-dtick) and `dtick` (https://plot.ly/python/reference/#layout-yaxis-tick0) attributes:

```
from plotly import tools
import plotly.graph_objs as go
import plotly.offline as py
fig = tools.make_subplots(rows=2, cols=2, subplot_titles=['A', 'B'], shared_xaxes=False, shared_yaxes=True)


py.init_notebook_mode()

data = [[10, 4, 15, 20.5], [3, 12, 22.2], [6.5, 12, 26.2], [18, 4.2, 22.2]]
traces = [go.Bar(x=['Type A', 'Type B', 'Type C'], y=d) for d in data]

fig.append_trace(traces[0], 1, 1)
fig.append_trace(traces[1], 1, 2)
fig.append_trace(traces[2], 2, 1)
fig.append_trace(traces[3], 2, 2)

fig['layout']['yaxis1'].update(title='', range=[0, 25], autorange=False, tick0=0, dtick=5)
fig['layout']['yaxis2'].update(title='', range=[0, 30], autorange=False, tick0=0, dtick=5)

py.iplot(fig)
```

![screen shot 2018-05-28 at 10 33 00 am](https://user-images.githubusercontent.com/2789078/40619305-8713341e-6262-11e8-90dd-5bd58bb9dc25.png)



The original result is not a bug but rather the intended autorange behavior.
In the future, please post individual questions in our community forum: https://community.plot.ly/ as we reserve issues here for bug reports.
