### ISSUE TITLE
if possible to set tickwidth ? eg: fig['layout']['yaxis']['tickwidth'] =50

### ISSUE THREAD

**Issue by liceblone** [plotly/plotly.py#1017]
if possible to set tickwidth ? eg: fig['layout']['yaxis']['tickwidth'] =50

Thanks,

**Comment by rysktky** [comment]
hi, tickwidth can be set like samples at the official site.
https://plot.ly/python/axes/

you can update the attribute later with this as well
`fig['layout'].update(yaxis=dict(tickwidth=20))`

**Comment by cldougl** [comment]
Please post future questions in the Plotly community forum: https://community.plot.ly/
Thanks!

**Comment by liceblone** [comment]
Thanks a lot
