### ISSUE TITLE
plotly seamless editing in notebook  

### ISSUE THREAD

**Issue by arsenovic** [plotly/plotly.py#102]
http://nbviewer.ipython.org/gist/arsenovic/c2e82c7fc2554529580d

i noticed that if i embed a slightly different URL then it makes for  very convenient  in-notebook plot editing. this is a really sweet and seamless way to combine plotly's ease of use GUI editing with the notebook. 

thoughts?

**Comment by jonmmease** [comment]
Closing as this is going to be handled through the [JupyterLab chart editor extension](https://github.com/plotly/jupyterlab-chart-editor). Follow along and chime in with https://github.com/plotly/jupyterlab-chart-editor/issues/20 and https://github.com/plotly/jupyterlab-chart-editor/issues/23 if you're interested!
