### ISSUE TITLE
Update to CircleCI 2.0

### ISSUE THREAD

**Issue by scjody** [plotly/plotly.py#1022]
I just noticed that plotly.py is still using CircleCI 1.0. This is [being shut down](https://circleci.com/blog/sunsetting-1-0/) on August 31, so if you want to continue using CI it needs to be migrated before then.

See [the official migration documentation](https://circleci.com/docs/2.0/migrating-from-1-2/) for guidance, or the CircleCI team are usually willing to do a lot of this work for us (but someone does need to be available to work with them). To get started with that option, contact chloe@circleci.com .

@cldougl @Kully @chriddyp FYI

**Comment by Kully** [comment]
@chriddyp I just checked the CIRCLE changelog and it looks like Python 3.6 only started being supported in version 2.6.0 (2017-02-04) https://pypi.org/project/tox/

This means we need to port over to circleCI 2.0 if we want to test python3.6 codegen in https://github.com/plotly/plotly.py/pull/942

**Comment by scjody** [comment]
To be clear: you need to do this by the end of August anyway. I'd get going now.

**Comment by scjody** [comment]
Just a reminder that this repo still uses CircleCI 1.0, which will no longer be available as of the end of August, so if you want to keep using CircleCI (which I strongly recommend), you need to transition to 2.0 **before August 31**. You can contact erin@circleci.com for help with this if necessary.

I'm tagging everyone at or affiliated with Plotly who's contributed to this repo in the past month: @jonmmease @xhlulu @michaelbabyn @priyatharsan 
plus @cldougl @Kully @chriddyp

**Comment by jonmmease** [comment]
Done!
