### ISSUE TITLE
County Outline create_choropleth

### ISSUE THREAD

**Issue by snaily250** [plotly/plotly.py#1028]
Is it possible to add a black border to outline the counties in the full USA county map? I looked over some of the layout attributes and none of them seem to support this.

Thanks!

**Comment by jmmease** [comment]
Yes (if I understand correctly), see the `county_outline` option in the second example at https://plot.ly/python/county-choropleth/.

This example specifies a white border with a width of 0.5:
`county_outline={'color': 'rgb(255,255,255)', 'width': 0.5}`

So you'll want to change it to something like 
`county_outline={'color': 'black', 'width': 0.5}`
And you can increase the width if you want the outline to be more prominent.  

Hope that helps (and please go ahead and close the issue if it does 🙂)

**Comment by snaily250** [comment]
Thanks for the help! If I could ask another question, I've been trying to add a thicker state outline using state_outline but it seems like changing the attribute isn't affecting the state outline at all, also looking at the examples I'm not sure if its properly working there. Thanks!

**Comment by jmmease** [comment]
You should be able to use the `state_outline` option just like the `county_outline` option, where you pass in a dict containing the line properties (color, width, etc.).  Here's a full example, modified from the example I referenced above, that draws the county outlines in black and the state outlines in pink.

```python
import numpy as np
import pandas as pd

df_sample = pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/minoritymajority.csv')
df_sample_r = df_sample[df_sample['STNAME'] == 'California']

values = df_sample_r['TOT_POP'].tolist()
fips = df_sample_r['FIPS'].tolist()

colorscale = [
    'rgb(193, 193, 193)',
    'rgb(239,239,239)',
    'rgb(195, 196, 222)',
    'rgb(144,148,194)',
    'rgb(101,104,168)',
    'rgb(65, 53, 132)'
]

fig = ff.create_choropleth(
    fips=fips, values=values, scope=['CA', 'AZ', 'Nevada', 'Oregon', ' Idaho'],
    binning_endpoints=[14348, 63983, 134827, 426762, 2081313], colorscale=colorscale,
    county_outline={'color': 'black', 'width': 0.5}, round_legend_values=True,
    legend_title='Population by County', title='California and Nearby States'
)
iplot(fig, filename='choropleth_california_and_surr_states_outlines')
```
![newplot-1](https://user-images.githubusercontent.com/15064365/41036286-8ceb35c4-695d-11e8-931a-069f63ae6502.png)

Does that work for you?

**Comment by jonmmease** [comment]
Closing because there doens't seem to be a bug. If you have more usage questions please ask on the plotly python forum: https://community.plot.ly/c/api/python

Thanks!
