### ISSUE TITLE
Order of traces affects visibility in Scatter3d

### ISSUE THREAD

**Issue by ivirshup** [plotly/plotly.py#1030]
For 3d scatter plots with `opacity` < 1, the last trace to be added always shows up on top, regardless of camera position.

```python
import numpy as np
from itertools import product

import plotly.graph_objs as go
import plotly.offline as py
py.init_notebook_mode(connected=True)

# Gen data
n = 10
r = np.arange(n)
a1 = np.zeros((n*n, 3))
a2 = np.zeros((n*n, 3))
for i, (x, y) in enumerate(product(r, r)):
    a1[i, :] = (x, y, -1)
    a2[i, :] = (x, y, 1)

# Gen traces
traces = list()
for i, a in enumerate((a1, a2)):
    trace = go.Scatter3d(
        x = a[:, 0],
        y = a[:, 1],
        z = a[:, 2],
        mode="markers",
        marker=dict(
            opacity=.99
        )
    )
    traces.append(trace)

# Plot
fig = go.Figure(data=traces)
py.iplot(fig)
```

When `trace 1` should be on top:

<img width="471" alt="screen shot 2018-06-08 at 2 47 07 pm" src="https://user-images.githubusercontent.com/8238804/41139581-d77e9e12-6b2b-11e8-962d-bde269b66f48.png">

When `trace 0` should be on top:

<img width="488" alt="screen shot 2018-06-08 at 2 47 19 pm" src="https://user-images.githubusercontent.com/8238804/41139589-e599afaa-6b2b-11e8-8212-38618c11d928.png">

**Comment by jmmease** [comment]
Hi @ivirshup, thanks for the report.

I've opened a corresponding issue in the plotly.js project (plotly/plotly.js#2717), which is where the actual plot rendering logic lives.  I'm going to close this issue, and we can continue the conversation with the plotly.js devs over there.

**Comment by jmmease** [comment]
Updated issue: plotly/plotly.js#1267
