### ISSUE TITLE
connectgaps=True not working properly 

### ISSUE THREAD

**Issue by ggrrll** [plotly/plotly.py#1046]
Hi, 

I am on python3, in jupyter notebook (v 5.4.1), using plotly 2.7.0

Even if there is actually *no gap* in my data (weekly time series), a gap appears. 
Plus, when I use `connectgaps=True` in my traces, it connects the last with first datapoint, as you can see in the picture.

<img width="443" alt="screen shot 2018-07-03 at 11 03 33" src="https://user-images.githubusercontent.com/15370425/42234495-fa798046-7eb1-11e8-8b27-0a0efdc5911c.png">

any idea of what's going on?

**Comment by jonmmease** [comment]
Hi @ggrrll , thanks for the report. Could you update your example to include the values of your `temp_var` and `cases` columns?  Ideally in a form that we can copy and paste into a notebook cell to reproduce what you're seeing. Thanks!

**Comment by ggrrll** [comment]
@jonmmease 

thanks for your reply -- the issue has been solved by _sorting the dataframe_, as suggested [in the plotly forum](https://community.plot.ly/t/missing-line-in-mode-lines/11429/3) - you can find there code and data as well
