### ISSUE TITLE
Contour showlines has no effect if contours.coloring != "fill"

### ISSUE THREAD

**Issue by martin-drozdik** [plotly/plotly.py#1047]
From the [documentation](https://plot.ly/python/reference/#contour-contours-showlines):

> showlines (boolean) 
> default: True 
> Determines whether or not the contour lines are drawn. Has an effect only if `contours.coloring` is set to "fill".

I think it would be nice if this restriction was lifted. Otherwise it prevents the user from creating beautiful plots like:

![newplot 2](https://user-images.githubusercontent.com/11381175/42320525-ed9e5748-8055-11e8-971a-37d33ea3bce0.png)

A workaround I use now is:

`line={'color':'rgba(0,0,0,0.0)'}`

But this is neither readable, nor efficient.

Thank you!

**Comment by jonmmease** [comment]
Hi @martin-drozdik , thanks for the suggestion.  Could you include a small example of the code and resulting plot for the case that you don't prefer, and then the code and example plot for your workaround?

Any change in the appearance of the plots or behavior of these options would need to flow through the [Plotly.js](https://github.com/plotly/plotly.js) library before making its way to plotly.py, so we'll probably end up moving the issue there, but I'd like to get the clear before/after examples nailed down first.
Thanks!

**Comment by jonmmease** [comment]
I'm going to close this here for now, but if you're still interested in this please open a corresponding issue with the plotly.js project (https://github.com/plotly/plotly.js).  Thanks for taking the time to write up the suggestion!

**Comment by martin-drozdik** [comment]
I am sorry, I procrastinated this out of existence. I will open the issue on plotly.js. Thanks!
