### ISSUE TITLE
Can't set numbered subplot axis using update in plotly.py 3.0.0

### ISSUE THREAD

**Issue by slishak** [plotly/plotly.py#1050]
I can create a `Layout` with a `yaxis2` attribute using the following methods:
```python
layout1 = go.Layout(yaxis2={'title': 'y2'})

layout2 = go.Layout()
layout2.yaxis2 = {'title': 'y2'}

layout3 = go.Layout()
layout3['yaxis2'] = {'title': 'y2'}
```

but not like this:
```python
layout4 = go.Layout()
layout4.update(yaxis2={'title': 'y2'})

layout5 = go.Layout()
layout5.update({'yaxis2': {'title': 'y2'}})
```

because only `xaxis` and `yaxis` are valid properties for a `Layout` in the schema, so I get a `ValueError`.

**Comment by jonmmease** [comment]
Thanks for the clear report @slishak. Yeah, looks like the special handling for numbered subplots is missing from the new version of `update`.

**Comment by michaelbabyn** [comment]
It looks like [a similar thing happens](https://community.plot.ly/t/polar-subplots-in-plotly-py-3-0-0/11722) when adding a Scatterpolar graph to a subplot with FigureWidget.
```f.add_trace(go.Scatterpolar(r=[1,2,3,4,5],theta = [2,4,6,8,10]),row=2,col=1)``` will try to add ```{'xaxis':'x1', 'yaxis':'y2'}``` to the Scatterpolar object, but it fails to validate.

Is this the same problem?

**Comment by jonmmease** [comment]
Note to self: Check if this is related to https://community.plot.ly/t/polar-subplots-in-plotly-py-3-0-0/11722

**Comment by jonmmease** [comment]
@slishak and @michaelbabyn,  see PR #1057 for progress. Thanks!

**Comment by jonmmease** [comment]
Fixed in 3.0.1

**Comment by slishak** [comment]
Thanks @jonmmease!

**Comment by slishak** [comment]
Looks like there's a little more to this one - I also can't use `update` for `layout.shapes` even with Plotly 3.1.0. The following code prints an empty tuple.

```python
import plotly.graph_objs as go
layout = go.Layout()
shapes = [
    # Line Vertical
    {
        'type': 'line',
        'x0': 1,
        'y0': 0,
        'x1': 1,
        'y1': 2,
        'line': {
            'color': 'rgb(55, 128, 191)',
            'width': 3,
        },
    },
    # Line Horizontal
    {
        'type': 'line',
        'x0': 2,
        'y0': 2,
        'x1': 5,
        'y1': 2,
        'line': {
            'color': 'rgb(50, 171, 96)',
            'width': 4,
            'dash': 'dashdot',
        },
    },
    # Line Diagonal
    {
        'type': 'line',
        'x0': 4,
        'y0': 0,
        'x1': 6,
        'y1': 2,
        'line': {
            'color': 'rgb(128, 0, 128)',
            'width': 4,
            'dash': 'dot',
        },
    },
]
layout.update(shapes=shapes)
print(layout.shapes)
```

**Comment by jonmmease** [comment]
Thanks @slishak , something different is going on here so I'm going to create a new issue

**Comment by jonmmease** [comment]
Hi @slishak   ,

I just pushed out release candidates for plotly.py 3.1.1 and plotlywidget 0.2.1.  Installation instructions for the release candidates are at https://github.com/plotly/plotly.py/blob/bc1d4d188ab999cd9c21e3a7908729f156bc200f/README.md.

If you have a chance to confirm that this issue is resolved in the release candidate that would be awesome!
