### ISSUE TITLE
Italian State/City Map

### ISSUE THREAD

**Issue by iocohen** [plotly/plotly.py#1058]
Hi guys,

Do you have some data with regards to the Italian cities,regions?
Where do i find some info with regard to the Italian state?

Thanks,
 Ionut

**Comment by empet** [comment]
@iocohen Here you can find  topojson and  geojson files for regions in Italy: [https://github.com/Dataninja/geo-shapes/tree/master/italy](https://github.com/Dataninja/geo-shapes/tree/master/italy)
For any other question please use the Plotly Forum: [https://community.plot.ly/](https://community.plot.ly/)
