### ISSUE TITLE
PlotlyRequestError: Bad API key

### ISSUE THREAD

**Issue by derelearnro** [plotly/plotly.py#1066]
I got this error when followed by this tutorials: 
---------------------------------------------------------------------------
PlotlyRequestError                        Traceback (most recent call last)
<ipython-input-8-a57b44688b0f> in <module>()
     16 #this widget will display our plotly chart
     17 graph = GraphWidget("https://plot.ly/~jordanpeterson/889")
---> 18 fig = py.get_figure("https://plot.ly/~jordanpeterson/889")
     19 
     20 #find the range of the slider.

/usr/local/lib/python3.6/dist-packages/plotly/plotly/plotly.py in get_figure(file_owner_or_url, file_id, raw)
    460 
    461     fid = '{}:{}'.format(file_owner, file_id)
--> 462     response = v2.plots.content(fid, inline_data=True)
    463     figure = response.json()
    464     if six.PY2:

/usr/local/lib/python3.6/dist-packages/plotly/api/v2/plots.py in content(fid, share_key, inline_data, map_data)
     52     params = make_params(share_key=share_key, inline_data=inline_data,
     53                          map_data=map_data)
---> 54     return request('get', url, params=params)
     55 
     56 

/usr/local/lib/python3.6/dist-packages/retrying.py in wrapped_f(*args, **kw)
     47             @six.wraps(f)
     48             def wrapped_f(*args, **kw):
---> 49                 return Retrying(*dargs, **dkw).call(f, *args, **kw)
     50 
     51             return wrapped_f

/usr/local/lib/python3.6/dist-packages/retrying.py in call(self, fn, *args, **kwargs)
    210                 if not self._wrap_exception and attempt.has_exception:
    211                     # get() on an attempt with an exception should cause it to be raised, but raise just in case
--> 212                     raise attempt.get()
    213                 else:
    214                     raise RetryError(attempt)

/usr/local/lib/python3.6/dist-packages/retrying.py in get(self, wrap_exception)
    245                 raise RetryError(self)
    246             else:
--> 247                 six.reraise(self.value[0], self.value[1], self.value[2])
    248         else:
    249             return self.value

~/.local/lib/python3.6/site-packages/six.py in reraise(tp, value, tb)
    691             if value.__traceback__ is not tb:
    692                 raise value.with_traceback(tb)
--> 693             raise value
    694         finally:
    695             value = None

/usr/local/lib/python3.6/dist-packages/retrying.py in call(self, fn, *args, **kwargs)
    198         while True:
    199             try:
--> 200                 attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
    201             except:
    202                 tb = sys.exc_info()

/usr/local/lib/python3.6/dist-packages/plotly/api/v2/utils.py in request(method, url, **kwargs)
    153         content = response.content if response else 'No content'
    154         raise exceptions.PlotlyRequestError(message, status_code, content)
--> 155     validate_response(response)
    156     return response

/usr/local/lib/python3.6/dist-packages/plotly/api/v2/utils.py in validate_response(response)
     77         message = content if content else 'No Content'
     78 
---> 79     raise exceptions.PlotlyRequestError(message, status_code, content)
     80 
     81 

PlotlyRequestError: Bad API key

I am probably just started that trying to visualize and design networks using Python. Could you help me to solve it?

**Comment by jonmmease** [comment]
Hi @derelearnro , have you followed the "Initialization for Online Plotting" instructions here https://plot.ly/python/getting-started/?

**Comment by jonmmease** [comment]
Closing for now. Feel free to follow up with the requested info if you're still having trouble.
