### ISSUE TITLE
Plotly 3.0 error

### ISSUE THREAD

**Issue by RishabhPande** [plotly/plotly.py#1067]
Getting below error after upgrade. Can you please help?

Invalid value of type 'builtins.str' received for the 'bgcolor' property of layout.legend
        Received value: 'pearl02'

    The 'bgcolor' property is a color and may be specified as:
      - A hex string (e.g. '#ff0000')
      - An rgb/rgba string (e.g. 'rgb(255,0,0)')
      - An hsl/hsla string (e.g. 'hsl(0,100%,50%)')
      - An hsv/hsva string (e.g. 'hsv(0,100%,100%)')
      - A named CSS color:

**Comment by jonmmease** [comment]
That error message sounds like you're using cufflinks. Cufflinks doesn't support version 3 yet.

See https://github.com/santosjorge/cufflinks/issues/119 for progress. In the meantime, downgrade back to version 2.7 if you need cufflinks. Thanks!

**Comment by iamasad** [comment]
pip uninstall plotly
pip install plotly==2.7.0

**Comment by nabhijit** [comment]
which version of cufflinks shall i install with plotly version 2.7.0?
