### ISSUE TITLE
hovermode='closest' doesn't work for Python

### ISSUE THREAD

**Issue by armadillocommander** [plotly/plotly.py#1077]
Hi,

When a try to plotted a graph with plotly online (version 3.1.0), I set the layout as:

`
layout=go.Layout(
			autosize=True,
			hovermode='closest',
			title='Title',
			legend=dict(
				#yanchor='top',
				#xanchor='center',
				y=1,
				x=0.5,
				orientation="h",
				),
			yaxis=dict(autorange=True,zeroline=True),
			xaxis=dict(autorange=True,zeroline=True),
			)
		fig=dict(data=data,layout=layout)
		py.plot(fig,filename='VolcanoPlot_'+filename[0:-5],auto_open=True)
`

However on plot.ly website, the graph still uses data compare as the default hover mode. Is there any way to change the default hover mode? Thanks!

**Comment by jonmmease** [comment]
Hi @armadillocommander ,

You're example isn't reproducible, but when I change it to the following I get the `closest` hover mode behavior on plot.ly

```python
import plotly.graph_objs as go
import plotly.plotly as py

layout=go.Layout(
    autosize=True,
    hovermode='closest',
    title='Title', 
    legend=dict(
        #yanchor='top',
        #xanchor='center',
        y=1, x=0.5, orientation="h", ),
    yaxis=dict(autorange=True,zeroline=True),
    xaxis=dict(autorange=True,zeroline=True), )

fig=dict(data=[{'y': [1, 2, 3]}],layout=layout)

py.plot(fig,auto_open=True)
```

The mouse cursor doesn't show up in the image below, but it's right on the middle point.

![screen shot 2018-07-30 at 5 55 50 am](https://user-images.githubusercontent.com/15064365/43390882-49d36470-93bd-11e8-871e-ca8fd855d2d2.png)

If you're still having trouble, please include a full minimal example that we can copy and paste and run (with imports and data and everything). Also, please use a "fenced code block" to format the code (https://help.github.com/articles/creating-and-highlighting-code-blocks/).

Thanks!

**Comment by jonmmease** [comment]
I'm going to close this for now, but we can reopen if you're still interested and have time to provide a minimal example that demonstrates the problem.  Thanks!

**Comment by x011** [comment]
2 years after and this is still not working.

**Comment by x011** [comment]
Instead of `compare` use `x`

**Comment by x011** [comment]
Instead of `closest` use `x`, i.e.:

`hovermode='x'`
