### ISSUE TITLE
remove plotly plot from api

### ISSUE THREAD

**Issue by arsenovic** [plotly/plotly.py#109]
is there a way to delete a plotly plot using  the python api?

**Comment by coffenbacher** [comment]
Is this still in progress? Would be a helpful feature!

**Comment by chriddyp** [comment]
@coffenbacher yes it is, but it's a still a few months out. In the meantime, you can prevent the proliferation of graphs by overwriting existing graphs by specifying the same filename:

```
py.plot(figure, filename='temp')
```

**Comment by coffenbacher** [comment]
Great, thanks, that's the approach I'm using.

**Comment by theengineear** [comment]
There's support for this in the REST API now, so this should be more doable.

**Comment by cldougl** [comment]
Example of deleting a plot from python https://plot.ly/python/delete-plots/
