### ISSUE TITLE
Typo in `specs/ipyplotly_integration/Scatter GL Example.ipynb` input 5: needs f -> fig

### ISSUE THREAD

**Issue by mprogram** [plotly/plotly.py#1090]
Apparently, `specs/ipyplotly_integration/Scatter GL Example.ipynb` has a typo; to correct: f -> fig in input 5. ~Please, add missing file `specs/ipyplotly_integration/biblio.bib` too to avoid 404 errors there.~ _(EDIT: my oversight with `latex_envs` upon saving the notebook)_

**Comment by jonmmease** [comment]
Hi @mprogram , thanks for bringing this up. I've actually been meaning to delete these notebooks. Most have been improved and moved to https://github.com/jonmmease/plotly_ipywidget_notebooks. When I remove this directory I'll go ahead and fix this error and add the ScatterGL notebook to this repo.

Also, I don't know what you mean by `biblio.bib` being missing. Could you elaborate?

**Comment by mprogram** [comment]
It seems when I fixed the `f`-typo on my side, my `latex_envs` added non-present in the original ScatterGL notebook file `biblio.bib`. I was referring the ScatterGL example in jupyter-widgets/pythreejs/issues/206 to illustrate that `plotly` is working on my side, and, probably, missed that alteration. Thank you for bringing this to my attention, and sorry for unneeded noise. _Changing the title back now._

**Comment by jonmmease** [comment]
Stale notebooks have been removed from the repo. Thanks for mentioning it!
