### ISSUE TITLE
Silent failure to display scatter3d plot in mode lines+markers when line color is given

### ISSUE THREAD

**Issue by ivirshup** [plotly/plotly.py#1093]
In mode `lines+markers`, if a line is specified with color from a numerical vector the plot silently fails. This happens regardless of whether I'm trying to display it in a notebook or write a file. Here's an example:

<img width="852" alt="screen shot 2018-08-05 at 1 39 17 pm" src="https://user-images.githubusercontent.com/8238804/43682321-060668da-98b5-11e8-9b43-0c6d53a99cea.png">

And here's a copy-able version of the relevant code:

```python
import plotly.graph_objs as go
import numpy as np

x, y, z, c = np.random.random_sample((4, 10))
go.FigureWidget(data=[
    go.Scatter3d(x=x, y=y, z=z,
                 line=go.scatter3d.Line(color=c))
])
```

**Comment by jonmmease** [comment]
Thanks for another helpful report @ivirshup 🙂 

I was able to reproduce the issue in Plotly.js directly and I've opened a corresponding issue there. You can follow plotly/plotly.js#2873 for updates.

**Comment by jonmmease** [comment]
Fixed in plotly.js by https://github.com/plotly/plotly.js/pull/3341 (See https://github.com/plotly/plotly.js/pull/3316#issuecomment-447962764), released in plotly.js 1.43.0 and shipped in plotly.py 3.5.0.

```python
import plotly.graph_objs as go
import numpy as np

x, y, z, c = np.random.random_sample((4, 10))
go.FigureWidget(data=[
    go.Scatter3d(x=x, y=y, z=z, mode='lines+markers',
                 line=go.scatter3d.Line(color=c),
                 marker={'color': 'blue'}
                )
])
```
![newplot 1](https://user-images.githubusercontent.com/15064365/50826197-f99d1c00-1308-11e9-8b1b-e00467cb9f53.png)
