### ISSUE TITLE
Documentation for Using Networkx Outdated

### ISSUE THREAD

**Issue by jsigee87** [plotly/plotly.py#1097]
The example written for using Networkx in Plotly uses an outdated version of Networkx (1.x). There were substantial changes between versions and the example [here](https://plot.ly/python/network-graphs/) no longer works.

In particular, at least these two sections need to be modified- the lists need to be cast as tuples.

```
for edge in G.edges():
    x0, y0 = G.node[edge[0]]['pos']
    x1, y1 = G.node[edge[1]]['pos']
    edge_trace['x'] += tuple([x0, x1, None])
    edge_trace['y'] += tuple([y0, y1, None])
```
and
```
for node in G.nodes():
    x, y = G.node[node]['pos']
    node_trace['x'] += tuple([x])
    node_trace['y'] += tuple([y])
```

There is also an error in this section that I have not been able to figure out yet.
```
for node, adjacencies in enumerate(G.adjacency_list()):
    node_trace['marker']['color'].append(len(adjacencies))
    node_info = '# of connections: '+str(len(adjacencies))
    node_trace['text'].append(node_info)
```

**Comment by jonmmease** [comment]
Thanks for the report @jsigee87!

Help keeping the docs up to date is always appreciated. Would you mind moving this issue to the documentation repo at https://github.com/plotly/documentation? Thanks!

**Comment by jsigee87** [comment]
I wrote a new one with better formatting and a possible solution to the last error. I'm going to close this one.
