### ISSUE TITLE
Not only plotlywidgets, but also the ipywidgets  are not rendered in Plotly cloud

### ISSUE THREAD

**Issue by empet** [plotly/plotly.py#1119]
Not only plotlywidgets that use `np.array`(s), but also the  `ipywidgets` widgets (sliders, text boxes, and more) are  not rendered  in Plotly cloud.

Here are pairs of identical notebooks posted on:

github: [http://nbviewer.jupyter.org/gist/empet/aabb4e6be803cbe0f7b379a0e9375a5d](http://nbviewer.jupyter.org/gist/empet/aabb4e6be803cbe0f7b379a0e9375a5d)
Plotly cloud: [https://plot.ly/~empet/14914](https://plot.ly/~empet/14914)

respectively,

github: [http://nbviewer.jupyter.org/gist/empet/8ca843886fdb038e4316165ace1523db](http://nbviewer.jupyter.org/gist/empet/8ca843886fdb038e4316165ace1523db)
Plotly cloud: [https://plot.ly/~empet/14917](https://plot.ly/~empet/14917).

**Comment by jonmmease** [comment]
I *think* the plotly cloud support for this is still in development (not yet deployed).
Is that right @tarzzz ?

**Comment by tarzzz** [comment]
> the plotly cloud support for this is still in development (not yet deployed)

That's correct. I will keep you posted.

**Comment by jonmmease** [comment]
@tarzzz just following up. Has this been deployed to public cloud yet?

**Comment by tarzzz** [comment]
@jonmease yes, we can close this now .. !!
