### ISSUE TITLE
Annotated Heatmap with custom color scale raises ValueError

### ISSUE THREAD

**Issue by andy-lz** [plotly/plotly.py#1122]
Creating an annotated heatmap with figure factory using a custom color scale (as seen below) leads to a ValueError: "map object not subscriptable."

`import plotly.figure_factory as ff`
` `
`data_test2 = ff.create_annotated_heatmap(z=z, x=x, y=y, colorscale=[[0.0, 'rgb(250,0,0)'], [0.5, 'rgb(250,250,250)'], [1.0, 'rgb(0,0,0)']], annotation_text=df_str, showscale=True)` 

I fixed this by explicitly defining the map objects for `min_col` and `max_col` in `_AnnotatedHeatMap.get_text_color()` as lists.

**Comment by jonmmease** [comment]
Thanks for the report @andy-lz . Could you add a quick example that results in this error?
Thanks!

**Comment by andy-lz** [comment]
Used a modified example from plotly documentation.

```
import plotly.plotly as py
import plotly.figure_factory as ff

z = [[.1, .3, .5],  
     [1.0, .8, .6],
     [.6, .4, .2]]

x = ['Team A', 'Team B', 'Team C']
y = ['Game Three', 'Game Two', 'Game One']

z_text = [['Win', 'Lose', 'Win'],  
          ['Lose', 'Lose', 'Win'],
          ['Win', 'Win', 'Lose']]

fig = ff.create_annotated_heatmap(z, x=x, y=y, annotation_text=z_text, colorscale=[[0.0, 'rgb(250,0,0)'], [0.5, 'rgb(250,250,250)'], [1.0, 'rgb(0,0,0)']])
```

**Comment by jonmmease** [comment]
Done in #1151
