### ISSUE TITLE
any way for offline static image export?

### ISSUE THREAD

**Issue by guoyuf** [plotly/plotly.py#1137]
HI All,

We'd like to export the ploty image as a background task that run regularly, and I tried the way from https://plot.ly/python/static-image-export/
but however, py.image.save_as method required network connectivity and send the data to the plot.ly and return the image back. offline.plot actually generate the html file, then open it in browser and download the image file. 
We want to export the image file in the background task and this two ways don't meet the requirement. Is the any way for the api office image export ?

thanks,
Eric

**Comment by jonmmease** [comment]
Hi @guoyuf ,

We've actually been working on this problem a lot lately and we're planning to release a solution in version 3.2. If you're interested in the background, check out https://github.com/plotly/plotly.py/issues/1105 and https://github.com/plotly/plotly.py/pull/1120.

If you'd be willing to help us test out the current alpha version of the static image export approach, we'd really appreciate it. Here's a repo with instructions for installing plotly.py 3.2.0 alpha 2 and the orca command line utility (orca is the project that performs that static image export): https://github.com/jonmmease/plotly_orca_notebooks.  The repo also has two example notebooks that demonstrate the new API.

Thanks for your interest 🙂
