### ISSUE TITLE
Plot.ly doesn't work in Python scripts compiled using PyInstaller

### ISSUE THREAD

**Issue by ismailuddin** [plotly/plotly.py#114]
I'm trying to make executable / standalone programs using Python. I've used Qt designer to design the GUI, and then used PyQT (pyuic4) to convert the .UI files into .PY files which I can edit and build my Python scripts / program within.

Finally, once the program is built, I use PyInstaller to compile them into standalone executable files on Windows. Unfortunately, any graphs plotted using the Plot.ly module fail to work, but matplotlib graphs still do work. Any ideas?

Here's an example which you can see works as .PY file, but if you compile using PyInstaller will not:
http://pastebin.com/yTF1zbwn

Over here you can see the exact program I'm developing in Python where my problem is occurring:
https://github.com/RUGRLN/bioinformatics/tree/master/Hydropathy%20Plot

Any ideas?

**Comment by jonmmease** [comment]
Closing as plotly.py has been largely rewritten since this was opened. Feel free to open a new issue with plotly.py version 3 if anyone is still struggling with this!
