### ISSUE TITLE
Wrapping timeseries chart

### ISSUE THREAD

**Issue by brylie** [plotly/plotly.py#1156]
A Redditor posted a seemingly simple chart design, [asking how to produce the design](https://reddit.com/comments/9cifqe):

![chart design sketch](https://i.redd.it/25ajib1bbyj11.jpg)

Initial responses about how to produce the chart were in three main flavors:
- gantt
- stacked bar
- calendar heatmap

In practice, each of the above chart types present unique challenges for, and may be incapable of rendering, the desired output.

The data structure might be, in effect, an array of two-tuples where each tuple contains a start and end Datetime.

What are some ideas on how this chart could be created with Plotly.py?

**Comment by jonmmease** [comment]
Hi @brylie ,

**Comment by jonmmease** [comment]
Hi @brylie ,

In general this kind of question is better suited to the forums (https://community.plot.ly/c/api/python), but I don't mind talking about it here this time.  This is almost a perfect fit for the `create_gantt` figure factory method.  The only thing that's perhaps not a perfect fit is that the time values have to include a date (e.g. 8am of Sept. 4th 2018, not just 8am).  Here's a quick example that shows the nature of the data structure you would need, and the result.

```python
import plotly.graph_objs as go
import plotly.figure_factory as ff
from datetime import datetime
import pandas as pd

# Helper function to build datetime for time on a certain date
def get_time(hr, min):
    return datetime(2018, 9, 4, hr, min)

df = pd.DataFrame([
      dict(Task="Monday", Start=get_time(8, 30), Finish=get_time(9, 30), Resource='Breakfast'),
      dict(Task="Monday", Start=get_time(11, 30), Finish=get_time(13, 0), Resource='Lunch'),
      dict(Task="Monday", Start=get_time(15, 30), Finish=get_time(16, 0), Resource='Snack'),
      dict(Task="Monday", Start=get_time(19, 30), Finish=get_time(20, 30), Resource='Dinner'),
      dict(Task="Tuesday", Start=get_time(9, 0), Finish=get_time(10, 0), Resource='Breakfast'),
      dict(Task="Tuesday", Start=get_time(12, 0), Finish=get_time(13, 30), Resource='Lunch'),
      dict(Task="Tuesday", Start=get_time(17, 30), Finish=get_time(18, 30), Resource='Dinner'),
      dict(Task="Wednesday", Start=get_time(8, 45), Finish=get_time(9, 30), Resource='Breakfast'),
      dict(Task="Wednesday", Start=get_time(11, 45), Finish=get_time(13, 30), Resource='Lunch'),
      dict(Task="Wednesday", Start=get_time(18, 0), Finish=get_time(19, 30), Resource='Dinner'),
     ], columns=['Start', 'Finish', 'Task', 'Resource'])

df.head()
```
![screen shot 2018-09-04 at 5 48 29 am](https://user-images.githubusercontent.com/15064365/45024087-30cf8980-b006-11e8-9bd6-5a23c290f532.png)

```python
fig = ff.create_gantt(df, index_col='Resource', show_colorbar=True, group_tasks=True)
go.FigureWidget(fig)
```
![newplot-6](https://user-images.githubusercontent.com/15064365/45024118-43e25980-b006-11e8-9db5-36708ea92c14.png)

Hope that helps!

**Comment by brylie** [comment]
Looks great! I will see if I can modify it to parse an array of structured data with proper `Datetime`s.

**Comment by brylie** [comment]
Ah, I understand better now! The `group_tasks=True` causes the tasks to be shown in the same row. That makes sense, but had me confused for a bit.

Thanks again @jonmmease :-)

**Comment by jonmmease** [comment]
Sure thing!
