### ISSUE TITLE
wrong leaves determination of _dendrogram.py

### ISSUE THREAD

**Issue by 444thLiao** [plotly/plotly.py#1181]
When I using the function for creating dendrogram, I meet some wrong presentation of the leaves.
![all zero leaves](https://user-images.githubusercontent.com/16633223/45608688-e5e25700-ba86-11e8-8e20-9ee3e28680dd.png)

In your code(**~/.local/lib/python3.6/site-packages/plotly/figure_factory/_dendrogram.py**), we can see that 
![original code which come from ~/.local/lib/python3.6/site-packages/plotly/figure_factory/_dendrogram.py](https://user-images.githubusercontent.com/16633223/45608710-0e6a5100-ba87-11e8-931f-508bd7320e4c.png)

Above code without comment is the original code for determination the y axis tick or labels. In the first image I provide, you can see that 138-140 line code will **raise silent error** which mean wrong alignment of leaves of dendrogram and labels. 

So I make a litter bit **revise** of this by 142-145 code (Of course without comment and I have use this in my computer, as far as I see, it will not raise any conflict.) .

Here is the  code
```
        if len(self.zero_vals) > len(yvals) + 1:
            l_border = int(min(self.zero_vals))
            r_border = int(max(self.zero_vals))
            self.zero_vals = [v for v in range(l_border,r_border + 1, int((r_border-l_border) / len(yvals)))]
```

#1180

**Comment by jonmmease** [comment]
Hi @444thLiao , thanks for the report. I left some comments over in #1180 , so we can continue the conversation over there.

**Comment by jonmmease** [comment]
Done in #1186. Thanks @444thLiao!
