### ISSUE TITLE
Double click zoom out behaviour

### ISSUE THREAD

**Issue by pfbuxton** [plotly/plotly.py#1183]
Hello,

Here is a movie of the problem behaviour (taken from https://plot.ly/python/zoom-events/; but it's the same using any plotly ):
![double_click2](https://user-images.githubusercontent.com/4923588/45626277-06aaac80-ba87-11e8-850e-4d86bbbe8cef.gif)

1. Zoom in by selecting a region.
2. Zoom out by double clicking.
3. Zoom in by horizontal selection.

The problem is that stage 3 also changes the vertical zoom back to that in stage 1.

**Comment by jonmmease** [comment]
Hi @pfbuxton , thanks for the report. I see what you mean. Would you mind moving this issue to the Plotly.js project at https://github.com/plotly/plotly.js/issues?  The fix will need to be made there, and then plotly.py will get it automatically.  Thanks!

**Comment by pfbuxton** [comment]
**Moved to https://github.com/plotly/plotly.js/issues/3026**
