### ISSUE TITLE
The length of the arrows are not maintained by the 2D quiver plot in figure factory.

### ISSUE THREAD

**Issue by dabana** [plotly/plotly.py#1187]
### Bug report

Thanks to the Plotly community for this great implementation of 2D quiver plots in the figure factory. The issue is that the length of the arrows are not maintained by the quiver plot. 

**Bug summary**

The length of the arrows in a quiver plot carries relevant information in most applications (wind speed, force field intensity, etc.). This seem to be the case with the quiver plot in figure factory if both axis have the same scale (for example if quiver plot is plotted on a map: x and y coordinates have obviously the same scale). However, as soon as the scales of both axis are different, the apparent length of the arrows is distorted. The barb angle is also affected. This should not be the case.

**Code for reproduction**

This is an instance of a quiver plot where the scales of both axis are different but where the length of each arrow is intended to be the same (using the norm and an angle to produce u an v).

```python
import plotly.plotly as py
import plotly.figure_factory as ff
import plotly
print(plotly.__version__)
import numpy as np

x,y = np.meshgrid(np.arange(0.5, 3.5, .5), np.arange(0.5, 4.5, .5))
u = x
v = y
angle = np.arctan(v / u)
norm = 0.25
u = norm * np.cos(angle)
v = norm * np.sin(angle)

fig = ff.create_quiver(x, y, u, v, scale = 1)
```

**Actual outcome**

The above code produces arrows with apparent lengths changing depending on their angle. This should not be the case.

![fig1](https://user-images.githubusercontent.com/29574757/45758771-64a8d280-bbf4-11e8-8c82-b7570765ef7f.png)

**Expected outcome**

This is an instance of the above quiver plot but where the scales of both axis are forced to be the same using specifications on the layout.

```python
x,y = np.meshgrid(np.arange(0.5, 3.5, .5), np.arange(0.5, 4.5, .5))
u = x
v = y
angle = np.arctan(v / u)
norm = 0.25
u = norm * np.cos(angle)
v = norm * np.sin(angle)

fig = ff.create_quiver(x, y, u, v, scale = 1)
fig.layout = go.Layout(
    yaxis=dict(
        scaleratio = 1,
        scaleanchor = "x"
    ))
```
![fig2](https://user-images.githubusercontent.com/29574757/45758786-6e323a80-bbf4-11e8-97f7-770ac85bab8d.png)

It would be nice to have nicely scaled arrows as the above plot but with axis of different scales.

*WORKAROUND*: To maintain an aspect ratio similar the original plot, we can force a scale ratio different than 1 and apply an inverse transformation on u (or v) to counter the effect of the stretching.

```
x,y = np.meshgrid(np.arange(0.5, 3.5, .5), np.arange(0.5, 4.5, .5))
u = x
v = y
angle = np.arctan(v / u)
norm = 0.25
scale_ratio = 0.5
u = norm * np.cos(angle) * scale_ratio
v = norm * np.sin(angle)

fig = ff.create_quiver(x, y, u, v, scale = 1)
fig.layout = go.Layout(
    yaxis=dict(
        scaleratio = scale_ratio,
        scaleanchor = "x"
    ))
```
![fig3](https://user-images.githubusercontent.com/29574757/45758795-75594880-bbf4-11e8-88f2-3737005ad550.png)

This workaround is not perfect though. Despite the fact that the length of the arrows are maintained, the barbs of the arrows are still distorted and they don't look good.

**Plotly version**
  * Operating system: Ubuntu 16.04 Bash on Windows10
  * Plotly version: 3.2.1
  * Python version: 3.5.6
plotly installed from pip

**Comment by dabana** [comment]
Fun fact, the plotly.js team was working actively on a 3D quiver plot (see closed issue #861) earlier this year. This issue maybe a good time for the plotly community to give a little love to their 2D quiver plot. Just saying ;)

**Comment by jonmmease** [comment]
Hi @dabana ,

Thanks for the report, this is a great point regarding scale distortion.  What if we added `scaleratio` as an input parameter (optional for now for backwards compatibility) that would cause the arrow length and arrowhead shape to be computed with respect to this ratio, and would set the `scaleanchor` and `scaleratio` attributes in the resulting figure as you do above.

Do you have any interest in working on this?

**Comment by jonmmease** [comment]
Yeah, I was picturing that the user would use the `scaleratio` to adjust the viewport onto the data. But you're right that this would take some manual tweaking to get right.

Another option that comes to mind is that the user could specify the figure width/height that they want. Then we could subtract off the margins to get the pixel width/height of the axis extents. Then we could also manually compute the axis range extents based on the data itself to compute the `scaleratio` that way.

To go a step further, we could add an option to return the figure as a `FigureWidget`, with per-installed callback functions that would dynamically recompute the scale ratio and the quiver lines whenever the plot resizes or the user zooms in.  This would be someone similar to the DataShader example here: http://nbviewer.jupyter.org/github/jonmmease/plotly_ipywidget_notebooks/blob/master/notebooks/DataShaderExample.ipynb.

**Comment by dabana** [comment]
I like the callback function approach a lot. I will look into it. Thanks!

**Comment by dabana** [comment]
I have opened a pull request regarding only the scaling of the arrows for now by passing a `scaleratio` parameter to the `create_quiver` function.

I have not worked on the widget callback option yet. I still have problem making widgets work on my dev environment.

Here is the result with `scaleratio` = 1:

![fig3](https://user-images.githubusercontent.com/29574757/45984582-b8218300-c02f-11e8-982e-ef901a9e625c.png)

**Comment by dabana** [comment]
@jonmmease I am having trouble making the [FigureWidget callback example](http://nbviewer.jupyter.org/github/jonmmease/plotly_ipywidget_notebooks/blob/master/notebooks/DataShaderExample.ipynb) work. When I try to zoom in on the last figure, the one with the callback, it does not redraw the image. I suppose it should redraw an image with many points when I zoom in? Right? But it just zooms in the image like the previous figure. Maybe there is something I do wrong...

**Comment by jonmmease** [comment]
Hi @dabana , could you try upgrading plotly and all of the other packages to match the current versions in the [README instructions](https://github.com/plotly/plotly.py#installation) and try again?
