### ISSUE TITLE
Difficulties with cx_Freeze and plotly.py

### ISSUE THREAD

**Issue by T4rk1n** [plotly/plotly.py#1199]
Trying to cx_Freeze a dash app, I get errors that it cannot import `pkg_resources` in https://github.com/plotly/plotly.py/blob/f727c465d1606e667444db9130a3d0b8e70336f6/plotly/offline/offline.py#L11. 

From a google search, seems like `pkg_resources` is hard to include with cx_Freeze and most solutions requires editing the site-package libs that use `pkg_resources`. I was only able to get past the problem once I commented out the import in my local plotly install.

 I think `pkg_resources` can be replaced with `pkgutils` like we use in dash to get the bundle files.
https://github.com/plotly/dash/blob/f94991be2db9a3a640ea680c2cf872611f857eb6/dash/dash.py#L453

**Comment by jonmmease** [comment]
I'm definitely open to considering this, but I would need to understand the background a bit more.  In particular, are there any situations where `pkg_resources.resource_string` and `pkgutils.get_data` don't return the same thing?

@chriddyp Do you recall any background on how plotly.py ended up using `pkg_resources` and dash ended up using `pkgutils`.

**Comment by T4rk1n** [comment]
@jonmmease I just tested and they return the same thing, they both resolve the content by using the appropriate loader. The difference is that `pkg_resources` is part of `setuptools` whereas `pkgutil` is stdlib.

**Comment by chriddyp** [comment]
> Do you recall any background on how plotly.py ended up using pkg_resources and dash ended up using pkgutils.

I don't recall. Probably the result of google searches for both cases. They were done a few years apart from each other so I'm not surprised that they are different.

**Comment by jonmmease** [comment]
Thanks @T4rk1n , after looking into this a bit this does seem like a pretty benign change, and if it helps with cx_Freeze compatibility I'm all for it.  This is also as good a time as any as I'm about to run through a bunch of manual notebook testing for the 3.3 release.  See PR in #1201.  If all goes well this will be in 3.3 in a few days.

**Comment by T4rk1n** [comment]
Thanks
