### ISSUE TITLE
Multiple Y axes: only one scatterplot renders

### ISSUE THREAD

**Issue by thatneat** [plotly/plotly.py#1200]
This may be an issue in plotlyjs - if so, please point me to the right place.

When plotting data on multiple Y axes, particularly when nothing is plotted on the primary Y axis, sometimes plotly will only show one series.

## Example code

```
# !pip install plotly
import datetime
from numpy import array

import plotly.graph_objs as go

import plotly
print(plotly.__version__) # 3.2.1

go.FigureWidget({
    'data': [{'marker': {'color': 'red', 'size': 5, 'symbol': 'circle-open'},
              'mode': 'markers',
              'name': 'r',
              'type': 'scatter',
              'uid': 'af705b50-c0ee-11e8-84dc-1208b1a853fd',
              'x': array([datetime.datetime(2015, 1, 1, 0, 0),
                          datetime.datetime(2015, 1, 2, 0, 0),
                          datetime.datetime(2015, 1, 3, 0, 0),], dtype=object),
              'y': [0.43369082538702236, 1.2898213293637133, 0.624430850249652,],
              'yaxis': 'y2'},
             {'marker': {'color': 'green', 'size': 5, 'symbol': 'circle-open'},
              'mode': 'markers',
              'name': 'g',
              'type': 'scatter',
              'uid': 'af705b51-c0ee-11e8-9e48-1208b1a853fd',
              'x': array([datetime.datetime(2015, 1, 1, 0, 0),
                          datetime.datetime(2015, 1, 2, 0, 0),
                          datetime.datetime(2015, 1, 3, 0, 0),], dtype=object),
              'y': [-0.30649578247834386, -1.0464786848889265, 1.911426735783162,],
              'yaxis': 'y3'},],
    'layout': {'xaxis': {'title': 'Time'},
               'yaxis': {'title': 'y axis number one',},
               'yaxis2': {'overlaying': 'y',
                          'title': 'y axis 2'},
               'yaxis3': {'overlaying': 'y',
                          'side': 'right',
                          'title': 'y axis 3'}}
})
```

## Expected behavior

Two series are plotted

## Actual behavior

Two series show up in the legend, but only one series is plotted:
![image](https://user-images.githubusercontent.com/3341011/46046395-bdd1a400-c0d5-11e8-8854-af490377d5bd.png)

## Workaround

If you change `'y2'` in the code above to '`y1`', both series will show up. However, it's not always reasonable to assume there will be data on y1 - I am trying to write a purpose-specific API that uses plotly in such a way that I cannot guarantee there will be something on y1 without significant extra complexity.

**Comment by thatneat** [comment]
I found another workaround - simply place a blank, invisible annotation on axis 1:
```
'layout': {
    ...
    'annotations': [{
        'yref': 'y',
        'xref': 'paper',
        'text': '',
        'showarrow': False,
        'visible': True,
    }],
    ....
}
```
This also causes both scatterplots to display correctly.

**Comment by jonmmease** [comment]
Hi @thatneat ,

Thanks for the report, I see what you mean.  Yes, I think this is something we should move to the plotly.js repo at https://github.com/plotly/plotly.js/issues.  You can mention me in that plotly.js issue as well in case they have any questions on the Python side. Thanks!

**Comment by thatneat** [comment]
Thanks @jonmmease , I'll close this since it clearly occurs without plotly.py . As you can see above I filed plotly/plotly.js#3074
