### ISSUE TITLE
tools.make_subplots with colspan/rowspan fails when using sharex/sharey

### ISSUE THREAD

**Issue by claria** [plotly/plotly.py#1209]
Hi,
i am trying to create  subplots with colspan/rowspan attribute and shared_xaxes using the code below (Plotly 3.3). As soon as i use the shared_xaxes=True parameter, the code fails with the error message:

`Exception: Something went wrong. An axis object for (2,4) subplot cell got deleted.`

Example code:
```
from plotly import tools
import plotly
import plotly.plotly as py
import plotly.graph_objs as go

trace1 = go.Scatter(
    x=[0, 1, 2],
    y=[10, 11, 12]
)
trace2 = go.Scatter(
    x=[2, 3, 4],
    y=[100, 110, 120],
)
trace3 = go.Scatter(
    x=[2, 3, 4],
    y=[100, 110, 120],
)

fig = tools.make_subplots(rows=3, cols=4, specs=[[{'colspan':3}, None, None, None], 
                                                [{'rowspan':2, 'colspan':3}, None, None, {'rowspan':2}], 
                                                [None, None, None, None]],
                          shared_xaxes=True, shared_yaxes=True,
                          vertical_spacing=0.001)

print(fig['layout'])

fig.append_trace(trace1, 1, 1)
fig.append_trace(trace2, 2, 1)
fig.append_trace(trace3, 2, 4)

print(fig['layout'])

fig['layout'].update(height=600, width=600, title='Stacked Subplots with Shared X-Axes')
plotly.offline.iplot(fig, filename='test')
```

Cheers,
Georg

**Comment by empet** [comment]
@claria,  Remove `shared_xaxes=True`, because the trace1 and trace 2, that are aligned vertically, do not have the same x range, to share xaxes.
After this change no error is displayed, and you'll get the plot.

**Comment by claria** [comment]
@empet Aah sorry, i put this minimal example together too quickly. If you change the x axes to overlap, e.g. of all traces to x=[1,2,3], the error remains. And yes, this error is specific to shared_xaxes=True

**Comment by empet** [comment]
@claria  The error persists, because the trace3 is not aligned vertically with no other trace to share xaxis.

**Comment by empet** [comment]
@claria, This case has the same drawback as the previous example:

![subplots_sharexaxes](https://user-images.githubusercontent.com/3627253/46249807-f6f07800-c437-11e8-8db3-cce4ccea5a9e.png)

I removed `shared_xaxes=True` to get this plot.  The traces 3 and 5  have common x-range, but there is
an empty cell above them. `shared_xaxes`, respectively `yaxes` work only  when on the corresponding column/row we have inserted traces in all cells, and moreover they have the same range.

**Comment by claria** [comment]
@empet I could accept this as the expected behaviour if shared_xaxes=[[1,1],[2,1],[4,1]] would work so that i could use shared_axes at least for the first column. But this gives the same error message. I would expect this to be a common use case.

**Comment by claria** [comment]
Hi @empet, in the plot you showed with shared_xaxes=False, the y axes are shared without a problem. Even more strange. I can even add a subplot+trace in the upper right corner and the error with shared_xaxes=True persists.
```
from plotly import tools
import plotly
import plotly.plotly as py
import plotly.graph_objs as go


trace1 = go.Scatter(
    x=[0, 1, 2],
    y=[10, 11, 12]
)
trace2 = go.Scatter(
    x=[0, 1, 2],
    y=[100, 110, 120],
)
trace3 = go.Scatter(
    x=[0, 1, 2],
    y=[100, 110, 120],
)
trace4 = go.Scatter(
    x=[0, 1, 2],
    y=[100, 110, 120],
)
trace5 = go.Scatter(
    x=[0, 1, 2],
    y=[100, 110, 120],
)
trace6 = go.Scatter(
    x=[0, 1, 2],
    y=[100, 110, 120],
)

fig = tools.make_subplots(rows=5, cols=4, specs=[[{'colspan':3}, None, None, {}], 
                                                 [{'rowspan':2, 'colspan':3}, None, None, {'rowspan':2}], 
                                                 [None, None, None, None],
                                                 [{'rowspan':2, 'colspan':3}, None, None, {'rowspan':2}], 
                                                 [None, None, None, None],
                                                 ],
                          shared_xaxes=True, shared_yaxes=True,
                          vertical_spacing=0.001)

print(fig['layout'])

fig.append_trace(trace1, 1, 1)
fig.append_trace(trace2, 2, 1)
fig.append_trace(trace3, 2, 4)
fig.append_trace(trace4, 1, 4)
fig.append_trace(trace5, 4, 1)
fig.append_trace(trace6, 4, 4)

print(fig['layout'])

fig['layout'].update(height=600, width=600, title='Stacked Subplots with Shared X-Axes')
plotly.offline.iplot(fig, filename='test')
```

**Comment by claria** [comment]
@empet, why are the ticks in the first column below the first upper most subplot, in the second column below the lowest one?

Let's summarize the behaviour:

- If you use colspan/rowspan you cannot use shared_{x,y}axes=True , but have to specify  the shared cols/rows.
- If you additionally have an empty cell somewhere, shared axes does not work at all.

**Comment by empet** [comment]
@claria 
1)  The ticks are put  to the plot referenced to `xaxis`, `yaxis`, because 
as we can see from the printed `Layout`:
```
Layout({
    'xaxis': {'anchor': 'y', 'domain': [0.0, 0.74]},
    'xaxis4': {'anchor': 'free', 'domain': [0.78, 1.0], 'position': 0.0},
    'yaxis': {'anchor': 'x', 'domain': [0.832, 1.0]},
    'yaxis2': {'anchor': 'free', 'domain': [0.416, 0.792], 'position': 0.0},
    'yaxis4': {'anchor': 'free', 'domain': [0.0, 0.376], 'position': 0.0}
})
```
that the cell  (1,1) is referenced to the `xaxis`, and `yaxis` and both have set the anchor `y`, respectively `x`.

With these updates: 
```
fig.layout.xaxis.anchor='free'
fig.layout.yaxis.anchor='free'
```
the ticks are put to the lowermost cell.

2) `shared_xaxes`, `shared_yaxes` given as lists or lists of lists of tuples work  in the subplots with empty cells, too.

**Comment by claria** [comment]
@empet Thank you a lot for your advice. It is very much appreciated. Regarding 2) you are right, shared_axes given as lists work in subplots with empty cells.

Regarding the inconsistency of the axes, adding your fig.layout...='free' lines results in the following plot for me, which is clearly undesired:
![newplot](https://user-images.githubusercontent.com/1030408/46260834-9753a480-c4eb-11e8-88df-cc8925c51710.png)

**Comment by empet** [comment]
@claria  What is your Plotly version?  Here is a Jupyter Notebook [https://plot.ly/~empet/14993](https://plot.ly/~empet/14993) running Plotly 3.3.0, and it works with those `fig.layout` updates.

**Comment by claria** [comment]
Ah i checked if the behaviour was the same in Plotly 2.7 so i switched back and forgot to upgrade again. Thanks a lot for the hint!

**Comment by empet** [comment]
@jonmmease this issue can be closed.
