### ISSUE TITLE
Add Congressional Districts Geometry to Choropleth  State and National Maps

### ISSUE THREAD

**Issue by thedatasleuth** [plotly/plotly.py#1215]
Hi, 

I really like the county choropleth feature in Plotly, and I'm wondering if we can add congressional district geometries as a new feature.  I think there would be a lot of interest in this, especially with the upcoming elections.  Here are some shapefiles for congressional districts from the Census Bureau's website:  https://www.census.gov/geo/maps-data/data/cbf/cbf_cds.html to get started.  Let me know how else I might be able to help!

**Comment by jonmmease** [comment]
Hi @thedatasleuth, this would be awesome!  Feel free to make some suggestions for how the API might look.

Should it be an option in `county_choropleth` (though I suppose the name would be bit misleading in that case)?  I assume that the FIPS codes we use for counties would not be relevant to congressional districts. Is there a good analog for congressional districts?

**Comment by mbkupfer** [comment]
#1219

**Comment by thedatasleuth** [comment]
Hi,  I've started to take a look at the zip file I downloaded located at the website I posted above.  It looks like congressional districts are uniquely defined, first by the column 'STATEFP' which is the same as the state FIPs code used for the county choropleth.  Within each state FIP code, there is another column 'CD115FP' which defines the congressional districts within each state.  I was able to open the .dbf file with this code:

```
import pandas as pd
from simpledbf import Dbf5
dbf = Dbf5('./cb_2017_us_cd115_500k.dbf')
df = dbf.to_dataframe()
```

And I was able to plot the distinct congressional districts with this code:

```
import pandas as pd
import shapefile
import numpy as np
import matplotlib.pyplot as plt

shp_file_base='cb_2017_us_cd115_500k'
dat_dir='/Users/jessicachace/Desktop/general_assembly/Post-Course/Midterm Elections/'+shp_file_base +'/'
sf = shapefile.Reader(dat_dir+shp_file_base)

""" PLOTS ALL SHAPES AND PARTS """
plt.figure(figsize=(30,30))
ax = plt.axes() # add the axes
ax.set_aspect('equal')

for shape in list(sf.iterShapes()):
    npoints=len(shape.points) # total points
    nparts = len(shape.parts) # total parts

    if nparts == 1:
        x_lon = np.zeros((len(shape.points),1))
        y_lat = np.zeros((len(shape.points),1))
        for ip in range(len(shape.points)):
            x_lon[ip] = shape.points[ip][0]
            y_lat[ip] = shape.points[ip][1]
        plt.plot(x_lon,y_lat) 

    else: # loop over parts of each shape, plot separately
        for ip in range(nparts): # loop over parts, plot separately
            i0=shape.parts[ip]
            if ip < nparts-1:
               i1 = shape.parts[ip+1]-1
            else:
               i1 = npoints
            
            seg=shape.points[i0:i1+1]
            x_lon = np.zeros((len(seg),1))
            y_lat = np.zeros((len(seg),1))
            for ip in range(len(seg)):
                x_lon[ip] = seg[ip][0]
                y_lat[ip] = seg[ip][1]
            
            plt.plot(x_lon,y_lat) 

plt.xlim(-130,-60)
plt.ylim(23,50)
plt.show();
``` 

which I found on this website: https://chrishavlin.wordpress.com/2016/11/16/shapefiles-tutorial/

**Comment by BA-Apex** [comment]
Just checking.  Has there been any movement in this topic?  Is there a congressional district choropleth map for plotly?

**Comment by bdempe18** [comment]
From what I have seen there is still no congressional district choropleth for plotly, although I desperately need one (but not quite desperate enough to do it myself).

**Comment by nicolaskruchten** [comment]
We're not planning on adding any new geometries to the library itself, however both flavours of Choropleth maps (outline and mapbox) support GeoJSON input of arbitrary geometries, now, so you can make this yourself pretty easily: https://plotly.com/python/choropleth-maps/ and https://plotly.com/python/mapbox-county-choropleth/
