### ISSUE TITLE
Can I display plotly figure in github readme?

### ISSUE THREAD

**Issue by pjgao** [plotly/plotly.py#1217]
Hello, I want to display graph generated by plotly in jupyter notebook, Can I use markdown to achieve this goal?

**Comment by jonmmease** [comment]
Hi @pjgao, you can display a figure in markdown as a static image (See https://daringfireball.net/projects/markdown/syntax#img). To create the static image, click the little camera button in the plot toolbar, or use the [static image export](https://plot.ly/python/static-image-export/) instructions from Python.  I don't know of any way to embed a live version of the plot in GitHub markdown.

And please direct future questions (that aren't bug reports or feature requests) to the plotly python forum channel (https://community.plot.ly/c/api/python). Thanks!
