### ISSUE TITLE
Could Plotly export 3D building to a PDF with all elements are vector format?

### ISSUE THREAD

**Issue by ConAntares** [plotly/plotly.py#1221]
Could Plotly export 3D building to a PDF with all elements are vector format?

Now, I have a free account, if Plotly can export 3D buildings to a PDF or EPS file with all elements including line, point, colorbar, etc, are vector elements, i will buy it.

**Comment by jonmmease** [comment]
Hi @ConAntares , static image export to vector formats can now be done offline without an account using the orca project. See https://plot.ly/python/static-image-export/.  But, here's an important note from that page:

> Note: It is important to note that any figures containing WebGL traces (i.e. of type scattergl, heatmapgl, contourgl, scatter3d, surface, mesh3d, scatterpolargl, cone, streamtube, splom, or parcoords) that are exported in a vector format will include encapsulated rasters, instead of vectors, for some parts of the image.

So you can export 3D plots to PDF/EPS format, but they will be still be included as raster (non-vector) images.  This is also the case for the online export under a paid account.

Please ask future questions (that aren't bug reports / feature requests) on the forums at https://community.plot.ly/c/api/python. Thanks!
