### ISSUE TITLE
Customizable SI Codes with d3-format

### ISSUE THREAD

**Issue by jhxu0416** [plotly/plotly.py#1222]
When I am setting valueformat in hoverlabel, plotly is using d3-format. I have the same issue as [Stackoverflow discussion](https://stackoverflow.com/questions/17037023/how-to-get-localizable-or-customizable-si-codes-with-d3-format), which is to show "B" instead of "G" to make chart more busniess friendly. 

Is there a way to modify in plotly?

Thanks.

**Comment by jonmmease** [comment]
Hi @jhxu0416,

This would need to be handled in the plotly.js project (https://github.com/plotly/plotly.js), right now the formats are based on what D3 provides (https://github.com/d3/d3-format/blob/master/README.md#locale_format), and it doesn't look like there's a way to change the SI suffix. I'm going to close this here, but feel free to raise a feature request over there.
