### ISSUE TITLE
Python Dashboard API - Custom Header and Box Title Font

### ISSUE THREAD

**Issue by tim-sauchuk** [plotly/plotly.py#1225]
I see that all plots can have customized font, but fonts using the dashboard API doesn't allow for this. Specifically, the header font and the box title fonts are restricted to a default font. This would be great to have, since all text in a dashboard could use the same, custom font.

**Comment by Kully** [comment]
Hey @tim-sauchuk, although it is not in the documentation page [over here](), you can actually set the fontfamily for the entire dashboard the same way you can do with the online tool:

For example:

```python
my_dboard['settings']['fontFamily'] = 'Liberation Sans'
```

and with these fonts to choose from:

![screen shot 2018-10-16 at 7 40 38 am](https://user-images.githubusercontent.com/10369095/47013926-c5a1c880-d116-11e8-93bd-4596bb766f0b.png)

Does this answer your questions? Let me know if you have anymore.

**Comment by jonmmease** [comment]
Closing for now, thanks for the documentation update @Kully!
