### ISSUE TITLE
[HTML plot div output] Reducing html file size

### ISSUE THREAD

**Issue by frgfm** [plotly/plotly.py#1226]
Hi,

I'm having trouble with HTML output for significant data amounts. 

# System
Linux system Ubuntu 16.04
Python 2.7
plotly 3.0.0

# Data used
A pandas dataset df, with 2 columns for instance 'prob' between 0 & 1 and 'cat_var' which would be a categorical variable

# What I did

`import plotly.offline as py
import plotly.graph_objs as go

traces = [go.Histogram(x=df.loc[df.cat_var == value, 'prob'],
                                      xbins=dict(start=0, end=1, size=0.025),
                                      name=value, opacity=0.6) 
              for value in df.cat_var.unique()]

layout = go.Layout(title='Distribution of classification probabilities',
                   xaxis={'title': 'Confidence on classification'},
                   yaxis={'title': 'Occurrences', 'type': 'log'},
                   barmode='overlay')
fig = go.Figure(data=traces, layout=layout)

html = py.plot(fig, include_plotlyjs=False, output_type='div')
text_file = open('my_plot.html', 'w')
text_file.write(html)
text_file.close()
`

# Expected behavior
Usually, I just paste the html in the webpage I want to and it works (in HTML snippets for platforms like Confluence). 
However, in this case, let's assume I have about 10k-15k samples : 
- whichever interaction I will have with the window, for each bin, the only information available for this given bin (visible) is : bin population size, bin boundaries
- yet, in the html output ALL probabilities are output which generate huge file size for this usage

So is there any way to reduce the file size ? (I thought about moving to barchart which would require some data preprocessing but if there is any way to provide compact html output, I would be delighted!)

Any help/advice is welcome !
Thanks

**Comment by jonmmease** [comment]
Hi @frgfm ,

If you use the `histogram` trace type then the underlying data must be embedded along with the HTML.  In your case I'd recommend you compute the histogram in Python using numpy's histogram function (https://docs.scipy.org/doc/numpy/reference/generated/numpy.histogram.html#numpy.histogram), and then plot your data as a bar chart.

If you'd like more help working through the detials, please start a thread on the forum at https://community.plot.ly/c/api/python. Thanks!
