### ISSUE TITLE
Document aspectmode for 3D axes in example page

### ISSUE THREAD

**Issue by chrisranderson** [plotly/plotly.py#1228]
I'm plotting spatial data and I wanted the aspect ratio of the data to be preserved, but I couldn't figure out how. I eventually found #70 and `aspectmode=data`.

In https://plot.ly/python/3d-axes/, there's no mention of "scale", "ratio", or "aspect" when I ctrl+F through. I think it would be helpful to add an example showing 1) skewed data due to the cube default and 2) data with square angles after using `aspectmode=data`. That seems like the most natural place to demo this functionality.

Thanks!

**Comment by jonmmease** [comment]
Thanks for the suggestion @chrisranderson!  I'm going to move this to the documentation repo at https://github.com/plotly/documentation/issues/1142.
