### ISSUE TITLE
Changing the color of axes and numbers 

### ISSUE THREAD

**Issue by pnoonan32** [plotly/plotly.py#1247]
How can I change the color of the axes & numbers of a graph. For instance, if my x axis had the numbers 5,10,15,20. How can I change the color of those numbers. Also, if my x-axis title was "Dates", how can I change the color of that title

**Comment by jonmmease** [comment]
Hi @pnoonan32,

Setting the `layout.xaxis.color` and `layout.yaxis.color` properties will set the color of the axes, axis ticks, and axis labels.

e.g.
```python
import plotly.graph_objs as go
fig = go.FigureWidget()
fig.layout.xaxis.color = 'red'
fig.layout.yaxis.color = 'red'
fig.layout.xaxis.title = 'Dates'
fig
```
![newplot 64](https://user-images.githubusercontent.com/15064365/47711374-7629c500-dc0b-11e8-898c-19dd8fd7f481.png)

Please ask future questions (that aren't bug reports / feature requests) in the forum at https://community.plot.ly/c/api/python.  Thanks!
