### ISSUE TITLE
Enable explicite definition of 'middle' colour in bullet charts

### ISSUE THREAD

**Issue by EBoisseauSierra** [plotly/plotly.py#1261]
**Could it please be possible to easily manually set the 'middle' colour of a bullet chart — e.g., via `range_colors` list of length 3: `range_colors=[<bad>, <medium>, <good>]`?**

Currently, you can only define `range_colors=[<bad>, <good>]` and `<medium>` is automatically computed. A hacky workaround is needed to set it manually.

----

When you create a bullet chart (see MWE below), the 'middle' colour is computed as the "average" of both `range_colors` that have been manually defined.

However, I believe it might sometimes be needed to be able to manually define this 'middle' colour.

In the example below, **I'd like to manually define the automatically computed brown as blue**. 

![image](https://user-images.githubusercontent.com/37387755/48012851-d98b8980-e11a-11e8-9e9c-4f2e8a015158.png)

This bullet chart is created via the code below:

``` python
import plotly.graph_objs as go
import plotly.figure_factory as ff

# Create initial bullet chart
fig = ff.create_bullet(
            orientation='h',
            ranges='range',
            range_colors=['#ff1a1a', '#7cfc00'],
            measures='data',
            measure_colors=['#ffffff', '#333333'],
            data=[dict(
                range=[.4, .5, 1],
                data=[0, 0.8],
            )],
        )

# Display figure
go.FigureWidget(fig)
```

**Manually changing brown into blue is only possible via a 'hacky' solution** detailed by @jonmmease on the [community forum](https://community.plot.ly/t/manually-define-all-3-colors-of-a-bullet-chart-background):

![screenshot from 2018-11-05 16-54-36](https://user-images.githubusercontent.com/37387755/48013140-88c86080-e11b-11e8-9b40-ccde8b9f3487.png)

```python
import plotly.graph_objs as go
import plotly.figure_factory as ff

# Create initial bullet chart
fig = ff.create_bullet(
            orientation='h',
            ranges='range',
            range_colors=['#ff1a1a', '#7cfc00'],
            measures='data',
            measure_colors=['#ffffff', '#333333'],
            data=[dict(
                range=[.4, .5, 1],
                data=[0, 0.8],
            )],
        )

# Filter down to the 'ranges' bars
bar = [bar for bar in fig.data if bar.name == 'ranges']

# Set the color of the middle bar to blue
bar[1].marker.color = 'blue'

# Display figure
go.FigureWidget(fig)
```

**Comment by nicolaskruchten** [comment]
We've actually deprecated the `ff.create_bullet()` figure factory in favour of the `go.Indicator` trace type: https://plotly.com/python/bullet-charts/
