### ISSUE TITLE
3D Network shows only one lable

### ISSUE THREAD

**Issue by Lindafr** [plotly/plotly.py#1283]
Hello!

I am currently working on creating a 3D Network Graph with your tool. Everything is awesome and so easy. I have only one question: why does every 3D Network Graph show only one certain label where-ever I hover the mouse or whatever node I click on. One example can be your tutorial itself: https://plot.ly/python/3d-network-graph/. I'm working in Ubuntu and checked it in Firefox and Chrome. If the problem is in my computer I don't know where to look. 

Thanks for this amazing tool.

**Comment by jonmmease** [comment]
Hi @Lindafr, glad you're enjoying working with plotly.py 🙂 

I'm not sure that I'm seeing what you're seeing.  When I hover over on the example in https://plot.ly/python/3d-network-graph/ I do see different hover labels for each point:

![hover_network](https://user-images.githubusercontent.com/15064365/48900474-7ab75700-ee20-11e8-9dc5-ccf85c5b4474.gif)

Is the behavior you're seeing consistent with https://github.com/plotly/plotly.py/issues/952?

**Comment by Lindafr** [comment]
Hi, @jonmmease!

Here's an example of what I see on https://plot.ly/python/3d-network-graph/ in Ubuntu 16.04:

![peek 2018-11-22 15-52](https://user-images.githubusercontent.com/32580630/48906943-c09b0c00-ee6e-11e8-94d0-c78d8563509b.gif)

I read the other issue #952, and decided to test looking the network on Windows 10. There it works just fine! Anyways, it's not a big problem for me as I understood it's not a problem in my code (based on that example).

**Comment by jonmmease** [comment]
@archmoj @etpinard Is this (and #952) a known issue on the plotly.js side? Seems like something that's happening for some users on Ubuntu.

**Comment by etpinard** [comment]
Sounds similar to https://github.com/plotly/plotly.js/issues/3258

**Comment by jonmmease** [comment]
Fixed by plotly.js https://github.com/plotly/plotly.js/pull/3301, released in plotly.js 1.43.0, and shipped in plotly.py 3.5.0
