### ISSUE TITLE
Increase orca retry timeout

### ISSUE THREAD

**Issue by jonmmease** [plotly/plotly.py#1297]
As reported in https://github.com/plotly/orca/issues/164, the current policy of retrying the first image export for up to 8 seconds is not always sufficient.

https://github.com/plotly/plotly.py/blob/a9fa5de705d86a229eca988ec1f5ed5069d91dc0/plotly/io/_orca.py#L1194-L1195

Lets increase this to 30 seconds to be on the safe side.

**Comment by RylanSchaeffer** [comment]
I run into timeout issues when creating a scatter plot with 2^20 points. The following doesn't help:

```
plotly.io.orca.ensure_server()
time.sleep(10)
```

Any other suggestions?
