### ISSUE TITLE
New runtime error

### ISSUE THREAD

**Issue by hughesadam87** [plotly/plotly.py#132]
HI,

I had some plotly code that had nicely produced Plotly from a 3 x 2 matplotlib multiplot.  Any example of the interactive 6-plot is shown here.

http://nbviewer.ipython.org/github/hugadams/FiberData/blob/master/2014/5_29_14/Analysis/Fiber2/peg_overnight/peg_overnight.ipynb

Now when I run the same code, I get a RuntimeError.  The plot still works in matplotlib, so all I can figure is that it's a plotly issue?  I'm using `plotly 1.3.0`.  

Any ideas?

RuntimeError                              Traceback (most recent call last)
<ipython-input-3-71decdb19631> in <module>()
      7 ts = ts.as_varunit(INTERVAL)
      8 
----> 9 six_plot_inter(ts, title='Full Data %.2f-%.2f%s' % (ts.columns[0], ts.columns[-1], INTERVAL), striplegend=True)

<ipython-input-2-b8c750de4683> in six_plot_inter(_args, *_kwargs)
     16           #           world_readable=False,
     17                       height=650,
---> 18                       update=_pyupdate) #Overwrite some mpl-conversion settings

/home/glue/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/plotly/plotly/plotly.pyc in iplot_mpl(fig, resize, strip_style, update, **plot_options)
    220 
    221     """
--> 222     fig = tools.mpl_to_plotly(fig, resize=resize, strip_style=strip_style)
    223     if update and isinstance(update, dict):
    224         try:

/home/glue/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/plotly/tools.pyc in mpl_to_plotly(fig, resize, strip_style, verbose)
    359     if _matplotlylib_imported:
    360         renderer = matplotlylib.PlotlyRenderer()
--> 361         matplotlylib.Exporter(renderer).run(fig)
    362         if resize:
    363             renderer.resize()

/home/glue/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/plotly/matplotlylib/mplexporter/exporter.pyc in run(self, fig)
     47             import matplotlib.pyplot as plt
     48             plt.close(fig)
---> 49         self.crawl_fig(fig)
     50 
     51     @staticmethod

/home/glue/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/plotly/matplotlylib/mplexporter/exporter.pyc in crawl_fig(self, fig)
    114                                        props=utils.get_figure_properties(fig)):
    115             for ax in fig.axes:
--> 116                 self.crawl_ax(ax)
    117 
    118     def crawl_ax(self, ax):

/home/glue/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/plotly/matplotlylib/mplexporter/exporter.pyc in crawl_ax(self, ax)
    145                 with self.renderer.draw_legend(legend=legend, props=props):
    146                     if props['visible']:
--> 147                         self.crawl_legend(ax, legend)
    148 
    149     def crawl_legend(self, ax, legend):

/home/glue/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/plotly/matplotlylib/mplexporter/exporter.pyc in crawl_legend(self, ax, legend)
    165                     if not (child is legend.get_children()[-1]
    166                             and child.get_text() == 'None'):
--> 167                         self.draw_text(ax, child, force_trans=ax.transAxes)
    168                 elif isinstance(child, matplotlib.lines.Line2D):
    169                     self.draw_line(ax, child, force_trans=ax.transAxes)

/home/glue/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/plotly/matplotlylib/mplexporter/exporter.pyc in draw_text(self, ax, text, force_trans, text_type)
    209                                     coordinates=coords,
    210                                     text_type=text_type,
--> 211                                     style=style, mplobj=text)
    212 
    213     def draw_patch(self, ax, patch, force_trans=None):

/home/glue/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/plotly/matplotlylib/renderer.pyc in draw_text(self, **props)
    506         """
    507         self.msg += "    Attempting to draw an mpl text object\n"
--> 508         if not mpltools.check_corners(props['mplobj'], self.mpl_fig):
    509             warnings.warn(
    510                 "Looks like the annotation(s) you are trying \n"

/home/glue/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/plotly/matplotlylib/mpltools.pyc in check_corners(inner_obj, outer_obj)
     39 
     40 def check_corners(inner_obj, outer_obj):
---> 41     inner_corners = inner_obj.get_window_extent().corners()
     42     outer_corners = outer_obj.get_window_extent().corners()
     43     if inner_corners[0][0] < outer_corners[0][0]:

/home/glue/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/matplotlib/text.pyc in get_window_extent(self, renderer, dpi)
    737             self._renderer = renderer
    738         if self._renderer is None:
--> 739             raise RuntimeError('Cannot get window extent w/o renderer')
    740 
    741         bbox, info, descent = self._get_layout(self._renderer)

RuntimeError: Cannot get window extent w/o renderer

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
