### ISSUE TITLE
Plotly User Guide in Python - Incorrect "size" value in example

### ISSUE THREAD

**Issue by vitchyr** [plotly/plotly.py#1384]
The first example in the [Plotly User Guide in Python](https://plot.ly/python/user-guide/) seems to have an error. I just updated plotly and am using version 3.4.2.

The `'size'` value should be a number rather than a string. Otherwise, I get the following error:
```
ValueError: 
    Invalid value of type 'builtins.str' received for the 'size' property of scatter.marker
        Received value: '10'
```

**Comment by jonmmease** [comment]
Thanks for taking the time to report this @vitchyr. I've opened an issue for it in our documentation repo at https://github.com/plotly/documentation/issues/1225.
