### ISSUE TITLE
3.5.0rc1 QA

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.py#1388]
Will collect QA items in comments here.

**Comment by nicolaskruchten** [comment]
If I make a heatmap using the `plotly` theme, it doesn't pick up the colorscale... `heatmap`, `contour`, `histogram2d` still need `autocolorscale` set in the themes for this to work: https://github.com/plotly/streambed/blob/master/shelly/webapp/static/webapp/src/workspace/components/panels/EditModeMenu/Themes/Default/figures/plotly-dark-theme.js#L155

(I suspect `histogram2dcontour` also does but I haven't checked... if so please let me know and I'll fix it in Chart Studio also!)

**Comment by jonmmease** [comment]
Thanks for opening the issue.  Hmm, this *should* be happening already.

Here's the templategen logic

https://github.com/plotly/plotly.py/blob/eba79a196b38ac2212158078c7759fd2397f2dfd/templategen/utils/__init__.py#L93-L96

And here's what I'm seeing for a heatmap example.

![screen shot 2019-01-03 at 6 13 31 pm](https://user-images.githubusercontent.com/15064365/50666608-8c456000-0f83-11e9-88be-ea9697d721a3.png)

Could you add an example of where it's not picking up the theme colorscale for you?

**Comment by nicolaskruchten** [comment]
I think my notebook was somehow stuck with Plotly 1.42.5 ...

**Comment by nicolaskruchten** [comment]
Looks like this release is good!
