### ISSUE TITLE
Error in running plots

### ISSUE THREAD

**Issue by Sirorezka** [plotly/plotly.py#1391]
Hi,

I’ve got error when running plotly in Jupyter. Plotly version 3.4.2, python version 3.6.5, Windows 10.

My code:
from plotly import version
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot
import plotly.graph_objs as go
init_notebook_mode(connected=False)
plot([go.Scatter(x=[1, 2, 3], y=[3, 1, 6])])

Error:
AttributeError: module ‘plotly.validators.scatter.marker.colorbar’ has no attribute ‘TitlefontValidator’

Could you please help me with it? I belive that it is missing in __init__ file

**Comment by jonmmease** [comment]
Cross reference https://community.plot.ly/t/error-when-running-plotly-on-python-jupyter/17980

> Sometimes this kind of problem can happen if there are somehow multiple copies of plotly.py installed. Could you check the output of pip list and conda list to see if plotly shows up in both places?

**Comment by jonmmease** [comment]
Closing here, lets continue discussion on the forum if you're still having this problem.
