### ISSUE TITLE
4 new colors for plotly themes

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.py#1392]
Let's add the last 4 colors from here!

https://projects.susielu.com/viz-palette?colors=[%22#636efa%22,%22#EF553B%22,%22#00cc96%22,%22#ab63fa%22,%22#19d3f3%22,%22#e763fa%22,%22#FECB52%22,%22#FFA15A%22,%22#FF6692%22,%22#B6E880%22]&backgroundColor=%22#ffffff%22&fontColor=%22black%22

**Comment by jorive** [comment]
I feel these colors would be nice to have too: [A color palette optimized for data visualization](http://www.mulinblog.com/a-color-palette-optimized-for-data-visualization/)
