### ISSUE TITLE
FigureWidget not working in Jupyterlab

### ISSUE THREAD

**Issue by avneeshs1** [plotly/plotly.py#1405]
I have tried following the instructions to the dot but am still getting "Error displaying widget" error. ipywidgets works ok. pyplot offline itself works fine. But not FigureWidget.

==============

Python 3.6.5 :: Anaconda, Inc.
JupyterLab v0.35.0
Known labextensions:
   app dir: D:\conda\envs\python3\share\jupyter\lab
        @jupyter-widgets/jupyterlab-manager v0.38.1 enabled  ok
        @jupyterlab/plotly-extension v0.18.1 enabled  ok
        jupyterlab-chart-editor v1.0.0 enabled  ok
        plotlywidget v0.6.0 enabled  ok

================

![image](https://user-images.githubusercontent.com/13733034/51642685-0be99d80-1f38-11e9-945d-f833e475366c.png)

![image](https://user-images.githubusercontent.com/13733034/51642758-4c491b80-1f38-11e9-906b-9871d3eea06d.png)

**Comment by jonmmease** [comment]
Hi @avneeshs1,

Thanks for the report and for including the browser error messages.  The fact that the widget manager is complaining that it can't find plotlywidget `0.2.1` implies that you have an older version of the plotly python package installed.  To match up with version `0.6.0` of the JupyterLab `plotlywidget` extension you need `plotly` version `3.5.0` installed.

I recommend referring to the README JupyterLab installation instruction (https://github.com/plotly/plotly.py/blob/master/README.md#jupyterlab-support-python-35) for the current compatible versions.

Does that help?

**Comment by avneeshs1** [comment]
Thanks for clarifying and apologies for missing this somehow. Upgrading plotly fixed the issue.
