### ISSUE TITLE
3D sphere

### ISSUE THREAD

**Issue by guenp** [plotly/plotly.py#141]
Hi folks,
I'm trying to plot a sphere in plotly, but it's not showing up.
http://nbviewer.ipython.org/gist/guenp/bef6f907d801ba092c01
Any help is appreciated.
-Guen

**Comment by jumpjack** [comment]
I can I do this in javascript? I don't know python, but I would like to add a real 3d shape at the center of my 3d chart here:
http://win98.altervista.org/space/exploration/3d/space-explorer-tracker.html?orbiter=-85&center=coord@301&lat=-70.90267&lon=22.78110&alt=0&name=Moon
