### ISSUE TITLE
Boxplot with log x-axis results in wrong box sizes

### ISSUE THREAD

**Issue by KonradTUM** [plotly/plotly.py#1415]
I tried plotting boxplots with an log x-axis but ran into trouble with the box width (the with is very big for low and very small for high x-values). See the screenshot for what I mean. As I couldnt find a solution to manipulate the box width manually I decided to open this issue. 
![newplot 10](https://user-images.githubusercontent.com/20302399/51846138-4b89fe00-2319-11e9-9eb6-4a84f266b38d.png)

**Comment by jonmmease** [comment]
Hi @KonradTUM, thanks for taking the time to bring this up.  I've reproduced what you're seeing in plotly.js and opened an issue over there at https://github.com/plotly/plotly.js/issues/3508.  I'm going to close this, and we can continue discussion on the plotly.js issue.  Thanks!
