### ISSUE TITLE
numpy.asscalar is deperecated

### ISSUE THREAD

**Issue by yurzo** [plotly/plotly.py#1427]
Per https://docs.scipy.org/doc/numpy/reference/generated/numpy.asscalar.html

np.asscalar is deprecated

https://github.com/plotly/plotly.py/blob/bc4fb4697bca78cd5732fdd3f86fa8b7eb53909c/_plotly_utils/basevalidators.py#L57

**Comment by jonmmease** [comment]
Thanks @yurzo.  Do you happen to know how far back `numpy.ndarray.item()` is supported?

cc @malmaud

**Comment by d0tfile** [comment]
@jonmmease looks like since 1.6 (https://docs.scipy.org/doc/numpy-1.6.0/reference/generated/numpy.ndarray.item.html)

**Comment by malmaud** [comment]
I'll take a look in a few days.
