### ISSUE TITLE
barchart breaks and groups all values into one bar

### ISSUE THREAD

**Issue by vavalomi** [plotly/plotly.py#1434]
On a specific string in the labels, barchart breaks and only displays one bar.

```python
from plotly.offline import init_notebook_mode, iplot
import plotly.graph_objs as go
from plotly import __version__
__version__
```
    '3.6.1'

```python
init_notebook_mode(connected=True)
```
```python
trace1 = [go.Bar(
            y=[20, 14, 23],
            x=['11.1.1', '12.1.0', '12.1.1'],
)]

iplot(trace1, filename='bar')
```
```python
trace2 = [go.Bar(
            y=[20, 14, 23],
            x=['11.1.1', '12.1', '12.1.1'],
)]

iplot(trace2, filename='bar1')
```

trace1 results in correct chart with 3 bars, but trace2 ends up showing only one bar for the value ('12.1', 14).

The issue seems to be '12.1', It gets interpreted as a number.

This was present in the previous version as well and didn't get resolved after updating to the current version.

**Comment by jonmmease** [comment]
Hi @vavalomi,

If you're working with strings that may contain valid numbers that you want to treat as categorical, you'll need to explicitly set the axis type to `'category'`

```python
from plotly.offline import init_notebook_mode, iplot
import plotly.graph_objs as go
init_notebook_mode(connected=True) 

trace2 = [go.Bar(
            y=[20, 14, 23],
            x=['11.1.1', '12.1', '12.1.1'],
)]
layout = go.Layout(xaxis={'type': 'category'})
fig = go.Figure(trace2, layout)
iplot(fig)
```
![newplot 4](https://user-images.githubusercontent.com/15064365/53012018-dbe6ca80-340f-11e9-829b-709d1583eda5.png)

Here is the reference documentation for `layout.xaxis.type`: https://plot.ly/python/reference/#layout-xaxis-type.

Does that work?

**Comment by vavalomi** [comment]
Hi @jonmmease, thanks for the suggestion, that does seem to resolve my particular issue.
Just a general clarification though, why would xaxis (or yaxis for horizontal) not be always categorical for a bar chart? histogram is already a separate chart type so I'd assume that the 'regular' bar charts are for discrete values. no?
Also, this still seems like a bug to me - I would understand the behavior if all the values were valid numbers that happened to be encoded as strings, but in the example, all values are string except one 'like number' and still the type ends up being set as continuous ...

**Comment by jonmmease** [comment]
> Just a general clarification though, why would xaxis (or yaxis for horizontal) not be always categorical for a bar chart?

No, this isn't always the case. Sometimes the axis could be dates (https://plot.ly/python/bar-charts/#customizing-individual-bar-base) and for various reason you may still want to use a bar chart to display a histogram (e.g. you're only given the frequencies, or dataset is larger that what the browser can handle so you compute the frequencies in advance)

> Also, this still seems like a bug to me - I would understand the behavior if all the values were valid numbers that happened to be encoded as strings, but in the example, all values are string except one 'like number' and still the type ends up being set as continuous ...

Yeah, you have a good point. I'm going to close this here because this behavior is determined by Plotly.js. Feel free to open an issue over there (https://github.com/plotly/plotly.js/issues) to talk about whether this should be changed.
