### ISSUE TITLE
[Bug] Geom_smooth graphical error when converting from ggplot to plotly using ggplotly

### ISSUE THREAD

**Issue by MartinWillem** [plotly/plotly.py#1439]
Hello,

I have a graphical issue which shows up when converting a ggplot2 plot with geom_smooth to a plotly plot:
![bugged](https://user-images.githubusercontent.com/22497488/53079735-5d655800-34f7-11e9-92c5-cd280f9febea.PNG)

as you can see in the plotly plot, an extra nonsensical confidence interval ribbon gets generated below the fitted lines.

When I lower the confidence interval from 0.95 to 0.80 the ribbon in correctly displayed:
![ggplotly_correct_but_lower_confinterval](https://user-images.githubusercontent.com/22497488/53079864-a74e3e00-34f7-11e9-81d3-be5725624a84.PNG)

However this is not the confidence interval I need.
I know it has something to do with plotly as this is my ggplot (with confidence interval 0.95) used to generate the first bugged image:
![ggplot_correct](https://user-images.githubusercontent.com/22497488/53079926-ce0c7480-34f7-11e9-9192-db9bbc6538e5.PNG)

Here is the (anonymized) code used to generate the plot(s):

p16 <- ggplot(data= df, order = rownames(x)) + 
  geom_point(data= df,aes(x=x.ordered, y=(mean1), color=paste("Number = ", Number))) + 
  geom_point(data= df,aes(x=x.ordered, y=(mean2), color=paste("Number2 = ", Number))) +
  geom_smooth(data = dfcopy, aes(x=x.ordered, y=mean2, color=Number, group=Number), method="loess", level=0.95) + 
  ylab("y") + scale_y_continuous(limits=c(0, 1)) + xlab(paste("x")) +
  theme_bw() + theme(plot.title = element_text(hjust = -.5, face="bold"), axis.title.x = element_text(hjust = 1, size = 14, face="bold"), axis.text.x = element_text(angle = 90, hjust = 1), axis.title.y = element_text(size = 14, face="bold")) + 
  ggtitle("") + labs(color = "\n\nType of data point: " )

p16 <- p16 + scale_color_manual(values=c("#B24745FF", "#DF8F44FF","#00A1D5FF",  "#6A6599FF", "#00A1D5FF", "#6A6599FF"))
gp16 <- ggplotly(p16, tooltip=c("text")) %>% layout(legend = list(orientation = "v",xanchor = "center", x = 1.2), title = list())  

Unfortunately I can't provide data or the axes, I also removed the ggplot text variable due to anonymous data.

If someone might know a solution to this graphical error, it would be greatly appreciated.

**Comment by jonmmease** [comment]
Hi @MartinWillem,

Please move this issue to the R plotly library project at https://github.com/ropensci/plotly. Thanks!
