### ISSUE TITLE
How to rotate the direct label text on the bars?

### ISSUE THREAD

**Issue by COlivasWork** [plotly/plotly.py#1441]
![image](https://user-images.githubusercontent.com/47869652/53200678-ffa83d00-35d6-11e9-80b6-81cb45dbfd6c.png)

When the text on the bars is bigger than the width of the bars, the text is rotated to fit inside the bars. However, this rotation is uncomfortable to read. How can you rotate the text so that it would be read down to up rather than up to down, as it is now.

**Comment by jonmmease** [comment]
Hi @COlivasWork,

I don't think it's possibe to customize the rotation direction right now.  I'm going to close this here because this is a change that would need to be added to Plotly.js, but feel free to open an issue over there to discuss the idea https://github.com/plotly/plotly.js.  Thanks!
