### ISSUE TITLE
Actually absolute sizemode for cones

### ISSUE THREAD

**Issue by CarlAndersson** [plotly/plotly.py#1443]
If I understand the documentation correctly there is no way to manually scale the cones in the plot units. Even when using sizemode='absolute' there is some magic rescaling of the length of the cones.
I would expect a way to use the norm of the (u,v,w) vector directly as the length of the cones, but this is not really possible unless you understand how the scaling factor is computed.

**Comment by jonmmease** [comment]
Hi @CarlAndersson, could you move this issue to the plotly.js project (https://github.com/plotly/plotly.js/issues) so that devs over there will see it?  Thanks!
