### ISSUE TITLE
"Download plot as png" returns damaged heatmaps, if it is a lot of values

### ISSUE THREAD

**Issue by PlatonB** [plotly/plotly.py#1446]
Plotly 3.6.1, Fedora 28, Firefox 65.

A screenshot of a big heatmap made by "Download plot as png" is incorrect:
![plotly_ld_triangle_big_heatmap](https://user-images.githubusercontent.com/25541767/53726258-aa91e400-3e7e-11e9-8a8a-4fc7d0709a84.png)

The correct version made by Firefox Screenshots:
![firefox_ld_triangle_big_heatmap](https://user-images.githubusercontent.com/25541767/53726458-078d9a00-3e7f-11e9-9ebd-59bccd185219.png)

**Comment by jonmmease** [comment]
Hi @PlatonB,

Could you share the code you're using to make this?  Or better yet, a minimal example with synthetic data that shows the problem.

We'll need to work out a reproducible example and open a report with the Plotly.js project at https://github.com/plotly/plotly.js/issues

**Comment by PlatonB** [comment]
Hello, @jonmmease !
Example with synthetic data:
```
import random, plotly as py, plotly.figure_factory as ff
z = [[round(random.random(), 2) for cell_index in range(300)] for row_index in range(300)]
heatmap = ff.create_annotated_heatmap(z, xgap=1, ygap=1, colorscale='Greens')
heatmap['layout']['annotations'] = []
py.offline.plot(heatmap)
```

"Download plot as a png":
![plotly_random_300x300](https://user-images.githubusercontent.com/25541767/53736177-0b7ae580-3e9a-11e9-88d6-1f234bfcd68a.png)

Firefox Screenshots:
![firefox_random_300x300](https://user-images.githubusercontent.com/25541767/53736201-1df51f00-3e9a-11e9-8645-62eec02aee61.png)

**Comment by jonmmease** [comment]
Hi @PlatonB,

I think the issue might be the figure size.  Clicking save snapshot doesn't automatically use the current figure size. So my guess is that the figure is expanded to a larger size when you take the firefox snapshot than the default plotly download png size.  Try setting the `figure.layout.width` and `figure.layout.height` to something larger and see if you get better results.
 
Alternatively, you might consider setting `xgap` and `ygap` to 0 when the resolution of the heatmap is approaching the resolution of the plot area of the resulting png image.

**Comment by PlatonB** [comment]
Hello, @jonmmease !
I made width x height equal 1920x1080, and set xgap and ygap as 0. Indeed it works that way. The heatmap saved as png is visible (albeit slightly blurred). It's a bit frustrating that this is not the default behavior.

**Comment by jonmmease** [comment]
For discussion of figure size when using the export button see https://github.com/plotly/plotly.js/issues/1576.  

It alright if we close this here in favor of that issue?

**Comment by PlatonB** [comment]
Thanks!
OK.
