### ISSUE TITLE
Excess horizontal lines

### ISSUE THREAD

**Issue by Garafutdinov102** [plotly/plotly.py#1450]
Hi plotly community. Thank you for incredible work. It's awesome!
I have some trouble with plotly lib on Python. When I make two graph on one plot, then plot show excess horizontal lines.
scatter1 & scatter2 on one plot: 
![image](https://user-images.githubusercontent.com/25218835/53805111-58be8c00-3f5a-11e9-9c88-e178300aaf24.png)
scatter1 on one plot : 
![image](https://user-images.githubusercontent.com/25218835/53805142-6542e480-3f5a-11e9-8fb0-1c752aca2c9e.png)
scatter2 on one plot: 
![image](https://user-images.githubusercontent.com/25218835/53805153-6aa02f00-3f5a-11e9-8291-035929f386a5.png)
Maybe you know how I can solute this trouble?

**Comment by jonmmease** [comment]
Hi @Garafutdinov102,

It looks like the data set you're plotting isn't sorted by the x dimension.  Could you check that out? If that doesn't help, please include a fully reproducible example that demonstrates the problem. Thanks!

**Comment by Garafutdinov102** [comment]
Hi @jonmmease,
Thank you for answer. Yes, it's problems with data set.
