### ISSUE TITLE
Double clicking to isolate a trace is buggy

### ISSUE THREAD

**Issue by mbkupfer** [plotly/plotly.py#1457]
I'm sorry, but I don't have time to create a reproducible example as I'm on a tight deployment schedule at the moment, but feel free to try this out in my demo link: http://eurostat-demo.herokuapp.com/

The issue is that the isolate trace feature, by double clicking in the legend, works at times and sometimes it doesn't. See below for an example. I find that this doesn't occur in Firefox, but does in IE and Chrome. 

My gif below is from the second tab. The figure is called: Temporary employees by education (1000's)

![bug_legend](https://user-images.githubusercontent.com/6313008/54045901-a835cf80-4187-11e9-9247-c59af13d57fd.gif)

**Comment by jonmmease** [comment]
Thanks for the report @mbkupfer, and very nice app BTW!

I tried it in Chrome and I see what you mean.  In my case, the figures with vertical legends seem to work fine, but this one with the horizontal legend has this odd behavior.  And I can also reproduce the problem with this simple Plotlyjs scatter example with a horizontal legend (https://plot.ly/javascript/horizontal-legend/).

Do the vertical legend plots work properly for you?  If so, perhaps you could switch this legend to vertical as a workarond, and then we can open a plotly.js issue that calls out horizontal legends.

Thanks for taking the time to let us know!

**Comment by mbkupfer** [comment]
Yes, now that you mention it is that vertical figures don't experience this issue. In my situation, the horizontal legends have very little traces not making it a big burden to isolate a single trace. I think I will just leave as is as I already like my layout, but thanks for the suggestion. 

>If so, perhaps you could switch this legend to vertical as a workarond, and then we can open a plotly.js issue that calls out horizontal legends.

This is the strangest thing, but for some reason I can't reproduce the problem anymore! Even using the scatter example. I will close this issue here, but feel free to open a new one in plotly.js if you can still reproduce. Otherwise I will just assume it was a fluke.
