### ISSUE TITLE
Invalid property specified for object of type plotly.graph_objs.layout.Scene: 'annotaions'

### ISSUE THREAD

**Issue by ZhangJiankun21** [plotly/plotly.py#1458]
Hi, I'm trying to plot 3D line plot in Jupyter notebook while got an error like this 
`ValueError: Invalid property specified for object of type plotly.graph_objs.layout.Scene: 'annotaions'
`
`layout = go.Layout(
    width=800,
    height=700,
    autosize=False,
    title='Test 3dg',
    scene=dict(
        aspectratio = dict(
            x = 1,
            y = 1,
            z = 0.7
        ),
        xaxis=dict(
            gridcolor='rgb(255, 255, 255)',
            zerolinecolor='rgb(255, 255, 255)',
            showbackground=True,
            backgroundcolor='rgb(230, 230,230)'
        ),
        yaxis=dict(
            gridcolor='rgb(255, 255, 255)',
            zerolinecolor='rgb(255, 255, 255)',
            showbackground=True,
            backgroundcolor='rgb(230, 230,230)'
        ),
        zaxis=dict(
            gridcolor='rgb(255, 255, 255)',
            zerolinecolor='rgb(255, 255, 255)',
            showbackground=True,
            backgroundcolor='rgb(230, 230,230)'
        ),
        camera=dict(
           center =dict(
               x = 0,
               y = 0, 
               z = 0
           )
        ),
        annotaions = annotation
    ),

)`

Indeed annotation here is a list just like [{'yanchor': 'bottom', 'xanchor': 'left', 'text': 'LINC01128\nprocessed_transcript:long intergenic non-protein coding RNA 1128 [Source:HGNC Symbol;Acc:HGNC:49377]\n', 'ax': 50, 'ay': 0, 'x': -11.474487698561111, 'y': 2.0491968453108957, 'arrowhead': 1, 'z': -8.298534164977223}
Please let me know if you have some suggestions.

**Comment by jonmmease** [comment]
Hi @ZhangJiankun21, I think there might be a typo in the example you pasted here. I think `annotaions` should be `annotations`.

Does changing that take care of the error?

**Comment by ZhangJiankun21** [comment]
Yes. Thanks for the help. Really sorry for the inconvenience.

**Comment by jonmmease** [comment]
No problem. Thanks for caring about plotly.py and taking the time to help make it better!
