### ISSUE TITLE
plotly.offline.iplot - Option to save to a file and embed link in notebook

### ISSUE THREAD

**Issue by Nikolai-Hlubek** [plotly/plotly.py#1469]
Dear all

The following use case:
I use jupyter with plotly. In some notebooks we plot large amount of data > 1e6 points. Embedding the plot directly in the notebook causes the notebooks to get very large > 100Mb. 
This causes issues with 
- saving in jupyter [Jupyter: Large notebook fails to save](https://github.com/jupyter/notebook/issues/650)
- saving incremental progress because the files are so huge 
- with version control of the notebooks, since the diffs are huge.

The following solution seems to solve these issues for me:
```
filename = 'results/foo.html'
plotly.offline.plot(fig, filename=filename)
IPython.display.display(IPython.display.IFrame(src=filename, width=1200, height=800))
```

This saves the picture to an external file and embeds the contents of this file in Jupyter, therefore bypassing all issues mentioned above. Since googling showed that other users sometimes have similar issues maybe it is a good idea to add the above code to plotly.offline.iplot and make it available via a option?

Best regards
Nikolai

**Comment by jonmmease** [comment]
Thanks for the suggestion @Nikolai-Hlubek, I can see that this could be really useful in some situations.  As it happens, I was in the middle of large rewrite of the plotly.py rendering system when I saw this, and it was actually pretty easily to integrate it as an option based on what I had so far.  See the writeup at https://github.com/plotly/plotly.py/pull/1474 for more context if you're interested!

**Comment by onclick360-blog** [comment]
I am using Jupyter [notebook](https://onclick360.com/cost-function-in-machine-learning/) as a public server and accessing remotely when i am trying to run some plot with plotly it's not showing on my [remote web browser](https://onclick360.com/jenkins-installation-windows) its throw error "127.0.0.1 refused to connect." not sure in iframe how to use original server ip instead of 127.0.0.1.

**Comment by Nikolai-Hlubek** [comment]
Dear Jon

I forgot to respond to your reply. Thank you that this functionality has been implemented.
