### ISSUE TITLE
Can ff.create_choropleth be used for non USA countries?

### ISSUE THREAD

**Issue by APandaInFjord** [plotly/plotly.py#1472]
`import plotly.plotly as py
from plotly.offline import init_notebook_mode, iplot # plotly offline mode
init_notebook_mode(connected=True) 

import plotly.figure_factory as ff

fips = ['01', '02', '03']
values = range(len(fips))
print (type(values))
fig = ff.create_choropleth(fips=fips, values=values, scope=['norway'])
iplot(fig, filename='choropleth of some norway counties')`

It gives a blank window... what shall i do if i want non-USA countries?

**Comment by empet** [comment]
@APandaInFjord   `ff.create_choropleth()` works only for US counties.  To get the Norway choropleth
follow this Jupyter Notebook: [https://plot.ly/~empet/15052](https://plot.ly/~empet/15052).

**Comment by APandaInFjord** [comment]
Thanks. What about other plots than choropleth on this page https://plot.ly/python/maps/

do they also only work for USA?

**Comment by empet** [comment]
@APandaInFjord   The plots that involve traces of type `scattermapbox` work with any other country, and  `scattergeo` works for sure with Europe,  for example.

**Comment by APandaInFjord** [comment]
@empet What about bubble map?

**Comment by empet** [comment]
@APandaInFjord  The bubble map [https://plot.ly/python/bubble-maps/](https://plot.ly/python/bubble-maps/) contains a `scattergeo`-type trace.

**Comment by jonmmease** [comment]
Thanks for the information @empet!  @APandaInFjord, I'm going to close this now but feel free to continue the discussion in the forums at https://community.plot.ly/c/api/python if you have more questions on what's possible with ploty. Thanks!
