### ISSUE TITLE
Free or Prohibit when i use my own cloud system?

### ISSUE THREAD

**Issue by jsh1204** [plotly/plotly.py#1477]
Hi,  I’m student studying visualization.

I have a question about paid regulation.

Plotly is known as an open source library.

In addition, I know that plotting online in the cloud of the plotly is paid service for setting it private.

By the way, Is it free to use the library on my personal cloud system?

for example, I draw my graph using the library(offline mode). and upload My cloud system. Another person approaches my graph on my cloud system.

I will wait for answer.
Thank you!

**Comment by jonmmease** [comment]
Hi @jsh1204, plotly.py and plotly.js are [MIT licensed](https://opensource.org/licenses/MIT) so you can use it for whatever you want and you have full ownership of the resulting figures to do with whatever you want.  Hope that helps, and if you have more questions please direct them to the forums at https://community.plot.ly/c/api/python.  Thanks!

**Comment by jsh1204** [comment]
Thank U so much
