### ISSUE TITLE
Please upgrade plotly.py to 1.46 plotly js to use cyclic sankey

### ISSUE THREAD

**Issue by joetristano** [plotly/plotly.py#1490]
Please integrate the cyclic sankey from plotly.js into plotly.py

Thanks

**Comment by jonmmease** [comment]
Hi @joetristano, thanks for your interest in plotly.py.  The upgrate to plotly.js 1.46 should be coming in the next few days.  But circular Sankey support was added in plotly.js 1.45 (see https://github.com/plotly/plotly.js/blob/master/CHANGELOG.md#1450----2019-02-26), so it is available in plotly.py 3.7. 

Example: https://nbviewer.jupyter.org/github/jonmmease/plotly.py_release_notebooks/blob/master/notebooks/v3.7.0/sankey_updates.ipynb#Circular-links.

**Comment by jonmmease** [comment]
Upgraded to 1.47.1 in https://github.com/plotly/plotly.py/pull/1517

**Comment by joetristano** [comment]
Thanks @jonmmease I will take a look!

**Comment by joetristano** [comment]
Hi @jonmmease ,  I'm able to create a small cyclic chart but the page hangs on me for this dataset

[{'node': {'color': ['blue', 'blue', 'blue', 'blue', 'blue', 'blue', 'blue', 'blue', 'blue', 'blue', 'blue', 'blue', 'blue', 'blue', 'blue', 'blue', 'blue', 'blue', 'blue', 'blue', 'blue', 'blue', 'blue', 'blue', 'blue', 'blue', 'blue', 'blue', 'blue', 'blue', 'blue', 'blue', 'blue', 'blue', 'blue', 'blue', 'blue', 'blue', 'blue'], 'label': ['Manage', 'Connect', 'System', 'Create', 'Pats', 'MPID', 'EPD', 'Outp', 'Care', 'SearcForP', 'Dashboard', 'OL', 'SVM', 'Practs', 'IR', 'IL', 'GP', 'EDS', 'TM', 'CPUIDs', 'MCM', 'PP', 'GS', 'VPD', 'Direct', 'OD', 'Spec', 'CTD', 'CareD', 'PDM', 'CMM', 'PDTM', 'CM', 'R', 'EditP', 'IDM', 'MSV', 'OCs', 'ETD'], 'line': {'color': 'black', 'width': 0.5}, 'thickness': 20, 'pad': 15}, 'type': 'sankey', 'link': {'value': [74, 1, 19, 486, 55, 1, 32, 7, 15, 3, 20, 2, 1693, 3, 82, 61, 24, 1, 94, 59, 124, 1, 23, 122, 147, 407, 11, 1, 5, 1, 254, 32, 1, 95, 1, 5, 11, 1, 307, 96, 2385, 1, 2, 7, 806, 31, 1, 661, 129, 10564, 31, 454, 54, 1, 7, 2, 84, 5, 18, 17, 1, 44, 661, 15, 9, 8164, 109, 17, 1, 11, 27, 3, 5, 1, 4, 3, 561, 13, 459, 5, 16, 1, 44, 947, 6, 17, 7, 12, 53, 9, 2441, 5, 78, 39, 13, 302, 2, 2, 1098, 1, 20, 10, 13, 1394, 39, 6, 5, 23, 62, 7, 168, 80, 1, 1, 294, 6, 80, 1, 7, 5, 3, 133, 1, 1, 3, 9, 2, 444, 2, 2, 159, 77, 878, 2, 1, 4, 1, 2, 80, 116, 9, 31, 3, 10, 1, 31, 1, 21, 68, 2, 38, 2545, 23, 5, 470, 67, 2, 42, 1, 604, 1, 212, 4211, 3, 1, 6, 227, 15, 16, 14, 1, 18, 9144, 2, 2], 'source': [15, 36, 5, 10, 5, 18, 10, 18, 16, 28, 0, 10, 24, 26, 29, 29, 11, 18, 21, 26, 10, 10, 25, 28, 10, 16, 24, 17, 16, 10, 11, 13, 15, 0, 13, 18, 18, 16, 24, 25, 9, 26, 30, 24, 29, 36, 13, 35, 9, 29, 2, 9, 16, 5, 35, 24, 0, 13, 11, 24, 9, 24, 16, 35, 21, 0, 9, 0, 18, 9, 0, 25, 18, 26, 24, 26, 35, 9, 15, 13, 26, 13, 29, 0, 5, 15, 35, 36, 15, 36, 10, 17, 9, 36, 11, 9, 16, 25, 10, 2, 9, 11, 2, 15, 0, 26, 16, 35, 21, 5, 10, 10, 35, 13, 0, 36, 17, 14, 28, 9, 24, 16, 15, 36, 29, 0, 18, 10, 29, 0, 16, 9, 16, 5, 36, 15, 15, 36, 14, 29, 13, 15, 28, 0, 2, 36, 30, 24, 16, 29, 18, 0, 21, 17, 0, 10, 14, 16, 35, 10, 36, 15, 24, 10, 14, 2, 28, 24, 9, 9, 30, 11, 0, 21, 28], 'target': [29, 18, 9, 9, 29, 16, 21, 9, 11, 9, 5, 18, 0, 36, 5, 36, 9, 30, 21, 13, 28, 36, 11, 10, 29, 10, 10, 36, 28, 5, 10, 26, 36, 11, 21, 0, 36, 25, 9, 10, 9, 0, 29, 18, 9, 2, 9, 15, 16, 0, 26, 10, 35, 2, 16, 15, 9, 2, 29, 17, 30, 5, 0, 0, 35, 0, 15, 18, 15, 0, 28, 0, 5, 18, 16, 5, 10, 18, 35, 36, 2, 5, 18, 16, 36, 16, 9, 5, 0, 36, 0, 9, 11, 29, 16, 29, 36, 29, 15, 0, 28, 0, 36, 10, 25, 29, 14, 29, 16, 0, 11, 14, 36, 16, 35, 9, 29, 0, 29, 25, 30, 9, 5, 10, 30, 14, 10, 35, 10, 30, 29, 35, 16, 18, 0, 21, 18, 16, 10, 17, 29, 9, 16, 36, 21, 26, 5, 21, 21, 29, 29, 10, 10, 18, 15, 25, 16, 15, 21, 16, 15, 28, 29, 10, 29, 29, 15, 36, 5, 36, 9, 25, 29, 15, 0]}}]

It's spaghetti, yes, but I'm doing some exploratory work and wanted to map out processes through process of elimination with this data.

When I plug this straight into D3, it renders just fine but will not render in the browser through plotly
