### ISSUE TITLE
Feature Request: Support for more trace types in create_facet_grid

### ISSUE THREAD

**Issue by briangottfried** [plotly/plotly.py#1497]
Would be really nice to see support for violin or line types in [create_facet_grid](https://github.com/plotly/plotly.py/blob/master/plotly/figure_factory/_facet_grid.py#L601).

**Comment by nicolaskruchten** [comment]
Hi there! We've just released a new library called Plotly Express (https://plotly.express/) which is where we're continuing development of faceting features. It currently supports a few more trace types like contours and violins, and will eventually support all trace types.

Read more about it here if you like:  https://medium.com/@plotlygraphs/introducing-plotly-express-808df010143d

**Comment by jonmmease** [comment]
Hi @briangottfried, thanks for the suggestion. As @nicolaskruchten said, we're interested in pushing forward on this in `plotly_express` rather than in the current figure factory.  I'll close this here, but please check out plotly_express and open issues over there as you have requests/suggestions!

**Comment by briangottfried** [comment]
I checked out plotly_express and it is exactly what I am looking for! Thanks.
