### ISSUE TITLE
Orthographic projection does not seem to work with FigureWidget

### ISSUE THREAD

**Issue by aplowman** [plotly/plotly.py#1504]
Using the following code in a Jupyter notebook:

```
from plotly import __version__
from plotly import graph_objs as go
from plotly.offline import init_notebook_mode, iplot

init_notebook_mode()

print(__version__)

data = [
    {
        'type': 'scatter3d',
        'x': [0, 1, 2],
        'y': [0, 1, 2],
        'z': [0, 1, 2],
    },
]

layout = {
    'scene': {
        'camera': {
            'projection': {
                'type': 'orthographic',
            }
        }
    }
}

f = go.Figure(data=data, layout=layout)
iplot(f)

fw = go.FigureWidget(data=data, layout=layout)
fw
```

I get the following outputs (on version 3.7.1):

`iplot` output (correct):
![iplot_output](https://user-images.githubusercontent.com/5176471/55800202-0e857900-5acb-11e9-9ea6-ca6298aa048a.png)

`FigureWidget` output (incorrect):
![figure_widget_ouput](https://user-images.githubusercontent.com/5176471/55800201-0e857900-5acb-11e9-86d2-5c21cf93ec5c.png)

So the `FigureWidget` does not seem to respect the projection property.

**Comment by jonmmease** [comment]
Hi @aplowman, thanks for the report!

I just did a quick check on plotly.py version 3.7.1 and the orthographic projection seems to be working for me with `FigureWidget`.  I'm thinking there might be a version mismatch going on somehow.  Are you using the classic notebook or JupyterLab?

If classic notebook. what is the output of `$ jupyter nbextension list`
If JupyterLab, what is the output of `$ jupyter labextension list`

Also, if you're using conda, please check the ouput of `$ pip list` and `$ conda list` to make sure that there aren't multiple versions of the `plotly` package installed.

**Comment by aplowman** [comment]
Hmm, I realise this is a different problem, which is, like you say, some sort of version mismatch. I have experienced this before: I have multiple conda environments, some of which cannot import FigureWidget, despite also reporting a Plotly version of at least 3.0. For some reason, my test notebook is now working with FigureWidget (I don't know what's changed, sorry!). Perhaps it is a conda issue.

FYI, output of `jupyter nbextension list`:
```
  config dir: C:\Users\adamj\.jupyter\nbconfig
    notebook section
      plotlywidget/extension enabled
      - Validating: ok
      codefolding/main enabled
      - Validating: ok
      scratchpad/main enabled
      - Validating: ok
      toc2/main enabled
      - Validating: ok
      collapsible_headings/main enabled
      - Validating: ok
      hide_input_all/main enabled
      - Validating: ok
  config dir: C:\code_local\anaconda\etc\jupyter\nbconfig
    notebook section
      plotlywidget/extension enabled
      - Validating: ok
      jupyter-js-widgets/extension enabled
      - Validating: ok
      nbextensions_configurator/config_menu/main enabled
      - Validating: problems found:
        - require?  X nbextensions_configurator/config_menu/main
      contrib_nbextensions_help_item/main enabled
      - Validating: ok
    tree section
      nbextensions_configurator/tree_tab/main enabled
      - Validating: problems found:
        - require?  X nbextensions_configurator/tree_tab/main
```
`conda list` reports one plotly (3.7.1) installed via PyPI. `pip list` also reports one plotly (3.7.1).

So I don't mind if you close this issue. (I have found another issue with orthographic projection though: zooming does not appear to work correctly, I'll open another issue!)

**Comment by jonmmease** [comment]
Ok, thanks for the update!
