### ISSUE TITLE
Integrate plotly_express

### ISSUE THREAD

**Issue by jonmmease** [plotly/plotly.py#1507]
Integrate the `ploty_express` library (https://medium.com/@plotlygraphs/introducing-plotly-express-808df010143d) into plotly.py for version  4. 

We'll have to look at the package structure a little more closely, but as a starting point
`plotly_express` will become `plotly.express`.  We should either keep the submodules of `plotly_express` where they are, or move them and keep aliases so that folks can migrate to plotly.py v4 by only changing the single import.

**Comment by jonmmease** [comment]
For version 3.10, let's make `plotly_express` available as `plotly.express`.

Then for v4, actually move the `plotly_express` codebase into the plotly.py repo.

**Comment by nicolaskruchten** [comment]
works for me. As an optional download or as a direct dependency? either would work for me :)

**Comment by jonmmease** [comment]
Optional, I don't think we should change required dependency structure before version 4.

**Comment by nicolaskruchten** [comment]
ah right, PX isn't actually that light due to statsmodels and pandas?

**Comment by jonmmease** [comment]
Done in the v4_integration branch and v4.0.0a2 release.  it would be great to add some tests, but all the functionality in `plotly_express` is now available as `plotly.express`.
