### ISSUE TITLE
Issue with zooming when projection is set to orthographic

### ISSUE THREAD

**Issue by aplowman** [plotly/plotly.py#1513]
Using the following code in a Jupyter notebook:

```
from plotly import __version__
from plotly import graph_objs as go

print('version: ', __version__)

data = [
    {
        'type': 'scatter3d',
        'x': [0, 1, 2],
        'y': [0, 1, 2],
        'z': [0, 1, 2],
    },
]

layout = {
    'scene': {
        'camera': {
            'projection': {
                'type': 'orthographic',
            }
        }
    },
}

fw = go.FigureWidget(data=data, layout=layout)
fw
```

`version:  3.7.1`

The resulting FigureWidget does not seem to zoom properly, as can be seen in the below GIF. When `projection` is set to `perspective`, there is no problem with zooming.

![plotly_fw_orthographic_projection_problem](https://user-images.githubusercontent.com/5176471/55917121-3b7a7e80-5be6-11e9-9207-54085a8bfee6.gif)

EDIT: to be more specific, it seems like when using orthographic projection, we can't zoom out from the original camera position. See the below GIF, where I start with perspective projection (where I can zoom out) and then switch to orthographic projection (where I can't zoom out beyond the original level). It could be possible I am misunderstanding something about orthographic projection however.

![plotly_fw_orthographic_projection_problem_2](https://user-images.githubusercontent.com/5176471/55946864-57613d00-5c45-11e9-86c3-c73712d5287b.gif)

**Comment by marcotama** [comment]
I think this was [reported and fixed upstream](https://github.com/plotly/plotly.js/pull/3601), in the Javascript implementation, a few weeks ago and the changes have just now [made their way downstream](https://github.com/plotly/plotly.py/blob/master/CHANGELOG.md), in `plotly 3.8.0`.

**Comment by jonmmease** [comment]
Thanks @marcotama. @aplowman can you confirm whether the upgrade to 3.8.0 takes care of the issue for you?

**Comment by aplowman** [comment]
Yes, verion 3.8.0 has done the trick! Thanks both.

**Comment by emmanuelle** [comment]
can this issue be closed? I think so

**Comment by aplowman** [comment]
Yes.
