### ISSUE TITLE
HTML plotly graphs with output_type="div" are visible in JupyterLab, but blank space in Jupyter Notebook

### ISSUE THREAD

**Issue by manycoding** [plotly/plotly.py#1522]
I noticed that graphs printed as `display(HTML(plot([{"x": [1, 2, 3], "y": [3, 1, 6]}], include_plotlyjs=True, output_type="div")))` are not visible in Notebook, only in JupyterLab.
I print them as a work around #1516 issue.

All examples are in the attached notebook, a minimal would be:

```
from IPython.display import display, HTML
import plotly.graph_objs as go
from plotly.offline import plot, iplot, init_notebook_mode
init_notebook_mode(connected=False)

display(HTML(plot([{"x": [1, 2, 3], "y": [3, 1, 6]}], include_plotlyjs=True, output_type="div")))
```

plotly 3.7.1
notebook 5.7.8

[plotly figure html.ipynb.zip](https://github.com/plotly/plotly.py/files/3081267/plotly.figure.html.ipynb.zip)

**Comment by jonmmease** [comment]
Hi @manycoding,

This approach isn't expected to work in the notebook (I'm honestly surprised that it works in JupyterLab). `plotly.offline.iplot` is specifically designed to display figures in the classic notebook.

You may be interested in checking out the renderers PR (https://github.com/plotly/plotly.py/pull/1474) that was merged in for 3.8.0.  As it introduces a bunch of new options for displaying figures in different contexts.
