### ISSUE TITLE
Plotly Offline 3D Surface Plots: Customize the x & y tickvals/ticktext AND ensure readability of the axis labels

### ISSUE THREAD

**Issue by jhthompson12** [plotly/plotly.py#1533]
Hello Plotly People,

Firstly, thank you very much for developing this incredible tool. You are all amazing. And apologies in advance if I did not submit this properly, this is my first time ever submitting a feature request. 

This post is in response to a question I recently asked in detail on the Plotly forum [found here](https://github.com/plotly/plotly.py/blob/master/CHANGELOG.md). 

In essence, when creating a surface plot, I would like to specify the values that are presented on the x and y axes AND set the maximum number of my custom axis tick mark values that will be displayed. At the moment, I can set the custom values with tickvals/ticktext, but the axis shows all of the ticktext that I provide. The nticks parameter almost provides the functionality that I'm looking for, but it doesn't seem to work with custom axis markers (nticks can only be used when tickmode = ‘auto’)

The following image shows how with a lot of tickvals/ticktext, the axis becomes unreadable. 

![](https://discourse-cdn-sjc2.com/standard17/uploads/plot/original/2X/4/4d38caeb3889e73328a9281277539c0db5615c1b.png)

Thank you for looking into this and please let me know if I need to provide any more information. 

-Joe

**Comment by jonmmease** [comment]
Hi @jhthompson12, that for taking the time to write this up. Could you move this issue to the Plotly.js repository (https://github.com/plotly/plotly.js/issues)?  And changes in this behavior would have to flow through Plotly.js and then would be automatically available in plotly.py.  Thanks!

**Comment by jhthompson12** [comment]
Thanks for the guidance, @jonmmease. Just moved it over to plotly.js. I will close this issue in plotly.py out.

**Comment by jhthompson12** [comment]
This issue has been moved over to [plotly.js as issue 3822](https://github.com/plotly/plotly.js/issues/3822#issue-438887081)
