### ISSUE TITLE
Pattern filled bar plots

### ISSUE THREAD

**Issue by djstrong** [plotly/plotly.py#1538]
Feature request: pattern filled bar plots - mainly for grey scale printing.
E.g. https://matplotlib.org/examples/pylab_examples/hatch_demo.html

**Comment by jonmmease** [comment]
Hi @djstrong, thanks for the request.  I agree this would be a nice thing to have.

I'm going to move this to the Plotly.js repository since that's where a change like this would need to take place.  See https://github.com/plotly/plotly.js/issues/3815.

**Comment by ploner** [comment]
Would also love to see this feature. I used it quite often in **R**, since _R base plot_ includes this option for decades.

**Comment by nicolaskruchten** [comment]
We'd also love to see this feature happen but we would need sponsorship to get it implemented in Plotly.js... see details in https://github.com/plotly/plotly.js/issues/3815

**Comment by HadiJahanshahi** [comment]
Any news? Hatch patterns are necessary.

**Comment by nicolaskruchten** [comment]
This feature just came out in v5.0 :) https://community.plotly.com/t/introducing-plotly-py-5-0-0-a-new-federated-jupyter-extension-icicle-charts-and-bar-chart-patterns/54039
