### ISSUE TITLE
hovermode=False; allow user to revert to the assigned hovermode after clicking on compare or closest

### ISSUE THREAD

**Issue by AlexC84** [plotly/plotly.py#1545]
The user/viewer of a plot is currently unable to revert back to the assigned `hovermode` for the plot if it is set to `False` in the `layout`. The plot will load with hovermode initially set to `False` but as soon as the user clicks on 'Show closest data on hover' or 'Compare data on hover' they can't turn hovermode back off without reloading the plot.

```py
import plotly.offline as off
import plotly.graph_objs as go

x0 = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
x1 = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
y0 = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

trace0 = {
    'type': 'scatter',
    'name': 'trace0',
    'x': x0,
    'y': y0
}

trace1 = {
    'type': 'scatter',
    'name': 'trace1',
    'x': x1,
    'y': y0
}

data = [trace0, trace1]
layout = {'hovermode': False}
fig = {'data': data, 'layout': layout}
off.plot(fig)
```

**Comment by AlexC84** [comment]
the same is true if the `hovermode` is set to `'y'` in the `layout`; as soon as the user clicks on 'Show closest data on hover' or 'Compare data on hover' the user can't revert to the assigned hovermode and they're stuck with either `'hovermode':'closest'` or `'hovermode':'x'`

**Comment by jonmmease** [comment]
Thanks for raising the issue @AlexC84, Moving this to https://github.com/plotly/plotly.js/issues/3832 so that we can discuss with the Plotly.js team.
