### ISSUE TITLE
Streamplot examples for adding scatter plot data to graph does not work

### ISSUE THREAD

**Issue by TakodaS** [plotly/plotly.py#1555]
The  [streamline and source point](https://plot.ly/python/streamline-plots/) example given does not work because the line `fig['data'].append(source_point)` throws an error message saying you can't append to a tuple. I There is an easy workaround:
```
new_data = [*fig['data'],source_point]
py.iplot(new_data, filename='streamline_source')
```

But as of now you are not able to append new data to an existing figure, which makes the example shown and the example in the create_streamline docstring fail to compile and I think this should be fixed.

**Comment by jonmmease** [comment]
Thanks for letting us know @TakodaS.  Moving this to the documentation repo at https://github.com/plotly/documentation/issues/1333.
