### ISSUE TITLE
template height not respected with offline.iplot?

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.py#1560]
If I render a figure with `layout.template.height=800`, the final figure seems to render with a height of 525.

**Comment by jonmmease** [comment]
Yeah, there are places in the code that add default width/height behavior if the these aren't specified.

For example:
https://github.com/plotly/plotly.py/blob/6a85e4b7b6510d58d6f4525de179a45339aa297c/plotly/io/_html.py#L159-L161

But, we should track down and update all of these to also check `fig.layout.template.layout.width`/`height`.
