### ISSUE TITLE
Auto-save HTML chart file in the project directory

### ISSUE THREAD

**Issue by abhi3700** [plotly/plotly.py#1563]
I am using Excel with Python.

For this, I have used xlwings package.

Now, my code is written in a .py file for an Excel file.
So, when I run the code, the plotly chart opens in Browser.

This is fine!..

But, it saves the .html file in "C:\Users\Abhi\Documents\" directory.

I want html file to be auto-saved in project directory.

How to do this?

Anyone please.

**Comment by jonmmease** [comment]
Hi @abhi3700,
The easiest way to write a figure to an HTML file is currently the `plotly.io.write_html` function.  If you'd like more help working through things, please start a thread on the forums at https://community.plot.ly/c/api/python.  Thanks!
