### ISSUE TITLE
Implement of  force-directed-graph of d3

### ISSUE THREAD

**Issue by 444thLiao** [plotly/plotly.py#1567]
Sorry for my disturb...

I just want to ask if any plan to implement a force-directed-graph of d3 inside the plotly??

If I want to implement it by myself, I want to know where and how to find js code at python library of plotly. 

Here is the force-directed-graph of d3.
https://observablehq.com/@d3/force-directed-graph

The main purpose of this implement is to improve the network layout when too many point was shown...

**Comment by jonmmease** [comment]
Hi @444thLiao, thanks for the suggestion.  This is something that would need to be implemented in the JavaScript layer.  Could you move this issue to https://github.com/plotly/plotly.js/issues?  Thanks!
