### ISSUE TITLE
Heatmap coloring disappears when resizing notebook window

### ISSUE THREAD

**Issue by devnoname120** [plotly/plotly.py#1573]
![plotly_heatmap_resize](https://user-images.githubusercontent.com/2824100/58238095-e1bdb600-7d46-11e9-8063-c80b16b71550.gif)

```python
import numpy as np
import plotly.graph_objs as go
from plotly.offline import init_notebook_mode, iplot

init_notebook_mode(connected=True)

x = np.random.randn(2000)
y = np.random.randn(2000)
iplot([go.Histogram2dContour(x=x, y=y, contours=dict(coloring='heatmap'))], show_link=False)
```

How to reproduce:
- Open a Jupyter notebook, and paste the code above.
- Run the notebook.
- Resize the browser window.

Information:
- **Python 3.6.0**.
- **Plotly 3.8.1** installed using conda.
- Reproduced on both **Firefox 66.0.5 (64-bit)** and **Chromium 73.0.3683.86**.

Extra information:
```
noname@noname-pc:~$ conda list | grep -iE 'jupy|ipyt'
ipython                   7.4.0                    pypi_0    pypi
ipython-genutils          0.2.0                    pypi_0    pypi
ipython_genutils          0.2.0                    py36_0  
jupyter_client            5.2.4                    py36_0  
jupyter_core              4.4.0                    py36_0  
```

**Comment by jonmmease** [comment]
Thanks for taking the time to make this thorough report @devnoname120, I was able to reproduce this directly in plotly.js, so I'm going to move the issue over there at https://github.com/plotly/plotly.js/issues/3894.  Thanks!
