### ISSUE TITLE
PLotly to Matplotlib

### ISSUE THREAD

**Issue by pablolmiranda** [plotly/plotly.py#1575]
I tried to search online and didn't find any reference on how to convert a Plotly Figure to a Matplotlib figure.
Is it possible? If so, there is any documentation available about it?

**Comment by jonmmease** [comment]
Hi @pablolmiranda.  No, that's not something that's possible with plotly.py, or with any library that I'm aware of.  I'm going to close this since I don't think this is in scope for plotly.py.  Thanks for bringing up the question though.
