### ISSUE TITLE
FF.create_trisurf can not relabel the x or y-axis

### ISSUE THREAD

**Issue by 100518832** [plotly/plotly.py#1591]
Can not change the layout object of the FF.create_trisurf figure to adjust the x or y-axis tick labels, or values. Will it be possible to add the functionality in the future to adjust the labels of the ticks on the x or y-axis for the trisurf figures created with figure factory.

**Comment by empet** [comment]
@100518832   To update `fig.layout` just print it, and then perform the necessary changes.
Example:
`fig.layout.scene.xaxis.title='a'`

`FF.create_trisurf` is the oldest method to define trisurfs with Plotly. You can have much more control on both the trace definition and layout if you define the trisurf as a `Mesh3d` instance, like in this notebook:
[https://plot.ly/~empet/14742](https://plot.ly/~empet/14742).
