### ISSUE TITLE
figure_factory.create_table['data'] is a tuple, why ? 

### ISSUE THREAD

**Issue by shinycarl** [plotly/plotly.py#1593]
`import plotly as py
import plotly.graph_objs as go
import plotly.figure_factory as FF

# ----------pre def
pyplt = py.offline.plot

table_data = [['team', 'win', 'lose', 'tie'],
              ['A', 18, 4, 0],
              ['B', 18, 5, 0],
              ['C', 16, 5, 0],
              ['D', 13, 8, 0],
              ['E', 13, 8, 0],
              ['F', 13, 8, 0]]

figure = FF.create_table(table_data, height_constant=60)

print("type of figure['data']:",type(figure['data']))
print(figure)`

result:
type of figure['data']: <class 'tuple'>
Figure({
    'data': [{'colorscale': [[0, '#00083e'], [0.5, '#ededee'], [1, '#ffffff']],
              'hoverinfo': 'none',
              'opacity': 0.75,
              'showscale': False,
              'type': 'heatmap',
              'uid': '00597e27-0114-4b33-b674-66dcbc106523',
              'z': [[0, 0, 0, 0], [0.5, 0.5, 0.5, 0.5], [1, 1, 1, 1], [0.5, 0.5,
                    0.5, 0.5], [1, 1, 1, 1], [0.5, 0.5, 0.5, 0.5], [1, 1, 1, 1]]}],
             ........

how can I make a combine of tables and lines ?
help!

**Comment by jonmmease** [comment]
Hi @shinycarl,

Are you wanting to add additional traces to the figure returned by `create_table`?  If so, you can do this using the `fig.add_trace`/`fig.add_traces` methods.  If you have other usage questions, please start a new thread on the forums at https://community.plot.ly/c/api/python. Thanks!

**Comment by shinycarl** [comment]
I’ll have a try.
Thank you.
