### ISSUE TITLE
How to set height in plotly make_subplots?

### ISSUE THREAD

**Issue by eromoe** [plotly/plotly.py#1596]
I follow https://plot.ly/pandas/subplots/ 

I have a dataframe with 10 group , each group has 845 point by hour from 2019-01-01 to 2019-06-03 .

My code: 
```
    import plotly.plotly as py
    import plotly.tools as tls
    
    from plotly.offline import iplot,init_notebook_mode
    
    import cufflinks as cf
    cf.go_offline(connected=True)
    
    sids = pdf.store_id.unique()
    fig = tls.make_subplots(rows=len(sids), cols=1, shared_xaxes=True)
    for sid in sids:
        td = pdf[pdf.store_id==sid]
        fig.append_trace({'x': td['date'], 'y': td['sale_count'], 'type': 'scatter', 'name': sid }, 1, 1)
    
    iplot(fig, filename='pandas/mixed-type subplots')
```
Result plot is ugly : 

[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/RhS3S.png

I'd lile see the lines expand whole space in yaxis, and move right to see hidden line in xaxis.

I don't find a `height` parameter in `tls.make_subplots` . 
How do I set the height for this plot ?

**Comment by yoyocheng-nft** [comment]
fig = tls.make_subplots(rows=len(sids), cols=1, row_heights=[,0.4], shared_xaxes=True)
you could use row_heights to adjust heights
