### ISSUE TITLE
Bars at edge cut off when xaxis range is set

### ISSUE THREAD

**Issue by GabrielPereyra** [plotly/plotly.py#1603]
`plotly==3.10.0`

```python
from plotly.offline import plot

plot({
    'data': [{
        'x': range(10),
        'y': range(10),
        'type': 'bar',
    }],
    'layout': {
        'xaxis': {
            'range': [0, 9]
        },
    }
})
```

When I plot this, the bar at `x = 9` is only half visible. Changing margins didn't help and I couldn't find a simple fix in the docs. A hacky solution would be to extend the range but I feel like there is a better solution that I'm missing. Let me know what I missed and if not, it seems like by default border bars shouldn't be cut off.

**Comment by jonmmease** [comment]
Hi @GabrielPereyra,

Since bars are centered on their respective values, this is the expected behavior.  Extending the range is the right solution.
