### ISSUE TITLE
re: autorange='reversed' in scatter3d

### ISSUE THREAD

**Issue by deliciouslytyped** [plotly/plotly.py#1605]
Does this work now? I have plotly 4.8.0 and it doesn't seem to do anything.

https://github.com/plotly/plotly.py/issues/803

**Comment by nicolaskruchten** [comment]
From the version number you mentioned, it seems like you're using plotly in R, but this repository is for the Python version (where the highest version number is 3.10.0 today ;) 

The latest version in CRAN for plotly for R is 4.9.0 IIRC, so if upgrading to that version doesn't fix your issue, I suggest creating an issue in the R repo here: https://github.com/ropensci/plotly

**Comment by deliciouslytyped** [comment]
I seem to have opened two issues by mistake https://github.com/ropensci/plotly/issues/1547, not really sure what happened here.
