### ISSUE TITLE
go.Figure should accept a scalar trace as data

### ISSUE THREAD

**Issue by emmanuelle** [plotly/plotly.py#1611]
For the case of a single trace in a figure, it would be very convenient if `go.Figure` could take a scalar trace as data parameter and not only a tuple or a list. For example at the moment you have to write
```
fig = go.Figure(data=[go.Scatter(...)])
```
It would be nice to be able to to 
```
fig = go.Figure(data=go.Scatter(...))
```

**Comment by jonmmease** [comment]
Done in the v4_integration branch and v4.0.0a2 release.
