### ISSUE TITLE
Blank plot in jupyter lab in offline mode inside docker container 

### ISSUE THREAD

**Issue by samueljackson92** [plotly/plotly.py#1640]
Hi. I'm trying to use plotly in a docker container with jupyter lab. When I attempt to plot in offline mode I get the following error message:

![Screenshot from 2019-06-28 09-33-02](https://user-images.githubusercontent.com/2487781/60329196-c79b7700-9987-11e9-9b27-df2c873399bc.png)
 
I've followed the installation instructions and advice in similar issues to make sure that the correct jupyter lab extensions are installed to the container. My `Dockerfile` currently looks like this:

```docker
FROM python:3.7

EXPOSE 8888

RUN curl -sL https://deb.nodesource.com/setup_12.x | bash - \
    && apt-get install -y nodejs

RUN pip install plotly==3.10.0 jupyterlab==0.35 ipywidgets>=7.2

RUN export NODE_OPTIONS=--max-old-space-size=4096 \
    && jupyter labextension install @jupyter-widgets/jupyterlab-manager@0.38 --no-build \
    && jupyter labextension install plotlywidget@0.11.0 --no-build \
    && jupyter labextension install @jupyterlab/plotly-extension@0.18.2 --no-build \
    && jupyter lab build

VOLUME /work /data
``` 
The code I'm using to test plotting is as follows:

```python
from plotly.offline import init_notebook_mode, iplot
from plotly.graph_objs import Scatter

init_notebook_mode(connected=True)

iplot([Scatter(x=[1, 2, 3], y=[3, 1, 6])])
```

Any ideas? Thanks.

**Comment by pvanliefland** [comment]
@samueljackson92 did you figure it out? I'm stuck on the same issue...

**Comment by samueljackson92** [comment]
@pvanliefland It was really dumb: I forgot to refresh the jupyter lab page after I restarted the docker container. I think doing so pulled in the new javascript library requirements installed by `plotlywidget`/`ploty-extension`.

**Comment by pvanliefland** [comment]
Wow, worked for me as well. Thanks a lot, somehow I didn't think of this at all!
