### ISSUE TITLE
Expose parallelLimit for orca image exports

### ISSUE THREAD

**Issue by rskabelund** [plotly/plotly.py#1655]
Interested in parallel processing images of plots using orca.

I found in the js version they have the setting parallelLimit:
https://github.com/plotly/orca/blob/master/src/app/runner/coerce-opts.js#L20

Would we be able to expose that to the python library with the desired result to be parallel processing?
or
Please explain how best to call .to_image() for 500+ figures efficiently.

**Comment by jonmmease** [comment]
Hi @rskabelund,  It looks like this option only applies to the `orca graph` batch mode for using orca, not to the `orca serve` mode that plotly.py uses.

Plotly.py runs orca in a separate server process and then sends image export requests to that local server process.  This server process should be able to handle parallelizing multiple simultaneous requests, so you might be able to use `plotly.io.orca.ensure_server()` to start the orca server from the main Python process, and then use multiprocessing (https://docs.python.org/3/library/multiprocessing.html) to send multiple export requests to the server at the same time.

If you give it a try, please let us know what you find out!

**Comment by rskabelund** [comment]
switched to kaleido and have not looked back...
