### ISSUE TITLE
plotly.plotly import error message

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.py#1660]
Should have caught this before RC1, sorry... This message:

![image](https://user-images.githubusercontent.com/203523/60894345-7d8c7e00-a230-11e9-8e5a-8a625b37118b.png)

I think should provide a little more context and say something like:

```
The plotly.plotly module is deprecated.
To create figures using the Chart Studio service, please install the chart-studio package and use the chart_studio.plotly module instead. 
To create and display figures locally, please use the plotly.offline module which is based on the new version 4 rendering framework.
```

Basically give people more information and a stronger hint about using offline (which is arguably the smallest change to their code that lets them get on with their day)

**Comment by JobCollins** [comment]
I also have the same issue on Jupyter 5.7.8 . I downloaded the latest version of Anaconda and ran a notebook shared from my other computer [does not use current version of Anaconda] where it worked fine.

**Comment by jonmmease** [comment]
Hi @JobCollins, when using `plotly` version 4 (released two days ago) and error message here is the expected behavior. See https://plot.ly/python/v4-migration/ for the version 4 migration guide, or downgrade your plotly version to 3.10.

This issue is concerned with adding more information to the error message.

**Comment by JobCollins** [comment]
Sorry, I did not realize that.

I downgraded and it works fine. Thanks

**Comment by zShores** [comment]
So I have come into the same issue - whereby the program I am using utilises pre-update plotly.plotly. I have attempted to update the code in the program to use the new chart_studio.plotly, however I am getting the same following error:

`>>> plotESD_interactive(family)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\User\AppData\Local\conda\conda\envs\Aesop\lib\site-packages\aesop\aesop.py", line 4881, in plotESD_interactive
    import chart_studio.plotly as py
  File "C:\Users\User\AppData\Local\conda\conda\envs\Aesop\lib\site-packages\plotly\plotly\__init__.py", line 4, in <module>
    _chart_studio_error("plotly")
  File "C:\Users\User\AppData\Local\conda\conda\envs\Aesop\lib\site-packages\_plotly_future_\__init__.py", line 49, in _chart_studio_error
    submodule=submodule
ImportError:
The plotly.plotly module is deprecated,
please install the chart-studio package and use the
chart_studio.plotly module instead.`

**Comment by jonmmease** [comment]
Hi @zShores, thanks for letting us know.  The stack trace you're getting is a bit confusing as it looks like `import chart_studio.plotly as py` is resulting in the import of `plotly.plotly`, which shouldn't be happening.  Could you try fully uninstalling and reinstalling the `plotly` and `chart-studio` packages to see if that makes a difference?

```
$ pip uninstall plotly
$ conda uninstall plotly
$ pip uninstall chart-studio
$ conda uninstall chart-studio
$ conda install -c plotly plotly chart-studio
```

**Comment by sousablde** [comment]
> Hi @zShores, thanks for letting us know. The stack trace you're getting is a bit confusing as it looks like `import chart_studio.plotly as py` is resulting in the import of `plotly.plotly`, which shouldn't be happening. Could you try fully uninstalling and reinstalling the `plotly` and `chart-studio` packages to see if that makes a difference?
> 
> ```
> $ pip uninstall plotly
> $ conda uninstall plotly
> $ pip uninstall chart-studio
> $ conda uninstall chart-studio
> $ conda install -c plotly plotly chart-studio
> ```

Hello Jonmease, I have the exact same issue described here and I attempted your solution but unfortunately it does not seem to be working for me.

Do you have any other suggestion for something I can try?
I accidentally updated plotly, which started causing issues and so far attempting to revert it back did not fix it.
Best B

**Comment by anki-code** [comment]
@jonmmease I have fresh installation of plotly and I've got the same error. I've tried to repeat "Pandas Basic Line Plot" (https://plot.ly/pandas/line-charts/) and I've got:
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-5ca56d58b308> in <module>
----> 1 import plotly.plotly as py
      2 import plotly.graph_objs as go
      3 
      4 import pandas as pd
      5 import numpy as np

/opt/miniconda/lib/python3.7/site-packages/plotly/plotly/__init__.py in <module>
      2 from _plotly_future_ import _chart_studio_error
      3 
----> 4 _chart_studio_error("plotly")

/opt/miniconda/lib/python3.7/site-packages/_plotly_future_/__init__.py in _chart_studio_error(submodule)
     47 chart_studio.{submodule} module instead.
     48 """.format(
---> 49             submodule=submodule
     50         )
     51     )

ImportError: 
The plotly.plotly module is deprecated,
please install the chart-studio package and use the
chart_studio.plotly module instead. 
```

**Comment by JobCollins** [comment]
@anki-code here is what worked for me:
Downgraded from the latest plotly version
`pip install plotly==3.10.0`

**Comment by anki-code** [comment]
@JobCollins after downgrade to `3.10.0` I've got:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-44cc9d35eca1> in <module>
     21 # py.iplot(data, filename='pandas/basic-line-plot')
     22 
---> 23 url = py.plot(data, filename='pandas/basic-line-plot')

AttributeError: module 'plotly.plotly' has no attribute 'plot'
```

**Comment by jonmmease** [comment]
Hi @anki-code, the documentation page you linked to (https://plot.ly/pandas/line-charts/) is written for version 3 only (See purple text box at the top). So downgrading to version 3 is what you would need to do to follow this example.

The error you're getting indicates that there's something corrupt in the installation.  Try uninstalling and reinstalling the `plotly` package. Or better yet, create a new virtual environment.

**Comment by vaibhavai** [comment]
$ pip install chart_studio 
After successful installation 
Run it
from chart_studio.plotly import iplot
![chart_studio plotly Runs](https://user-images.githubusercontent.com/44393485/62606830-a335a180-b91a-11e9-867d-070e8fe56d89.png)

**Comment by erdemalpkaya** [comment]
As one of Plotly fan, I am not happy at all.

**Comment by jonmmease** [comment]
@vaibhavai, The import of `plotly.plotly` (as in your screenshot) is intended to raise that exception.  Are you saying you also see the exception when importing `chart_studio.plotly`?

**Comment by nonoumasy** [comment]
what a mess

**Comment by haribanshagrawal** [comment]
thanks @JobCollins 
it worked for me

**Comment by abhi526691** [comment]
Is this installation work for offline mode

**Comment by haribanshagrawal** [comment]
It will
But for downloadung the package you will need internet

**Comment by abhi526691** [comment]
I have net connection and I have installed all the dependencies then also it's not working

**Comment by yasosheikh** [comment]
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-6-c964da380f12> in <module>()
     34 import os
     35 
---> 36 from plotly import plotly
     37 import plotly.offline as offline
     38 import plotly.graph_objs as go

C:\Anaconda3\lib\site-packages\plotly\plotly\__init__.py in <module>()
      2 from _plotly_future_ import _chart_studio_error
      3 
----> 4 _chart_studio_error("plotly")

C:\Anaconda3\lib\site-packages\_plotly_future_\__init__.py in _chart_studio_error(submodule)
     47 chart_studio.{submodule} module instead.
     48 """.format(
---> 49             submodule=submodule
     50         )
     51     )

ImportError: 
The plotly.plotly module is deprecated,
please install the chart-studio package and use the
chart_studio.plotly module instead.

**Comment by Zaid0** [comment]
guys try this it worked for me

`pip uninstall cufflinks
pip install plotly == 3.10.0
`

**Comment by nicolaskruchten** [comment]
@Zaid0 this is no longer necessary: if you install `cufflinks` version 0.17 it's compatible with `plotly` 4.2+

**Comment by Zaid0** [comment]
oh nice thank you for this information

**Comment by feliperoque** [comment]
works with me when i downgrade the plotly version from 4.1 to 3.10.0

**Comment by nicolaskruchten** [comment]
@feliperoque are you not able to make things work with `cufflinks` 0.17 and `plotly` 4.2, or is something keeping you on `cufflinks` 0.16 ?

**Comment by feliperoque** [comment]
there isn't any thing to keep me with cufflinks 0.16 but i don't know what is happening with cufflinks and plotly at the jupyter lab. I tryed soo many thins but none of them works...

**Comment by nicolaskruchten** [comment]
OK. This issue is starting to be full of "me too" and it's not possible for me to keep track of who is having what issue, so I'm going to lock it now. If you're having problems, please check out our new [Troubleshooting guide](https://plot.ly/python/troubleshooting/) and if that doesn't help you sort things out, please [create a new issue](https://github.com/plotly/plotly.py/issues/new) describing your specific problem and we'll try to help!
