### ISSUE TITLE
Plotly with ipywigets 7.5 fails on Jupyterlab installation

### ISSUE THREAD

**Issue by LuisFRoch** [plotly/plotly.py#1662]
Hi,

The installation of "plotly==4.0.0rc1" went fine, however following the Jupyterlab update ([https://plot.ly/python/next/getting-started/]), lead me to the challenge below were "current_repodata.json " fails to resolve the environment, and "repodata.json Solving environment" runs endlessly it seems (i killed it after 8mins). Any ideas on how i can get over this issue to start testing backwards compatibility?

Thanks!

    'plotly                      pkgs/main::plotly-3.10.0-py_0 --> plotly/label/test::plotly-4.0.0rc1-py_0

    Proceed ([y]/n)? y

    Downloading and Extracting Packages
    plotly-4.0.0rc1      | 3.8 MB    | ##################################### | 100% 
    Preparing transaction: done
    Verifying transaction: done
    Executing transaction: done
    (base) User-mbp-2:~ User$ conda install -c defaults -c conda-forge jupyterlab=1.0 
    "ipywidgets>=7.5"
    Collecting package metadata (current_repodata.json): done
    **Solving environment: failed**
    Collecting package metadata (repodata.json): done
    **Solving environment: -** `

**Comment by jonmmease** [comment]
Hi @LuisFRoch ,

Hmm, I'm not sure what might be going on here.  The resolution works for me in a fresh environment on MacOS using conda version 4.7.5.  Have you tried this in a fresh conda environment?

**Comment by LuisFRoch** [comment]
Hi @jonmmease,

The solution was uninstalling and re-installing conda, jupyter and widgets.
It seems order -and for sure versioning of packages- makes a big difference before running _jupyter lab build_. Also, if there's a file-trace of some sort it creates issues even with a fresh install (at least in my experience or maybe i just suck =) ). In summary removed every single anaconda and jupyter related files, clean install plus creation of separate environments.


`> Hi @LuisFRoch ,
   Hmm, I'm not sure what might be going on here. The resolution works for me in a fresh 
   environment on MacOS using conda version 4.7.5. Have you tried this in a fresh conda 
   environment?`

**Comment by jonmmease** [comment]
Thanks for reporting back @LuisFRoch, there are a lot of moving parts unfortunately. Glad you got it working!
