### ISSUE TITLE
Wrong link to Version 4 announcement in CHANGELOG.MD

### ISSUE THREAD

**Issue by SaskiaKeil** [plotly/plotly.py#1669]
Hey everyone,

the link to the version 4 announcement is not working in CHANGELOG.MD.
It seems it contains a placeholder `version 4 announcement`, but as it doesn't exist you are forwarded to `https://github.com/plotly/plotly.py/blob/master`.

I don't know if the announcement already exists somewhere, this is why I can't create a PR myself.

**Comment by jonmmease** [comment]
Thanks @SaskiaKeil, fixed in https://github.com/plotly/plotly.py/commit/c576adf6e89354eef02a0311702c67e0ed178474.
