### ISSUE TITLE
Feature request: enable_notebook() command

### ISSUE THREAD

**Issue by twiecki** [plotly/plotly.py#167]
`mpld3` for example has a single command to turn all plots that are generated to d3 (`mpld3.enable_notebook()` I think). This would make it much easier if using plot.ly was just a single line at the beginning of the notebook rather than converting each figure.

In an email, Andrew had these concerns:

```
1. if you have a *bunch* of plots, this command is going to take forever right now, and won't be much fun
2. you don't have any control of where those files will end up on your plotly account (and no way to give them filenames)
3. you don't have control of updates to figures (update objects or strip_style args)
```

All those points are valid. However, I think there's a good chunkg of users who don't care that much about 2. and 3. initially and just want to get going. Without any knowledge of the tool I could just use that command. Regarding 1., if I only want sections of my NB to use plot.ly I can easily section those with `enable_notebook` and `disable_notebook` calls.

**Comment by twiecki** [comment]
Any update on this?

**Comment by theengineear** [comment]
@twiecki , we've recently added in widget support which will make local versions of plots possible. With this, we may be able to allow iframes with live versions of the plots to be populated, though it woudn't require saving all of the plots unnecessarily to an account and proliferating unnamed figures in your profile on Plotly. I'll drop a note in here when if/when we get closer to this feature.

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
