### ISSUE TITLE
PX color_scale_continous docs incomplete

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.py#1679]
Here https://github.com/plotly/plotly.py/blob/master/packages/python/plotly/plotly/express/_doc.py#L164

We accept color scale names also right?

**Comment by jonmmease** [comment]
Yeah, `px` is using the same colorscale validator as graph objects now. Here's where that docstring is generated:

https://github.com/plotly/plotly.py/blob/168398e89f581bf3ae451c6bfec29bfc3b7ac9a5/packages/python/plotly/_plotly_utils/basevalidators.py#L1550-L1562

So it would probably make sense to combine the generation of these docstrings into a common function in `_plotly_utils`.
