### ISSUE TITLE
add support for the _r convention to reverse colorscales

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.py#1681]
...the way Matplotlib does it.

**Comment by jonmmease** [comment]
yeah, this would be great.

This would be handled in the `ColorscaleValidator.validate_coerce`, when processing string inputs...

https://github.com/plotly/plotly.py/blob/168398e89f581bf3ae451c6bfec29bfc3b7ac9a5/packages/python/plotly/_plotly_utils/basevalidators.py#L1568-L1583

with something like 

```python
elif v_lower.endswith('_r') and v_lower[:-2] in self.named_colorscales:
    v = list(reversed(self.named_colorscales[v_lower[:-2]]))
    ...
```
