### ISSUE TITLE
Plotly Express strange hover_data ValueError

### ISSUE THREAD

**Issue by suciokhan** [plotly/plotly.py#1683]
Scatter plotting with no problems, until I attempted to map a column of my data to hover_data.
Here's what my data looks like. I'm trying to map the `most_similar_kt` column to hover_data.

![image](https://user-images.githubusercontent.com/23055812/61797829-2b358a80-adf6-11e9-8240-00387e858a26.png)

Here's the error message:
`ValueError: Element of value of 'hover_data' is not the name of a column in 'data_frame'. Expected one of ['x', 'y', 'label', 'freq', 'similarity', 'size', 'class', 'most_similar_kt'] but received: m`

And here's my code:
`fig = px.scatter(df, x='x',y='y', color='similarity', size='size', symbol='class',hover_name='label', hover_data='most_similar_kt', width=1500, height=1000, template='plotly_dark', render_mode='webgl')`

Apologies if this has already been addressed; I spent 10 minutes googling for errors and it doesn't appear anyone else had this issue.

If I `remove the hover_data assignment`, then the plot works:
![image](https://user-images.githubusercontent.com/23055812/61798086-aeef7700-adf6-11e9-9bad-8bc878c1c7c6.png)

Thanks for your assistance!

**Comment by suciokhan** [comment]
Apologies; I figure out that you are supposed to feed columns inside a list rather than just a string of the column name like the other items. Closing out.

**Comment by zhaomh1998** [comment]
Had the exact same issue. This is indeed a very misleading error message though, and very much seem to be a bug as it says `Expected one of ['x', 'y', 'label', 'freq', 'similarity', 'size', 'class', 'most_similar_kt'] but received: m`, as you passed in `hover_data='most_similar_kt'`.

It would make sense if it says something like "list of column names expected but received a single str".

**Comment by emmanuelle** [comment]
@zhaomh1998 we have an open issue #2177 to improve the error message, it should be improved soon :-).

**Comment by boral** [comment]
Please fix this.

**Comment by nicolaskruchten** [comment]
We haven't gotten around to it yet... Contributions are welcome :)

**Comment by rocu-mapspeople** [comment]
just came here to say these comments helped me.  :)

**Comment by StankovskiA** [comment]
The answers have helped me as well. For other newbies like myself, to pass all the columns you can do
` hover_data = df.columns.tolist()`
 and to pass just certain columns 
`hover_data = [ 'col1', 'col2']`
