### ISSUE TITLE
Databricks notebook renderer

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.py#1684]
Right now it seems like the only way to render in Databricks notebook is via `displayHTML(fig.to_html())`.

From Slack:

> Is displayHTML a built-in databricks thing?  If so, then this could be done as ExternalRenderer renderer, where the side-effect is calling displayHTML.  And we could use the presence of that function in the global namespace to automatically enable the renderer. 

>Basically identical to BrowserRenderer (https://github.com/plotly/plotly.py/blob/168398e89f581bf3ae451c6bfec29bfc3b7ac9a5/packages/python/plotly/plotly/io/_base_renderers.py#L659-L707)
but calling displayHTML instead of open_html_in_browser.  We should probably extract a shared ExternalHtmlRenderer parent class too.  Then add an auto-detect section like the colab one in https://github.com/plotly/plotly.py/blob/168398e89f581bf3ae451c6bfec29bfc3b7ac9a5/packages/python/plotly/plotly/io/_renderers.py#L454-L460.  But it would check for a NameError on the displayHTML function.

**Comment by LePuppy** [comment]
Hi, I'm actually displaying graph_objects figures inside Databricks ! I build the figure then use fig.show() and this work perfectly for me.

**Comment by nicolaskruchten** [comment]
Ah yes, we did this in https://github.com/plotly/plotly.py/pull/1703
