### ISSUE TITLE
Building the plotly extensions breaks JupyterLab

### ISSUE THREAD

**Issue by sursu** [plotly/plotly.py#1686]
Ubuntu 18.04.2
Plotly 4.0.0
JupyterLab 1.0.2

It looks like building the plotly extensions for JupyterLab breaks it (cannot be launched: see [here](https://github.com/jupyterlab/jupyterlab/issues/6858))

Jupyter Notebooks run well.

**Comment by jonmmease** [comment]
Hi @sursu, what versions of the plotly extensions (`jupyterlab-plotly` and `plotlywidget`) do you have installed?  Can you provide a reproducible set of steps that create the problem?

The instructions at https://github.com/plotly/plotly.py#jupyterlab-support-python-35 include the supported combination of versions of everything needed to get JupyterLab support working.  Also make sure you don't have the legacy `@jupyterlab/plotly-extension` extension installed.

**Comment by sursu** [comment]
Hi @jonmmease, I have followed the instructions you have mentioned.

If you haven't changed that then the versions should be those:
- `plotlywidget@1.0.0`
- `jupyterlab-plotly@1.0.0`

(Don't know how to check them otherwise)

Reproducible set of steps:
1. Uninstall and then install JupyterLab
As an intermediary step check that the installation works by running `jupyter lab` in the terminal.
2. Follow the instructions here: https://github.com/plotly/plotly.py#jupyterlab-support-python-35

**Comment by sursu** [comment]
@jonmmease can you replicate this?

**Comment by janjagusch** [comment]
> Hi @sursu, what versions of the plotly extensions (`jupyterlab-plotly` and `plotlywidget`) do you have installed? Can you provide a reproducible set of steps that create the problem?
> 
> The instructions at https://github.com/plotly/plotly.py#jupyterlab-support-python-35 include the supported combination of versions of everything needed to get JupyterLab support working. Also make sure you don't have the legacy `@jupyterlab/plotly-extension` extension installed.

`@jupyterlab/plotly-extension` was the cause for me. thanks!

**Comment by sursu** [comment]
Thank you, that solved it!

For posterity, here is how uninstalling is done:

`jupyter labextension uninstall @jupyterlab/plotly-extension`

**Comment by dymodi** [comment]
so is there any guidance on using plotly-extension with jupyter-lab?

**Comment by nicolaskruchten** [comment]
Yes, we have a Troubleshooting guide now: https://plot.ly/python/troubleshooting/ :)

**Comment by amandhaliwal88** [comment]
I had the same problem. For some reason after uninstalling the JupyterLab plotly extension it is now working fine.

**Comment by cpoptic** [comment]
the old extension `plotly-extension` has been deprecated and is now replaced with `jupyterlab-plotly`
Use this instead for your Plotly extension install;

`jupyter labextension uninstall @jupyterlab/plotly-extension`
`jupyter labextension install jupyterlab-plotly`

**Comment by lanreogun** [comment]
took me a few hours to find this thread. worked perfectly
