### ISSUE TITLE
Plotly doesn't show anything after following instructions in SageMaker

### ISSUE THREAD

**Issue by leolorenzoluis** [plotly/plotly.py#1688]
Following instructions found https://plot.ly/python/getting-started/

I installed the required libraries and extensions, but when I do the following code it still displays blank output
```
import plotly.graph_objects as go
fig = go.Figure(data=go.Bar(y=[2, 3, 1]))
fig.show()
```

**Comment by nicolaskruchten** [comment]
Did you get this to work in the end?

**Comment by leolorenzoluis** [comment]
@nicolaskruchten Yes, I refreshed the browser and it started to show up.

**Comment by YikaiHu** [comment]
Hi, May I ask what's your browser's type? Chrome or firefox?

**Comment by YikaiHu** [comment]
I have refreshed my chrome, it still didn't appear

**Comment by sangeetsaurabh** [comment]
It's not showing up for me too. It works for Jupyter Notebook instance, but it doesn't work for Jupyterlab. I have installed all the extensions as instructed.

**Comment by viniciusslvdor** [comment]
For those who continue to have this problem, one of the options to solve it is to specify this command at the top of the notebook:
`plotly.offline.init_notebook_mode(connected=True)`

Plotly can work in both online and offline mode. In offline mode, the graphs are generated and displayed locally in the browser, without the need for an internet connection or to send data to Plotly's servers. The init_notebook_mode() command is essential for setting up this mode when working on a Jupyter notebook.

If, for some reason during your application, you are unable to connect to the Plotly server, this is a valid option.

To find out more, there is a specific tab in the documentation: https://plotly.com/python/getting-started/#initialization-for-offline-plotting
