### ISSUE TITLE
Plotly express feature request: Bypass dataframes

### ISSUE THREAD

**Issue by malmaud** [plotly/plotly.py#1696]
Since Plotly Express is now in this repository, I just wanted to cross-link https://github.com/plotly/plotly_express/issues/85. cc @nicolaskruchten

**Comment by nicolaskruchten** [comment]
Yes indeed, now that we've released 4.0, PX development is open for business once again :)

**Comment by nicolaskruchten** [comment]
This will be implemented as part of plotly/plotly.py#1767 ... thanks for the input and patience :)
