### ISSUE TITLE
Template is included in dict/json export

### ISSUE THREAD

**Issue by Batalex** [plotly/plotly.py#1698]
Hi,
I noticed that since 4.0 the active template is included in the dict/json export.

Given the following snippet:

```python
import json
import plotly.graph_objs as go

traces = [go.Scatter(x=[0, 1], y=[0, 1])]

fig = go.Figure(data=traces, layout={})

with open("fig.json", "w", encoding="utf-8") as f:
    json.dump(fig.to_dict(), f)
```

The final `fig.json` file is **118 bytes** large with plotly.py `3.10` and **6 661** using `4.0`.
The new output utility `.write_json` behaves the same way.

The size difference is not really an issue on larger plots of course.
Prior to `4.0`, I could restyle a json plot by loading it in an environment with a different default template. The `update_layout()` method works just fine, so this is not a blocker either.

This change is not documented in the migration guide, so I figured it would be a regression rather than an intended change.

**Comment by nicolaskruchten** [comment]
Yes, this is intentional: the template must be included in the figure in order to be taken into account during rendering. I don't really consider this a regression, as we have no documented commitments to JSON file size in our documentation, and although the relative size increase is enormous for simple figures, the absolute size increase is quite small.

Note that this behaviour can be disabled by setting the `template` to `None` either on a per-figure or session-wide default level.

**Comment by jonmmease** [comment]
We could add an `include_template=True` kwarg to the `fig.to_json`/`fig.write_json` methods to make it easier for folks to write out JSON files without a template.

**Comment by nicolaskruchten** [comment]
We could but... that would make the resulting output look very different! Maybe if we have a new `with_template=` kwarg for the matching JSON import functions? so you could strip them out on the way to disk and tack them back on on they way back into Python?

**Comment by Batalex** [comment]
I am not sure about adding more complexity to export/import functions, as there is already a convenient & straightforward way to change a figure template with `fig.layout.template="my_theme"`.

I mostly wanted to bring this to your attention but since it is intentional it is all good I guess!

**Comment by jonmmease** [comment]
Thanks @Batalex. I'll close for now but we can reopen if there's more to discuss.
