### ISSUE TITLE
Missing dependencies when installing from pip ("requests")

### ISSUE THREAD

**Issue by hnykda** [plotly/plotly.py#17]
Hello,

when i tried to install plotly using `pip install plotly`, I got:

```
Downloading/unpacking plotly
  Downloading plotly-1.0.10.tar.gz (60kB):    Downloading plotly-1.0.10.tar.gz (60kB):    Downloading plotly-1.0.10.tar.gz (60kB):    Downloading plotly-1.0.10.tar.gz (60kB):    Downloading plotly-1.0.10.tar.gz (60kB):    Downloading plotly-1.0.10.tar.gz (60kB):    Downloading plotly-1.0.10.tar.gz (60kB):    Downloading plotly-1.0.10.tar.gz (60kB):    Downloading plotly-1.0.10.tar.gz (60kB):    Downloading plotly-1.0.10.tar.gz (60kB):    Downloading plotly-1.0.10.tar.gz (60kB):    Downloading plotly-1.0.10.tar.gz (60kB):    Downloading plotly-1.0.10.tar.gz (60kB):    Downloading plotly-1.0.10.tar.gz (60kB):    Downloading plotly-1.0.10.tar.gz (60kB): 1  Downloading plotly-1.0.10.tar.gz (60kB):    Downloading plotly-1.0.10.tar.gz (60kB): 60kB downloaded
  Running setup.py (path:/home/dan/prac/.virtualenvs/work/build/plotly/setup.py) egg_info for package plotly
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/home/dan/prac/.virtualenvs/work/build/plotly/setup.py", line 3, in <module>
        exec (open('plotly/version.py').read())
      File "<string>", line 3, in <module>
    ImportError: No module named 'requests'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/home/dan/prac/.virtualenvs/work/build/plotly/setup.py", line 3, in <module>

    exec (open('plotly/version.py').read())

  File "<string>", line 3, in <module>

ImportError: No module named 'requests'

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /home/dan/prac/.virtualenvs/work/build/plotly
Storing debug log for failure in /home/dan/.pip/pip.log
```

after installing "requests" using `pip install requests`, everything works fine.

**Comment by moritzmcgarrie** [comment]
I typed:   pip install --upgrade plotly
and it installed fine, and then I type: python -c "import plotly"
and get 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named plotly

I am using mac, with python --version
Python 2.7.10
but I also have python 3.4 installed

**Comment by moritzmcgarrie** [comment]
Solved my own problem: So even though I had python --version
Python 2.7.10 , when I type pop install <some-package> it must be installing for 3.4...

Using (https://docs.python.org/2/installing/):
python2   -m pip install SomePackage  # default Python 2
python2.7 -m pip install SomePackage  # specifically Python 2.7
python3   -m pip install SomePackage  # default Python 3
python3.4 -m pip install SomePackage  # specifically Python 3.4

I can change plotly specifically for version 2.7 and now works fine.

**Comment by jordiac** [comment]
Having the same issue in windows (8.1) and solve as indicated by moritzmcgarrie: 

Using ([https://docs.python.org/2/installing/](url)) for pyhton 3.6 : 
py -3.6 -m pip install plotly

**Comment by nishant-reddy** [comment]
I only have python 3.4, and even though I install plotly using pip, I can never import plotly in a python file. I always get the error: plotly is not a package.

**Comment by mithunsureshqa** [comment]
i have python 2.7.14 & plotly : Version: 2.2.1 on my mac. 
still running into error _import plotly
ImportError: No module named plotly_ 
any help is apprecaited.
