### ISSUE TITLE
Power  BI visual object with Plotly

### ISSUE THREAD

**Issue by stinkfist93** [plotly/plotly.py#1709]
Hi guys, how can i make a visual object using Plotly with Python in Power BI? 
Like this guy does https://www.youtube.com/watch?v=uLikWluqg54

**Comment by jonmmease** [comment]
Hi @stinkfist93, I'm not very familiar with Power BI and plotly.py itself doesn't have any specific integration with it. Perhaps someone on the community forum (https://community.plot.ly/c/api/python) might have some ideas. Good luck!
