### ISSUE TITLE
choroplethmapbox  fails to map z-values to a colorscale

### ISSUE THREAD

**Issue by empet** [plotly/plotly.py#1712]
I installed plotly 4.1.0 and the first experiment was to plot a choroplethmapbox chart.
It seems that it doesn't work even on examples
downloaded from  plotly mocks: [https://plot.ly/~empet/15236](https://plot.ly/~empet/15236).

After this  failure I had an attempt to plot the choropleth of France regions
using this geojson file from url = 'https://raw.githubusercontent.com/gregoiredavid/france-geojson/master/regions.geojson'

When I wanted to fill in the choroplethmapbox attributes I realized that
I cannot understand the description of the 'locations`:

```
locations - Sets which features found in "geojson" to plot using
          their feature `id` field.
```

 

 In the trace definition I assigned the url of the geojson file
but I  read it, too, as a json file to inspect its contents.

Each geojson feature has the following `'properties'`:

```
for feat   in jdata['features']:
    print(feat['properties'])

{'code': '11', 'nom': 'Île-de-France'}
{'code': '24', 'nom': 'Centre-Val de Loire'}
{'code': '27', 'nom': 'Bourgogne-Franche-Comté'}
{'code': '28', 'nom': 'Normandie'}
{'code': '32', 'nom': 'Hauts-de-France'}
{'code': '44', 'nom': 'Grand Est'}
{'code': '52', 'nom': 'Pays de la Loire'}
{'code': '53', 'nom': 'Bretagne'}
{'code': '75', 'nom': 'Nouvelle-Aquitaine'}
{'code': '76', 'nom': 'Occitanie'}
{'code': '84', 'nom': 'Auvergne-Rhône-Alpes'}
{'code': '93', 'nom': "Provence-Alpes-Côte d'Azur"}
{'code': '94', 'nom': 'Corse'}
```

Is 'code' the  id mentioned in `'locations'` definition?

What should I set for `locations`?  I extracted the `nom` for each region and defined locations = regions,
but the regions are left white, and no value was colormapped (the same behaviour as the mock example, above).

A detailed example, with all keys set, to understand their  role, would be very useful.
Thanks!

**Comment by nicolaskruchten** [comment]
This example should clear things up: https://plot.ly/python/mapbox-county-choropleth/

The `id` is adjacent to `properties`, not inside it.

**Comment by empet** [comment]
@nicolaskruchten 
Thanks!  Its clear now what is id, but the docs should make it more clear.
Not all geojson files storing  data for  states, regions or counties in different countries contain a key id.

The geojson file for France regions I used in my first example displays the following keys for each
feature:
```
print(jdata['features'][0].keys())
dict_keys(['type', 'geometry', 'properties'])
```
while that in the example at the  link  you gave above  displays:
```
print(counties['features'][0].keys())
dict_keys(['type', 'properties', 'geometry', 'id'])
```
 The solution is to add  an `id ` key to each feature in my `jdata['features']` , as well as in in the additional file that contains the z-values.

**Comment by nicolaskruchten** [comment]
Yep, we're working on more detailed docs, I just had to rush these out last night.

Re `id`s... yeah, not all GeoJSON objects have them but they're trivial to add, as you say. That's what I had to do to build the example I linked to.

**Comment by nicolaskruchten** [comment]
BTW per https://tools.ietf.org/html/rfc7946#section-3.2 :

> If a Feature has a commonly used identifier, that identifier
      SHOULD be included as a member of the Feature object with the name
      "id", and the value of this member is either a JSON string or
      number.

So we're not just totally making this up ;)
