### ISSUE TITLE
Two ways of instllation in README.md are misleading. 

### ISSUE THREAD

**Issue by inTheRye** [plotly/plotly.py#1770]
# Problem

There are two ways of installation in README.md.
1. `$ pip install plotly "notebook>=5.3" "ipywidgets>=7.2"` in [Quickstart](https://github.com/plotly/plotly.py/blob/master/README.md#quickstart)
1. `$ pip install plotly==4.1.1` in [Installation](https://github.com/plotly/plotly.py/blob/master/README.md#installation)

I tried the "Quickstart installation" at first. But in my environment, there was already installed older version of plotly (3.4.2). I did't notice it was the older version because the 1st way of installation doesn't specify the version.

So, I executed the command ``$ pip install plotly "notebook>=5.3" "ipywidgets>=7.2"`` but it said the `plotly` is already installed.

Then I tried some example code in 'https://plot.ly/python/' but it didn't work. 
After I tried the version specified command `$ pip install plotly==4.1.1`, it worked.

# Solution

Please modify the ”Quickstart” installation in README.md into version specific way. I think It will be beginner-friendly.

example to modify
`$ pip install plotly==4.1.1 "notebook>=5.3" "ipywidgets>=7.2"`

Thank you in advance.

**Comment by emmanuelle** [comment]
I think we should recommend `pip install -U plotly` so that the newest version is installed. Any thoughts @nicolaskruchten @jonmmease ?

**Comment by daxsoule** [comment]
When I pip install in either of these two ways and run the test case in a jupiter notebook, I get a blank figure. 

!pip install -U plotly
import plotly.graph_objects as go

fig= go.Figure(data=go.Isosurface(
    x=[0,0,0,0,1,1,1,1],
    y=[1,0,1,0,1,0,1,0],
    z=[1,1,0,0,1,1,0,0],
    value=[1,2,3,4,5,6,7,8],
    isomin=2,
    isomax=6,
))

fig.show()

Space is created for a figure, but no figures appears. Any ideas how to trouble shoot this?

**Comment by nicolaskruchten** [comment]
I've fixed this in the Readme, thanks for pointing out a source of confusion @inTheRye !
