### ISSUE TITLE
Scattergl doesn't work in Brave browser

### ISSUE THREAD

**Issue by 6Hhcy** [plotly/plotly.py#1773]
I'm trying to reproduce this sample:

https://plot.ly/python/compare-webgl-svg/

Plotly version: 4.1.1
Python version: 3.6.6
Brave version: 0.68.132

I had some Scattergl code that worked a couple of months back. I've just revisited it and now it doesn't work. The tab opens, I see axes, but no points. Using Chrome instead.

```
import plotly.graph_objects as go
import numpy as np
np.random.seed(1)

N = 75000

fig = go.Figure()
fig.add_trace(
    go.Scattergl(
        x = np.random.randn(N),
        y = np.random.randn(N),
        mode = 'markers',
        marker = dict(
            line = dict(
                width = 1,
                color = 'DarkSlateGrey')
        )
    )
)

fig.show(renderer="browser")
```

**Comment by Batalex** [comment]
I am currently using Brave and the graph renders just fine on my side.
That being said, I remember some very particular times where the privacy shield would hinder the webgl loading. Try to disable it and see if it changes anything on your side.
