### ISSUE TITLE
Formatting and hiding hover_data in PX

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.py#1774]
Let's implement the API from https://github.com/plotly/plotly_express/issues/115 and support `False` as a value so as to support https://github.com/plotly/plotly_express/issues/120.

**Comment by emmanuelle** [comment]
For the format of `hover_data`, would you prefer 
- accepting a dict, in which case all keys must have a value, eg `hover_data={'species':None, 'petal_length':'%s"}` 
- or keeping a list, and the element of the list can be either column names  / columns / arrays, or tuples, eg `hover_data=[('species', None), 'petal_length', ('petal_width', '%03d')]` etc.

**Comment by nicolaskruchten** [comment]
Ah, you mean how should a user be able to specify the formatting for some `hover_data` items but leave some as a default?

**Comment by emmanuelle** [comment]
yes

**Comment by nicolaskruchten** [comment]
Hmmm. And we need some pythonic way of distinguishing between "use the defaults" and "suppress this one"... Is `None` vs `False` clear enough? They're both falsey... `""` has the same problem I think.

**Comment by emmanuelle** [comment]
yes, this is why I was thinking of keeping a list but allowing tuple elements

**Comment by nicolaskruchten** [comment]
Is this a common pattern in Python or... ? It makes sense but I've not seen it before.

**Comment by emmanuelle** [comment]
hum, not really... let me think this over

**Comment by nicolaskruchten** [comment]
I actually think saying "using `""` as a `dict` value will use the default formatting" is OK. That's how  plotly.js will treat it under the hood anyways, as far as I can tell

**Comment by nicolaskruchten** [comment]
so `None` and `False` would suppress it and `""` would not do any formatting. And/or we could add a `px.DEFAULT` magic-constant.

**Comment by JohnLarson775** [comment]
Any updates on this? I'm searching for a nice way to suppress certain items and keep redirecting back to this open issue.

**Comment by nicolaskruchten** [comment]
This is not yet implemented, no but we'd happily accept a PR :)
