### ISSUE TITLE
super(type, obj): obj must be an instance or subtype of type

### ISSUE THREAD

**Issue by aglucaci** [plotly/plotly.py#1781]
Hello,
I receive the following error with plotly 4.1.1 and python 3.7.4

"super(type, obj): obj must be an instance or subtype of type"

**Comment by nicolaskruchten** [comment]
Can you provide a minimal runnable example for us to reproduce this bug please?

**Comment by aglucaci** [comment]
Seems to have resolved.

**Comment by wavemakersh** [comment]
> Seems to have resolved.

how do you fix it
