### ISSUE TITLE
Getting AttributeError: module 'plotly.validators.layout.mapbox.layer' has no attribute 'CoordinatesValidator'

### ISSUE THREAD

**Issue by MartinPetrov8** [plotly/plotly.py#1789]
I am using plotly 3.1 and am getting he below error:
`AttributeError: module 'plotly.validators.layout.mapbox.layer' has no attribute 'CoordinatesValidator'`
I read around tried with 3.4.2 and 4.1 versions - same error here is an example code i am using:

```
trace = go.Bar(
    x=cnt_users.year_month,
    y=cnt_users.num_users,
    marker=dict(
        colorscale = 'Picnic',
        reversescale = True
    ),
)
layout = go.Layout(
    title='Count of Unique Users per Month',
    font=dict(size=16)
)
data = [trace]
fig = go.Figure(data=data, layout=layout)
fig['layout'].update(height=500, width=1500)
py.iplot(fig, filename="TargetCount")
```
This was working for me 4 months ago but now i am getting an error

![image](https://user-images.githubusercontent.com/25074675/65678492-7709e780-e064-11e9-8cb8-8ef9f1f004b1.png)

**Comment by nicolaskruchten** [comment]
This is pretty strange. Can you provide a fully-runnable example including dummy data please?

**Comment by mitraabhik** [comment]
@nicolaskruchten even I am facing the same issue while trying to create a heatmap.
This is my code:
# creating a heatmap
fig = go.Figure(data = go.Heatmap(z = np.round(data_numeric_corr,2),
                                  x = data_numeric.columns,
                                  y = data_numeric.columns  ))
fig.update_layout(height = 800, width = 800)
fig.show()

This is the error:
AttributeError                            Traceback (most recent call last)
<ipython-input-13-1a75e824636f> in <module>
      2 fig = go.Figure(data = go.Heatmap(z = np.round(data_numeric_corr,2),
      3                                   x = data_numeric.columns,
----> 4                                   y = data_numeric.columns  ))
      5 fig.update_layout(height = 800, width = 800)
      6 fig.show()

c:\users\sante\appdata\local\programs\python\python37\lib\site-packages\plotly\graph_objs\_figure.py in __init__(self, data, layout, frames, skip_invalid, **kwargs)
    586             is invalid AND skip_invalid is False
    587         """
--> 588         super(Figure, self).__init__(data, layout, frames, skip_invalid, **kwargs)
    589 
    590     def add_area(

c:\users\sante\appdata\local\programs\python\python37\lib\site-packages\plotly\basedatatypes.py in __init__(self, data, layout_plotly, frames, skip_invalid, **kwargs)
    197         # ### Import Layout ###
    198         self._layout_obj = self._layout_validator.validate_coerce(
--> 199             layout, skip_invalid=skip_invalid
    200         )
    201 

c:\users\sante\appdata\local\programs\python\python37\lib\site-packages\_plotly_utils\basevalidators.py in validate_coerce(self, v, skip_invalid)
   2428     def validate_coerce(self, v, skip_invalid=False):
   2429         if v is None:
-> 2430             v = self.data_class()
   2431 
   2432         elif isinstance(v, dict):

c:\users\sante\appdata\local\programs\python\python37\lib\site-packages\plotly\graph_objs\__init__.py in __init__(self, arg, angularaxis, annotations, annotationdefaults, autosize, bargap, bargroupgap, barmode, barnorm, boxgap, boxgroupgap, boxmode, calendar, clickmode, coloraxis, colorscale, colorway, datarevision, direction, dragmode, editrevision, extendfunnelareacolors, extendpiecolors, extendsunburstcolors, font, funnelareacolorway, funnelgap, funnelgroupgap, funnelmode, geo, grid, height, hiddenlabels, hiddenlabelssrc, hidesources, hoverdistance, hoverlabel, hovermode, images, imagedefaults, legend, mapbox, margin, meta, metasrc, modebar, orientation, paper_bgcolor, piecolorway, plot_bgcolor, polar, radialaxis, scene, selectdirection, selectionrevision, separators, shapes, shapedefaults, showlegend, sliders, sliderdefaults, spikedistance, sunburstcolorway, template, ternary, title, titlefont, transition, uirevision, updatemenus, updatemenudefaults, violingap, violingroupgap, violinmode, waterfallgap, waterfallgroupgap, waterfallmode, width, xaxis, yaxis, **kwargs)
   5382         self["legend"] = legend if legend is not None else _v
   5383         _v = arg.pop("mapbox", None)
-> 5384         self["mapbox"] = mapbox if mapbox is not None else _v
   5385         _v = arg.pop("margin", None)
   5386         self["margin"] = margin if margin is not None else _v

c:\users\sante\appdata\local\programs\python\python37\lib\site-packages\plotly\basedatatypes.py in __setitem__(self, prop, value)
   4294         if match is None:
   4295             # Set as ordinary property
-> 4296             super(BaseLayoutHierarchyType, self).__setitem__(prop, value)
   4297         else:
   4298             # Set as subplotid property

c:\users\sante\appdata\local\programs\python\python37\lib\site-packages\plotly\basedatatypes.py in __setitem__(self, prop, value)
   3343             # ### Handle compound property ###
   3344             if isinstance(validator, CompoundValidator):
-> 3345                 self._set_compound_prop(prop, value)
   3346 
   3347             # ### Handle compound array property ###

c:\users\sante\appdata\local\programs\python\python37\lib\site-packages\plotly\basedatatypes.py in _set_compound_prop(self, prop, val)
   3694         validator = self._validators.get(prop)
   3695         # type: BasePlotlyType
-> 3696         val = validator.validate_coerce(val, skip_invalid=self._skip_invalid)
   3697 
   3698         # Save deep copies of current and new states

c:\users\sante\appdata\local\programs\python\python37\lib\site-packages\_plotly_utils\basevalidators.py in validate_coerce(self, v, skip_invalid)
   2428     def validate_coerce(self, v, skip_invalid=False):
   2429         if v is None:
-> 2430             v = self.data_class()
   2431 
   2432         elif isinstance(v, dict):

c:\users\sante\appdata\local\programs\python\python37\lib\site-packages\plotly\graph_objs\layout\__init__.py in __init__(self, arg, accesstoken, bearing, center, domain, layers, layerdefaults, pitch, style, uirevision, zoom, **kwargs)
  15686         self["layers"] = layers if layers is not None else _v
  15687         _v = arg.pop("layerdefaults", None)
> 15688         self["layerdefaults"] = layerdefaults if layerdefaults is not None else _v
  15689         _v = arg.pop("pitch", None)
  15690         self["pitch"] = pitch if pitch is not None else _v

c:\users\sante\appdata\local\programs\python\python37\lib\site-packages\plotly\basedatatypes.py in __setitem__(self, prop, value)
   3343             # ### Handle compound property ###
   3344             if isinstance(validator, CompoundValidator):
-> 3345                 self._set_compound_prop(prop, value)
   3346 
   3347             # ### Handle compound array property ###

c:\users\sante\appdata\local\programs\python\python37\lib\site-packages\plotly\basedatatypes.py in _set_compound_prop(self, prop, val)
   3694         validator = self._validators.get(prop)
   3695         # type: BasePlotlyType
-> 3696         val = validator.validate_coerce(val, skip_invalid=self._skip_invalid)
   3697 
   3698         # Save deep copies of current and new states

c:\users\sante\appdata\local\programs\python\python37\lib\site-packages\_plotly_utils\basevalidators.py in validate_coerce(self, v, skip_invalid)
   2428     def validate_coerce(self, v, skip_invalid=False):
   2429         if v is None:
-> 2430             v = self.data_class()
   2431 
   2432         elif isinstance(v, dict):

c:\users\sante\appdata\local\programs\python\python37\lib\site-packages\plotly\graph_objs\layout\mapbox\__init__.py in __init__(self, arg, below, circle, color, coordinates, fill, line, maxzoom, minzoom, name, opacity, source, sourceattribution, sourcelayer, sourcetype, symbol, templateitemname, type, visible, **kwargs)
    797         self._validators["circle"] = v_layer.CircleValidator()
    798         self._validators["color"] = v_layer.ColorValidator()
--> 799         self._validators["coordinates"] = v_layer.CoordinatesValidator()
    800         self._validators["fill"] = v_layer.FillValidator()
    801         self._validators["line"] = v_layer.LineValidator()

AttributeError: module 'plotly.validators.layout.mapbox.layer' has no attribute 'CoordinatesValidator'

**Comment by nicolaskruchten** [comment]
This seems like a corrupted installation of `plotly`... The recommended path forward here is to uninstall `plotly` with both `conda remove plotly` and `pip uninstall plotly` and then reinstall it with one or the other but not both. Please let me know if this works!

**Comment by mitraabhik** [comment]
I have not installed anaconda so I think I can bypass that. But regarding normal pip installation I have reinstalled the latest version of plotly ( 4.0.0) , chart-studio and cufflinks. Still no leads as the code gives the same error.

**Comment by nicolaskruchten** [comment]
Can you share the output of `pip freeze` please?

**Comment by nicolaskruchten** [comment]
Also, does something as simple as `go.Figure(go.Heatmap(z = [[1,2],[3,4]])).show()` give you the same result?

**Comment by pankajPizone** [comment]
How can i use custom symbol for marker?

**Comment by Salinatorimperator** [comment]
Any workaround this error?

**Comment by kasalimger** [comment]
Same issue here

**Comment by nicolaskruchten** [comment]
This problem is being experienced by a small fraction of users and unfortunately, no one on the Plotly.py team has been able to reproduce this problem locally, so we don't know how to help you. If you are seeing this problem, please provide *as much detail as you can* about your environment! Are you on Windows/Mac/Linux? Are you in a virtualenv or conda env? Did you install Plotly with pip or conda? Which version of Plotly are you using? Which version of Jupyter are you using? etc.

It would also *really* help if you could provide a set of steps for us to reproduce this problem from scratch i.e. "here is how to create the environment and install the versions which show this issue".

**Comment by adambens** [comment]
Working on newest Mac running in a conda env with plotly == 3.10.0, pip installed and uninstalled plotly, retried with conda. When doing something as simple as  "go.Figure(go.Heatmap(z = [[1,2],[3,4]])).show()" I get the following error: AttributeError: module 'plotly.validators.layout' has no attribute 'ExtendtreemapcolorsValidator'. Using this data set to visualize: https://www.kaggle.com/blastchar/telco-customer-churn

**Comment by emmanuelle** [comment]
@adambens could you please upgrade to a more recent version of plotly.py (`pip install -U plotly`) to see if the problem disappears? Thanks !

**Comment by nicolaskruchten** [comment]
@adambens it seems like you have multiple versions of `plotly` installed, because in a clean environment with just 3.10.0 installed, this code yields:

```
ValueError:
    Invalid value of type 'plotly.graph_objs.Heatmap' received for the 'data' property of
        Received value: Heatmap({
    'z': [[1, 2], [3, 4]]
})
```

As a simple check, are you able to `import plotly.graph_objects as go` ? (note: `graph_objects` rather than `graph_objs`... the former is only available in v4+). And what does `import plotly; plotly.__version__` return?

**Comment by adambens** [comment]
I updated to version 4.2.1 and everything works. Apologies for confusion as I had not used plotly since well before it had been updated to version 4. I would guess most other people experiencing this issue have not updated their plotly.

**Comment by Anasm448** [comment]
Hello, 
Unfortunately, I have the same problem? I use plotly 4.3.0. I tried the abovementioned step by uninstalling from Anaconda or cmd. And then I installed through "conda install plotly" but it doesn't wrok!!

**Comment by amrihasan** [comment]
Hello, 
I also experienced the same thing when running the program using the library plotly,I use anaconda and Windows users and currently use the latest version plotly 4.6.0
![image](https://user-images.githubusercontent.com/39668761/78558899-a3859400-783d-11ea-8c92-931aa9cbeb68.png)

my code 
![image](https://user-images.githubusercontent.com/39668761/78559017-d760b980-783d-11ea-8026-dbf1047cfc6a.png)
![image](https://user-images.githubusercontent.com/39668761/78559048-e5163f00-783d-11ea-871b-a8eac90b62f2.png)

**Comment by nicolaskruchten** [comment]
Hi all,

No one on the Plotly.py team has been able to replicate this behaviour unfortunately. I would recommend trying to carefully follow the [Troubleshooting guide](https://plotly.com/python/troubleshooting/) to see if there is a double-install of `plotly` at play here...

**Comment by krbundy** [comment]
Hello, 

I got this issue after doing something dumb: I had a kernel running on the conda environment I was installing into.  I think that was the cause of the error - I had a Jupyter notebook on the wrong environment.  

Once I closed the kernel, ran `pip install -U plotly` and restarted the kernel everything worked fine.

**Comment by nicolaskruchten** [comment]
I've just been able to replicate this with an open notebook after installing a different version of `plotly` while the kernel was running, and restarting the kernel resolved the issue, so this may be part of the solution for some folks.

**Comment by SHUBHAM1991** [comment]
use below import 

from plotly.offline import init_notebook_mode, iplot
import plotly.express as ex
import plotly.graph_objs as go  

it will work if not then do let me know  
![erro1lot](https://user-images.githubusercontent.com/14157244/99899592-90420e80-2cd0-11eb-9548-d4aab305efcc.PNG)

![image](https://user-images.githubusercontent.com/14157244/99899631-d5664080-2cd0-11eb-928a-d968f67f8f3f.png)

**Comment by SHUBHAM1991** [comment]
![image](https://user-images.githubusercontent.com/14157244/99899709-6b9a6680-2cd1-11eb-8801-b863f537dbdd.png)

**Comment by Tkumar21** [comment]
I am also getting same issue while using CX_Freeze for bundling ,otherwise it is working fine on my system. unable to trace what the issue.
Do anyone have solution :

AttributeError: module 'plotly.validators.layout.xaxis' has no attribute 'AnchorValidator'

AttributeError: module 'plotly.validators.scatter' has no attribute 'LegendgroupValidator'
