### ISSUE TITLE
404 GET /static/plotly.js?v=

### ISSUE THREAD

**Issue by nicpayne713** [plotly/plotly.py#1797]
I am seeing this 404 intermittently which is prohibiting Plotly figures from rendering in my jupyter notebook. I have tried fresh conda environments and rolling back Jupyter installs. The problem is incredibly inconsistent and appears to happen randomly and persist for random amounts of time.
Plotly still renders outside the notebook environment (ie. pio.renderers.default='browser'), and .save() methods still render plots but they are now showing up in the notebook.

I've referenced issue 112 in plotly_express (https://github.com/plotly/plotly_express/issues/112) which looks incredibly similar but am still having the rendering problems.

Here's what I think is relevant for the issue although I'm not sure it can be reliably reproduced:

nbformat 4.4.0
nbconvert 5.6.0
ipython 7.8.0
ipykernel 5.1.2
ipython_genutils 0.2.0
jupyter 1.0.0
jupyter_client  5.3.3
jupyter_console 6.0.0
jupyter_core 4.4.0
plotly 4.1.1 (also have tried with 4.0.0 and see the same error appear seemingly randomly)

**Comment by vnikoofard** [comment]
In my case when I change the renderer to 'browser' and then back again to 'notebook' the problem get solved!

**Comment by eddy-geek** [comment]
indeed just `fig.show(renderer="notebook")` was enough for me. it seems to spend time regenerating the static files.

(thanks @vnikoofard )

**Comment by nicolaskruchten** [comment]
Yes, this is the approach suggested in our Troubleshooting guide here https://plotly.com/python/troubleshooting/ :)
