### ISSUE TITLE
Deeper pandas integration

### ISSUE THREAD

**Issue by hnykda** [plotly/plotly.py#18]
Hello,

I'd like to ask if there are plans to integrate plotly with pandas, similiar to [ggplot](https://github.com/yhat/ggplot/) style. Or is it impossible without changing "philisophy" of input?

Thank you

**Comment by chriddyp** [comment]
Here's a new library by @santosjorge for dealing with this: [cufflinks: Productivity Tools for Plotly + Pandas](https://github.com/santosjorge/cufflinks). 

There's a great notebook here: http://nbviewer.ipython.org/gist/santosjorge/cfaaf43b40db19d6127a

Looks great!

**Comment by hugadams** [comment]
Awesome, thanks for sharing

On Mon, Jan 12, 2015 at 6:33 PM, chriddyp <notifications@github.com> wrote:

> Here's a new library by @santosjorge <https://github.com/santosjorge> for
> dealing with this: cufflinks: Productivity Tools for Plotly + Pandas
> <https://github.com/santosjorge/cufflinks>.
>
> There's a great notebook here:
> http://nbviewer.ipython.org/gist/santosjorge/cfaaf43b40db19d6127a
>
> Looks great!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/plotly/python-api/issues/18#issuecomment-69668480>.
>



-- 
Adam Hughes
Physics Ph.D Candidate
George Washington University

**Comment by jonmmease** [comment]
Closing this for now.  plotly.py does support `DateTimeIndex` values now, and the cufflinks project has become an established way to build plotly plots from pandas data frames.  Feel free to open a new issue if anyone would like to discuss additional pandas integration ideas!
