### ISSUE TITLE
Presentation template should not change colors

### ISSUE THREAD

**Issue by benjaminjack** [plotly/plotly.py#1807]
## Issue

If you combine the 'presentation' template with another template using the plus-sign (+) composition syntax, the presentation template will change the colors of points, lines, and other traces that are defined in the other template.

```
plotly==4.1.1
```

## Expected behavior

The 'presentation' template should only change the size of text, points, and lines. It should not change the colors.

## Reprex

```
import plotly.express as px

iris = px.data.iris()

# Colors correctly follow the 'plotly_dark' theme
dark_plt = px.scatter(iris, x='sepal_length', y='sepal_width', color='species', template='plotly_dark')
dark_plt.show()

# 'presentation' template changes colors from 'plotly_dark' theme when it shouldn't
dark_pres_plt = px.scatter(iris, x='sepal_length', y='sepal_width', color='species', template='plotly_dark+presentation')
dark_pres_plt.show()
```

**Comment by jonmmease** [comment]
Thanks a lot for the report @benjaminjack, fixed in https://github.com/plotly/plotly.py/pull/1819 and will be released in version 4.2.0 in the next few days.
