### ISSUE TITLE
Plotly Treemap trace only available for plotly.js v1.50.0?

### ISSUE THREAD

**Issue by KangboLu** [plotly/plotly.py#1811]
Is the Treemap trace only available for plotly.js v 1.50.0? 
For python, we still need to use Squarify? Can I integrate Squarify with Dash for treemap?

**Comment by nicolaskruchten** [comment]
The next version of Plotly.py will have native treemap support... it should be out next week :)

**Comment by KangboLu** [comment]
Excited!

**Comment by nicolaskruchten** [comment]
Here you go! Version 4.2 is out, with native treemap support: https://plot.ly/python/treemaps/
