### ISSUE TITLE
Does Plotly 4.2.0 depend on scikit-image?

### ISSUE THREAD

**Issue by qutang** [plotly/plotly.py#1826]
I failed to `import plotly.figure_factory` because plotly seems not to install `scikit-image` when running `pip install -U plotly`. After I manually installed `scikit-image`, `import plotly.figure_factory` worked.

This was not a problem in version 4.1.1.

But the source code shows it depends on it.
https://github.com/plotly/plotly.py/blob/b7ad5433c4e0882715781fa6c4816fc7fff62965/packages/python/plotly/plotly/figure_factory/_ternary_contour.py#L11

**Comment by nicolaskruchten** [comment]
One of our figure factories depends on scikit-image, yes, but not the library as a whole.

**Comment by nicolaskruchten** [comment]
Related: #1829

**Comment by nicolaskruchten** [comment]
So the answer is that in 4.2 we accidentally made all figure factories depend on scikit-image, rather than just the one that needs it, and we'll fix that.

**Comment by nicolaskruchten** [comment]
Fixed in 4.2.1
