### ISSUE TITLE
ValueError: "plotlywidget@1.2.0" is not a valid npm package

### ISSUE THREAD

**Issue by BielStela** [plotly/plotly.py#1844]
Trying to follow the readme to make it work in jupyterlab but it doesn't work.
the line `jupyter labextension install plotlywidget@1.2.0 --no-build` outputs:
```
An error occured.
ValueError: "plotlywidget@1.2.0" is not a valid npm package
```

**Comment by nicolaskruchten** [comment]
That's odd... version 1.2.0 is indeed on NPM now? https://www.npmjs.com/package/plotlywidget

**Comment by BielStela** [comment]
Stills failing :(

**Comment by BielStela** [comment]
Tried with a fresh conda env following the readme step by step. The first issue is  `conda install -c plotly plotly=4.2.1` which gives:
```
CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.anaconda.org/plotly/noarch/plotly-4.2.1-py_0.tar.bz2>
```
I installed plotly from the default channel but the version is 4.1.1 instead of 4.2.1.
Then, again, I still get `ValueError: "plotlywidget@1.2.0" is not a valid npm package`

**Comment by BielStela** [comment]
The output log of npm is:
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/home/biel/anaconda3/envs/climate/bin/node',
1 verbose cli   '/home/biel/anaconda3/envs/climate/bin/npm',
1 verbose cli   'pack',
1 verbose cli   'plotlywidget@1.2.0'
1 verbose cli ]
2 info using npm@6.9.0
3 info using node@v12.4.0
4 verbose npm-session bb39a0dd3ba6786e
5 http fetch GET 304 https://registry.npmjs.org/plotlywidget 160ms (from cache)
6 silly pacote version manifest for plotlywidget@1.2.0 fetched in 168ms
7 silly tarball no local data for plotlywidget@1.2.0. Extracting by manifest.
8 http fetch GET 304 https://registry.npmjs.org/plotlywidget 148ms (from cache)
9 timing npm Completed in 705ms
10 error cb() never called!
11 error This is an error with npm itself. Please report this error at:
12 error <https://npm.community>
```

Hope it helps!

**Comment by BielStela** [comment]
:rainbow: I found a fix :rainbow: 
Doing `sudo npm cache clean --force` fixed the issue.
But don't know what, how nor why it worked.

**Comment by nicolaskruchten** [comment]
Great, glad it worked for you in the end! Clearly the NPM cache was just old and not refreshing.

**Comment by soerendip** [comment]
I still get this error. Even after cleaning the cache.
