### ISSUE TITLE
imshow function in plotly.py: discussion

### ISSUE THREAD

**Issue by emmanuelle** [plotly/plotly.py#1847]
Now that an`Image` trace is going to be in the next release of `plotly.py`, it would be great to have a corresponding function in `plotly.express`. However, we might have to modify a bit the logic of the internal of `px` functions. 

Indeed, `px` functions defined in `px._core` work with pandas Dataframes, which correspond to columnar data, whereas images are intrinsically 2D  (with both dimensions playing the same role). One possibility (which I'm in favor of) is to consider that the role of `px` is to provide a high-level **functional** API, and that it's fine to write a separate `px.image` function which would take a 2D array as input. Accepting `xarrays` would be good too (catching dimensions names for axis titles for example). 

Possible keyword arguments in the spirit of `px` functions:
- `animation_frame`: in the case of 3d+RGB arrays / xarray one could animate along one of the axis, like what is done https://plot.ly/python/visualizing-mri-volume-slices/
- `facet_row`/`facet_col` : could be nice to display line profiles of intensity of columns and rows, a bit like https://www.researchgate.net/profile/Hany_Ammar2/publication/3455251/figure/fig6/AS:669091962581005@1536535363296/Grayscale-line-profiles-of-the-input-image-the-upper-horizontal-line-profile-illustrates.ppm 
- displaying in a facet the histogram of R, G and B channels could be nice too
(and of course we would have the usual `hover_data`, `custom_data` etc.)

**Comment by emmanuelle** [comment]
This viz 
![image](https://user-images.githubusercontent.com/263366/67539878-87d46a00-f6b1-11e9-962b-b681ddc7e53d.png) is also nice

**Comment by emmanuelle** [comment]
For the dimension of the data, we'll have the same issue if we write `px` functions for `Isosurface` for example: the `go` trace takes 1d arrays for `x`, `y` and `z` for arguments, but it would be much nicer to be able to pass a 3d field (3d array), where the `x` and `y` would be implicit (grids of indices).

**Comment by emmanuelle** [comment]
Would love to hear your thoughts @nicolaskruchten @jonmmease @Mahdis-z @empet

**Comment by emmanuelle** [comment]
we also have to decide whether we write an `image` function and an `imshow` function which can take grayscale (resulting in a `Heatmap` trace) and color (resulting in an `Image` trace) arrays. I feel ok about relaxing the actual situation where one `px` function corresponds to one single `go` trace since as a user I had never really thought about this, but there is room for discussing this point :-).

**Comment by nicolaskruchten** [comment]
My feeling is that we want `px`-like functions (i.e. always give the same kind of trace!) called `matrix_heatmap`, `matrix_contour`, `matrix_surface` and `matrix_image` that accept no dataframe (we already set the precedent for this with the recent refactor), and 2d data for `z`, and as many of the existing `px`-like kwargs as we can manage. The logic behind the `matrix_*` name is that we already have `density_heatmap` and `density_contour` which produce `Histogram2d` and `Histogram2dContour` traces, respectively.

On top of that, we want a separate `imshow` function does something smarter/more aligned with matplotlib's `imshow`, and that maybe doesn't have to live under `plotly.express` but maybe under `plotly` or `plotly.image`. This one would choose the trace type based on the input. Let's write it first and figure out where to put it at the end :)

**Comment by emmanuelle** [comment]
Thank you for your thoughts @nicolaskruchten! Regarding the constraint of having `px` functions giving always the same kind of trace I'm not sure that this is something that users are really aware of / attached to. But I'm fine with starting to write something first :-).

**Comment by nicolaskruchten** [comment]
OK cool. If you want to start with the `imshow` part I can probably handle the `px` versions that I'm already familiar with/I'm the one with the strong opinions on ;)

**Comment by nicolaskruchten** [comment]
@emmanuelle I think this one is "mission accomplished" right?

**Comment by nicolaskruchten** [comment]
Did we capture any of the "additional features" in another issue somewhere? Like providing x and y axis categories or something like that?
