### ISSUE TITLE
Uncaught Error: Load timeout for modules: plotly

### ISSUE THREAD

**Issue by huhuhang** [plotly/plotly.py#1849]
When I use plotly in Jupyter Notebook, it can't be rendered. 

![CleanShot 2019-10-28 at 18 06 56](https://user-images.githubusercontent.com/5147530/67669924-cddd4680-f9ad-11e9-9559-1b4ef5832770.png)

Chrome Console：`Uncaught Error: Load timeout for modules: plotly`。

```
import plotly
import plotly.graph_objs as go
plotly.offline.init_notebook_mode(connected=True)

trace = {'x':[1,2],'y':[1,2]}
data = [trace]
fig = go.Figure(data = data, layout = {})

plotly.offline.iplot(fig)
```

I tried it on multiple devices and different browsers, and that's still the problem.

![CleanShot 2019-10-28 at 18 05 11](https://user-images.githubusercontent.com/5147530/67669801-8eaef580-f9ad-11e9-9f66-2e1d4be29ebb.png)

**Comment by huhuhang** [comment]
The problem is caused by poor network and has been solved.

**Comment by eromoe** [comment]
![image](https://user-images.githubusercontent.com/3938751/97532930-51cb7380-19f2-11eb-8deb-09b1b8cf7628.png)

happen in China

**Comment by vujacicsun** [comment]
> The problem is caused by poor network and has been solved.

what? poor network? Your Jupyter Notebook is running on remote server?

I have the same error on localhost running Jupyter Notebook Server

**Comment by Abdelgha-4** [comment]
I have the same issue running 
from a kaggle notebook
