### ISSUE TITLE
Blurry PNG

### ISSUE THREAD

**Issue by xbbld4x** [plotly/plotly.py#1852]
I have created several charts and then save them to my desktop as png. However, the png images seem blurry after saving.

Is there a way to increase the dpi or “sharpness” of the png images when saving?

**Comment by nicolaskruchten** [comment]
How are you saving charts to PNG? Can you share some sample code please?

**Comment by sursu** [comment]
I've dealt with this issue before when static image creation was being done with `pio.to_image()`.
The solution I found was to play with the `width`, `height`, and `scale` parameter which, think, you can pass to the `fig.write_image` function as well.
The combination you need is not always obvious.
In Mathematica, for instance, there is an option to the `Export` function called `ImageResolution` which is clear what it does.

But, if PNG is not a requirement, you may want to try the `svg` format first.

**Comment by xbbld4x** [comment]
Ok, thank you. Unfortunately, png is a requirement. I have tried playing with the width and height parameters, but the images still seem blurry (though perhaps I am doing it wrong).

I didn't know if there was something like in matplotlib where you can specify the dpi when saving plots to png. Thank you for your response though.

**Comment by xbbld4x** [comment]
I took a look and I think adjusting the scale is exactly what I needed! Thank you for the help.
