### ISSUE TITLE
Can't hide colorbar/scale via marker layout attributes with plotly express figures

### ISSUE THREAD

**Issue by joelostblom** [plotly/plotly.py#1858]
I tried to update the colorbar/colorscale via the marker attributes in `update_traces` (and also using a template), but none of the ones related to the colorbar has any effect:

```python
import plotly.express as px

iris = px.data.iris()
fig = px.scatter(iris, 'sepal_width', 'sepal_length', 'sepal_length')
fig.update_traces(opacity=0.5, marker=dict(showscale=False, reversescale=True, cmin=6, size=20))
```

![image](https://user-images.githubusercontent.com/4560057/68069281-5b2deb80-fd5e-11e9-8983-07558a1405c2.png)

<details>
<summary><code>print(fig)</code></summary>
<pre>
Figure({
    'data': [{'hoverlabel': {'namelength': 0},
              'hovertemplate': 'sepal_width=%{x}<br>sepal_length=%{marker.color}',
              'legendgroup': '',
              'marker': {'cmid': 0,
                         'color': array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8, 4.3,
                                         5.8, 5.7, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. , 5. , 5.2,
                                         5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4, 5.1, 5. , 4.5,
                                         4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 7. , 6.4, 6.9, 5.5, 6.5, 5.7,
                                         6.3, 4.9, 6.6, 5.2, 5. , 5.9, 6. , 6.1, 5.6, 6.7, 5.6, 5.8, 6.2, 5.6,
                                         5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7, 6. , 5.7, 5.5, 5.5, 5.8, 6. ,
                                         5.4, 6. , 6.7, 6.3, 5.6, 5.5, 5.5, 6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2,
                                         5.1, 5.7, 6.3, 5.8, 7.1, 6.3, 6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4,
                                         6.8, 5.7, 5.8, 6.4, 6.5, 7.7, 7.7, 6. , 6.9, 5.6, 7.7, 6.3, 6.7, 7.2,
                                         6.2, 6.1, 6.4, 7.2, 7.4, 7.9, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6. , 6.9,
                                         6.7, 6.9, 5.8, 6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9]),
                         'coloraxis': 'coloraxis',
                         'reversescale': True,
                         'showscale': False,
                         'size': 20,
                         'symbol': 'circle'},
              'mode': 'markers',
              'name': '',
              'opacity': 0.5,
              'showlegend': False,
              'type': 'scatter',
              'x': array([3.5, 3. , 3.2, 3.1, 3.6, 3.9, 3.4, 3.4, 2.9, 3.1, 3.7, 3.4, 3. , 3. ,
                          4. , 4.4, 3.9, 3.5, 3.8, 3.8, 3.4, 3.7, 3.6, 3.3, 3.4, 3. , 3.4, 3.5,
                          3.4, 3.2, 3.1, 3.4, 4.1, 4.2, 3.1, 3.2, 3.5, 3.1, 3. , 3.4, 3.5, 2.3,
                          3.2, 3.5, 3.8, 3. , 3.8, 3.2, 3.7, 3.3, 3.2, 3.2, 3.1, 2.3, 2.8, 2.8,
                          3.3, 2.4, 2.9, 2.7, 2. , 3. , 2.2, 2.9, 2.9, 3.1, 3. , 2.7, 2.2, 2.5,
                          3.2, 2.8, 2.5, 2.8, 2.9, 3. , 2.8, 3. , 2.9, 2.6, 2.4, 2.4, 2.7, 2.7,
                          3. , 3.4, 3.1, 2.3, 3. , 2.5, 2.6, 3. , 2.6, 2.3, 2.7, 3. , 2.9, 2.9,
                          2.5, 2.8, 3.3, 2.7, 3. , 2.9, 3. , 3. , 2.5, 2.9, 2.5, 3.6, 3.2, 2.7,
                          3. , 2.5, 2.8, 3.2, 3. , 3.8, 2.6, 2.2, 3.2, 2.8, 2.8, 2.7, 3.3, 3.2,
                          2.8, 3. , 2.8, 3. , 2.8, 3.8, 2.8, 2.8, 2.6, 3. , 3.4, 3.1, 3. , 3.1,
                          3.1, 3.1, 2.7, 3.2, 3.3, 3. , 2.5, 3. , 3.4, 3. ]),
              'xaxis': 'x',
              'y': array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8, 4.3,
                          5.8, 5.7, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. , 5. , 5.2,
                          5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4, 5.1, 5. , 4.5,
                          4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 7. , 6.4, 6.9, 5.5, 6.5, 5.7,
                          6.3, 4.9, 6.6, 5.2, 5. , 5.9, 6. , 6.1, 5.6, 6.7, 5.6, 5.8, 6.2, 5.6,
                          5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7, 6. , 5.7, 5.5, 5.5, 5.8, 6. ,
                          5.4, 6. , 6.7, 6.3, 5.6, 5.5, 5.5, 6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2,
                          5.1, 5.7, 6.3, 5.8, 7.1, 6.3, 6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4,
                          6.8, 5.7, 5.8, 6.4, 6.5, 7.7, 7.7, 6. , 6.9, 5.6, 7.7, 6.3, 6.7, 7.2,
                          6.2, 6.1, 6.4, 7.2, 7.4, 7.9, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6. , 6.9,
                          6.7, 6.9, 5.8, 6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9]),
              'yaxis': 'y'}],
    'layout': {'coloraxis': {'colorbar': {'title': {'text': 'sepal_length'}},
                             'colorscale': [[0.0, '#0d0887'], [0.1111111111111111,
                                            '#46039f'], [0.2222222222222222,
                                            '#7201a8'], [0.3333333333333333,
                                            '#9c179e'], [0.4444444444444444,
                                            '#bd3786'], [0.5555555555555556,
                                            '#d8576b'], [0.6666666666666666,
                                            '#ed7953'], [0.7777777777777778,
                                            '#fb9f3a'], [0.8888888888888888,
                                            '#fdca26'], [1.0, '#f0f921']]},
               'height': 600,
               'legend': {'tracegroupgap': 0},
               'margin': {'t': 60},
               'template': '...',
               'xaxis': {'anchor': 'y', 'domain': [0.0, 0.98], 'title': {'text': 'sepal_width'}},
               'yaxis': {'anchor': 'x', 'domain': [0.0, 1.0], 'title': {'text': 'sepal_length'}}}
})
</pre>
</details>

When I try the same thing with a figure created without plotly express, it works as expected (note that I change between True and False in this example, just to show that all colorbar marker attributes work as expected):

```python
import plotly.graph_objects as go
import numpy as np

fig = go.Figure(data=go.Scatter(
    y = np.random.randn(500),
    mode='markers',
    marker=dict(
        size=16,
        color=np.random.randn(500), #set color equal to a variable
        colorscale='Viridis', # one of plotly colorscales
        showscale=False,
    )
))

fig.update_traces(opacity=0.5, marker=dict(showscale=True, reversescale=True, cmid=0, size=20))
```

![image](https://user-images.githubusercontent.com/4560057/68069375-dd6adf80-fd5f-11e9-9ecd-86e926aa4f6f.png)

<details>
<summary><code>print(fig)</code></summary>
<pre>
Figure({
    'data': [{'marker': {'cmid': 0,
                         'color': array([-0.58207535,  0.79725625, -1.54958717, ...,  0.01890008,  1.49074695,
                                          1.6721    ]),
                         'colorscale': [[0.0, '#440154'], [0.1111111111111111,
                                        '#482878'], [0.2222222222222222,
                                        '#3e4989'], [0.3333333333333333,
                                        '#31688e'], [0.4444444444444444,
                                        '#26828e'], [0.5555555555555556,
                                        '#1f9e89'], [0.6666666666666666,
                                        '#35b779'], [0.7777777777777778,
                                        '#6ece58'], [0.8888888888888888,
                                        '#b5de2b'], [1.0, '#fde725']],
                         'reversescale': True,
                         'showscale': True,
                         'size': 20},
              'mode': 'markers',
              'opacity': 0.5,
              'type': 'scatter',
              'y': array([-0.29207826,  1.35449056, -0.52644856, ..., -0.90899513,  1.79810226,
                           0.06748418])}],
    'layout': {'template': '...'}
})
</pre>
</details>

Viewing the printed figure dicts shows that there is a coloraxis attribute created with plotly express, not sure if that is what makes the axis impossible to hide or if I am just using the wrong approach here.

**Comment by nicolaskruchten** [comment]
Indeed, Plotly Express doesn't define its colorbar per-trace but rather figure-wide using `layout.coloraxis`. You can control this colorbar's configuration via [`layout.coloraxis.colorbar` attributes](https://plot.ly/python/reference/#layout-coloraxis-colorbar). You can control whether or not this colorbar is shown [via `layout.coloraxis.showscale`](https://plot.ly/python/reference/#layout-coloraxis-showscale).

**Comment by nicolaskruchten** [comment]
(The reason things are done this way is so that facetted traces can share the same color scale, BTW :)

**Comment by joelostblom** [comment]
Thanks for the explanation! I did notice that there was both `fig.update_traces(showlegend=False)` and `fig.update(layout_showlegend=False)` for the legend. I tried `fig.update(layout_showscale=False)` but missed the coloraxis part which makes sense now that I look at how the templates are designed.

It would be helpful if there was a warning message when trying to use the marker properties for plotly express figures, pointing towards the correct usage layout.coloraxis usage with figure.update instead of silently not changing the figure.

I think the error message from `figure.update_traces` is super useful since it list all the properties that can be used which makes it very easy to explore. Would it be possible to add a similar error message to `figure.update`?

**Comment by nicolaskruchten** [comment]
So all update methods raise those helpful exceptions. The challenge here is that a figure produces by PX is the same as any other, and so setting layout color attributes isn’t wrong in this case, it just happens to be ignored at the JS level. 

Trying to “predict” what the JS layer will do and raising Python-level exceptions is pretty daunting to get right in the long term so in general we don’t do it at the moment :)

**Comment by joelostblom** [comment]
Ah ok, I see how it can be tricky to raise the warning only for certain properties if there is no signal emitted from the JS layer.

My comment regarding the helpful error messages is for when I try something that does generate an error, e.g. `fig.update(test=0)` which will just give back the error message `KeyError: 'test'`. On the other hand, if I do `fig.update_traces(test=0)` it raises the error `ValueError: Invalid property specified for object of type plotly.graph_objs.Scatter: 'test'` and then lists all the valid properties, which is the super helpful part that I would love to get from `fig.update` as well.

Thanks for the heads up in the other issue about the upcoming release, will try to get a template PR up soon!

**Comment by nicolaskruchten** [comment]
Interesting re update()... it would be helpful if you could open a separate issue for that. You do get error messages for `fig.update(layout_test=1)` though, right?

**Comment by joelostblom** [comment]
Nope, I opened https://github.com/plotly/plotly.py/issues/1860 to discuss further.

Before closing this issue, I want to ask if you think it is feasible to add an indication in the docstring for the per trace parameters that do not work with plotly express figures and indicate that a figure wide parameter should be used instead. Or would this be too much work for too little benefit, or maybe not possible at all?

**Comment by nicolaskruchten** [comment]
> per trace parameters that do not work with plotly express figures

That's the thing: from a schema perspective, all trace parameters are allowed within all figures, whether those figures were produced by Plotly Express or not. Furthermore, a figure and/or a trace doesn't "know" that it's been produced with Plotly Express in any sense: once they come out, they're just normal `graph_objects`, to which anyone can add any new trace, with any parameters. I wouldn't want to have PX 'tag' its figures somehow and lock them down with special error messages, as that would really limit what people can do with these figures in my opinion.

All that said, I do recognize that it's not sufficiently clear in our docs how to mutate PX figures to get various desired outcomes, but I'd rather fix that at the documentat level than at the object/error-message level. For example, `coloraxis` isn't actually documented anywhere yet, but we're working on it. Any contributions you might have to our documentation would be heartily welcomed! You can click on the "Edit this page on Github" link in the top-right of any page under https://plot.ly/python/ and submit a PR :)

**Comment by joelostblom** [comment]
> all trace parameters are allowed within all figures

Yes sorry, I expressed myself imprecisely. I should have said something like "per trace parameters that don't appear to work with plotly express figures because the figure does not change visually" to highlight what I was thinking when trying the parameter but seeing neither a visual change nor an error message.

I think the docs can be a good idea (and maybe even a static note in the docstrings for parameters that you know won't work, even if the trace itself can't tell and give that info dynamicaly?). I will have a look but won't promise a PR here because I am a bit swamped with things at the moment, so let's see.

**Comment by nicolaskruchten** [comment]
> don't appear to work with plotly express figures because the figure does not change visually

I see what you're getting at, but the rules for expressing what does and doesn't result in a visual change are *really* complicated and implemented in Javascript. Replicating them in Python would be a large undertaking, and would undoubtedly diverge from the underlying implementation, leading to even more confusion :)

Also, it would break otherwise fine code like this by imposing a stricter order than necessary:

```python
fig.update_traces(<something that isn't currently visible because layout.foo==False>)
fig.update_layout(foo=True)
```

**Comment by joelostblom** [comment]
:+1: Thanks for explaining!

**Comment by aheze** [comment]
In [v5.1.0](https://github.com/plotly/plotly.py/releases/tag/v5.1.0), this works for me:

```
fig.update_coloraxes(showscale=False)
```

Before | After
--- | ---
[![Bar chart with gradient color bar on right side][1]][1] | [![Only bar chart][2]][2]


  [1]: https://i.stack.imgur.com/dJ0ru.png
  [2]: https://i.stack.imgur.com/2lJhK.png
