### ISSUE TITLE
FigureWidget does work not from inside an if statement

### ISSUE THREAD

**Issue by sursu** [plotly/plotly.py#1861]
Encountered in Jupyter Lab.

Take the following 2 cases:
```python
fig = go.FigureWidget()
fig
```
&
```python
silent=False

if not silent:
    fig = go.FigureWidget()
    fig
```
The first one produces a figure, the second one does not.
Why don't they behave similarly?

If I use the `@interact` decorator in the second case.
e.g.
```python
if not silent:
    fig = go.FigureWidget()
    fig.add_scatter()

    @interact(s=(3,5))
    def update(s=3):
        with fig.batch_update():
            fig.data[0].y = np.random.normal(size=s)
    fig
```
the slider appears, but the figure does not.

**Comment by nicolaskruchten** [comment]
The way widgets work is that they render if they are the “output” of a cell, i.e. the last statement. 

For @interact to work, the widget must be returned from the function.

**Comment by sursu** [comment]
@nicolaskruchten I undestand that it currently works like that. But, for the future, is there a reason for the widget not to work when returned from the `if` statement? An instance created with `go.Figure()` does.

**Comment by nicolaskruchten** [comment]
`if` statements don't actually return anything, no. For a normal `go.Figure()` to work within an `if` statement you must call `fig.show()` on it.

These limitations aren't really Plotly limitations but rather Jupyter/Python limitations that we can't do much about :)

**Comment by nicolaskruchten** [comment]
For example, this doesn't render anything, as expected:

![image](https://user-images.githubusercontent.com/203523/68090533-d4067380-fe42-11e9-921a-991062c639af.png)

**Comment by sursu** [comment]
Yes, right with `fig.show()`.

So, not possible?

**Comment by jasongrout** [comment]
Use the `display` command:

```
if True:
    fig = go.Figure()
    display(fig)
```

**Comment by sursu** [comment]
TIL about `display` :)

Thanks a lot!

**Comment by jasongrout** [comment]
`display` is what IPython calls automatically on the last top-level expression to display it in your first example.
