### ISSUE TITLE
Set default barmode to overlay for histograms in plotly express

### ISSUE THREAD

**Issue by joelostblom** [plotly/plotly.py#1865]
Seeing this histogram makes me believe that there are more observations in the red distribution compared to the purple one.

![image](https://user-images.githubusercontent.com/4560057/68098688-6dbf3680-febe-11e9-8b6b-78339030f09a.png)

However, this turns out to be because the default behavior for `plotly.express.histogram` is to stack histograms distributions instead of anchoring each distribution at zero.

![image](https://user-images.githubusercontent.com/4560057/68098864-7feda480-febf-11e9-8cc5-d4df87692f38.png)

This is trivial to change by setting `barmode='overlay'`, but I would argue that this is an unexpected default behavior that could lead to some unfortunate misinterpretations of data for peole that do not read the full docstring (so many) before using the function. If the default behavior was "overlay" it would immeidately be clear what is happening and anyone interested in changing would be prompted to look in the docstring for the relevant parameter.

**Comment by nicolaskruchten** [comment]
It's a bit confusing, yeah, although a hover will clear it up pretty quickly.

**Comment by joelostblom** [comment]
Yes a hover would clarify the count for each bin, but the distributions are still difficult to compare visually if they are stacked rather than starting from the same axis value, and hovering each bin is not as effective as comparing them by eye.

When making marginal histograms, `barmode='overlay'` and `opacity=0.5` are used by default, so it would be good if the behavior was consistent between standalone and marginal histograms.

![image](https://user-images.githubusercontent.com/4560057/68199904-2ff60700-ffbf-11e9-8f6e-42f402d01052.png)
