### ISSUE TITLE
support axhline/axvline exports from mpl with annotations in plotly

### ISSUE THREAD

**Issue by theengineear** [plotly/plotly.py#188]
Since axh(v)lines live in two coordinate systems, we haven't been exporting them. However, a nice solution is to add a headless arrow from an annotation in Plotly which can live just fine in both data _and_ page coordinates.

**Comment by chriddyp** [comment]
we now have shapes and lines!

**Comment by theengineear** [comment]
w00t! this is great. Maybe it's worth patching together 1.4.x support for mpl and adding this in? I'm not sure how much effort that would take, but I think it might be worth it.

**Comment by chriddyp** [comment]
this may be naive (and slow), but could we just do rectangles and lines for all the MPL stuff that we can't crawl?

**Comment by theengineear** [comment]
sorta. we still need to figure out *what* some of those things are. For example, we want to make new annotations, not draw annotation boxes from mpl. Also we want to make the legend, not draw the little legend boxes.

I think, yes, we get a lot of flexibility with this new info, but we'll end up adding confusing things to the plots if we're not careful.

**Comment by oars** [comment]
Is there a way to generate axhline/axvline directly in plotly as a workaround?

I realize I can use the svg shapes and lines, but they break the autoscaling of the chart.

**Comment by oars** [comment]
I realize now, the way to do this is to use the yref='paper'.

**Comment by jmarrec** [comment]
+1

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
