### ISSUE TITLE
The Image trace is not rendered on Plotly cloud

### ISSUE THREAD

**Issue by empet** [plotly/plotly.py#1895]
I installed plotly 4.3.0 and played with the new trace type. It works fine in Jupyter notebook:

![blackwhite](https://user-images.githubusercontent.com/3627253/68679181-0d885e80-0568-11ea-9fc9-77d3ef9420d4.png)

![pixelated](https://user-images.githubusercontent.com/3627253/68679206-19742080-0568-11ea-8c02-6f76fd6c8e7f.png)

![plotly-image](https://user-images.githubusercontent.com/3627253/68679228-21cc5b80-0568-11ea-9464-b710d502a063.png)

but no one of these images is rendered on Plotly cloud [https://plot.ly/~empet/15293/#/](https://plot.ly/~empet/15293/#/).

**Comment by nicolaskruchten** [comment]
Yep, should be another couple of days :)

**Comment by nicolaskruchten** [comment]
We haven’t even announced this version or the docs on the forum yet, so if you could hold off on publicizing this until then, I’d really appreciate it :)

Should be this afternoon for the docs and forum post!

**Comment by empet** [comment]
OK, I saw Jon's announcement a few hours ago, and following the Image attributes described in  plotly.js I was able to define the traces corresponding to the above images. There is no hurry to be rendered on Plotly cloud

**Comment by emmanuelle** [comment]
A brand new tutorial featuring this chart is to be merged today :-) https://github.com/plotly/plotly.py-docs/pull/192

**Comment by nicolaskruchten** [comment]
OK so the official announcement is out! https://community.plot.ly/t/announcing-plotly-py-4-3-and-4-2-and-4-1/31245

I'll update Chart Studio Cloud very soon, sorry for the delay :) Our priority these days is Plotly.py first!

**Comment by nicolaskruchten** [comment]
Sorry, "very soon" turned out to be 13 days ;)
