### ISSUE TITLE
Resampling before rendering

### ISSUE THREAD

**Issue by baosws** [plotly/plotly.py#1897]
Hi,
I'm trying to plot a 3D Surface of a raster image of size 3601x3601 in jupyter lab (offline mode), which has not been succeed on my pc (jupyter lab breaks after consuming around 1GB of VRAM, while I have 8GB).
My assumption is that the image is too big for plotly to handle, so my workaround was to downscale the image by the factor of 1/5 and the plot showed up, everything went fine. However the xaxis, yaxis and zaxis don't have the original range (before scaling), which I desire to have.
So my question is: is there any option to automatically plot the rescaled image without changing the axes? Or at least an option to map old axes to new ones?

**Comment by emmanuelle** [comment]
Hi, you can pass `x` and `y` parameter to `go.Surface` (see https://plot.ly/python-api-reference/generated/plotly.graph_objects.Surface.html) to ensure that the range will always be the same (use for example `np.linspace(vmin, vmax, npoints)`).

**Comment by emmanuelle** [comment]
We should add an example of a `go.Surface` using `x` and `y` in https://plot.ly/python/3d-surface-plots/

**Comment by baosws** [comment]
@emmanuelle Oh that's one easy solution I haven't thought of. Thank you a lot.
But how can I keep the z range unchanged? Because I scaled all 3 axes down to retain the relative ratios.

**Comment by emmanuelle** [comment]
Hum not sure why you would scale the `z`?? Anyway you can always multiply `z` by a scaling factor before passing it to `go.Surface`. You can also change the aspect ratio of 3d axes as described here https://plot.ly/python/3d-axes/#fixed-ratio-axes

**Comment by baosws** [comment]
Okay I've found the solution for that, using aspectratio.
Thank you for your support.
But I do think there should be a consideration for more optimized rendering.
