### ISSUE TITLE
Streaming Heatmap

### ISSUE THREAD

**Issue by petered** [plotly/plotly.py#190]
Hi all, 

I couldn't find any examples for doing a streaming heatmap in plotly, and it's not completely obvious from the streaming documentation.  So, here is an example:

```
import plotly.plotly as py
import plotly.graph_objs as pyg
import plotly.tools as tls
import numpy as np
import time
# Auto-login should happen if you're set up properly

# You need to generate your own stream token from https://plot.ly/settings/api
STREAM_TOKEN = 'i88971hg1x'  
heatmap = pyg.Heatmap(stream = dict(token=STREAM_TOKEN))
plot_data = pyg.Data([heatmap])
py.plot(plot_data)

get_data = lambda: np.random.randn(30, 40)
s = py.Stream(STREAM_TOKEN)
s.open()
t = time.time()
n_frames = 100
for _ in xrange(n_frames):
    s.write(dict(z=get_data(), type = 'heatmap'))
print 'Mean FPS: %s' % (n_frames/(time.time()-t))
s.close()
```

It lets me write at about 80 FPS, but the plot itself only updates at about 5FPS by the looks of it - and updates lag way behind the execution of the code, so it's not exactly real time.  Better would be if it just discarded updates when it couldn't keep up.

Also, every second time I run the program, I get

```
Traceback (most recent call last):
  File "plotly_stream_demo.py", line 10, in <module>
    py.plot(plot_data)
  File "/Users/peter/projects/tests/venv/lib/python2.7/site-packages/plotly/plotly/plotly.py", line 221, in plot
    raise exceptions.PlotlyAccountError(res['error'])
plotly.exceptions.PlotlyAccountError: Uh oh, an error occured on the server. 
```

Is there any easy fix to these issues?  It'd be great to have real-time streaming heatmaps.  Even real-time streaming images would be fine - if I could just send over uint-8 RGB data as a numpy array, that would work.

**Comment by theengineear** [comment]
@petered , the lag is simply due to the draw speed of the browser. Here are a couple options for you:

* try using the `surface` type instead of a `heatmap`, if that makes sense for your data. It draws much faster in the browser.
* you can ditch the images client-side manually

The time it takes to send the data and draw it is likely *always* going to lag the computation time for the data itself. So in your loop, you could consider slowing things down to match that lag:

```python
for _ in xrange(n_frames):
    s.write(dict(z=get_data(), type = 'heatmap'))
    time.sleep(0.2)
```

Again, do try the surface plot as it will cruise along much faster:

```python
import plotly.plotly as py
import plotly.graph_objs as pyg
import plotly.tools as tls
import numpy as np
import time

get_data = lambda: np.random.randn(30, 40)

# stream tokens are saved locally in your credentials as well
STREAM_TOKEN = py.get_credentials()['stream_ids'][0]
heatmap = pyg.Surface(stream=pyg.Stream(token=STREAM_TOKEN))
plot_data = pyg.Data([heatmap])
py.plot(plot_data)

s = py.Stream(STREAM_TOKEN)
s.open()
n_frames = 100
for _ in xrange(n_frames):
    s.write(dict(z=get_data(), type='surface'))
    time.sleep(0.08)
s.close()
```

**Comment by petered** [comment]
@theengineear 
Thanks for your response.  Surface is faster, which is odd, because it creates a 3-D rendering, when all I want is an image.  I guess I could view it from the top, to make it look like a heatmap, and turn off interpolation somehow, but this seems wrong.  Why does heat-map take so long?  Ditching images on client-side manually - I take it that involves writing some JavaScript somewhere, or is there a built-in plotly option for that (couldn't find one).

**Comment by jonmmease** [comment]
Closing for now as it sounds like the initial issue was resolved (or worked around).  Feel free to chime in if that's not the case!

**Comment by philpil** [comment]
> @philpil there have been lots of changes in the last 5 years since this was closed ;) Perhaps describe your use case in a post on the furum https://community.plotly.com/ and see what suggestions people have?

its okay I made a work around so the data is updated and then i use plotly.update to take that latest data and update my x,y,z
