### ISSUE TITLE
No figure displayed in Jupyter lab (works in notebook)

### ISSUE THREAD

**Issue by YubinXie** [plotly/plotly.py#1901]
I followed the installation in the readme. 4.3.0 plotly, latest jupyter lab > 1.1.4 ipywidgets==7.5.1 

But when I plot in jupyter lab, nothing returned. However, it works in notebook.
![119924D8-9C8B-4399-B26E-D955C75DF9AF](https://user-images.githubusercontent.com/16257776/68829344-9db4c980-0676-11ea-971f-44c5133c681f.png)

**Comment by nicolaskruchten** [comment]
Did you install the very latest versions of the extensions? See our JLab Troubleshooting guide for details: https://plot.ly/python/troubleshooting/#jupyterlab-problems

If you're still having issues, can you provide the output of `jupyter labextension list` please?

**Comment by YubinXie** [comment]
JupyterLab v1.1.4
Known labextensions:
   app dir: /Users/xiey/miniconda3/share/jupyter/lab
        @jupyterlab/toc v2.0.0-rc.0  enabled  OK
        jupyter-webrtc v0.4.3  enabled  OK
        plotlywidget v1.3.0  enabled  OK

**Comment by YubinXie** [comment]
I might miss the jupyter plotly. let me check it.

**Comment by YubinXie** [comment]
After installing jupyerplotly it works. Thanks!
