### ISSUE TITLE
px.imshow() not working in vscode python interactive and notebook mode

### ISSUE THREAD

**Issue by YoniChechik** [plotly/plotly.py#1902]
```
#%%
import plotly.express as px
import cv2

im = cv2.imread("chess.jpg")

fig = px.imshow(im)
fig.show()


# %%
import plotly.express as px
iris = px.data.iris()
fig = px.scatter(iris, x="sepal_width", y="sepal_length")
fig.show()
```

while the same code works in google colab and in regular running of script in vscode (figure displayed at chrome), it doesn't workin bothe vscode python interactive mode and notebook mode:

works in colab:
![image](https://user-images.githubusercontent.com/16686924/68839865-3aed1d80-06ca-11ea-8eda-ca50a50c27cb.png)

doesn't work in interactive

![image](https://user-images.githubusercontent.com/16686924/68840019-89022100-06ca-11ea-911d-f36d182820af.png)

other plots work:
![image](https://user-images.githubusercontent.com/16686924/68840078-ae8f2a80-06ca-11ea-8558-721828a6b599.png)

also doesn't work as ipynb in vscode (scatter does work...):
![image](https://user-images.githubusercontent.com/16686924/68840122-c23a9100-06ca-11ea-85b6-257817af9fa8.png)

**Comment by nicolaskruchten** [comment]
Yes, VSCode Python bundles its own version of Plotly.js, which is not the latest one at the moment. I will submit a PR to them and then it takes a few weeks for that to ripple through to a release of theirs.

**Comment by YoniChechik** [comment]
works
