### ISSUE TITLE
Support smooth animations in Scatter3D?

### ISSUE THREAD

**Issue by mjlbach** [plotly/plotly.py#1904]
I'm not sure if this is implemented upstream in the javascript library yet, but currently Scatter graph objects show smooth transitions between frames, whereas Scatter3D show abrupt transitions. I was looking to replace ipyvolume for some animations, and this is one current disadvantage.

**Comment by TKaluza** [comment]
@mjlbach 
Why was this closed? Is this working? 
Could you perhaps provide a link to a solution, please? (or maybe provide an example, that would be awesome!)

**Comment by mjlbach** [comment]
@TKaluza It's not fixed or working, but there are better libraries for this particular purpose (vispy, ipyvolume). I've reopened the issue, but this isn't something I would implement, and I usually don't like leaving open issues I wouldn't be open to fixing.

**Comment by TKaluza** [comment]
@mjlbach I totaly agree with use on this issue. Thank you for clarification  
As far as I'm concerend this can be closed.

**Comment by nicolaskruchten** [comment]
This is indeed something that would need to be addressed in the underlying Javascript library, you can follow our progress here: https://github.com/plotly/plotly.js/issues/3456
