### ISSUE TITLE
Calculate number of bins for a Histogram that plotly would produce

### ISSUE THREAD

**Issue by stelmath** [plotly/plotly.py#1906]
Hello,

I am trying to grab the `xbins.size` `xbins.start` and `xbins.end` properties of a go.Histogram, but in this code the above properties are returned as `None `when I examine `fig` :

```
import plotly.graph_objects as go
import numpy as np

np.random.seed(1)
x = np.random.randn(20)

fig = go.Figure(data=[go.Histogram(x=x)])

fig.show()
```

![image](https://user-images.githubusercontent.com/38814495/69006321-3dec4600-0936-11ea-8800-8a5106b43504.png)

I read in the documentation that if certain properties are not passed to Histogram, then an algorithm will compute the number of bins by selecting a _nice_ size for each bin. What I am trying to do is either find this algorithm or be able to get the aforementioned properties. Ultimately I want to be able to produce [this ](https://miro.medium.com/max/1324/1*ss8c_W1U3uSPNDqUSctAzQ.jpeg)in Plotly, as I was inspired by [this blog post](https://towardsdatascience.com/advanced-histogram-using-python-bceae288e715)

**Comment by churchill1973** [comment]
Hi,
I've been stuck in the same stuff. I've read that's not possible because the autobin variable is calculated  on the render in JavaScript, could you do it? Thanks

**Comment by nicolaskruchten** [comment]
A few notes:
1. To reproduce a specific chart, you can always set `start`, `end` and either `size` or `nbins`
2. Yes, the Javascript layer computes some defaults for these if they're not provided. The relevant code is here https://github.com/plotly/plotly.js/blob/5b8b1db1386b82db747cbad239fed754e624a18f/src/plots/cartesian/axes.js#L352
3. Today, it's impossible to access these values from Python, but in an upcoming version of Plotly.py, we'll make it possible to access the Javascript-computed values. Hopefully in 4.9!

**Comment by nicolaskruchten** [comment]
I should add that a slightly different and easier way to build a plot that gives you the same or better information than the one in the article is as follows... If you use a cumulative histogram, you can just see where the bars intersect the horizontal gridlines to see the quartiles, and you can add a marginal box plot with all the options turned on: notches, outliers, mean and standard deviation :)

```python
import plotly.express as px
import numpy as np

np.random.seed(1)
x = np.random.randn(200)

fig = px.histogram(x, marginal="box", cumulative=True, histnorm="percent")
fig.update_traces(selector=dict(type="box"), boxmean='sd')
fig.update_yaxes(dtick=25)
fig.show()
```

![image](https://user-images.githubusercontent.com/203523/83335350-32c98980-a27a-11ea-94aa-d8300c8e5914.png)

**Comment by stelmath** [comment]
Ok I am closing this then. Thanks for the response @nicolaskruchten

**Comment by Raudcu** [comment]
> A few notes:
> 
>     1. To reproduce a specific chart, you can always set `start`, `end` and either `size` or `nbins`
> 
>     2. Yes, the Javascript layer computes some defaults for these if they're not provided. The relevant code is here https://github.com/plotly/plotly.js/blob/5b8b1db1386b82db747cbad239fed754e624a18f/src/plots/cartesian/axes.js#L352
> 
>     3. Today, it's impossible to access these values from Python, but in an upcoming version of Plotly.py, we'll make it possible to access the Javascript-computed values. Hopefully in 4.9!

Is it possible nowadays?

**Comment by nicolaskruchten** [comment]
Yes, you can get access to the output of the JS layer's defaults like this:

```python
import plotly.express as px

df = px.data.tips()

px.histogram(df, x="total_bill").full_figure_for_development().data[0].xbins
```

**Comment by nicolaskruchten** [comment]
Here is more information on introspection of figures: https://plotly.com/python/figure-introspection/

**Comment by Raudcu** [comment]
Wow! I can't explain to you how much I looked for it. Thank you very much @nicolaskruchten! What I don't see there is a way to get the actual count in each binning. But I can obtain it using numpy from the binning.
