### ISSUE TITLE
Steps parameter of parent data[type=indicator].gauge is not working

### ISSUE THREAD

**Issue by nalpalhao** [plotly/plotly.py#1912]
When introducing parameter steps 
For example int the 'https://plot.ly/python/bullet-charts/' Multi Bullet example, this error appears:

ValueError: Invalid property specified for object of type plotly.graph_objs.indicator.Gauge: 'steps'

    Valid properties:
        axis
            plotly.graph_objects.indicator.gauge.Axis instance or
            dict with compatible properties
        bar
            Set the appearance of the gauge's value
        bgcolor
            Sets the gauge background color.
        bordercolor
            Sets the color of the border enclosing the gauge.
        borderwidth
            Sets the width (in px) of the border enclosing the
            gauge.
        shape
            Set the shape of the gauge
        stepss
            A tuple of plotly.graph_objects.indicator.gauge.Steps
            instances or dicts with compatible properties
        stepsdefaults
            When used in a template (as
            layout.template.data.indicator.gauge.stepsdefaults),
            sets the default property values to use for elements of
            indicator.gauge.steps
        threshold
            plotly.graph_objects.indicator.gauge.Threshold instance
            or dict with compatible properties

When changing to 'stepss' the error disappears but nothing happens in terms of steps in the visualization

**Comment by emmanuelle** [comment]
Which version of plotly are you using ? (`import plotly; print(plotly.__version__)`). If you execute the notebook on binder (click the "launch binder" link at the top of the page) then it works fine..

**Comment by nalpalhao** [comment]
I'm on 4.1.0 and the problem still persists

**Comment by nalpalhao** [comment]
So apparently after upgrading to the current version 4.3.0 the problem disappeared, classic mistake I guess

**Comment by nicolaskruchten** [comment]
Sorry, this one is on us: version 4.1.0 was released with this bug and it was fixed in 4.1.1.
