### ISSUE TITLE
Clarify work with external server

### ISSUE THREAD

**Issue by dev-dsp** [plotly/plotly.py#1914]
I started orca as shown here: https://github.com/plotly/orca#method-3-docker
So I got it on 9091 port on localhost accessible

I've installed plotly==4.3.0 with latest "feature" from #1850 

Now, when running following code, I get two terminal screens of errors and cool stories about how to install that orca executable, which I actually should not have to keep in my host system when using orca *server*:
```
import plotly.io as pio
import plotly.graph_objects as go
pio.orca.config.server_url = "localhost"
pio.orca.config.port = 9091
pio.to_image(go.Figure())
```

Could you _please_ clarify, how to use that new feature? since for now it is just useless without binary in PATH.

**Comment by miriad** [comment]
Please try including the port directly in server_url, such as "localhost:9091"

The port field is intended for use with a locally managed server, and setting will override the server_url field

**Comment by dev-dsp** [comment]
Thanks @miriad for such quick answer!

However, with following lines
```
import plotly.io as pio
import plotly.graph_objects as go
pio.orca.config.server_url = "http://localhost:9091"
pio.to_image(go.Figure())
```

I still get completely the same output with the same errors. 
Attaching traceback for a better understanding of what is happening:
```
>>> pio.to_image(go.Figure())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ns.ops/.local/share/virtualenvs/project-BSL7RaPy/lib/python3.6/site-packages/plotly/io/_orca.py", line 1533, in to_image
    ensure_server()
  File "/home/ns.ops/.local/share/virtualenvs/project-BSL7RaPy/lib/python3.6/site-packages/plotly/io/_orca.py", line 1389, in ensure_server
    validate_executable()
  File "/home/ns.ops/.local/share/virtualenvs/project-BSL7RaPy/lib/python3.6/site-packages/plotly/io/_orca.py", line 1087, in validate_executable
    instructions=install_location_instructions,
ValueError: 
The orca executable is required to export figures as static images,
but it could not be found on the system path.

...
```

**Comment by MaximeWeyl** [comment]
I have the same issue when using orca on a remote url  : 
The orca executable is required to export figures as static images,
but it could not be found on the system path.


I found a workaround to insert before to_image or write_image : 

```
plotly.io.orca.status._props["state"] = "validated"
```


Seems like a plotly.py's bug to me.
