### ISSUE TITLE
Hard to remove colorbar with px.imshow

### ISSUE THREAD

**Issue by emmanuelle** [plotly/plotly.py#1929]
See https://community.plot.ly/t/hide-colorbar-in-px-imshow/31853

**Comment by nicolaskruchten** [comment]
I would just `update_layout(coloraxis_showscale=False)` or something similar...

**Comment by tkstevens** [comment]
Thanks to both.  `fig.layout.coloraxis.showscale = False` did the trick (note that I couldn't see the `showscale` property within the `layout.coloraxis` dict upon `print(fig)`.

**Comment by nicolaskruchten** [comment]
> note that I couldn't see the showscale property within the layout.coloraxis dict upon print(fig).

This is normal, as you can only see properties that have explicitly been set, either by `px` or by your own code. The default values for anything missing are inferred/inlined on render. 

This is kind of annoying, as it means you need to familiarize yourself with https://plot.ly/python/reference, but we're brainstorming ways of making this easier to introspect from Python :)
