### ISSUE TITLE
[BUG] zmin and zmax not working in imshow for 2d data

### ISSUE THREAD

**Issue by emmanuelle** [plotly/plotly.py#1931]
See for example
```
import plotly.express as px
import numpy as np
img = np.random.random((10, 10))
px.imshow(img, zmin=0.3, zmax=0.7)
```
I think this is because the Heatmap trace uses instead the `range_color` argument which was quite introduced quite late in the process. It's easy to fix, we just have to decide first if the API is ok as it is.

**Comment by nicolaskruchten** [comment]
Conclusion from discussion: we should continue to use `range_color` if provided, but if it isn't, we insert `zmin` and `zmax` in its place.

**Comment by emmanuelle** [comment]
So of course it's a bit more complicated than I originally thought because in the coloraxis if you give `cmin` you must also give `cmax` (I don't see why, btw). Working on it!
