### ISSUE TITLE
No output when using Jupyter Lab

### ISSUE THREAD

**Issue by andreamoro** [plotly/plotly.py#1940]
Hello there, 

Haven't read of anything so far, but apparently using the library on Jupiter Lab (v. 1.2.1) and on a Mac running Mojave, no output is shown (No problem if I use Jupiter Notebook).
On the contrary, I've seen some ticket open for Jupiter Lab which suggests a fault of mine.

Not sure how to investigate on this further, nor if I'm using the right package. I have, in fact, installed both the plotly_express and the pip install plotly-express that is per se already confusing.

This [page](https://plot.ly/python/getting-started/#installation) explicitly requires v. 1.2.0, but trying that option doesn't work too.

Any help is appreciated.

**Comment by nicolaskruchten** [comment]
Hi there!

I would recommend going through our JupyterLab troubleshooting guide if you haven't already: https://plot.ly/python/troubleshooting/#jupyterlab-problems

Regarding Plotly Express, it started out life as a separate package called `plotly_express` and `pip` accepts both the underscore and hyphen variant, so `plotly-express` is the same thing. That said, nowadays it lives under `plotly.express` so `import plotly_express` is exactly the same as `import plotly.express` :)

**Comment by andreamoro** [comment]
Thanks.
Eventually the JupiterLab extensions were completely missing, so thanks for pointing me to that. 

When advised to install the package, I was not told about them.

May I ask the reason why the "Lab" requires extensions and Notebook works just out of the box?

**Comment by zydariv** [comment]
Can't install plotly on Jupyter Lab 1.2, Python 3.7.6, MacOS Mojave
I am using a virtal Python Environment

I followed the instructions on https://plot.ly/python/getting-started/

```
$ pip install jupyterlab==1.2 "ipywidgets>=7.5"
$ export NODE_OPTIONS=--max-old-space-size=4096
$ jupyter labextension install @jupyter-widgets/jupyterlab-manager@1.1 --no-build
$ jupyter labextension install jupyterlab-plotly@1.5.2 --no-build
$ jupyter labextension install plotlywidget@1.5.2 --no-build
$ jupyter lab build
$ unset NODE_OPTIONS

```
When I import plotly, I get the following error:
**ModuleNotFoundError: No module named 'plotly'**

When using 

> $ pip install plotly

I end up with empty outputs.

Thank you for your help in advance!

Cheers!

**Comment by Raman236** [comment]
I have the exact same issue
![image](https://user-images.githubusercontent.com/76923489/145361360-3de112b1-0740-4258-b5c1-d4554da82194.png)
