### ISSUE TITLE
Sunburst should take grandparents info

### ISSUE THREAD

**Issue by rotemgb** [plotly/plotly.py#1976]
Sunburst should take grandparents info (as many as one want), to avoid identical ids passed to Sunburst, especially when working on categorical data.

For example, taking the sunburst plot example from the website:

![Screenshot from 2019-12-04 13-40-01](https://user-images.githubusercontent.com/35784524/70184417-a78d8380-169c-11ea-8139-69658f8b30e3.png)

If we would like to add gender on the second circle, and some of the salesperson initials would have been the same, some of the sunburst ids would also be the same, and it would be possible to plot.

This problem happens every time you have categorial data.

Thank you,

**Comment by emmanuelle** [comment]
Thank you for noticing this @rotemgb. I just hit exactly the same bug :-). We will update the doc.

**Comment by tayyabvohra** [comment]
@emmanuelle @rotemgb  I am having this issue can you please resolve this 

https://github.com/plotly/plotly.py/issues/2285

**Comment by rotemgb** [comment]
As far as I know, this issue hasn't been resolved. I don't think @emmanuelle completely understood the issue. The problem is not with documentation, but the class of sunburst need to be modified to give flexibility when working on categorical data. 

@tayyabvohra  As for a work around the issue, I created a small loop that add to each category a space in the beginning or the end. for example, the string 'coffee' and 'coffee ' (with a space in the end) are not the same. That way sunburst "think" that they are different and manage to link each one of them to different children. This solution works well with small number of categories, but when you have too many, the plot will be a little messy, as the names of the labels can't be modified (as far as I know), and you will have the spaces you added in the plot.

I think 2 things should be added to sunburst:
**Give the users the flexibility to link not just the parents, but also the grandparents. That will solve the categorical data with sunburst issue.
**Add the flexibility to change the labels on the plot. meaning, sunburst shouldn't take automatically the name of the parents and children as the labels, and there should be a way for us to modify it.

@tayyabvohra hope that helps :)

**Comment by tayyabvohra** [comment]
@rotemgb can you share your code here for this problem..!

**Comment by nicolaskruchten** [comment]
So to be clear: `id` must be unique per segment and must have a unique parent. The calling code probably should indeed prepend the `id`s of the parents to the `id`s of the children, recursively, but this is not something that can be done internally using the `id`/`parent`/`label` API.

That said, we added the `path` API to `px.sunburst` to handle doing this automatically for tabular data. Check it out here: https://plot.ly/python/sunburst-charts/#sunburst-of-a-rectangular-dataframe-with-plotlyexpress

@emmanuelle do you think you could you see if you can make the docs clearer/more explicit about how unique IDs must be?

**Comment by nicolaskruchten** [comment]
Re the two proposed solutions:

> Give the users the flexibility to link not just the parents, but also the grandparents. That will solve the categorical data with sunburst issue.

This is already possibly from outside Plotly: IDs should be prepended with parent information, recursively, and we will make this clearer in examples like https://plot.ly/python/sunburst-charts/#sunburst-with-repeated-labels

> Add the flexibility to change the labels on the plot. meaning, sunburst shouldn't take automatically the name of the parents and children as the labels, and there should be a way for us to modify it.

This is already not the case: `id` and `label` are different fields per node. `id` defaults to `label` if not provided but both can be provided so a node can have a `label`=`"Female"` for display, a `parent`=`"a-b"` and an `id`=`"a-b-c"`. Another node can then be a child of this one with another label (even if that label is the same as some other sector :) and a `parent`=`"a-b-c"` and an `id`=`"a-b-c-d"`.

We should make this distinction between `id` and `label` clearer in the docs as well (and repeat this clarification in the treemap docs).

Thanks for the feedback :)

**Comment by tayyabvohra** [comment]
Can you provide any code for this problem , I cannot find any solution related to the problem on the OP questions chart, although this problem can be solved with different type of sunburst chart provided in the documentation @nicolaskruchten

**Comment by rotemgb** [comment]
@tayyabvohra you can find my code with the work-around the problem in here [https://www.kaggle.com/rotemgb/money-talks-gender-disparities-in-tech](url) , but after seeing this solution by @nicolaskruchten  using path, I think would solve your problem.

> That said, we added the path API to px.sunburst to handle doing this automatically for tabular data. Check it out here: https://plot.ly/python/sunburst-charts/#sunburst-of-a-rectangular-dataframe-with-plotlyexpress

I don't have a code for that, because I haven't used it (I'm not sure this option existed when I used it..), but follow the code examples in this documentation.

**Comment by rotemgb** [comment]
@nicolaskruchten you all did a great adding the path functionality!  That solves all problems with categorical data.

About the documentation, maybe adding an example on adding labels to your demo function `def build_hierarchical_dataframe` in [https://plot.ly/python/sunburst-charts/#sunburst-of-a-rectangular-dataframe-with-plotlyexpress](url) might help. 

Thank you!

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
