### ISSUE TITLE
TypeError when updating layout

### ISSUE THREAD

**Issue by Kairine** [plotly/plotly.py#2002]
Hello, 

I'm working with plotly 4.4.1 on Jupyter Notebook, and I'm trying to make a 3D scatter plot using the exact same code in the documentation:  

`import plotly.graph_objects as go`
`import numpy as np`

`t = np.linspace(0, 20, 100)`
`x, y, z = np.cos(t), np.sin(t), t`

`fig = go.Figure(data=[go.Scatter3d(`
`    x=x,y=y,z=z, mode='markers',`
`    marker=dict(size=12,color=z, colorscale='Viridis', opacity=0.8)`
`)])`

`fig.update_layout(margin=dict(l=0, r=0, b=0, t=0))`
`fig.show()`

Somehow it keeps giving TypeError:
`TypeError                                 Traceback (most recent call last)`
`<ipython-input-92-61d9c81ee298> in <module>()`
`     21 `
`     22 # tight layout`
`---> 23 fig.update_layout(margin=dict(l=0, r=0, b=0, t=0))`
`     24 fig.show()`

`TypeError: 'NoneType' object is not callable`

Could you please tell me how to fix this ?

**Comment by emmanuelle** [comment]
Hum indeed this should not happen... Could you restart your notebook kernel (Kernel -> restart and clear output) and then execute a cell with only the code above? I'm wondering if another part of your code might have overwritten an object such as `dict`?

**Comment by Kairine** [comment]
So I isolated this cell into a separate notebook and it worked... Indeed there must be some kind of conflict with my code. But I'm pretty sure I didn't overwrite `dict` in my code. Do you have any other ideas ? Other objects in the source code for example ?

**Comment by Kairine** [comment]
Actually in this separate notebook, when i put `import plotly.graph_objs as go` it works fine, but if I put `import plotly.graph_objects as go` there's another message:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-13-550ad0a41064> in <module>()
      1 #import plotly.graph_objs as go
----> 2 import plotly.graph_objects as go
      3 import numpy as np
      4 
      5 # Helix equation

/dds/miniconda/envs/dds/lib/python3.5/site-packages/plotly/graph_objects.py in <module>()
      1 from __future__ import absolute_import
----> 2 from plotly.graph_objs import *
      3 
      4 __all__ = [
      5     "AngularAxis",

AttributeError: module 'plotly.graph_objs' has no attribute 'FigureWidget'

Is that supposed to happen ? There might be a relation between the two problems maybe ?

**Comment by emmanuelle** [comment]
Hum maybe there was a problem with the installation of plotly? Could you try uninstalling plotly (and check that you don't have several versions installed) and install it again?

**Comment by renswilderom** [comment]
I had a similar problem when using the dictionary in the following code

fig.add_trace(go.Scatter(x=df_melt1['date'], y=df_melt1['value'], name='Revenue with discounts', 
                         line=dict(color='#E1D89F', width=2)))            

It kept giving me:

TypeError: 'dict' object is not callable

Reinstalling Plotly (through Anaconda) worked! It also needed to restart Jupyter

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
