### ISSUE TITLE
Feature Request: Add plotly as `pandas.plotting.backend` option

### ISSUE THREAD

**Issue by discdiver** [plotly/plotly.py#2005]
Feature Request: Add plotly as `pandas.plotting.backend` option. 

We don't have to use Matplotlib as the plotting backend for pandas any longer. Holoviewsand Bokeh are options. Would love Plotly to be an option. 

See [this SO answer](https://stackoverflow.com/a/58440525/4590385) for a discussion.

Thank you for considering!

**Comment by nicolaskruchten** [comment]
Yep, this is something that's on our roadmap, and we're pretty excited about it too!

**Comment by cybertk** [comment]
Is this still in the roadmap?

**Comment by nicolaskruchten** [comment]
Yes! We’re hoping to have something in the next release :)

**Comment by jolespin** [comment]
Will it use plotly express?

**Comment by nicolaskruchten** [comment]
Yes!

**Comment by nicolaskruchten** [comment]
This is set to be merged this week in https://github.com/plotly/plotly.py/pull/2336 :)

**Comment by jolespin** [comment]
@nicolaskruchten sorry, I’m a bit confused. I noticed the link out above is to the plotly github.  Does that mean the update will be in plotly instead of pandas?

**Comment by nicolaskruchten** [comment]
Yes! This issue was closed because my PR just landed in master. The functionality will be available for installation from PyPI tomorrow and I'll post a link here to the new docs and release announcement :)

**Comment by nicolaskruchten** [comment]
Here's the big announcement: https://medium.com/plotly/beyond-tidy-plotly-express-now-accepts-wide-form-and-mixed-form-data-bdc3e054f891
