### ISSUE TITLE
Parallel categories not recognizing dimension columns

### ISSUE THREAD

**Issue by robroc** [plotly/plotly.py#2008]
Data frame with two categorical columns and one numerical column being passed to `px.parallel_categories`. Only one column gets visualized, no matter what is passed to `dimensions`: a single column, two columns, or no columns.

Data types changed to `str` and `category`, but no change.

Data:

![px](https://user-images.githubusercontent.com/1219001/59059308-a48c1480-886c-11e9-91b8-52772e6656fd.PNG)

Code:

`px.parallel_categories(occupations_by_year, dimensions=['Main_jobs', 'Election year'], color = 'count')`

Result:

![px2](https://user-images.githubusercontent.com/1219001/59059317-a7870500-886c-11e9-8b91-7b49ce5a109c.PNG)

Python 3.6
plotly==3.10.0
plotly-express==0.3.0

**Comment by fjprobos** [comment]
Same issue over here. It is an easy way to look for colinearity among categorical features. Please get it fixed.

**unique transmission_model : 19
unique model_family: 24**

![image](https://user-images.githubusercontent.com/3968323/72534391-7e444380-3855-11ea-85b1-73f92ed8ea9e.png)

![image](https://user-images.githubusercontent.com/3968323/72534457-987e2180-3855-11ea-8127-da9ff3fcf42f.png)


Python 3.5.6
Plotly 4.4.1
