### ISSUE TITLE
Error when using two image scrappers together

### ISSUE THREAD

**Issue by jorgepiloto** [plotly/plotly.py#2014]
### Introduction to the problem 
I am trying to move the current Jupyter Notebook examples of the [poliastro project](https://github.com/poliastro/poliastro) to an [Sphinx-Gallery](https://github.com/sphinx-gallery/sphinx-gallery) set. Since we are making use of **plotly figures** we need to **capture them** as output figures and therefore, make use of the **plotly image scrapper**. We also need to capture `matplotlib` figures, so this image scrapper must be also added to the `conf.py` file.

#### How to reproduce this issue :beetle: 

If you download the [official example repository](https://github.com/plotly/plotly-sphinx-gallery)  from @emmanuelle for achieving this task and you add the following [simple Python file](https://gist.github.com/jorgepiloto/db807a7ee3a0bcfbaea38fc9cd7ac95e) in the `examples/` directory for plotting a sinusoidal wave with `matplotlib` and error is raised:

```bash
generating gallery...
generating gallery for auto_examples... [ 25%] plot_sin.py                                                                                                                                       
Exception occurred:
  File "/home/lobo/anaconda3/envs/poliastro/lib/python3.7/site-packages/plotly/io/_sg_scraper.py", line 91, in figure_rst
    figure_name = figure_paths[0]
IndexError: list index out of range
```

**Comment by emmanuelle** [comment]
Thank you for the bug report @jorgepiloto. I've opened #2015 to correct this. Could you please try it with the `scraper` branch of the PR to check that it's working well for you (also maybe with more examples)? They should be a release of plotly.py in the first half of January so we should be able to include a fix.
