### ISSUE TITLE
ModuleNotFoundError: No module named 'plotly'

### ISSUE THREAD

**Issue by karthikGandiban** [plotly/plotly.py#2039]
I am a beginner here , as part of my learning module which requires  Plotly , i followed the standard method of using pip install plotly and pip install cufflinks - after successful installation when i call them on my jupyter note book , i am getting this error .

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-d863167bda64> in <module>()
      1 import pandas as pd
      2 import numpy as np
----> 3 from plotly import __version__
      4 print(__verison__)

ModuleNotFoundError: No module named 'plotly'

Tried few of the options mentioned like downgrading Plotly etc etc but of no use , request your support . sorry if the question is lame.

**Comment by emmanuelle** [comment]
Hi @karthikGandiban are you using a virtual environment when installing plotly? One common issue is when the jupyter notebook is not launched in the same environment as the one where plotly is installed. 
Could you please paste here the output of
```
pip list | grep plotly
```
if you're working on Mac or linux, or just
```
pip list
```
if you're on Windows.

**Comment by karthikGandiban** [comment]
C:\Users\gak2ban>pip list
Package            Version
------------------ ----------
attrs              19.3.0
backcall           0.1.0
beautifulsoup4     4.8.1
bleach             3.1.0
certifi            2019.11.28
chardet            3.0.4
chart-studio       1.0.0
colorama           0.4.3
colorlover         0.3.0
cufflinks          0.17.0
cycler             0.10.0
decorator          4.4.1
defusedxml         0.6.0
entrypoints        0.3
html5lib           1.0.1
idna               2.8
importlib-metadata 1.3.0
ipykernel          5.1.3
ipython            7.11.1
ipython-genutils   0.2.0
ipywidgets         7.5.1
jedi               0.15.2
Jinja2             2.10.3
json5              0.8.5
jsonschema         3.2.0
jupyter-client     5.3.4
jupyter-core       4.6.1
jupyterlab         1.2.0
jupyterlab-server  1.0.6
kiwisolver         1.1.0
lxml               4.4.2
MarkupSafe         1.1.1
matplotlib         3.1.2
mistune            0.8.4
more-itertools     8.0.2
nbconvert          5.6.1
nbformat           4.4.0
notebook           6.0.2
numpy              1.17.4
pandas             0.25.3
pandocfilters      1.4.2
parso              0.5.2
pickleshare        0.7.5
pip                19.3.1
plotly             4.4.1
prometheus-client  0.7.1
prompt-toolkit     3.0.2
Pygments           2.5.2
pyparsing          2.4.5
pyrsistent         0.15.6
python-dateutil    2.8.1
pytz               2019.3
pywin32            227
pywinpty           0.5.7
pyzmq              18.1.1
requests           2.22.0
retrying           1.3.3
scipy              1.4.1
seaborn            0.9.0
Send2Trash         1.5.0
setuptools         40.8.0
six                1.13.0
soupsieve          1.9.5
SQLAlchemy         1.3.12
terminado          0.8.3
testpath           0.4.4
tornado            6.0.3
traitlets          4.3.3
urllib3            1.25.7
wcwidth            0.1.8
webencodings       0.5.1
widgetsnbextension 3.5.1
xlrd               1.2.0
zipp               0.6.0

**Comment by vantainguyen** [comment]
I have the same problem. Also, I failed to install Cufflinks in Windows 10. Could anyone please give a hand?

**Comment by ddobric** [comment]
Have the same issue.

![image](https://user-images.githubusercontent.com/1756871/77829027-953dc680-711f-11ea-8ed9-f0aa11ce685a.png)

![image](https://user-images.githubusercontent.com/1756871/77829040-ae467780-711f-11ea-88a9-6ecb8e58b30e.png)

**Comment by ashraf-ul** [comment]
same issue using jupyter in IBM's Skills Network Lab

import plotly as px
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-6-36cd69112af4> in <module>
----> 1 import plotly as px

ModuleNotFoundError: No module named 'plotly'



import plotly.express as px
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-8-86e89bd44552> in <module>
----> 1 import plotly.express as px

ModuleNotFoundError: No module named 'plotly'


@harshitcodes I encountered this problem while implementing from your post "Building COVID-19 interactive dashboard from Jupyter Notebooks"

**Comment by Vegeta1313** [comment]
just type " pip install plotly "  it will install the package and just restart the kernel hopefully you would be good to go

**Comment by likesh11235** [comment]
same issue.Please help @emmanuelle

**Comment by likesh11235** [comment]
@harshitcodes did the issue get resolved. if so please help

**Comment by karthikGandiban** [comment]
@Vegeta1313  , @ashraf-ul @likesh11235 : i resolved this issue by creating a new environment ( i am using Anaconda Navigator to launch Python) and installed the libraries in the new environment and now everything is back to normal.

**Comment by jsj14** [comment]
`import plotly.express as px
`
ModuleNotFoundError: No module named 'plotly.express'; 'plotly' is not a package. 

I'm getting this despite having installed it using pip. I'm using a virtualenv and if I try importing the same inside python shell, it works. but not via the program I'm running.

**Comment by dgitts** [comment]
If you are using Anaconda, launch Anaconda Navigator and run cmd.exe from there. The run `pip install plotly` or `conda install -c plotly` from that terminal window. I had the same issue and this is what resolved it for me, despite having plotly installed on the machine.

**Comment by texabyte** [comment]
I have the same issue. When I open Anaconda - Terminal on Windows and type pip list, I can see it is in the list. 
Also in the Anaconda, under installed packages I can see that plotly is there. 
But when I try to go on jupyter notebook and type import plotly, it gives me the error No module named plotly. Can someone help please?

**Comment by texabyte** [comment]
> I have the same issue. When I open Anaconda - Terminal on Windows and type pip list, I can see it is in the list.
> Also in the Anaconda, under installed packages I can see that plotly is there.
> I even checked manually in - C:\Users\User\Anaconda3\pkgs and there is a folder called plotly in there.
> 
> But when I try to go on jupyter notebook and type import plotly, it gives me the error No module named plotly. Can someone help please?


Update:

I followed this from stackoverflow and it works.

import sys
!conda install --yes --prefix {sys.prefix} plotly

Source: https://stackoverflow.com/questions/36959782/plotly-in-jupyter-issue

**Comment by howardpen9** [comment]
> Have the same issue.
> 
> ![image](https://user-images.githubusercontent.com/1756871/77829027-953dc680-711f-11ea-8ed9-f0aa11ce685a.png)
> 
> ![image](https://user-images.githubusercontent.com/1756871/77829040-ae467780-711f-11ea-88a9-6ecb8e58b30e.png)

Same issued on me (Use PyCharm)  TnT

**Comment by jaganrr** [comment]
> If you are using Anaconda, open Anaconda Navigator and launch cmd prompt (cmd.exe) from there. Then run `pip install plotly` or `conda install -c plotly` from that terminal window. I had the same issue and this is what resolved it for me, despite having plotly already installed on the machine.

Worked for me as well when installed from Anaconda cmd prompt

**Comment by rhlklwr** [comment]
> > Have the same issue.
> > ![image](https://user-images.githubusercontent.com/1756871/77829027-953dc680-711f-11ea-8ed9-f0aa11ce685a.png)
> > ![image](https://user-images.githubusercontent.com/1756871/77829040-ae467780-711f-11ea-88a9-6ecb8e58b30e.png)
> 
> Same issued on me (Use PyCharm) TnT

I have faced similar issue with Plotly. Than I found out this is due to pandas library was not installed.

Can you install pandas library and check if you still getting error.

**Comment by NadirRupani** [comment]
![conda](https://user-images.githubusercontent.com/68913488/88683024-59147580-d0c1-11ea-98d6-3bdf459785d5.PNG)

Launch CMD.exe from Anaconda navigator and type "pip install plotly".

**Comment by raybg** [comment]
> @Vegeta1313 , @ashraf-ul @likesh11235 : i resolved this issue by creating a new environment ( i am using Anaconda Navigator to launch Python) and installed the libraries in the new environment and now everything is back to normal.

Yes ... i tried it in another environment and it worked for me ... Thanks.

**Comment by patecm** [comment]
For those of you in a virtual environment, did you add the kernel to Jupyter? After install plotly and cufflinks (with conda) into that environment, I was having the same problem and fixed it with:

`
conda activate myenv
ipython kernel install --name myenv --user
jupyter notebook
`

After jupyter launched, I loaded my notebook and then changed from Python3 to myenv in the navigation bar under:

Kernel > Change kernel > myenv

And then plotly would import!

**Comment by Qiizoff** [comment]
use command: python3 -m pip install plotly

**Comment by pratikghatake** [comment]
I am having the same issue. I am trying to plot the model object using 3D graph. 
It's throwing's me the following error- 
No module named 'plotly.validators.layout'

I have tried some of the options from above, such as uninstalling or updating the plotly but nothing is working out for me. I am trying to run the code from Anaconda Prompt - Jupyter Notebook. Any help is highly appreciated. 

Thanks in advance.

**Comment by akash-yadav12** [comment]
@pratikghatake 
so if you are using Anaconda prompt, then instead of running pip install plotly command in cmd/terminal, try running the same command in Anaconda prompt, your issue will be instantly solved

**Comment by JaeminJamesKim** [comment]
If you are using Anaconda Navigator and already checked(using pip list) that you have installed plotly, this will solve your problem:
Go to Environments tab in your Navigator, click on the sideway triangle next to Anaconda environment below base(root) environment, and then click "open with Jupyter Notebook". Then, your Jupyter will recognize plotly in your notebook.

![image](https://user-images.githubusercontent.com/23378043/102302382-910c4000-3f1e-11eb-8317-8b6d5aa17b43.png)

**Comment by Jeevan-Kiran-Lenka** [comment]
![Screenshot (131)](https://user-images.githubusercontent.com/53392413/109455592-01862000-7a7d-11eb-81f1-63b589cd8ee1.png)
 
I'm also having the same error even though I have installed it properly and also everything was running smoothly for the first time this error came up the second time of running the program

**Comment by ltog** [comment]
Make sure your python file is NOT called `plotly.py` but something else.

**Comment by raptor46** [comment]
> ![Screenshot (131)](https://user-images.githubusercontent.com/53392413/109455592-01862000-7a7d-11eb-81f1-63b589cd8ee1.png)
> 
> I'm also having the same error even though I have installed it properly and also everything was running smoothly for the first time this error came up the second time of running the program

**Comment by raptor46** [comment]
if you are using the anaconda prompt just try an run (conda install nb_conda)
it will work

**Comment by trbedwards** [comment]
> For those of you in a virtual environment, did you add the kernel to Jupyter? After install plotly and cufflinks (with conda) into that environment, I was having the same problem and fixed it with:
> 
> ```
> conda activate myenv     
> ipython kernel install --name myenv --user    
> jupyter notebook
> ```
> 
> After jupyter launched, I loaded my notebook and then changed from Python3 to myenv in the navigation bar under:
> 
> Kernel > Change kernel > myenv
> 
> And then plotly would import!

I was scratching my head and assumed that launching jupyter inside my environment would be enough to load the correct kernel; I was wrong! 

Thanks a bunch for this useful tip, as it turns out you do really have to use the ipython kernel command and switch to that environment in jupyter, even if you're launching jupyter from that environment itself!

**Comment by abhiram540** [comment]
ThnQ @dgitts 

Running **pip install plotly** in Anaconda Prompt worked for me.

**Comment by MSingh03** [comment]
> 
> 
> If you are using Anaconda, open Anaconda Navigator and launch cmd prompt (cmd.exe) from there. Then run `pip install plotly` or `conda install -c plotly` from that terminal window. I had the same issue and this is what resolved it for me, despite having plotly already installed on the machine.

**Comment by MSingh03** [comment]
> 
> 
> If you are using Anaconda, open Anaconda Navigator and launch cmd prompt (cmd.exe) from there. Then run `pip install plotly` or `conda install -c plotly` from that terminal window. I had the same issue and this is what resolved it for me, despite having plotly already installed on the machine.

This worked for me.
Thanks a lot.

**Comment by jensenojs** [comment]
I have a similar issue——

No module named 'plotly.express'; 'plotly' is not a package

plotly.version is 5.2.1, and i trying to install plotly_express, but` from plotly.express import *` still make things wrong.

**Comment by mcleantom** [comment]
I had to restart my laptop to make it work

**Comment by lynnemunini** [comment]
> just type " pip install plotly " it will install the package and just restart the kernel hopefully you would be good to go

Worked for me, Thanks!

**Comment by ankitsethknp** [comment]
I was getting the error 
**ModuleNotFoundError: No module named 'plotly.graph_objects'; 'plotly' is not a package**

After 1 hour of searching the solution, I finally figured it out. The problem was that I named my python file as plotly.py, because of which I was getting this error. After I renamed the file, this error was gone.

**Comment by Potato-boyguy** [comment]
could you help me? I have this error "Requirement already satisfied: plotly in c:\programdata\anaconda3\lib\site-packages (5.8.1)
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: 'c:\\programdata\\anaconda3\\lib\\site-packages\\plotly-5.8.1.dist-info\\METADATA'" when I try to install pip plotly.

**Comment by gloverthe** [comment]
> Make sure your python file is NOT called `plotly.py` but something else.

this worked for me

**Comment by Kitsui-Tango** [comment]
> 

I cant believe this was my issue :(   Thanks so much!

**Comment by cormos** [comment]
> pip install plotly



> > **Make sure your python file is NOT called `plotly.py` but something else.**
> 
> this worked for me

Yes, this was my issue too
Thank you

**Comment by zenoprod** [comment]
> 

thank you

**Comment by putriafia26** [comment]
i have the same problem when deploying streamlit app, the error is 'ModuleNotFoundError: No module named 'plotly''
does anyone knows how to fix this? thx

**Comment by camilaran** [comment]
I installed plotly in the virtual environment. If I run python or ipython it works, if I try with jupyter notebook it doesn't.

I solved the problem by re-installing the kernel for the virtual environment after installing plotly, even if it was already installed before.
So apparently, the kernel for the virtual environment needs to be refreshed, or recreated, so that it takes into account the newly installed plotly module. 
ipython kernel install --name myenv --user
deactivate
jupyter notebook
# select the myenv as kernel in the jupyter notebook, and it works
