### ISSUE TITLE
Scattergl snippet from plotly documentation does not plot on jupyter notebook

### ISSUE THREAD

**Issue by stelmath** [plotly/plotly.py#2040]
I am using the snippet from https://plot.ly/python/line-and-scatter/#large-data-sets but I get a black plot instead:

![image](https://user-images.githubusercontent.com/38814495/71890762-b0ff8500-314d-11ea-8693-88105452fc0f.png)

I have the latest version of plotly installed. Any help?

**Comment by emmanuelle** [comment]
Hi @stelmath thanks for the bug report. I could not reproduce on my machine (it works).

So you're using plotly 4.4.1, correct? Could you also tell us which browser you are using? (did you try in another browser?).

For the sake of debugging, it would also be helpful if you could run this code outside of the notebook, for example inside an IPython console, run
```
import plotly.io as pio
pio.renderers.default='firefox' 
```
(or `'chrome'`, etc.)
and then the rest of the example, so that the figure should open in the browser.

**Comment by empet** [comment]
@stelmath   
data  should be a list, not a graph object. Hence the working code is like this:

`fig = go.Figure(data = [go.Scattergl(...)])`

**Comment by emmanuelle** [comment]
@empet, in fact in plotly 4+ versions we allow to pass a single trace to the `data` parameter. When I started working on the project I complained heavily about the verbosity of adding `[]` for passing a single trace and so this modification was made :-). So of course the syntax you propose is completely correct (and more generalizable) but passing a trace object is also ok.

**Comment by nicolaskruchten** [comment]
@empet as of v4 you can pass in a trace object without the list.

**Comment by empet** [comment]
Thanks, I didn't notice this change.

**Comment by stelmath** [comment]
@emmanuelle  Thanks for the reply. For some weird reason, today it works on my machine. I was using Chrome when the bug happened, yet today it works OK on Chrome. Pretty weird.

**Comment by emmanuelle** [comment]
@stelmath the hardest bugs are the ones which are hard to reproduce :-). I will close for now but if it happens again or if you can identify a reproducible pattern of course feel free to re-open.

**Comment by mazzma12** [comment]
Hi there, I met the same issue with chrome and chromium (works fine with firefox). I first identified the issue with the parallel coordinate plot, but scatterGL produces the same.
# Versions

```
plotly.__version__ :  4.5.4
Chromium 80.0.3987.87 Built on Ubuntu , running on Ubuntu 18.04
ChromeDriver 79.0.3945.36 
```

# Reproduce

```python
import plotly.express as px
df = px.data.iris()
fig = px.parallel_coordinates(df, color="species_id", labels={"species_id": "Species",
                "sepal_width": "Sepal Width", "sepal_length": "Sepal Length",
                "petal_width": "Petal Width", "petal_length": "Petal Length", },
                             color_continuous_scale=px.colors.diverging.Tealrose,
                             color_continuous_midpoint=2)
fig.show()
```
![image](https://user-images.githubusercontent.com/23187108/78065675-e950e100-7393-11ea-92cd-5534f7bc7351.png)

Note that there is no traceback in the jupyter console
