### ISSUE TITLE
Remove nosetests from our CI build (Was:Bring back test_jupyter)

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.py#2042]
We should undo this PR sometime soon: https://github.com/plotly/plotly.py/pull/2041

**Comment by nicolaskruchten** [comment]
from Slack

Jon Mease 15:03
I'm not sure what might have changed, but I think we can :knife: these tests. The modern version of this functionality is pretty well tested in packages/python/plotly/plotly/tests/test_io/test_renderers.py.
As I recall, these were also the only tests we have that weren't working with pytest, so we may be able to switch all of the test invocations from nosetests to pytest as well.

**Comment by emmanuelle** [comment]
closed.
