### ISSUE TITLE
inspect.getargspec() is deprecated

### ISSUE THREAD

**Issue by anders-kiaer** [plotly/plotly.py#2045]
[This line](https://github.com/plotly/plotly.py/blob/81f3922722672fbd6ce7ff50acfac8771c7c7ac2/packages/python/plotly/plotly/express/_doc.py#L503) triggers a `DeprecationWarning` on Python 3:
```
[...]/lib/python3.6/site-packages/plotly/express/_doc.py:503: DeprecationWarning:
inspect.getargspec() is deprecated, use inspect.signature() or inspect.getfullargspec()
```
`getfullargspec` from the same `inspect` package is usually a [drop-in replacement on Python 3](https://docs.python.org/3/library/inspect.html#inspect.getargspec).

**Comment by emmanuelle** [comment]
Thank you @anders-kiaer !
