### ISSUE TITLE
Feature request: plotly express and vertical_spacing

### ISSUE THREAD

**Issue by weber-s** [plotly/plotly.py#2054]
Hello there!

The function used by the different px graph is `make_subplots`, which support a `vertical_spacing` argument. It would be nice to be able to customize our plots created from plotly.express with this option as well.

**Comment by claesnn** [comment]
I would like this option aswell. Currently this workaround works, but it seems unnecessary and actually makes setting subplot_titles with make_subplots really difficult, because px.line uses start_cell="bottom-left". I still have not figured out how to get those back.

```
uniques = math.ceil(len(df.a.unique()) / 5)
fig_data = px.line(df, x="x", y="y", color="z", facet_col="a", facet_col_wrap=5)

fig = make_subplots(uniques, 5, start_cell="bottom-left", shared_xaxes=True, shared_yaxes=True, vertical_spacing=0.015, horizontal_spacing=0.015)

fig.add_traces(fig_data.data)
```

**Comment by claesnn** [comment]
So I found an easy way to add titles to the plots, but it's not super pretty.

```
fig_titles = make_subplots(uniques, 5, start_cell="top-left", subplots_titles=df.a.unique(), vertical_spacing=0.015, horizontal_spacing=0.015)

fig.update_layout(annotations=fig_titles.layout.annotations)
```

**Comment by nicolaskruchten** [comment]
We added `facet_col_spacing` and `facet_row_spacing` to PX functions which support `facet_col` and `facet_row`: https://plotly.com/python/facet-plots/#controlling-facet-spacing
