### ISSUE TITLE
Sometimes IPython widget fails to display

### ISSUE THREAD

**Issue by chriddyp** [plotly/plotly.py#206]
First, `View creation failed Backbone.Model.extend.constructor`, then `Exception in Comm callback TypeError: Cannot read property '$el' of null TypeError: Cannot read property '$el' of null`

![image](https://cloud.githubusercontent.com/assets/1280389/6771734/1f47c4fa-d0be-11e4-8c7e-694dec771071.png)

intermittent, I can't replicate!

IPython version `2.3.1`, Python `2.7.6`

**Comment by theengineear** [comment]
I was just using the widgets in IPython 3 today and I didn't see this come up. I'll keep an eye out though.

**Comment by jonmmease** [comment]
Old `GraphWidget` has been replaced by `FigureWidget` in version 3.
