### ISSUE TITLE
go.Figure() does not render in JupyterLab, only go.FigureWidget()

### ISSUE THREAD

**Issue by prncevince** [plotly/plotly.py#2061]
`go.Figure()` does not render in JupyterLab, only `go.FigureWidget()`.

Chrome Console Error: `Uncaught ReferenceError: require is not defined`

Example:
```python
import plotly
import plotly.io as pio
import plotly.graph_objects as go

figwidget = go.FigureWidget(data=go.Bar(y=[1, 2, 3]))
fig = go.Figure(data=go.Bar(y=[3, 2, 1]))

display(pio.renderers)
display(figwidget)
display(fig)
```

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/17718313/72232439-2d032e00-358f-11ea-8abb-4c32804256f9.png">

Jupyter & Plotly specifics: 

```bash
%load_ext watermark
%watermark -d -iv -v -m -u -n -t -z
!jupyter labextension list plotly
```

```
plotly 4.4.1
last updated: 2020-01-12 22:40:00 EST 

CPython 3.7.6
IPython 7.11.1

compiler   : Clang 4.0.1 (tags/RELEASE_401/final)
system     : Darwin
release    : 19.2.0
machine    : x86_64
processor  : i386
CPU cores  : 4
interpreter: 64bit
JupyterLab v1.2.4
Known labextensions:
   app dir: ~/anaconda3/share/jupyter/lab
        @jupyter-widgets/jupyterlab-manager v1.1.0  enabled  OK
        jupyterlab-plotly v1.4.0  enabled  OK
        plotlywidget v1.4.0  enabled  OK
        qgrid v1.1.1  enabled  OK
```

**Comment by emmanuelle** [comment]
Does the figure display correctly when you call `fig.show()`?

**Comment by prncevince** [comment]
@emmanuelle negative
![image](https://user-images.githubusercontent.com/17718313/72299653-730fce80-362f-11ea-9f16-aa184cae2c87.png)

**Comment by emmanuelle** [comment]
ok, thanks. Did you take a look at the Jupyterlab section in the troubleshooting guide https://plot.ly/python/troubleshooting/? In particular the fact that the extension version needs to be the correct one.

**Comment by prncevince** [comment]
My plotly & extension versions (displayed above) match exactly as shown in https://plot.ly/python/getting-started/ . 
plotly.py v4.4.1 and both jupyterlab-plotly & plotlywidget v1.4.0

**Comment by prncevince** [comment]
Ah, found the issue. 
My `~/anaconda3/share/jupyter/lab/settings/page_config.json` file was:
```json
{
    "disabledExtensions": [
        "@jupyterlab/plotly-extension"
    ]
}
```

I did this to test the new extensions. Removing the entry from `disabledExtensions` fixed things. Thanks! Can be closed.

**Comment by HaithamMaya** [comment]
I'm running into the same issue.

extensions:

```
jupyter labextension list plotly
JupyterLab v2.1.5
Known labextensions:
   app dir: /opt/conda/envs/python/share/jupyter/lab
        @jupyter-widgets/jupyterlab-manager v2.0.0  enabled  OK
        jupyterlab-dash v0.3.0  enabled  OK
        jupyterlab-plotly v4.10.0  enabled  OK
```

```python
import plotly.graph_objects as go
fig = go.Figure()
fig.add_trace(go.Scatter(y=[2, 1, 4, 3]))
fig.add_trace(go.Bar(y=[1, 4, 3, 2]))
fig.update_layout(title = 'Hello Figure')
fig.show()
```

Code above shows a blank screen in the jupyterlab notebook. Looks fine in classic jupyter notebook.

Console:
```
Uncaught ReferenceError: require is not defined
```

I don't have a page_config.json file defined, so its not disabled.

**Comment by ahotrod** [comment]
@emmanuelle @HaithamMaya 

Same problem, `fig = go.Figure() ... (fig.definitions) ... fig.show()` doesn't render the plot in JupyterLab, works in Jupyter Notebook.

My installation:
```
plotly  4.10.0
~$ labextension list
JupyterLab v2.2.6
Known labextensions:
   app dir: /home/dn/anaconda3/envs/nlpu/share/jupyter/lab
        @jupyter-widgets/jupyterlab-manager v2.0.0  enabled  OK
        jupyterlab-plotly v4.10.0  enabled  OK
        plotlywidget v4.10.0  enabled  
```

**Comment by math-student** [comment]
> I'm running into the same issue.
> 
> extensions:
> 
> ```
> jupyter labextension list plotly
> JupyterLab v2.1.5
> Known labextensions:
>    app dir: /opt/conda/envs/python/share/jupyter/lab
>         @jupyter-widgets/jupyterlab-manager v2.0.0  enabled  OK
>         jupyterlab-dash v0.3.0  enabled  OK
>         jupyterlab-plotly v4.10.0  enabled  OK
> ```
> 
> ```python
> import plotly.graph_objects as go
> fig = go.Figure()
> fig.add_trace(go.Scatter(y=[2, 1, 4, 3]))
> fig.add_trace(go.Bar(y=[1, 4, 3, 2]))
> fig.update_layout(title = 'Hello Figure')
> fig.show()
> ```
> 
> Code above shows a blank screen in the jupyterlab notebook. Looks fine in classic jupyter notebook.
> 
> Console:
> 
> ```
> Uncaught ReferenceError: require is not defined
> ```
> 
> I don't have a page_config.json file defined, so its not disabled.

Hey did you ever figure out the issue? I'm in the same position as you. The file works fine in classic notebook, but if I look at it with Nbviewer/Github/Jupyterlab the plots don't show up (blank spaces).

**Comment by HaithamMaya** [comment]
@math-student No i have not been able to resolve the issue yet

**Comment by surchs** [comment]
@ahotrod @HaithamMaya: any chance you are running jupyter with more than one python kernel (i.e. https://ipython.readthedocs.io/en/stable/install/kernel_install.html)? If so, please ensure that the [`jupyterlab-plotly` extension](https://plotly.com/python/getting-started/) is available in the python environment you use to start jupyterlab.

**Comment by HaithamMaya** [comment]
@surchs thank you I should have thought of that!

So the python kernel that I run the jupyter server on is different than the python kernels I use in jupyter. I was assuming the install needed to be on the kernels being used in the notebook, not on the jupyter server's kernel itself. That has resolved my issue.

<img width="1247" alt="image" src="https://user-images.githubusercontent.com/8363383/99542387-00bef780-2980-11eb-82df-564bf13a35f8.png">

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson

**Comment by SBS-EREHM** [comment]
> Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson

plotly still doesn't render in JupyterHub notebooks.
