### ISSUE TITLE
plotly express do not displaying color-category name if function applied

### ISSUE THREAD

**Issue by OleksiiYeromenko** [plotly/plotly.py#2070]
When I set "color=" to column from my dataframe but applying any function to it - I got in fig. legend just 'color'.   
Cant figure out how to set it manually if  I need to set custom color, not just existing column from my dataset.

![Screenshot_2](https://user-images.githubusercontent.com/50664057/72447975-f4499b80-37be-11ea-84cc-45eee397c99b.png)

Example for reproduce:
```
df = pd.DataFrame({'x':[1,2,3,4,5,6,7],'y':[1,2,3,4,5,6,7],'color':[-100,0,1,1000,5000,3000,7000]})

fig = px.scatter(df, x='x', y='y'
                 ,size=df.groupby(by=['y','x'])['y'].transform('count')
                 #,color=df['color']
                 ,color=df['color'].apply(np.log)
                 ,color_continuous_scale=px.colors.sequential.Inferno
                 ,opacity=0.7
                )
fig.show()
```

Thank you.

**Comment by emmanuelle** [comment]
Do I understand correctly that you want to change the title of the colorbar? For this you can pass a `labels` argument to `px` functions: `labels={'color": 'my_name'}`.

**Comment by OleksiiYeromenko** [comment]
> Do I understand correctly that you want to change the title of the colorbar? For this you can pass a `labels` argument to `px` functions: `labels={'color": 'my_name'}`.

It was the fastest response)
Thanks, Emmanuelle! How come I didnt find it..
