### ISSUE TITLE
filled contour plot in plotly.express

### ISSUE THREAD

**Issue by lucanics** [plotly/plotly.py#2071]
Is there a way to create **filled** contour plots with plotly.express similar to the following one?
![contour2](https://user-images.githubusercontent.com/56067087/72451911-f3b00580-37bc-11ea-895f-3d32b49e2884.png)
(reference: https://plot.ly/python/contour-plots/)

The only ones I have seen so far with plotly.express are not filled, e.g.:
```
import plotly.express as px
df = px.data.iris()
fig = px.density_contour(df, x="sepal_width", y="sepal_length", color="species", marginal_x="rug", marginal_y="histogram")
fig.show()
```
![contour1](https://user-images.githubusercontent.com/56067087/72451909-f3b00580-37bc-11ea-990b-923de416ff60.png)
(reference: https://plot.ly/python/plotly-express/)

Any help is appreciated! :)

**Comment by emmanuelle** [comment]
Hi, after a `print(fig)` to understand the structure of the figure created by plotly express, you can call `fig.update_traces` to change the configuration of the trace. See the example below
```
import plotly.express as px
df = px.data.iris().query("species == 'virginica'")
fig = px.density_contour(df, x="sepal_width", y="sepal_length")
fig.update_traces(contours_coloring='fill')
fig.show()
```
![image](https://user-images.githubusercontent.com/263366/72472159-0c66ee00-37b2-11ea-980c-0121b57fef03.png)

**Comment by lucanics** [comment]
That's perfect, thanks! And how can you change the colorscale?

**Comment by nicolaskruchten** [comment]
You can set the `colorscale` in the `update_traces()` call like this:

![image](https://user-images.githubusercontent.com/203523/72530008-74faad00-383c-11ea-86fa-c6c65cba4c92.png)

**Comment by lucanics** [comment]
Many thanks, that solves all my problems

**Comment by nicolaskruchten** [comment]
@Mahdis-z can you add these examples or similar to https://plot.ly/python/2d-histogram-contour/ please?

**Comment by lucanics** [comment]
In case this is useful to anyone, I needed this kind of plot in combination with animation frames.

Although the solution below might not be very beautiful using the iris dataset, you might have a better usecase for other dataframes:

`import plotly.express as px
df = px.data.iris()
df_w = df["sepal_width"].copy()
df_l = df["sepal_length"].copy()

fig = px.density_contour(df, x="sepal_width", y="sepal_length", 
                         range_x=[df_w.min(),df_w.max()], 
                         range_y = [df_l.min(), df_l.max()],
                         animation_frame="species")

fig.data[0]["contours"].coloring = "fill"
fig.update_traces(colorscale="Viridis")

for num,frames in enumerate(fig.frames, start=0):
    fig.frames[num].data[0]["contours"].coloring = "fill"

fig.show()`
