### ISSUE TITLE
Hovertemplate from customdata does not work for go.Sankey

### ISSUE THREAD

**Issue by empet** [plotly/plotly.py#2082]
There are a few unanswered forum questions on using `customdata` in `hovertemplate` definition. That's why I uploaded a notebook on Plotly cloud that deals with different customdata definitions (from a single array, multiple arrays, for both 1d and 2d data,  from single dataframe column or multiple dataframe columns). Most of graph_objects work fine with customdata-hovertemplate, except for `go.Sankey`.
`customdata` is a property for `go.Sankey`, but we have two different `hovertemplate` properties:
 `go.sankey.Node.hovertemplate` and `go.sankey.Link.hovertemplate` .

My question: how should be defined the array `customdata` to hold both m-element subbarays for node extra-attributes and n-element arrays (m different from n)  for extra link attributes, and how these subarrays can be accessed to use them in `node.hovertemplate`, respectively  `link.hovertemplate`?
Any attempt following the same construction as for other `graph_objects` failed.    

 I have this example
```
node_labels = ["A1", "A2", "B1", "B2", "C1", "C2", "C3"]
source = [0, 1, 1, 0, 2, 3, 3, 2] 
target = [2, 2, 3, 3, 4, 4, 5, 6]
value =  [5, 1, 3, 5, 6, 4, 2, 5]

fig = go.Figure(go.Sankey(
                    node = dict(
                            pad = 25,
                            thickness = 20,
                            line = dict(color = "black", width = 0.5),
                            label = node_labels,
                            color = "RoyalBlue"),
                    link = dict(
                            source = source,
                            target = target,
                            value =  value)))

fig.update_layout(title_text="Sankey Diagram")
```
and want to add to `customdata` this extra numerical attributes for all 7 nodes
```
node_newprop = np.array([ 9.2,  7.5,  8.3,  9.76, 12.34, 10.72,  6.31])
```
and these two 8-element lists, for links:
```
link_flow = ['A1->B1: 5',
 'A2->B1: 1',
 'A2->B2: 3',
 'A1->B2: 5',
 'B1->C1: 6',
 'B2->C1: 4',
 'B2->C2: 2',
 'B1->C3: 5']

date = ['2020 01 08',
 '2020 01 09',
 '2020 01 10',
 '2020 01 11',
 '2020 01 12',
 '2020 01 13',
 '2020 01 14',
 '2020 01 15']
```
How should be defined the corresponding  `customdata`, and how the first, respectively the last two arrays would be refered to in `hovertemplate` definition?

I suspect that this is a plotly.js question/issue, but plotly.py  should give the way of accessing the customdata elements (this was the topic of most forum questions, related to other trace types).

I addressed the last question because accessing customdata elements is far from being pythonic:
for an usual trace type (such as scatter, scatterpolar, polarbar, etc) a  `customdata` array  containing  three dataframe columns is defined as follows: 
```
customdata  = np.stack((df['c1'], df['c2'], df['c3']), axis=-1)
```
Its shape is (len(df), 3), and each column is passed to hovertemaplate as `customdata[k]`, k =0,1,2.

**Comment by emmanuelle** [comment]
Hi @empet thanks for the issue. First of all I had to use `fullData.customdata` to be able to access the customdata from a node or a link, as in the example below, do you confirm this? But even with this I can only access the first element of the customdata, there seems to be something wrong with the data access pattern... 
```
import plotly.graph_objects as go
node_labels = ["A1", "A2", "B1", "B2", "C1", "C2", "C3"]
source = [0, 1, 1, 0, 2, 3, 3, 2] 
target = [2, 2, 3, 3, 4, 4, 5, 6]
value =  [5, 1, 3, 5, 6, 4, 2, 5]

node_newprop = np.array([ 9.2,  7.5,  8.3,  9.76, 12.34, 10.72,  6.31])[:, np.newaxis]

fig = go.Figure(go.Sankey(
                    node = dict(
                            pad = 25,
                            thickness = 20,
                            line = dict(color = "black", width = 0.5),
                            label = node_labels,
                            color = "RoyalBlue",
                            hovertemplate='%{fullData.customdata[0]}'
                    ),
                    link = dict(
                            source = source,
                            target = target,
                            value =  value),
                customdata=node_newprop
)
               )

fig.update_layout(title_text="Sankey Diagram")
```

**Comment by empet** [comment]
Hi @emmanuelle ,

Yes, it cannot access customdata. But moreover I'd like to define simultaneously customdata for links, too, and the corresponding hovertemplate. As long as the customdata for nodes have a different length  from that associated to links, I cannot see how fullData.customdata can be defined in this case.

**Comment by emmanuelle** [comment]
You could think of filling with nans (as pandas does for example) so that it would be possible to concatenate the arrays for links and nodes. But there is something fishy with the way `fullData.customdata` is accessed, I think we'll have to ask the Javascript team here.

**Comment by emmanuelle** [comment]
closing since customdata for nodes and links are now available with plotly.js 1.53 / plotly.py 4.6
