### ISSUE TITLE
Facet category order with missing data

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.py#2084]
This seems like a bug: https://community.plot.ly/t/python-plotly-express-facet-col-facet-row-order-categories/33693

**Comment by emmanuelle** [comment]
Indeed. Do you think it should be part of the 4.5 milestone?

**Comment by nicolaskruchten** [comment]
Ideally yes! I'm hoping it's just a one-liner 🙈

**Comment by emmanuelle** [comment]
I'm on it FYI.

**Comment by nicolaskruchten** [comment]
This problem is actually somewhat generalized: in the example below we ask for Lunch to precede Dinner, and for the symbol sequence to be circle before square. The legend is ordered correctly, but Lunch is mapped to square instead of circle.

![image](https://user-images.githubusercontent.com/203523/72758101-d2299200-3b9f-11ea-9379-3be8166669a0.png)
