### ISSUE TITLE
AttributeError: module 'plotly_express' has no attribute 'imshow'

### ISSUE THREAD

**Issue by fhamborg** [plotly/plotly.py#2090]
Reproduce with:
```
import plotly.express as px
fig_rows = []
fig = px.imshow(fig_rows)
fig.show()
```

Will give:
```
Traceback (most recent call last):
  File "/Users/felix/IdeaProjects/cope/ann4class/workwithaestore.py", line 66, in <module>
    investigate_distribution(dataset_ids=set([ALLSIDES_DATASET_ID]))
  File "/Users/felix/IdeaProjects/cope/ann4class/workwithaestore.py", line 54, in investigate_distribution
    fig = px.imshow(fig_rows)
AttributeError: module 'plotly_express' has no attribute 'imshow'
```

**Comment by nicolaskruchten** [comment]
Can you confirm that you have the latest version of `plotly` installed? It's 4.4.1

**Comment by fhamborg** [comment]
Yea it's 4.4.1

```
conda list
...
plotly                    4.4.1                      py_0    plotly
```

**Comment by nicolaskruchten** [comment]
The error message is a bit puzzling as it says `plotly_express` but the code you have above says `plotly.express` so are you sure you're querying the same environment you're running the code in?

`plotly_express` does import and re-export `plotly.express` so it shouldn't matter but if you could run `import plotly; plotly.__version__` in the same environment where you're seeing this run-time error that would rule out one more possible cause of this issue :)

**Comment by fhamborg** [comment]
Oh, I'm very sorry - the error was caused by a misconfigured PyCharm. When running it straight from the python shell it works. I'm sorry! Thank you very much, though, for your quick reply :-) And awesome library, btw, I very much like how little code one needs to quickly get beautiful and functional charts!

**Comment by SeaDude** [comment]
For those who stumble here: If using Jupyter Notebooks... after you install a module such as plotly, you must restart the Jupyter kernel before the install will take effect. 
I received this error, installed plotly, but error persisted until restarting the kernel. 
HTH!

**Comment by priyankakachroo** [comment]
> For those who stumble here: If using Jupyter Notebooks... after you install a module such as plotly, you must restart the Jupyter kernel before the install will take effect.
> I received this error, installed plotly, but error persisted until restarting the kernel.
> HTH!

it helped me .thanks :)

**Comment by omar1890** [comment]
Also worked with me, thanks @SeaDude
