### ISSUE TITLE
plotly 4.0 df.iplot() shows link 'export to plotly'.

### ISSUE THREAD

**Issue by arunkumarn123** [plotly/plotly.py#2100]
As per documentation of Plotly 4.0 plotly base package is completely offline. However, df.iplot() function still produces plots with a 'export to plotly' link at the bottom of the plot.

**Comment by nicolaskruchten** [comment]
Yes, the `df.iplot()` function is not part of the `plotly` library: it comes from a third party library out of our control called `cufflinks` which makes different trade offs on backwards compatibility.

**Comment by arunkumarn123** [comment]
Sorry about that. Thanks for the response
