### ISSUE TITLE
X-axis in plot not following dataframe order

### ISSUE THREAD

**Issue by robroc** [plotly/plotly.py#2122]
I grouped a dataframe's datatime column to weekly periods, and when plotted, the x-axis doesn't follow chronologically, even if the dataframe in sorted properly:

![plotly](https://user-images.githubusercontent.com/1219001/62569222-5ee3cc00-b85c-11e9-8f38-9d2c68e9e252.PNG)

Here's the relevant code in case it's helpful:

```
to_plot = (df.groupby(['colA', df.ad_delivery_start_time.dt.to_period('W').astype(str)])
  .size()
  .reset_index(name='ads')
  .sort_values('ad_delivery_start_time')
)

px.line(to_plot, x='ad_delivery_start_time', y='ads', color = 'colA', height=600)
```

**Comment by emmanuelle** [comment]
Hi @robroc is there any chance you could share here a minimal dataset reproducing the issue? It would help us a lot for finding a fix :-).

**Comment by robroc** [comment]
Hi @emmanuelle. Apologies, I didn't see your response until now.

Funny enough, I can't repeat the error either. Maybe it got fixed in an update. Here's some sample data, but it seems to be ordering the x-axis properly now.

Replace `colA` with `type` in my code.

[plotly_sample_data.zip](https://github.com/plotly/plotly.py/files/4409974/plotly_sample_data.zip)

**Comment by nicolaskruchten** [comment]
Closing as "not reproducible" for now, but please re-open if this ever occurs again with the latest version of `plotly`.
