### ISSUE TITLE
when using px.bar, there is some case weird.

### ISSUE THREAD

**Issue by heumsi** [plotly/plotly.py#2123]
I'm using 

```
px.__version__
```
```
'0.3.0'
```
and jupyter notebook, python 3.6

and I tried this code.
```
a = pd.DataFrame({"data":[1,2,3,4,100]}, index=['A','B','C','5','0']).reset_index()
print(a)
px.bar(a, x='index', y='data')
```
![image](https://user-images.githubusercontent.com/31306282/63247971-41bded00-c2a1-11e9-9d0a-22018abd7a82.png)

I expected this kind of something...

![image](https://user-images.githubusercontent.com/31306282/63248169-b3963680-c2a1-11e9-8544-87ceddf21be8.png)

Is this bug..? or was I confused something..?

**Comment by nicolaskruchten** [comment]
This is an odd edge case of our categorical-vs-continuous detection algorithm. In cases like this you will need to force the axis type to be categorical with `.update_xaxes(type="category")` like this:

```python
import plotly.express as px
import pandas as pd
a = pd.DataFrame({"data":[1,2,3,4,100]}, index=['A','B','C','5','0']).reset_index()
print(a)
px.bar(a, x='index', y='data').update_xaxes(type="category")
```

![image](https://user-images.githubusercontent.com/203523/87718722-4b392900-c780-11ea-9b42-c03a2d0000ba.png)
