### ISSUE TITLE
plotly.express import raises ModuleNotFound in environment without pandas.

### ISSUE THREAD

**Issue by CarlAndersson** [plotly/plotly.py#2125]
Importing plotly.express when pandas is not available raises `ModuleNotFoundError: No module named 'pandas'`, instead of the intended `ImportError: Plotly express requires pandas to be installed.`
This happens on `from ._imshow import imshow`.
Perhaps this import should be moved below the code that will output a more helpful message?

**Comment by emmanuelle** [comment]
Thank you @CarlAndersson ! This should be fixed by #2132.
