### ISSUE TITLE
3D plane visualization

### ISSUE THREAD

**Issue by KyloRen1** [plotly/plotly.py#2134]
I was trying to plot orthogonal 3d plane to a given parametric line equation with given point M. Even though calculations are correct. Plotted figure outputs plane that is not orthogonal to the line indicated by two points. Full code down.

  
    import numpy as np
    centroid = np.array([2.19713507, 2.31639408, 2.29542484])
    target = np.array([18.60952211,  0.55945673,  1.25858935])
   
    def parametric_line_equations(start_point, end_point):
        position_vector = start_point
        direction_vector = end_point - start_point
        print('Parametric line equation: [x, y, z, ...] = {} + t * {}'.format(position_vector, direction_vector))
        print('Normal vector : {}'.format(direction_vector))
        return position_vector, direction_vector

    position_vector, normal_vector = parametric_line_equations(centroid, target)

    def perpendicular_plane_equation(normal_vector, position_vector):
         weights = normal_vector 
         bias = np.matmul(normal_vector, position_vector)
         return weights, bias

     weights, bias = perpendicular_plane_equation(normal_vector, position_vector)
     import plotly.graph_objects as go
     import numpy as np

      x = np.linspace(-30,30,100)
      y = np.linspace(-30,30,100)

      X,Y = np.meshgrid(x,y)
      Z = (bias - weights[0]*X - weights[1]*Y) / weights[2]

      fig = go.Figure(data = [
       go.Surface(x = x,y = y,z = Z), 
       go.Scatter3d(x=np.array(target[0]), y=np.array(target[1]), z=np.array(target[2]), mode='markers'),
       go.Scatter3d(x=np.array(centroid[0]), y=np.array(centroid[1]), z=np.array(centroid[2]), mode='markers'),
       go.Scatter3d(x=[target[0],centroid[0]] , y=[target[1],centroid[1]] , z=[target[2],centroid[2]] ,
       marker=dict(
        size=4,
        colorscale='Viridis',
    ),
        line=dict(
        color='darkblue',
        width=2
    )
    )])
       fig.show()

**Comment by KyloRen1** [comment]
![fig1](https://user-images.githubusercontent.com/35574157/73286857-f53bed80-4200-11ea-8ea8-0e2b71d54d89.jpg)
<img width="689" alt="fig2" src="https://user-images.githubusercontent.com/35574157/73286869-fa993800-4200-11ea-8f64-da8ec99831ce.png">

**Comment by emmanuelle** [comment]
Hi @KyloRen1 the line does not appear to be perpendicular because the three axes don't have the same scale (if the ranges of the 3 axes are very different, the default mode is to make the 3d domain look more or less cubic). You can force the scale of the axes to be the same with
```
fig.update_layout(scene_aspectmode='data') 
```
For more details, please see https://plot.ly/python/3d-axes/#fixed-ratio-axes

**Comment by KyloRen1** [comment]
@emmanuelle Oh, ok! My bad. Thanks a lot
