### ISSUE TITLE
Bar Chart Row Facets example renders with white lines over the bars

### ISSUE THREAD

**Issue by adamerose** [plotly/plotly.py#2148]
The example titled "Bar Chart Row Facets" on the page below shows a bunch of white lines on the bars between each data point. I don't think it is supposed to look like this and haven't seen this on other bar chart examples.
https://plot.ly/python/facet-plots/#bar-chart-row-facets

![image](https://user-images.githubusercontent.com/10884874/73493290-753c9180-4380-11ea-9e9b-826532eb01de.png)

**Comment by nicolaskruchten** [comment]
This is intentional: there are many small stacked bars being rendered, with thin white borders...

**Comment by therealgherkhin** [comment]
how do I get rid of those lines? My csv only contains one value for the y-axis and it still has 2 white lines in it
