### ISSUE TITLE
Parallel Coordinates do not fire on select event

### ISSUE THREAD

**Issue by khuesmann** [plotly/plotly.py#2149]
Hi,
I would like to use the parallel coordinate visualization but i am struggling with making them interactive.
Here an example:

```
import plotly.graph_objects as go

fig = go.Figure(data=
    go.Parcoords(
        line_color='blue',
        dimensions = list([
            dict(range = [1,5],
                 constraintrange = [1,2], # change this range by dragging the pink line
                 label = 'A', values = [1,4]),
            dict(range = [1.5,5],
                 tickvals = [1.5,3,4.5],
                 label = 'B', values = [3,1.5]),
            dict(range = [1,5],
                 tickvals = [1,2,4,5],
                 label = 'C', values = [2,4],
                 ticktext = ['text 1', 'text 2', 'text 3', 'text 4']),
            dict(range = [1,5],
                 label = 'D', values = [4,2])
        ])
    )
)
fig.show()

def on_selection():
    print('hi')
    
fig.data[0].on_selection(on_selection)
```

Analogously to other plots i used the on_selection method. So when i am brushing an axis, i expect the on_selection method to fire, but it doesn't ... Am I doing something wrong or do I miss a special concept on Parcoords or is there a bug?

Thank you in advance!!

**Comment by meffmadd** [comment]
Are there any updates or work-arounds for this issue? 

The documentation mentions that the "callbacks will only be triggered when the trace belongs to a instance of plotly.graph_objs.FigureWidget" which may cause the issue for @khuesmann, however, I use a FigureWidget and still have the same problem described above.

**Comment by Phil-avi** [comment]
Here's a link to the solution [https://community.plotly.com/t/parallel-coordinates-plot-axis-line-event/9489](url)

However, I was using Jupyter Notebook, so I just created a button to fire an event. The callback function reads the constraintrange values.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
