### ISSUE TITLE
Stub out an AI/ML section in the docs

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.py#2153]
If we were to add an "AI/ML" section in the docs on par with Maps, say, what could we put in there? People search for KNN, ROC, PCA etc right now and we don't return any search results.

**Comment by nicolaskruchten** [comment]
@xhlulu consider adding parts of your SVM app in here as well, especially the contour stuff that shows the separation line between the classes! Basically whatever the docs *should* have had to make it super easy for you to write that app back in the day :)

**Comment by emmanuelle** [comment]
@xhlulu I would also recommend a Google search such as "scikit-learn auto_examples" to see which gallery examples are coming first
![image](https://user-images.githubusercontent.com/263366/73695217-aaf6b880-46a7-11ea-8aa3-42c391236f16.png)

**Comment by nicolaskruchten** [comment]
Other thoughts: a nice TSNE example, maybe in both 2 and 3 d?

**Comment by nicolaskruchten** [comment]
@jdamiba can you please do the needed setup for a new section in the docs for AI/ML alongside basic/scientific/statistical etc? @xhlulu will need to be able to add `display_as: ai_ml` to his new doc pages. Let’s display it right below statistical plz and add it to the check_ci scripts etc

**Comment by jdamiba** [comment]
@nicolaskruchten @xhlulu 

https://github.com/plotly/graphing-library-docs/pull/9 is ready to be merged after these docs are merged. It creates a new "Artificial Intelligence and Machine Learning" category in the docs. 

Nice work @xhlulu, these are very valuable additions!
