### ISSUE TITLE
problem in customized ticks in go.Surface 

### ISSUE THREAD

**Issue by aligoglos** [plotly/plotly.py#2158]
I want to customize x and y labels, I tried this but haven't worked!
```
fig = go.Figure(data=[go.Surface(z=z_vals)])
    print(list(lable1))
    print(list(lable2))
    fig.update_layout(scene=dict(
        xaxis=dict(
            nticks = 12,
            ticktext=list(lable1)),
        yaxis=dict(
            nticks=12,
            ticktext=list(lable2)),
    ))
    fig.show()
```
print results:

```
['1398/01', '1398/02', '1398/03', '1398/04', '1398/05', '1398/06', '1398/07', '1398/08', '1398/09', '1398/10', '1398/11', '1398/12']

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l']
```
but always show :
![image](https://user-images.githubusercontent.com/3922472/73725874-949e3a80-4743-11ea-9c07-ec3f1c4100f7.png)

**Comment by empet** [comment]
To set custom ticklabels it's not sufficient to give a list of strings, for `ticktext`. You have to set `tickvals` as a list/array of numerical values, with len(tickvals)=len(ticktext). At these numerical values on  axis will be  located the strings in `ticktext`.

If your surface is defined only by an array, z, of shape (m,n), then, besides ticktext you should define
tickvals = np,arange(12) .

**Comment by aligoglos** [comment]
Thanks a lot.
