### ISSUE TITLE
Add nbformat to dependencies

### ISSUE THREAD

**Issue by rpanai** [plotly/plotly.py#2159]
Apparently `nbformat` is required by the latest plotly version. After a clean install if I try to plot I receive back this error

```bash
ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed
```
If you want I can update the requirements that I guess are [here](https://github.com/plotly/plotly.py/blob/master/packages/python/plotly/requirements.txt).

**Comment by emmanuelle** [comment]
Hi @rpanai thank you for the report. On top of the requirements listed in `requirements.txt`, we also have some optional requirements which are not installed by defaults. `nbformat` is indeed needed to display figures in the notebook. It is a hard dependency of the jupyter-notebook package, so you must have it installed unless you have a very old version of the notebook (nbformat 4.2 was released in December 2016). Could you please confirm that you trying to plot plotly figures inside the jupyter notebook, and also check the versions of jupyter notebook and nbformat which you are using? I don't think we will update the `requirements.txt` because it's only an optional dependency and for a large majority of users (who have updated the notebook since Dec. 2016) it will be already installed. Of course if this is more complex happy to keep on discussing this with you.

**Comment by rpanai** [comment]
Hi @emmanuelle,
* I was trying to plot inside jupyter-lab
* `jupyterlab=0.35.5` was installed in July 2019
* nbformat wasn't installed and it's not required by lab see [requirement](https://github.com/jupyterlab/jupyterlab/blob/master/setup.py) but you're right that's required by jupyter notebook

Anyway apparently this happened on my laptop only as on my VMs I didn't have this problem.

**Comment by emmanuelle** [comment]
Hi @rpanai for jupyter-lab plotly requires a separate extension `jupyterlab-plotly` to be installed as described in https://plot.ly/python/getting-started/#jupyterlab-support-python-35, was it the case for you?

**Comment by rpanai** [comment]
Yes it was.

**Comment by rpanai** [comment]
@emmanuelle I double checked and yes there is an issue. When you have several kernels you can access from jupyter-lab/notebook you need to install `nbformat` within the kernel in order to have plotly works. In the previous version it wasn't necessary.

**Comment by lgwds** [comment]
any updates?

**Comment by rpanai** [comment]
> any updates?

Not that I know. I've to install `nbformat` in all my environments with plotly.

**Comment by lgwds** [comment]
same

**Comment by nicolaskruchten** [comment]
I'll take a closer look and consider adding it to our documentation as a requirement when using JupyterLab. I'm not inclined to add it to the hard requirements for the whole library, though, as not everyone uses Jupyter :)

**Comment by johnnybarrels** [comment]
Same issue arises when using Jupyter notebooks within VSCode, which seems to be becoming a popular Jupyter client.

**Comment by goel-aman** [comment]
> Same issue arises when using Jupyter notebooks within VSCode, which seems to be becoming a popular Jupyter client.

Same thing is happening with me.

**Comment by Niehaus** [comment]
Hello guys, same thing happening with me too

**Comment by sleter** [comment]
I have the same issue running Jupyter Notebooks with VSCode. Nbformat version 5.0.8 already installed

**Comment by nicolaskruchten** [comment]
Hi folks, what is the "same thing" you are are referring to here, that you have to manually install `nbformat` or that something is broken even when you do?

**Comment by rpanai** [comment]
@nicolaskruchten I guess that the problem is that we have to install `nbformat`.

**Comment by sleter** [comment]
@nicolaskruchten
I have `nbformat`, `plotly` and other libraries already installed in conda environment. But when running jupyter notebook with Plotly plots in VSCode it is throwing an error:
`ValueError: Mime type rendering requires nbformat>=4.2.0 but it is not installed`

I created virtualenv (same dependencies) with Pipenv tool and installed a new kernel in Jupyter. When running notebook in VSCode issue resolved itself.

**Comment by johnnybarrels** [comment]
> Hi folks, what is the "same thing" you are are referring to here, that you have to manually install `nbformat` or that something is broken even when you do?

Just the manual install of `nbformat`. All works perfectly once installed :)

**Comment by Niehaus** [comment]
I did the manual install of  `nbformat` and all works for me too, and I'm talking about Jupyter inside VSCode as well.

**Comment by daczarne** [comment]
@nicolaskruchten, @johnnybarrels, or @Niehaus could you elaborate on what you did, please? I have the same issue. I'm using pipenv, Jupyter and VS Code. I run `pipenv install nbformat`, restarted the kernel, but the error is still there. Tried `pipenv install nbformat>=4.2.0` same result. Even tried installing nbformat globally with `pip install nbformat` and then recreating the pipenv, still no luck.

**Comment by Niehaus** [comment]
@daczarne  I was about to reply to you, but it's nice that you've found this solution, nice job!

**Comment by kaiharuto** [comment]
Facing the same error, although i have nbformat installed in the same environment used by the kernel.
```
$ pip freeze | grep nbformat
nbformat==5.1.2
```
installing the extensions mentioned in [Getting Starded](https://plotly.com/python/getting-started/#jupyterlab-support), rebuilding jupyter lab and reinstalling `ipykernel` all didn't help :cry:

**Comment by Anas1981** [comment]
if not work for you try going back  Python v 3.9.8
