### ISSUE TITLE
Better error message if passed in a column name instead of a list of column names into `custom_data`

### ISSUE THREAD

**Issue by chriddyp** [plotly/plotly.py#2177]
`custom_data` is unlike most other `px` properties in that it accepts a list of columns instead of just a single column.

It would be helpful if we said something like "Looks like you supplied a single column name, you should supply a list of columns."

Here's the current error: 
> ValueError: Value of 'custom_data_0' is not the name of a column in 'data_frame'. Expected one of ['uid', 'from_uid', 'dropout', 'embedding_size', 'epoch', 'lr', 'train f1', 'valid ppl'] but received: 19751736_1

**Comment by emmanuelle** [comment]
Good idea. Same for `hover_data` and maybe a couple of others. We'll have to find a clever workaround though to see at which level to catch the error.

**Comment by chriddyp** [comment]
It would also be helpful if we noted _which_ attribute had an error. So, for the error message above, saying something like "You supplied a single column name _to the property custom_data_. This property only accepts a list of column names. Try supplying custom_data=["your-column"] instead of custom_data="your-column""

**Comment by wornbb** [comment]
Do you think it might be better to automatically convert single column data "your-column" to ["your-column"] instead of throwing an error?

**Comment by wornbb** [comment]
If we let it convert "your-column" to ["your-column"], will there be any consequence?

**Comment by nicolaskruchten** [comment]
I'd rather we provide a helpful error message for all the `array_attrables` if what's provided for them is not list-list :)
