### ISSUE TITLE
add symbol types to the marker style chapter

### ISSUE THREAD

**Issue by chriddyp** [plotly/plotly.py#2182]
Marker style comes up as the first hit when we search for marker symbol types, but it doesn't have any examples of symbols

![image](https://user-images.githubusercontent.com/1280389/74277621-ddc33100-4ce5-11ea-8b9e-0f752ea641df.png)

**Comment by emmanuelle** [comment]
As a starting point the code below displays the symbols
```
import plotly.graph_objects as go
fig = go.Figure()
for i in range(45):
    fig.add_trace(go.Scatter(x=[i], y=[1], 
                             marker_symbol=i, marker_color='black', showlegend=False))
    fig.add_trace(go.Scatter(x=[i], y=[2], 
                             marker_symbol=100 + i, marker_color='black', showlegend=False))
fig.show()
```

It should be improved though because at the moment this is very ugly :-)
![image](https://user-images.githubusercontent.com/263366/74278331-0c8dd700-4ce7-11ea-900e-722e1e5f6238.png)

**Comment by emmanuelle** [comment]
@Mahdis-z @jdamiba is one of you interested in taking this one?

**Comment by chriddyp** [comment]
An example we used to have and that we previously work shopped: https://github.com/plotly/documentation/pull/16

**Comment by emmanuelle** [comment]
Also see
https://plot.ly/~etpinard/435/hover-over-the-marker-points-to-see-their-names/#/

**Comment by jdamiba** [comment]
I'm interested! Always wanted to learn more about styling markers and this will be the perfect opportunity.

**Comment by jdamiba** [comment]
closed by https://github.com/plotly/plotly.py/pull/2197
