### ISSUE TITLE
Annotated heatmaps: font colour blends with the colour of the square when using zmin and zmax

### ISSUE THREAD

**Issue by PlatonB** [plotly/plotly.py#2187]
Since there's no reaction to the new message in #1300, I'll write it as a separate issue.

Bug can be reproduced when using `zmin` and `zmax` arguments. Plotly 4.5.0.

```
from random import triangular
import plotly.figure_factory as ff

z = [[round(triangular(0.01, 0.1), 3) for j in range(10)] for i in range(10)]
ff.create_annotated_heatmap(z, colorscale='greens').show()
ff.create_annotated_heatmap(z, colorscale='greens', zmin=0, zmax=1).show()
```

Without `zmin` and `zmax`:
![without_zmin_zmax](https://user-images.githubusercontent.com/25541767/73575713-ce441c80-4489-11ea-8c08-a89bc45bf564.png)

With `zmin=0` and `zmax=1`:
![with_zmin_zmax](https://user-images.githubusercontent.com/25541767/73575733-d9974800-4489-11ea-8108-9223e0baa3f3.png)

**Comment by emmanuelle** [comment]
Thanks @PlatonB this is indeed a bug.

**Comment by bensdm** [comment]
I have the same issue with colorscale='Rdbu'
![image](https://user-images.githubusercontent.com/29406515/93321716-ca93b900-f812-11ea-9ac3-b83ca3481a77.png)

**Comment by nicolaskruchten** [comment]
Agreed, this is a bug, and is probably fixable in this repo rather than Plotly.js, for once :)

**Comment by bensdm** [comment]
Any update on this? should be quite easy to fix. Also was wondering why RdBu is in both sequential and diverging color scales https://plotly.com/python/builtin-colorscales/

**Comment by nicolaskruchten** [comment]
No update, we'd be happy to accept a PR for it if it's easy :) 

The `RdBu` inclusion in sequential was a mistake, as noted in the docs you linked:

![image](https://user-images.githubusercontent.com/203523/98828473-1f644200-2406-11eb-858f-06ebce17502e.png)

**Comment by bensdm** [comment]
I submit a PR, (this is my first one), not sure why one requirement failed https://github.com/plotly/plotly.py/pull/2892
