### ISSUE TITLE
Remove/replace zombie/gremlin pages from website

### ISSUE THREAD

**Issue by emmanuelle** [plotly/plotly.py#2200]
https://plot.ly/python/sending-data-to-charts/
 https://plot.ly/python/2d-density-plots/
https://plot.ly/python/file-options/
https://plot.ly/python/figure-factory/table/
https://plot.ly/python/3d-hover/

(found with a `site:ly plotly "fork on github"` g search)

**Comment by nicolaskruchten** [comment]
I think I got all these using a different approach :)
