### ISSUE TITLE
FigureWidget in Google Colab

### ISSUE THREAD

**Issue by rr5577** [plotly/plotly.py#2202]
I just tried google colab, and using FigureWidget, it doesn´t seem to work, i.e nothing is displayed: 
![image](https://user-images.githubusercontent.com/31547476/74595675-c61cdd00-5044-11ea-967b-7c05357a6d7f.png)

and the browser console shows an error
![image](https://user-images.githubusercontent.com/31547476/74595528-c3b98380-5042-11ea-9a38-bd8971509da5.png)

can this be fixed (by installing something that´s missing from the colab defaults)?

**Comment by lollipopenator** [comment]
I've got the same problem!
file:///home/wendy/pCloudDrive/Screenshots/Screenshot_20200406_colab_plotly_issue.png

**Comment by lollipopenator** [comment]
I've got the same problem!

![Screenshot_20200406_colab_plotly_issue](https://user-images.githubusercontent.com/894111/78502967-17289200-77a7-11ea-93bb-1f91a191bfd3.png)

**Comment by emmanuelle** [comment]
I can reproduce. @jonmmease is the plotlywidget supposed to work in Colab? For a while Colab did not support `ipywidgets` since they had their own widgets but it seems to be working now...

**Comment by jonmmease** [comment]
Last I checked, Colab supported the built-in ipywidgets but not custom widgets. Though that was a while back.

**Comment by flow4u** [comment]
ipywidgets ...buttons and slider work; I can create buttons with actions from a list. However, go.FigureWidget() seems like looping

**Comment by abisi** [comment]
Hello, 
I was trying to reproduce the example from [https://plotly.com/python/figurewidget-app/](https://plotly.com/python/figurewidget-app/) in Google Colab and although a widget like FloatRangeSlider works on its own, I could not make the example work.

<img width="671" alt="Capture d’écran 2020-05-11 à 17 03 28" src="https://user-images.githubusercontent.com/22441447/81577138-6450e280-93a9-11ea-800a-0a69a7109e62.png">

Nothing is shown. Any idea why that may be ?
`g.show()` displays the default graph. 
(Plotly: 4.4.1; ipywidgets: 7.5.1)

Regards,
Axel

**Comment by b-z** [comment]
I have same issue both in colab and jupyter

**Comment by ucalyptus** [comment]
@abisi this would work now. Ipywidgets is supported on colab now.

**Comment by FlorentF9** [comment]
@ucalyptus I tried and it still displays nothing. Have you tried?

**Comment by alexgorbachev** [comment]
Seems like it still doesn't work.

**Comment by SebaVGit** [comment]
Hi everyone, 
@FlorentF9  @alexgorbachev  I tested it a few moments ago an still does not working. Despite it seems that runs correctly, this example does not show anything on the screen.

**Comment by yumyai** [comment]
I tried it and it still does not work. I have no idea why since plotly.offline.iplot or .plot() work fine.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
