### ISSUE TITLE
px.choropleth and px.choropleth_map have some parameters not working

### ISSUE THREAD

**Issue by waterchinap** [plotly/plotly.py#2205]
plotly.__version__ =4.4.1

px.choropleth: I found that the 'geojson' parameter has been removed. however, this parameter is still exist in the document website and the demos.  If this parameter is removed, how can we load our own geojson to plot?

px.choropleth_mapbox: the 'geojson' parameter is working, however, the 'featureidkey' parameter is missing.

**Comment by emmanuelle** [comment]
Hi @waterchinap these parameters have been added in plotly 4.5 this is why you have them in the documentation but not in plotly 4.4. Could you please upgrade your version if you want to use these parameters?

**Comment by waterchinap** [comment]
> Hi @waterchinap these parameters have been added in plotly 4.5 this is why you have them in the documentation but not in plotly 4.4. Could you please upgrade your version if you want to use these parameters?

Thank you very much, great help!

I should have check the version first, I run the update, but the conda library seems not the latest one.
