### ISSUE TITLE
[BUG]: sunburst/pie not using color_discrete_map argument

### ISSUE THREAD

**Issue by emmanuelle** [plotly/plotly.py#2212]
See https://stackoverflow.com/questions/60270054/how-can-i-set-the-colors-on-a-plotly-sunburst-chart

**Comment by emmanuelle** [comment]
The problem also exists for pies:
```
import plotly.express as px
# This dataframe has 244 lines, but 4 distinct values for `day`
df = px.data.tips()
fig = px.pie(df, values='tip', names='day',
            color='day', 
                 color_discrete_map={'Sun':'blue', 
                                     'Sat':'red', 
                                     'Thur':'yellow', 
                                     'Fri':'green'})
fig.show()
```
![image](https://user-images.githubusercontent.com/263366/74751703-a4d21180-523b-11ea-9534-1133ba11f0c5.png)

**Comment by emmanuelle** [comment]
Basically all charts where we accept discrete colors but we have one single trace.

**Comment by amandeep1991** [comment]
It is still not working for me

**Comment by nicolaskruchten** [comment]
Hi @amandeep1991 ! If you could provide your Plotly.py version number and the code that isn't working for you (as well as an explanation of what isn't working/what you expect to see but don't) we would be better able to help you out :)

**Comment by rathipankajj** [comment]
I created a color map like this
color_map={'Other':'#F0F8EF',       
                                        'Device Not Responding':'#F0F8FF', 
                                        'Return':'#636EFA',
                                        'App' : '#EF553B',
                                        'Shipping':'#00CC96',
                                        'Pre-Sales':'#AB63FA',
                                        'Chems not read' : '#FFA15A',
                                        'TEST' : '#19D3F3',
                                        'RMA' : '#FF6692',
                                        'Flow' : '#B6E880',
                                        'Incorrect chems':'#FF97FF'
                                       }

Using it like this in two pie charts but colors don't match up

px.sunburst(sfpie, path=['Type','Case Reason'], values = 'Open',color_discrete_map=color_map
                    )

**Comment by rathipankajj** [comment]
Resolved the issue: needed to specify the color property as well.  In my example, color_map is generated by taking a unique list from a column, say column 'Type'. I had to update the code to include color property in the sunburst chart. Updated line looks like this
px.sunburst(sfpie, path=['Type','Case Reason'], values = 'Open',
                    color='Type',color_discrete_map=color_map
                    )
