### ISSUE TITLE
pyinstaller shows SyntaxWarning: "is" with a literal. Did you mean "=="?

### ISSUE THREAD

**Issue by soerendip** [plotly/plotly.py#2230]
I am trying to package a plotly app with `pyinstaller`. During the process I get these warnings:

c:\users\soere\miniconda3\envs\ms-mint\lib\site-packages\_plotly_utils\utils.py:214: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if (iso_string.split("-")[:3] is "00:00") or (iso_string.split("+")[0] is "00:00"):
c:\users\soere\miniconda3\envs\ms-mint\lib\site-packages\plotly\figure_factory\_candlestick.py:194: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if direction is "increasing":
c:\users\soere\miniconda3\envs\ms-mint\lib\site-packages\plotly\figure_factory\_candlestick.py:199: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif direction is "decreasing":
c:\users\soere\miniconda3\envs\ms-mint\lib\site-packages\plotly\figure_factory\_ohlc.py:176: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if direction is "increasing":
c:\users\soere\miniconda3\envs\ms-mint\lib\site-packages\plotly\figure_factory\_ohlc.py:179: SyntaxWarning: "is" with a literal. Did you mean "=="?

**Comment by ashwinpn** [comment]
Try to upgrade outdated python modules.

```
pip3 list --outdated --format=freeze | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 pip3 install -U

```
Fair warning though, mass upgrade of models could lead to conflicts with package manager installed packages, so maybe you should manually check this out.

**Comment by nicolaskruchten** [comment]
I think #2262 will resolve this.
