### ISSUE TITLE
Feature request: Make px facet work with secondary_y

### ISSUE THREAD

**Issue by claesnn** [plotly/plotly.py#2232]
Currently you are able to make plots with secondary_y using make_subplots, which px.line uses, however, it is not possible to set this using px.line in combination with facet_col.

Is this possible to implement?

I would like to plot multiple data in one graph currently using a approach similar to the below. However, this does not provide a secondary_y axis :/

```
fig = px.line(tank_dataa, x="Minutes", y="Value", facet_col="tank", facet_col_wrap=6)
fig2 = px.line(tank_datab, x="Minutes", y="Value", facet_col="tank", facet_col_wrap=6)
fig.add_traces(fig2.data)
fig.layout.yaxis2.side = "right"
fig.layout.yaxis2.visible = True
fig.show()
```

An optimal implementation would be:

```
fig = px.line(tank_dataa, x="Minutes", y="Value", facet_col="tank", facet_col_wrap=6)
fig2 = px.line(tank_datab, x="Minutes", y="Value", facet_col="tank", facet_col_wrap=6, secondary_y=True)
fig.add_traces(fig2.data)
fig.show()
```

**Comment by claesnn** [comment]
This works, but is super cumbersome :/

`spec_list = [{"secondary_y": True} for x in range(0, 6)]
spec_list = [spec_list, spec_list]

fig = make_subplots(cols=6, rows=2, specs=spec_list)

p1 = px.line(tank_dataa, x="Minutes", y="Value", facet_col="tank", facet_col_wrap=6, height=900)
p2 = px.line(tank_datab, x="Minutes", y="Value", facet_col="tank", facet_col_wrap=6, height=900)

for i, data in enumerate(p1.data):
    row = math.ceil((i + 1) / 6)
    col = i + 1 - (row - 1) * 6
    fig.add_trace(data, secondary_y=False, row=row, col=col)

for i, data in enumerate(p2.data):
    row = math.ceil((i + 1) / 6)
    col = i + 1 - (row - 1) * 6
    fig.add_trace(data, secondary_y=True, row=row, col=col)


fig.show()`

**Comment by nicolaskruchten** [comment]
We definitely want to make this possible with PX, although the API might look a little different!

**Comment by m-ganko** [comment]
Hi, I would like to start working on implemenation of this feature. It is my first contribution in plotly, so I hope to get some feedback ;). Do you have any idea how this API might look?

**Comment by Girmii** [comment]
This is still an issue I encountered in 2026 (plotly 6.5.2), so it might be relevant to re-open.
