### ISSUE TITLE
new data-file storage breaks on some machines

### ISSUE THREAD

**Issue by theengineear** [plotly/plotly.py#224]
We recently switched over to saving data in a special directory relative to `sys.prefix` for our python install. However, this is failing on user's machines.

I've tried multiple times and can't recreate this failure on my machine.

**Comment by theengineear** [comment]
@chriddyp , @etpinard , @cldougl

Mind trying to install plotly in the following way to see if it works?

`pip install -i https://testpypi.python.org/pypi plotly`

What's *supposed* to happen is that a directory called `plotly-data` gets stored wherever you Python's `sys.prefix` is. So, for me:

```
import sys
sys.prefix  # '/Users/ee/venvs/python-api/bin/..'
```

And there's a directory:

`/Users/ee/venvs/python-api/plotly-data`

The above terminal code just installs from the test pypi server instead of from the normal pypi server (the offending version isn't up on the normal pypi).

Note that when installing from test pypi, you'll get errors if you don't already have all the dependencies installed. So you might need to run these if you get failures, like if you're doing this in a new virtualenv:

```
pip install six
pip install requests[security]
pip install pytz
```

**Comment by jonmmease** [comment]
Cannot reproduce, and I don't think this storage approach is still in use.
