### ISSUE TITLE
isosurface is sensitive to ordering of the input data

### ISSUE THREAD

**Issue by JerzyDziewierz-UH** [plotly/plotly.py#2240]
```
import plotly.graph_objects as go
import numpy as np
            
x_base = np.linspace(0, 1, 5)  
y_base = np.linspace(0, 1, 4) 
z_base = np.linspace(0, 1, 3) # note different count of steps on each axis - essential to make the bug appear

# x_mesh, y_mesh, z_mesh = np.meshgrid(x_base, y_base, z_base, indexing = 'ij')  # << Uncomment this to see good effect
x_mesh, y_mesh, z_mesh = np.meshgrid(x_base, y_base, z_base, indexing = 'xy')  # << Uncomment this to see bad effect

fig=go.Figure(
    data=go.Isosurface(
                        x=x_mesh.flatten(),
                        y=y_mesh.flatten(),
                        z=z_mesh.flatten(),
                        value=z_mesh.flatten(),                        
                        isomin=0.2,
                        isomax=0.4)
)
fig.show()
```

---

Buggy effect when `indexing="xy"`  (default option): 

![image](https://user-images.githubusercontent.com/51780492/75708187-446db600-5cb8-11ea-976c-768887935fac.png)

---

Correct effect when `indexing = "ij"` (requires setting an optional flag)

![image](https://user-images.githubusercontent.com/51780492/75708155-30c24f80-5cb8-11ea-926a-f8b6f881a54d.png)

---
 
I can see several possible solutions to this problem, for example:

* Make the input to isosurface insensitive to how the points are sorted(ordered). This is what one would expect when the input is 'flat list' of X-coordinates. Also, make it insensitive to missing points, or non-regular spacing. That would be the most flexible option and it would preserve compatibility with existing code.

OR 

* Make the input to isosurface to be of public and known ordering, e.g. by requiring a shape=(nx, ny, nz) array such as one produced directly by `numpy.meshgrid` and `numpy.mgrid` - this will reduce the need to call `.flatten()` and make many things more obvious

OR

* Make it clear in the documentation that the input from numpy.meshgrid is not supported unless special option `indexing="ij"` is enabled. 

OR

there are several other possible solutions to this -- I will let you decide.

p.s. credit for figuring this out goes to `Hector Barreiro Cabrera`

**Comment by JerzyDziewierz-UH** [comment]
when the ordering is "unexpected", you get a different jaggy pattern depending on which dimension has how many steps:
e.g. for 
```
x_base = np.linspace(0, 1, 3)
y_base = np.linspace(0, 1, 4)
z_base = np.linspace(0, 1, 5)
```
one gets:
![image](https://user-images.githubusercontent.com/51780492/75709546-c7900b80-5cba-11ea-9a00-36e5f67c4fc7.png)

for
```
x_base = np.linspace(0, 1, 6)
y_base = np.linspace(0, 1, 2)
z_base = np.linspace(0, 1, 2)
```
one gets:
![image](https://user-images.githubusercontent.com/51780492/75709590-e1315300-5cba-11ea-8ed2-f7f79799c8c1.png)


The possibilities are limitless :-) except for that in all these cases I was expecting a solid block like this:
![image](https://user-images.githubusercontent.com/51780492/75709660-03c36c00-5cbb-11ea-838e-ce8508adb1a9.png)


The examples from the documentation at https://plot.ly/python/3d-isosurface-plots/ do not show this problem because they always go for equal count of data steps along each axis.

**Comment by empet** [comment]
It seems you are running an old Plotly version because with 4.5.2 I  cannot reproduce your reported issue. Please upgrade  via:
```
pip install plotly --upgrade
```

**Comment by JerzyDziewierz-UH** [comment]
I report that saying

`conda update plotly` 

reports

```
The following packages will be UPDATED:
plotly                          plotly::plotly-4.4.1-py_0 --> pkgs/main::plotly-4.5.0-py_0
```

and sorts the issue for me. No more problems. Thank You!
