### ISSUE TITLE
Using plotly with jupyterlab 2.0

### ISSUE THREAD

**Issue by emmanuelle** [plotly/plotly.py#2244]
See https://community.plot.ly/t/jupyterlab-2-0-support/35715

**Comment by buddythumbs** [comment]
Is there a workaround for this until a fix is generated?

**Comment by nicolaskruchten** [comment]
There is no workaround other than not using JupyterLab 2.x at the moment, but we should have a fix out shortly :)

**Comment by nicolaskruchten** [comment]
The fix for building the extensions is now out but see https://github.com/plotly/plotly.py/issues/2249 for a remaining issue with the `FigureWidget`
