### ISSUE TITLE
Scatter plot(Line plots) changed from 3.6.0 to 4.5.2

### ISSUE THREAD

**Issue by javidsch** [plotly/plotly.py#2248]
On fresh version(4.5.2), on-hover action shows only information/title about one dot on the plot. 
On early version(3.6.0) it works differently: shows value of X axis, and every Y-axis value for plots.
One on-hover action: a lot of information shown.
Is it possible to do the same behavior on 4.5.2 what was on 3.6.0 default behavior?

![image](https://user-images.githubusercontent.com/28500366/75997396-f0591080-5f07-11ea-943f-debf920c4138.png)
![image](https://user-images.githubusercontent.com/28500366/75997428-fa7b0f00-5f07-11ea-987d-d65ba98c5f50.png)

**Comment by nicolaskruchten** [comment]
Yes, we changed the value of `layout.hovermode` in the default template. from `x` to `closest` but you can set it back to `x` to bring back the old behaviour.

You can also get all the old behaviours (and colors and positioning etc) back by setting `layout.template` to the string `"none"`.

**Comment by javidsch** [comment]
Cool! Thanks!
