### ISSUE TITLE
plotlywidget 1.5.3 fails to render FigureWidget in JupyterLab 2.x

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.py#2249]
Although https://github.com/plotly/plotly.py/pull/2245 allowed us to install the extensions into JupyterLab, it looks like the `FigureWidget` is currently broken in JupyterLab 2.x

**Comment by nicolaskruchten** [comment]
Note that `plotlywidget@1.5.3` contains no changes compared to `plotlywidget@1.5.2`, and its `package-lock.json` contains references to `@phosphor` via `@jupyter-widgets/base@2.0.0` ... upgrading to `@jupyter-widgets/base@3.0.0` causes it to work in JupyterLab 2.0 but not 1.2 so that alone is not a backwards-compatible change.

Ideally we would find a backwards-compatible change, or we'll have to do the awkward documentation thing where we say "JupyterLab 1.2 needs this and JupyterLab 2.0 needs that" :(

**Comment by consideRatio** [comment]
If I would had been more observant, my initial PR to support JupyterLab 2.0.0 would have also made the plotlywidget extension support it in the same sense as for the plotly-extension. I would do it by ensuring its dependencies were specified to allow for both use of JupyterLab 1 and 2 dependencies, which it use in a non-breaking way as far as I understand.

> upgrading to @jupyter-widgets/base@3.0.0 causes it to work in JupyterLab 2.0 but not 1.2 so that alone is not a backwards-compatible change.

## Dear rubber duck of understanding...
I've learned that jupyter-widgets/base 2 is requested by plotly-extension and @jupyter-widgets/jupyterlab-manager, and installing it for JupyterLab 2 requires a lot of JupyterLab 2 dependencies. Hmmm...

I really struggle to grasp all this, but, what I know is, that I think it would make sense to do the PR, as that allow it to install with the available JupyterLab 2 dependencies and not specifically JupyterLab 1 dependencies. I think...

**Comment by consideRatio** [comment]
@nicolaskruchten thanks for your work on this project :heart:! This issue should be closed now :tada:!

**Comment by nicolaskruchten** [comment]
Thanks for the reminder, and for *your* work on helping us keep up with the world of JupyterLab :)
