### ISSUE TITLE
import plotly.graph_objects fails with ipywidget version is <= 7.0.0

### ISSUE THREAD

**Issue by GaelVaroquaux** [plotly/plotly.py#2264]
Steps to reproduce:
<pre>
$ python3.7 -m venv test
$ . test/bin/activate
(test) $ pip install plotly
(test) $ pip install ipywidgets==6
(test) $ python -c "import plotly.graph_objects"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/varoquau/tmp/clean_venv/test/lib/python3.7/site-packages/plotly/graph_objects.py", line 2, in <module>
    from plotly.graph_objs import *
AttributeError: module 'plotly.graph_objs' has no attribute 'FigureWidget'
</pre>
The problem is on line 100184 of plotly/graph_objs/__init__.py: the `__all__.append("FigureWidget")` that is a few lines below should be moved under the "if" clause.

Given that it is generated code, I don't know how to fix it, so I won't send a pull request.

**Comment by nicolaskruchten** [comment]
Indeed, we don’t support anything below 7.2.

**Comment by nicolaskruchten** [comment]
Sorry, that’s actually 7.2 for classic Notebook and 7.5 for Jupyter Lab, according to our docs at https://plot.ly/python/getting-started/

**Comment by nicolaskruchten** [comment]
🤦‍♂ sorry, I misread your issue. Importing should not fail, clearly :)

**Comment by GaelVaroquaux** [comment]
> Importing should not fail, clearly :)

Thanks, I was hesitating with replying that, wondering if I was being an A-hole. :)

**Comment by nicolaskruchten** [comment]
> wondering if I was being an A-hole. :)

Nope that was me ;)
