### ISSUE TITLE
px.histogram marginal and facet_row don't play well together

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.py#2266]
```python
px.histogram(px.data.gapminder().query("year==2007"), 
    x="lifeExp", marginal="rug", facet_row="continent")
```

![image](https://user-images.githubusercontent.com/203523/76375118-64862080-631b-11ea-8d90-a1496ebd21f0.png)

**Comment by xhlulu** [comment]
when using `marginal_x` any value given to `facet_col_wrap` will be ignored:

![image](https://user-images.githubusercontent.com/21180505/125488966-8691b418-140d-4e98-9f81-4b6dfe53d56a.png)

`marginal_y` seems to be ignored completely when using facets:
![image](https://user-images.githubusercontent.com/21180505/125489146-bf60ad6c-b799-44b9-9f4b-37a3339e246e.png)

Don't have a short reproduceable example but I can think of one if needed

**Comment by nicolaskruchten** [comment]
This is correct and as designed :)

**Comment by nicolaskruchten** [comment]
We don't currently reaggregate across facets, and we don't support multiple rows of marginals (i.e. with wrapping).
