### ISSUE TITLE
incorrect rientation of y-axis in heatmap

### ISSUE THREAD

**Issue by deliciouslytyped** [plotly/plotly.py#2267]
https://github.com/plotly/plotly.py/issues/413 remains a problem, but due to being unable to reopen the issue, I have created this one.

**Comment by nicolaskruchten** [comment]
Is the follow-up on the conversation in #413 helpful or does it make sense to keep this issue open?

**Comment by laughingrice** [comment]
It appears that plotly.express.imshow does not work with plotly.graph_objects.make_subplots that requires plotly.graph_objects.Heatmap

I could not get any of the suggestions to work at all, or on a per matrix case.

Being able to flip the matrices is pretty critical to allow to match y-axis orientation with the problem at hand (both matrices and images), especially as different tools are used in different contexts so it's pretty essential to be able to match orientations between the different tools

The only solution I found is to set dy=-1 but that messes up the y axis values
