### ISSUE TITLE
switch from clientresp to `api.plot.ly/v2/*` endpoints

### ISSUE THREAD

**Issue by theengineear** [plotly/plotly.py#227]
a _lot_ of care needs to be taken here. Note that all public users of plot.ly will be _OK_ if we just switch this, but private users of plot.ly will _not_ have the most updated backend.

**Comment by chriddyp** [comment]
@theengineear is the new plots endpoint live?

Here, I guess we'll:
- check if accessing public site: then use new endpoint
- if using on-prem, then hit clientresp until next on-prem release
- on next on-prem release, release a new client lib which will hit the new endpoing. if a 404 is returned, then it'll fallback to clientresp

**Comment by theengineear** [comment]
@chriddyp , plot creation isn't supported yet. I'm on that this week as I attempt to prep us to migrate away from clientresp.

And yeah, what you listed is along the lines of how I was thinking of dealing with the problem. Shouldn't be too bad :)
