### ISSUE TITLE
plotly express error: cannot import name 'qualitative'

### ISSUE THREAD

**Issue by nhohung** [plotly/plotly.py#2281]
Hi,

I'm trying to create a Choropleth map using plotly express. However when importing plotly express, I got an error:
code:
`import plotly.express as px`
error:
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-39-86e89bd44552> in <module>
----> 1 import plotly.express as px

/opt/conda/envs/Python36/lib/python3.6/site-packages/plotly/express/__init__.py in <module>
     13     )
     14 
---> 15 from ._imshow import imshow
     16 from ._chart_types import (  # noqa: F401
     17     scatter,

/opt/conda/envs/Python36/lib/python3.6/site-packages/plotly/express/_imshow.py in <module>
      1 import plotly.graph_objs as go
      2 from _plotly_utils.basevalidators import ColorscaleValidator
----> 3 from ._core import apply_default_cascade
      4 import numpy as np
      5 

/opt/conda/envs/Python36/lib/python3.6/site-packages/plotly/express/_core.py in <module>
      4 
      5 from _plotly_utils.basevalidators import ColorscaleValidator
----> 6 from .colors import qualitative, sequential
      7 import math
      8 import pandas as pd

ImportError: cannot import name 'qualitative'
```
This issue is different from issue plotly [#26793](https://community.plot.ly/t/import-plotly-express-error/26793), plotly express [#1672](https://github.com/plotly/plotly.py/issues/1672) and [#123](https://github.com/plotly/plotly_express/issues/123).

I have tried uninstalling plotly, both via `pip` and `conda` and reinstalling plotly version 4 as suggested at the main [github page](https://github.com/plotly/plotly_express), [pypi](https://pypi.org/project/plotly-express/) and [plotly](https://plot.ly/python/getting-started/). However there is no success.

Just to be clear, I run an environment on cloud.IBM.com notebook, python 3.6, built-in plotly 3.6.1.

I have no further clue how to fix this, please provide some help. Any suggestion is appreciated.

Thanks,
Hung

**Comment by emmanuelle** [comment]
Hum, it seems to be something related to your environment? Could you try the import in a completely fresh environment to diagnose? Also, if you're using the "built-in plotly 3.6.1", version 3.6.1 did not include plotly.express, you need a version greater than >= 4 for this. For further help, please provide the list of packages installed in your environment.

**Comment by nhohung** [comment]
Hi Emmanuelle,

Thanks for your response.

I am aware that I need plotly version higher than 4. In my previous post, I have tried uninstalled plotly and reinstalled the newest version (4.5.4) but it didn't help.

Today when I basically redo everything, it works! My best guess is because the instance is restarted.

For those who have the same problem, this is exactly what I run at the beginning of my notebook:
```
! pip freeze   # optional: this is to check current installed package
! pip install plotly --upgrade   # this to update plotly to latest version, at the time of this post: 4.5.4
! pip install plotly   # might be unnecessary, but I did this
import plotly.express as xp   # now it works
```

Therefore, I'm closing the issue. Thanks for your help.

Hung

FYI, below lists my installed packages:
```
absl-py==0.7.0
alabaster==0.7.12
anaconda-client==1.7.2
anaconda-project==0.8.2
arcgis==1.6.0
asn1crypto==0.24.0
astor==0.7.1
astroid==2.1.0
astropy==3.1.1
astunparse==1.6.2
atomicwrites==1.3.0
attrs==18.2.0
autoai-libs==1.10.5
Babel==2.6.0
backcall==0.1.0
backports.os==0.1.1
backports.shutil-get-terminal-size==1.0.0
beautifulsoup4==4.7.1
biopython==1.72
bitarray==0.8.3
bkcharts==0.2
blaze==0.11.3
bleach==3.1.0
bokeh==1.0.4
boto==2.49.0
boto3==1.9.82
botocore==1.12.82
Bottleneck==1.2.1
brunel==2.3
category-encoders==2.0.0
certifi==2019.11.28
cffi==1.11.5
chardet==3.0.4
Click==7.0
cloudpickle==0.7.0
clyent==1.2.2
colorama==0.4.1
colour==0.1.5
contextlib2==0.5.5
cplex==12.9.0.0
cryptography==2.5
cx-Oracle==7.0.0
cycler==0.10.0
Cython==0.29.5
cytoolz==0.9.0.1
dask==1.1.1
datashape==0.5.4
decorator==4.3.2
defusedxml==0.5.0
dill==0.2.8.2
distributed==1.25.3
docloud==1.0.375
docplex==2.12.182
docutils==0.14
entrypoints==0.3
et-xmlfile==1.0.1
fastcache==1.0.2
filelock==3.0.10
Flask==1.0.2
Flask-Cors==3.0.7
future==0.17.1
gast==0.2.2
geographiclib==1.49
geojson==2.4.1
geopy==1.18.1
gevent==1.4.0
glob2==0.6
gmpy2==2.0.8
greenlet==0.4.15
grpcio==1.16.1
h5py==2.9.0
heapdict==1.0.0
html5lib==1.0.1
ibm-bias-detection==1.0.8
ibm-cos-sdk==2.4.3
ibm-cos-sdk-core==2.4.3
ibm-cos-sdk-s3transfer==2.4.3
ibm-db==2.0.9
ibm-db-sa==0.3.4
ibmdbpy==0.1.5
idna==2.8
imageio==2.4.1
imagesize==1.1.0
importlib-metadata==0.7
ipykernel==5.1.0
ipython==7.2.0
ipython-genutils==0.2.0
ipywidgets==7.4.2
isort==4.3.4
itsdangerous==1.1.0
JayDeBeApi==1.1.1
jdcal==1.4
jedi==0.13.2
jeepney==0.4
Jinja2==2.10
jmespath==0.9.3
JPype1==0.6.3
JPype1-py3==0.5.5.2
jsonschema==2.6.0
jupyter==1.0.0
jupyter-client==5.2.4
jupyter-console==6.0.0
jupyter-core==4.4.0
jupyter-pip==0.3.1
jupyterlab==0.35.3
jupyterlab-server==0.2.0
Keras==2.2.4
Keras-Applications==1.0.6
Keras-Preprocessing==1.0.5
keyring==18.0.0
kiwisolver==1.0.1
lazy==1.4
lazy-object-proxy==1.3.1
libarchive-c==2.8
lief==0.9.0
llvmlite==0.27.0
locket==0.2.0
lomond==0.3.3
lxml==4.3.1
Markdown==3.0.1
MarkupSafe==1.1.0
matplotlib==3.0.2
mccabe==0.6.1
mistune==0.8.4
mkl-fft==1.0.10
mkl-random==1.0.2
mock==2.0.0
more-itertools==5.0.0
mpld3==0.3
mpmath==1.1.0
msgpack==0.6.1
multipledispatch==0.6.0
nbconvert==5.4.0
nbformat==4.4.0
networkx==2.2
nltk==3.4
nose==1.3.7
notebook==5.7.8
numba==0.42.0
numexpr==2.6.9
numpy==1.15.4
numpydoc==0.8.0
odo==0.5.1
olefile==0.46
openpyxl==2.6.0
packaging==19.0
pandas==0.24.1
pandocfilters==1.4.2
parso==0.3.2
partd==0.3.9
path.py==11.5.0
pathlib2==2.3.3
patsy==0.5.1
pbr==5.1.3
pep8==1.7.1
pexpect==4.6.0
pickleshare==0.7.5
Pillow==5.4.1
pixiedust==1.1.17
pkginfo==1.5.0.1
plotly==3.6.1
pluggy==0.8.1
ply==3.11
project-lib==1.7.1
prometheus-client==0.5.0
prompt-toolkit==2.0.8
protobuf==3.6.1
psutil==5.5.0
psycopg2==2.7.6.1
ptyprocess==0.6.0
py==1.7.0
pyarrow==0.11.1
pycodestyle==2.5.0
pycosat==0.6.3
pycparser==2.19
pycrypto==2.6.1
pycurl==7.43.0.2
pyflakes==2.1.0
Pygments==2.3.1
pylint==2.2.2
pymssql==2.1.4
pyodbc==4.0.25
pyOpenSSL==19.0.0
pyparsing==2.3.1
pypyodbc==1.3.4
pyshp==2.1.0
PySocks==1.6.8
pytest==4.2.1
pytest-arraydiff==0.3
pytest-astropy==0.5.0
pytest-doctestplus==0.2.0
pytest-openfiles==0.3.2
pytest-remotedata==0.3.1
python-dateutil==2.7.5
pytz==2018.9
PyWavelets==1.0.1
PyYAML==3.13
pyzmq==17.1.2
QtAwesome==0.5.6
qtconsole==4.4.3
QtPy==1.6.0
requests==2.21.0
retrying==1.3.3
rope==0.11.0
ruamel-yaml==0.15.46
s3transfer==0.1.13
scikit-image==0.14.1
scikit-learn==0.20.3
scipy==1.2.0
seaborn==0.9.0
SecretStorage==3.1.0
Send2Trash==1.5.0
simplegeneric==0.8.1
singledispatch==3.4.0.3
six==1.12.0
snowballstemmer==1.2.1
sortedcollections==1.1.2
sortedcontainers==2.1.0
soupsieve==1.7.1
Sphinx==1.8.4
sphinxcontrib-websupport==1.1.0
spyder==3.3.3
spyder-kernels==0.4.2
SQLAlchemy==1.2.18
statsmodels==0.9.0
streamsx==1.13.14
sympy==1.3
tables==3.4.4
tabulate==0.8.2
tblib==1.3.2
tensorflow==1.13.1
tensorflow-estimator==1.13.0
termcolor==1.1.0
terminado==0.8.1
testpath==0.4.2
toolz==0.9.0
tornado==5.1.1
tqdm==4.31.1
traitlets==4.3.2
typed-ast==1.3.1
unicodecsv==0.14.1
urllib3==1.24.1
watson-machine-learning-client==1.0.376
wcwidth==0.1.7
webencodings==0.5.1
Werkzeug==0.14.1
widgetsnbextension==3.4.2
wrapt==1.11.1
wurlitzer==1.0.2
xlrd==1.2.0
XlsxWriter==1.1.2
xlwt==1.3.0
zict==0.1.3
```

**Comment by emmanuelle** [comment]
great, glad to see you could solve the problem!

**Comment by kenaitian** [comment]
i did what @nhohung suggested above and which worked for him but I'm getting the same error:

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-73-f2b0683563b3> in <module>
      4 
      5 # x and y given as array_like objects
----> 6 import plotly.express as px
      7 fig = px.scatter(sorted_country_df.head(10), x='country', y='confirmed', size='confirmed', 
      8                   color='country', hover_name='country', size_max=60)

/opt/conda/envs/Python36/lib/python3.6/site-packages/plotly/express/__init__.py in <module>
     13     )
     14 
---> 15 from ._imshow import imshow
     16 from ._chart_types import (  # noqa: F401
     17     scatter,

/opt/conda/envs/Python36/lib/python3.6/site-packages/plotly/express/_imshow.py in <module>
      1 import plotly.graph_objs as go
      2 from _plotly_utils.basevalidators import ColorscaleValidator
----> 3 from ._core import apply_default_cascade
      4 import numpy as np
      5 

/opt/conda/envs/Python36/lib/python3.6/site-packages/plotly/express/_core.py in <module>
      4 
      5 from _plotly_utils.basevalidators import ColorscaleValidator
----> 6 from .colors import qualitative, sequential
      7 import math
      8 import pandas as pd

ImportError: cannot import name 'qualitative'

**Comment by kenaitian** [comment]
I followed the instructions per @nhohung suggested above eand restarting the kernel from the IBM Watson Notebook fixed the issue.

**Comment by shubendu** [comment]
It worked for me thank you so much

**Comment by Jeremias-Tivane** [comment]
**You can install it in command line via pip:**
`pip install plotly
`
**Or Install specific version:**
`pip install "plotly==4.5.2"
`
