### ISSUE TITLE
update_layout only applies to one plot when faceting in Express

### ISSUE THREAD

**Issue by robroc** [plotly/plotly.py#2292]
When using `facet_col` and `facet_col_wrap` in plotly express, any axis-specific commands in `update_layout` only apply to the bottom left chart.

![small_multiples](https://user-images.githubusercontent.com/1219001/77082769-f0124800-69d2-11ea-8bf3-5b03e92d7c62.png)

```
(px.line(df, x = 'days_since_50', y = 'cases', facet_col = 'Country', facet_col_wrap = 5, log_y = True, height = 800)
.update_layout(
    autosize=True,
    showlegend=False,
    plot_bgcolor='white',
    xaxis=dict(
        showgrid=True,
        showline=True,
        showticklabels=True,
        gridwidth=0.5,
        gridcolor='lightgrey'
        ),
    yaxis=dict(
        showgrid=True,
        showticklabels=True,
        gridwidth=0.5,
        gridcolor='lightgrey'
       )
    )
)
```

**Comment by nicolaskruchten** [comment]
Yes, that's why we added `.update_xaxes()` and `.update_yaxes()` which will apply those changes to either all x/y axes or you can target specific subplots with `row` and `col`.

**Comment by nicolaskruchten** [comment]
Nice plot BTW :)
