### ISSUE TITLE
pio.write_image is not showing markers on go.scatter graph

### ISSUE THREAD

**Issue by supr3m3** [plotly/plotly.py#2296]
Hi, 

I am having issue with exporting this figure. It is not displaying the symbol on the scatter graph. Please see below:

This is how the figures looks on the dashboard.
![newplot (28)](https://user-images.githubusercontent.com/45615840/77148438-d1509780-6a4c-11ea-991e-4c914e9b14b6.png)

But with the static image export via `pio.write_image()`, the figure does not show the symbol on the figure.
![CoSTAR_alpha_2_robot_activity](https://user-images.githubusercontent.com/45615840/77149253-6607c500-6a4e-11ea-9eee-9870e38a22b4.png)

```
        mask_in = (robot_in_events['event_type__name']=='Ingress')
        res = list(compress(range(len(mask_in)), mask_in))
        for j in res:
            if not 'Ingress' in event_types:
                markers_in[j] = 'line-ew-open'
            else:
                markers_in[j] = 'triangle-right'

        mask_in = (robot_in_events['event_type__name']=='Gate Trip')
        res = list(compress(range(len(mask_in)), mask_in))
        for j in res:
            if not 'Gate Trip' in event_types:
                markers_in[j] = 'line-ew-open'
            else:
                markers_in[j] = 'x-open'

    trace0 = go.Scatter(
            x = xdata_in,
            y = ydata_in,
            name = 'robot',
            mode = 'lines+markers',
            marker = dict(
                size = 20,
                symbol = markers_in,
                line = dict(
                    width = 2,
                ),    
            ),
            hoverinfo = 'text',
            # text = 'Robot ID: ' + unique_robot_list[i-1] + '<br>',
            showlegend = False
        )
        
        data.append(trace0)
```

**Comment by nicolaskruchten** [comment]
That is quite strange... What version of `orca` are you running?

**Comment by nicolaskruchten** [comment]
Are you able to export the image from this example? https://plot.ly/python/marker-style/#custom-marker-symbols 

Locally this works for me with Orca 1.3 and 1.2 as per the "status" section from https://plot.ly/python/orca-management/#status

**Comment by supr3m3** [comment]
I was able to export the figure above with the symbol showing and I am running Orca1.2.1.  I still can't figure out why the symbol won't show on my graph.

**Comment by supr3m3** [comment]
It looks like the issue is caused by the for-loop on my markers... If I use markers = symbols, `    symbols.append(raw_symbols[i])
` from the example you gave me, I can see the markers on my figure.

**Comment by nicolaskruchten** [comment]
Could you please share a bit more of your code? I'm having trouble understanding what `markers_in` is and how it's constructed :)

**Comment by supr3m3** [comment]
@nicolaskruchten I figured it out! It looks like the `if-not` statement (see the commented out code below) on the markers was causing the issue. Any idea why that didn't affect the dashboard figure though, but only the export figure?

```
for i in range(1, robot_list_count+1):
        robot_in_mask = metadata['asset'] == unique_robot_list[i-1]
        entity_in_mask = robot_activity['entity'] == unique_robot_list[i-1]
        robot_in_events = robot_activity[robot_in_mask | entity_in_mask]
        
        idx_egress_in = np.flatnonzero(robot_in_events['event_type__name']=='Egress')
        idx_ingress_in = np.flatnonzero(robot_in_events['event_type__name']=='Ingress')

        robot_in_events.iloc[idx_egress_in]
        robot_in_events.iloc[idx_ingress_in]
        
        xdata_in = pd.Series()
        xdata_in = xdata_in.append(pd.to_datetime(robot_in_events['start_datetime'], utc=False).dt.tz_localize('US/Central'))
        xdata_in = xdata_in.dt.tz_convert('US/Pacific')
        ydata_in = np.ones(len(xdata_in)) * i
    
        markers_in = [42] * len(xdata_in)
       
        mask_in = (robot_in_events['event_type__name']=='Traversal of Note')
        res = list(compress(range(len(mask_in)), mask_in))
        for j in res:
            # if not 'Traversal of Note' in event_types:
            #     markers_in[j] = 141
            # else:
            markers_in[j] = 108
```
