### ISSUE TITLE
[BUG] Plotly Express (px) pandas datetime with timezone converted to UTC

### ISSUE THREAD

**Issue by m0wer** [plotly/plotly.py#2311]
Similar to what happened in <https://github.com/plotly/plotly.py/issues/209> Plotly Express converts the Pandas datetime object to UTC instead of respecting its timezone. If the datetime is a string or is converted to `pydatetime` it works as expected. A reproducible example is available at <https://gist.github.com/m0wer/74d5a8901b9499795d13992d29cc2f0c>.

A workaround (shown in the example) is to convert the datetime column of the Pandas DataFrame to `pydatetime` with:

```python
df['date'].dt.to_pydatetime()
```

**Comment by amadeuspzs** [comment]
I can confirm this behaviour and also perceive it to be a bug

**Comment by nicolaskruchten** [comment]
Hmm, it is really unfortunate that Plotly Express behaves differently than Graph Objects here, as `px.scatter(df, x='date', y='value')` does what is expected. I'll have to think about how big a breaking change this is.

**Comment by nicolaskruchten** [comment]
Update: `px.scatter(df, x='date', y='value')` does *not* do what is expected per the changes we made in the 4.0 release (see https://plotly.com/python/v4-migration/#timezones), but `go.Figure(go.Scatter(x=df["date"], y=df["value"]))` does in this particular case... digging into why and what we can do about it.

**Comment by nicolaskruchten** [comment]
I suspect this was introduced in https://github.com/plotly/plotly.py/pull/1934 because pulling the `.values` out of a series seems to strip the timezone information:

![image](https://user-images.githubusercontent.com/203523/91625705-95185000-e977-11ea-8eab-2b295fa1c301.png)

@jonmmease @alexcjohnson @emmanuelle should we fix this? The bug has been in the wild now much longer than the non-buggy code :(

**Comment by nicolaskruchten** [comment]
Also cc @chriddyp would love your input on this one.

**Comment by nicolaskruchten** [comment]
I'm thinking we should fix it... the only plots which will break are those where folks made plots on an hourly timescale and fed in data with timezones but really wanted the plot to be in UTC and relied on the fact that it's automatic, which feels like a small set to me.

**Comment by alexcjohnson** [comment]
I think I agree we should fix it - px and non-px need to behave the same, and if / when we implement real timezone support in plotly.js the fixed version will still be compatible.

**Comment by nicolaskruchten** [comment]
I should add that this only happens when the input is a pandas datetime column, not a column of ISO strings and not a numpy array of dates or that kind of thing.

**Comment by jonmmease** [comment]
I would favor fixing this since it is a bug with respect to the v4 change log.

**Comment by emmanuelle** [comment]
I also think we should fix it.

**Comment by nicolaskruchten** [comment]
Resolved in 4.10 https://community.plotly.com/t/announcing-plotly-py-4-10-date-axis-improvements-a-faster-px-imshow-and-full-figures-for-development/44685

**Comment by amadeuspzs** [comment]
Thanks for fixing this I was coming here to file a bug report!
