### ISSUE TITLE
How to create annotated heatmaps in subplots?

### ISSUE THREAD

**Issue by rtadewald** [plotly/plotly.py#2313]
Hello.
I'm trying to create a subplot of annotated heatmaps using Dash + Plotly. 
Without using annotated heatmaps (from Figure Factory), the following code get what I want:
```
...
fig = make_subplots(rows=1, cols=2)
fig.add_trace(go.Heatmap(x=x1, y=y1, z=z1, colorscale='RdBu'), row=1, col=1)
fig.add_trace(go.Heatmap(x=x2, y=y2, z=z2, colorscale='RdBu'), row=1, col=2)
...
```

But, when I try to use annotated heatmaps, it becames hard. (In matplotlib, it's just passing an parameters **annot=True**).
Does anyone can help me?

**Comment by rtadewald** [comment]
Changing my code to that:
```
fig1 = ff.create_annotated_heatmap(z=df_fr_review.values, colorscale='RdBu')
fig2 = ff.create_annotated_heatmap(z=df_doid_review.values, colorscale='RdBu')

for i in range(len(fig1.data)):
    fig1.data[i].xaxis='x1'
    fig1.data[i].yaxis='y1'
fig1.layout.xaxis1.update({'anchor': 'y1'})
fig1.layout.yaxis1.update({'anchor': 'x1'})

for i in range(len(fig2.data)):
    fig2.data[i].xaxis='x2'
    fig2.data[i].yaxis='y2'
fig2['layout']['xaxis2'] = {}
fig2['layout']['yaxis2'] = {}
fig2.layout.xaxis2.update({'anchor': 'y2'})
fig2.layout.yaxis2.update({'anchor': 'x2'})

fig.add_trace(fig1.data[0], row=1, col=1)
fig.add_trace(fig2.data[0], row=1, col=2)
fig.layout.update(fig1.layout)
fig.layout.update(fig2.layout)
```
Results in this (no annot information on the second figure):
![image](https://user-images.githubusercontent.com/22618324/77557785-e9834500-6e98-11ea-99ed-4eec11a6067f.png)

**Comment by emmanuelle** [comment]
Hi @rtadewald, you need to change the annotations of the second figure so that they are on the second xaxis:
```
import plotly.figure_factory as ff
from plotly.subplots import make_subplots

z = [[.1, .3, .5, .7, .9],
     [1, .8, .6, .4, .2],
     [.2, 0, .5, .7, .9],
     [.9, .8, .4, .2, 0],
     [.3, .4, .5, .7, 1]]

fig1 = ff.create_annotated_heatmap(z)
fig2 = ff.create_annotated_heatmap(z)
for annot in fig2['layout']['annotations']:
    annot['xref'] = 'x2'
fig = make_subplots(rows=1, cols=2)
fig.add_trace(fig1.data[0], row=1, col=1)
fig.add_trace(fig2.data[0], row=1, col=2)
fig.update_layout(fig1.layout)
fig.layout.annotations += fig2.layout.annotations
fig.show()
```
This is quite hacky though, we should rather have the labels as a scatter trace with text rather than layout annotations, this would make it easier. Maybe we'll incorporate this feature in `px.imshow` in the future.

**Comment by emmanuelle** [comment]
please close the issue if this solves your problem

**Comment by noob-procrastinator** [comment]
An example on you you can add annotations to heatmap by using scatter plot :

```
def draw_heatmap(df, y):
    """

    Parameters
    ----------
    df : pandas.DataFrame
    y: list[str]
        The names of the column to be used for the heatmap separation
    Returns
    -------
    plotly.graph_object.Figure
    """
    fig = make_subplots(
        rows=2,
        cols=1,
        shared_xaxes=True,
        vertical_spacing=0.02)

    fig.add_trace(go.Heatmap(x=df[x], y=df[y1], z=df[z1]), row=1, col=1)

    fig.add_trace(go.Scatter(x=df[x], y=df[y], text=df[text1] , mode="text"), row=1, col=1)

    fig.add_trace(go.Heatmap(x=df[x], y=df[y], z=df[z2]), row=2, col=1)

    fig.add_trace( go.Scatter(x=df[x], y=df[y],text=df[text2], mode="text"), row=2, col=1)

    # custom colorscale, setting middle value to 1 doesn't work as expected
    val_range = [
        min(df[percentage_cols].values.flatten()),
        1,
        max(df[percentage_cols].values.flatten())
    ]
    val_range = (val_range - min(val_range)) / (max(val_range) - min(val_range))

    fig.update_layout(showlegend=False)

    return fig
```
But this will not look nice if your text is long, or if your heatmap cells are small. You could probably check the length of your df , and if small enough then also plot the scatter plots, otherwise add it on hover

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
