### ISSUE TITLE
Bad URL link in contributing guidelines

### ISSUE THREAD

**Issue by DavidKershaw** [plotly/plotly.py#2319]
In https://github.com/plotly/plotly.py/blob/master/doc/contributing.md
it says
"Want to improve the plotly documentation?
Thank you! Instructions on how to contribute to the documentation are given here. Please also read the next section if you need to setup a development environment."
Clicking on "here" takes you to
https://github.com/plotly/plotly.py/blob/master/doc/contributing.md
404 Page not found - GitHub.

**Comment by nicolaskruchten** [comment]
Thanks for letting us know... fixed!
