### ISSUE TITLE
init_notebook_mode() Incompatible with Colab

### ISSUE THREAD

**Issue by ushuz** [plotly/plotly.py#2320]
Example notebook on Colab:
https://colab.research.google.com/drive/13FfuRlyzqRqmmCII-048ASHIPLsb0jbR

`init_notebook_mode()` set renderers.default to `'plotly_mimetype+notebook'` which is incompatible with Colab. This causes trouble for cufflinks's [offline mode](https://github.com/santosjorge/cufflinks/blob/5df644f91ad8817e85d05cec7d21cfaf9316947b/cufflinks/offline.py#L13-L32).

Workaround: manually override `renderers.default` back to `'colab'`:

```python
import cufflinks as cf
cf.go_offline()
import plotly.io as pio
pio.renderers.default = 'colab'
```

**Comment by nicolaskruchten** [comment]
Yes, this is the recommended approach.
