### ISSUE TITLE
Waterfall plot doesn't always plot the right axis range

### ISSUE THREAD

**Issue by AndreCNF** [plotly/plotly.py#2327]
Depending on the data values, when setting a base (i.e. initial value), the plot doesn't always adjust the axis range accordingly. For instance, where's a plot working as expected:

```
import plotly.graph_objs as go
fig = go.Figure()

fig.add_trace(go.Waterfall(
    y = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'],
    x = [1, 2, 3, -2, -1, 3, -4, 1],
    base = 100,
    orientation='h'
))

fig.show()
```

![image](https://user-images.githubusercontent.com/19359510/77815472-4eb28280-70b3-11ea-8914-e4a71b0c1743.png)

Now here's what happens when I change a single value in the data (in this case, I changed the third value from 3 to 1):

```
import plotly.graph_objs as go
fig = go.Figure()

fig.add_trace(go.Waterfall(
    y = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h'],
    x = [1, 2, 1, -2, -1, 3, -4, 1],
    base = 100,
    orientation='h'
))

fig.show()
```

![image](https://user-images.githubusercontent.com/19359510/77815476-570abd80-70b3-11ea-9f8f-d41d9b1957e7.png)

I'm using plotly 4.5.4 and python 3.7.4 

Can anyone help me understand what I might be doing wrong or fix this issue?

**Comment by emmanuelle** [comment]
Thank you @AndreCNF I opened an issue in plotly.js to report the problem. You can use the axis attribute `range` to set the range explicitly (see https://plotly.com/python/axes/#setting-the-range-of-axes-manually) until it works again. Thanks again!

**Comment by nicolaskruchten** [comment]
Changing the third value to 1 causes the seventh to dip below the base, so the axis resets to include zero, basically. Not a great behaviour, admittedly!

**Comment by emmanuelle** [comment]
In fact it goes to 0 not to negative values so there might be a precision here problem as well?

**Comment by AndreCNF** [comment]
Thank you @emmanuelle and @nicolaskruchten for looking into this issue! I see now that it resets the axis whenever it passes the base value (it happens in both directions, either when going from bigger than the base value to smaller than it, or vice versa). Is it possible to correct this behavior? Because this axis reset can make the data less readable (especially if the base value is much bigger than the relative changes) and, in some cases, the value 0 might not even make sense in the current context.

**Comment by nicolaskruchten** [comment]
I'm sorry I haven't followed up on this issue, but it should be resolved in the most recent version of `plotly` :)

**Comment by AndreCNF** [comment]
@nicolaskruchten Yes, it's resolved. That's why I closed this issue. Thanks for the help! 🙂
