### ISSUE TITLE
PX scatter, bar behaviour when only one of x or y is specified

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.py#2332]
Plotly.js defaults to assuming `x` or `y` are increasing integers if unspecified, but this is a bad fit for PX... consider the following case where coloring the markers results in their shifting position (note the x axis range!)

![image](https://user-images.githubusercontent.com/203523/77869109-5ab15800-720b-11ea-845e-fe0248edb22a.png)

This case is even scarier, with individual bars have different heights based on position in the data frame:

![image](https://user-images.githubusercontent.com/203523/77869167-8b918d00-720b-11ea-8346-abd94fefb176.png)

For `bar`, `line`, `scatter` and `area` we should probably disallow specifying one but not both of `x` and `y`. Possibly in the 3d cases also? Anywhere else? Bar-like traces?

**Comment by nicolaskruchten** [comment]
Note that we can already pass in `df.index` to either of these, if we really do want sequential integers and that's what the index is, and we'll soon be able to pass in `y=px.Constant(1)` for the second example there.

**Comment by emmanuelle** [comment]
Hum here I don't think we should make it more complicated than what is possible to do with `go`. I think users see `px` as a simplification compared to `go` so ideally it should not be more verbose. Having increasing indices as a default for `x` and `y` is a sensible default, which is also shared with other libraries such as matplotlib.
I'm not shocked by the scatter example. The bar one is very weird indeed (and trying to adapt this to a `go` example is even weirder! Don't really understand what is done!).
I think I would rather try to document this behaviour rather than changing it.

**Comment by nicolaskruchten** [comment]
Oh so I'm not proposing to make anything more complicated: I'm saying we should raise an exception if one of the two is `None`.

**Comment by nicolaskruchten** [comment]
(this is what Seaborn does also BTW)

**Comment by emmanuelle** [comment]
well having to pass an additional parameter is more complicated :-). When what you want to do is 
```
px.line(y=[10, 3, 5])
```

**Comment by nicolaskruchten** [comment]
OK, so here is a heuristic we could use which results in reasonable results for scatter/line/area/bar...

* Define a trivial new class `px.Range` such that it stands in for columns as `range(len(df))`
* For scatter-like traces, if only `y` is provided, then `x` should default to `px.Range()` (and vice-versa) ... this would give similar results to what `px.line(y=[10,3,5])` does, except that adding `color=['a',b','a']` wouldn't change the position of any point, which is important IMO.
* For bar-like traces, if only `y` is provided, then `x` should default to `px.Constant(1)` (and vice-versa) ... this is basically what we do right now for box/violin/strip via an `x0`/`y0` hack.

**Comment by nicolaskruchten** [comment]
The `Constant(1)` approach looks like this in various permutations:

![image](https://user-images.githubusercontent.com/203523/78931330-c7321f80-7a73-11ea-863a-dd67e61fb43b.png)

![image](https://user-images.githubusercontent.com/203523/78931345-cef1c400-7a73-11ea-90e2-fef4cd6dbc2e.png)
![image](https://user-images.githubusercontent.com/203523/78931375-df09a380-7a73-11ea-9ee4-f1c63d6ea1be.png)

**Comment by nicolaskruchten** [comment]
This is what `px.Range()` looks like:

![image](https://user-images.githubusercontent.com/203523/78932570-c4d0c500-7a75-11ea-8227-f3669e3d47d5.png)

**Comment by nicolaskruchten** [comment]
OK so I've actually implemented a more complicated option, wherein if the `df` is provided, we use its `index` otherwise `px.Range()` *except* in the `bar` case if the provided column is categorical, then we use `px.Constant(1)`.
