### ISSUE TITLE
PX "wide-form" mode like Seaborn

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.py#2333]
Seaborn has a nice mode whereby in something like `px.line()`, if neither `x` nor `y` are specified (see also #2332!) it treats the data frame as "wide" rather than "long"/"tidy" and sets `x`=index, `y`=melted value and `color`=melted variable. We could do some variation on this as well.

**Comment by nicolaskruchten** [comment]
See also https://github.com/plotly/plotly_express/issues/141, https://github.com/plotly/plotly_express/issues/126, https://github.com/plotly/plotly_express/issues/37

**Comment by emmanuelle** [comment]
Interesting! Indeed switching all the time between wide and tidy is a pain.
