### ISSUE TITLE
Rebrand and clean up Sphinx CSS

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.py#2334]
Two things:
1. We need to rebrand https://plotly.com/python-api-reference/ with the new colors (let's leave the fonts alone for now)
2. We need to tweak the CSS a bit to better-format the markup that comes out of Sphinx

Re the latter, here's what comes to mind:
* reformat `blockquote` so it doesn't look like a quote and doesn't make the text bigger
* reformat `dt`/`dd` so that the terms aren't bold and the definitions are a bit indented
* maybe add a bit of whitespace above/below `li` to make things breathe a bit?

**Comment by nicolaskruchten** [comment]
In terms of how: `cd doc/apidoc && make html` to build it... Hopefully all this stuff is just a set of "overrides" in https://github.com/plotly/plotly.py/blob/master/doc/apidoc/_static/plotly-style.css

**Comment by nicolaskruchten** [comment]
Ah, small and annoying wrinkle: it's hard/impossible to correctly build the entire docs on MacOS due to its case-insensitive filesystem.

Probably best to use the inspector stylesheet or something to do this :(

**Comment by nicolaskruchten** [comment]
While trying to see how easy this inspector-stylesheet approach is to use, I basically ended up implementing most of the points in part 2 here... sorry! https://github.com/plotly/plotly.py/commit/a78442be81dff0c021b7ab125ddcdb5c0f91f71f

**Comment by gvwilson** [comment]
@LiamConnors is this still an open concern?

**Comment by LiamConnors** [comment]
the page looks okay to me. I'm not certain on the reasons for the original issue and what was worked on. Closing it out
