### ISSUE TITLE
Plotly graphs are not showing up anymore in Jupyter notebook when running from command line

### ISSUE THREAD

**Issue by muneebable** [plotly/plotly.py#2339]
I am running a jupyter notebook from command line. 
`jupyter nbconvert --execute --to notebook --inplace <name>
`
MY jupyter version is this :

jupyter core     : 4.5.0
jupyter-notebook : 6.0.1
qtconsole        : 4.5.5
ipython          : 7.8.0
ipykernel        : 5.1.2
jupyter client   : 5.3.1
jupyter lab      : not installed
nbconvert        : 5.6.0
ipywidgets       : 7.5.1
nbformat         : 4.4.0
 
After running when I see the output, it shows me nothing:
![Screenshot from 2020-03-31 16-57-05](https://user-images.githubusercontent.com/3126387/78041287-c6f99c00-7370-11ea-8bc7-73a64acbde9e.png)

This is how i imported libraries. and my **ployly** version is `4.1.1'`

```
# Import the necessaries libraries
import plotly
import plotly.offline as pyo
import plotly.graph_objs as go

from IPython import get_ipython
import IPython.core.display
import termcolor
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from IPython.core.display import display, HTML

%matplotlib inline
display(HTML("<style>.container { width:90% !important; }</style>"))
pyo.init_notebook_mode()
```
I did a little debugging 
![Screenshot from 2020-04-06 14-52-37](https://user-images.githubusercontent.com/3126387/78560507-78d41500-7816-11ea-8218-76bea658900a.png)
The red part is executed within the notebook/or from browser, where as the green part is executed with commandline tool. It can't add the JS if we run from commandline. How can we force it to add JS script ?

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
