### ISSUE TITLE
The node property "width" in line doesn't properly work (Sankey diagram)

### ISSUE THREAD

**Issue by xanderwallace85** [plotly/plotly.py#2343]
Hi there. 
The node property "width" in line doesn't properly work. In the documentation it says that we can specify color and width of the line for each node. However, when setting width = [.2, .5, ...], for example, the width of the line is (probably) set to the default value (.5) for all the nodes.

**Comment by emmanuelle** [comment]
Hi @xanderwallace85 indeed the `width` of a `go.sankey.node.Line` is a scalar parameter, not an array. Usually the documentation says explicitly when it's an array.

**Comment by xanderwallace85** [comment]
Hi @emmanuelle. Thank you for the quick reply!
Maybe in the future it would be interesting to add also the array option? This for sure would help to personalize events. For instance by changing the width (larger values) of the nodes when calling the on_hover function :)

**Comment by Djeez2** [comment]
@emmanuelle : the documentation does explicitly say the width (or color for that matter) can be an array:

> width 
Parent: data[type=sankey].node.line 
Type: number or array of numbers greater than or equal to 0 
Default: 0.5 
Sets the width (in px) of the `line` around each `node`.
