### ISSUE TITLE
setup.py updateplotlyjs does not support repos other than plotly.py

### ISSUE THREAD

**Issue by zouhairm** [plotly/plotly.py#2344]
I have a [PR in plotly.js](https://github.com/plotly/plotly.js/pull/4575) to add a feature for scattermapbox. Unfortunately the PR is taking a while to merge, and I'm looking for a way to use my fork in the meantime.

I've tried following the [instructions](https://github.com/plotly/plotly.py/blob/master/contributing.md#update-to-a-new-version-of-plotlyjs) on how to update to a new plotly.js, but unfortunately the setup script does not allow specifying a version that is not an official plotly release. I've tried posting a [question](https://community.plot.ly/t/how-to-use-own-fork-of-plotly-js-plotly-py/36412) in the community forums, but @nicolaskruchten suggested I post here instead.

I've created a [branch in my plotly.py fork](https://github.com/plotly/plotly.py/compare/master...zouhairm:dev/mbx_symbol) that changes setup.py to support a non-plotly remote#branch. I've tried using this, but I'm not sure it's enough as it's not clear how I tell plotly.py to use that version instead of plotly.js from a CDN ?

I'd love some help on making this possible. Happy to turn my branch into a PR and update the contributing documentation for others in the future.

**Comment by nicolaskruchten** [comment]
So the closest thing we've got to what you're trying to do is the `python setup.py updateplotlyjsdev` command, which reruns code generation based not on a published version of Plotly.js, but one that is sitting in a CircleCI artifact (the one in the latest build of Plotly.js master). You may be able to run down how this works inside `setup.py` to create a variant script that will work given an arbitrary URL to a (built) Plotly.js bundle... Hopefully that's enough of a thread to start pulling on!

**Comment by zouhairm** [comment]
Thanks @nicolaskruchten 
I think that's what I needed and from the looks of it I should be able to get things working this way for now. I'll create a PR to plotly.py to make `updateplotlyjsdev` accept a repo and branch name (other than master).

**Comment by nicolaskruchten** [comment]
Closed with a very neat #2349 :) Thanks again!
