### ISSUE TITLE
Document how to install orca on Google Colab

### ISSUE THREAD

**Issue by emmanuelle** [plotly/plotly.py#2346]
Solution is described in https://stackoverflow.com/questions/57262385/saving-or-downloading-plotly-iplot-images-on-google-colaboratory/57272111#57272111

This should be a section of https://plotly.com/python/static-image-export/.

**Comment by WinstonPais** [comment]
This is my first try in the open source community. I made changes in the .md file. How am i supposed to build the html, the instructions in the README file for documentation was not really clear. Thanks in advance.

**Comment by nicolaskruchten** [comment]
Closed by @WinstonPais in  https://github.com/plotly/plotly.py/pull/2486
