### ISSUE TITLE
animation issue 

### ISSUE THREAD

**Issue by Jacques2101** [plotly/plotly.py#2358]
hi 
I am trying to use Plotly (v 4.6) and everything is working fine except when I tried to reproduce the example from the website with animation : 
import plotly.express as px
df = px.data.gapminder()
fig = px.scatter(df, x="gdpPercap", y="lifeExp", animation_frame="year", animation_group="country",
           size="pop", color="continent", hover_name="country",
           log_x=True, size_max=55, range_x=[100,100000], range_y=[25,90])
fig1 = go.Figure(fig.frames[0].data, fig.layout)
fig1.show()

I get the graph but no animation even I tried to change the date on the bar. Nothing happens. 

I work on vscode 1.43.2 with jupyter module. 

Thanks for your help

**Comment by JTebeka** [comment]
I tried also with python on vscode but still same results...
