### ISSUE TITLE
Manually defining ticks on log plot causes axis label to move off to side

### ISSUE THREAD

**Issue by gregor-taylor** [plotly/plotly.py#2359]
When defining log axes and only wanting major tick indicators, I found on the forums the way to do it is to manually define the ticks. So for example, after plotting something that has a maximum Y-val of 100 we would use:
```
tickvals=[2,3,4,5,6,7,8,9,10,20,30,40,50,60,70,80,90,100]
ticktext=[str(val) if val in [10,100] else '' for val in tickvals]
fig.update_yaxes(type='log', tickvals=tickvals, ticktext=ticktext)
```
Which would set the major tick labels at 10 and 100 but leave everything else blank. This works but the y-axis label then jumps far off to the left, effectively setting a massive title_standoff. This is for online plotting but have also tried saving it using write_image and it's the same. I can move the label by altering title_standoff but I cannot get it to where it would be usually - and indeed the behaviour is somewhat random, sometimes larger values of standoff move the title closer and smaller values make it move further away. I can play around until I get something that is passable but not perfect.

Full working example:
```
import numpy as np
import plotly.graph_objects as go


x_data=np.linspace(1, 100, num=100)
y_data=np.linspace(1, 100, num=100)

fig=go.Figure()
fig.add_trace(go.Scatter(x=x_data, y=y_data, mode='markers', marker_color='rgba(152, 0, 0)'))
fig.update_traces(mode='markers', marker_line_width=1, marker_size=5)
fig.update_layout(yaxis=dict(
	              title_text='Y Data'),
	              #title_standoff = 1),
	              xaxis_title='X Data',
	              font=dict(
                       family="Helvetica",
                       size=18,
                       color="#000000")
	              )
tickvals=[2,3,4,5,6,7,8,9,10,20,30,40,50,60,70,80,90,100]
ticktext=[str(val) if val in [10,100] else '' for val in tickvals]
fig.update_yaxes(type='log', tickvals=tickvals, ticktext=ticktext)


fig.show()
```
The commented out title_standoff can be altered to move the title about and see the random behaviour.

**Comment by emmanuelle** [comment]
Hi @gregor-taylor when I run your code the web console displays a warning "too many automargin redraws". The automargin algorithm seems to have a hard time computing the margin. You can switch off automargin and give your own, like
```
import numpy as np
import plotly.graph_objects as go


x_data=np.linspace(1, 100, num=100)
y_data=np.linspace(1, 100, num=100)

fig=go.Figure()
fig.add_trace(go.Scatter(x=x_data, y=y_data, mode='markers', marker_color='rgba(152, 0, 0)'))
fig.update_traces(mode='markers', marker_line_width=1, marker_size=5)
fig.update_layout(yaxis=dict(
	              title_text='Y Data'),
	              xaxis_title='X Data',
	              font=dict(
                       family="Helvetica",
                       size=18,
                       color="#000000"),
                  margin=dict(t=50, b=50, r=50, l=80),
                 
	              )
tickvals=[2,3,4,5,6,7,8,9,10,20,30,40,50,60,70,80,90,100]
ticktext=[str(val) if val in [10,100] else '' for val in tickvals]
fig.update_yaxes(type='log', 
                 tickvals=tickvals, ticktext=ticktext,
                 automargin=False
                )
fig.update_xaxes(automargin=False)

fig.show()
```
That said, this is probably a slight but on our side.

**Comment by emmanuelle** [comment]
Interestingly the problem disappears when not using any template (`fig.update_layout(template=None)`). I discovered this when trying to reproduce the pb in Javascript, and I couldn't since JS does not use templates.

**Comment by gregor-taylor** [comment]
Yeah seems to be something to do with the templates. Tried a few and the problem persists but as you say if I set `update_layout(template=None)` and then define all of the template features manually in the update_layout method then it works as expected.

**Comment by kvanderwijst** [comment]
This problem happens to be everytime I use a custom ticktext which is an empty string ''. Just a space (' ') doesn't trigger the problem. So not only log plot:

fig = go.Figure()
fig.add_scatter(x=[1,2,3], y=[10,5,7])
fig.update_xaxes(
    tickmode='array',
    tickvals=[1,2,3],
    ticktext=['Tick 1', '', 'Tick 3'] # ['Tick 1', ' ', 'Tick 3'] is fine
)
