### ISSUE TITLE
Unified hovermode not working

### ISSUE THREAD

**Issue by rpanai** [plotly/plotly.py#2361]
I just installed the last version of plotly but [unified-hovermode](https://plotly.com/python/hover-text-and-formatting/#unified-hovermode) is not working for me. I don't get any error but there is not hovermode.

**Comment by nicolaskruchten** [comment]
Can you please provide a bit of code so we can try to replicate what you're seeing?

Also: if you are using JupyterLab, can you confirm that you've got the latest versions of the `jupyterlab-plotly` extension, which is 4.6.0?

**Comment by rpanai** [comment]
> Can you please provide a bit of code so we can try to replicate what you're seeing?
> 
> Also: if you are using JupyterLab, can you confirm that you've got the latest versions of the `jupyterlab-plotly` extension, which is 4.6.0?

I just used the example listed on the link. And I guess the problem is the jupyter-lab extension version. I'll keep you updated.

**Comment by fernandascovino** [comment]
Hey! I'm having a similar problem... The new `hovermode` works perfectly on Jupyter - thanks, by the way, it's beautiful! 

However, when using a `go.Figure` in my Streamlit application, by calling `streamlit.plotly_chart(fig)`, the `x unified` mode gives the same output as `hovermode='x'` 🤔

**Comment by emmanuelle** [comment]
Hi @fernandascovino are you sure Streamlit uses the latest release of plotly here?

**Comment by fernandascovino** [comment]
Not so sure... I'll check this out!

**Comment by fernandascovino** [comment]
@emmanuelle from what I could find they use [`plotly.js > 1.52.2`](https://github.com/streamlit/streamlit/blob/a3d5aad51b8b1df7b0dd3c85553ee867c152577e/frontend/package.json), and `x unified` has been introduced in [`plotly.js==1.53`](https://github.com/plotly/plotly.js/releases)

**Comment by rpanai** [comment]
> Can you please provide a bit of code so we can try to replicate what you're seeing?
> 
> Also: if you are using JupyterLab, can you confirm that you've got the latest versions of the `jupyterlab-plotly` extension, which is 4.6.0?

This fixed it.
