### ISSUE TITLE
How show all data label when I move cursor to the legend?

### ISSUE THREAD

**Issue by slsongge** [plotly/plotly.py#2369]
Hi, Does plotly can achieve this function(When I move the cursor to the legend, the corresponding picture will show all data label)?
Thanks!

https://user-images.githubusercontent.com/19553554/35089953-4865fe2c-fc73-11e7-8c47-e917332d061c.gif

**Comment by emmanuelle** [comment]
Hi @slsongge unfortunately this is not supported in plotly at the moment. A related issue is https://github.com/plotly/plotly.js/issues/65, feel free to add a comment in this issue.

**Comment by slsongge** [comment]
@emmanuelle  Thanks for your reply!
