### ISSUE TITLE
How to remove horizontal white line on stacked bar charts?

### ISSUE THREAD

**Issue by javidsch** [plotly/plotly.py#2373]
It is strange. Not always, but in some cases over stacked bar charts additional horizontal lines.
How remove it? Or what can be reasons?

<img width="1100" alt="Screen Shot 3" src="https://user-images.githubusercontent.com/28500366/79048017-da372200-7c22-11ea-996d-70f19071b3e8.png">

**Comment by emmanuelle** [comment]
Hi @javidsch these lines correspond to the marker lines of the bar trace. You can remove them by setting their width to zero, for example
```
import plotly.graph_objects as go
animals=['giraffes', 'orangutans', 'monkeys']

fig = go.Figure(data=[
    go.Bar(name='SF Zoo', x=animals, y=[20, 14, 23], marker_color='blue'),
    go.Bar(name='LA Zoo', x=animals, y=[12, 18, 29], marker_color='blue')
])
# Change the bar mode
fig.update_layout(barmode='stack')
fig.update_traces(marker_line_width=0)
fig.show()
```
Please note that support questions such as this one should be asked preferably on the community forum https://community.plotly.com/.

**Comment by javidsch** [comment]
Thanks, Emmanuelle!
You are amazing. :)
