### ISSUE TITLE
code not formatted correctly in the dash renderers example

### ISSUE THREAD

**Issue by chriddyp** [plotly/plotly.py#2376]
![image](https://user-images.githubusercontent.com/1280389/79080498-43be3b80-7cca-11ea-9874-fc9bf512add2.png)

**Comment by emmanuelle** [comment]
Addressed in #2374.

**Comment by emmanuelle** [comment]
Hum the fix in #2374 didn't work apparently. @nicolaskruchten @jdamiba when I convert the notebook on my machine using jupytext and nbconvert the code block appears correctly in a `<code>` tag but on https://github.com/plotly/plotly.py-docs/blob/built/2019-07-03-renderers.html it's a simple `<div>` and the formatting is therefore broken. I'm using jupytext 1.3.0, nbconvert 5.4.0

**Comment by nicolaskruchten** [comment]
Let's just remove that section... the automatic "what about Dash?" section at the bottom already covers this.

**Comment by nicolaskruchten** [comment]
Closed by #2381
