### ISSUE TITLE
Quantmod not importing

### ISSUE THREAD

**Issue by arunklama** [plotly/plotly.py#2378]
When I try to import quantmod after installing it, I  get several errors like -

"C:\ProgramData\Anaconda3\lib\site-packages\pandas_datareader\compat\__init__.py:7: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  from pandas.util.testing import assert_frame_equal"

ModuleNotFoundError: No module named 'quantmod.theming'

I've almost tried every solution I got but it never worked. Is there any single  person who has imported quantmod successfully in a jupyter notebook?

**Comment by emmanuelle** [comment]
Hi @arunklama I don't think this problem is related to plotly.py, is it?

**Comment by arunklama** [comment]
> Hi @arunklama I don't think this problem is related to plotly.py, is it?

I'm new to programming. The main reason of not working quantmod is because it suggests to chart_studio instead of plotly because plotly is deprecated kind of error.

**Comment by emmanuelle** [comment]
I think you should report this problem in the quantmod issue tracker https://github.com/joshuaulrich/quantmod

**Comment by arunklama** [comment]
> I think you should report this problem in the quantmod issue tracker https://github.com/joshuaulrich/quantmod

Thank you.
