### ISSUE TITLE
Plotly in Jupyter Notebook has some problems

### ISSUE THREAD

**Issue by nguyenduyminhthong** [plotly/plotly.py#2382]
I cannot change the quartilemethod. 3 chart in this image are same, which means they only show the result of linear method.
![image](https://user-images.githubusercontent.com/54903090/79256004-7d04d000-7eb1-11ea-9ea9-1f65e11069fe.png)

**Comment by nicolaskruchten** [comment]
From your screenshot, you're using VSCode which uses VSCode-Python, which unfortunately doesn't yet ship with a version of Plotly.js that supports custom quartilemethods. If you launch Jupyter directly you'll find that this works :)

**Comment by nguyenduyminhthong** [comment]
> From your screenshot, you're using VSCode which uses VSCode-Python, which unfortunately doesn't yet ship with a version of Plotly.js that supports custom quartilemethods. If you launch Jupyter directly you'll find that this works :)

Thank you so much!!!
