### ISSUE TITLE
Plotly express Scatter: slow to setup with animations

### ISSUE THREAD

**Issue by maartenbreddels** [plotly/plotly.py#2400]
Hi,

I aggregated some data with Vaex, and want to show an animated scatter plot with plotly express. My aggregated dataframe contains 3117 rows (see screenshot), but making the plot takes 11 seconds (on the Python side), which I think is a bit slow.

I've attached a code example below and I've attached the aggregated data, so you don't need to install vaex not download all the data to reproduce it.
[taxi.csv.zip](https://github.com/plotly/plotly.py/files/4510766/taxi.csv.zip)

Is this performance expected, and can I do something to work around it? (maybe without plotly express?)

Regards,

Maarten

```python
import pandas as pd
import plotly.express as px

df = pd.read_csv('taxi.csv')
fig = px.scatter(df,
                 x="trip_distance_mean",
                 y="total_amount_mean",
                 color="pickup_borough_name",
                 size='count',
                 hover_data=['pickup_zone_name'],
                 animation_frame="pickup_month", animation_group='pickup_zone_name',
                 range_x=[0, 8], range_y=[0, 30])
fig.show()
```

![image](https://user-images.githubusercontent.com/1765949/79880714-aad99f80-83f0-11ea-88b1-d5018f70a81f.png)

**Comment by emmanuelle** [comment]
Hi @maartenbreddels great to see you here :-). @jonmmease made very recently some major speed improvements for creating plotly figures (#2368). On plotly master, your code snippet only takes 0.5s to execute. Would you mind checking that you see the same using master? We hope to release in the next two weeks :-).

**Comment by maartenbreddels** [comment]
Hi @emmanuelle! Great, I can confirm it is much faster indeed. Fast enough for us for now.

**Comment by fedario** [comment]
Creating animations with many frames still gets slow quickly even for very simple frames.

Here is an example:

```Python
plot_bmus = px.scatter(
    bmus,
    x="x",
    y="y",
    range_x=(0, img_height),
    range_y=(0, img_width),
    animation_frame=bmus.index,
)
```
Where `bmus` can be treated as a dataframe of random integers for this example.
Here is the head:
```
    x         y
0  980.0  210.0
1  970.0  200.0
2  990.0  210.0
3  970.0  220.0
4  990.0  220.0

```

And here a plot showing the time taken to generate the plot for different numbers of rows in the dataframe:
![benchmark](https://user-images.githubusercontent.com/24253179/92004367-708af200-ed42-11ea-99f9-8c9520a7de67.png)
