### ISSUE TITLE
accept int for rows and cols in `fig.add_traces`

### ISSUE THREAD

**Issue by emmanuelle** [plotly/plotly.py#2410]
At the moment if you want to add several traces to the same subplot you have to pass an iterable to the `rows` and `cols` arguments of `fig.add_traces`. 
```
import plotly.express as px
df = px.data.tips()
fig = px.scatter(df, x='total_bill', y='tip', color='day')
from plotly.subplots import make_subplots
fig2 = make_subplots(1, 2)
fig2.add_traces(fig.data, rows=[1,]*len(fig.data), cols=[1,]*len(fig.data))
fig2.show()
```
We could also accept an int here, in which case all traces would be added to the same subplot.

**Comment by nicolaskruchten** [comment]
Did you close this because it's working now or because you no longer think this is a good idea?

**Comment by emmanuelle** [comment]
Because it was fixed by #2451 (sorry for being lazy here!)

**Comment by nicolaskruchten** [comment]
Ah ok, thanks for following up :) should #2391 be closed now then?

**Comment by nicolaskruchten** [comment]
@MCBoarder289 if you're interested, solving this issue might involve the same area of the code you were just in :)

**Comment by MCBoarder289** [comment]
@nicolaskruchten Thanks! I'll take a look and see what I can do here

**Comment by nicolaskruchten** [comment]
Awesome! Please don't feel any pressure to work on it or anything, I was just flagging it in case you were looking for a (possibly easy) entry-point into another PR here :)
