### ISSUE TITLE
px.scatter sharex=False

### ISSUE THREAD

**Issue by d6tdev** [plotly/plotly.py#2412]
I'm not seeing an option to disable sharing of x-axis in facetgrid plots as is available in seaborn.

    import plotly.express as px
    df = px.data.tips()
    px.scatter(df, x="total_bill", y="tip", facet_col="day") # shares x
    px.scatter(df, x="total_bill", y="tip", facet_col="day", sharex=False) # fails
    import seaborn as sns
    sns.lmplot(x="total_bill", y="tip", col="day", data=df, sharex=False) # works

Only related issue I see is https://github.com/plotly/plotly.py/issues/1209

**Comment by nicolaskruchten** [comment]
The docs here have en example of how to do this: https://plotly.com/python/facet-plots/

**Comment by d6tdev** [comment]
Thanks. So the recipe is

    import plotly.express as px
    df = px.data.tips()
    g = px.scatter(df, x="total_bill", y="tip", facet_col="day")
    g.update_xaxes(matches=None)
