### ISSUE TITLE
Multiple Executions Removed Embedded Plotly Javascript

### ISSUE THREAD

**Issue by jhamet93** [plotly/plotly.py#2414]
I found that when displaying a Plotly graph in JupyterLab, the embedded Plotly JS library gets removed on second execution of displaying the graph.

Plotly Version: 4.6.0
Running on JupyterLab: 1.2.6

```
from plotly.io import renderers
renderers.default
```

The output of the above is desired: **plotly_mimetype+notebook**. I want the graph to be visible in JupyterLab as well as visible when the notebook is converted to HTML to be hosted in an offline environment for sharing.

```
import plotly.graph_objects as go
fig = go.Figure(data=go.Bar(y=[2, 3, 1]))
fig.show()
```

On first execution, the cell will have two output elements. The first element will contain the embedded Plotly JS library. This is desired for when the notebook is displayed externally in HTML via `nbconvert`. 

However, if I execute the cell again, the embedded Plotly JS library is removed. When the notebook gets displayed externally now, the Plotly JS library is no longer embedded and the graphs will not render.

After further investigation, I found it is due to this chunk of code: https://github.com/plotly/plotly.py/blob/master/packages/python/plotly/plotly/io/_renderers.py#L188-L192. 
On first execution, the `NotebookRenderer` gets activated which is responsible for producing the embedded Plotly JS library. On second execution, the renderer has already been activated thus this code path is not executed and the embedded Plotly JS library from the previous execution gets overwritten.

Is this expected ? More than happy to produce a pull request to resolve this if not. The current workaround for our users is to manually specify the renders when attempting to display a figure which forces the `activate` method to be called every execution (e.g. `fig.show(renderers="plotly_mimetype+notebook")`)

**Comment by emmanuelle** [comment]
Hi @jhamet93 thanks for the report. This appears to be a bug indeed and I can reproduce the problem. @jonmmease @nicolaskruchten to reproduce the problem, create a notebook with a single cell with 
```
import plotly.graph_objects as go
fig = go.Figure(data=go.Bar(y=[2, 3, 1]))
fig.show()
```
execute the cell, export as html (this first html file look fine). Then execute the cell again and save another html file. This time the figure is blank. Probably this is now a wanted behaviour?

**Comment by jhamet93** [comment]
I'm guessing this was done as an optimization to not include the embedded Plotly.js library in every cell trying to render a figure.

I created a patch for our own hosted distribution of this package to embed the library in every cell trying to render a figure (to solve the issue noted above), but this now results in very large notebooks. One notebook example had 8 charts and equated to roughly 50 MB notebook size.

**Comment by jonmmease** [comment]
Yeah, for the default `notebook` renderer, we only load the plotly.js bundle into the notebook the first time it is used.  If it's a useful option to have, this is something that could be implemented as a custom renderer (whether inside or outside the plotly.py codebase).

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
