### ISSUE TITLE
create_gantt() index_col legend not ordering correctly

### ISSUE THREAD

**Issue by FTHuld** [plotly/plotly.py#2417]
I'm having an issue with the legend ordering with create_gantt(). Essentially, the legend is not ordered in any way that I can understand. The third item in index_col (i.e. `Workpackage='Work package C'` in the example below) is moved to the end of the legend. Changing the order of items in the dict does not change the order of the legend, but removing 'Work package C' moves 'Work package D' to last place.

In summary, the third item in index_col is listed last in the legend, except sometimes when it isn't.
Is it something to do with the amount of time each Workpackage is taking? I'd like the legend to be displayed in order of appearance in the dict.

See the example code below:

```
import plotly.figure_factory as ff

df = [dict(Task="A1", Start='2019-07-01', Finish='2019-08-31', Workpackage='Work package A'),
      dict(Task="A2", Start='2019-09-01', Finish='2019-11-30', Workpackage='Work package A'),      
      dict(Task="B1", Start='2019-12-01', Finish='2020-03-31', Workpackage='Work package B'),
      dict(Task="B2", Start='2020-04-01', Finish='2020-07-31', Workpackage='Work package B'),
      dict(Task="B3", Start='2020-04-01', Finish='2020-11-30', Workpackage='Work package B'),    
      dict(Task="C1", Start='2020-05-01', Finish='2020-10-31', Workpackage='Work package C'),
      dict(Task="C2", Start='2020-11-01', Finish='2021-02-28', Workpackage='Work package C'),
      dict(Task="C3", Start='2020-11-01', Finish='2021-04-30', Workpackage='Work package C'),
      dict(Task="D1", Start='2021-01-01', Finish='2021-06-30', Workpackage='Work package D'),
      dict(Task="D2", Start='2021-07-01', Finish='2021-11-30', Workpackage='Work package D'),
      dict(Task="D3", Start='2021-07-01', Finish='2021-12-31', Workpackage='Work package D'),      
      dict(Task="E1", Start='2019-07-01', Finish='2019-09-30', Workpackage='Work package E'),
      dict(Task="E2", Start='2020-02-01', Finish='2020-04-30', Workpackage='Work package E'),
      dict(Task="E3", Start='2020-02-01', Finish='2020-04-30', Workpackage='Work package E'),
      dict(Task="E4", Start='2020-09-01', Finish='2020-12-31', Workpackage='Work package E'),
      dict(Task="E5", Start='2020-11-01', Finish='2021-01-31', Workpackage='Work package E'),
      dict(Task="E6", Start='2020-11-01', Finish='2021-04-30', Workpackage='Work package E'),
      dict(Task="F1", Start='2021-05-01', Finish='2022-04-30', Workpackage='Work package F'),
      dict(Task="F2", Start='2022-05-01', Finish='2022-06-30', Workpackage='Work package F'),
     ]

fig = ff.create_gantt(df, index_col='Workpackage', group_tasks=True, show_colorbar=True)
fig.update_layout(plot_bgcolor='white')
fig.layout.legend={'traceorder':'reversed'}

fig.show()
```

**Comment by YuehLinChung** [comment]
I do have this question, too.
Then I found out:
The order depend on the **colors** parameter passed in **create_gantt()**.
In my case, I passed a list of color with **'rgb(x, y, z)'** format.
And this list of colors will become a *str- type* ***key*** in a *dict-type* variable named ***scatter_data_dict*** inside their plotting function, **gantt_colorscale()**, in **site-packages/plotly/figure_factory/_gantt.py**.
And then affect variable name ***data*** after all.
You can find out that the keys are sorted as a string in ascending according to their ASCII in the image attached below.
If you're using **Spyder IDE**, you can use Debug to trace the progress and find way to solve this problem.

![scatter_data_dict](https://user-images.githubusercontent.com/43700502/86896779-194d1480-c139-11ea-84b1-578c6812c996.png)

**Comment by nicolaskruchten** [comment]
As of the recent version 4.9 release we recommend using `px.timeline()` as a replacement for `ff.create_gantt()`, and it allows better control over ordering: https://plotly.com/python/gantt/

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
