### ISSUE TITLE
Pluggable trendlines

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.py#2418]
To address issues like https://github.com/plotly/plotly.py/pull/1763 and https://github.com/plotly/plotly_express/issues/31 I think we should generalize the PX `trendline` kwarg to:

1. Look strings up in a registry of known trendline functions, like renderers and templates do, so that we can keep `"ols"` and `"trendline"` but also allow people to add their own.
2. Also accept functions if people don't want to have to register them to use them.
3. Probably add `trendline_args` as a set of arguments people can pass to parameterize their trendlines.

If we stick with allowing this mostly on scatter plots and returning new scatter traces then this is pretty easy... we might want to allow this on bar charts (sometimes people ask) or maybe go big and allow it for all charts, in which case "trendline" is the wrong name. I'm thinking here of allowing, say, KDE on histograms, or moving averages on bars.

Either way, the basic idea is that for each trace we normally add in the figure, we add another one by calling this trendline function, so people could do stuff like confidence intervals, error bands, different kinds of regressions, non-linear fits, parameterized LOWESS etc etc.

One additional thing to think about is how this relates to the idea of generating a trendline for the whole dataset or per facet instead of per trace: sometimes people want to do basically one trendline for the whole dataset, but then break it out by color. This would mean we would need to do some extra grouping. Something similar comes up when we think about doing marginal plots when using facet_row and facet_col: we would need to reaggregate differently there too.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
