### ISSUE TITLE
Sets the opacity width in The figure_factory create_gantt method 

### ISSUE THREAD

**Issue by strawberryLoU** [plotly/plotly.py#2420]
I am using figure_factory create_gantt method. I am wondering if I can set the opacity value show the overlaps in between each tasks. 
By reading the help document, I am not aware of a way to doing so.
I'm new to python, and I tried to change the opacity value in _gantt.py soure code  but it did not work for me.
Can anyone tell me if set opacity in create_gantt is feasible at the moment? 
Many thanks.

**Comment by emmanuelle** [comment]
Hi @strawberryLoU , the `create_gantt` figure factory creates a plotly figure object with several traces, which you can modify using `fig.update_traces`, for example
```
import plotly.figure_factory as ff

df = [dict(Task="Job A", Start='2009-01-01', Finish='2009-02-28'),
      dict(Task="Job B", Start='2009-03-05', Finish='2009-04-15'),
      dict(Task="Job C", Start='2009-02-20', Finish='2009-05-30')]

fig = ff.create_gantt(df)
fig.update_traces(opacity=0.5, selector={'fill':'toself'})
fig.show()
```
(here I used a selector to select only the filled parts of the Gantt chart but maybe you don't need to use a selector). You can read the tutorial https://plotly.com/python/creating-and-updating-figures/ for a better understanding of how to update plotly figures.
I hope this will solve your problem. Please note that support requests (as opposed to bug reports or feature requests) should preferably be asked on the community forum https://community.plotly.com/ so maybe see you on the forum another time ;-).

**Comment by strawberryLoU** [comment]
Hi @emmanuelle  thanks a lot, that's very kind of you 
I will post support requests to community forum next time.
