### ISSUE TITLE
Using new Rangebreaks drops the candlestick box.

### ISSUE THREAD

**Issue by jvschoen** [plotly/plotly.py#2426]
I noticed last month that the rangebreaks were added to plotly: 
https://github.com/plotly/plotly.js/issues/1382

When using rangebreaks the candlesticks lose there open/close box, and whiskers are left.

## get data using financialmodelingprep api
```
symbol='ROKU'
url_30m = f"https://financialmodelingprep.com/api/v3/historical-chart/30min/{symbol}?from=2020-01-12&to=2020-04-30"
roku_response = requests.get(url_30m).json()
roku_30m = pd.DataFrame(roku_response)
```
## Make figure without the range breaks
```
df_ = roku_30m
fig = go.Figure(data=[go.Candlestick(x=df_['date'],
                    open=df_['open'],
                    high=df_['high'],
                    low=df_['low'],
                    close=df_['close'])])
    

fig.show()
```
![image](https://user-images.githubusercontent.com/35496082/80775411-863aa180-8b2d-11ea-9f50-c02790b01eb2.png)

## Adding rangebreaks
```
fig.update_xaxes(
    rangebreaks=[
        dict(bounds=["sat", "mon"]), #hide weekends
        dict(values=["2015-12-25", "2016-01-01"]),  # hide Christmas and New Year's
        dict(pattern="hour", bounds=[16, 9.5]),
    ]
)
fig.show()
```
![image](https://user-images.githubusercontent.com/35496082/80775320-4d9ac800-8b2d-11ea-98da-01c6f704a4f4.png)

## Removing the `hour` pattern
```
fig.update_xaxes(
    rangebreaks=[
        dict(bounds=["sat", "mon"]), #hide weekends
        dict(values=["2015-12-25", "2016-01-01"]),  # hide Christmas and New Year's
    ]
)
fig.show()
```
![image](https://user-images.githubusercontent.com/35496082/80775805-b5054780-8b2e-11ea-85ea-21996e0a2da4.png)

It looks like there may be a bug in the hour pattern

**Comment by emmanuelle** [comment]
Thank you for the report @jvschoen, there is an open issue in plotly.js to fix this problem https://github.com/plotly/plotly.js/issues/4795

**Comment by nicolaskruchten** [comment]
I believe this was resolved upstream
