### ISSUE TITLE
RuntimeError in the plotly express scatter function

### ISSUE THREAD

**Issue by ItsWajdy** [plotly/plotly.py#2432]
I am submitting this issue because I couldn't find any answers anywhere.
I was trying to customize the hover info in my scatter plot following code examples from [this post](https://github.com/plotly/plotly.py/blob/master/doc/python/hover-text-and-formatting.md), specifically the code example under the title "Disabling or customizing hover of columns in plotly express". I passed a dictionary as an argument to hover_data but got a RuntimeError.

I should say that the scatter plot that I want differs from the one in the code example in the fact that it has animation. I don't know if this information is helpful in any way.

Using
```
Python 3.6.9
Plotly==4.6.0
```

This is the code causing the error
```
figure = px.scatter(data, x='x', y='y', hover_data={'x': False,
                                                        'y': False,
                                                        'City': True,
                                                        'Balance': ':,',
                                                        'InAmt': ':,',
                                                        'OutAmt': ':,'},
                                                animation_frame='Date',
                                                category_orders={'Date': date_group},
                                                hover_name='City',
                                                text='City',
                                                color='Balance',
                                                size=[100 for i in range(data.shape[0])])
```

And here is the full error text

```
Traceback (most recent call last):
  File "/tf/tensorflow/app.py", line 955, in update_output
    return network_graph(clickData, value, city_dropdown, city_exclude_dropdown, dropdown, connections_to_draw, connections_slider, factor_in_self_loops == ['y'], coloring_criteria, data_space, balance_slider)
  File "/tf/tensorflow/app.py", line 574, in network_graph
    figure = construct_bubble_chart(balanceSlider)
  File "/tf/tensorflow/app.py", line 542, in construct_bubble_chart
    'OutAmt': ':,'}, animation_frame='Date', category_orders={'Date': date_group}, hover_name='City', text='City', color='Balance', size=[100 for i in range(data.shape[0])])
  File "/usr/local/lib/python3.6/dist-packages/plotly/express/_chart_types.py", line 55, in scatter
    return make_figure(args=locals(), constructor=go.Scatter)
  File "/usr/local/lib/python3.6/dist-packages/plotly/express/_core.py", line 1368, in make_figure
    args, constructor, trace_patch
  File "/usr/local/lib/python3.6/dist-packages/plotly/express/_core.py", line 1211, in infer_config
    args = build_dataframe(args, all_attrables, array_attrables)
  File "/usr/local/lib/python3.6/dist-packages/plotly/express/_core.py", line 942, in build_dataframe
    for i, (argument, field) in enumerate(zip(argument_list, field_list)):
RuntimeError: dictionary changed size during iteration
```

What I am really trying to do is hide some information from the hover text, like the X and Y coordinates and the size of the marks. And I am trying to format some values in 'data' to be more readable.

Is there something obvious I'm missing?

**Comment by emmanuelle** [comment]
Hi @ItsWajdy this doc example is for the development version of plotly.py (you found it on Github, it is not deployed in the online doc), since it uses an unreleased feature of plotly. It will be included in the next release, which should be this week, or alternatively you can install the development version following the procedure described in https://github.com/plotly/plotly.py/blob/master/contributing.md

**Comment by ItsWajdy** [comment]
Oh sorry, I guess I didn't check to see if it was on the online docs.
Thank you for your help :)
