### ISSUE TITLE
Callback errors with plotly 4.7.0

### ISSUE THREAD

**Issue by christopherjeon** [plotly/plotly.py#2448]
I have been working on an application that utilizes DDK and a Mapbox token. Yesterday, I suddenly received a callback error that traces back to a function which generates a choropleth map object with Plotly Express - this error prevented the maps from loading. At the end of the error message was: 

> TypeError: unhashable type: 'Template'

Explicitly installing `plotly==4.6.0` in my requirements removed the callback error and I was able to reproduce this error again once I switched back to `plotly==4.7.0`

This was also experienced by @xhlulu, where he experienced the same error with a callback that updates a ddk.Graph component with a px.bar object.

**Comment by nicolaskruchten** [comment]
Fixed in 4.7.1
