### ISSUE TITLE
px.box(...).to_html() should generate the minimum amount of data necessary

### ISSUE THREAD

**Issue by tomzx** [plotly/plotly.py#2456]
If I have a million points and run `px.box(dataframe_with_1_million_rows, x="property-a", y="property-b", points=False).to_html()`, the resulting HTML contains all the `dataframe_with_1_million_rows` serialized, which is huge and seems unnecessary when all I'm displaying are the 5 metrics used by the boxplot.

Instead, I would expect that the necessary metrics (min, max, median, q1/q3) would be calculated and serialized for the javascript to consume.

Why? I want to have as little data as possible in the generated HTML. Those are consumed as static reports. Storing and loading 500 MB HTML files is quite slow, the plot displayed is laggy and it provides a bad user experience.

Is there a reason all this data needs to be available to javascript if all I'm displaying is a box plot and none of the actual points?

**Comment by emmanuelle** [comment]
Hi @tomzx the computation of the quantiles is done in Javascript this is why you have to pass the whole data to the browser. That said, you can precompute the quantiles in Python using the different methods of scipy.stats (scoreatpercentile, iqr, etc) and then pass them to `go.Box` as in [this documentation example](https://plotly.com/python/box-plots/#box-plot-with-precomputed-quartiles). You can also pass to `go.Box` a subsampling of your data points, or no points as all as below
```
import plotly.graph_objects as go

fig = go.Figure()

fig.add_trace(go.Box(y=[
        [None],
        [None],
        [None]
      ], name="Precompiled Quartiles"))

fig.update_traces(q1=[ 1, 2, 3 ], median=[ 4, 5, 6 ],
                  q3=[ 7, 8, 9 ], lowerfence=[-1, 0, 1],
                  upperfence=[5, 6, 7], mean=[ 2.2, 2.8, 3.2 ],
                  sd=[ 0.2, 0.4, 0.6 ], notchspan=[ 0.2, 0.4, 0.6 ] )

fig.show()
```

**Comment by tomzx** [comment]
Hello @emmanuelle!

I was aware of this example. I was wondering if there were any plans to make the `px.box(...)` method smarter to make it easier for the user to get the same result without computing those values themselves.

**Comment by nicolaskruchten** [comment]
We have discussed the idea of a “server side” mode for aggregation-type functions like histogram and box but we haven’t scheduled any of this work just yet.

**Comment by maximilianreimer** [comment]
Hello, 
thanks for the great library. However, I also vote plus one for working on that! I have a box plot that is over 50 MB which is completely unnecessary.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Alternatively, if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
