### ISSUE TITLE
Apparent regression in y-label positioning

### ISSUE THREAD

**Issue by jjnurminen** [plotly/plotly.py#2470]
I'm doing plots with multiple subplots and noticed the following. On Plotly 4.1.1, I get reasonable y-label positioning:

![image](https://user-images.githubusercontent.com/8491321/81950453-9dd55800-960c-11ea-849d-a91485b88fe7.png)

However at least with 4.3.0 and newer, the y labels start to overlap the adjacent plots quite a lot:

![image](https://user-images.githubusercontent.com/8491321/81950582-c78e7f00-960c-11ea-8180-6fc9ac15db25.png)

**Comment by nicolaskruchten** [comment]
These are really beautiful plots! :)

The change is likely related to the new `yaxis.title.standoff` attribute which was added. You should be able to set that value to 0 or `None` to get back the old behaviour. Sorry for the breakage!

**Comment by jjnurminen** [comment]
Indeed fixed by `standoff: 0`. Thanks for the quick response @nicolaskruchten
