### ISSUE TITLE
subplot2grid equivalent on plotly

### ISSUE THREAD

**Issue by cdhainaut** [plotly/plotly.py#2479]
Hello
I am used to matplotlib in python but i'd like to switch to plotly for some reasons.
I really like to use subplot2grid tools in matplotlib, and I dont really like the way I need to  use make_subplots inside plotly...
Actually, what I am using is a dictionnary where I have all my subplots parameters:

```
    plotParameters = {
	"title":"My subplots",
	"size":(2,2),
	"subplots":{
		"Subplot 1":{
			"position":(1,1),
			"rowspan":1,
			"colspan":1,
			"x":"x_column_1",
			"y":"y_column_1",
			"xLabel":"xlabel1",
			"yLabel":"ylabel1"
		},
		"Subplot 2":{
			"position":(1,2),
			"rowspan":1,
			"colspan":1,
			"x":"x_column_2",
			"y":"y_column_2",
			"xLabel":"xlabel2",
			"yLabel":"ylabel2"
		},
		"Subplot 3":{
			"position":(1,3),
			"rowspan":1,
			"colspan":1,
			"x":"x_column_3",
			"y":"y_column_3",
			"xLabel":"xlabel3",
			"yLabel":"ylabel3"
		},
		"Subplot 4":{
			"position":(2,1),
			"rowspan":1,
			"colspan":1,
			"x":"x_column_4",
			"y":"y_column_4",
			"xLabel":"xlabel4",
			"yLabel":"ylabel4"
		},

	}
}
```

```
    def plot(x,y,xLabel,yLabel,ax):
        // dummy function i use to  plot data
    for key,value in plotParameters["subplots"].items():
        axes[key] = plt.subplot2grid(plotParameters["size"], value["position"], rowspan=value["rowspan"], colspan=value["colspan"])
    	plot(value["x"],value["y"],value["xLabel"],value["yLabel"],axes[key])
```

This allows me or another user of the code to customize the plot he is doing using external json file for example. Without having to change the source of the code.

Any idea of something easy and equivalent with plotly?

Many thanks
Cheers

**Comment by nicolaskruchten** [comment]
This looks a lot like make_subplots to me... what do you see as the key differences?

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
