### ISSUE TITLE
Plotting multiple data with Plotly Express

### ISSUE THREAD

**Issue by AStubbusch** [plotly/plotly.py#2487]
A general question to Plotly Express:
Is it in any way possible to plot e.g. 3d-lines based on data frame A, add 3d-dots based on data frame B, and also add an animation based on all displayed data?

In previous issues I only saw '.update_traces(mode="lines+markers")' as option, but this does not allow to add data from a different data frame.

If Plotly Express in not capable of this, would Plotly be? (with commands like fig.add_trace()?)

**Comment by nicolaskruchten** [comment]
You can create an animated figure with `fig = px.line()` and then add scatter traces to each frame of the animation, yes.

**Comment by AStubbusch** [comment]
Thanks a lot for your quick reply, that sounds like a great suggestion.


However, I fail to obtain an animated plot with fig = px.line_3d(). This command returns an empty graph:

```
import plotly.express as px
df = px.data.iris()
df['time'] = range(0, len(df['petal_length']), 1)
fig = px.line_3d(df,
                 x="sepal_width", y="sepal_length", z="time",
                 color="species",
                 animation_frame="time",
                 animation_group="species", 
                 )
fig.show()
```
Are animations not possible with px.line_3d() like this?


Also, I could add an additional scatter trace to the plot in the Plotly format:
```
import plotly.graph_objects as go
fig2= fig.add_trace(go.Scatter3d(x = [4,2,1], y=[4,2,1], z=[1,60,100],
                                 mode='markers'
                                 ))
fig2.show()
```
But is it also possible to add a trace in the Plotly Express format and how can you connect it to the previous animation?


Many thanks for your help!!

**Comment by AStubbusch** [comment]
Were you able to see why the animation is not working in a 3d graph?

And could you hint me at a function that allows to add new data to a Plotly express 3d plot, if there is any? I saw that otherwise Plotly can do the trick.

Really looking forward to a reply, many thanks for your insights!
