### ISSUE TITLE
Interactive bar chart doesn't show all the bars.

### ISSUE THREAD

**Issue by Thanasisleo** [plotly/plotly.py#2497]
Hi,

I have the following dataframe and I am trying to create an interactive bar chart with plotly.express:

[![enter image description here][1]][1]

    import pandas as pd
    import plotly.express as px
    
    data = {
            'Profile': ['PK', 'OP', 'PK', 'OP', 'PK', 'OP', 'PK', 'OP'],
            'Date': ['2020-01-01', '2020-01-01', '2020-01-02', '2020-01-02', '2020-01-01', '2020-01-01', '2020-01-02', '2020-01-02'],
            'Month': ['Jan-20','Jan-20','Jan-20','Jan-20','Feb-20','Feb-20','Feb-20','Feb-20'],
            'Value': [10, 20, 60, 70, 30, 60, 55,89]
        }
    
    df = pd.DataFrame(data=data, columns=['Profile','Date', 'Month', 'Value'])
    
    fig = px.bar(data_frame=df, x='Month', y='Value', animation_frame='Date', animation_group='Profile')

    fig.show()

Even though the chart appears, only the first bar has color, the rest are transparent.

[![enter image description here][2]][2]

Plotly version is 4.7.1

  [1]: https://i.stack.imgur.com/bWGm4.png
  [2]: https://i.stack.imgur.com/zl4kB.png

**Comment by 10ego** [comment]
First thing I noticed is your animation frame being between 2020-01-01 ~ 2020-01-02.
Looks like when you declare animation_frame = 'Date', it's recognizing this as only 2 timeframes.

For example, adding in random 8 frames will work if you try this with numpy.
<pre>
fig = px.bar(data_frame=df, x='Month', y='Value', animation_frame=np.arange(8), animation_group='Profile')
</pre>

If animation is important to you, it might be important to declare more distinguishable timeframes.

**Comment by Thanasisleo** [comment]
> First thing I noticed is your animation frame being between 2020-01-01 ~ 2020-01-02.
> Looks like when you declare animation_frame = 'Date', it's recognizing this as only 2 timeframes.
> 
> For example, adding in random 8 frames will work if you try this with numpy.
> 
> fig = px.bar(data_frame=df, x='Month', y='Value', animation_frame=np.arange(8), animation_group='Profile')
> If animation is important to you, you can bypass this issue by declaring more distinguishable timeframes or just using the above solution (your X-axis legend will change to display the correct month value so it might be the simplest solution).

Hi, 

the range of the Date column is just a sample. In reality, it will have from 2 to 200 different dates.
And in general, the x-axis will have from 1 to 12 months. I only added 2 months in this example, just to demonstrate the issue.

Still, even if I have three dates, the bar for Feb-20 is invisible.

```
data = {
        'Profile': ['PK', 'OP', 'PK', 'OP', 'PK', 'OP', 'PK', 'OP', 'PK', 'OP', 'PK', 'OP'],
        'Date': ['2020-01-01', '2020-01-01', '2020-01-02', '2020-01-02', '2020-01-03', '2020-01-03', '2020-01-01', '2020-01-01', '2020-01-02', '2020-01-02', '2020-01-03', '2020-01-03',],
        'Month': ['Jan-20','Jan-20','Jan-20','Jan-20','Jan-20','Jan-20', 'Feb-20','Feb-20','Feb-20','Feb-20', 'Feb-20','Feb-20'],
        'Value': [10, 20, 60, 70, 30, 60, 55, 89, 31, 45, 86, 23]
    }
```

**Comment by 10ego** [comment]
> when you declare animation_frame = 'Date', it's recognizing this as only 2 timeframes.

This is the reason why you are encountering the issue.

> 'Date': ['2020-01-01', '2020-01-01', '2020-01-02', '2020-01-02', '2020-01-03', '2020-01-03', '2020-01-01', '2020-01-01', '2020-01-02', '2020-01-02', '2020-01-03', '2020-01-03',],

Effectively, this change still has the same problem. You only have 3 timeframes ranging between Jan 1~ Jan 3.  Of course that means you only progress through 3 `frames` of data and terminate before it reaches your Feb 20 data.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
