### ISSUE TITLE
Bar position drifting when multi bars are displayed in time series.

### ISSUE THREAD

**Issue by himmel22** [plotly/plotly.py#2500]
Plotly Version 4.7.1

1. When multi bars are displayed:
<img width="1126" alt="QQ20200526-111811@2x" src="https://user-images.githubusercontent.com/448649/82857546-e1e92680-9f43-11ea-9196-26be02be6ab7.png">

2. When hovering on a value, you can see the timestamp of the data in 17:25, and the dot line shows the correct position, but the color line is in a wrong position after 18:00
<img width="1138" alt="QQ20200526-111855@2x" src="https://user-images.githubusercontent.com/448649/82857559-ed3c5200-9f43-11ea-9f97-637048369c77.png">

3. When I toggle off all other bars, the position of the only bar remained changed to the right position and  overlapping with the hover dot line.
<img width="1134" alt="QQ20200526-111914@2x" src="https://user-images.githubusercontent.com/448649/82857562-f0cfd900-9f43-11ea-99c0-415303149e97.png">
<img width="1136" alt="QQ20200526-111942@2x" src="https://user-images.githubusercontent.com/448649/82857570-f2999c80-9f43-11ea-9c71-f968748f478a.png">

Here is the code snippet:

```python
fig.add_trace(
    go.Bar(
        x=df_HTM.index,
        y=df_HTM['HTM_label'] * 1800,
        width=1,
        marker_color=COLOR_VALUE1,
        marker_line_width=1,
        marker_line_color=COLOR_VALUE1,
        name='HTM'))

fig.add_trace(
    go.Bar(
        x=df_OSE.index,
        y=df_OSE['contextOSE_label'] * 1800,
        width=1,
        marker_color=COLOR_VALUE2,
        marker_line_width=1,
        marker_line_color=COLOR_VALUE2,
        name='contextOSE'))

fig.update_layout(
    template='none',  
    hovermode='x unified', 
    bargap=0,
    xaxis_range=['2019-01-01', '2020-01-01']
)
```

**Comment by Kyle-Hsu** [comment]
I see similar issue with fig.add_bar:

Not sure why the y position has a slope when using the same y position coordinate
```
for i in range(0,10):
    fig.add_bar(x=[1], y=[1], width=[1], base=[i], textposition='auto', orientation='h', name="test")
```
![Screen Shot 2020-06-05 at 8 46 45 PM](https://user-images.githubusercontent.com/19542994/83935370-d8469680-a76d-11ea-9622-83dcf0299b8a.png)

**Comment by nicolaskruchten** [comment]
@Kyle-Hsu in this case this is the intended behaviour when `layout.barmode` is set to `group`, which is the default. If you're trying to set all bar parameters like this i.e. `x`, `y`, `width` and `base`, I would recommend setting `layout.barmode` to `overlay`.

![image](https://user-images.githubusercontent.com/203523/83945275-a8cc7400-a7d7-11ea-82fb-0312882ac416.png)

**Comment by nicolaskruchten** [comment]
With respect to @himmel22 's original question, without access to the actual data it's hard to replicate this behaviour... @alexcjohnson do you have any intuition here?

**Comment by nicolaskruchten** [comment]
@himmel22 in `df_OSE.index` is there in fact a value at `2019-06-29 17:25`? It could be that there is a bar there indeed but it's too narrow/faint to be shown?

**Comment by Kyle-Hsu** [comment]
@nicolaskruchten thank you so much for the tip, the overlay parameter was what I was missing! 👍

**Comment by himmel22** [comment]
Thank you for your replies!
I found the cause of the problem: The `barmode` property is set to `group` by default, so when two bar traces have overlaps in some points, every point's position will be slightly changed even in non-overlap point.
When I set `barmode` to `overlay`, the drifting are gone.
