### ISSUE TITLE
Cannot show the figure in jupyterlab

### ISSUE THREAD

**Issue by charlesdong1991** [plotly/plotly.py#2505]
Somehow, I am not able to show the figure in jupyterlab anymore, all i get is blank iplot

```python
import plotly.graph_objects as go
fig = go.Figure()
fig.add_trace(go.Scatter(y=[2, 1, 4, 3]))
fig.add_trace(go.Bar(y=[1, 4, 3, 2]))
fig.update_layout(title = 'Hello Figure')
fig.show()
```

I also noticed a previous PR, and follow the steps in https://plotly.com/python/troubleshooting/, but still not able to see plot.

Dependencies:
```
plotly==4.8.0
jupyterlab==2.1.3
ipywidgets==7.5.0
```

**Comment by nicolaskruchten** [comment]
What does `jupyter labextension list` return? This is a common symptom of having mismatched versions of the `plotly` Python module and the `jupyterlab-plotly` lab extension. They should be at the same version: 4.8.0

**Comment by charlesdong1991** [comment]
ahh, I see, thanks a lot!!

**Comment by wangfan860** [comment]
I have matched version of python Plotly and jupyterlab-plotly, but I still can't see the figure. Any ideas? thanks so much! <img width="584" alt="image" src="https://user-images.githubusercontent.com/18297731/99743028-656e7500-2a9a-11eb-9a23-e1a0ac6e9239.png">

**Comment by charlesdong1991** [comment]
@wangfan860 maybe could try the rebuild suggestion discussed in this similar issue (disclaimer: I didn't try): https://github.com/plotly/plotly.py/issues/2508 

but seems this is indeed an issue in plotly.
