### ISSUE TITLE
Having long x-tickslabels leads to cut off labels in both heatmap and imshow. 

### ISSUE THREAD

**Issue by sorenwacker** [plotly/plotly.py#2506]
Having long x-tickslabels leads to cut off labels in both heatmap and imshow. 

import plotly.graph_objects as go
import datetime
import numpy as np

```
def plotly_heatmap(df, title=None):
    fig = go.Figure(data=go.Heatmap(
            z=df.values,
            x=df.columns,
            y=[ '-'.join([str(j) for j in i]) for i in df.index],
            colorscale='Viridis'))

    fig.update_layout(
        title=title,
        xaxis_nticks=36)

    fig.show()
    return fig

plotly_heatmap(df)
```

```
def plotly_heatmap(df):
    
    img = px.imshow(df,
                    labels = dict(x=df.columns.name, y=df.index.name, color="Test"),
                    x = df.columns,
                    y = [ '-'.join([str(j) for j in i]) for i in df.index])
    return img
    
plotly_heatmap(df)
```

In the second example the size of the heatmap seems to be corrected, but the whole heatmap is centered and not at the top. So, there is a big blank space on the top and the labels are cut off anyway.

**Comment by soerendip** [comment]
PS, when exported to html it looks good. But not when inline of a jupyter notebook.

**Comment by emmanuelle** [comment]
Hi, could you please share a standalone example with some dummy data? I tried to do something quickly but my dataframe did not have the expected structure and I got errors with the function. Thanks!
