### ISSUE TITLE
Blank plot in Jupyter Lab 

### ISSUE THREAD

**Issue by BismeetSingh** [plotly/plotly.py#2508]
This gives blank output in Jupyter Lab running this simple example:
```
import plotly.graph_objects as go
fig = go.Figure()
fig.add_trace(go.Scatter(y=[2, 1, 4, 3]))
fig.add_trace(go.Bar(y=[1, 4, 3, 2]))
fig.update_layout(title = 'Hello Figure')
fig.show()
```

I am running node v12.17.0 and python 3.8.2. and conda 4.8.3

**Comment by nicolaskruchten** [comment]
Similar to https://github.com/plotly/plotly.py/issues/2505... 

What does jupyter labextension list return? This is a common symptom of having mismatched versions of the plotly Python module and the jupyterlab-plotly lab extension. They should be at the same version: 4.8.0. Please check out the troubleshooting guide at https://plotly.com/python/troubleshooting/ for more details :)

**Comment by BismeetSingh** [comment]
![image](https://user-images.githubusercontent.com/13601266/83017834-f875a780-a041-11ea-8429-eaf872366b37.png)

**Comment by nicolaskruchten** [comment]
OK, that looks right. Within JupyterLab, what does `import plotly; plotly.__version__` return?

**Comment by BismeetSingh** [comment]
4.4.1

**Comment by nicolaskruchten** [comment]
Ah ok, so the version should match: I would recommend you upgrade to `plotly` 4.8.0 if you can...

**Comment by ismailuddin** [comment]
I'm still having this exact same problem on Windows with JupyterLab. Plotly Python package version is '4.8.1', and so are the lab extensions (as installed with the version set to 4.8.1 as per the documentation). But if I launch a classic notebook, the same notebook file shows the plots. If I look at the console when inside a JupyterLab template, I get the error

````
Uncaught ReferenceError: require is not defined
....

                require(["plotly"], function(Plotly) {
                    window.PLOTLYENV=window.PLOTLYENV || {};
                    
                if (document.getElementById("8c520407-3036-4b5f-9834-304ee04c0f38")) {
````

But Plotly with JupyterLab on Mac doesn't give me this problem...

**Comment by ismailuddin** [comment]
@nicolaskruchten 
Altair apparently has a similar problem with Jupyter Lab, where the wrong extension seems to be used:
https://altair-viz.github.io/user_guide/troubleshooting.html#jupyterlab-require-is-not-defined

Does this point to a similar problem with Plotly? I'm not sure how you can make Plotly prefer the Jupyter Lab renderer over another?

**Comment by Rabeez** [comment]
Having the same issue with `plotly 4.9.0`

```
JupyterLab v2.2.2
Known labextensions:
   app dir: c:\users\ruote\anaconda3\share\jupyter\lab
        @ijmbarr/jupyterlab_spellchecker v0.1.6 enabled  ok
        @jupyter-widgets/jupyterlab-manager v2.0.0 enabled  ok
        @jupyterlab/toc v4.0.0 enabled  ok
        @krassowski/jupyterlab_go_to_definition v1.0.0 enabled  ok
        @ryantam626/jupyterlab_sublime v0.3.2 enabled  ok
        bqplot v0.4.7 enabled  ok
        jupyterlab-plotly v4.9.0 enabled  ok
        plotlywidget v4.9.0 enabled  ok
```

The test code I'm running is 
```python
fig = go.FigureWidget(data=go.Bar(y=[2, 3, 1]))
fig
```
and I get this error `Error displaying widget: model not found`. Executing `fig.show()` creates a blank output.

**Comment by tecis** [comment]
Having the same issue as @Rabeez and I guess @BismeetSingh .

Has anyone been able to find a solution issue?

 > Additional note: Plotly is functioning properly in IPython, just not Jupyter Lab


#### Instance information:

List of jupyter lab extensions:

```.shell
jupyter labextension list               
JupyterLab v2.2.5
Known labextensions:
        @jupyter-widgets/jupyterlab-manager v2.0.0 disabled OK
        @jupyterlab/toc v4.0.0  enabled  OK
        @lckr/jupyterlab_variableinspector v0.5.1  enabled  OK
        jupyterlab-dash v0.3.0 disabled OK
        jupyterlab-plotly v4.9.0  enabled  OK
        plotlywidget v4.9.0  enabled  OK

```

Plotly version being used: 

```python
plotly.__version__

Out[7]: '4.9.0'
```

Image of Jupyter Lab instance running the getting started code for plotly.express: 
<img width="821" alt="Screen Shot 2020-08-20 at 1 50 08 PM" src="https://user-images.githubusercontent.com/67809811/90807162-10c92b80-e2ec-11ea-9264-d6ad1b71c872.png">

**Comment by nicolaskruchten** [comment]
Some notes: 

1. `FigureWidget` and `Figure` get rendered via two totally different paths and have different failure modes, so folks reporting that `fig` doesn't work for `FigureWidget` instances should check out their `plotlywidget` extension version numbers, whereas `fig.show()` problems for `Figure` instances should check out their `jupyterlab-plotly` extension version numbers.
2. I've found (for reasons that I don't understand yet!) that sometimes just forcing a rebuild of JupyterLab makes things work even though in principle rebuilding the same set of extensions shouldn't change anything, so just running `jupyter lab build`

If you're seeing problems, please do share your version numbers and anything you see in the Javascript console, as although the symptom (no figure rendered) is common, there seems to be many possible underlying causes, which is why people keep piling on to this and similar issues without ever finding the One True Solution :)

**Comment by tecis** [comment]
@nicolaskruchten 
Thanks for responding quickly.

Trying to tackle the problem I tired the these different configuration scenarios with now avail. Do you have any other idea of what might work, or is there any way for me to help?

**Scenario 1**
```shell
jupyter labextension list
        JupyterLab v2.2.5
         Known labextensions:
        @jupyter-widgets/jupyterlab-manager v2.0.0  enabled  OK
        @jupyterlab/toc v4.0.0  enabled  OK
        jupyterlab-dash v0.3.0 disabled OK
        jupyterlab-plotly v4.9.0  enabled  OK

jupyter lab build
```
<img width="1240" alt="Screen Shot 2020-08-21 at 12 24 16 AM" src="https://user-images.githubusercontent.com/67809811/90852272-0edf8680-e345-11ea-8d98-159e39b2aea4.png">

**Scenario 2**

```shell
jupyter labextension list                       
         JupyterLab v2.2.5
         Known labextensions:
        @jupyter-widgets/jupyterlab-manager v2.0.0  enabled  OK
        @jupyterlab/toc v4.0.0  enabled  OK
        @lckr/jupyterlab_variableinspector v0.5.1  enabled  OK
        jupyterlab-dash v0.3.0 disabled OK
        plotlywidget v4.9.0  enabled  OK

jupyter lab build
```
<img width="1067" alt="Screen Shot 2020-08-21 at 12 35 55 AM" src="https://user-images.githubusercontent.com/67809811/90852734-4d297580-e346-11ea-9d95-877683d9389f.png">


Javascript version:
```shell
npm -v
6.14.7
node -v
v14.8.0
```

**Comment by tecis** [comment]
# Environment Information:

Attached: JS Console Log.

Software versions:
- Python                   3.8.3
- jupyter-client         6.1.6
- jupyter-core           4.6.3
- jupyterlab               2.2.5
- jupyterlab-server   1.2.0
- npm                        6.14.7
- node                       14.8.0
- Firefox                    79.0

OS
- MacOS 10.15.6 

Other notes: 
 - Vanilla JupyterLab installed using `pip install jupyterlab` (no Anaconda).
 - Through further testing I found that plotly figures can be generated using IPython from Terminal (7.17.0).

[plotly_js_error.txt](https://github.com/plotly/plotly.py/files/5119736/plotly_js_error.txt)

**Comment by youyoubilly** [comment]
I solved the problem via `jupyter lab build`!

jupyter labextension list:
        jupyterlab-plotly v4.9.0  enabled  OK
        plotlywidget v4.9.0  enabled  OK

$ npm -v
6.14.7
$ node -v
v14.7.0

**Comment by bdthombre** [comment]
Install plotly lab extension
by one of the following command:

conda install -c conda-forge jupyterlab-plotly-extension
conda install -c conda-forge/label/cf202003 jupyterlab-plotly-extension

then restart and run:

>jupyter lab build

then restart again

**Comment by nicolaskruchten** [comment]
I've updated https://plotly.com/python/troubleshooting/ with a bunch more information about common ways this can happen and possible fixes... hopefully this helps!
