### ISSUE TITLE
No 'mode' support for pandas backend plot

### ISSUE THREAD

**Issue by futurehome** [plotly/plotly.py#2515]
pandas                    1.0.3 
plotly                      4.8.0 

```
import numpy as np
import pandas as pd

pd.options.plotting.backend = 'plotly'
pd.DataFrame.from_dict(dict([('A', [1, 2, 3]), ('B', [4, 5, 6])])).plot(mode='line+markers')
```

TypeError: line() got an unexpected keyword argument 'mode'

**Comment by nicolaskruchten** [comment]
This is as intended... `df.plot(...)` delegates to `plotly.express.line(df, ...)` which doesn't support `mode`. If you want to change the mode, you can call `.update_traces(mode="lines+markers")` on the resulting `Figure` object, though!

**Comment by futurehome** [comment]
Got it, thanks.
