### ISSUE TITLE
cell output blank in html if code cell executed twice or more in Jupyter lab

### ISSUE THREAD

**Issue by mvonpapen** [plotly/plotly.py#2516]
# Problem
If a plotly.py cell in Jupyter lab is executed twice (or more) and the notebook then converted into html, the corresponding cell is blank. This issue seems to be related to #1448 .

# Steps to reproduce
1) `docker build -t plotly_bug .` using this Dockerfile:
```
FROM jupyter/minimal-notebook

RUN pip install plotly pandas nbconvert "ipywidgets>=7.5"

# install JupyterLab Extensions
RUN jupyter labextension install jupyterlab-plotly && \
	jupyter labextension install @jupyter-widgets/jupyterlab-manager plotlywidget && \
	jupyter lab build
```

2) `docker run -p 8888:8888 plotly_bug`
3) go to localhost:8888 and create new Python3 notebook
4) execute the following code cell twice in a Jupyter lab notebook:
```
import plotly.express as px
df = px.data.iris()
fig = px.scatter(df, x="sepal_width", y="sepal_length", color="species",
                 size='petal_length', hover_data=['petal_width'])
fig.show()
```
5) File --> Download as --> html
6) open html and the cell output is blank
![image](https://user-images.githubusercontent.com/26275671/83245353-e65e4b00-a1a0-11ea-92ab-27df0ee909ff.png)
7) Developer console shows this error:
```
Uncaught Error: Script error for: plotly
http://requirejs.org/docs/errors.html#scripterror
    at C (require.min.js:8)
    at HTMLScriptElement.onScriptError (require.min.js:29)
```

# Workaround
A workaround for this bug is to add
```
from plotly.offline import init_notebook_mode
init_notebook_mode(connected=False)
```
to the code cell. This works for both `connected=False` and `connected=True`. I find this strange because @nicolaskruchten [mentioned](https://github.com/plotly/plotly.py/issues/1448#issuecomment-582227331) that `init_notebook_mode` "no longer does anything".

# Versions
plotly = 4.8.1

Output of `jupyter labextension list`:
```
JupyterLab v2.1.3
Known labextensions:
   app dir: /opt/conda/share/jupyter/lab
        @jupyter-widgets/jupyterlab-manager v2.0.0  enabled  OK
        jupyterlab-plotly v4.8.1  enabled  OK
        plotlywidget v4.8.1  enabled  OK
```

**Comment by draustin** [comment]
I have reproduced this behavior. Versions: plotly = 4.8.1, Jupyter notebook = 6.0.3, Python = 3.8.3. Browser is Chrome and platform is Windows. The developer console error message is the same as quoted above.

**Comment by timvink** [comment]
Thanks! This issue helped me solve a similar issue (VSCode on windows 10, `plotly==5.3.1`, `nbconvert==6.2.0` , browser Chrome)

Solution for me:

```python
from plotly.offline import init_notebook_mode, iplot
init_notebook_mode(connected=False)
iplot(fig)
``

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
