### ISSUE TITLE
Problem converting PDFs to bbytes?

### ISSUE THREAD

**Issue by RMeli** [plotly/plotly.py#2521]
The following code throws an error when `format="pdf"`:

```
img_bytes = fig.to_image(format="pdf")
img = Image.open(io.BytesIO(img_bytes))
img.save("image.pdf")
```
```
Traceback (most recent call last):
  File "test.py", line 27, in <module>
    img = Image.open(io.BytesIO(img_bytes))
  File "XXX/lib/python3.7/site-packages/PIL/Image.py", line 2896, in open
    "cannot identify image file %r" % (filename if filename else fp)
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7f6515a11e30>
```

Using (`format="png"`) works as expected.
```
img_bytes = fig.to_image(format="png")
img = Image.open(io.BytesIO(img_bytes))
img.save("image.png")
```

**Comment by nicolaskruchten** [comment]
This is pretty much as expected... Here you're trying to open an PDF with PIL, which is an image-processing library. This StackOverflow answer might help you save the `BytesIO` to a file using Python built-ins: https://stackoverflow.com/questions/29324037/convert-bytesio-into-file

**Comment by RMeli** [comment]
@nicolaskruchten Thank you for pointing this out.  I was under the impression that PDFs were supported by PIL, but I now realize they are a write-only format.

However, if I write out the PDF as follows
```
img_bytes = fig.to_image(format=fmt, scale=5)

with open(f"hyperopt.{fmt}",'wb') as out:
    out.write(img_bytes)
```
the lines produced by `px.parallel_coordinates` are still pixelated  (i.e. they look like they would in the PNG). This is a different issue, but is it expected?

**Comment by nicolaskruchten** [comment]
Yes, this is a known limitation of certain trace types, `parcoord` included... see note at bottom of section https://plotly.com/python/static-image-export/#vector-formats-svg-and-pdf

The reason here is that parallel coordinates are implemented using a raster technology (WebGL) under the hood for performance reasons, and so remain rasterized no matter the output target.

**Comment by RMeli** [comment]
I see, thank you very much for the clarification and the link!
