### ISSUE TITLE
px.histogram draws incorrect size of count bars when grouped by color

### ISSUE THREAD

**Issue by mateusz-d4c** [plotly/plotly.py#2538]
<img width="949" alt="Screenshot 2020-06-05 at 11 28 29" src="https://user-images.githubusercontent.com/61227728/83860869-216ff980-a720-11ea-8a1c-fb75b2b33dc1.png">
Hi,

I believe I have found an issue with plotly express which is visible even on the tutorial page. Namely when drawing a histogram with plotly express and using `color` argument to group data, the size of count bars is bigger than the real count value.

Code from tutorials can be used as a reproducible example (section: _Visualizing the distribution_):
https://plotly.com/python/histograms/ Count bars for `Male` group are bigger than actual counts displayed when we hover over the bar. E. g. for `total_bill = 16 - 17.99` we have `count = 18` in the annotation, but the value displayed is greater than 30. I've manually checked a few values for various plots and the true value is correctly displayed in the annotation. The count bars are however much bigger than they should.

For completeness, here's the code which is being used in the tutorial:

```
import plotly.express as px
df = px.data.tips()
fig = px.histogram(df, x="total_bill", color="sex", marginal="rug", # can be `box`, `violin`
                         hover_data=df.columns)
fig.show()
```

**Comment by nicolaskruchten** [comment]
The count of the red bar is indeed 18, and it's stacked on top of a blue bar representing a count of 14, so the total height of the stack is 32. You can change this behaviour with the `barmode` parameter, for example setting it to `overlay`:

![image](https://user-images.githubusercontent.com/203523/83876414-d2699a80-a706-11ea-806d-335e0e3d0608.png)

Or `group`:

![image](https://user-images.githubusercontent.com/203523/83876452-de555c80-a706-11ea-988a-2d718e971822.png)

**Comment by mateusz-d4c** [comment]
Ah! Ok. Thank you

**Comment by adirot** [comment]
I think the default should be barmode = overlay, that is the more intuitive one
