### ISSUE TITLE
fig.update_layout() does not iterate on all facets

### ISSUE THREAD

**Issue by rsgoodwin** [plotly/plotly.py#2545]
I am trying to make a faceted plot where I need to treat the x axis as categorical,  even though it is an integer.   On a single chart (that is not faceted),  the following works:

`fig.update_layout(xaxis_type='category')`

However,  on a faceted chart,  only one of the facets is changed.  I would think that updating the figure layout would iterate on all facets.

Is there an an alternate way to do this using one of the fig.for_each_*() methods?  (as in for_each_xaxis() .  I played around with it but could not seem to find a way to do it.

Using plotly 4.6.0 on windows

Thanks
```
import pandas as pd
import plotly.express as px

df = pd.DataFrame({
    'x': [1, 2, 3, 5, 6],
    'y1': [1, 2, 3, 4, 5],
    'y2': [10, 11, 12, 13, 15]
}).melt('x')

bars = px.bar(
    data_frame=df,
    x = 'x',
    y = 'value',
    facet_col = 'variable'
)

bars.update_layout(xaxis_type='category')
bars.show()
```
![2020-06-05_19-45-25](https://user-images.githubusercontent.com/2280241/83934352-43d83600-a765-11ea-8245-8166d622d28e.png)

**Comment by nicolaskruchten** [comment]
This is as intended: `layout.xaxis` refers to one x axis, and `layout.xaxis2` refers to the other. If you want to update all x axes, you can use `.update_xaxes(type="category")`.

Furthermore, you can use `.update_xaxes(row=1, col=2, type="category")` to target your update to a specific facet if you so choose, so you don't really need to keep track of `xaxis` vs `xaxis1` etc yourself if you choose not to :)

**Comment by rsgoodwin** [comment]
:)  Thanks!   I am officially ashamed of my google and "read the docs" skills.  Thanks for the simple and direct answer.  Perhaps the post will benefit the next person googling around for this!

Keep up the excellent work on plotly!

**Comment by nicolaskruchten** [comment]
No need for shame! our docs aren't as clear as they should be :) Thanks for adding an easy-to-google-for issue that others can stumble across!

**Comment by MaxGhenis** [comment]
For posterity: `update_layout(xaxes_type='category')` does not work; you need to use `update_xaxes` as suggested here.

**Comment by rsgoodwin** [comment]
Yup `fig.update_xaxes(type='category')`,  as documented [here](https://plotly.com/python/categorical-axes/).

Thanks for the posterity post!
