### ISSUE TITLE
distplot wrapper

### ISSUE THREAD

**Issue by jackparmer** [plotly/plotly.py#256]
@cldougl basically already wrote this for Tesla:

http://nbviewer.ipython.org/gist/cldougl/0667ff6ca4ce83abc88a

Based on Seaborn's dist plot:

http://stanford.edu/~mwaskom/software/seaborn/generated/seaborn.distplot.html

Someone just needs to incorporate it into TraceFactory

Seaborn has some other *really* nice plotting wrappers that might have useful plotly implementations:

http://stanford.edu/~mwaskom/software/seaborn/examples/many_facets.html
http://stanford.edu/~mwaskom/software/seaborn/examples/scatterplot_matrix.html
http://stanford.edu/~mwaskom/software/seaborn/examples/hexbin_marginals.html

**Comment by cldougl** [comment]
https://plot.ly/python/distplot/
