### ISSUE TITLE
no src/index.js in jupyterlab-plotly makes it fail to build for jupyterlab app

### ISSUE THREAD

**Issue by TermeHansen** [plotly/plotly.py#2560]
I'm trying to build my own app based on jupyterlab, using there example/app. I have added plotlywidget without any problems to the app, but jupyterlab-plotly fails to build because it can not find the src/index.js that is mentioned as main in package.js

https://github.com/plotly/plotly.py/blob/d1914585bfe747218e95218b2744898d0242de9b/packages/javascript/jupyterlab-plotly/package.json#L7

Why is there no index.js, and how do I fix this issue the best?

**Comment by TermeHansen** [comment]
changing to "dist/javascript-renderer-extension.js" makes it build. Is that the fix?

**Comment by TermeHansen** [comment]
seems to work - kind of. I don't see anythin in a standard notebook in the app, but from voila-preview it show?!?
![image](https://user-images.githubusercontent.com/6922018/84498171-69f35e00-acb0-11ea-8d6d-5a6be54e53e2.png)
no error in jupyterlab consol, but this in browser console:
```
ReferenceError: require is not definedexample line 123439 > scriptElement:2:17
    <anonymous> example line 123439 > scriptElement:2
    attachWidget index.es6.js:2758
    insertWidget index.es6.js:2661
    _insertOutput widget.js:392
    onModelChanged widget.js:216
    invokeSlot index.es6.js:459
    emit index.es6.js:416
    emit index.es6.js:99
    _onListChanged model.js:231
    invokeSlot index.es6.js:459
    emit index.es6.js:416
    emit index.es6.js:99
    push observablelist.js:135
    _add model.js:207
    add model.js:128
    _onIOPub widget.js:91
    _handleIOPub future.js:216
    InterpretGeneratorResume self-hosted:1151
    AsyncFunctionNext self-hosted:693
```

which comes from this line:
```
        // Insert the widget's node before the sibling.
        this.parent.node.insertBefore(widget.node, ref);
```

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
