### ISSUE TITLE
Add base to px.bar

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.py#2585]
and consider adding px.timeline.

**Comment by JulianWgs** [comment]
I'm assuming you mean something like the bottom parameter in [matplotlib's bar chart](https://matplotlib.org/api/_as_gen/matplotlib.pyplot.bar.html)?

**Comment by nicolaskruchten** [comment]
Yes, that's roughly what the `base` parameter does. We've recently fixed a bug in plotly.js which prevented reliable use of `base` and `x` together to make horizontal gantt-like timeline charts, so exposing `base` in `px.bar` would basically allow us to replace the `create_gantt` figure factory.

**Comment by JulianWgs** [comment]
That sounds like a good idea. What is the ETA on this? I want to use this feature in one of my projects. What would be the path of action to take? Do you need help? :)

**Comment by nicolaskruchten** [comment]
so this is already supported at the Graph Objects layer. This issue just refers to adding the option into Plotly Express. The ETA is that it'll be added to Plotly.py 4.9.0 in 2-3 weeks :) No help needed at the moment but thanks for the offer!
