### ISSUE TITLE
Plotly Express bar subplots with log scale button

### ISSUE THREAD

**Issue by lumbar63** [plotly/plotly.py#2596]
I am new to plotly express and pretty new to coding in general. What I am trying to do is develop a dashboard to highlight the data I have regarding offences that have taken place over the last several years. The data contains the total number of offences reported in a given year for each region and is broken down further into specific offences. In the sample data I have provided I am comparing three offences, Road collision with injury, road fatalities and traffic infringement notices. What I have done so far is create a 4X2 faceted bar chart ; however, the scale is too large to see some of the smaller results. So I in an attempt to see the data more clearly I added linear/log buttons to my code; however, the log only takes effect on the row4, col1 chart. Is there any way to apply the log scale to each facet?

Below is the code I used to develop the charts. I have included a snapshot of part of the graph and also a snapshot of part of the dataframe I am using. Ultimately I want all individual charts to look like the 2020 chart. Any help would be greatly appreciated.

traffic = df[((df['Date'] == '2014') | (df['Date'] == '2015') | (df['Date'] == '2016') | (df['Date'] == '2017') |
           (df['Date'] == '2019') | (df['Date'] == '2020'))
           & ((df['Offence']== 'Traffic infringement notices') | (df['Offence']== 'Road Collision with injury')
           | (df['Offence']== 'Road Fatality')) & (df['Region'] != 'ACT')]

fig24 = px.bar(traffic, x='Offence', y= 'Nr_Incidents', color = 'Region', hover_data=['Region', 'Date'], barmode = 'group', 
             facet_col='Date', facet_col_wrap=2)
fig24.for_each_annotation(lambda a: a.update(text=a.text.split('=')[-1]))
fig24.update_layout(
    updatemenus = [
        dict(
            buttons = list([
                dict(label='Linear', method='relayout', args=[{'yaxis.type': 'linear'}]),
                dict(label='Log', method='relayout', args=[{'yaxis.type': 'log'}]),
            ]),
        )
    ],
    margin=dict(
        t=100, b=50, 
    ),
    title="ACT Traffic Offences by Year 2014-2020",
    title_x = 0.5,
    width = 900,
    height = 1200,
    font=dict(
        size=12,
        color="#7f7f7f"
    ))
fig24.update_yaxes(matches = None)

![sample dataframe](https://user-images.githubusercontent.com/23353140/85641528-2c3ffd80-b6d2-11ea-9dad-fa86be8073ea.png)
![sample charts](https://user-images.githubusercontent.com/23353140/85642475-fa7c6600-b6d4-11ea-9ee9-e3d9ed64e24d.png)

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
