### ISSUE TITLE
Plots display on Jupyter Lab but don't show titles, labels or interactivity. 

### ISSUE THREAD

**Issue by GiordanPretelin** [plotly/plotly.py#2602]
Hi, I was wondering if someone has an idea of what can be happening and how I can solve it.

I can display plots on Jupyterlab but they show no title, labels or hover information even when adding it. I think I have the most recent extensions. Any idea?

![image](https://user-images.githubusercontent.com/25410458/85788469-a4b6b680-b6f2-11ea-9fc0-16937863c547.png)

![image](https://user-images.githubusercontent.com/25410458/85789001-77b6d380-b6f3-11ea-8210-f7855d5694e0.png)

When ouputing to an HTML I can see it properly displayed:
![image](https://user-images.githubusercontent.com/25410458/85788938-5e158c00-b6f3-11ea-9955-4369e0ad2fc2.png)

Thanks in advance.

**Comment by JoopBanaan** [comment]
Same here
$ jupyter labextension list                                                
JupyterLab v2.2.8                                                          
Known labextensions:                                                       
   app dir: c:\users\jk035588\python_envs\jupyterlab228\share\jupyter\lab  
        @aquirdturtle/collapsible_headings v2.2.0 enabled  ok              
        @bokeh/jupyter_bokeh v2.0.3 enabled  ok                            
        @ijmbarr/jupyterlab_spellchecker v0.1.6 enabled  ok                
        @jupyter-widgets/jupyterlab-manager v2.0.0 enabled  ok             
        @jupyterlab/celltags v2.2.6 enabled  ok                            
        @jupyterlab/debugger v0.3.4 enabled  ok                            
        @jupyterlab/git v0.22.3 enabled  ok                                
        @jupyterlab/toc v4.0.0 enabled  ok                                 
        @krassowski/jupyterlab_go_to_definition v1.0.0 enabled  ok         
        @pyviz/jupyterlab_pyviz v1.0.4 enabled  ok                         
        @ryantam626/jupyterlab_code_formatter v1.3.6 enabled  ok           
        @wallneradam/run_all_buttons v0.2.0 enabled  ok                    
        jupyterlab-chart-editor v4.10.0 enabled  ok                        
        jupyterlab-favorites v2.0.0 enabled  ok                            
        jupyterlab-plotly v4.12.0 enabled  ok                              
        jupyterlab-recents v2.0.0 enabled  ok                              
        jupyterlab-snippets v0.3.2 enabled  ok                             
        nbdime-jupyterlab v2.0.1 enabled  ok                               
        plotlywidget v4.12.0 enabled  ok                                   
        qgrid2 v1.1.3 enabled  ok

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
