### ISSUE TITLE
Skipping categories instead of overlapping them

### ISSUE THREAD

**Issue by discdiver** [plotly/plotly.py#2606]
plotly backend for pandas with barh isn't showing all the rows.display error 

Plotting in JupyterLab, offline.

Only half the row labels are shown, although all the bars are shown.

![plot_showing_half_barh_row_labels](https://user-images.githubusercontent.com/7703961/85901654-4829c900-b7d0-11ea-9a06-3899e9fd744c.png)
[soccer.csv.zip](https://github.com/plotly/plotly.py/files/4839270/soccer.csv.zip)

csv file for data to read in also attached. It's zipped. And it's like 20 lines of soccer stats.

```
import pandas as pd #v1.0.5
import plotly #v4.8.2

pd.options.plotting.backend = "plotly" 

players = pd.read_csv('soccer.csv', index_col=0)
players['G'].sort_values(ascending=True).plot(kind='barh')
```

**Comment by nicolaskruchten** [comment]
This is by design: you’ll need to increase the height or decrease the font size to get all the text to render without overlaps.

**Comment by nicolaskruchten** [comment]
Come to think of it, maybe setting `layout.yaxis.nticks` to a large number might do it too.

**Comment by discdiver** [comment]
Thanks for the work-around.As a user, it would be nice if it just worked. 😀

**Comment by nicolaskruchten** [comment]
Fair enough. 

This is a tricky area in terms of picking defaults. Right now if `nticks` is unspecified, it is being dynamically computed while taking into account the bounding boxes of the possible tick labels and the height of the plot, so as to avoid overlap. In Plotly terms, you're basically saying you want the default `nticks` to be equal to the number of categories (in the case of categorical axes), even if this causes overlap. The "right way" to express this desire today is to override the default and to set `nticks`. I'm not sure that I agree that having overlap is a better default but we could discuss changing this in the next major version (when breaking changes are allowed).

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
