### ISSUE TITLE
Choropleth only displaying one color in custom geojson

### ISSUE THREAD

**Issue by COYE-Coder** [plotly/plotly.py#2619]
I am trying to create a choropleth using `plotly.express`. The figure is able to load, but it only shows one color. I can mouse over each feature and it displays the relevant information, but not in variable color. This implies that it is reading the geojson but not displaying properly. [Here](https://stackoverflow.com/questions/62719643/plotly-express-choropleth-only-shows-one-color) is my stackoverflow thread I created earlier. 

I am using the `featureidkey` parameter with a geojson (_hucs_) that should match with the DataFrame (_predictions_). 

Here is _predictions_:

```
import pandas as pd
predictions = pd.read_csv("Predictions_DF_2002.csv")

predictions.head()
```

```
huc12           Predicted PRBT   Std
170102120304    30.677075        23.348831
170102120603    31.362211        23.784001
90400010201     5.697461         7.688427
100301040401    3.493039         5.36472
170101011208    4.421055         11.924093
```

And here is the code for reading in the geojson (_hucs_):

```
#Read in geojson
import geopandas as gpd
import json


hucs = gpd.read_file(~/"HUC.geojson")

#Populate hucs['properties'] (i.e. convert to plotly-readible geojson-type)
hucs = json.loads(hucs.to_json())

#Print Properties for sanity check
print(hucs['features'][0]['properties'])
```
```
#...<a bunch of stuff we don't care about> 
{'huc12':170102120304}
#...
```

I followed the example [here](https://plotly.com/python/choropleth-maps/#indexing-by-geojson-properties) to index by geojson properties:

```
fig = px.choropleth(predictions,
                    geojson=hucs, color='Predicted PRBT',
                    locations='huc12', featureidkey='properties.huc12',
                    color_continuous_scale="Viridis", labels={'Predicted PRBT':'Predicted % RBT'})
fig.update_geos(fitbounds="locations",visible=False)
fig.show()
```
And here is what the output shows. Note that mouse-over shows relevant information, but no colors are displayed:

![image](https://user-images.githubusercontent.com/47835300/86614020-9c227380-bf6f-11ea-8972-11cc191f31c4.png)

My csv and geojson are available for download [here](https://drive.google.com/file/d/1yUBsWTeOUbKe8kkNQlE_tUKBsO_fV5h0/view).

Many thanks in advance for the help!

**Comment by nicolaskruchten** [comment]
The issue appears to be with your GeoJSON file, which is "wound" the wrong way... see https://github.com/plotly/plotly.py/issues/2354#issuecomment-638742767 for a fix.

**Comment by nicolaskruchten** [comment]
![image](https://user-images.githubusercontent.com/203523/86683909-0834c400-bfd0-11ea-9045-0c5848d46038.png)

**Comment by COYE-Coder** [comment]
That solved it, thank you!

**Comment by nicolaskruchten** [comment]
Here's more copy-pasteable code for starting from a badly-wound GeoPandas dataframe:

```python
import json
import geojson_rewind
import geopandas as gpd

gdf = gpd.read_file("badly_wound.json")

gdf = gdf.set_geometry(
    gpd.GeoDataFrame.from_features(
        json.loads(
            geojson_rewind.rewind(
                gdf.to_json(), 
                rfc7946=False
            )
        )["features"]
    ).geometry
)
```

**Comment by ColdTeapot273K** [comment]
> Here's more copy-pasteable code for starting from a badly-wound GeoPandas dataframe:
> 
> ```python
> import json
> import geojson_rewind
> import geopandas as gpd
> 
> gdf = gpd.read_file("badly_wound.json")
> 
> gdf = gdf.set_geometry(
>     gpd.GeoDataFrame.from_features(
>         json.loads(
>             geojson_rewind.rewind(
>                 gdf.to_json(), 
>                 rfc7946=False
>             )
>         )["features"]
>     ).geometry
> )
> ```

This can sometimes produce dataframe with empty geometry column.

Somewhat more robust way:

```python
igdf = gdf.set_geometry(
    gpd.GeoDataFrame.from_features(
        json.loads(
            geojson_rewind.rewind(
                gdf.to_json(), 
                rfc7946=False
            )
        )["features"]
    ).geometry.values
)
```

Tested on:
- geopandas == 0.14.3
- plotly == 5.19.0
