### ISSUE TITLE
Feature request: Mesh webgl

### ISSUE THREAD

**Issue by VHchavez** [plotly/plotly.py#2620]
Hello all, Thank you for developing this amazing library!

I am a graduate student in chemistry and I am working on molecular visualization in Jupyter. The module requires the addition of multiple cylinders and spheres as go.Mesh3D traces. This works great for a small molecules but becomes very slow for more than a few atoms/bonds. A binder example can be found here: https://mybinder.org/v2/gh/vhchavez/molyexamples/master?filepath=basic_examples%2FBasic_Example.ipynb

I have recently found your Dash-bio demo using Speck and I think it is really great. I am interested in developing more functionality relevant for chemists that includes volume and vector spaces visualization, and animations within Jupyter Notebooks, and I would find it very beneficial to keep everything on the Python level.

I have noticed that functions like scatter and heatmap have their webgl "versions" for fast computation of a vast set of points, I was wondering if there is any plan to have more of your functions powered by webgl. Having a fast option for visualizing a Mesh would make more complex things like animations possible. I would be more than happy to put my hands into this if someone experienced from your team could provide some support. 

Any input from you folks will be greatly appreciated,
Merci bien!
Victor Hugo

**Comment by nicolaskruchten** [comment]
Hi Victor,

The `mesh` trace is already rendered using webgl actually, although it certainly could be optimized to work faster/scale better with more points :) At the moment this is not on our roadmap and we would probably need an organization to step up to fund this work in order to get it done in the near future.

**Comment by VHchavez** [comment]
Thanks for your response Nicolas, 
This is incredible helpful information. I will try to see If I can create and feed the traces to the figure object in a more efficient way.
