### ISSUE TITLE
Customising facet plots

### ISSUE THREAD

**Issue by anuraghuram** [plotly/plotly.py#2622]
I have a facet plot using px.line(). I want to add a trace over the existing plots in each facet but not sure if there is functionality for this. Something like fig.for_each_facet() would be useful, especially to add plots for multiple y values.

_Note: I had previously tried installing v.4.8.1, since I read [here](https://community.plotly.com/t/announcing-plotly-py-4-8-plotly-express-support-for-wide-and-mixed-form-data-plus-a-pandas-backend/40048/3) that px.line() can now take multiple y values. However, when I tried implementing this, I received the following error:_

'ValueError: All arguments should have the same length. The length of `y` is 2....'

**Comment by nicolaskruchten** [comment]
Can you provide a bit more context around what you're trying to do so we can better answer your question? Are you trying to add more line traces? the same trace to each facet?

**Comment by anuraghuram** [comment]
Yex, exactly that - I would like to add the same trace to each facet.

**Comment by nicolaskruchten** [comment]
OK, and you're on version 4.8 or later? Does `df` have columns `time, profit, loss, product, size`? If so, this should work...

**Comment by anuraghuram** [comment]
Correct, I have pip installed 4.8.1 and `df` contains all of the above columns.

**Comment by nicolaskruchten** [comment]
Hmm, so this actually does work for me, if I just use one of the built-in dataframes and rename the columns...

```python
import plotly.express as px

df = px.data.tips()
df = df.rename(columns=dict(total_bill="profit", tip="loss", sex="product"))
print(df.head())

fig = px.line(df, x='time', y=['profit', 'loss'], color='product', facet_col='size')
fig.show()
```

**Comment by anuraghuram** [comment]
For multiple y values to work, can we pass columns containing 'NULL' observations? I'm not sure if that is why I am receiving the length error...

**Comment by nicolaskruchten** [comment]
That shouldn't make a difference ... can you double-check the plotly version with `import plotly; print(plotly.__version__)` ?

**Comment by anuraghuram** [comment]
Yes, I see 4.8.1. Not sure if uninstalling/reinstalling would help?

**Comment by nicolaskruchten** [comment]
Are you able to run the code I pasted above?

**Comment by anuraghuram** [comment]
Yes. It isn't clear to me if the input df needs to be indexed, as is implied in the wide example [here](https://community.plotly.com/t/announcing-plotly-py-4-8-plotly-express-support-for-wide-and-mixed-form-data-plus-a-pandas-backend/40048/3). Can you please clarify if I need to index `time`, `product` and `size`?

**Comment by nicolaskruchten** [comment]
Indexes are not required, they will be inferred if absent. If you can run the code above then there's no version problem... Can you share a minimal example of the data that is causing an error for you, even if this data is synthetic?

**Comment by anuraghuram** [comment]
It works now, thank you -- I notice that my profit trace looks like a normal line plot (with peaks and dips), but see that the loss trace is a straight line (which should not be the case). Any reason why this trace is getting plotted as a perfectly straight line?

**Comment by nicolaskruchten** [comment]
I'd need to see some sample data to be able to comment further :) One thing to keep in mind is that line charts are plotted in the order given, so you may need to sort your data frame by the `time` column.

**Comment by anuraghuram** [comment]
Using the toy data example above, I'm trying to map the loss trace as a dashed line, and the profit trace as a solid line. Additionally, I want to format the keys such that for each product (Female, Male), I have a key corresponding to product x trace type:

Female - profit
Female - loss
Male - profit
Male - loss

**Comment by nicolaskruchten** [comment]
Oh, I see. You can set `line_dash="product"` in that case then.

**Comment by anuraghuram** [comment]
Thank you! However, I still had to .melt() the df from wide to long format, and then create a new column called product_measure (containing the combinations that I wanted above). One potential feature that might be useful is to enable cross-tabulations within the colour parameter (for instance with the y value(s) passed through the y parameter in this example).

**Comment by nicolaskruchten** [comment]
Hmm, well, I'm fairly certain you can do what you're trying without having to `melt()` the data ahead of time, but if you've got things working that's great!
