### ISSUE TITLE
Improve PDF export by making them Interactive

### ISSUE THREAD

**Issue by philipptempel** [plotly/plotly.py#2625]
CAD tools like SolidWorks allow to export the generated model as a 3D PDF which uses Adobe Flash inside a PDF to display all components. It even supports to hide components, change transparency, and to, of course, navigate around the model.

I would love to see a similar feature for the PDF export from plotly as I often find myself creating unit tests for my models (robotics models) and it is quite a burden on my browsers to open many figures for every unit test. As such, it would be great to have the ability to export to PDF but with the same functionality as a rendered HTML file.
For reference, there is a MATLAB implementation of this feature https://nl.mathworks.com/matlabcentral/fileexchange/37640-export-figure-to-3d-interactive-pdf that turns figures to 3D interactive PDFs (with a detour over a TeX file, but still).
Also, for bigger plots, particularly 3D plots with lots of data, exporting them to a 3D PDF and then viewing in Adobe Reader would reduce the memory footprint (I assume) and make viewing the results much quicker.

Would that be a feature we could see in the future?

**Comment by nicolaskruchten** [comment]
That sounds really exciting! We'd be really happy to work with someone to build this kind of thing, indeed!
