### ISSUE TITLE
Feature Request: Mapbox Density Heatmap Aggregation Option

### ISSUE THREAD

**Issue by phaabe** [plotly/plotly.py#2630]
Hi, I am wondering how data is aggregated in density map and this may turn into a feature request.
As data can be aggregated in time, here in a density map it is aggregated in space. Meaning: When I have 3 points on a map and I zoom out they will be merged to one point -- they are aggregated. But which value should be taken here?

- The maximum of the three?
- The average?
- The minimum?
- The sum?
- ...

As for time-wise aggregation it depends on the application and I believe it makes sense to offer options here.
Looking at [this example](https://plotly.com/python/mapbox-density-heatmaps/) I am not quite following how aggregation works. When I zoom into Greece I see a lot of tiny values being purple and showing values around 5 (hovering shows values). And when I zoom out it is turning more and more yellow which represents values around 9. But hovering still shows values around 5 again.
How can that be explained? And how about adding this option?

Thanks

**Comment by nicolaskruchten** [comment]
The actual logic used to draw the map comes from Mapbox GL so probably the best answer to your question would be to check out their documentation: https://docs.mapbox.com/help/tutorials/make-a-heatmap-with-mapbox-gl-js/

**Comment by phaabe** [comment]
Thanks for the answer! 

The key phrase from the article is:

> we draw the kernel (which looks like a blurred circle) into an offscreen half-float texture with additive blending (so that values are **summed** together when kernels overlap)

I will ask in their repository why they took this design decision :)
