### ISSUE TITLE
Plotly express scatter plot seems to have a certain limit of max groups displayed in animated plot?

### ISSUE THREAD

**Issue by bolekkerous** [plotly/plotly.py#2634]
Hey,
this is something that I spent already quite a few hours with and I came to the conclusion that it's either or bug or I am somehow using it wrong and can't figure out what's the problem. I tried googling and searching the issue here but no luck.

Basically my problem is this. I have a dataset with around ~50k rows, pretty similar to the gapminder dataset - country gdp and their taxation rate in over time in different years. And I want to do the gapminder animation. That in itself is not a problem. The problem is that when I export the animated chart, some data from the dataset is missing / disappears during the animation, even though the data definitely is in the dataset (because when I preprocess the dataset and filter it just to that country, in this case USA, it is able to plot the data for the country for all the years).

Not sure if the problem is completely understandable from the description, so I recorded a video.  
  
https://tax-gdp.surge.sh/plotly_express.mp4

In the first run you can see that USA dissapears, in the second run when I filter the data set to just USA, it works correctly.

So far from my digging, it looks like if there is some sort of limit on the number of entities that can be animated in one plot at a time? And because there are some countries that do not have data for all the years (for example data only since 2005 like China), when they appear, they basically pop out other countries that were there before? At least that's my hunch based on the fact that in the legend scrollbar listing the entities, it always somehow cuts off at around ~60 countries and doesn't show the rest for some reason (notice that countries starting with Z are missing completely from the list for example)  
  
Here's my code and links to hosted visualizations.

Code:

```
import pandas as pd
import plotly_express as px
import plotly.io as pio

df = pd.read_csv('./country-level-taxes-vs-income.csv')

### clean missing records
clean = df[df.tax.notnull() & df.gdp.notnull() & df.population.notnull()]

### USA alone
# clean = clean[clean.code == 'USA']

fig = px.scatter(clean, x="tax", y="gdp", animation_frame="year", category_orders={"year": ['1990','1991','1992','1993','1994','1995','1996','1997','1998','1999','2000','2001','2002','2003','2004','2005','2006','2007','2008','2009','2010','2011','2012','2013','2014','2015','2016','2017']}, animation_group="country", size="population", color="country", hover_name="country", log_y = True, size_max=45, range_x=[0,50], range_y=[100,100000], render_mode="svg")

fig.layout.updatemenus[0].buttons[0].args[1]["frame"]["duration"] = 1000
fig.layout.updatemenus[0].buttons[0].args[1]["transition"]["duration"] = 0
fig.show()

pio.write_html(fig, file='./all.html', auto_open=True)

```

Data: https://tax-gdp.surge.sh/country-level-taxes-vs-income.csv  
Jupyter notebook: https://tax-gdp.surge.sh/gdp_tax.ipynb  
USA - working example html: https://tax-gdp.surge.sh/usa.html
All countries - not working example html: https://tax-gdp.surge.sh/all.html

Let me know in case you need any other info. I tried it also in google collab, so I'd say it probably isn't a problem with my version of python or plotly (I'm using the latest).
  
Thanks!

**Comment by bolekkerous** [comment]
Oh my god, literally minutes after writing this issue I tried to remove `color="country"` from the call and it solved it. So I guess there is a limited number of predefined colors that are able to be assigned and if there are more groups than defined colors, it starts behaving oddly.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
