### ISSUE TITLE
Skewed heatmap / image / isosurface...

### ISSUE THREAD

**Issue by pfebrer96** [plotly/plotly.py#2635]
Hi!

I have scientific data represented in 3D grids. Heatmaps and isosurfaces are great for displaying them. However, in some cases the axes of the grid are not `x`, `y` and `z`, but some other direction in space. Then, I would like to somehow see the "skewed" images. I believe it is not possible in plotly to specify the "direction" of the axes in these kind of traces, is it? I don't know how hard it would be to implement, but it would be extremely useful.

In case this is not feasible or you are not interested in implementing it, could you suggest a workaround? I'm quite lost on this :)

PS: Sorry if this belongs to `plotlyjs` github page, I'm not sure.

**Comment by empet** [comment]
@pfebrer96 An instance of the class `go.Isosurface` is defined by plotly.js as a `Mesh3d` trace, with vertices and faces (triangles) returned by the Marching Cube algorithm.
This algorithm acts on 3D grids associated to a parallelepiped with sides  parallel to the standard axes, i.e. axes of directions
 e1=(1, 0, 0), e2=(0,1,0), e3=(0,0,1). @archmoj  can give more details on how this algorithm works for `go.Isosurface`


If go.Isosurface had a transformation attribute, i.e. an array of shape (3,3), and positive determinant,
`T=np.array([u1, u2, u3]).transpose()`, to  map vertex coordinates resulted from marching cube triangulation, then we could simply define an isosurface carved within a volume with sides of directions u1, u2, u3. Namely it could be defined  as a Mesh3D having as  vertices, the T-transformed initial vertices, and the same faces. See a workaround for this procedure in this notebook [https://chart-studio.plotly.com/~empet/15738](https://chart-studio.plotly.com/~empet/15738).

Notice that unlike the isosurfaces defined as `go.Isosurface`(s), the isosurfaces constructed by the method presented in the above Jupyter Notebook can be colored according to vertex intensities (defined by a scalar field on the isosurface). 

If you intend to propose a PR, for such isosurfaces,  then it must be posted on plotly.js, not here.

**Comment by pfebrer96** [comment]
Thank you very much for your reply! It was very enlightening, as I didn't know how isosurfaces were calculated. The notebook was specially helpful, thanks for that!

> If you intend to propose a PR, for such isosurfaces, then it must be posted on plotly.js, not here.

I'm using your workaround right now as I like to have the vertices and faces available for quantitative analysis. I will not be submitting a PR to plotly.js because I don't have any notion of how the package is structured :+1: 

One last thing: Most of the times we like to plot only 2 dimensions (e.g. a cross section or averaging a dimension) because it is easier to visualize and it gives us the information that we want. Do you have any suggestion on how to do this? I can think of the very dirty approach of using a scatter trace with `fill="toself"` for each pixel, but that is far from optimal :)  Is there a similar workaround for the 2D case or would I need to create a 3D mesh and make it look as if it were 2D?

Thanks!

**Comment by empet** [comment]
I haven't understood your question. Do you intend to define and plot a slice in a volume ? Or  are you  to another  2d plot?

**Comment by pfebrer96** [comment]
Sorry, I should have explained better.

Imagine I have a 3D array that represents data in a space defined by `u1=(1, 0, 0)`, `u2=(0,1,0)` and `u3=(0,2,1)`. Then I average along the first axis. Therefore I have now a 2D array that represents data along `u2=(0,1,0)`, `u3=(0,2,1)`. Normally I would represent my 2D array with a heatmap. But the problem is that in the case that `u2` and `u3` are not orthogonal, the data display is distorted (it is shown within a rectangle when it should be shown in a parallelogram). My question is if there is a way to correct that, or a good workaround. Thanks!

**Comment by pfebrer96** [comment]
> Or are you referring to another 2d plot?

So, I mean in a new 2D plot.

**Comment by empet** [comment]
No, it isn't represented like a heatmap, but as a planar surface, with surfacecolor defined by the scalar field  caracterizing your volume (values in go.Volume), restricted to that plane.

This notebook: [https://chart-studio.plotly.com/~empet/14231](https://chart-studio.plotly.com/~empet/14231) could suggest how to plot the planar surface. If you cannot  transpose this method to your non-rectangular plane, let us know, and tomorrow I'll post an example.

**Comment by pfebrer96** [comment]
Thanks! 

So there is no possible way to do this in 2D? I don't want to represent a slice of volumetric data. Since I averaged along the first axis, there isn't really a third dimension. Therefore the 3D scene makes no sense and I would have to make it look as if it  was a 2D plot (placing the camera accordingly I guess). The main problem is that this is not for an individual case, but to integrate it in a package that uses plotly to plot different things. Therefore, the user (not necessarily proficient in plotly) would have to know that it's a "fake" 2D plot to update its axes, for example. This is the main reason I would like to plot the skewed data in 2D, not inside a 3D scene.

**Comment by empet** [comment]
Well, It is possible to plot a linearly transformed heatmap, via `scipy.ndimage.interpolation.affine_transform`.
Here is the code: [https://chart-studio.plotly.com/~empet/15762](https://chart-studio.plotly.com/~empet/15762), and a few examples.
    After many experiments I concluded that it is sufficient to apply a rotation, and particular settings of the layout width and height deform  the rectangle to parallelograms.
![rot1](https://user-images.githubusercontent.com/3627253/88936195-4f3e6e00-d28b-11ea-9899-d11eda89de4a.png)
![rot-plasma](https://user-images.githubusercontent.com/3627253/88936420-92004600-d28b-11ea-806b-55c0cff22e08.png)

**Comment by empet** [comment]
Update:  To preserve the ratio between the side lengths of the transformed heatmap, set
```
yaxis_scaleanchor = "x",
yaxis_scaleratio = 1
```
These settings allow to plot both rotated and arbitrary linearly transformed heatmaps, without deforming the ratio of side lengths, even in the case when layout width and height are updated.

**Comment by pfebrer96** [comment]
This is exactly what I needed! Thank you very much :)

With that, I have all the workarounds that I needed, so you can close this issue if you want.

Cheers and I really appreciate the help!

**Comment by zxdawn** [comment]
@empet It seems the linearly transformed heatmap method can be used to get the same image of pcolormesh? I met this [issue](https://community.plotly.com/t/how-to-use-2d-coordinates-to-plot-pixels-like-heatmap/18375) three years ago, but haven't found a good solution. The plotly notebook link is 404 now. If you could provide an example, I will appreciate it a lot.
