### ISSUE TITLE
go.Scattergl draws lines outside of plot boundaries on subplots

### ISSUE THREAD

**Issue by miranska** [plotly/plotly.py#2641]
go.Scattergl draws lines outside of plot boundaries on subplots

Thank you for the great product!

Consider an example of creating multiple subplots, with a single line on each subplot. As the number of subplots increases, `go.Scattergl` draws the lines outside of the subplot boundaries. Here is an example for 50 subplots (showing the first three):
![image](https://user-images.githubusercontent.com/5458848/87591997-25941d00-c6b7-11ea-8ea3-6a65559fec66.png)

If we use `go.Scatter`, the plot is rendered correctly:
![image](https://user-images.githubusercontent.com/5458848/87591876-03020400-c6b7-11ea-876d-0f2d36b06029.png)

My environment: 
```
MacOS 10.15.5
Python 3.7.7
plotly 4.8.2
```

To reproduce, run the following:
```python
import numpy as np
import plotly.graph_objects as go
from plotly.subplots import make_subplots

plot_cnt = 50
N = 100
x = np.linspace(0, 100, N)
fig = make_subplots(rows=plot_cnt, cols=1)
fig['layout'].update(height=200 * plot_cnt)

for i in range(1, plot_cnt + 1):
    fig.add_trace(go.Scattergl(x=x, y=np.random.random(N)), i, 1)

fig.show()
```

**Comment by alexcjohnson** [comment]
There's a hard - and browser-dependent - limit to WebGL context size. Perhaps you're hitting this? See https://github.com/plotly/plotly.js/issues/4339

**Comment by miranska** [comment]
@alexcjohnson, thank you! Yes, this looks the correct root-cause. Let's hope that the WebGL component developers will relax this constraint one day.
