### ISSUE TITLE
Hiding legend titles in plotly express?

### ISSUE THREAD

**Issue by anuraghuram** [plotly/plotly.py#2644]
Hi, I have a line chart with a legend key - I want to hide the legend title, but keep the legend keys visible. Is there any way to do so? AFAIK there's only an option to fully hide the legend title + keys or display both of them. Thanks!

**Comment by nicolaskruchten** [comment]
Yep! You can delete the legend title with `fig.update_layout(legend_title_text=None)`

**Comment by anuraghuram** [comment]
Thanks! Does this work with px.line() charts where we have subplots (using the facet_row or facet_col feature)?

**Comment by nicolaskruchten** [comment]
Try it! (yes, it does :)

**Comment by anuraghuram** [comment]
Thank you!
