### ISSUE TITLE
tickcolor

### ISSUE THREAD

**Issue by yangziy** [plotly/plotly.py#2650]
### Code

According to https://plotly.com/python/reference/#layout-xaxis-tickcolor layout.xaxis.tickcolor should be effective.

```
import plotly.graph_objects as go

scatter = go.Scatter(y=[0, 1])
x_axis = go.layout.XAxis(tickcolor='red')
fig = go.Figure(data=scatter, layout=go.Layout(xaxis=x_axis))
fig.show()
```
### Expected output
Figure with red x axis ticks
### Actual output
Figure with Black x axis ticks

**Comment by nicolaskruchten** [comment]
This figure isn't displaying ticks at all (which is the default). To see the ticks you'll need to set `ticks="outside"` or something like that:

![image](https://user-images.githubusercontent.com/203523/87740079-4fc90600-c7af-11ea-85ae-ba3b481f1a99.png)

**Comment by yangziy** [comment]
Thank you for your reply.
