### ISSUE TITLE
Super Figure

### ISSUE THREAD

**Issue by M6stafa** [plotly/plotly.py#2655]
Hi. I think it is helpful that there is a super figure with next/prev button for figures, like the pic below (sorry for arrows :P)
![image](https://user-images.githubusercontent.com/7975309/87889388-9d12d500-ca46-11ea-991a-a9e441d93615.png)
I needed this feature when i try to draw each feature vs label and i had too many features. so if i draw subplot, it has a performance issue and they become very small too (i know i can zoom but the performance was the big issue), so i save them as image.
but then i think it would be nice if there was a feature like this that keeps the plots in the notebook and you can navigate through them and use helpful interactive features of Plotly too.

**Comment by nicolaskruchten** [comment]
So I actually think you can do something like this already using our "animation" feature: treat every plot as an animation frame basically.

**Comment by M6stafa** [comment]
Sorry for the late response.
I test the animations and for my case, it works. I faced a bug in VSCode-Jupyter too, that you must use `fig.show(renderer='notebook')`. If you only use `fig.show()`, animations not work and plot only shows the first frame.
I see the custom buttons too that can be used in other situations. 

But I think the Super Figure is easier to use and has better performance:
- For animation in my case, you must melt data to use it (it isn't hard for me but maybe for a scientist with the low coding capability it becomes hard), and it takes 2.5x longer time to render with animations than plot separately and save.
- my data hasn't the same scale so for each frame so I must use autoscale to see the data after changing the frame.
- If you have a different type of plot and subplots in each state, it's hard to manage with custom controls too.

If you don't agree with me, close this! Maybe I reopen it when I have time to code it myself.
Thank Plotly team for this great library, This was just my idea for this great library to becomes greater.
