### ISSUE TITLE
PX add bar_group argument like line_group 

### ISSUE THREAD

**Issue by hbaniecki** [plotly/plotly.py#2657]
There is a `line_group` argument in [px.line()](https://plotly.com/python-api-reference/generated/plotly.express.line.html) that allows for multiple lines of the same color value. 
![image](https://user-images.githubusercontent.com/32574004/88101748-bf1f6b00-cb9e-11ea-902f-1ecda2d6b4e4.png)
It would be neat to have a `bar_group` argument in [px.bar()](https://plotly.com/python-api-reference/generated/plotly.express.bar.html) performing the same action (e.g. below: 3 green bars and 3 blue bars per categorical variable level).
![image](https://user-images.githubusercontent.com/32574004/88102292-9c418680-cb9f-11ea-9a3d-e439c875b53a.png)

**Comment by nicolaskruchten** [comment]
I'm afraid I don't really understand what you're looking for here, could you expand a bit more please? It seems to me that this is the current behaviour already, no?

**Comment by hbaniecki** [comment]
Here we see that the bars stack on each other (e.g 3 values between `0` and `1` sum up to `2.5~`). Such argument could allow for 3 blue bars and 3 green bars next to each other (each with a value between `0` and `1` in this case). The 3 lines are next to each other and not stacked (sum of values?).

**Comment by hbaniecki** [comment]
Code: 
```python
import plotly.express as px
import pandas as pd
df = px.data.stocks().melt(id_vars = 'date')
df.date = pd.to_datetime(df.date)
df = df.assign(week=df.date.apply(lambda x: x.week), year=df.date.apply(lambda x: x.year))
df = df.loc[df.week.isin(list(range(2,12))), :]

px.line(df, x="week", y="value", color="variable", line_group='year')  

px.bar(df, x="week", y="value", color="variable", barmode='group')  # no bar_group means stacked barplot 
```

![image](https://user-images.githubusercontent.com/32574004/89915983-518fb900-dbf7-11ea-816e-7ad5300884b7.png)

**Comment by nicolaskruchten** [comment]
Ah, I see. Interesting. I think calling it `bar_group` would be pretty confusing actually... maybe `bar_stack` ?

**Comment by hbaniecki** [comment]
The desired output is an "unstacked" barplot relative to the above. I am not sure how the `bar_stack` correlates. I thought about `bar_group` because, in a sense, it would behave the same as `line_group`.

**Comment by nicolaskruchten** [comment]
I understand. I think it's pretty confusing with respect to `barmode="group"` however.

For this kind of data I would recommend using a faceted plot to be honest. The main reason we have `line_group` is to avoid lines being connected front-to-back, causing weird zigzags, which isn't really the case for bar charts...
