### ISSUE TITLE
Left Navbar not aligned properly

### ISSUE THREAD

**Issue by Rajwrita** [plotly/plotly.py#2666]
![Screenshot (7)](https://user-images.githubusercontent.com/47374547/88479253-628bc980-cf6b-11ea-8d09-97dce319427b.png)

**Comment by nicolaskruchten** [comment]
Can you elaborate on what's wrong in the above screenshot? It seems pretty well as intended to my eye.

**Comment by Rajwrita** [comment]
Hi Nicol, 
The bottom left of the navbar, below the Maps, is not visible. Even on scrolling down, the section remains broken.

**Comment by nicolaskruchten** [comment]
OK, I've tweaked a couple of things... Looking better now?

**Comment by Rajwrita** [comment]
Yes, perfect! :)
