### ISSUE TITLE
PX add **kwargs to plot functions

### ISSUE THREAD

**Issue by hbaniecki** [plotly/plotly.py#2667]
Consider adding `**kwargs` to `px.line()`, which then will be used in `go.Scatter`? This applies to all `px` functions.

**Comment by nicolaskruchten** [comment]
I'm pretty sure we don't want to do this, as it will likely get us into trouble later in terms of preventing us from using certain argument names. The way to do this right now is pretty terse still: `px.line(...).update_traces( <these are applied as you ask>)`.
