### ISSUE TITLE
I am getting an error as as mentioned I am using plotly 3.10.0 and i have already imported the required modules

### ISSUE THREAD

**Issue by sarthakkhare945** [plotly/plotly.py#2668]
Thanks for your interest in plotly.py!!

Help me i have attatched the code below and this is whatever the modules i have imported 

import pandas as pd
import plotly.plotly as py
import plotly.offline as po
import plotly.graph_objs as go
%matplotlib inline
po.init_notebook_mode(connected = True)
agri = pd.read_csv('214.agri(1).csv')
agri.head()
data = dict(type = 'choloropeth',  
                                                locatons = ['AL','AK','AZ','AR','CA'], 
                                               locationmode = 'USA-states'
                                                ,z = [1,2,3,40,50], 
                                               text = ['alabama','alaska','arizona','pugger','california'])

layout = dict(geo = {'scope':'usa'})
x = pg.Figure(data = [data] , layout=layout)
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-15-53ec66af1153> in <module>
----> 1 po.plot(x)
NameError: name 'x' is not defined

po.plot(x)
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-23-9514ec4f0938> in <module>
----> 1 x = pg.Figure(data = [data] , layout=layout)

NameError: name 'pg' is not defined

**Comment by nicolaskruchten** [comment]
In this case the error message seems fairly clear: there is nothing called `pg` in your environment. You are probably meaning `go.Figure` :)

**Comment by sandynoddy** [comment]
I have already tried but i didn't get the desired output thats why now i am trying to do the same thing by using chart_studio               but still error

**Comment by empet** [comment]
@sandynoddy 
With Plotly 4.9.0 (the last version) this code works:

```
import pandas as pd
import plotly.offline as po
import plotly.graph_objs as go
po.init_notebook_mode(connected = True)

data = go.Choropleth(
            locations = ['AL', 'AK', 'AZ', 'AR', 'CA'],
            locationmode = 'USA-states',
            z = [1, 2, 3, 40, 50],
            text = ['alabama', 'alaska', 'arizona', 'pugger' ,'california'])
layout = dict(geo = {'scope':'usa'})
fig = go.Figure(data, layout=layout)
po.plot(fig)
```
![map](https://user-images.githubusercontent.com/3627253/88637760-3be0a680-d0c3-11ea-8879-5d8f0e49b1e3.png)

**Comment by Shwetago** [comment]
Hey @sandynoddy!!

First of all don't use 
> import plotly.plotly as py
> import pandas as of
> %matplotlib inline
These doesn't make sense.

Second change the below line of your code:
> x = pg.Figure(data = [data] , layout=layout)

Instead of using above, use the below code:
> x = go.Figure(data, layout = layout)
> po.plot(x)

Hope this helps!!

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
