### ISSUE TITLE
plotly domain is still plotly.com in chart_studio files.py

### ISSUE THREAD

**Issue by empet** [plotly/plotly.py#2671]
Any attempt to call `chart_studio.plotly.iplot()` ends with an error, because although I changed   the `plotly_domain` to `https://chart-studio.plotly.com`, in my `.config` file, in the file `~/chart_studio/files.py`  it is set as `https://plotly.com`:
[https://github.com/plotly/plotly.py/blob/master/packages/python/chart-studio/chart_studio/files.py#L21](https://github.com/plotly/plotly.py/blob/master/packages/python/chart-studio/chart_studio/files.py#/L21).

**Comment by empet** [comment]
@nicolaskruchten  Could you, please, change plotly.com in this file, too. Thanks!

**Comment by nicolaskruchten** [comment]
Can you expand a bit on "any attempt to call `iplot()`"? This works fine for me:

![image](https://user-images.githubusercontent.com/203523/100010718-addda980-2d9e-11eb-8e08-6f2dca355dfa.png)

and my `.config` doesn't even have `chart-studio` in it:

```json
{
    "sharing": "public",
    "world_readable": true,
    "plotly_streaming_domain": "stream.plot.ly",
    "plotly_ssl_verification": true,
    "plotly_proxy_authorization": false,
    "plotly_api_domain": "https://api.plotly.com",
    "auto_open": true,
    "plotly_domain": "https://plotly.com"
}
```

**Comment by empet** [comment]
With a config file like your, I get  the following error, displayed in my notebook, instead  of the corresponding figure: `PlotlyError: Because you didn't supply a 'file_id' in the call, we're assuming you're trying to snag a figure from a url. You supplied the url, 'https://plotly.com/~empet/some_number/', we expected it to start with 'https://chart-studio.plotly.com/'. Run help on this function for more information.`  Then I changed plotly_domain to `"https://chart-studio.plotly.com"`, and the same error persisted. That's why I searched within plotly.py repo where the domain 
(in fact, the right domain), is `"https://plotly.com"` and suggested in the above filled issue to change it, because the  above error,  says explicitly: `You supplied the url, 'https://plotly.com/~empet/some_number/', we expected it to start with 'https://chart-studio.plotly.com/`.  Fortunately the plot is sent to chart studio, but  it isn't displayed in my notebook. This is an inconvenient only when I post a notebook, with a longer answer to a forum question, and the plot cannot be inserted in notebook, via `chart_studio.plotly.iplot()`

**Comment by nicolaskruchten** [comment]
Can you confirm:

1. You're running v1.1.0 of `chart-studio`?
2. With the same config file as me and the exact same code i.e. `iplot(go.Figure())` that you're seeing an error message?

If you're seeing an error message with some other code i.e. you're passing some other arguments to `iplot()` please share them so I can actually debug this. I can't just change these lines and re-release without being able to reproduce the issue you're seeing and understanding the exact mechanism :)

**Comment by empet** [comment]
Reinstalling chart-studio  fixed the issue. Thanks for assistance!!!
