### ISSUE TITLE
Option to make facet panel sizing proportional to axis range

### ISSUE THREAD

**Issue by dhimmel** [plotly/plotly.py#2675]
**Type**: python feature request
**Expands**: https://github.com/plotly/plotly_express/issues/147#issuecomment-612952746

When creating faceted plots in Python, it it possible to make the width (or height) proportional to the length of the scale?

Setting `fig.update_yaxes(matches=None)` allows the y-axes to have different values, but all panels still take up the same amount of vertical space regardless of their range.

Here's an [example notebook](https://nbviewer.jupyter.org/github/greenelab/circadian-clock-modulators/blob/a51cecf3588c06631e935fe349f7feca3efb0d04/20.plot-compounds.ipynb) where facets are all the same size and not spaced relative to x-axis range. The issue is also striking when plotting categorical variables, where one facet might have 1 category and another 100 categories. But the panel dimensions are the same for both, leading to one facet being more spaced out than the other.

The functionality would be similar to [`ggplot2::facet_grid`](https://ggplot2.tidyverse.org/reference/facet_grid.html)'s `space` argument:

> **space**
If `"fixed"`, the default, all panels have the same size. If `"free_y"` their height will be proportional to the length of the y scale; if `"free_x"` their width will be proportional to the length of the x scale; or if `"free"` both height and width will vary. This setting has no effect unless the appropriate scales also vary.

**Comment by dhimmel** [comment]
The [subplot documentation](https://plotly.com/python/subplots/#customize-subplot-column-widths-and-row-heights) contains relevant functionality:

> The `column_widths` argument to `make_subplots` can be used to customize the relative widths of the columns in a subplot grid. It should be set to a list of numbers with a length that matches the `cols` argument. These number will be normalized, so that they sum to 1, and used to compute the relative widths of the subplot grid columns. The `row_heights` argument serves the same purpose for controlling the relative heights of rows in the subplot grid.

```python
from plotly.subplots import make_subplots
fig = make_subplots(rows=1, cols=2, column_widths=[0.7, 0.3])
```

But not sure how to combine this with plot express functions that perform the faceting automatically.

**Comment by dhimmel** [comment]
Related discussion in the community forum at [Setting height/width of subplot](https://community.plotly.com/t/setting-height-width-of-subplot/1861/7).

**Comment by nicolaskruchten** [comment]
This is a good idea, but probably very challenging to implement unfortunately.

**Comment by Lulatsch39** [comment]
Hey @dhimmel, have you figured out a workaround for this issue?

**Comment by dhimmel** [comment]
> have you figured out a workaround for this issue?

No

**Comment by nicolaskruchten** [comment]
Unfortunately there's not really any reliable way to do this at the moment, sorry!
