### ISSUE TITLE
Adding texture to bar charts

### ISSUE THREAD

**Issue by anuraghuram** [plotly/plotly.py#2678]
> Is there a way to add diagonal/horizontal/vertical patterns to bar plots? Thank you!

**Comment by nicolaskruchten** [comment]
This isn't supported at the moment, no, but we'd be happy to work with someone to add it in to the underlying display library Plotly.js :)

**Comment by BenjaminMacNeille** [comment]
Are there alternative methods to be ADA compliant in plotly? This may be more of an ADA compliance question, but thought I would ask at least!

**Comment by nicolaskruchten** [comment]
This is now supported, as of version 5.0 :) https://plotly.com/python/pattern-hatching-texture/
