### ISSUE TITLE
Colorful error-bars in px.bar() plots

### ISSUE THREAD

**Issue by papomail** [plotly/plotly.py#2685]
Error-bars (_error_y, error_y_) in _px.bar()_ plots are drawn in black regardless of the facecolor.
It'd be great to have the option to specify the color; e.g:

```
fig=px.bar(df, x='x_vals', y='y_vals', 
                  color='color_vals', 
                  error_y='error_vals',
                  **error_y_color='color_vals'**
)
```

Thank you!!

**Comment by nicolaskruchten** [comment]
Would you be interested in changing the color of the error bars individually or all at once? The latter case can be addressed with an `update_traces()` call:

```python
import plotly.express as px

fig = px.bar(dict(a=[1,2], b=[4,5]), barmode="group", error_y=[0.5,0.5])
fig.update_traces(error_y_color="yellow")
fig.show()
```

**Comment by papomail** [comment]
I wasn't aware that you could change the 'error_y_color'. Thank you! 

Ideally the error bar would match the color of the bar; as in the box-plots.
Is there a good way of getting something like this?
<img width="349" alt="color_errorbars" src="https://user-images.githubusercontent.com/12429470/89798840-9ac30880-db24-11ea-9f27-ccd8e1d9f905.png">

Thanks for your time!





> Would you be interested in changing the color of the error bars individually or all at once? The latter case can be addressed with an `update_traces()` call:
> 
> ```python
> import plotly.express as px
> 
> fig = px.bar(dict(a=[1,2], b=[4,5]), barmode="group", error_y=[0.5,0.5])
> fig.update_traces(error_y_color="yellow")
> fig.show()
> ```

**Comment by nicolaskruchten** [comment]
Yep, you can do that with a slightly more complicated variant:

```python
import plotly.express as px

fig = px.bar(dict(a=[1,2], b=[4,5]), barmode="group", error_y=[0.5,0.5])
fig.for_each_trace(lambda t: t.update(error_y_color=t.marker.color))
fig.show()
```

**Comment by papomail** [comment]
Awesome! That's exactly what I was looking for.  
Thank you so much for taking the time and showcasing the 'each_trace' method. 
Have a great day 👍

**Comment by tlicquia** [comment]
Hi @nicolaskruchten is there a way to do this same thing with px.scatter?  I just tried and got an error back (code below) here is what the code looks like.  I'm using a continuous color scale for the markers (based on numeric variable) and would like the error bars to match instead for being black.

`
fig = px.scatter(**graph_dict)
fig.for_each_trace(lambda t: t.update(error_x_color=t.marker.color, error_y_color=t.marker.color))
`

Error message:
ValueError: Invalid value of type 'numpy.ndarray' received for the 'color' property of scatter.error_x Received value: array([2. , 2. , 2. , 2.0015 , 1.9991 , 2.0056 , 2.001981]) The 'color' property is a color and may be specified as: - A hex string (e.g. '#ff0000') - An rgb/rgba string (e.g. 'rgb(255,0,0)') - An hsl/hsla string (e.g. 'hsl(0,100%,50%)') - An hsv/hsva string (e.g. 'hsv(0,100%,100%)') - A named CSS color: aliceblue, antiquewhite, aqua, aquamarine, azure, beige, bisque, black, blanchedalmond, blue, blueviolet, brown, burlywood, cadetblue, chartreuse, chocolate, coral, cornflowerblue, cornsilk, crimson, cyan, darkblue, darkcyan, darkgoldenrod, darkgray, darkgrey, darkgreen, darkkhaki, darkmagenta, darkolivegreen, darkorange, darkorchid, darkred, darksalmon, darkseagreen, darkslateblue, darkslategray, darkslategrey, darkturquoise, darkviolet, deeppink, deepskyblue, dimgray, dimgrey, dodgerblue, firebrick, floralwhite, forestgreen, fuchsia, gainsboro, ghostwhite, gold, goldenrod, gray, grey, green, greenyellow, honeydew, hotpink, indianred, indigo, ivory, khaki, lavender, lavenderblush, lawngreen, lemonchiffon, lightblue, lightcoral, lightcyan, lightgoldenrodyellow, lightgray, lightgrey, lightgreen, lightpink, lightsalmon, lightseagreen, lightskyblue, lightslategray, lightslategrey, lightsteelblue, lightyellow, lime, limegreen, linen, magenta, maroon, mediumaquamarine, mediumblue, mediumorchid, mediumpurple, mediumseagreen, mediumslateblue, mediumspringgreen, mediumturquoise, mediumvioletred, midnightblue, mintcream, mistyrose, moccasin, navajowhite, navy, oldlace, olive, olivedrab, orange, orangered, orchid, palegoldenrod, palegreen, paleturquoise, palevioletred, papayawhip, peachpuff, peru, pink, plum, powderblue, purple, red, rosybrown, royalblue, rebeccapurple, saddlebrown, salmon, sandybrown, seagreen, seashell, sienna, silver, skyblue, slateblue, slategray, slategrey, snow, springgreen, steelblue, tan, teal, thistle, tomato, turquoise, violet, wheat, white, whitesmoke, yellow, yellowgreen

**Comment by hammad45** [comment]
@tlicquia I am facing the same issue. Were you able to find a solution for this?
