### ISSUE TITLE
slight change in surface opacity changes image completely

### ISSUE THREAD

**Issue by paddyroddy** [plotly/plotly.py#2690]
I need to adjust the opacity of a surface, so I can overlay two surfaces on top of each other (not sure how else to do that). But on a very small change from 1 to slightly below the look of the plot changes a lot.

`opacity=1`
![image](https://user-images.githubusercontent.com/15052188/89465012-5375fa00-d769-11ea-80a7-838a9e07fa72.png)

`opacity=0.99999`
![image](https://user-images.githubusercontent.com/15052188/89465026-5a047180-d769-11ea-9608-644726448902.png)

```
import numpy as np
from plotly.graph_objs import Figure, Surface

x = np.array(
    [
        [0, 0, 0, 0, 0, 0, 0, 0, 0],
        [
            7.07106781e-01,
            0.5,
            4.32978028e-17,
            -0.5,
            -7.07106781e-01,
            -0.5,
            -1.29893408e-16,
            0.5,
            7.07106781e-01,
        ],
        [
            1,
            7.07106781e-01,
            6.12323400e-17,
            -7.07106781e-01,
            -1,
            -7.07106781e-01,
            -1.83697020e-16,
            7.07106781e-01,
            1,
        ],
        [
            7.07106781e-01,
            0.5,
            4.32978028e-17,
            -0.5,
            -7.07106781e-01,
            -0.5,
            -1.29893408e-16,
            0.5,
            7.07106781e-01,
        ],
        [
            1.22464680e-16,
            8.65956056e-17,
            7.49879891e-33,
            -8.65956056e-17,
            -1.22464680e-16,
            -8.65956056e-17,
            -2.24963967e-32,
            8.65956056e-17,
            1.22464680e-16,
        ],
    ]
)
y = np.array(
    [
        [0, 0, 0, 0, 0, -0, -0, -0, 0],
        [0, 0.5, 7.07106781e-01, 0.5, 8.65956056e-17, -0.5, -7.07106781e-01, -0.5, 0],
        [
            0,
            7.07106781e-01,
            1,
            7.07106781e-01,
            1.22464680e-16,
            -7.07106781e-01,
            -1,
            -7.07106781e-01,
            0,
        ],
        [0, 0.5, 7.07106781e-01, 0.5, 8.65956056e-17, -0.5, -7.07106781e-01, -0.5, 0],
        [
            0,
            8.65956056e-17,
            1.22464680e-16,
            8.65956056e-17,
            1.49975978e-32,
            -8.65956056e-17,
            -1.22464680e-16,
            -8.65956056e-17,
            0,
        ],
    ]
)
z = np.array(
    [
        [1, 1, 1, 1, 1, 1, 1, 1, 1],
        [
            7.07106781e-01,
            7.07106781e-01,
            7.07106781e-01,
            7.07106781e-01,
            7.07106781e-01,
            7.07106781e-01,
            7.07106781e-01,
            7.07106781e-01,
            7.07106781e-01,
        ],
        [
            6.12323400e-17,
            6.12323400e-17,
            6.12323400e-17,
            6.12323400e-17,
            6.12323400e-17,
            6.12323400e-17,
            6.12323400e-17,
            6.12323400e-17,
            6.12323400e-17,
        ],
        [
            -7.07106781e-01,
            -7.07106781e-01,
            -7.07106781e-01,
            -7.07106781e-01,
            -7.07106781e-01,
            -7.07106781e-01,
            -7.07106781e-01,
            -7.07106781e-01,
            -7.07106781e-01,
        ],
        [-1, -1, -1, -1, -1, -1, -1, -1, -1],
    ]
)
data = [Surface(x=x, y=y, z=z, surfacecolor=np.ones(x.shape), opacity=0.99999)]
fig = Figure(data=data)
fig.show()
```

sorry about the numbers, they've been generated by some external library

my actual use case is like this where there are weird lines appearing on the plot by setting opacity
![image](https://user-images.githubusercontent.com/15052188/89465483-16f6ce00-d76a-11ea-91db-a05511cb3405.png)

**Comment by nicolaskruchten** [comment]
@archmoj can you comment please?

**Comment by archmoj** [comment]
@paddyroddy could you please set the opacity to 0.25 or 0.5 and share new screenshots?

**Comment by paddyroddy** [comment]
`opacity=0.5`
![image](https://user-images.githubusercontent.com/15052188/89542976-46541c00-d7f8-11ea-9c16-4ee9a921b911.png)

and in my more complicated use-case with `opacity=0.5`
![image](https://user-images.githubusercontent.com/15052188/89543254-9b902d80-d7f8-11ea-8f8d-e22f4ba7eb79.png)

**Comment by archmoj** [comment]
Here is a [demo](https://codepen.io/MojtabaSamimi/pen/zYqxGxw?editors=0010) in codepen.
Wondering if you tried using `mesh3d` instead of `surface` plot for that kind of geometry?

**Comment by archmoj** [comment]
This could possibly be fixed/improved by https://github.com/plotly/plotly.js/pull/4643.
But at the moment I don't see that PR being merged in near feature.

**Comment by paddyroddy** [comment]
> Here is a [demo](https://codepen.io/MojtabaSamimi/pen/zYqxGxw?editors=0010) in codepen.
> Wondering if you tried using `mesh3d` instead of `surface` plot for that kind of geometry?

thanks, no I haven't. My actual data is spherical (the example was low resolution) and isn't one uniform colour I have a `surfacecolor` passed to it. So not sure whether `mesh3d` would achieve the same thing

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
