### ISSUE TITLE
Not able to hide modebar in browser

### ISSUE THREAD

**Issue by tadorfer** [plotly/plotly.py#2696]
I'm embedding a plotly figure on my [Github pages](https://tadorfer.github.io/nlprot) and can't seem to make the modebar go away. I tried both the config options (displayModeBar=False) as well as hiding it with CSS, but neither method seems to work.

**Comment by nicolaskruchten** [comment]
It seems like you're using Chart Studio embeds on your page, in which case this documentation page is likely what you need: https://plotly.com/chart-studio-help/embed-graphs-in-websites/#step-8-customize-the-iframe ... basically you can add `&modebar=false` to your embed URL like this https://chart-studio.plotly.com/~tadorfer/6.embed?showlink=false&modebar=false

**Comment by tadorfer** [comment]
Amazing @nicolaskruchten - thank you so much, it works perfectly!
