### ISSUE TITLE
tickformat = ',d' results in an unexpected alignment of subplots

### ISSUE THREAD

**Issue by Brunox13** [plotly/plotly.py#2697]
### Preface
I first encountered this issue in a **JupyterLab** notebook when using a custom axes layout (_without_ using the **`make_subplots()`** function, similar to the "low-level API" examples [here](https://plotly.com/python/subplots/)). However, the reproducible examples below were produced and tested in an offline/non-interactive environment (**Spyder** IDE) using `make_subplots()`, which suggests that this issue is independent of where or how subplots are generated.

### Problem Description
When I want to change the format of the YAxis ticks to only show integers, using `tickformat = ',d'` like so:

```python
from plotly.subplots import make_subplots
import plotly.graph_objects as go

fig = make_subplots(rows = 1, cols = 7)

for i in range(7):
    fig.add_trace(go.Scatter(x = [1, 2, 3], y = [4, 5, 6]),
                  row = 1, col = i+1)

fig.update_layout(yaxis_tickformat = ',d')
    
fig.show()
```
results in an unexpected alignment of the subplot axes:

![tickformat_1](https://user-images.githubusercontent.com/45436070/89744261-3434e080-da79-11ea-8b10-9765d14ba9ea.png)

Interestingly, chosing a different `yaxis` (here `yaxis2`) for this formatting results in a slightly different layout:

```python
from plotly.subplots import make_subplots
import plotly.graph_objects as go

fig = make_subplots(rows = 1, cols = 7)

for i in range(7):
    fig.add_trace(go.Scatter(x = [1, 2, 3], y = [4, 5, 6]),
                  row = 1, col = i+1)

fig.update_layout(yaxis2_tickformat = ',d')
    
fig.show()
```
![tickformat_3](https://user-images.githubusercontent.com/45436070/89744313-b4f3dc80-da79-11ea-8bd0-6f2d99921cf3.png)

Commenting out the relevant line results in a completely normal set of axes:

```python
from plotly.subplots import make_subplots
import plotly.graph_objects as go

fig = make_subplots(rows = 1, cols = 7)

for i in range(7):
    fig.add_trace(go.Scatter(x = [1, 2, 3], y = [4, 5, 6]),
                  row = 1, col = i+1)

# fig.update_layout(yaxis_tickformat = ',d')
    
fig.show()
```
![tickformat_2](https://user-images.githubusercontent.com/45436070/89744287-6e05e700-da79-11ea-9b5e-35ccd4be0333.png)

It seems that when these plots are rendered interactively (setting `plotly.io.renderers.default = 'browser'`), further issues are introduced with panning, zooming etc.
**Is this behavior expected? Is there currently a way to format an axis to only show integers while avoiding these issues?**

**Comment by nicolaskruchten** [comment]
This seems to be an automargin bug, as setting `yaxis_automargin=False` seems to be a workaround.

The underlying bug is recorded in the Javascript project as https://github.com/plotly/plotly.js/issues/5059

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
