### ISSUE TITLE
Python plot similar to Matlab's stackedplot()

### ISSUE THREAD

**Issue by addarnr** [plotly/plotly.py#2700]
Hello,
Is there a plot function available in Python that is same as Matlab's stackedplot()?
stackedplot() in Matlab can line plot several variables with the same X axis and are stacked vertically. Additionally, there is a scope in this plot that shows the value of all variables for a given X just by moving the cursor (please see the plot below). I have been able to generate subplots in Python with no issues, however, not able to add a scope like this that shows the value of all variables by moving the cursor. Is this feature available in Python?

Thanks much for your help in advance!

![stackedplot scope2](https://user-images.githubusercontent.com/34237024/89850974-09b65680-db51-11ea-9cdc-ad2fb33c8252.png)

**Comment by nicolaskruchten** [comment]
There is currently no way to get hoverlabels across subplots, unfortunately.

**Comment by emmanuelle** [comment]
https://github.com/plotly/plotly.js/issues/4755 is related to this issue.

**Comment by addarnr** [comment]
The solution for this issue is at the link below.
https://stackoverflow.com/questions/63358465/scope-in-python-subplot-similar-to-matlabs-stackedplot
