### ISSUE TITLE
Officially expose `figure_factory._dendrogram._Dendrogram`

### ISSUE THREAD

**Issue by nicholas-esterer** [plotly/plotly.py#2701]
If users want to use `_Dendrogram` it is possible but some projects' linters complain and don't pass integration tests. It's true that directives can be used in these cases to turn off the linter temporarily, but then it's still not really safe to depend on a protected member.
The reason for using `_Dendrogram` directly would be for users wanting access to the data in the `_Dendrogram.data` field, for example to combine with other traces. An example using this is `dashbio.Clustergram`, where it combines a heatmap with a dendrogram.

**Comment by nicolaskruchten** [comment]
Hmmm well this part of the code is really not maintained that well so I would really rather not expose it like this... for dash-bio maybe you should inline a copy of this code ?

**Comment by nicholas-esterer** [comment]
This is a possible solution, but I would prefer avoiding this because this is basically why `dashbio` was still broken after scipy changed the colormap :joy: : it also needed to be fixed and that meant maintaining the same code twice (the code wasn't exactly the same, I think written before `_Dendrogram` existed in `plotly.py`). Anyhow in that case I can also suggest that `dashbio` follow a specific `plotly.py` version where `_Dendrogram` exists and has the expected interface, (maybe?).

**Comment by nicholas-esterer** [comment]
the fix might be as simple as writing `Dendrogram=_Dendrogram` in `figure_factory/_dendrogram.py`, :hear_no_evil:

**Comment by nicolaskruchten** [comment]
>  I think written before _Dendrogram existed in plotly.py

Definitely not... it was just written by someone who didn't know about the dendrogram figure factory 👍 

Re the double-maintenance thing... this sort of thing comes up very rarely for modules like this so I'm reticent to do this. Can you not add a `# ignore-rule` comment in dash-bio for this linter thing? Seems to be the most reasonable solution: basically we are not making this public from the plotly.py end, and not committing to not breaking dash-bio or anyone else (this is the big thing for me!) and dash-bio takes on this risk.

**Comment by nicholas-esterer** [comment]
Yes in the end the ignore directive to the linter seems the best strategy.
