### ISSUE TITLE
histogram() got an unexpected keyword argument 'legend' with pandas backend

### ISSUE THREAD

**Issue by Kerybas** [plotly/plotly.py#2706]
pandas version 1.1.0
plotly version 4.9.0

The following will raise `histogram() got an unexpected keyword argument 'legend' `:
```python
import pandas as pd
pd.options.plotting.backend = "plotly"
df = pd.DataFrame()
df.hist()
```
I suggest to add `legend` in the skip list:
https://github.com/plotly/plotly.py/blob/dc9c5fdfe70367d5dc4fcdca6a0ad07125d64647/packages/python/plotly/plotly/__init__.py#L161

**Comment by nicolaskruchten** [comment]
Thanks for the bug report and suggested fix! Should be in the next version :)
