### ISSUE TITLE
Tiny bar when using Facet in plotly.express.bar

### ISSUE THREAD

**Issue by chienazazaz** [plotly/plotly.py#2707]
I'm trying to visualize gridded subplots using plotly.express. This is what I got

![image](https://user-images.githubusercontent.com/56796835/90161321-2a82e400-ddbd-11ea-8a7f-bfd794cf9e3a.png)

As in the picture, the bar on each subplot is too small to see.
This is the expected result

![image](https://user-images.githubusercontent.com/56796835/90161496-61f19080-ddbd-11ea-881a-250fc1cda87e.png)

Using the same code, the tutorial that I follow has a large difference in the size of the bar. Is there any solution that helps me to achieve what is expected?

**Comment by nicolaskruchten** [comment]
Can you please share a link to the tutorial and/or the dataset you're working with?

I suspect your tutorial was written before `plotly` version 4.8 came out, which has slightly different logic when one of `x` or `y` is unspecified, and you may want to specify `y=px.Constant("some value")` here

**Comment by chienazazaz** [comment]
> Can you please share a link to the tutorial and/or the dataset you're working with?
> 
> I suspect your tutorial was written before `plotly` version 4.8 came out, which has slightly different logic when one of `x` or `y` is unspecified, and you may want to specify `y=px.Constant("some value")` here

Here is the link to the tutorial, in this we work on plotly.express.data.gapminder dataset
https://towardsdatascience.com/create-effective-data-visualizations-of-proportions-94b69ad34410
