### ISSUE TITLE
textposition='auto' not showing zero values

### ISSUE THREAD

**Issue by DrMaphuse** [plotly/plotly.py#2709]
In a barchart, when the textposition is set to 'auto', I get the following result:
![grafik](https://user-images.githubusercontent.com/41578390/90247415-cb61b580-de36-11ea-8a17-1a8cf72a0463.png)
However, when I set it to 'outside', the zero value will actually show up:
![grafik](https://user-images.githubusercontent.com/41578390/90247319-9c4b4400-de36-11ea-95de-b6e42dff6d39.png)
This seems inconsistent, as the auto-option suggests automatic placement of the text, not removal of the text.

**Comment by alexcjohnson** [comment]
Let's follow up in https://github.com/plotly/plotly.js/issues/6474 - thanks @AaronStiff!
