### ISSUE TITLE
Datashader and Mapbox - Projection issues?

### ISSUE THREAD

**Issue by jcfbeardsley** [plotly/plotly.py#2710]
Also posted in Plotly Community at https://community.plotly.com/t/datashader-and-mapbox-projection-issues/43812

Hi team,

Using the Datashader example [here](https://plotly.com/python/datashader/), I’ve managed to write a small script that will extract temperature from a given NetCDF file and create Datashader polygons for plotting on a Mapbox (see below). I’ve opted for Datashader polygons due to the volume of points and performance limitations with Choroplethmapbox.

The script runs successfully, but I’m finding issues with the projected location of the Datashader image when rendered. The original dataset is in EPSG 4326, and when plotted using Scattermapbox or Choroplethmapbox, the points are in the correct locations (i.e. the ocean relative to the coastline). However, the Datashader image is suffering distortions in part of the image, as you’ll see from the mismatch between the Datashader and Scattermapbox results below. The coordinates appear to line up okay in the south-west and north-east corners of the grid, but are distorted in the north-west, south-east and central parts (differing by approx 3 grid cells in the Y direction). The Datashader polygons should be overlapping with all those points shown from Scattermapbox.

![image](https://user-images.githubusercontent.com/63836041/90361595-f734a380-e0a1-11ea-8f6b-fb58edc2e573.png)

![image](https://user-images.githubusercontent.com/63836041/90361565-e4ba6a00-e0a1-11ea-83cc-a09f2d89a537.png)

Given that there is nothing wrong with the geojson in the supplied polygon boundaries (as evidenced by plotting Choroplethmapbox in the correct location), I’m trying to get my head around what is happening in Datashader to create this distortion. Can someone please explain?

I read in [this post](https://community.plotly.com/t/datashader-image-distorted-when-passed-to-mapbox/39375) that all Datashader data should be in EPSG 3857 for plotting with Mapbox, but in my instance that results in an even larger discrepancy. Is this simply a case of a different projection mismatch, or is something bigger going on here?

Thanks in advance.

Full script and datasets available for download here: https://github.com/jcfbeardsley/tastemp/tree/datashader

**Comment by philippjfr** [comment]
I too suspect Mapbox or whatever takes care of projecting the image is at fault here, using cartopy to project from EPSG: 4326 to EPSG: 3857 I cannot reproduce this issue.

**Comment by nicolaskruchten** [comment]
@jonmmease did you ever encounter something like this?

**Comment by jonmmease** [comment]
Yeah, as @philippjfr said, you'll need to project your input data from lat/lon coordinates (EPSG: 4326) to web Mercator coordinates (EPSG: 3857) before calling Datashader.  

The reason the scatter points show up properly is that, in this case, mapbox has the lat/lon coordinate of each point and can project them individually.  When you use an image, mapbox has the lat/lon of the corners and will project these properly, but it assumes the image itself is already stretched into web Mercator coordinates.  I think Mapbox could, in principle, do this projection itself, but it doesn't as this point.

Hope that helps!

**Comment by jcfbeardsley** [comment]
> Yeah, as @philippjfr said, you'll need to project your input data from lat/lon coordinates (EPSG: 4326) to web Mercator coordinates (EPSG: 3857) before calling Datashader.
> 
> The reason the scatter points show up properly is that, in this case, mapbox has the lat/lon coordinate of each point and can project them individually. When you use an image, mapbox has the lat/lon of the corners and will project these properly, but it assumes the image itself is already stretched into web Mercator coordinates. I think Mapbox could, in principle, do this projection itself, but it doesn't as this point.
> 
> Hope that helps!

Thanks for the insight! Would you mind taking a quick look at [this sample script](https://github.com/jcfbeardsley/tastemp/blob/datashader/datashader_demo.py) and telling me where I've gone wrong? I'd read about this before posting and had included a boolean flag in my code to reproject the geodataframe from 4326 to 3857 prior to calling datashader (currently set to false in the checked in code), but in my instance the resulting

**Comment by jcfbeardsley** [comment]
> Yeah, as @philippjfr said, you'll need to project your input data from lat/lon coordinates (EPSG: 4326) to web Mercator coordinates (EPSG: 3857) before calling Datashader.
> 
> The reason the scatter points show up properly is that, in this case, mapbox has the lat/lon coordinate of each point and can project them individually. When you use an image, mapbox has the lat/lon of the corners and will project these properly, but it assumes the image itself is already stretched into web Mercator coordinates. I think Mapbox could, in principle, do this projection itself, but it doesn't as this point.
> 
> Hope that helps!

Fantastic, thanks for the insight.
