### ISSUE TITLE
Restore python-3-5-orca build step?

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.py#2714]
I've just disabled the newly-mysteriously-failing `python-3-5-orca` build step in b78a1a8fb30ffa1df9b0c49d05431abef4b4dedf ... should we spend time bringing it back?

@jonmmease @emmanuelle  thoughts?

**Comment by nicholas-esterer** [comment]
Error seems to arrive with new `parso` version 0.8.0
https://anaconda.org/anaconda/parso

**Comment by nicolaskruchten** [comment]
we should close this once the 3.5-drop is complete #3158
