### ISSUE TITLE
Hovertext bug using discrete colour data on stacked bar chart with customdata

### ISSUE THREAD

**Issue by amarkham09** [plotly/plotly.py#2716]
I have a Pandas DataFrame, `df` which I am using to populate a Plotly bar chart. For the sake of example, let's define `df` as the following:

```
import pandas, numpy
import plotly.express as px

df = pandas.DataFrame.from_dict(
    {
        "x": ["John Cleese", "Eric Idle", "Michael Palin", "Eric Idle"],
        "y": [7, 10, 3, 8],
        "colour": ["0", "0", "0", "1"],
        "a": [1, 2, 3, 4],
        "b": [1, 4, 9, 16],
        "c": [1, 8, 27, 64]
    }
)
```

And create a bar chart derived from these data
```
fig = px.bar(df, x="x", y="y", color="colour", barmode="stack")

my_customdata = numpy.transpose(numpy.array([df["a"], df["b"], df["c"]]))

fig = fig.update_traces(
    patch={
        "customdata": my_customdata,
        "hovertemplate": "x: %{x}, y: %{y}, a: %{customdata[0]}, b: %{customdata[1]}, c: %{customdata[2]}<extra></extra>"
    },
    overwrite=True
)
fig.update_layout(
    xaxis={"categoryorder": "total ascending"}
)
fig.show()
```
The bug arises in the hover text for the red stacked bar. You'll notice that the `x` and `y` data in the hover text are correct, but the data arising from the `customdata` are not!

![Discrete colour data produces bug](https://user-images.githubusercontent.com/68236897/90559970-5378ef80-e196-11ea-909e-1232b292b2fb.png)

Intriguingly, this bug only occurs when the `Pandas.Series` object passed to the `color` argument of `px.bar()` consists of string data (i.e. discrete colour data). If in the code above I instead set `df.colour = [0, 0, 0, 1]` (using integers for continuous colour data, notice the colorbar), the following graph is created:

![No bug when the colour data is continuous](https://user-images.githubusercontent.com/68236897/90560012-6095de80-e196-11ea-8a14-2c95b4973d7a.png)

I would try and fix this myself via a pull request, but I'm struggling to get my head round the architecture of the module (esp. how it integrates with JS).

I have additionally reported this bug [on StackOverflow](https://stackoverflow.com/questions/63472524/plotly-py-bug-using-discrete-colour-data-on-stacked-bar-chart-with-customdata-in) and [community.plotly.com](https://community.plotly.com/t/bug-using-bar-chart-categoryorder-and-customdata/43925?fbclid=IwAR2yKnSgedDjDmIGe3vhd8GPiQ_DFFAGephrq6G4Wl80iJST3Psn6kkzIs8)

**Comment by amarkham09** [comment]
It turns out the solution was relatively simple, and was my fault rather than being an issue with the source code itself (oh, the hubris of thinking that it wasn't my fault!)

### The reason my code breaks
On running `px.bar()`, `plotly.express` creates a `plotly.graph_objs.Figure` object which contains *two* `Bar` objects, not one. Then, when `fig.update_traces()` is called, the `customdata` is applied to *all* of the `Bar` objects which are children of `fig`. Red Eric Idle is the 4th value of the original DataFrame, but `fig.update_traces()` doesn't care where Red Eric Idle _used_ to be - it only understands that now it's part of a second `Bar` object. In fact, Red Eric Idle is the first datapoint of this `Bar` object, and so merrily assigns creates hovertext data using `customdata[0][n]`, `customdata[1][n]`, `customdata[2][n]`, with `n=0` (the first value), rather than with `n=3` (the fourth value) as I expected.

_This_ is why the hover text for Red Eric Idle contains `"a: 1, b: 1, c: 1"`, rather than `"a: 4, b: 16:, c: 64"`.

### The solution
The solution is very straightforward. Since the Plotly figure "forgets" where in the original DataFrame each point's data was supposed to go after it finishes running `px.bar()`, we simply have to assign custom data to each datapoint _before_ it forgets (i.e. during the `px.bar()` call. Simply replace
```
fig = px.bar(df, x="x", y="y", color="colour", barmode="stack")
my_customdata = numpy.transpose(numpy.array([df["a"], df["b"], df["c"]]))
fig = fig.update_traces(
    patch={
        "customdata": my_customdata,
        "hovertemplate": "x: %{x}, y: %{y}, a: %{customdata[0]}, b: %{customdata[1]}, c: %{customdata[2]}<extra></extra>"
    },
    overwrite=True
)
```
with
```
fig = px.bar(
    df, x="x", y="y", color="colour", barmode="stack", custom_data=["a", "b", "c"]
)
fig = fig.update_traces(
    patch={
        "hovertemplate": "x: %{x}, y: %{y}, a: %{customdata[0]}, b: %{customdata[1]}, c: %{customdata[2]}"
    },
    overwrite=True
)
```
Hey presto, Red Eric Idle suddenly has hover text with the `4, 16, 64` rather than `1, 1, 1`:

![Screenshot 2020-08-18 at 21 55 17](https://user-images.githubusercontent.com/68236897/90564650-a30ee980-e19d-11ea-9a02-e14ac00abf40.png)
This is also neater code in the first place. It wasn't obvious to me in the original Plotly example documentation that `custom_data` could be assigned like this within the `plotly.express` module.

### Why this didn't happen for continuous colour data
But why does this strange behaviour go away when we set `df.colour = [0, 0, 0, 1]`?

The reason is that when `px.bar()` is passed continuous colour data, it only creates one `Bar` object per figure. In this case, every datapoint in `Bar` remembers its row position in the DataFrame, and so the assignment of `customdata` works like a charm.

**Comment by nicolaskruchten** [comment]
You've figured it out, yes! Basically Plotly Express takes care of splitting your data into multiple traces if needed, so the best way to use `customdata` is to give that to PX and let it split for you rather than trying to "bolt it on" after the fact.

Note that PX will in fact create multiple traces even with continuous color, e.g. if you use the `facet_row` or `facet_col` or `animation_frame` arguments so in general it's best to pass custom data from the original PX call in all cases ;)

**Comment by nicolaskruchten** [comment]
PS: thanks for the original, very detailed and clear issue! :)

**Comment by amarkham09** [comment]
>  so the best way to use customdata is to give that to PX and let it split for you rather than trying to "bolt it on" after the fact.

It might be useful for beginners to make this more prominent in the docs, i.e. featuring an example of using the `custom_data` option within `plotly.express.bar`, perhaps analagous to [this](https://plotly.com/python/bar-charts/#bar-chart-with-hover-text) but featuring a custom `hovertemplate`? I'd be happy to contribute to this.

**Comment by nicolaskruchten** [comment]
Hmm if you want to insert custom data mostly for the purposes of hovertemplate I would recommend using the hover_data argument of most PX functions instead, as it lets you specify the name and formatting for individual hover data attributes. If then you want to override the template you still can.

This might be a nice doc example in here: https://plotly.com/python/hover-text-and-formatting/
