### ISSUE TITLE
[Bug] Hovertemplate not persisted after animation

### ISSUE THREAD

**Issue by ogelin** [plotly/plotly.py#2722]
I've noticed this issue using Plotly with Dash & also reproduced in my own Jupyter notebook. 

Here is a code sample reproducing the issue : 

```
import plotly.express as px
df = px.data.gapminder()

fig = px.scatter(df, x="gdpPercap", y="lifeExp",
	         size="pop", color="continent", animation_frame='year', animation_group='country',
                 hover_name="country", log_x=True, size_max=60)

fig.update_traces(
        hovertemplate='<span>hi!!</span>',
    )

fig.show()
```

When the figure is initially loaded, the tooltips show my custom hover template. After the animation, my hover template is no longer in use and the tooltips show their initial content (i.e. the property names followed by an equal sign & their value).

**Before animation:**
![image](https://user-images.githubusercontent.com/16294757/91052047-eb3f6900-e5ee-11ea-93a7-1142363878ec.png)

**After animation:**
![image](https://user-images.githubusercontent.com/16294757/91051993-da8ef300-e5ee-11ea-9a62-1e3a00ca6137.png)

**Comment by nicolaskruchten** [comment]
This is indeed surprising and annoying, but `update_traces` doesn't update traces in the animation frames at the moment, although it probably should! To do this today you will need to iterate across the traces in `fig.frames` and set the hovertemplate manually.

**Comment by MaxGhenis** [comment]
>To do this today you will need to iterate across the traces in fig.frames and set the hovertemplate manually.

Could you give an example? I don't see anything that distinguishes `fig.frames[0]` (which shows the updated hovertemplate) and `fig.frames[1]`. Both have customdata and the default (incorrect) `hovertemplate`. I'm using `px.choropleth`.

**Comment by DaniloSI** [comment]
> Thanks @nicolaskruchten, this worked for me:
> 
> ```
> CUSTOM_HOVERTEMPLATE = "<b>%{customdata[0]}</b><br>%{customdata[1]}<br>%{customdata[2]}"
> fig.update_traces(hovertemplate=CUSTOM_HOVERTEMPLATE)
> for frame in fig.frames:
>     frame.data[0].hovertemplate = CUSTOM_HOVERTEMPLATE
> ```

This works for me too. But, I needed to iterate through frame.data.

My code looked like this:

```
fig.update_traces(hovertemplate=CUSTOM_HOVERTEMPLATE)

for frame in fig.frames:
    for data in frame.data:
        data.hovertemplate = CUSTOM_HOVERTEMPLATE
```

**Comment by chriscampana** [comment]
I unfortunately cannot get either of these two workarounds to work using a choropleth or a choropleth_mapbox.  Any advice ?

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
