### ISSUE TITLE
Implementation of fig.close() or px.close(fig) similar to matplotlib.pyplot.close()

### ISSUE THREAD

**Issue by indiana-nikel** [plotly/plotly.py#2725]
Hello,

I have a use case where I am attempting to plot a large amount of data in a Jupyter environment using Plotly (express to be specific). If I attempt to plot more than a few plots at a time in the same notebook, the notebook crashes due to the large use of memory. There are workarounds here (ie. sample your data, comment out the charts you don't want to see). However, for my use case, I wouldn't want to remove data quite yet or hunt in my notebook for the chart eating up memory. I would rather a method that could close a plot (or plots) created earlier.

It would be useful to have a method similar to `matplotlib.pyplot.close()` [https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.pyplot.close.html#](https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.pyplot.close.html#) where we could close a chart created earlier in a notebook.

```
# Example implementation

import plotly.express as px

fig1 = px.scatter(
    ....
)
fig1.show()

# Later in the notebook

fig.close()
## or
px.close(fig=fig1)

```

**Comment by NEGU93** [comment]
Not sure if this post helps about [Deleting Plots in Python](https://plotly.com/python/delete-plots/).

Although I agree this must be implemented.

**Comment by DavidMendes91** [comment]
Yup, needing this too

**Comment by nicolaskruchten** [comment]
Unfortunately, this is not something that can be done from Python... The excess memory in use is mostly in the Jupyter frontend so the thing to do here is comment out the `fig.show()` calls and rerun the offending cells to clear out the Jupyter output.

**Comment by disouzam** [comment]
> Not sure if this post helps about [Deleting Plots in Python](https://plotly.com/python/delete-plots/).
> 
> Although I agree this must be implemented.

Hi, @NEGU93 :

Link is not working anymore in 2026. Any direction on where to find the relevant information?

Thanks in advance!
