### ISSUE TITLE
fig.show() doesn't provide an output and i don't know why

### ISSUE THREAD

**Issue by Efezino-E** [plotly/plotly.py#2742]
![Annotation 2020-](https://user-images.githubusercontent.com/68451305/91937700-63daaf80-ecea-11ea-8a85-701252f1e838.png)

When i **import** plotly.express **as** px and use the _px.scatter_ to create a fig. if i then use fig.show(), i get no output and i don't know why.

**Comment by JanHomann** [comment]
I am having the same issue. Several, conda environments, all relatively recent, but not all, all the necessary modules / extensions installed. Nothing shows up anywhere. It used to work.

**Comment by Shwetago** [comment]
Use plotly.offline. It works for me.

**Comment by JanHomann** [comment]
> Use plotly.offline. It works for me.

Not for inline figures in my case. Only figures that pop up in the browser.

**Comment by Shwetago** [comment]
Did you check here: https://plotly.com/python/renderers/

**Comment by Efezino-E** [comment]
> Did you check here: https://plotly.com/python/renderers/

this really helped a lot thank you!!

**Comment by Shwetago** [comment]
> this really helped a lot thank you!!

Glad to know it helped!! @Efezino-E 
You can close the issue now.
