### ISSUE TITLE
Google Colab static image export with Kaleido error

### ISSUE THREAD

**Issue by rr5577** [plotly/plotly.py#2744]
I wanted to try and export a plot as static image from a google colab notebook using kaleido, but it doesn´t seem to work even though I think the requirements from the plotly documentation are met:
![image](https://user-images.githubusercontent.com/31547476/92106903-49393100-ede5-11ea-944e-0205f5ba4b3c.png)

![image](https://user-images.githubusercontent.com/31547476/92107028-6ec63a80-ede5-11ea-8834-d11456517c89.png)

**Comment by Shwetago** [comment]
Try to rerun notebook after restarting the session if you have kaleido installed.!!

**Comment by rr5577** [comment]
Yes, that fixed it, thank you!
