### ISSUE TITLE
jupyter html

### ISSUE THREAD

**Issue by aierides** [plotly/plotly.py#2748]
Having issues exporting html document with interactive plotly plots. They don't show up in HTML at all.

**Comment by Shwetago** [comment]
> Having issues exporting html document with interactive plotly plots. They don't show up in HTML at all.
> 

Can you show us your source code?

**Comment by Tamoghna-Saha** [comment]
In the importing section, in the end, add this.

```
import plotly.io as pio
pio.renderers.default = "notebook"
```

**Comment by Shwetago** [comment]
Check out this link!
https://plotly.com/python/embedding-plotly-graphs-in-HTML/
Hope this helps!! @aierides
