### ISSUE TITLE
Link is broken!!

### ISSUE THREAD

**Issue by Shwetago** [plotly/plotly.py#2750]
Kaggle kernels link is broken in displaying figures module.

**Comment by nicolaskruchten** [comment]
Can you provide more details about what you mean here? is there a page in our documentation with a broken link?

**Comment by Shwetago** [comment]
In the official website, this is the link 
https://plotly.com/python/renderers/
 
Under the interactive renderers, there is a Kaggle kernels link and that link is not working.

**Comment by nicolaskruchten** [comment]
Ok, thanks for the clarification!

**Comment by Shwetago** [comment]
Hey @nicolaskruchten,

Did you resolve it? If not, Can you assign this to me?

**Comment by nicolaskruchten** [comment]
We'd happily accept a PR if you want to fix this, yes!

**Comment by Shwetago** [comment]
Just fixed it!! Waiting for review!
