### ISSUE TITLE
Feature to arrange categorical legend keys in alphabetical order?

### ISSUE THREAD

**Issue by anuraghuram** [plotly/plotly.py#2763]

**Comment by Shwetago** [comment]
Can you elaborate?

**Comment by nicolaskruchten** [comment]
The legend appears in the order the traces appear in the `data` array, so if creating traces manually with graph_objects that's how you can control it. If using Plotly Express then the `categorical_orders` keyword argument lets you control the trace and therefore legend order :)

**Comment by anuraghuram** [comment]
@nicolaskruchten thanks for clarifying!
