### ISSUE TITLE
Sankey with misplaced nodes

### ISSUE THREAD

**Issue by Nemecsek** [plotly/plotly.py#2770]
**Plotly 4.10.0, Python 3.8.0 on Ubuntu 20.04**

I am trying all on Jupyter Lab, and I found out the issue while using Plotly 4.9.0. After updating to the latest 4.10.0, nothing changed even if on Stackoverflow somebody told me that 4.10.0 doesn't produce the issue. 
Is there the possibility that Jupyter Lab reload a cached 4.9.0 while telling me that the installed one is 4.10.0?!?

This code produce properly placed nodes: 
```
import plotly.graph_objects as go

sources = [ 0,  0,  1,  1,  2,  2]
targets = [ 1,  2,  3,  4,  5,  6]
values  = [46, 30, 16, 30, 20, 10]
labels = ['Node 0', 'Node 1', 'Node 2', 'Node 3', 'Node 4', 'Node 5', 'Node 6']

link = dict(source=sources, target=targets, value=values)
node = dict(label=labels)
data = go.Sankey(link=link, node=node)
fig = go.Figure(data)
fig.show(renderer="svg", width=1000, height=500)   # for jupyter lab 
```

Changing values to `values  = [45, 30, 15, 30, 20, 10]` nodes change position in a wrong way. [Images here](https://stackoverflow.com/questions/63886267/plotly-sankey-why-are-nodes-misplaced).

Changing node_pad value to 9 solves the issue. With 10 it is back again: 
`data = go.Sankey(link=link, node=node, node_pad=9)`

**Comment by Shwetago** [comment]
node_pad will definitely help because it is used to define the padding between the nodes.
To avoid overlapping of the nodes, you need to change the values. 
Check this link: https://plotly.com/python/sankey-diagram/

**Comment by Nemecsek** [comment]
As the generation is unsupervised, it shouldn't be necessary to change `note_pad` manually. As you can see in my [Stackoverflow's post](https://stackoverflow.com/questions/63886267/plotly-sankey-why-are-nodes-misplaced), I already pinpointed note_pad as a possible culprit. 

My question here is more related to Jupyter Lab: is it possible that even if the python side is using the newest 4.10.0 (I can confirm the version), the javascript is 4.9.0 instead? This would explain why other users don't see the problem.

**Comment by Shwetago** [comment]
It can be a possibility!!

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
