### ISSUE TITLE
Multi-layered animated filled scatterplot displays strange transition behaviour

### ISSUE THREAD

**Issue by doughagey** [plotly/plotly.py#2775]
Hi,

I'm seeing a strange transition problem with my multi-layered, filled animated scatterplot. When the filled shapes adjust they rotate wildly before settling in their final destination. Here is a video of the problem: 

[https://drive.google.com/file/d/1djq59xJpR3yz7CYwyB52yujrrtDgs6ZD/view?usp=sharing](url)

I'm using the latest Plotly version for Python available via Anaconda (4.9). The individual markers for the filled scatterplots are ordered by their convex hull order. This order does change as the animation evolves but the animation rendering seems to get confused as to how to plot it and it rotates until eventually settling. 

Code snippet:

`
   fig = px.scatter(df, x="X", y="Y", color="Team", hover_name="NickName", animation_frame="GameTime",
                 animation_group="NickName", range_x=[-4,110], range_y=[-4,72], size='size', size_max=9,
                 width=900, height=700, color_discrete_map=color_discrete_map,
                 hover_data={'X': False,'Y':False,'GameTime':False,'size':False, 'Team':False, 'Position':False})

    frames_convex_team1 = [go.Frame(
                            data=[go.Scatter(
                            x=group['hull_x'],
                            y=group['hull_y'],
                            mode="lines",
                            marker=dict(color="gray", size=0),
                            fill="toself",
                            opacity=.25,
                            name = "C-Hull 1")
                        ]) for name, group in grouped_convex_hull_team1]

    frames_convex_team2 = [go.Frame(
                            data=[go.Scatter(
                            x=group['hull_x'],
                            y=group['hull_y'],
                            mode="lines",
                            marker=dict(color='green', size=0),
                            fill="toself",
                            opacity=.50,
                            name = "C-Hull 2")
                        ]) for name, group in grouped_convex_hull_team2]

    fig2 = go.Figure(data=go.Scatter(mode='lines',fill='toself'),
                    layout=go.Layout(width=900, height=700,
                         xaxis=dict(range=[-4, 110], autorange=False, zeroline=False),
                         yaxis=dict(range=[-4, 72], autorange=False, zeroline=False),
                         hovermode="closest",
                         transition={'duration': 0, 'easing': 'linear'},
                         ),
                    frames= frames_convex_team1
    )

    fig3 = go.Figure(data=go.Scatter(mode='lines',fill='toself'),
                    layout=go.Layout(width=900, height=700,
                         xaxis=dict(range=[-4, 110], autorange=False, zeroline=False),
                         yaxis=dict(range=[-4, 72], autorange=False, zeroline=False),
                         hovermode="closest",
                         transition={'duration': 0, 'easing': 'linear'},
                         ),
                    frames= frames_convex_team2
    )

    fig.add_trace(fig2.data[0])
    for i, frame in enumerate(fig.frames):
        fig.frames[i].data += (fig2.frames[i].data[0],)

    fig.add_trace(fig3.data[0])
    for i, frame in enumerate(fig.frames):
        fig.frames[i].data += (fig3.frames[i].data[0],)
`

The same thing happens if I use purely Plotly Express as follows with three separate px plots.

If I've configured something wrong please let me know. But, I should note that when plotting this same exact data in an animated fashion on Tableau, the problem does not occur (but it is noticeably more sluggish in its animation, hence why I'd rather get this working in Plotly). The sports analytics community would likely be very grateful to have this display/rendering/transition issue resolved and I would share it with them at that point. Thanks!

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
