### ISSUE TITLE
Surface plots with opacity < 1 not rendering in Safari 14

### ISSUE THREAD

**Issue by daanreijnders** [plotly/plotly.py#2777]
My 3D surface plots with opacity lower than 1 do not render anymore in Safari 14 (just updated from Safari 13). 

Take this minimal example (almost equal to [this one on Plotly's website](https://plotly.com/python/3d-surface-plots/), except for the opacity):
```python
import plotly.graph_objects as go

import pandas as pd

# Read data from a csv
z_data = pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/api_docs/mt_bruno_elevation.csv')

fig = go.Figure(data=[go.Surface(z=z_data.values, opacity=0.5)])
fig.update_layout(title='Mt Bruno Elevation', autosize=False,
                  width=500, height=500,
                  margin=dict(l=65, r=50, b=65, t=90))

fig.show()
```
In Safari (Version 14.0 (14610.1.28.1.9)) this is rendered as:
![Unknown](https://user-images.githubusercontent.com/9340879/93487952-170bf100-f906-11ea-9e34-dfd16834b339.png)

In Chrome (v85.0.4183.102), it's properly rendered: 
![newplot](https://user-images.githubusercontent.com/9340879/93487878-03608a80-f906-11ea-80e5-05bd7829ac94.png)

I'm wondering whether this is something that can be fixed on Plotly's side, or whether it's a bug in the new Safari that Apple needs to address. 

For completeness, Safari's console logs this error:
`[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (individual-plots.json, line 0)`

**Comment by nonhermitian** [comment]
I can confirm that I see this as well:

```python

import numpy as np
import plotly.graph_objects as go

u = np.linspace(0, 2*np.pi, 100)
v = np.linspace(0, 2*np.pi, 100)
x = np.outer(np.cos(u), np.sin(v))
y = np.outer(np.sin(u), np.sin(v))
z = np.outer(np.ones(np.size(u)), np.cos(v))

color="black"
opacity = 0.99 # Set to 1.0 for a black sphere

fig = go.Figure()


fig.add_trace(go.Surface(x=x, y=y, z=z,
                         opacity=opacity,
                         showscale=False,
                         hoverinfo='skip',
                         colorscale=[[0, color],
                                     [1, color]],
                         contours=dict(
                             x=dict(highlight=False),
                             y=dict(highlight=False),
                             z=dict(highlight=False))
                         ))
fig
```

<img width="484" alt="Screen Shot 2020-10-02 at 10 35 13" src="https://user-images.githubusercontent.com/1249193/94935399-05e0e980-049b-11eb-93fd-400c2809273a.png">

**Comment by roozmahdavian** [comment]
+1, seeing an issue identical to @nonhermitian's

**Comment by nicolaskruchten** [comment]
@archmoj can you take a look please?

**Comment by RFQED** [comment]
Is there a plan to address this?

**Comment by rben01** [comment]
I think this is a new issue in Big Sur -- if my memory serves me, opacities less than 1 worked fine in Catalina.

**Comment by rben01** [comment]
This should be closed in favor of https://github.com/plotly/plotly.js/issues/5158

**Comment by archmoj** [comment]
This is addressed in [plotly.js v1.58.4](https://github.com/plotly/plotly.js/releases/tag/v1.58.4).
