### ISSUE TITLE
Generate a docset for Zeal/Dash

### ISSUE THREAD

**Issue by raghavmallampalli** [plotly/plotly.py#2778]
FEATURE REQUEST

Would it be possible to generate a docset for plotly for the [Dash/Zeal](https://zealdocs.org) offline docset viewing platform? The procedure is described [here](https://kapeli.com/docsets) and is supposed to be quite simple.

**Comment by nicolaskruchten** [comment]
This is a good idea but not something the maintainers have any bandwidth for at the moment... That said, this is probably something someone from the community could maintained a satellite project :) 

The documentation source code is in the `doc` directory as is the makefile that converts it into HTML suitable for embedding within the plotly.com/python CMS.

**Comment by raghavmallampalli** [comment]
If the developer team generates the docset it can be made natively available in the program. That being said, user-contributed docsets are not very difficult to load up. If anyone is willing to make the docset [this](https://github.com/nim-lang/Nim/issues/1401) thread may be useful to them.

**Comment by nicolaskruchten** [comment]
Cool. I can't commit to keeping any "official" docset up to date at the moment beyond what's at plotly.com/python, so it seems like a community-maintained one is the right way to go here :)

**Comment by yimingli** [comment]
I tried it but ran into multiple issues building the API doc. https://github.com/plotly/plotly.py/issues/3543

I was wondering if I could download the api doc html files somewhere (something like [scikit-learn](https://scikit-learn.org/dev/versions.html)), and I could try to convert it into a dash docset.

**Comment by rabyj** [comment]
Also ran into issues trying to create offline API doc with `doc2dash 3.0.0` on `Ubuntu 20.04` https://github.com/plotly/plotly.py/issues/2060, spent a few hours on the whole ordeal on it and gave up. I was able to run `make html` but the result was not directly compatible with `doc2dash`, it seems.

It would be incredibly neat if someone could figure out how to create a docset, `doc2dash` **should** make the process simpler, in theory. It would enable having a streamlined offline documentation build.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Alternatively, if it's a request for tech support, please post in our community forum. Thank you - @gvwilson

**Comment by specter119** [comment]
> Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Alternatively, if it's a request for tech support, please post in our community forum. Thank you - 嗨 - 我们正在尝试整理 Plotly 公共存储库中的陈旧问题和 PR，以便我们可以专注于对我们社区仍然很重要的事情。由于这个已经坐了一段时间，我要关闭它;如果仍然是一个问题，请添加评论，让我们知道您已经检查了我们软件的最新版本，以便我可以重新打开它并将其添加到我们的积压工作中。或者，如果是技术支持请求，请在我们的社区论坛中发帖。谢谢-@gvwilson

I think it's still an issue, since web document is not quite stable in my side.

**Comment by carlocastoldi** [comment]
I confirm this is still an issue that I wish it was kept open for discussion.
On the other hand, if you, as developers, don't plan to ever work on this issue I understand and in that case I think it can be kept close.

Anyways, I don't understand why issues should be closed for being "stale".
