### ISSUE TITLE
Annotated heatmap bug when some x can be casted as int

### ISSUE THREAD

**Issue by bensdm** [plotly/plotly.py#2782]
There is a display bug when some x element can be casted as int:

`import plotly.figure_factory as ff
ff.create_annotated_heatmap(np.random.rand(3,3), x=['2019', '2020', 'total'], y=[1,2,3])`
![image](https://user-images.githubusercontent.com/29406515/93775747-171c3180-fc23-11ea-9f02-e951ed269d31.png)
works fine adding a underscore
`ff.create_annotated_heatmap(np.random.rand(3,3), x=['2019_', '2020_', 'total'], y=[1,2,3])`
![image](https://user-images.githubusercontent.com/29406515/93775826-2d29f200-fc23-11ea-90d8-f108ef3b260c.png)

**Comment by empet** [comment]
This issue is generated by the non-uniform x-values: two ints as strings and and the string `total`.
A solution to display your initial xaxis labels is as folows:
```
import plotly.figure_factory as ff 
fig =ff.create_annotated_heatmap(z=np.random.rand(3,3), x=['2019', '2020', '2021'], y=[1,2,3])
fig.update_xaxes(tickvals=[2019, 2020, 2021], ticktext=['2019', '2020', 'Total'])
```

**Comment by merillium** [comment]
@empet this same issue was recently brought up on stackoverflow in [this question](https://stackoverflow.com/questions/69420578/why-is-my-annotation-text-in-python-plotly-figure-factory-getting-the-wrong-coor/69421015#69421015), and for any xvalues containing a string that can be cast as an int... your workaround can be generalized to if you pass the arguments `tickvals=list(range(len(x)))` and `ticktext=x` to `fig.update_xaxes`

I am not sure if it's necessary, but it might be nice to automatically do this in the `_annotated_heatmap.py` file in `plotly.figure_factory` whenever any x-values or y-values passed to the heatmap contain strings that can be cast as int. I would be happy to create a PR on my own branch for this feature

**Comment by gvwilson** [comment]
Hi ,
Greetings from Plotly - I started a new gig as manager of the libraries team seven weeks ago, and so far I'm feeling like the longer I'm here, the further behind I am :-) We're thinking about overhauling our charts, and our designer would be grateful for a chance to talk with a few people about what changes they'd like to see - any chance you could spare a bit of time to chat with him online?
Hope you and yours are safe and well,
Greg
