### ISSUE TITLE
Provide a link to the px reference page on every chart page

### ISSUE THREAD

**Issue by chriddyp** [plotly/plotly.py#2784]
We currently link to the graph objects reference page, but not to the px sunburst page. 

![image](https://user-images.githubusercontent.com/1280389/93829605-dc19fe00-fc22-11ea-942d-58d2e62589b8.png)

**Comment by emmanuelle** [comment]
For interested contributors, the px reference page is https://plotly.com/python-api-reference/plotly.express.html. Please read the Readme in https://github.com/plotly/plotly.py/tree/master/doc to learn how the doc is organized and edited.

**Comment by ry-v1** [comment]
@chriddyp @emmanuelle - I can work on this, can you please assign it to me.
Is the below format is fine.

Reference
See https://plotly.com/python/reference/sunburst/ or https://plotly.com/python-api-reference/generated/plotly.express.sunburst.html for more information and chart attribute options! 

I do see px site doesn't have documentation for all the charts like bubble, bullet and candlestick chart.

**Comment by emmanuelle** [comment]
Assigned! Yes, `plotly.express` does not have (yet) functions for all traces. You can find the list of available functions in https://plotly.com/python-api-reference/plotly.express.html. 

For the format it looks good, just put the plotly.express link first please.

**Comment by ry-v1** [comment]
Sure, will do

**Comment by nicolaskruchten** [comment]
For the PX link it might be nice to have some link text like "function reference for `px.scatter()`" instead of that big URL?

**Comment by ry-v1** [comment]
How about this?

Reference
See function reference for [px.sunburst()](https://plotly.com/python-api-reference/generated/plotly.express.sunburst) or https://plotly.com/python/reference/sunburst/ for more information and chart attribute options!

**Comment by nicolaskruchten** [comment]
I would use something like this:

> See [function reference for `px.sunburst()`](https://plotly.com/python-api-reference/generated/plotly.express.sunburst) or ...

with the following code:

```
See [function reference for `px.sunburst()`](https://plotly.com/python-api-reference/generated/plotly.express.sunburst) or ...
```

**Comment by ry-v1** [comment]
I have submitted pull request #2784. Please check.
