### ISSUE TITLE
Add Title to Table

### ISSUE THREAD

**Issue by tconnor23** [plotly/plotly.py#2795]
Is there a way to add a title to a table generated using ff.create_table?

fig.update_layout(title_text="Some title text") does not appear to work in this particular scenario

![image](https://user-images.githubusercontent.com/41125521/94309435-1565ad00-ff46-11ea-9129-e0b2d5a8cd93.png)

_note: in the screenshot, the "out" is a pandas dataframe_

**Comment by emmanuelle** [comment]
Hi @tconnor23 it should work (see attached screenshot), probably you need to [set the margins or graph size here](https://plotly.com/python/setting-graph-size/) so that the title becomes visible ?

**Comment by tconnor23** [comment]
Awesome - thank you!  I couldn't see the screenshot, but updating the margin worked.

![image](https://user-images.githubusercontent.com/41125521/94818688-635a3500-03cc-11eb-8805-182df8bd511d.png)
