### ISSUE TITLE
Implementation of "value_counts()" like feature in bar chart plotly express

### ISSUE THREAD

**Issue by matsujju** [plotly/plotly.py#2797]
Will it be possible to add `count feature/frequency as axis label` for `bar chart` like in seaborn for `plotly express` in future ?
It is helpful when we need like specific number of values from particular feature while plotting.

**Comment by nicolaskruchten** [comment]
This this basically what `px.histogram()` does, and it also supports other functions like `sum` etc... Does that meet your needs or am I misunderstanding?

**Comment by matsujju** [comment]
I am not sure how `px.hsitogram()` uses value_counts() for calculating frequencies of let say xaxis unique categories and plotting them in yaxis accordingly like in seaborn. As on looking the parameters, it requires both `x` and `y` to plot. However, if i have to let say plot `top10 uniques categories` with it's `frequency`, how to do that with histogram? Do i need to calculate frequency of top10 categories and pass it to yaxis, if this the case then this will have to be done in all other parameters which are directly affected by serialization of values in pandas dataframe column?

**Comment by nicolaskruchten** [comment]
if you pass in just `x` then `px.histogram()` will bin along that dimension and summarize by count. If you pass in `x` and `y`, it will bin along `x` and summarize by `sum(y)` unless `orientation="h"` in which case it'll do the same thing the other way. If you pass in just `y` it will infer `orientation="h"` and bin along `y`, summarizing by `count` also.

**Comment by nicolaskruchten** [comment]
Simple example:
![image](https://user-images.githubusercontent.com/203523/94483964-b0aa8c80-01a9-11eb-8673-f60d17ac6bb9.png)

**Comment by matsujju** [comment]
thanks...it is much helpful though i didn't find anywhere related to this in documentation( or may be i just missed out).

**Comment by nicolaskruchten** [comment]
Right, at the moment there's so built-in "top N" support. How does Seaborn handle this?

**Comment by matsujju** [comment]
Sorry but i can't find any parameter built in `px.histogram()`. Can you please specify what are you implying?
Seaborn has two plots  for this, one is `countplot` with `order` parameter where we can specify the index of top categories using pandas `value_counts()` method and same with `catplot` with `kind = 'count'` and `order` parameters.

**Comment by nicolaskruchten** [comment]
Sorry, typo fixed: "there's *no* built in feature"

**Comment by matsujju** [comment]
Can you suggest how do I implement this in `plotly express`? and will this feature be added in future?

**Comment by nicolaskruchten** [comment]
I don't think this is the kind of feature we'd add to the library at this time, as this is more of a data-prep concern than a strictly visualization concern: Plotly Express visualizes the whole dataset you provide to it, as a rule, rather than a subset :) 

That said, what you're looking for looks a little like this?

```python
import plotly.express as px
df = px.data.tips()
px.bar(df["day"].value_counts()[:2])
```

![image](https://user-images.githubusercontent.com/203523/94584717-03895000-024d-11eb-960a-a813dd056767.png)
