### ISSUE TITLE
BUG: Bar plot fails to display a category

### ISSUE THREAD

**Issue by fninsiima** [plotly/plotly.py#2798]
I have a pandas series called dependants that is ranked ordinally.
```
# importing pandas as pd 
import pandas as pd 
pd.options.plotting.backend = "plotly"
  
# Creating the Series 
dependants = pd.Series(['0','0','0','1','2+','2+']) 

# Plot the Series
dependants.plot.bar()
```

When I plot a bar chart, it won't display the category '2+'. Why?
![image](https://user-images.githubusercontent.com/5743896/94624542-57348180-02bf-11eb-8637-169f1ad3fa0e.png)

**Comment by emmanuelle** [comment]
Thanks for reporting this @fninsiima You can work around this by forcing the axis type to `category` as in
```python
 importing pandas as pd 
import pandas as pd 
pd.options.plotting.backend = "plotly"
  
# Creating the Series 
dependants = pd.Series(['0','0','0','1','2+','2+']) 

# Plot the Series
fig = dependants.plot.bar()
fig.update_xaxes(type='category')
fig.show()
```
but I agree it's an unexpected behaviour. I think `plotly.js` looks at the first values of the data array and decides that it has to be a numerical axis (even if you passed strings, but it's strings of numbers). @nicolaskruchten is it something hard-wired deep into plotly.js or would it be possible to change this behaviour?

**Comment by fninsiima** [comment]
Thanks for this @emmanuelle!
