### ISSUE TITLE
Wrong operator used in a condition of "process_args_into_dataframe"

### ISSUE THREAD

**Issue by nicolas-harraudeau-sonarsource** [plotly/plotly.py#2804]
Hello,

While analyzing plotly.py on SonarCloud I saw what looks like an error in [`packages/python/plotly/plotly/express/_core.py`](https://github.com/plotly/plotly.py/blob/73651942b51587086da1eee53f67995f28d68ee3/packages/python/plotly/plotly/express/_core.py#L1087):

<img width="1849" alt="Screenshot 2020-10-02 at 15 46 21" src="https://user-images.githubusercontent.com/40498978/94930769-3179c900-04c7-11eb-9a96-6eefeaa1f812.png">

You can see [the issue in SonarCloud here](https://sonarcloud.io/project/issues?id=nicolas-harraudeau-sonarsource_plotly.py&issues=AXToibzozGVPSI2IQ8-z&open=AXToibzozGVPSI2IQ8-z).

The expression `[None]` will always create a new `list`. As the operator `is` compares the identity of two objects it will check if `argument_list` points to the same object as `[None]`, which is not possible as `[None]` is a newly created object. Thus the condition `argument_list is [None]` will always be `False`.

As SonarCloud issue says, the operator `==` should be used instead of `is`. The resulting condition would then be:
```
if argument_list is None or argument_list == [None]:
```

In case you want to scan Plotly on SonarCloud [here is what the configuration looks like with Github actions](https://github.com/nicolas-harraudeau-sonarsource/plotly.py/commit/9835e125a6372c30093d41ee9064fcf69fd7887f) and here is [the config if you prefer to let SonarCloud scan your project by itself](https://github.com/nicolas-harraudeau-sonarsource/plotly.py_autoscan/commit/463c45f56c2b08a360b63642d8be83ce10a5231d). It is free for open source projects.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
