### ISSUE TITLE
Plotting histogram instead of bar chart

### ISSUE THREAD

**Issue by singh-shreyas** [plotly/plotly.py#2816]
I am trying to make a stacked bar graph but when I give a list to the parameter **"y"** to the function **"plotly.express.bar"**, plotly creates a histogram instead of a bar chart.

```
import pandas as pd
import plotly.express as px

tweets = pd.read_csv("Tweets.csv")
tweets.head()

bar = tweets[['airline','airline_sentiment']]
bar.reset_index()

new_df = pd.DataFrame(columns = ["airline", "positive", "negative", "neutral"])

airlines = bar['airline'].unique()

for i in range(len(airlines)):
    new_df.loc[len(new_df),'airline']=airlines[i]
    x = bar[bar['airline'] == airlines[i]]
    new_df.loc[len(new_df)-1,'positive'] = (x['airline_sentiment'] == 'positive').sum()
    new_df.loc[len(new_df)-1,'negative'] = len(x[x['airline_sentiment'] == 'negative'])
    new_df.loc[len(new_df)-1,'neutral'] = len(x[x['airline_sentiment'] == 'neutral'])
             
new_df

fig = px.bar(new_df, x = "airline", y = ["positive","negative", "neutral"], title = "Sentiments")
fig.show()

```

![plotly](https://user-images.githubusercontent.com/25030681/95472413-be90b680-09ce-11eb-9da9-8bf8965e1f1d.png)

The CSV file and Jupyter notebook are included in the zipped file.
[StackedBar.zip](https://github.com/plotly/plotly.py/files/5348580/StackedBar.zip)

**Comment by nicolaskruchten** [comment]
Thanks for reporting this, it seems like a bug in the heuristics PX uses to determine what kind of chart to make...

Internally your code *should* resolve to the equivalent of

```python
px.bar(new_df.melt(id_vars="airline"), x = "airline", y = "value", color="variable", title = "Sentiments")
```

but something is going wrong, clearly!

**Comment by nicolaskruchten** [comment]
Ah, I see what's wrong here... `new_df.dtypes` shows the problem: your positive/negative/neutral columns are of type `'object'` because of the way you're building them up, so the type-detection is going wrong here.

You'll have to either force your column types to numeric like this:

```python
new_df["positive"] = new_df["positive"].astype('int32')
new_df["negative"] = new_df["negative"].astype('int32')
new_df["neutral"] = new_df["neutral"].astype('int32')
```

or build your data frame in a more pandas-standard way like this:

```python
df = tweets.groupby(['airline', 'airline_sentiment']).size().reset_index(name='counts')
px.bar(df, x="airline", y="counts", color="airline_sentiment")
```

Or, to be honest, you don't have to build up this data frame like this, you can use Plotly's built-in system like this:

```python
px.histogram(tweets[['airline','airline_sentiment']], x="airline", color="airline_sentiment")
```

![image](https://user-images.githubusercontent.com/203523/95510271-a6e01080-0983-11eb-8e29-3c2b303d801c.png)

**Comment by singh-shreyas** [comment]
Hi Nicolas,

Thanks for your reply.

I got what the problem was with my data frame and understood your given resolution.

But, one thing that struck my mind was why can't plotly automatically detects the type of the object? What I mean here is plotly should automatically get the type based on the data it contains. That way plotly will be smarter.

This code snippet is converting the data type of all the three columns as int.
```
new_df["positive"] = new_df["positive"].astype('int32')
new_df["negative"] = new_df["negative"].astype('int32')
new_df["neutral"] = new_df["neutral"].astype('int32')
```

What I think is plotly should be able to do this type conversion while plotting the chart.

Thanks!

**Comment by nicolaskruchten** [comment]
It would be nice for Plotly to do this, yes, but it's more of a day-later responsibility here IMO than a vis-layer concern. If Pandas is unable to get the type right in this case, it's unlikely that Plotly will be able to do a better job :)

**Comment by singh-shreyas** [comment]
Yeah, you are right Nicolas.

Anyways, as a programmer, we should be able to debug the problem and your comment helped me in understanding the problem which was great learning for me.
