### ISSUE TITLE
Move `FigureFactory`

### ISSUE THREAD

**Issue by theengineear** [plotly/plotly.py#282]
There are some weird organizational issues with having `tools.py` depend on `graph_objs.py`. Tools is where we will want to load in graph reference. It will probably make a lot more sense to move FigureFactory stuff to `graph_objs_tools`.

This was OK before because graph reference was defined before any imports, this isn't the case anymore.

**Comment by jonmmease** [comment]
Has been moved to `plotly.figure_factory`
