### ISSUE TITLE
Settings hovertemplate for scatter_3d and understanding the difference between px.scater_3d and go.Scatter3d

### ISSUE THREAD

**Issue by luggie** [plotly/plotly.py#2821]
I'm trying to set a hovertemplate to a `plotly.express.scatter_3d` plot which I have managed to do with updating the figures `data[0]`(which contains a `go.Scatter3d` as far as I understood it) which consumes a lot of performance especially because I need to update the `plotly.express.scatter_3d` with another trace a step later and then I again would need to update the _hover probs_. Is there a way to get hovertemplate direcly into  `plotly.express.scatter_3d` while creating it? I probably missed a point with understanding the difference between `go.Scatter3d` and  `plotly.express.scatter_3d`.

```
...
hover_template = '<b>%{customdata[5]}</b>' +\
                 '<br><b>Main Class</b>: %{customdata[6]}' +\
                 '<br><b>Category</b>: %{customdata[3]}' +\
                 '<extra></extra>'

fig = px.scatter_3d(df, x='x', y='y', z='z',
                    hover_data=df.columns,
                    color='CATEGORY', opacity=0.5, size='mass',
                    height=800)

# set hover probs
for i, category in enumerate(fig.data):
    fig.data[i].update(hovertemplate=ts.hover_template, hoverinfo='skip')
fig.update_layout(hoverlabel=ts.hover_label)
...
```
Sorry for not providing a full working example bu I think you get the point. If not I'll provide more.

**Comment by luggie** [comment]
well, like always. As soon as you start opening an issue, you find the answer yourself:
`fig.update_traces(hovertemplate=ts.hover_template)`
However internally my loop and this line of code are probably doing similar things and don't change the problem of performance. My underlying question of the difference between `go.Scatter3d` and  `plotly.express.scatter_3d`is still puzzling me

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
