### ISSUE TITLE
Could not set plotly as pandas plotting backend:"ValueError: Could not find plotting backend 'plotly'. "

### ISSUE THREAD

**Issue by zhangyuz** [plotly/plotly.py#2830]
my env:
conda
python 3.7.6
pandas 1.1.3
plotly 4.4.1
and following https://plotly.com/python/getting-started/ get my env ready.
in my code:
```python
import pandas as pd
pd.options.plotting.backend = "plotly"
```
and I got error `Could not find plotting backend 'plotly'. Ensure that you've installed the package providing the 'plotly' entrypoint, or that the package has a top-level `.plot` method.`

So I checked pandas code for querying plotting backends, and tried the following code
```python
import pkg_resources
import importlib

for entry_point in pkg_resources.iter_entry_points('pandas_plotting_backends'):
    print(entry_point)

module = importlib.import_module('plotly')
if hasattr(module, 'plot'):
    print('YES')
else:
    print('NO')
```
and got the following result:
```
matplotlib = pandas:plotting._matplotlib
NO
```

Do anybody have a clue what went wrong? or how I can fix this.

**Comment by nicolaskruchten** [comment]
That's right, we introduced this backend in version 4.8 of `plotly` so you'll need to upgrade. The latest version right now is 4.11.

**Comment by zhangyuz** [comment]
> That's right, we introduced this backend in version 4.8 of `plotly` so you'll need to upgrade. The latest version right now is 4.11.

It worked for me after upgrading plotly to 4.11, thx
