### ISSUE TITLE
Request: Add change aspect ratio

### ISSUE THREAD

**Issue by danekasper** [plotly/plotly.py#285]
Python api does not have aspect ratio.

Python api does not convert 
`scene=Scene(
        aspectmode='Manual',
        aspectratio=AspectRatio(
            x=1,
            y=1,
            z=0.7)
)`

into json equivlient
`scene:{aspectratio:{
y:1,
x:1,
z:0.7
}}`

**Comment by theengineear** [comment]
Thanks for opening this up! We're working on an upgrade right now.

**Comment by bcdunbar** [comment]
Example of fixed ratio here https://plot.ly/python/axes/#fixed-ratio-axes and reference info here https://plot.ly/python/reference/#layout-xaxis-scaleanchor

**Comment by jonmmease** [comment]
I think this is now possible. Feel free to reopen if not.
