### ISSUE TITLE
How to create interval legend on choropleth graph?

### ISSUE THREAD

**Issue by BS-98** [plotly/plotly.py#2857]
Hi,

is it possible to create a choropleth with intervals visualization? I've searched that is possible but only working with USA area but I have another region.

I have something like this:
![plot1](https://user-images.githubusercontent.com/66216239/97088469-47475d80-1631-11eb-90d1-acda3f6298eb.PNG)

But I want to have a legend like this in red rectangle:
![plot2](https://user-images.githubusercontent.com/66216239/97088478-57f7d380-1631-11eb-9a12-e99db973e023.png)

Code for my graph is:
```
fig = px.choropleth(dff,
                        locations="Województwo",
                        geojson=pl_json,
                        color=color,
                        color_continuous_scale=px.colors.sequential.Blues,
                        scope="europe")
    
    fig.update_geos(fitbounds="locations", visible=False)
    fig.update_layout(height=600)
```

I would be grateful for any help.

**Comment by gvwilson** [comment]
Hi - we are tidying up issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. For tech support and "how-to" questions, please post in our community forum https://community.plotly.com/. Thank you - @gvwilson
