### ISSUE TITLE
add_{hline, vline, hrect, vrect} not working as intended

### ISSUE THREAD

**Issue by FCCMac** [plotly/plotly.py#2865]
## The Problem
Using ```fig.add_{hline, vline, hrect, vrect}``` on a plotly.express object is not working as described in the docs. Following along with the simple example given:
```
iris = px.data.iris()
fig = px.scatter(iris, x='petal_length', y='petal_width')
fig.add_hline(y=0.9)
fig.add_vrect(x0=0.9, x1=2)
fig.show()
```
Displays the following in a notebook running in Visual Studio Code:
![snap](https://user-images.githubusercontent.com/25341060/97718078-1a5cd580-1a8b-11eb-9d77-a31dfa2c465b.png)

I originally discovered this behavior when placing a vline on a px.line figure in dash:
```
df = foo.get_history()
fig = px.line(df, template='ggplot2')
fig.add_vline(x='2020-10-30', line_width=3, line_dash='dash', line_color='red')
```
![image](https://user-images.githubusercontent.com/25341060/97720598-11b9ce80-1a8e-11eb-945d-61149a2282cf.png)
The line is drawn on the correct date, but only from 0 to 1.

## Intended Behavior
The y extents of the vrect should encompass the entire plot area and the hline should extend across the entire plot area horizontally. Instead, they are fixed to 0 and 1.

## Probable Cause
It seems that the ```add_{hline, vline, hrect, vrect}``` methods in ```basedatatypes.py``` for ```BaseFigure``` set these values in the call to ```self._process_multiple_axis_spanning_shapes(,...)```. For example, the ```add_vline()``` method:
![image](https://user-images.githubusercontent.com/25341060/97718471-96571d80-1a8b-11eb-899a-d05cc8216645.png)

## Proposed Solution
It seems like we should just be able to find the x/y axis range and set the x0/x1/y0/y1 based on that, but I'm not sure how to get to those values. I'm a bit short on time this morning, but I may have a crack at this in the afternoon.

**Comment by FCCMac** [comment]
Well now I'm lost. Works as intended when run in the notebook linked via Binder from the docs:

![image](https://user-images.githubusercontent.com/25341060/97726908-5ac15100-1a95-11eb-99a2-f029f864d4d6.png)

**Comment by nicolaskruchten** [comment]
I suspect that you're running this in JupyterLab and you haven't updated your `jupyterlab-plotly` and/or `plotlywidget` extensions to versions matching the `plotly` module, which is 4.12.0 at the moment: https://plotly.com/python/troubleshooting/

**Comment by FCCMac** [comment]
No JupyterLab, the first example is in Visual Studio Code's notebook environment and the second is in a simple dash app. I just made sure that I'm on the latest version of dash (1.17.0) and dash-renderer (1.8.3), and that Code is up to date as well (1.50.1).

**Comment by nicolaskruchten** [comment]
Ah, yeah, VSCode's Python extension trails the latest version of Plotly.js by a few releases unfortunately.

**Comment by nicolaskruchten** [comment]
Dash 1.17 should have the right version of Plotly.js on board though... still seeing issues with that version of Dash?

**Comment by nicolaskruchten** [comment]
Are you on the latest version of dash-core-components (which should come in automatically with the latest version of Dash)?

**Comment by nicolaskruchten** [comment]
(sorry I didn't fully read through your thorough issue! I shouldn't try to answer questions from my phone :)

**Comment by wallflower** [comment]
In case this helps anyone.   Was seeing the same thing (i,.e. working in jupyter but not in dash... )

The package versions I had:

```
dash                          1.16.3
dash-bootstrap-components     0.10.7
dash-core-components          1.12.1
dash-html-components          1.1.1
dash-renderer                 1.8.2
dash-table                    4.10.1
...
plotly                        4.12.0
```

Forcing an update of dash ( `pip install -U dash`) moved my versions to:

```
dash                          1.17.0
dash-bootstrap-components     0.10.7
dash-core-components          1.13.0
dash-html-components          1.1.1
dash-renderer                 1.8.3
dash-table                    4.11.0
...
plotly                        4.12.0
```

And all it working as expected.

**Comment by c06n** [comment]
@wallflower Updating dash works for Jupyter notebooks, but unfortunately not for VS Code. The issue persists there.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
