### ISSUE TITLE
PlotlyWidget Rendering Jupyterlab Extension not updating

### ISSUE THREAD

**Issue by jorekai** [plotly/plotly.py#2870]
I came across the following Issue which I wasnt able to resolve yet. I am running Jupyterlab and want to render Figurewidgets which i can update periodically. Updates are not working and on some configuration the plot is not even rendering.

I am initializing my FigureWidget as a class object and use it later on to add traces dynamically and update them upon ticks.
If i use .show() upon every tick the plot is shown and rendered individually for every iteration. If i leave it the plot never even gets rendered.

This React error is popping up in my console everytime i run my cell.
![PlotlyWidgetError](https://user-images.githubusercontent.com/15143394/97778224-0cd04a00-1b76-11eb-9f6f-f1b97a574229.png)

My Labextensions are the following:
![grafik](https://user-images.githubusercontent.com/15143394/97778248-44d78d00-1b76-11eb-9a90-89aa0e0b8c3d.png)

Also my conda packages which i have installed.

_libgcc_mutex             0.1                        main  
absl-py                   0.11.0                   pypi_0    pypi
argon2-cffi               20.1.0           py38h7b6447c_1  
astunparse                1.6.3                    pypi_0    pypi
async_generator           1.10                       py_0  
atari-py                  0.2.6                    pypi_0    pypi
attrs                     20.2.0                     py_0  
backcall                  0.2.0                      py_0  
blas                      1.0                         mkl  
bleach                    3.2.1                      py_0  
brotlipy                  0.7.0           py38h8df0ef7_1001    conda-forge
ca-certificates           2020.10.14                    0  
cachetools                4.1.1                    pypi_0    pypi
certifi                   2020.6.20          pyhd3eb1b0_3  
cffi                      1.14.3           py38he30daa8_0  
chardet                   3.0.4           py38h924ce5b_1008    conda-forge
cloudpickle               1.6.0                    pypi_0    pypi
cryptography              3.2              py38hb23e4d4_0    conda-forge
cycler                    0.10.0                   pypi_0    pypi
dataclasses               0.6                      pypi_0    pypi
dbus                      1.13.18              hb2f20db_0  
decorator                 4.4.2                      py_0  
defusedxml                0.6.0                      py_0  
entrypoints               0.3                      py38_0  
expat                     2.2.10               he6710b0_2  
ffmpeg                    1.4                      pypi_0    pypi
fontconfig                2.13.0               h9420a91_0  
freetype                  2.10.4               h5ab3b9f_0  
future                    0.18.2                   pypi_0    pypi
gast                      0.3.3                    pypi_0    pypi
glib                      2.66.1               h92f7085_0  
google-auth               1.22.1                   pypi_0    pypi
google-auth-oauthlib      0.4.1                    pypi_0    pypi
google-pasta              0.2.0                    pypi_0    pypi
grpcio                    1.33.1                   pypi_0    pypi
gst-plugins-base          1.14.0               hbbd80ab_1  
gstreamer                 1.14.0               hb31296c_0  
gym                       0.17.3                   pypi_0    pypi
h5py                      2.10.0                   pypi_0    pypi
icu                       58.2                 he6710b0_3  
idna                      2.10               pyh9f0ad1d_0    conda-forge
importlib-metadata        2.0.0                      py_1  
importlib_metadata        2.0.0                         1  
intel-openmp              2020.2                      254  
ipykernel                 5.3.4            py38h5ca1d4c_0  
ipython                   7.18.1           py38h5ca1d4c_0  
ipython_genutils          0.2.0                    py38_0  
ipywidgets                7.5.1                      py_1  
jedi                      0.17.2                   py38_0  
jinja2                    2.11.2                     py_0  
joblib                    0.17.0                     py_0  
jpeg                      9b                   h024ee3a_2  
json5                     0.9.5              pyh9f0ad1d_0    conda-forge
jsonschema                3.2.0                      py_2  
jupyter                   1.0.0                    py38_7  
jupyter_client            6.1.7                      py_0  
jupyter_console           6.2.0                      py_0  
jupyter_core              4.6.3                    py38_0  
jupyterlab                2.2.9                      py_0    conda-forge
jupyterlab-plotly-extension 1.0.0                      py_0    conda-forge
jupyterlab_pygments       0.1.2                      py_0  
jupyterlab_server         1.2.0                      py_0    conda-forge
keras-preprocessing       1.1.2                    pypi_0    pypi
kiwisolver                1.3.0                    pypi_0    pypi
ld_impl_linux-64          2.33.1               h53a641e_7  
libedit                   3.1.20191231         h14c3975_1  
libffi                    3.3                  he6710b0_2  
libgcc                    7.2.0                h69d50b8_2    conda-forge
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_0  
libpng                    1.6.37               hbc83047_0  
libsodium                 1.0.18               h7b6447c_0  
libstdcxx-ng              9.1.0                hdf63c60_0  
libuuid                   1.0.3                h1bed415_2  
libxcb                    1.14                 h7b6447c_0  
libxml2                   2.9.10               hb55368b_3  
markdown                  3.3.3                    pypi_0    pypi
markupsafe                1.1.1            py38h7b6447c_0  
matplotlib                3.3.2                    pypi_0    pypi
mistune                   0.8.4           py38h7b6447c_1000  
mkl                       2020.2                      256  
mkl-service               2.3.0            py38he904b0f_0  
mkl_fft                   1.2.0            py38h23d657b_0  
mkl_random                1.1.1            py38h0573a6f_0  
nbclient                  0.5.1                      py_0  
nbconvert                 6.0.7                    py38_0  
nbformat                  5.0.8                      py_0  
ncurses                   6.2                  he6710b0_1  
nest-asyncio              1.4.1                      py_0  
nodejs                    10.13.0              he6710b0_0  
notebook                  6.1.4                    py38_0  
numpy                     1.18.5                   pypi_0    pypi
numpy-base                1.19.2           py38hfa32c7d_0  
oauthlib                  3.1.0                    pypi_0    pypi
opencv-python             4.4.0.44                 pypi_0    pypi
openssl                   1.1.1h               h7b6447c_0  
opt-einsum                3.3.0                    pypi_0    pypi
packaging                 20.4                       py_0  
pandas                    1.1.3                    pypi_0    pypi
pandoc                    2.11                 hb0f4dca_0  
pandocfilters             1.4.2                    py38_1  
parso                     0.7.0                      py_0  
pcre                      8.44                 he6710b0_0  
pexpect                   4.8.0                    py38_0  
pickleshare               0.7.5                 py38_1000  
pillow                    8.0.1                    pypi_0    pypi
pip                       20.2.4                   py38_0  
plotly                    4.12.0                     py_0    plotly
prometheus_client         0.8.0                      py_0  
prompt-toolkit            3.0.8                      py_0  
prompt_toolkit            3.0.8                         0  
protobuf                  3.13.0                   pypi_0    pypi
ptyprocess                0.6.0                    py38_0  
pyasn1                    0.4.8                    pypi_0    pypi
pyasn1-modules            0.2.8                    pypi_0    pypi
pycparser                 2.20                       py_2  
pyglet                    1.5.0                    pypi_0    pypi
pygments                  2.7.1                      py_0  
pyopenssl                 19.1.0                     py_1    conda-forge
pyparsing                 2.4.7                      py_0  
pyqt                      5.9.2            py38h05f1152_4  
pyrsistent                0.17.3           py38h7b6447c_0  
pysocks                   1.7.1            py38h924ce5b_2    conda-forge
python                    3.8.5                h7579374_1  
python-dateutil           2.8.1                      py_0  
python_abi                3.8                      1_cp38    conda-forge
pytz                      2020.1                   pypi_0    pypi
pyzmq                     19.0.2           py38he6710b0_1  
qt                        5.9.7                h5867ecd_1  
qtconsole                 4.7.7                      py_0  
qtpy                      1.9.0                      py_0  
readline                  8.0                  h7b6447c_0  
requests                  2.24.0             pyh9f0ad1d_0    conda-forge
requests-oauthlib         1.3.0                    pypi_0    pypi
retrying                  1.3.3                      py_2  
rsa                       4.6                      pypi_0    pypi
scikit-learn              0.23.2           py38h0573a6f_0  
scipy                     1.5.3                    pypi_0    pypi
send2trash                1.5.0                    py38_0  
setuptools                50.3.0           py38hb0f4dca_1  
sip                       4.19.13          py38he6710b0_0  
six                       1.15.0                     py_0  
sqlite                    3.33.0               h62c20be_0  
stable-baselines          2.10.1                   pypi_0    pypi
stable-baselines3         0.10.0                   pypi_0    pypi
tensorboard               2.3.0                    pypi_0    pypi
tensorboard-plugin-wit    1.7.0                    pypi_0    pypi
tensorflow                2.3.1                    pypi_0    pypi
tensorflow-estimator      2.3.0                    pypi_0    pypi
termcolor                 1.1.0                    pypi_0    pypi
terminado                 0.9.1                    py38_0  
testpath                  0.4.4                      py_0  
threadpoolctl             2.1.0              pyh5ca1d4c_0  
tk                        8.6.10               hbc83047_0  
torch                     1.7.0                    pypi_0    pypi
tornado                   6.0.4            py38h7b6447c_1  
traitlets                 5.0.5                      py_0  
typing-extensions         3.7.4.3                  pypi_0    pypi
urllib3                   1.25.11                    py_0    conda-forge
wcwidth                   0.2.5                      py_0  
webencodings              0.5.1                    py38_1  
werkzeug                  1.0.1                    pypi_0    pypi
wheel                     0.35.1                     py_0  
widgetsnbextension        3.5.1                    py38_0  
wrapt                     1.12.1                   pypi_0    pypi
xz                        5.2.5                h7b6447c_0  
zeromq                    4.3.3                he6710b0_3  
zipp                      3.3.1                      py_0  
zlib                      1.2.11               h7b6447c_3

**Comment by nicolaskruchten** [comment]
I'm having trouble understanding the code you're using... could you share a snippet please?

In general, the instructions here https://plotly.com/python/troubleshooting/ have just been updated to include more information about how to solve this class of problem, if you want to check it out.

**Comment by jorekai** [comment]
Hey I managed to resolve the issue quite some time ago. My problem was that i wanted to use the FigureWidget as a class member instance and call changes upon its data later in my notebook. Therefore i still needed to watch that my plot is the last call in a jupyter notebook cell, so that it is updated and rendered dynamically.

 Then my plot could be accessed via callbacks. My working example can be found here: https://github.com/jorekai/Anomaly-Detection-Baselines/blob/master/AdvancedStateAndReward.ipynb
