### ISSUE TITLE
Graph not displayed in jupyterlab (FigureWidget works)

### ISSUE THREAD

**Issue by antonio-yu** [plotly/plotly.py#2873]
This example does not work in jupyter lab,but works well in jupyter notebook.Only shows a blank between two cells.

```
import plotly.graph_objects as go
fig = go.Figure()
fig.add_trace(go.Scatter(y=[2, 1, 4, 3]))
fig.add_trace(go.Bar(y=[1, 4, 3, 2]))
fig.update_layout(title = 'Hello Figure')
fig.show()
```

But when i use class "FigureWidget",it works in jupyterlab and the graph shows,don't know why.

```
import plotly.graph_objects as go
fig = go.FigureWidget()
fig.add_trace(go.Scatter(y=[2, 1, 4, 3]))
fig.add_trace(go.Bar(y=[1, 4, 3, 2]))
fig.update_layout(title = 'Hello Figure')
fig
```

The following version:

JupyterLab v2.2.6
Known labextensions:
   app dir: d:\programfiles\anaconda\share\jupyter\lab
        @bokeh/jupyter_bokeh v2.0.3 enabled  ok
        @jupyter-widgets/jupyterlab-manager v2.0.0 enabled  ok
        @jupyterlab/fasta-extension v2.0.0 enabled  ok
        @jupyterlab/geojson-extension v2.0.1 enabled  ok
        @jupyterlab/github v2.0.0 enabled  ok
        @jupyterlab/katex-extension v2.0.0 enabled  ok
        @jupyterlab/latex v2.0.1 enabled  ok
        @jupyterlab/mathjax3-extension v3.0.0 enabled  ok
        @jupyterlab/toc v4.0.0 enabled  ok
        @jupyterlab/vega2-extension v2.0.0 enabled  ok
        @jupyterlab/vega3-extension v2.0.0 enabled  ok
        @kiteco/jupyterlab-kite v1.0.0 enabled  ok
        @krassowski/jupyterlab-lsp v1.1.2 disabled ok
        @krassowski/jupyterlab_go_to_definition v1.0.0 enabled  ok
        @lckr/jupyterlab_variableinspector v0.5.1 enabled  ok
        jupyter-leaflet v0.13.2 enabled  ok
        jupyter-matplotlib v0.7.3 enabled  ok
        jupyterlab-dash v0.3.0 enabled  ok
        jupyterlab-drawio v0.7.0 enabled  ok
        jupyterlab-plotly v4.12.0 enabled  ok
        jupyterlab-spreadsheet v0.3.2 enabled  ok
        keplergl-jupyter v0.2.1 enabled  ok
        plotlywidget v4.12.0 enabled  ok
        spreadsheet-editor v0.4.0 enabled  ok

**Comment by antonio-yu** [comment]
sorry,correct the second code 
```
import plotly.graph_objects as go
fig = go.FigureWidget()
fig.add_trace(go.Scatter(y=[2, 1, 4, 3]))
fig.add_trace(go.Bar(y=[1, 4, 3, 2]))
fig.update_layout(title = 'Hello Figure')
fig
```

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
