### ISSUE TITLE
Add pretty doc strings back after graph reference upgrade

### ISSUE THREAD

**Issue by theengineear** [plotly/plotly.py#289]
The old docs were based on the old version of graph reference. This has changed, but belongs in a separate PR.

**Comment by chriddyp** [comment]
by docs, you mean doc strings?

**Comment by theengineear** [comment]
yeah, sorry, i'll correct that title

**Comment by chriddyp** [comment]
and fyi python reference pages have been updated, there might be some things that you'll want to copy: https://plot.ly/python/reference/

In particular, I think the explanation of the types is pretty good, like `flaglist`: https://plot.ly/python/reference/#scatter-mode, and `graph_objs`: https://plot.ly/python/reference/#scatter-marker-line.

Code is here: https://github.com/plotly/documentation/blob/source/_includes/reference-block.html

**Comment by theengineear** [comment]
yeah, those docs are wonderful! i'd love to have something like that in our 'help'

**Comment by jonmmease** [comment]
Version 3 docstrings are very pretty 🙂
