### ISSUE TITLE
Add key ordering back to python api.

### ISSUE THREAD

**Issue by theengineear** [plotly/plotly.py#290]
There's no order in the new plot schema.

**Comment by etpinard** [comment]
Wouldn't loading up the plot-schema json with as an ordered dict suffice?

**Comment by theengineear** [comment]
sorta. i think this is still hard to test though, if we made a change in the plot-schema and the new hashes changed the order of the stored json, then loading this new json as an ordered dict would break tests, right? we *have* to set an order in `plot-schema.json` before we can start using the `OrderedDict` `ordered_pairs` hook. Right?

**Comment by etpinard** [comment]
@theengineear That sounds like another syncing nightmare.

Why would we need to test the order of the plot-schema?

Doesn't validation only care of the existence of the attributes, not their position in the plot-schema?

Are you concerned about the output of the `help` method?

**Comment by theengineear** [comment]
Testing `to_string` is nearly impossible without having a predictable order.

Just in case we're not on the same page. As far as updating the python api goes, I really don't care or need the plot schema to have a consistent order. I do some *exceedingly* simple ordering in the python api so that the `to_string` test result will pass. But that's all. This is highly :football:-able as far as I'm concerned.

I created an issue because we *would* ideally like better `help` and I think there's some documentation-related needs for ordering in the plot schema.

The python api has no intention of testing full ordering, but just a *small* subset needs to be predictable in order to test the `to_string` method.

@chriddyp :wind_chime:-ed in on this earlier though and might have more opinions on it.

**Comment by etpinard** [comment]
@theengineear all good :+1:
