### ISSUE TITLE
Plotly map shows Crimea as a part of Russia

### ISSUE THREAD

**Issue by notiqq** [plotly/plotly.py#2903]
Hi,
I have noticed that plotly map shows Crimea as a part of Russia https://i.imgur.com/Pm5ZmF0.png
As per United Nations Resolution 68/262, US, Canadian, EU law and by the law of many other countries, Crimea is considered as a part of Ukraine. https://en.wikipedia.org/wiki/United_Nations_General_Assembly_Resolution_68/262

Could you please amend this issue in library?

**Comment by nicolaskruchten** [comment]
See https://github.com/plotly/plotly.js/issues/4345 for details about the built-in data and how to override it.
