### ISSUE TITLE
Plotly range_slider limits

### ISSUE THREAD

**Issue by tomron** [plotly/plotly.py#2909]
(I have also posted this in [SO](https://stackoverflow.com/questions/64864440/plotly-range-slider-limits/))

I post it here as well since I do know what I do wrong and I'm worried about what seems to be inconsistent.

I run the code below to create a scatter with a range slider using plotly. This yields the following output - [![here][1]][1]

I want to make the scatter "tight", i.e no slack with no data on the sides. When I run the code from plotly's [documentation][2] there are no slacks (same notebook, same kernel). 

When I add - `fig.update_layout(xaxis=dict(range=[x[0],x[-1]]))` it update only the range of the graph but not the range of the slider. [![enter image description here][3]][3]

I would appreciate any advice.

    import plotly.graph_objects as go
    from datetime import datetime, timedelta
    
    x = [datetime(2019, 1, 1) + timedelta(days=i) for i in range(365)]
    y = [1]  * 365
    fig = go.Figure()
    fig.add_trace(go.Scatter(x=x, y=y, name="Pred", mode="markers"))
    fig.update_layout(
        xaxis=dict(
            rangeselector=dict(
                buttons=list([
                    dict(count=1,
                         label="1m",
                         step="month",
                         stepmode="backward"),
                    dict(count=6,
                         label="6m",
                         step="month",
                         stepmode="backward"),
                    dict(count=1,
                         label="YTD",
                         step="year",
                         stepmode="todate"),
                    dict(count=1,
                         label="1y",
                         step="year",
                         stepmode="backward"),
                    dict(step="all")
                ])
            ),
            rangeslider=dict(
                visible=True
            ),
            type="date"
        )
    )
    fig.show()

  [1]: https://i.stack.imgur.com/R4gRX.png
  [2]: https://plotly.com/python/range-slider/
  [3]: https://i.stack.imgur.com/g1fhe.png

**Comment by surchs** [comment]
Hi @tomron, you can get the desired performance by using the `lines` mode instead of the `marker` mode. I.e.:

```
import plotly.graph_objects as go
from datetime import datetime, timedelta

x = [datetime(2019, 1, 1) + timedelta(days=i) for i in range(365)]
y = [1]  * 365
fig = go.Figure()
fig.add_trace(go.Scatter(x=x, y=y, name="Pred", mode="lines"))
fig.update_layout(
    xaxis=dict(
        rangeselector=dict(
            buttons=list([
                dict(count=1,
                     label="1m",
                     step="month",
                     stepmode="backward"),
                dict(count=6,
                     label="6m",
                     step="month",
                     stepmode="backward"),
                dict(count=1,
                     label="YTD",
                     step="year",
                     stepmode="todate"),
                dict(count=1,
                     label="1y",
                     step="year",
                     stepmode="backward"),
                dict(step="all")
            ])
        ),
        rangeslider=dict(
            visible=True
        ),
        type="date"
    )
)
fig.show()
```

![image](https://user-images.githubusercontent.com/1302022/99421264-31455980-28cc-11eb-8a37-55a58ef80dc7.png)


You may also want to follow plotly/plotly.js#1876 for updates on this behaviour.

**Comment by tomron** [comment]
Thanks!
From my point of view, this issue can be closed as "external dependency".
