### ISSUE TITLE
Can't change xticks font Size using: 

### ISSUE THREAD

**Issue by AndreuJove** [plotly/plotly.py#2922]
Unable to change the size of xticks in any plot. Even if a use font in the instance of the plot the xticks change.

fig.update_xaxes(
                             ticks="outside", 
                             tickfont=dict(family='Arial', size=20, color='black')
                             )

**Comment by leo-smi** [comment]
try using:

```
fig.update_layout(
	yaxes = dict(
	
	)
)
```

**Comment by AndreuJove** [comment]
Hi leo-smi. Thank you for the answer.

I tryied:


    fig.update_layout(xaxis_type='category', 
                        bargap=0.7,
                        xaxis = dict(
                            tickfont=dict(family='Helvetica', size=20, color='black'),
                        ),


The font and the color it works but the size not. 


How can I make xticks bigger in plotly python?

**Comment by leo-smi** [comment]
Please take a look at the [documentation](https://plotly.com/python/reference/layout/xaxis/#layout-xaxis-tickfont), maybe it helps.

**Comment by AndreuJove** [comment]
Thank you for the answer leo-smi. I tried and it does the same as before it only changes the orientation. 

Could be this a bug?

TickfontSize changes the orientation of ticks but it does not make them bigger.

**Comment by nicolaskruchten** [comment]
@AndreuJove are you trying to increase the text size of the tick labels, or are you trying to increase the size of the little tick?

this code does both:

```python
import plotly.express as px

df = px.data.iris()
fig = px.scatter(df, x="sepal_length", y="sepal_width")
fig.update_xaxes(tickfont_size=40, ticks="outside", ticklen=20, tickwidth=10)
fig.show()
```

![newplot](https://user-images.githubusercontent.com/203523/99973750-16f8f900-2d6e-11eb-9433-79a59df9ceee.png)

**Comment by AndreuJove** [comment]
Hi Nicolas it seems that using plotly in Dash doesn't work tickfont_size. All the others work perfectly.

**Comment by nicolaskruchten** [comment]
That's quite surprising... Can you show me some sample Dash code where this is the case?

**Comment by AndreuJove** [comment]
Yes sure! I tried all different possibilities to change the size of xticks but it is not working. And it is quite important to see what is each axes.
The figure.update_xaxes method only works on the family and color. But not in the size of the xticks.


Here is a function to create a px.bar:



def create_px_bar_http_codes(df, x_value, y_value, title_given, color_given):
    # Create bar for http codes in acces tab:
    df = df.copy()
    df['color'] = color_given
    fig = px.bar(df, x=x_value, y=y_value, log_y=True,
                 color_discrete_sequence=df.color.unique(),
                 template='simple_white',
                 hover_data={x_value: False, y_value: False},
                 hover_name=y_value)
    # fig.update_xaxes(ticks="outside", 
    #                 tickfont=dict(family='Helvetica', color='black'),                                   
    #                 )
    fig.update_layout(xaxis_type='category', 
                        bargap=0.7,
                        xaxis = dict(
                            automargin=True,
                            
                        ),
                      title=f"<b>{title_given} ({df[y_value].sum()})</b>", title_x=0.5
                      )
    fig.update_xaxes(tickfont_size=15, tickfont_color="Black")
    return fig

**Comment by nicolaskruchten** [comment]
This is indeed confusing. Can you confirm that you're using the latest versions of `plotly`, `dash` and` dash-core-components`? If so, I would suspect some CSS in your app which is forcing the tick labels to be smaller than desired.

**Comment by AndreuJove** [comment]
I'm using these versions:

dash                    1.16.2              
dash-core-components    1.12.1              
dash-html-components    1.1.1  
plotly                  4.10.0 


The CSS is not touching font-size.

**Comment by AndreuJove** [comment]
When I change tickfont_size to 50 that's what it changes:
![Screenshot from 2020-11-27 16-07-36](https://user-images.githubusercontent.com/52964120/100462643-d5987e80-30ca-11eb-9980-8632554fe0df.png)


fig.update_xaxes(tickfont_size=50)

**Comment by leo-smi** [comment]
try this example, I had to use today:

```
        fig.update_layout(
            # paper_bgcolor   = 'white',
            margin          = {"r":0,"t":35,"l":0,"b":5},
            xaxis_tickangle = -45,
            xaxis           = {'type':'category', 'tickfont_size':8},
            xaxis_title     = "Dia",
            title           = dict(
                text = f'{title}',
                font = dict(
                    size = 10
                )
            ),
            legend = dict(
                orientation = "h",
                x          = 0,
                y          = 1.03,
                xanchor    = "left",
                yanchor    = "middle",
                traceorder = "normal",
                font       = dict(
                    family = "sans-serif",
                    size   = 10,
                    color  = "black"
                ),
                bgcolor     = 'rgba(0,0,0,0)',
                bordercolor = 'rgba(0,0,0,0)',
                borderwidth = 2,
                # title = dict(
                #     font = dict(
                #         size = 5,
                #         color = "green"
                #     )
                # )
            ),
```

**Comment by NightMachinary** [comment]
@leo-smi I am trying to fit a large legend on a small image; Setting the font size to a small value doesn't help, as the freed up space just goes to become vertical margin. Any ideas?

```py
    fig.update_layout(
        legend = dict(
            traceorder = "normal",
            font       = dict(
                size   = 8,
            ),
            tracegroupgap=0, # the amount of vertical space (in px) between legend groups.
            )
    )
```

**Comment by leo-smi** [comment]
You need to put some screenshots, and we need to know what kind plotly you are using, is plotly express? is plotly graph_objects?

**Comment by gvwilson** [comment]
Hi ,
Greetings from Plotly - I started a new gig as manager of the libraries team seven weeks ago, and so far I'm feeling like the longer I'm here, the further behind I am :-) We're thinking about overhauling our charts, and our designer would be grateful for a chance to talk with a few people about what changes they'd like to see - any chance you could spare a bit of time to chat with him online?
Hope you and yours are safe and well,
Greg
