### ISSUE TITLE
Texttemplate from bar plot don't save with plotly.io

### ISSUE THREAD

**Issue by leo-smi** [plotly/plotly.py#2925]
I'm trying to save a bar plot but the plotly.io don't save properly, I miss the textteplate (is this because html code maybe?):

```
jupyterlab: 2.2.9
plotly: 4.12
```
The piece of code is:

```
fig.add_trace(go.Bar(
    x            = dataframe(df = df, ano = 2019)['fonte'],
    y            = dataframe(df = df, ano = 2019)['MWh_month'],
    name         = '2019',
    marker_color = 'rgb(62, 74,  137)',
    texttemplate = "<br>%{y:.2s}",
    textposition = "inside",
    textangle    = -90,     
))

# saving
import plotly.io as pio

pio.write_image(fig, path + r"\gráficos\fig6.png", width=960, height=540, scale=3)
```

The image I want is (this is a low image quality generate on jupyter output cell):

![newplot (41)](https://user-images.githubusercontent.com/20663547/99891466-be7c0b80-2c48-11eb-9338-a1357a19d65d.png)

The image that I'm getting is:

![fig6](https://user-images.githubusercontent.com/20663547/99891470-cc319100-2c48-11eb-949d-59355b28a26a.png)

**Comment by leo-smi** [comment]
When I put the text outside 1/3 the texttemplate appears:

```
fig.add_trace(go.Bar(
    x            = dataframe(df = df, ano = 2020)['fonte'],
    y            = dataframe(df = df, ano = 2020)['MWh_month'],
    name         = '2020',
    marker_color = 'rgb(31, 158,  137)', 
    texttemplate = "<br>%{y:.2s}",
    textposition = "outside",
    textangle    = -90,       
))
``` 

![fig6](https://user-images.githubusercontent.com/20663547/99891656-216ea200-2c4b-11eb-8c78-4b8772983f9e.png)

**Comment by leo-smi** [comment]
Problem solved, I change the image resolution and worked fine, I think the minimum size of the text inside the bar can't fit inside the bar and desappear...
```
pio.write_image(fig, path + r"\gráficos\fig6.png", width=1440, height=810, scale=2)
```

![fig6](https://user-images.githubusercontent.com/20663547/99892884-c9d73300-2c58-11eb-9ab0-a0391ba2439c.png)

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
