### ISSUE TITLE
Make graph reference singleton?

### ISSUE THREAD

**Issue by theengineear** [plotly/plotly.py#293]
There's a funny dependency issue:
1. on first init, config may not be set...
2. config gets set in tools
3. tools requires graph reference
4. graph reference requires a plotly domain from config... :(

This might be alleviated if we can make the GRAPH_REFERENCE a singleton which isn't actually created until it's used. This will be tricky because graph objs _can't_ be instantiated until later for this to work...

**Comment by jonmmease** [comment]
No longer applicable to version 3
