### ISSUE TITLE
[Feature Request] Add the function of customizing legend orders?

### ISSUE THREAD

**Issue by YukunYangNPF** [plotly/plotly.py#2931]
Hi, 

I'm working on creating a stacked bar chart using go. It seems that the legend order cannot be arbitrarily set. 

For example, in the official tutorial of creating a relative bar plot (https://plotly.com/python/bar-charts/#bar-chart-with-sorted-or-ordered-categories). The natural order of the bar types is red, blue, green, and purple. However, the order of the traces is blue, red, green, and purple. If I have to keep the order of bins presented in the plot, the order of the legends will have to be set up manually which is not supported.

![image](https://user-images.githubusercontent.com/70721363/100022105-990a1180-2db0-11eb-8b04-9f696af3445f.png)

**Comment by nicolaskruchten** [comment]
The idea of manually specifying legend order is a good idea and would have to be implemented in Plotly.js first. That said, some comments on your issue:

* The bars are laid out bottom-to-top and the legend top-to-bottom by default, so in the screenshot you've posted, blue is the first legend item, followed by red, and indeed in the figure, blue is the first bar (closest to zero) followed by red. Things get a bit confusing with the negative numbers but green was laid out next (closest to zero but going down) then purple, as in the legend. I'm not sure why you say "the natural order is red/blue/green/purple" ?
* Right now we have the option of reversing the legend order (https://plotly.com/python/legend/#legend-order) which causes the legend order to match the top-to-bottom bar order when all the values are positive, but this doesn't give you full manual control.

**Comment by YukunYangNPF** [comment]
> The idea of manually specifying legend order is a good idea and would have to be implemented in Plotly.js first. That said, some comments on your issue:
> 
> * The bars are laid out bottom-to-top and the legend top-to-bottom by default, so in the screenshot you've posted, blue is the first legend item, followed by red, and indeed in the figure, blue is the first bar (closest to zero) followed by red. Things get a bit confusing with the negative numbers but green was laid out next (closest to zero but going down) then purple, as in the legend. I'm not sure why you say "the natural order is red/blue/green/purple" ?
> * Right now we have the option of reversing the legend order (https://plotly.com/python/legend/#legend-order) which causes the legend order to match the top-to-bottom bar order when all the values are positive, but this doesn't give you full manual control.

Thanks for the response. I would definitely excited to have the new function of specifying the order of legends. 
About the natural order, what I mean is the natural order from top to bottom **on the plots** (left to right if using horizontal layout). For example, imagine the legends is not blue, red, etc, but sequential data like "a lot" (2), "some" (1), "few" (-1), "none" (-2). And "few" and "none" are coded in negative values (below 0). To make a chart using this new scale and keep the order of colors just like the screenshot, the order of adding bars will be "some", then "a lot", then "few" and the last is "none" and the legend will be "some" "a lot", "few", "none", which is not the natural order of the sequential data.

I acknowledged the function of reverse legend order, but in my case, this will not work either.

**Comment by nicolaskruchten** [comment]
The new `legendrank` attribute in version 5.0 allows you to control legend item order :)  https://plotly.com/python/legend/#legend-order
