### ISSUE TITLE
Image export ignores figure layout (using Kaleido)

### ISSUE THREAD

**Issue by sergiocalde94** [plotly/plotly.py#2933]
Hi!

Thank you very much for your awesome library 🥇 

I am having some issues about figure sizing with svg render. I think a reproducible example is very visual:

With default render (plotly_mimetype+notebook) the layout correctly changes the figure size:

<img width="1402" alt="Screenshot 2020-11-24 at 19 01 40" src="https://user-images.githubusercontent.com/22750693/100133778-7eef3280-2e87-11eb-9425-baa16ab9f897.png">

But if I try it with svg render it ignores the layout 😢:

<img width="1402" alt="Screenshot 2020-11-24 at 19 02 51" src="https://user-images.githubusercontent.com/22750693/100133897-a8a85980-2e87-11eb-8163-d28c1df664b6.png">

Do you know how to avoid this problem? I need an uniform strategy, that with the same code returns same figure size, excepting the rendered type.

Thank you in advance 👍

**Comment by sergiocalde94** [comment]
Update

**Plotly version**: 4.12.0

**Comment by nicolaskruchten** [comment]
This is partly addressed in #3240 and will be part of version 5.0 ... if you don't specify a width, in Jupyter the plot will fill the window width, but when rendering with PNG you won't get the same width, you'll get the underlying default.
