### ISSUE TITLE
Is it possible to expose labelangle at express level for parallel_coordinates plot?

### ISSUE THREAD

**Issue by ghlj** [plotly/plotly.py#2950]
Really impressed by all the magic offered by parallel coordinates plot in plotly such as the interactive axis arrangement capability, the automatic range setting for each dimension, automatic handling of categorical data and so on. To my knowledge, it is the only visualization package out there that can do this in one line.

One small issue is that when the number of dimensions are high, in jupyter notebook the axis label will overlap with each other. If I am not mistaken, it seems that the only way to "update" the labelangle is to go through graph_objects way, which makes me miss all the above magic obtained in one line. 

Is it possible that the attributes such as labelangle, labelfont, labelside, rangefont, tickfont get exposed at the "express" level?

**Comment by ghlj** [comment]
I tried one solution using fig.update_traces(labelangle=-20) and it works. 
I guess we can close it.

One last comment is that the comprehensive coverage of 3D and  ternary plots from plotly are also quite unique.

**Comment by nicolaskruchten** [comment]
Yes, `update_traces()` is the recommended way to change settings that are not exposed directly in the PX function arguments :)
