### ISSUE TITLE
Animation not working in visual studio

### ISSUE THREAD

**Issue by AnupamSaraph** [plotly/plotly.py#2956]
Animation does not work in Visual Studio with plotly.express but works in Jupyter, Google Collaboratory. 
The code tested for plotting with animation is:

> `
> import plotly.express as px
> df = px.data.gapminder()
> 
> fig = px.scatter(df, x="gdpPercap", y="lifeExp", animation_frame="year", animation_group="country",
> 
>            size="pop", color="continent", hover_name="country", facet_col="continent",
>            log_x=True, size_max=45, range_x=[100,100000], range_y=[25,90])
> fig.show()
> `
> 

The output is pasted below. In case of executing the code in Visual Studio the graph does not animate and moving the slider has no effect on the graph.

![image](https://user-images.githubusercontent.com/1920565/101274033-bb445c00-37c0-11eb-932c-707b7c14ab16.png)

My Visual Studio Version details are as follows:
![image](https://user-images.githubusercontent.com/1920565/101274083-19713f00-37c1-11eb-8cd6-4ebb015a6947.png)

**Comment by AnupamSaraph** [comment]
It's been a while since I raised this here as well as in https://github.com/microsoft/vscode-jupyter/issues/4364. Is it likely to to find a resolution anytime soon?

**Comment by nicolaskruchten** [comment]
As mentioned in https://github.com/plotly/plotly.js/issues/5401 it's not clear to me what we can do about this, and no one from our team is investigating at the moment. If you or someone else can investigate and point to why this is happening, either in our code or vscode's, that would probably speed up a resolution for you.

**Comment by Jacques2101** [comment]
Hi, I have the same issue. Impossible to animate a graph in VsCode. I can see it but no animation. 
I tried: 
```
import plotly.express as px
df = px.data.gapminder()
px.scatter(df, x="gdpPercap", y="lifeExp", animation_frame="year", animation_group="country",
           size="pop", color="continent", hover_name="country",
           log_x=True, size_max=55, range_x=[100,100000], range_y=[25,90])
```

**Comment by AnupamSaraph** [comment]
See https://github.com/microsoft/vscode-jupyter/issues/4364#issuecomment-817352686 for a workaround

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
