### ISSUE TITLE
only do the pandas import check when it is needed

### ISSUE THREAD

**Issue by chriddyp** [plotly/plotly.py#297]
importing pandas takes like 4 secs on my machine, and this cases our `import plotly` to take like 5 seconds (https://github.com/plotly/python-api/blob/master/plotly/utils.py#L22-L26). If we start downloading `plot-schema.json` on every import, importing plotly could take like 10 secs! Too long! 

Removing the `pandas` import test until it's actually needed could speed this up.

**Comment by theengineear** [comment]
Great idea. Yeah import time is starting to really lag :(

**Comment by jonmmease** [comment]
pandas is no longer auto-imported
