### ISSUE TITLE
add_layout_image doesn't work with a local image

### ISSUE THREAD

**Issue by MaxGhenis** [plotly/plotly.py#2975]
`add_layout_image` works for me with a web-hosted image, e.g.:
```
fig = px.bar(x=['a', 'b', 'c'], y=[3, 4, 1])
fig.add_layout_image(dict(
    source="https://raw.githubusercontent.com/UBICenter/blog/master/jb/_static/ubi_center_logo_wide_blue.png",
    sizex=0.2, sizey=0.2))
```
![image](https://user-images.githubusercontent.com/6076111/102133071-667c9300-3e09-11eb-8bae-2f6c2289e75f.png)

But when passing the identical image, stored locally, nothing shows up:
```
fig.add_layout_image(dict(
    source="../_static/ubi_center_logo_wide_blue.png",
    sizex=0.2, sizey=0.2))
```
![image](https://user-images.githubusercontent.com/6076111/102133109-71cfbe80-3e09-11eb-929c-9f8c3ec0f7a4.png)

I'm on plotly 4.14.1.

**Comment by Nemecsek** [comment]
It works with
```
source=url_for('static', filename='images/ubi_center_logo_wide_blue.png)
```
I am not really into it, but I assume you cannot use `_static` but only the standard `static`.

**Comment by MaxGhenis** [comment]
That didn't work. Here's a [notebook](https://colab.research.google.com/drive/1MfdPWmdGc2O-NquRYlXuC0cjaYnofzfY?usp=sharing) with a more reproducible example, it downloads the file into the working directory:
```
import plotly.express as px
import flask

!wget https://raw.githubusercontent.com/UBICenter/blog/master/jb/_static/ubi_center_logo_wide_blue.png

fig = px.bar(x=['a', 'b', 'c'], y=[3, 4, 1])
fig.add_layout_image(dict(
    source=flask.url_for("static", filename="ubi_center_logo_wide_blue.png"),
    sizex=0.2, sizey=0.2))
```
>RuntimeError: Attempted to generate a URL without the application context being pushed. This has to be executed when application context is available.

**Comment by Nemecsek** [comment]
`wget` is not saving in the canonical `/static` folder which `url_for` will point to. You are downloading in the working dir, but asking to load it from `/static`.
The notebook works correctly if, instead of `source=flask.url_for(..)`, you load the image with `source="ubi_center_logo_wide_blue.png"`

**Comment by MaxGhenis** [comment]
Moving the file into `/static` produced the same error above, and pointing to the file directly if it's in the working directory produces the initially reported issue: the image doesn't show up. Both cases are in the [notebook](https://colab.research.google.com/drive/1MfdPWmdGc2O-NquRYlXuC0cjaYnofzfY?usp=sharing#scrollTo=UOjURIl484fS).

**Comment by Nemecsek** [comment]
Hi Max.
Activating the browser Inspector, you see that when you ask for your
`source="ubi_center_logo_wide_blue.png"`
it tries to download it from:
`
https://colab.research.google.com/tun/m/m-s-34o95fke9keq5/ubi_center_logo_wide_blue.png?authuser=0`.
This return "*404*: Not found".
Accessing this address directly in the browser it returns "*400.* That’s an
error. That’s all we know."

When it fails, it tries again from  `
https://localhost:8080/ubi_center_logo_wide_blue.png`, a local server
that's not active, and "*500*: Not found" is returned.
All together *it looks like it is Colab related*. When I tried on my local
server and jupyter notebook I didn't see the problem.

I gave a look around but couldn't find a workaround.
Are you finally publishing it on Colab or on a local Jypiter notebook?

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
