### ISSUE TITLE
@nicolaskruchten The add_vline and add_hline methods are great, and I would really like to use them, but I have encountered a weird issue, where the line has a length of one. `fig.add_hline(y=10)` results in a line at 10 on the y axis but only extends from 0 to 1 on the x axis. `fig.add_vline(x=1000000)` results in a line at 1 million on the x axis but only extends from 0 to 1 on the y axis. Since my plot has max x values in the hundreds of billions, these lines are basically invisible (at least, until I change the axes to log scale, at which point the plot just looks strange. Screenshot of the log-scale mode below)

### ISSUE THREAD

**Issue by gsmaio** [plotly/plotly.py#2979]
@nicolaskruchten The add_vline and add_hline methods are great, and I would really like to use them, but I have encountered a weird issue, where the line has a length of one. `fig.add_hline(y=10)` results in a line at 10 on the y axis but only extends from 0 to 1 on the x axis. `fig.add_vline(x=1000000)` results in a line at 1 million on the x axis but only extends from 0 to 1 on the y axis. Since my plot has max x values in the hundreds of billions, these lines are basically invisible (at least, until I change the axes to log scale, at which point the plot just looks strange. Screenshot of the log-scale mode below)

<img width="1007" alt="Screen Shot 2020-11-12 at 1 09 55 PM" src="https://user-images.githubusercontent.com/11811148/98978730-66c2ff00-24e8-11eb-9406-54447ca8782f.png">

_Originally posted by @jenna-jordan in https://github.com/plotly/plotly.py/issues/2141#issuecomment-726247537_

**Comment by BlkPingu** [comment]
Why was this closed? The issue still persists
