### ISSUE TITLE
py.iplot should throw error if unexpected number of args

### ISSUE THREAD

**Issue by szeitlin** [plotly/plotly.py#298]
I was trying to reproduce someone else's work from a python file. 

original code:
`fig = Figure (data = data, layout = layout)`

In IPython notebook, when I did:

`py.iplot(data=data, layout=layout, filename = 'testing')`

some of the plot showed up (the data), and there were no errors, and some of the layout features did not show up, but most did not, which was confusing. I think incorrect syntax should throw an error. 

Ultimately I decided it probably wasn't using the layout argument at all (?), since this works as expected:

`py.iplot(fig, filename='testing')`

**Comment by theengineear** [comment]
@szeitlin , agreed. This was documented (though tough to discover) in a compatibility document: https://github.com/plotly/python-api/blob/master/compatibility.md#plot-and-iplot-call-signatures from the change `0 --> 1`.

This is an easy fix to ensure the `plot_options` are acceptable. However, this is a backwards incompatible change, so it may have to wait to a major version bump to go in. I'll open up a PR on it to continue the discussion.

**Comment by szeitlin** [comment]
wow, thanks for the fast response! 

I think we're supposed to be upgrading soonish (?), so if it's already fixed, that's good to know.

**Comment by theengineear** [comment]
You're likely already on the 1.x release, but if not, you should definitely take note of that document for some organizational changes.

`py.iplot(fig, filename='testing')` is the correct way to send data to plotly in `1.x`

**Comment by jonmmease** [comment]
I believe this was  taken care of several years ago. Feel free to reopen if that's not the case
