### ISSUE TITLE
Create a subplot consisting of two plots that have been created?

### ISSUE THREAD

**Issue by amitsou** [plotly/plotly.py#2999]
Hello, I need to create a subplot that consists of two plots that I have created. The subplot should consist of two rows and a column. If I run those plots individually, the code works fine, but I can't figure how to convert it as a subplot. Thank's in advance
Here's my code: 

`
from plotly.subplots import make_subplots
import plotly.graph_objs as go
import plotly as py
import pandas as pd

df = pd.DataFrame(cf, columns = ['M_A0','STD_A0','M_A1','STD_A1','M_A2','STD_A2','M_A3','STD_A3','M_A4','STD_A4'])
df['Time'] = chair_seconds()

fig1 = go.Figure(data = [
            go.Scatter(x=df['Time'], y=df['M_A0'],
                name='Sensor 1 ave',
                mode='lines'),

            go.Scatter(x=df['Time'], y=df['M_A1'],
                name='Sensor 2 ave',
                mode='lines'),

            go.Scatter(x=df['Time'], y=df['M_A2'],
                name='Sensor 3 ave',
                mode='lines'),

            go.Scatter(x=df['Time'], y=df['M_A3'],
                name='Sensor 4 ave',
                mode='lines'),

            go.Scatter(x=df['Time'], y=df['M_A4'],
                name='Sensor 5 ave',
                mode='lines')])
py.offline.plot(fig1)

fig2 = go.Figure(data = [
            go.Scatter(x=df['Time'], y=df['STD_A0'],
                name='Sensor 1 std',
                mode='markers'),

            go.Scatter(x=df['Time'], y=df['STD_A1'],
                name='Sensor 2 std',
                mode='markers'),

            go.Scatter(x=df['Time'], y=df['STD_A2'],
                name='Sensor 3 std',
                mode='markers'),

            go.Scatter(x=df['Time'], y=df['STD_A3'],
                name='Sensor 4 std',
                mode='markers'),

            go.Scatter(x=df['Time'], y=df['STD_A4'],
                name='Sensor 5 std',
                mode='markers')])
py.offline.plot(fig2)
`

**Comment by empet** [comment]
Here is a sample code on how your plots (traces) can be included in two subplots:
```
from plotly.subplots import make_subplots
import plotly.graph_objects as go

fig = make_subplots(rows=2, cols=1, vertical_spacing=0.085,
                   subplot_titles=("Title 1", "Title 2"))
fig.add_trace(go.Scatter(), 1,1)  #or fig.add_scatter(x=, y=....)
fig.add_trace(go.Scatter(), 1,1) 
fig.add_trace(go.Scatter(), 1,1)  
fig.add_trace(go.Scatter(), 1,1)  
fig.add_trace(go.Scatter(), 2, 1)
.
.
.
fig.add_trace(go.Scatter(), 2, 1)
fig.update_layout(title_text="Global title", title_x=0.5,
                  width=700, height=600)
```

**Comment by amitsou** [comment]
Thank's a lot, it works just fine!

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
