### ISSUE TITLE
Minor documentation in Magic Underscore Notation page

### ISSUE THREAD

**Issue by rsgoodwin** [plotly/plotly.py#3001]
While walking through the "Python > Fundamentals > Creating and Updating Figures" I think I found a minor documentation error in the "[Magic Underscore Notation](https://plotly.com/python/creating-and-updating-figures/#magic-underscore-notation)" section.

**As Is**
The title of the first plot is "A Graph Object Figure With Magic Underscore Notation"

**Should Be**
The title should be "A Graph Object Figure **Without** Magic Underscore Notation"

**Comment by nicolaskruchten** [comment]
Thanks! Should be resolved shortly :)

**Comment by rsgoodwin** [comment]
:) thanks!
