### ISSUE TITLE
relating the index of fig.data to row and col

### ISSUE THREAD

**Issue by ghost** [plotly/plotly.py#3023]
I am trying to plot a diagonal line per facet where each facet has its own axes scales. 
fig.data can get me the proper range per facet via 

```
for i, d in enumerate(fig.data):
    x0, x1= d.x.min(), d.x.max()
```
If I would had known the right row and col of each facet i, I would then use:
`fig.add_shape(type='line',x0=x0, x1=x1, y0=x0, y1=x1, row=row, col=col)`

However, to relate the index in data to the row and col needed to plot the new line is a kind of nightmare.
I tried a lot of stuff including `fig._grid_ref` but still no success.

help please !

**Comment by nicolaskruchten** [comment]
`row` and `col` are shortcuts to setting `xref` and `yref` on the underlying `shape` object. If you want to add a shape per trace, you can manually set `xref` and `yref` to match the trace's `xaxis` and `yaxis`, respectively:

```python
import plotly.express as px

df = px.data.tips()

fig = px.scatter(df, x="total_bill", y="tip", facet_col="day", facet_col_wrap=2)
for trace in fig.data:
    fig.add_shape(
        type="line",
        x0=trace.x.min(), 
        x1=trace.x.max(), 
        y0=trace.y.min(), 
        y1=trace.y.max(),
        xref=trace.xaxis,
        yref=trace.yaxis
    )
fig.show()
```

![image](https://user-images.githubusercontent.com/203523/104513936-7204da80-55be-11eb-89a2-af56d6c784d7.png)

**Comment by hanan-vian** [comment]
Thanks @nicolaskruchten !
I want to make the plots square and equal scaled.
How does this generalize to update_xaxes? It does not get as input the xref nor yref as input.

**Comment by nicolaskruchten** [comment]
Something like this? I'm not sure how your previous question relates to your current one :) 

```python
import plotly.express as px

df = px.data.tips()

fig = px.scatter(df, x="total_bill", y="tip", facet_col="day", facet_col_wrap=2)
fig.update_xaxes(constrain="domain", range=[0,60])
fig.update_yaxes(constrain="domain", scaleratio=1, scaleanchor="x", range=[0,60])
fig.show()
```

**Comment by hanan-vian** [comment]
I guess I have not explained myself well. 
I would like different ranges per facet (subplot). 
However, the update_xaxes does not get xref as argument. only col and row.

```
Signature:
fig.update_xaxes(
    patch=None,
    selector=None,
    overwrite=False,
    row=None,
    col=None,
    **kwargs,
)
```

**Comment by nicolaskruchten** [comment]
Are you manually computing the ranges or do you want them to be automatically computed?  Are you creating your figure using a `plotly.express` method or using `make_subplots` ?

**Comment by hanan-vian** [comment]
I use `plotly.express`. I am manually computing the ranges. I guess I want to do something very like your first answer but also change axes on top of plotting a line. You have suggested to pass `xref=trace.xaxis, yref=trace.yaxis` to `fig.add_shape`. I want to do something similar but to `fig.update_xaxes`

**Comment by nicolaskruchten** [comment]
OK, so your first step is probably to unmatch the axes:

```python
fig.update_xaxes(matches=None)
fig.update_yaxes(matches=None)
```

Then it'll be a bit gross, but to update the `xN` axis, you can pass `selector=(N-1)` to `fig.update_xaxes()` to set its range and anchor.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
