### ISSUE TITLE
[feature request] add icons in legend

### ISSUE THREAD

**Issue by sdementen** [plotly/plotly.py#3024]
The symbol before an item in a legend in a plotly chart is a mix of fill/lines/symbols.
For instance, with a legend like
![image](https://user-images.githubusercontent.com/1304950/104592983-5279ba80-566f-11eb-8e5f-73321359f577.png)
we have in the svg
```
<g class="layers">
    <g class="legendfill">
        <path class="js-fill" d="M5,-2h30v6h-30z"
              style="stroke-width: 0; fill: rgb(0, 204, 150); fill-opacity: 0.5;"></path>
    </g>
    <g class="legendlines">
        <path class="js-line" d="M5,-2h30"
              style="fill: none; stroke: rgb(0, 204, 150); stroke-opacity: 1; stroke-width: 2px;"></path>
    </g>
    <g class="legendsymbols">
        <g class="legendpoints"></g>
    </g>
</g>
```

I would like to be able to replace the "layers" part with an icon to get a legend similar to for instance https://www.rte-france.com/eco2mix/la-production-delectricite-par-filiere (the color of the icon would be the one of the "legendfill" or "legendpoints", depending on the kind of chart).

**Comment by nicolaskruchten** [comment]
You can directly set the `fillcolor` to be the same as the line color, to get roughly the same effect:

```python
import plotly.express as px
fig = px.area(px.data.gapminder(), x="year", y="pop", color="continent", line_group="country")
fig.for_each_trace(lambda t: t.update(fillcolor=t.line.color))
fig.show()
```

![image](https://user-images.githubusercontent.com/203523/104635243-9f5d9100-566f-11eb-80b7-48e5067d10f0.png)

**Comment by nicolaskruchten** [comment]
Ah, sorry, that page finally loaded the actual icons on top of the solid fill color. Right now the best I could recommend to get some sort of picture in the legend would be to use emojis within your category names :)

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
