### ISSUE TITLE
properly overlap ohlc/candlesticks of different widths

### ISSUE THREAD

**Issue by pjadzinsky** [plotly/plotly.py#3027]
Hi,
Thanks for a great package

i think this is a bug, please see the code below. I'm overlaying two Ohlc (same with Candlesticks), each with its own width but they are not displayed correctly. I don't think this is the intended behavior. Note that when displaying just one trace the horizontal lines almost overlap (which is the expected behavior) but when more than one trace (fig1) this doesn't happen and looks like there are gaps in the data. 

I understand that for a candlesticks plot, having a candle right next to the other might not look appealing (and plots are very appealing now) but as it is now, it is difficult to reason which datapoint in data_1 has the data in datapoint in data_2 (when a point in data_2 folls in between points in data_1). Maybe these methods should accept some type of notion of how `long` each point represents (in terms of x axis, meaning I would like to say 1d and 6h in each in either seconds, ms, timedelta, etc).

hope it is clear, thanks again

```
import pandas as pd
import plotly.graph_objects as go
from datetime import datetime

periods = 10
data_1 = pd.DataFrame(
    {
        "time": pd.date_range(datetime(2021, 1, 1), datetime(2021, 1, 10), periods=periods),
        "high": [10] * periods,
        "low": [8] * periods,
        "close": [9] * periods,
        "open": [8.5] * periods,
    }
)
periods = 40
data_2 = pd.DataFrame(
    {
        "time": pd.date_range(datetime(2021, 1, 1), datetime(2021, 1, 10), periods=periods),
        "high": [15] * periods,
        "low": [13] * periods,
        "close": [14] * periods,
        "open": [13.5] * periods,
    }
)

ohlc_1 = go.Ohlc(
    x=data_1.time,
    open=data_1.open,
    high=data_1.high,
    low=data_1.low,
    close=data_1.close,
    tickwidth=0.5,
    name="1d",
)
ohlc_2 = go.Ohlc(
    x=data_2.time,
    open=data_2.open,
    high=data_2.high,
    low=data_2.low,
    close=data_2.close,
    name="6h",
)
fig1 = go.Figure()
fig1.add_trace(ohlc_1)
fig1.add_trace(ohlc_2)
fig1.show()

fig2 = go.Figure()
fig2.add_trace(ohlc_1)
fig2.show()

```

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
