### ISSUE TITLE
BUG: Heatmapgl does not show at all in subplots, and other bugs

### ISSUE THREAD

**Issue by erezinman** [plotly/plotly.py#3031]
Using python v3.6.9 & plotly v4.14.1 on Chrome I get several different bugs with Heatmapgl:

1. When adding Heatmapgl to a subplot, nothing's shown.
2. Heatmapgl has `"fast"` zsmoothing by default (in contrast to Heatmap which is `False`).
3. Heatmapgl's `zsmooth=False` results in a truncated auto-view.
4. Heatmapgl's does not allow zooming/panning from the axes, and double-click doesn't work.
5. Heatmapgl's toolbar has a lot less options. 

This trace feels half-baked. It is really too-bad that I can not use it because I wished to show large spectrograms, and I can't using plotly.

In more detail:

Consider the following code:

```
import plotly.graph_objs as go
from plotly.subplots import make_subplots

fig = make_subplots(rows=1, cols=2)
fig.add_trace(go.Heatmapgl(z=[[0, 1, 2], [2, 0, 1], [1, 2, 0]], colorscale='Picnic'), row=1, col=1)
fig.add_trace(go.Heatmap(z=[[0, 1, 2], [2, 0, 1], [1, 2, 0]], colorscale='Picnic'), row=1, col=2)
fig.show(renderrer='browser')
```

And I get a blamk page with a color bar:
![image](https://user-images.githubusercontent.com/4324329/104974577-20ff4700-5a01-11eb-8b39-49100ee894fe.png)

Note that the same happens with other kinds of traces as secondary to Heatmapgl (like Scattergl).

Now, if I comment-out either lines, I get the traces as expected, only that for the Heatmapgl, I get a strange smoothing by default:
![image](https://user-images.githubusercontent.com/4324329/104974732-85baa180-5a01-11eb-8f0d-45b83d2c0442.png)
![image](https://user-images.githubusercontent.com/4324329/104974744-910dcd00-5a01-11eb-9ffe-f4af0e5c595c.png)

So I went ahead and set `zsmooth=False` for the Heatmapgl, and I got:
![image](https://user-images.githubusercontent.com/4324329/104975467-69b7ff80-5a03-11eb-8619-4cb69ab67093.png)

Note the missing buttons in the toolbar ("spike-lines" and "compare" which exist in Heatmap). I wasn't able to pan and zoom the plot by dragging the axes in the usual places. Also, after panning using the toolbar button, double-click did not return me to the original view.

Thanks.

**Comment by adriwitek** [comment]
Same problem too

**Comment by nicolaskruchten** [comment]
We are deprecating the `heatmapgl` trace in the next version of Plotly.js (2.0) and Plotly.py (5.0) which should be out in a couple of weeks. There are indeed many problems with this trace and we will like not be able to fix them, so we will try to improve the performance of `heatmap` instead.

**Comment by Jahn-KSB** [comment]
please bring the heatmapGL back! :D
