### ISSUE TITLE
JupyterLab prebuilt extensions

### ISSUE THREAD

**Issue by nicolaskruchten** [plotly/plotly.py#3036]
JupyterLab 3 supports "prebuilt" `pip`-installable extensions in addition to "source" extensions like the ones we've been publishing to NPM. We should come up with a plan to include those in our release process somehow.

See discussion in https://github.com/plotly/plotly.py/issues/2994

**Comment by koenlek** [comment]
Does plotly have any rough timeline in mind for supporting this?

It would be very convenient if I could rely fully on pip for setting up a jupyter lab environment (including plotly support).

**Comment by nicolaskruchten** [comment]
We can't commit to a timeline for doing this at the moment, but I'd love a hand! Right now our partly-manual/partly-automated release process is documented here: https://github.com/plotly/plotly.py/blob/master/release.md ... I would happily accept a PR that expands on this with some easy-to-follow steps that result in a pip-installable extension in addition to the current ones. Such a PR might include a script or two to build these extensions etc to keep the manual burden low :)

**Comment by nicolaskruchten** [comment]
So JupyterLab 3 *is* supported, just not with the "prebuilt" extensions. I'm not sure what you're asking regarding inline vs popup but it seems unrelated to this particular issue... ? Perhaps create another issue? :)

**Comment by koenlek** [comment]
This is great! When could we start seeing this on pypi? I'm happy to test a beta/RC if possible :)

**Comment by nicolaskruchten** [comment]
This will come out as part of 5.0 and we'll have an RC out on PyPI in a week or two I hope.

**Comment by koenlek** [comment]
Any news on a beta/RC that I could test? 🙏

**Comment by nicolaskruchten** [comment]
I'm hoping to have a beta out this week or next.

**Comment by nicolaskruchten** [comment]
OK, if someone wants to kick the tires on it, `pip install plotly==5.0.0rc1` should "just work" and install the prebuilt extension and it'll all just work in JLab3 regardless if you have our other extensions already installed.

**Comment by koenlek** [comment]
Works like a charm for me!

**Comment by nicolaskruchten** [comment]
This is now released as part of v5.0.
