### ISSUE TITLE
Lineplot overlapping when setting color input

### ISSUE THREAD

**Issue by AdamKubovic** [plotly/plotly.py#3038]
Hey,

I am trying to create sort of caterpillar plot which is based on a dataframe containing information regarding the distributional properties of the posterior sample of the parameter. The idea is to utilize dash with filtering options. As I am running a hierarchical model, I would like to be able to compare the multiple audience parameters.

In the code, I am using plotly.express.line as my go to plot and than add different traces for mean and the Confidence interval bounds. The plot looks something like this.

![example](https://user-images.githubusercontent.com/55055556/105324184-64a5ac80-5bcb-11eb-89d4-7ddaefabcd1c.png)

The problem is that the lines overlap while I would like to have them above each other. I was trying different commands directly in the plotly.express.line or through update_traces(), however, I was not able to figure out how to meet my desired output. This is the current iteration of the code:

```
    fig = px.line(thin_data, x='effect', y='var_name', line_group='var_name', color=color_facet,
                  facet_col=dims_facet, facet_col_spacing=0.1)
    fig.update_traces(hovertemplate="<b> 90% CI Bounds </b> <br>%{x:.4f}",
                      marker_opacity=0.5)
                      
    thick_line = px.line(thick_data, x='effect', y='var_name', line_group='var_name', color=color_facet,
                         facet_col=dims_facet, facet_col_spacing=0.1)
    thick_line.update_traces(line_width=5, marker_opacity=0.5,
                             hovertemplate="<b>50% CI Bounds</b> <br>%{x:.4f}")

    mean_line = px.scatter(mean_data, x='effect', y='var_name', color=color_facet,
                           facet_col=dims_facet, facet_col_spacing=0.1,
                           text='effect')
    mean_line.update_traces(hovertemplate="<b>Mean</b> <br>%{x:.4f}",
                            texttemplate="<b>%{text:.2f}</b>",
                            marker_size=15, textposition='top center',
                            textfont_size=15)
                            
    add_trace = lambda x, y: fig.add_trace(x['data'][y])
    for plot in (thick_line, mean_line):
        trace_len = range(len(plot['data'])) if len(plot['data']) else 0
        for i in trace_len:
            add_trace(plot, i)
```
            
I know from experience that when using e.g. px.box() and setting the color as a column in the DataFrame, the resulting plot is not having overlapping boxplots - I would like to have that with the lineplot if possible. I also came across plotly.express.strip() which results in the desired outcome but I was not able to connect the points in order to create a line plot. I am thankful for any tips.

Thank you

**Comment by nicolaskruchten** [comment]
Unfortunately, the `scatter` trace which powers line plots doesn't support "grouped" or "dodged" categorical axes, so you'll have to use different Y coordinates here like "Parameter 1 - target" and "Parameter 1 - non_target" to get them to render vertically offset from each other.

**Comment by AdamKubovic** [comment]
Thank you very much for the quick response. I see. I was hoping that I am potentially missing something 😄 But I was wondering, is there a plan to maybe implement dodging of the categorical axes in  the future or is this something that is not of priority at the moment ?

**Comment by nicolaskruchten** [comment]
It's not on anyone's roadmap that I know of at the moment, but a pull request into Plotly.js would certainly be welcomed!

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
