### ISSUE TITLE
Sunburst labels have erratic behavior

### ISSUE THREAD

**Issue by buckeye17** [plotly/plotly.py#3042]
My sunburst chart in a Dash application is showing strange behavior with labels disappearing.  I have played with the parameters which define the chart for a few hours, trying to isolate the cause.  But I've concluded the parameters aren't the cause.  Instead, the user interaction seems to be the cause.  One sequence of clicks will quickly cause the problem every time.  Other sequences are slower to cause the problem, but eventually all long sequences seem to encounter the problem.  These problems occur in both Chrome and Edge web browsers.  Once the problem is first encountered, some further interactions may allow the labels to come back, but eventually all the labels will disappear with enough clicks.

Here's a bad sequence, where it only takes 3 clicks to cause the problem of disappearing labels.
![Sunburst-bad](https://user-images.githubusercontent.com/17264335/105564961-77ff6780-5cf2-11eb-9b57-dae882d68e22.gif)

Here's a better sequence, where it takes 9 clicks to encounter the problem.
![Sunburst-better](https://user-images.githubusercontent.com/17264335/105564962-79309480-5cf2-11eb-8a38-bc3c015def17.gif)

**Comment by buckeye17** [comment]
Just a follow-up on this bug.  Once the labels become hidden, I figured out that my moving my mouse off of the plotly figure will allow of the labels to become visible again.

**Comment by jimmy6727** [comment]
<img width="329" alt="Screen Shot 2021-08-31 at 4 44 11 PM" src="https://user-images.githubusercontent.com/42276025/131589688-f9f9a2af-1142-4e3d-8c86-da827836996d.png">
<img width="282" alt="Screen Shot 2021-08-31 at 4 44 23 PM" src="https://user-images.githubusercontent.com/42276025/131589693-349fdc87-0380-47f8-b7bf-1350feb5bf2a.png">

Seeing similar funky behavior and disappearing labels in Chrome Version 92.0.4515.159 64-bit on a Surface Pro Laptop.

**Comment by buckeye17** [comment]
@jimmy6727 I eventually discovered that this glitch would be "fixed" by simply moving the cursor outside the figure boundary.

**Comment by jimmy6727** [comment]
@buckeye17 I was able to fix this by upgrading to Plotly version 5.3.1 which calls the updated Plotly.js version 2.4.2

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
