### ISSUE TITLE
Plotly Express labels dict not applying to traces generated with the color keyword

### ISSUE THREAD

**Issue by daviddekoning** [plotly/plotly.py#3049]
I have a dataframe that I am using to generate an area chart with three components. These components are split out using the `color` keyword. Unfortunately, the `labels` keyword only renames the title of columns, not the names of traces generated by the `color` keyword. In the example below, it would be great to be able to replace `steady`, `new_users` and `churn` with more descriptive labels.

Of course, I can work around this by modifying the original data frame, but the `labels` dict is so elegant...

![image](https://user-images.githubusercontent.com/2060138/105997199-55b27480-6079-11eb-9125-d0722db9ec5b.png)

**Comment by nicolaskruchten** [comment]
Right, the `labels` only operate on column names today, although I can see why for figures like this one, legend item text like "steady" could be thought of as a "label". I might be open to a new keyword argument for this to remap values... 

in the meantime, you can swap these out post-`px` like this:

```python
import plotly.express as px

df = px.data.tips()

fig = px.scatter(df, x="total_bill", y="tip", color="day")
value_map = { "Sun": "Sunday",  "Sat": "Saturday" }
for trace in fig.data:
    trace.name = value_map.get(trace.name, trace.name)

# or the chainable function version
fig.for_each_trace(lambda t: t.update(name=value_map.get(t.name, t.name)))

fig.show()
```

**Comment by daviddekoning** [comment]
That's very helpful, thanks!

**Comment by janosh** [comment]
I was expecting `px.defaults.labels` to apply to the legend labels as well.  If this issue gets a PR, would be great if this 

```py
import plotly.express as px

px.defaults.labels = {
    "sepal_length": "Sepal Length (cm)",
    "sepal_width": "Sepal Width (cm)",
    "petal_length": "Petal Length (cm)",
    "petal_width": "Petal Width (cm)",
    "species": "Species",
    "setosa": "Setosa",
    "versicolor": "Versicolor",
    "virginica": "Virginica",
}

df = px.data.iris()
fig = px.scatter_matrix(df, dimensions=["sepal_length", "sepal_width"], color="species")
```

![plotly express iris](https://user-images.githubusercontent.com/30958850/195922296-ceb3ac35-309f-4c70-9f2d-b7e095b5b20a.png)

**Comment by nicolaskruchten** [comment]
This is by design: the individual species here are **data** rather than **metadata** like the column names ares, so they are not relabelled via `labels`.

**Comment by janosh** [comment]
While these strings come from column data, when shown in the legend, they should count as labels and be subject to `px.defaults.labels` imo.

**Comment by avm19** [comment]
@nicolaskruchten wrote:
> Right, the `labels` only operate on column names today, although I can see why for figures like this one, legend item text like "steady" could be thought of as a "label". I might be open to a new keyword argument for this to remap values...

This semantics is very confusing. Every column of a dataframe either becomes an axis (x, y, colour, shape, facet_rows etc) or is discarded. There is no logical reason to treat colour/shape columns differently compared to other kinds of columns. I guess this different treatment is related to the fact that colour/shape columns define multiple traces within a single figure or facet. While this may make some sense to a plotly developer, it is baffling to users: [1](https://stackoverflow.com/questions/72885525/plotly-cannot-manually-specify-labels-legend-entries-in-multiple-line-chart), [2](https://stackoverflow.com/questions/72986882/how-do-i-modify-the-labels-of-data-in-plotly-with-python-no-pandas). The docstring for `labels` does not make such a distinction.

In janosh's example the dataframe is **tall**. The `"species"` column values define the colour. This column is unaffected by `labels=...`, although he expects this.

In OP's example, the dataframe is **wide**. Here is another example. The columns `["tip", "total_bill"]` correspond to two separate colours (and their values correspond to y-axis). These columns are again unaffected by `labels=...`.

```python
import plotly.express as px
df = px.data.tips()
fig = px.line(df, y=["tip", "total_bill"],
              labels={'value': 'Value (USD)', 'tip': 'Tip (USD)', 'total_bill': 'Bill (USD)'})
fig.update_layout(width=600, height=300)
fig.show()
```
![image](https://github.com/plotly/plotly.py/assets/52547519/464adcfd-72ee-4698-86a0-85e3e1fa4fc7)

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
