### ISSUE TITLE
Updating "JupyterLab Support" Docs + Prebuilt JupyterLab 3.0 extension

### ISSUE THREAD

**Issue by layne-sadler** [plotly/plotly.py#3055]
Greetings. Is this section of the documentation still up-to-date?
https://github.com/plotly/plotly.py#jupyterlab-support

As you probably know, JupyterLab 3.0 allows for prebuilt extensions that can be pip installed. This removes the user-facing dependency on Node.js and skips the lengthy extension/ lab build process, which results in a much smoother experience. Additionally, you could specify `ipywidgets` as a pypi dependency of the extension's `setup.py` `install_requires=[]`. Making the installation process a one-liner.

Thank you.

**Comment by nicolaskruchten** [comment]
Yes, this section is up to date. We are aware of prebuilt extensions and will include them in our build process in the future, we just haven't gotten around to it yet. See https://github.com/plotly/plotly.py/issues/3036

**Comment by nicolaskruchten** [comment]
OK, if someone wants to kick the tires on it, pip install plotly==5.0.0rc1 should "just work" and install the prebuilt extension and it'll all just work in JLab3 regardless if you have our other extensions already installed.

**Comment by aiqc** [comment]
@nicolaskruchten Success!

- Uninstalled plotly-charts or whatever the extension was called.
- Rebuilt jupyterlab env.
- Plots failed to display as expected.
- Installed plotly==5.0.0rc1.
- Plots failed to load.
- Restarted kernel.
- Plots failed to load.
- Restarted jupyterlab server.
- Plots succeeded.

![image](https://user-images.githubusercontent.com/74990642/120510355-56e10e80-c397-11eb-9a9f-e586b9b1017a.png)

**Comment by aiqc** [comment]
@nicolaskruchten would you guys be interested in demoing it at next month's community call?

**Comment by nicolaskruchten** [comment]
Glad it's working well! I'd be happy to chat about our stuff any time but really in this particular case it's all @fcollonval's work here so maybe ask them? This was the (epic) PR that resolved a whole bunch of open issues in our extension all at once: https://github.com/plotly/plotly.py/pull/3142

**Comment by aiqc** [comment]
Ohhhh @fcollonval now I see what you were saying by "you did it." Ha.

**Comment by nicolaskruchten** [comment]
This is now released as part of v5.0.
