### ISSUE TITLE
Documentation misspells

### ISSUE THREAD

**Issue by jmonticolo** [plotly/plotly.py#3074]
I was consulting the Plotly Python documentation and I ran into some misspells : `dictioanry` instead `dictionary`.

- [380](https://github.com/plotly/plotly.py/blob/03979d105c65dda3df3a155322eaff18f203b03f/packages/python/plotly/_plotly_utils/colors/__init__.py#L380),
- [500](https://github.com/plotly/plotly.py/blob/03979d105c65dda3df3a155322eaff18f203b03f/packages/python/plotly/_plotly_utils/colors/__init__.py#L500),
- [502](https://github.com/plotly/plotly.py/blob/03979d105c65dda3df3a155322eaff18f203b03f/packages/python/plotly/_plotly_utils/colors/__init__.py#L502).

**Comment by nicolaskruchten** [comment]
Thanks for letting us know! We'd be happy to accept a pull request to fix these :)

**Comment by jmonticolo** [comment]
I fixed [this issue](https://github.com/plotly/plotly.py/blob/03979d105c65dda3df3a155322eaff18f203b03f/packages/python/plotly/_plotly_utils/colors/__init__.py#L419) (with other misspells) but before PR, on which branch to PR for the v5 bump ?
