### ISSUE TITLE
named_colorscales() missing in plotly express

### ISSUE THREAD

**Issue by vsathwikm** [plotly/plotly.py#3077]
I was trying to execute sample code to run jupyter dash and stumbled upon this sample code.

`import plotly.express as px
from textwrap import wrap

named_colorscales = px.colors.named_colorscales()
print("\n".join(wrap("".join('{:<12}'.format(c) for c in named_colorscales), 96)))`

It returns the following error
`AttributeError: module 'plotly.express.colors' has no attribute 'named_colorscales'`

![image](https://user-images.githubusercontent.com/11830096/108269362-dece4000-713b-11eb-9731-8f49ba3a4925.png)

**Comment by nicolaskruchten** [comment]
Which version of `plotly` are you using? The latest version is 4.14.3

**Comment by vsathwikm** [comment]
I was using 4.0.0. Upgrading solved the issue. Thank you very much.
