### ISSUE TITLE
New feautre suggestion

### ISSUE THREAD

**Issue by saksham7778** [plotly/plotly.py#3082]
I want to make a gantt chart with around 10 lakh values(integers from 0-10,00,000on x axis and not as dates, is this possible? Please help

**Comment by nicolaskruchten** [comment]
This is possible using `go.Bar` and width/base/offset, but `px.bar` is designed to work specifically with dates.

**Comment by saksham7778** [comment]
But i have to draw blocks at diff places (for eg when y=1 and x=10 to x =20 i want to make yellow box for y=1 x=40 to x=70 i want to make red box ) is this possible?

**Comment by nicolaskruchten** [comment]
Yes, you can use the `base` attribute of `bar` traces for this.

**Comment by saksham7778** [comment]
First of all thanks for replying @nicolaskruchten 
I am doing something like this(see the code below )  and getting gannt charts, but I want to generate graphs for more data but when I am unresponsive pages on chrome , what shall I do 
1) shall I use some other technique to plot charts ?
2) make changes in this code only 
3) or some thing else ?
fig1 = px.timeline(df1, x_start=start, 
                      x_end=end, 
                      y=abc, 
                      color=operation,  
                      hover_data= ["duration"] 
                      )

fig1.layout.xaxis.type = 'linear'

df1['delta'] = df1['end'] - df1['start']

no_of_unique_operations = len(pd.unique(df1['Operation']))
for i in range(0,no_of_unique_operations):
    fig1.data[i].x = df1.delta.tolist()

plotly.offline.plot(fig1, filename='try_plot1.html', auto_open=True)

with the above code i am getting kind of graph :
![image](https://user-images.githubusercontent.com/43813299/109188347-dbc8f480-77b8-11eb-86bf-ab1d16d349c3.png)

**Comment by Simon-Duque-Tisnes** [comment]
Following @nicolaskruchten pointers, you can try something like
```
fig = px.bar(df1, 
base="start",
x = "duration",
y="abc",
text = "duration",
color = "operation",
orientation='h'
)

fig.update_yaxes(autorange="reversed")
fig.show()
```

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
