### ISSUE TITLE
Sliders fail to update shape visibility

### ISSUE THREAD

**Issue by Prometheus3375** [plotly/plotly.py#3087]
Versions where bug was found:
- Python 3.9.2, Plotly 4.14.3
- Python 3.6.9, Plotly 4.4.1

```python
import plotly.graph_objects as go

fig = go.Figure()

fig.add_shape(
    type='circle',
    x0=-5,
    y0=-5,
    x1=5,
    y1=5,
)

fig.add_shape(
    type='circle',
    x0=-4,
    y0=-4,
    x1=4,
    y1=4,
)

steps = [
    dict(
        method='update',
        args=[
             {},
             {'shapes': [{'visible': True}, {'visible': True}]},
        ]
    ),
    dict(
        method='update',
        args=[
             {},
             {'shapes': [{'visible': False}, {'visible': True}]},
        ]
    ),
    dict(
        method='update',
        args=[
             {},
             {'shapes': [{'visible': True}, {'visible': False}]},
        ]
    ),
]
sliders = [dict(
    active=0,
    steps=steps
)]

fig.update_layout(
    sliders=sliders,
    width=800,
    height=800,
)

fig.update_xaxes(
    # showgrid=False,
    # zeroline=False,
    range=[-10, 10]
)
fig.update_yaxes(
    # showgrid=False,
    # zeroline=False,
    scaleanchor='x',
    scaleratio=1,
    range=[-10, 10]
)

fig.show()
```

![initial picture](https://user-images.githubusercontent.com/35541026/108852822-1c791000-75f7-11eb-925c-0158028aeb16.png)

After changing steps all shapes disappear, and a black square appears which is situated relative to the plot.

![after changing steps](https://user-images.githubusercontent.com/35541026/108852904-30bd0d00-75f7-11eb-998a-121f35d4ec89.png)

You can check this in this [Colab notebook](https://colab.research.google.com/drive/113cWuXiJQSYxV9mNtFLZ2h--58WUvDVG).
Absolutely the same behavior in jupyter and .py file.

**Comment by Prometheus3375** [comment]
Basically, sliders do not update, but overwrite existing shapes.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
