### ISSUE TITLE
My plotly graphs are very light in display. I have uninstalled and again installed the plotly , still the problem hinders.

### ISSUE THREAD

**Issue by chandrikaselvamani** [plotly/plotly.py#3088]
fig=px.bar(df,x="Client Category",color='Client Category',color_discrete_sequence=px.colors.qualitative.G10_r)
fig.show()

**Comment by nicolaskruchten** [comment]
Often with bar charts this is because each individual bar has a little outline so if there are many segments, the outlines are all you see. Consider using `px.histogram` instead, which aggregates the bar segments into one big bar.

**Comment by chandrikaselvamani** [comment]
Thank you for your inputs. Its working now
