### ISSUE TITLE
Default axis for boolean line graphs is inconsistent

### ISSUE THREAD

**Issue by jmrgibson** [plotly/plotly.py#3089]
I often use pandas/plotly for writing tests that process time series data. To help users debug where a test might have failed, I often plot the boolean result of some assertions they might be writing, for example

```python
# assume everything is a pandas series
difference = expected_data - measured_data
samples_out_of_bounds = difference.abs() > error_tolerance
# plot the measured data alongside the boolean array to see where it went wrong
if samples_out_of_bounds.any():
    print("test failed!")
    px.line(samples_out_of_bounds).show()
    px.line(measured_data).show()
    px.line(measured_data).show()
    # these would be on the same graph in reality, this is just quick demo code for now
```

however one thing that I've run into is that the boolean plots don't have a consistent ordering as to where they put `True` and `False`  on the Y axis, so sometimes `True` is at the top and sometimes `False` is at the top. This can be reproduced using the following code below, which produces two plots with different Y axis arrangements. 

```python
import plotly.express as px
import pandas as pd
px.line(pd.Series([False,False,True], [1, 2, 3])).show()  # puts `False` higher on the Y axis
px.line(pd.Series([True,False,False], [1, 2, 3])).show()  # puts `True` higher on the Y axis
```

I understand that I could configure the axis myself to avoid this, but the whole point of plotly express is that its very easy to quickly make useful plots, but this inconsistency makes things very frustrating when everything else works "out-of-the-box", especially in an interactive setting. 

I'm suggesting that `True` should be always at the top, and `False` should be always at the bottom for cases where all the data is of type `bool`, but am open to other ways that I could make this easier on myself

**Comment by nicolaskruchten** [comment]
Thanks for this comment!

Right now PX treats boolean columns as categoricals, and applies its built-in logic of "first come first serve" for the ordering, with optional override via the `category_orders` keyword argument. You can also set a session-wide default for a given category name like this: `px.defaults.category_orders = dict(value=[False, True])`.

I'll have to think about how/if to standardize this for boolean axes specifically :)

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
