### ISSUE TITLE
textfont.color property only accepts a single color in Scattermapbox, while a list can be passed in Scattergeo

### ISSUE THREAD

**Issue by guidocioni** [plotly/plotly.py#3091]
I need to set a different font color for every text marker in a `Scattermapbox` object. Unfortunately, for some reason, only a single color can be passed, while in `Scattergeo` this works without problems with a list of colors.

Is there a reason why it was implemented like this?
I thought the only difference between the two functions is that in the first case rasters from `mapbox` are used in background, while in the second case they are directly built into Plotly. 

If the markers are placed on the map in the same way I'm wondering why wouldn't be possible to replicate the same behaviour of `Scattergeo` in `Scattermapbox`. Or maybe is it because in the latter method a JSON is passed directly to `mapbox`? 

Unfortunately I don't know enough the codebase of `plotly` and I cannot seem to find the relevant part in the code where this is done, otherwise I may be able to work on a pull request to change this behaviour. Could someone point me in the right direction? :)

**Comment by nicolaskruchten** [comment]
mapbox and geo subplots are rendered totally differently (the former delegates to Mapbox GL JS and the latter is done in SVG) which usually explains any differences in API. This limitation would need to be addressed first in the underlying JS renderer, for which the code is here: https://github.com/plotly/plotly.js/tree/master/src/traces/scattermapbox

**Comment by guidocioni** [comment]
> Mapbox GL JS

Ok, that makes a lot of sense. 
I could not find any example on the Mapbox GL JS with scatter plots including text with varying colors, so I assume this is just not a common use case. Which means it would be difficult to change the default behaviour. 

Do you have any suggestions about a possible workaround?

**Comment by nicolaskruchten** [comment]
The only thing that comes to mind would be to have a trace per point, which is not ideal, but could work :)

**Comment by guidocioni** [comment]
> The only thing that comes to mind would be to have a trace per point, which is not ideal, but could work :)

Yeah that would not be ideal. I already thought of using `Scattergo` instead and trying to change the background using tiles from `openmabox`, however the difference is that in `Scattermapbox` superclustering is also active and overlapping points are hidden depending on the zoom level, which I find really useful in this case. I believe this comes from the Mapbox GL JS and is not really done by plotly.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
