### ISSUE TITLE
fig.show() Times Out

### ISSUE THREAD

**Issue by dtoniolo** [plotly/plotly.py#3102]
**Versions**
Platform: macOS Catalina 10.15.7
Python: 3.8.5
Plotly: 4.14.3

**Description of the Issue**
When attempting to show any figure, the method `fig.show()` hangs about half of the time:
- sometimes the figure is shown correctly
- sometimes the plot is never drawn and the browser stops attempting to connect to the web page, with no resulting error from Plotly
- sometimes the plot is never drawn and the `fig.show()` method throws a `ConnectionTImedOut` error

Here's a minimum reproducible example:
```{python}
import numpy as np
import plotly.graph_objects as go

 a = np.arange(10)
fig = go.Figure(go.Scatter(x=a, y=a))
fig.show()
```

**Additional Details**
The problems also occurs with Plotly 4.10. Both Safari and Firefox can't connect to Plotly's visualisation server, so I guess the problem is on the Plotly itself.

**Comment by MlHsieh** [comment]
Same problem here.

Firefox 86.0.1 on windows 10.

Browser hang at some webpages of plotly's online documents as well. Like [3D Surface Plot](https://plotly.com/python/3d-surface-plots/).
![image](https://user-images.githubusercontent.com/61381271/111567887-ac673f80-87da-11eb-9254-33ca5d89c5b5.png)
I think plotly's server has some problem.

**Comment by MlHsieh** [comment]
The problem is related to extension **DuckDuckGo Privacy Essentials**.
Solve the problem after disabling the extension.

**Comment by dtoniolo** [comment]
I seem to have the same problem regardless of the browser. I don't have *DuckDuckGo Privacy Essentials* installed, but Safari 14 new privacy features might be involved here. On Firefox the problem might be caused by the adblocker, next time that the problem comes up I'll try disabling it

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
