### ISSUE TITLE
`to_html` method does not output a renderable HTML string in Jupyter

### ISSUE THREAD

**Issue by jonsnowseven** [plotly/plotly.py#3104]
Hello.

I am having an issue rendering the HTML content outputted from `to_html` method.

## Versions

* Python 3.8
* Plotly 4.14.3

## Code to reproduce

```python
import plotly.express as px
from IPython.display import HTML

df = px.data.iris()
fig = px.scatter(df, x="sepal_width", y="sepal_length", color="species")
HTML(fig.to_html())
```

## Output
![image](https://user-images.githubusercontent.com/25992803/110353892-7fbf6500-802f-11eb-9308-81c3a9d0ae88.png)

## Browser page inspection (from Brave)
![image](https://user-images.githubusercontent.com/25992803/110354714-5f43da80-8030-11eb-9afd-34ffcc167eaf.png)

**Comment by j-carson** [comment]
Have you tried it this way?

```python
from IPython.display import display, HTML
...
display(HTML(fig.to_html())
```

**Comment by jonsnowseven** [comment]
@j-carson, It should be the same outcome because Jupyter displays the last line of the cell. Nonetheless, I tried and had the same result (no content is shown).

**Comment by nicolaskruchten** [comment]
I'm confused about what the use-case is for this, vs `fig.show()` ?

**Comment by jonsnowseven** [comment]
@nicolaskruchten, I want to export the Plotly graph as HTML to use in other environments. When I tried to load the HTML content produced by `to_html`, the outcome was not the expected. Hence, I got reproducible code to show that the HTML export did not behave as expected.

**Comment by nicolaskruchten** [comment]
Does `fig.write_html("path/to/file.html")` result in a usable HTML file for you?

**Comment by nicolaskruchten** [comment]
If you look at the [docstring for `to_html`](https://plotly.com/python-api-reference/generated/plotly.graph_objects.Figure.html#plotly.graph_objects.Figure.to_html) you might find some options there that would let you get the output you're looking for... by default it outputs a whole HTML file, which is likely not what you want to be injecting into notebook output... Try using `full_html=False` to see if it does what you're looking for?

**Comment by jonsnowseven** [comment]
I tried both those options like this:

```python
import io
import plotly.express as px
from IPython.display import HTML, display
df = px.data.iris()
fig = px.scatter(df, x="sepal_width", y="sepal_length", color="species")
string_io = io.StringIO()
fig.write_html(string_io, full_html=False) # also tried with full_html=True
HTML(string_io.getvalue())
```

But both were unsuccessful in showing the HTML content. **Although**, if I save the content in an HTML file and open it in my browser, I can see the plot correctly.

**Comment by nicolaskruchten** [comment]
That's not super surprising... the HTML that comes out of `to_html()` is not particularly designed to be injected into Jupyter like this... that use-case is what `fig.show()` is for :)

**Comment by jonsnowseven** [comment]
Yes, I understand that. I was expecting to render the HTML output from `to_html` wherever HTML can be rendered. Thank you.
