### ISSUE TITLE
Weird interactions between hover_data and wide-format y in plotly.express.scatter

### ISSUE THREAD

**Issue by benlindsay** [plotly/plotly.py#3108]
If I use column names in the wide-format `y` and have those same column names in the `hover_data`, I run into some weird interactions.

As an example, start with a simple dataframe, and plot 2 columns of that data:

```py
import plotly.express as px
import pandas as pd

df = pd.DataFrame({"a": [0, 1, 2, 3], "b": [4, 5, 6, 7], "c": [8, 9, 10, 11]})
px.scatter(
    df,
    x="a",
    y=["b", "c"],
)
```

This works great and leads to the expected plot that looks like this:

![image](https://user-images.githubusercontent.com/9361152/110678142-984c8e00-819b-11eb-9e5c-340714220391.png)

Then if I want to be able to see both the "b" and "c" values in each point, I try to add those as hover_data, like so:

```py
px.scatter(
    df,
    x="a",
    y=["b", "c"],
    hover_data=["b", "c"],
)
```

But this results in an error, I'm guessing because there's some dataframe melting operation going on in the background?

![image](https://user-images.githubusercontent.com/9361152/110678751-43f5de00-819c-11eb-9c93-156f69d26375.png)

If I try the same thing with only one of the columns as a `hover_data` column, it excludes that column from the plot:

```py
px.scatter(
    df,
    x="a",
    y=["b", "c"],
    hover_data=["b"],
)
```

![image](https://user-images.githubusercontent.com/9361152/110679515-283f0780-819d-11eb-8464-1781f8f4a065.png)

This is with version 4.14.3. Is there a way to accomplish what I'm trying to do without doing some funky dataframe manipulations myself?

**Comment by benlindsay** [comment]
That makes sense. And this is probably too much of an edge case to warrant a PR to enable this sort of thing right? Thinking about this more, the manipulations wouldn't be too funky if I'm doing them outside of px, like

```
import plotly.express as px
import pandas as pd

df = pd.DataFrame({"a": [0, 1, 2, 3], "b": [4, 5, 6, 7], "c": [8, 9, 10, 11]})
y = ["b", "c"]
hover_data = ["b"]

columns_i_gotta_duplicate = list(set(hover_data).intersection(set(y)))
tmp_df = df.copy()
for c in columns_i_gotta_duplicate:
    tmp_df[f"___tmp___{c}"] = tmp_df[c]
id_vars = set(tmp_df.columns) - set(y)
melted_df = (
    tmp_df.melt(id_vars=id_vars, value_vars=y)
    .rename(columns=lambda c: c.replace("___tmp___", ""))
)

px.scatter(
    melted_df,
    x="a",
    y="value",
    color="variable",
    hover_data=hover_data
)
```

so like an extra 9-ish lines of code. If I were to translate that into a PR (absolutely no promises), how much more complicated would it get, and either way, would that be a welcome addition or would the juice not be worth the squeeze?

**Comment by nicolaskruchten** [comment]
The resulting PR would probably be pretty hairy, unfortunately, due to the necessary bookkeeping of the column names among all the internal dataframe transformations that PX does today, otherwise you'd likely end up in a situation where the "___tmp___" columns are in the "final" internal dataframe and fail to match the contents of `hover_data`. This is a pretty annoying problem that's crying out for a generic solution, as we encounter it in situations like `px.sunburst` or `px.timeline`  as well.

The mainline operation of PX when it's not manipulating the input dataframe is just to look at the input and match up the kwargs against the columns: this is easy. When we internally transform the input by melting or rearranging the columns from a "path"-based shape in `px.sunburst` or whatever, the column names of the intermediate DF don't really match up so well against the values a user rightly supplies in kwargs like `hover_data` and this causes issues.

**Comment by benlindsay** [comment]
Gotcha, thanks for the info! I'll stick to pre-melting my dataframes then :)

**Comment by Gullumluvl** [comment]
> When we internally transform the input by melting or rearranging the columns [...], the column names of the intermediate DF don't really match up so well against the values a user rightly supplies in kwargs like `hover_data` and this causes issues.

Hi there, I was planning to open an Issue but I think I encountered this problem (with `px.scatter`).

Sorry to ask clarifications, but would it be possible to output an error or at least a warning? As shown by the OP, there is zero message but the output is wrong.

Here is my tiny example:

```python
df = pd.DataFrame({'x':  [1,2,3],
                   'y1': [0.1, 0.2, 0.05],
                   'y2': [10, 11, 13.5]})

fig = px.scatter(df0,
                 x='x',
                 y=['y1', 'y2'],  # Wide-form.
                 facet_row='variable',
                 hover_data={'x':True, 'y1': False, 'y2': False}   # WRONG because 'y1' and 'y2' are not in the transformed data-frame.
)
fig.show()  # This only shows the `x` VS `y2` plot, without any complain. 
```

The correct `hover_data` argument should be

```python
                hover_data={'x':True, 'variable': False}
```

If I ask for a totally non-existing variable name in `hover_data` (like `'z'`, `'blurb'`, etc in this example), an error is produced; is it doable for the variables present in the long-form but missing from the melted dataframe?

Thanks a lot!
