### ISSUE TITLE
Subplots of heatmaps with shared coloraxis display only one of the heatmaps

### ISSUE THREAD

**Issue by empet** [plotly/plotly.py#3111]
Subplots of heatmaps that share the same coloraxis do not work.
 More precisely a heatmap is plotted but  the second one is either empty or 
 is displayed  only a uniform  color, depending on the definition of the z-array.
```
import numpy as np
import plotly.graph_objects as go
from plotly.subplots import make_subplots

N = 256
x, y = np.meshgrid(np.linspace(-1, 1, N),
                   np.linspace(-1, 1, N))
z1 = 1 - np.maximum(abs(x), abs(y))
I, J = np.indices((N,N))
fig = make_subplots(rows=1, cols=2, shared_yaxes=True,
                    horizontal_spacing=0.02)
fig.add_trace(go.Heatmap(z=z1, coloraxis='coloraxis'), 1, 1)
fig.add_trace(go.Heatmap(z=J^I, coloraxis='coloraxis'), 1, 2)
fig.update_layout(width=700, height=400,
                  coloraxis_colorscale='algae', coloraxis_showscale=False)
```
![subpl-heat](https://user-images.githubusercontent.com/3627253/110850053-0b4b2700-82b8-11eb-8eeb-23ee54f30b33.png)

With the classical definition the figure is plotted as expected:
```

fig1 = make_subplots(rows=1, cols=2, shared_yaxes=True,  horizontal_spacing=0.02)
colorsc = dict(colorscale='algae', showscale=False)
fig1.add_trace(go.Heatmap(z=z1, **colorsc), 1, 1)
fig1.add_trace(go.Heatmap(z=J^I, **colorsc), 1, 2)
fig1.update_layout(width=700, height=400)
```

**Comment by nicolaskruchten** [comment]
This is working as intended I think ... the left-hand figure has very small z values (less than 1), so they all show up as roughly the same color, on a scale shared with the right-hand figure which has z values that go up to 255.

**Comment by empet** [comment]
I've checked the code just now, and the same plot is displayed, while with the second block (without setting coloraxis) the figure is this one:

![heatmaps](https://user-images.githubusercontent.com/3627253/115069589-7366db80-9efc-11eb-88e5-00afe239adfa.png)

**Comment by nicolaskruchten** [comment]
Right. I'm saying that this is as intended. The figure you've just posted is not using a shared color axis, so points in the middle of the left-hand figure which have a z value of near one show up as quite dark, even though that color is used for points with a z-value of near 255 on the right-hand figure. This is as expected.

If you make a figure with a *shared* color axis, then all the points in the left-hand figure get a very light color, just like points in the right-hand figure with similar values of z. This all seems "as designed" to me. What else would you expect a shared color axis to do?

**Comment by nicolaskruchten** [comment]
Basically using a shared coloraxis means that the zmin/zmax are computed to include the union of all z values, as if your second figure had `zmin=0, zmax=255` in `colorsc`.

**Comment by empet** [comment]
Ah, OK :)
