### ISSUE TITLE
fig.update_xaxis runs fine, but fig.update_yaxis gives : 'Figure' object has no attribute 'update_yaxis'

### ISSUE THREAD

**Issue by danre07** [plotly/plotly.py#3113]
I'm getting an error when trying to set the y-axis of my candlestick chart to log-scale in Jupyter Notebook by running.

```python
fig = plt.plot_candles(fig, df) # my function
fig.update_xaxes(showgrid=False) # this executes just fine
fig.update_yaxis(type='log') 
>> 'Figure' object has no attribute 'update_yaxis'
```

For reference, my versions printed from Jupyter Notebook:

```python
print(plotly.__version__) # 4.14.3 
print(python_version()) # 3.9.1
```

I double checked the documentation (below), and that was the code they used:

https://plotly.com/python/reference/layout/yaxis/

https://plotly.com/python/log-plot/#logarithmic-axes-with-graph-objects

I also ran the code for jupyter notebook compatibility in their get started guide:

```python
pip install "notebook>=5.3" "ipywidgets>=7.5"
```

**Comment by nicolaskruchten** [comment]
Yes the function is update_yaxes not update_yaxis ... plural not singular.
