### ISSUE TITLE
go.Choropleth(): unexpected map border

### ISSUE THREAD

**Issue by to-mg** [plotly/plotly.py#3114]
I have two geojson files generated from the same shapefile. First step is to convert the orginal shapefile to geojson format with geopandas, the second step is to reduce the number of points with mapshaper:

mapshaper regione.geojson -simplify 5% -o 5regione.geojson   # keep 5% of the points 
mapshaper regione.geojson -simplify 20% -o 20regione.geojson # keep 20% of the points

When I run the following plotly program using go.Choropleth() to create a map without a border (layout_geo_showframe=False) with the above geojson files as input, the image from 5regione.geojson has non border (expected behavior), while the image from 20regione.geojson has a border (unexpected behavior).

See attached geojson.zip file for input geojson files and for generated images.
[geojson.zip](https://github.com/plotly/plotly.py/files/6137273/geojson.zip)

import json
import sys
import plotly.graph_objects as go
fileconfini = sys.argv[1]
titolo = dict(text=sys.argv[1], x=0.5, xanchor="center")
layout = go.Layout(
    geo=dict(
        showland=False, showcountries=False,
        showocean=False, showrivers=False,
        showlakes=False, showcoastlines=False,
        showframe=False,  # No frame !!
        fitbounds="locations",
    ),title=titolo,
)
confini = json.load(open(fileconfini))
featureidkey = "properties.COD_REG"
colorscale = [
    [0.0, "rgba(255,255,255,0)"],
    [1.0, "rgba(255, 255, 255, 0)"],
]
traccia = go.Choropleth(
    showscale=False, name="Mapparegione",
    visible=True, colorscale=colorscale,
    zmin=0, zmax=1, z=[0.5],
    geojson=confini, locations=["1"],
    featureidkey=featureidkey,
    marker_line_color="black",
    hoverinfo="skip", hovertemplate=None,
)
figura = go.Figure(data=[traccia], layout=layout)
figura.write_html(sys.argv[1].replace("geojson", "html"))
figura.write_image(sys.argv[1].replace("geojson", "jpg"))

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
