### ISSUE TITLE
Dropdown menus unreadable with Plotly Dark theme

### ISSUE THREAD

**Issue by singhkays** [plotly/plotly.py#3120]
### Issue
Drop down menus when used with Plotly dark theme are not readable when hovered over with the mouse. The fill color is very similar to white text. See screenshots below. 

### Screenshots
**Non-hover state**
![image](https://user-images.githubusercontent.com/6164178/111923923-f19ba380-8a5e-11eb-841a-ba2cb30d52c1.png)

**Mouse Hover**
![image](https://user-images.githubusercontent.com/6164178/111923933-ffe9bf80-8a5e-11eb-96f2-3b819fcdd247.png)

**Menu Open**
![image](https://user-images.githubusercontent.com/6164178/111923949-13952600-8a5f-11eb-9c35-607a92bb89f9.png)

### Plotly version
Latest offline version as of March 21, 2021

### Code

```python
# Figure Code
  fig = px.bar(barDf, x='Video Type', y=['Efficiency Cluster', 'Performance Cluster', 'DRAM', 'GPU', 'Other'], template='plotly_dark', orientation='v', hover_name = 'Video Type',
    labels={"value": "Power Consumption (mW)"}, 
    category_orders={"Video Type": ["4K-VP9", "4K-AV1",  "FHD-AV1", "FHD-H264", "FHD-VP9"]})

...some code omitted for brevity...

# Button Code
    fig.update_layout(
        updatemenus=[
            dict(
                type="dropdown",
                # direction="right",
                active=0,
                x=1.035,
                y=1.27,
                showactive = True,
                buttons=list([
                    dict(label="Grouped",
                        method="update",
                        args=[{"width": [0.11]},
                            {"barmode": "group"}]),
                    dict(label="Stacked",
                        method="update",
                        args=[{"width": [0.6]},
                            {"barmode": "stack"}])
                ]),
                bgcolor = "#222",
                bordercolor = "#FFF",
                borderwidth = 0.5
            )
        ])
```

**Comment by empet** [comment]
This is an old and unfixed issue:  [https://github.com/plotly/plotly.js/issues/1428](https://github.com/plotly/plotly.js/issues/1428)

**Comment by SinclairGurny** [comment]
Are there any updates on this issue?

**Comment by isaacbshelton** [comment]
Think I found a workaround. After noticing the active/hover color is not perfectly white, I checked the pixels and on my machine and plotly graphs they are #F4FAFF. Searching for this in the figure's .html file results in two variables: 

- activeColor:"#F4FAFF"
- hoverColor:"#F4FAFF"

This seemed promising so here's the python code I used to replace these variables:

`
# ... first create the figure in python plotly

fig.write_html('fig.html')
with open('fig.html', 'r') as file:
    file_contents = file.read()

# want to replace these strings in the html code
# activeColor:"#F4FAFF"
# hoverColor:"#F4FAFF"

# new colors
active_color = '#FF0000'
hover_color = '#00FF00'

file_contents = file_contents.replace('activeColor:"#F4FAFF"', f'activeColor:"{active_color}"')
file_contents = file_contents.replace('hoverColor:"#F4FAFF"', f'hoverColor:"{hover_color}"')

with open('fig_updated.html', 'w') as file:
    file.write(file_contents)
`

And it works now. The dropdown menus are readable with the dark theme. I have only tested this on my machine with a few graphs, so I'm unsure if these default color values are the same for everyone. It appears those two variables and their value #F4FAFF are hardcoded into ALL of my plotly html files, even the ones without buttons. It's possible your colors may be different, but the variables should hopefully be there.

**Comment by Tristan-Lo** [comment]
Is it possible to change the activeColor when using dcc.Graph in dash? Thanks.

**Comment by Coding-with-Adam** [comment]
@Tristan-Lo can you please clarify your question? What are you trying to achieve?

**Comment by Tristan-Lo** [comment]
Hi @Coding-with-Adam. The above method works when exporting the figure as html, then update the tml. But what if we are using dash? Suppose won't be saving the plot as html.
Only the inactive background color can be changed, but the active color will still be #F4FAFF.
Any suggestion? Thanks.

`
from dash import Dash, dcc, html
import plotly.express as px

df = px.data.iris()

fig = px.bar(df, x='sepal_width', y='petal_width')

update_buttons = dict(
    type='buttons',
    direction="left",
    buttons=[
        dict(args=[], label='Button 1', method='update'),
        dict(args=[], label='Button 2', method='update'),
    ],
    showactive=True,
    bgcolor='yellow',
    #bgcoloractive='blue', # is changing active background color possible? 
)
fig.update_layout(
    updatemenus=[
        update_buttons,
    ],
)

app = Dash()
app.layout = html.Div([dcc.Graph(id='bar', figure=fig)])
    
if __name__ == '__main__':
    app.run_server(debug=True)
`

**Comment by Coding-with-Adam** [comment]
`bgcoloractive` is not possible because that attribute does not exist in Plotly's [updatemenus](https://plotly.com/python/reference/layout/updatemenus/) feature. 

However, you can do this with Dash through the html.Button and the callback. Code:
```
from dash import Dash, dcc, html, callback, Output, Input, ctx, no_update
import plotly.express as px

df = px.data.iris()

fig = px.bar(df, x='sepal_width', y='petal_width')

active_color = {'backgroundColor': 'yellow'}
inactive_color = {'backgroundColor': 'gray'}


app = Dash()
app.layout = [
    html.Button('Button 1', id='button-1'),
    html.Button('Button 2', id='button-2'),
    dcc.Graph(id='bar', figure=fig)
]

@callback(
    Output('button-1', 'style'),
    Output('button-2', 'style'),
    Input('button-1', 'n_clicks'),
    Input('button-2', 'n_clicks')
)
def update_graph(n1,n2):
    button_id = ctx.triggered_id
    if button_id == 'button-1':
        return active_color, inactive_color
    elif button_id == 'button-2':
        return inactive_color, active_color
    elif button_id is None:
        return no_update


if __name__ == '__main__':
    app.run_server(debug=True)
```

**Comment by Tristan-Lo** [comment]
@Coding-with-Adam Got it, thanks.

**Comment by tom-andersson** [comment]
Thanks for the workaround @isaacbshelton -- just a note for others that this only works if `fig.to_html` packages plotly along with the figure (i.e. do *not* pass `include_plotlyjs='cdn'`.
