### ISSUE TITLE
Y Axis Auto-Scaling And Window Resizing Difficulties

### ISSUE THREAD

**Issue by mmehrle** [plotly/plotly.py#3125]
I'm fairly new to plotly but am pretty firm with python so it took me a little over a weekend to figure out how to produce the graph I wanted. Great API for sure but IMO it seems to have lingering issues that I don't see addressed and which IMO may prevent it from wider adoption.

To demonstrate my woes I have enclosed a generated graph I produced over the weekend. Despite two days of intense research I however was unable to fix two remaining issues:

1. Y axis scaling when zooming into the dataset. As you can see I am using BTC as the main series and we all know that it produces a pretty long tail when not shown in log mode. I was able to figure out the latter but what continues to irk me is that - no matter which approach I tried (and I spent hours trying every tip I found online) it seems to be impossible to scale the y axis when zooming in. You can test that by selecting a date range more than four years ago and then zooming in. You'll eventually be presented with almost a horizontal line. Not good enough for prime time IMHO.
2. Window zooming. Apparently there is a hack to get it done in python but I'm not using the chart in python, I am deploying it online to a wider audience. Some may access that page on a mobile phone, some on a desktop, some on a tablet. Even in a desktop environment they may want to see the chart large across the entire window. Once again, no matter what I did it seemed impossible to affect the graph size in any way - it looks completely hardcoded. I even jumped into the Chrome Inspector to figure out which CSS I could hack to affect the window with but to no avail.

So in essence these two main issues are keeping me from deploying my data via plotly as I would spend a lot of time on customer support, explaining to them that: no the chart can't be sized up, and no the zoom isn't adjusting the y axis properly.

Now it could very well be that I'm a complete halfwit and that both of these issues can be resolved easily. If so I would be delighted to be shown the errors of my ways. I would also be happy to hack the HTML/CSS if necessary as that can easily be done via beautifulsoup.

Any pointers and suggestions would be welcome.

**Comment by mmehrle** [comment]
For some reason it seems that the file did not make it. Trying again...

[BTC_Greed_Fear_Ratio.html.zip](https://github.com/plotly/plotly.py/files/6221284/BTC_Greed_Fear_Ratio.html.zip)

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
