### ISSUE TITLE
Pypi tarball contains prebuilt Python objects

### ISSUE THREAD

**Issue by noahfx** [plotly/plotly.py#313]
Hello, 
i am the maintainer of the python-api in Debian[[1](https://packages.qa.debian.org/p/plotly.html)], I have noticed your tarball for the version 1.8.5 in Pypi contains prebuild Python objects (*.pyc), if this wasn't on purpose it would be great to have a clean tarball for this release. Thanks.
Cheers!

**Comment by jonmmease** [comment]
Looking through the Pypi tar.gz for version 3.2.1 I can confirm that there are no *.pyc files included.
