### ISSUE TITLE
When putting multiple null-separated lines in one go.Scatter, cannot specify the line color 

### ISSUE THREAD

**Issue by j-carson** [plotly/plotly.py#3135]
Thanks for your interest in plotly.py!!

I am using go.Scatter with the "trick" to insert None's where I want line breaks. I cannot specify the colors of the lines in this case.

```python
import pandas as pd
import plotly.graph_objects as go
from IPython.display import display, HTML

x = pd.Series([0, 1, None, 2, 3], name = 'x')
y = pd.Series([1, 1, None, 2, 2], name = 'y')

# what I think should work
color0 = pd.Series(['red', 'red', None, 'orange', 'orange'], name = 'color0') 

# but the API won't accept nulls so here ya go
color = pd.Series(['red', 'red', 'orange', 'orange', 'orange'], name = 'color') 

df = pd.concat([x,y,color,color0,], axis=1)

fig = go.Figure()
fig.add_trace(
    go.Scatter(
        mode = 'markers+lines',
        x = df.x,
        y = df.y,
        marker_line_color=df.color,
        marker_color=df.color,
    )
)
```

What I see:
![newplot](https://user-images.githubusercontent.com/44308120/113765205-cc4e9c80-96d0-11eb-9f74-1108dbd30302.png)

What I want to see: 

Colors of lines match the colors of their endpoints. 

I would like this to work whether the markers are displayed or not, but using mode='lines' won't accept a vector for line_color, and doing the example with the marker displayed makes it easier to show what I am trying to do.

**Comment by nicolaskruchten** [comment]
As a point of clarification: `marker_line_color` is the color of the border-line around the marker, and this can indeed accept lists of values. The line itself at the moment can only be one color for a given trace, interrupted or not.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
