### ISSUE TITLE
Plotly Animated Scatter Plot updating points problem!

### ISSUE THREAD

**Issue by NiksanJP** [plotly/plotly.py#3137]
I have data of x and y values which change every frame

![image](https://user-images.githubusercontent.com/40626274/113851919-f12d3780-97d6-11eb-997a-bc571ed0999f.png)

The picture is the comparison between frame 0 and frame 1.
Here the coordinates change (max 8), the same person can be identified via their ID (id) and their frame.

Using Plotly's express I have plotted it using
```
fig = px.scatter(data, x = 'x', y = 'y', animation_frame='frame', color='color', range_x=[0,defaultX], range_y=[0, defaultY], title='Infections over 10 days')
fig.update_traces(marker=dict(size=8))
fig.show()
```

The results are Here:

Using the Play button!

https://user-images.githubusercontent.com/40626274/113852291-60a32700-97d7-11eb-9e28-5903552e7dd7.mp4

Using the Slider

https://user-images.githubusercontent.com/40626274/113852337-6e58ac80-97d7-11eb-870e-868d31bdf717.mp4

**What's the Error?**

When using the Play button there is a massive movement with the points but when you see my data, you can see the diffX and diffY with low distance movement.
This only happens when using the play button.

**How do you reproduce this?**
Add x and y values for each frame that has a minimal change.
using the code above you will be able to reproduce this.

**Comment by NiksanJP** [comment]
**UPDATE**

I just had to change my `animation_group = 'id'`.

But now I have a new problem.
I have 3 color variations of which green does not appear till later frames.

Actually green does not show even though some turned green.

It is the same data as before.

**Comment by nicolaskruchten** [comment]
There are some pretty strict limitations at the moment to our animation engine, documented here: https://plotly.com/python/animations/#current-animation-limitations-and-caveats

I suspect that the first point is what you're running into: data points cannot change categorical values (color, symbol) across frames, and every point must be present in every frame.
