### ISSUE TITLE
Scatter plot behaviour from 4.13.0 to 4.14

### ISSUE THREAD

**Issue by CalaveraLoco** [plotly/plotly.py#3144]
Hello,

I tried to plot a simple timeseries as pictured in the tutorial (https://plotly.com/python/line-charts/).
![plotly_4_13](https://user-images.githubusercontent.com/10377060/114561757-240b7b80-9c6e-11eb-84d1-9a1e36639d29.png)

Up until 4.13 this the plot the code produces.
But after updating to 4.14 the same code produced this:

![plotly_4_14](https://user-images.githubusercontent.com/10377060/114561781-2a99f300-9c6e-11eb-9002-e339425e1180.png)

Even the Y axis orientation is flipped..
Is this the intended behaviour? Did I miss something in the change notes? Using python 3.7.4 on Windows.

**Comment by nicolaskruchten** [comment]
Yes, we changed the behaviour of the type auto-detection for axes. I suspect that what's happening here is that your `opens` contains strings rather than numbers, and these are being interpreted as categories now, rather than implicitly being converted to numbers.

**Comment by CalaveraLoco** [comment]
You are right, the values were in fact strings as read from a CSV. Casting them to float prior to plotting them fixed the issue.
Thanks for your quick response!
