### ISSUE TITLE
FigureWidget does not apply layout in Jupyter Notebook (unless using fig.show())

### ISSUE THREAD

**Issue by jleape** [plotly/plotly.py#3145]
According to the [docs](https://plotly.com/python/figurewidget/), it should not be necessary to use f.show() to display a FigureWidget. However, the following code does not apply the specified title.
```
import plotly.graph_objects as go
f = go.FigureWidget()
f.add_scatter(y=[2, 1, 4, 3])
f.add_bar(y=[1, 4, 3, 2])
f.layout.title = 'Hello FigureWidget'
f
```
![newplot](https://user-images.githubusercontent.com/8622209/114596684-87d57a80-9c55-11eb-8ff1-c92d7c0b66ff.png)

I found that other updates to the layout, such as custom colorscales, do not get applied.

If I use f.show(), however, the layout is applied. Since I am passing f to GridspecLayout, it throws an error if I use f.show(), so that's not an option. 

This was not an issue before I made some package updates, but I cannot figure out an environment that works. Here's what I have:
```
ipywidgets==7.5.1
widgetsnbextension==3.5.1 
plotly==4.8.1
```
Assistance greatly appreciated!

**Comment by nicolaskruchten** [comment]
I'm in JupyterLab 3, with the `plotlywidget` extension installed and Plotly 4.14.3 and your code above *does* work.

What notebook are you in? Classic Notebook or Lab or Google Colab or something more exotic?

**Comment by jleape** [comment]
Thanks for the quick reply, @nicolaskruchten! I'm in Classic Notebook.

**Comment by nicolaskruchten** [comment]
Which version of the Notebook? Any chance you could upgrade to the latest Plotly?

**Comment by jleape** [comment]
`jupyter core     : 4.7.1
jupyter-notebook : 6.3.0
qtconsole        : not installed
ipython          : 7.22.0
ipykernel        : 5.5.3
jupyter client   : 6.1.12
jupyter lab      : not installed
nbconvert        : 6.0.7
ipywidgets       : 7.6.3
nbformat         : 5.1.3
traitlets        : 5.0.5`

Trying to udpate plotly..

**Comment by jleape** [comment]
I restarted jupyter and now it works. (I thought I just had to restart the kernel). Thanks!

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
