### ISSUE TITLE
LocalHost Refused to Connect, Site Cannot be Reached

### ISSUE THREAD

**Issue by windowshopr** [plotly/plotly.py#3150]
I'm trying to run this example, taken from [here](https://plotly.com/python/map-configuration/#named-map-scopes-and-country-subunits):

```
import plotly.graph_objects as go

fig = go.Figure(go.Scattergeo())
fig.update_geos(
    visible=False, resolution=110, scope="usa",
    showcountries=True, countrycolor="Black",
    showsubunits=True, subunitcolor="Blue"
)
fig.update_layout(height=300, margin={"r":0,"t":0,"l":0,"b":0})
fig.show()
```

...and the Chrome tab that opens up "loads" forever, then fails with the screen saying "This site can’t be reached. localhost refused to connect".

I see similar issues #3102, #2941, #2964 that have not provided unquestionable answers for them, which isn't very encouraging, but figured I'd try my luck as well. I also JUST pip installed plot.ly and dash onto my machine (Windows 10, Python 3.6) and am getting this issue trying to use their example which is a little frustrating. Can we get an answer on this? Thanks!

**Comment by nicolaskruchten** [comment]
Are you executing this in Jupyter or JupyterLab or some other environment?

**Comment by windowshopr** [comment]
Command prompt from a .py script

**Comment by nicolaskruchten** [comment]
In a local or remote shell?

**Comment by windowshopr** [comment]
Local machine

**Comment by nicolaskruchten** [comment]
Interesting. Try adding `import time; time.sleep(1)` after `fig.show()` to see if it changes anything?

if you have a script that contains exactly the code above, then what's meant to happen (and does happen on my machine) is that `fig.show()` launches a web browser and a web server and the former connects to the latter. Maybe the server is shutting down before the browser connects to it? Or maybe you have some firewall preventing the local web server from launching?

Most people use Plotly in a Notebook environment with `fig.show()` or if using Plotly in a script, will use `fig.write_html()` (https://plotly.com/python/interactive-html-export/) to dump an HTML file and then load it up in a browser.

**Comment by windowshopr** [comment]
Hmm. I wouldn't suspect there's any firewall issues unless it's Windows Firewall doing the blocking, in which case, what could I try to allow Plotly through? Or is there a source in the documentation that might help troubleshoot such issues? I surely can't be the only one experiencing this issue haha

I tried the sleep suggestion too, but same issue :(

The suggestion of `fig.write_html()` worked so I can inspect my plots as I build them, but would be nice to figure out the main part. If you have any suggestions, just let me know and I can give it a shot. thanks!

**Comment by nicolaskruchten** [comment]
Can you tell me a bit more about what you're trying to do and how? You've got a `script.py` file that you're running with like `python script.py`?

**Comment by windowshopr** [comment]
You got it, yep. Script is exactly as shown in the original post, updated versions of plotly/dash, windows 10, python 3.6.

**Comment by nicolaskruchten** [comment]
In that case, `fig.show()` is likely not as robust for you as you'd need, and you may want to dump the HTML file and use extra Python code to open up a browser window pointing to that file explicitly...

**Comment by windowshopr** [comment]
That's a good idea, and probably what I'll end up doing for now, likely using a solution similar to [here](https://stackoverflow.com/questions/40905703/how-to-open-an-html-file-in-the-browser-from-python). I was getting worried about having to manually open the .html file each time I run the script, but I can integrate this into the script to do that step. This would essentially do the same thing, however just not using the server obviously. I'm sure it would work in a Jupyter-Lab setting, so I'll try that later to see if the issue is resolved in there. Thanks!!

**Comment by windowshopr** [comment]
This is the final code I'm using for now:

```
import plotly.graph_objects as go
from selenium import webdriver

class Test_Map_Class():

    def __init__(self):
        pass

    def generate_map(self):

        fig = go.Figure(go.Scattergeo())
        fig.update_geos(
            visible=False, resolution=110, scope="usa",
            showcountries=True, countrycolor="Black",
            showsubunits=True, subunitcolor="Blue",
        )
        fig.update_layout(height=300, margin={"r":0,"t":0,"l":0,"b":0})
        fig.write_html("plot.html")
        
        #  Open the .html file with ChromeDriver
        driver = webdriver.Chrome()
        driver.get("file:///C:/Users/.../Documents/.../plot.html") # Replace with your own path to the file

        return driver




driver = Test_Map_Class().generate_map()
```
