### ISSUE TITLE
Latex in figure is not rendered in sphinx documentation

### ISSUE THREAD

**Issue by atharva-2001** [plotly/plotly.py#3152]
Hello, thanks for making this awesome library! 
I am trying to embed a plotly figure in sphinx documentation by plotting inside Jupyter Notebook, but Latex in the axes in the plotly figure is not rendered, and all I see is code that was supposed to generate the Latex-based axes title. 
Something like this: 
![image](https://user-images.githubusercontent.com/55894364/115005370-6b3f7980-9ec5-11eb-938e-5936d57b7627.png)
As mentioned [here](https://groups.google.com/g/sphinx-users/c/0cDKO35c5IQ/discussion), MathJax is not loaded until a math object is detected in the sphinx documentation. So I tried adding a cell with latex in it and the axes titles are rendered properly. 
![image](https://user-images.githubusercontent.com/55894364/115006160-2d8f2080-9ec6-11eb-8aea-f1c4de5da229.png)

However, I think this doesn't look appealing, and wondered if there is a different way to do it. If I export the figure in HTML using the `include_mathjax` argument, axes labels are rendered properly. It's just when I build the documentation using sphinx.
For references, please see: 
https://github.com/spatialaudio/nbsphinx/issues/369 
https://github.com/sphinx-doc/sphinx/issues/6981 
[and this](http://5.9.10.113/65796856/latex-and-plotly-using-sphinx-gallery)

**Comment by nicolaskruchten** [comment]
There's not much we can do on the Plotly side unfortunately... MathJax must be loaded for LaTeX to render in a figure. Maybe there's a sphinx flag to force it to load, or a way to hide that cell or something?

**Comment by atharva-2001** [comment]
Thanks for answering! I will try finding a workaround. Also, the nbsphinx guys are working on force loading MathJax, so maybe that will fix this.

**Comment by mgeier** [comment]
Can you please check if https://github.com/spatialaudio/nbsphinx/pull/551 fixes this?

**Comment by atharva-2001** [comment]
@nicolaskruchten Could you please check if https://github.com/spatialaudio/nbsphinx/issues/572 is something that you can help with?
It seems that the problem is Plotly inserting this:
```js
 if (window.MathJax) {MathJax.Hub.Config({SVG: {font: "STIX-Web"}});}
```
in the HTML page which is causing an error as `MathJax.Hub` no longer exists. This causes an error and plotly figures do not load. Downgrading to MathJax v2 fixes this issue because `MathJax.Hub` is supported by it.
Maybe you can see this [HTML file](https://rawcdn.githack.com/atharva-2001/nbsphinx-test/9ce4d43eb779310b44ff047f274a1471cdbdf320/assume_equations_true/build/html/plotly_latex_no_cell.html) to start with.
[Here](https://github.com/spatialaudio/nbsphinx/issues/572#issuecomment-852952461) is the link to the comment with some more test documents I made for this. 
Another reference: https://github.com/tardis-sn/tardis/pull/1607

**Comment by nicolaskruchten** [comment]
Hmmm are you using MathJax 3.x ? Plotly.js is only tested/developed against MathJax 2.x at the moment so that might be the problem right there.

**Comment by atharva-2001** [comment]
Oh, I see. 
Yes, MathJax 3 is what is loaded by default, and changing it back to MathJax v2 does the trick.
