### ISSUE TITLE
Trace hidden from legend when blank category value included

### ISSUE THREAD

**Issue by gaw89** [plotly/plotly.py#3154]
Before complaining about something not working properly, I have to say, Plotly rocks!  You guys are doing fantastic work - keep it up!!

That said, when I have empty string values in a categorical column and use that column as the `color` argument in Plotly Express, the category is automatically hidden from the legend but appears on the graph.  

Running this code with Plotly.py 4.14.3 will reproduce the behavior:
```python
import plotly.express as px
import plotly.offline as py

df = px.data.gapminder().query("continent=='Oceania'")
df.country = df.country.replace('Australia', '')
fig = px.bar(df, x="year", y="lifeExp", color='country')
py.plot(fig)  # Only New Zealand will show in the legend
```

[This line](https://github.com/plotly/plotly.py/blob/03979d105c65dda3df3a155322eaff18f203b03f/packages/python/plotly/plotly/express/_core.py#L1934) is what causes this behavior.  I am sure there is a reasonable thought process behind this, but for me, this behavior was unexpected and confusing.

I would propose one or some combination of the following:

1. Make it clear in the docs that this is the behavior (perhaps it's already there and I simply missed it)
2. Raise a warning that this is the default behavior when a blank category value is detected
3. Provide an option to enable/disable this behavior in the call to the plotly.express plotting function (e.g. `px.line(df, 'x', 'y', color='z', hide_blank_categories = False)`
4. Make the default behavior to show all traces in the legend, even if the category is blank (though this might be unexpected and confusing when a user sees a legend entry with no name)

I'm open to any other suggested resolutions from the Plotly team, but I would love this to be "fixed".

Thanks!!!

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
