### ISSUE TITLE
tickmode array combined with tickson='boundaries' returns error for categorical axis 

### ISSUE THREAD

**Issue by Djeramon** [plotly/plotly.py#3155]
I'm plotting **offline**.

**Reproducible example:**

```
import plotly.graph_objects as go

fig = go.Figure(go.Bar(
    x = ['A', 'B', 'C', 'D', 'E'],
    y = [28.8, 28.5, 37, 56.8, 69.7]
))


fig.update_layout(
    xaxis = dict(
        tickmode = 'array',
        tickvals = ['1', '3', '5'],
        ticktext = ['One', 'Three', 'Five'],
        tickson = 'boundaries'
    )
)

fig.full_figure_for_development()
```

**Error:**

`ValueError: Transform failed with error code 525: Cannot read property '0' of undefined`

**Additional information:**

- Plotly version: 4.14.1
- The issue only appears for categorical axis. Removing either the `ticktext `property or the `tickson `property removes the error.

**Comment by archmoj** [comment]
I was not able to replicate this using plotly.js in [this codepen](https://codepen.io/MojtabaSamimi/pen/wvdLwLo?editors=0010).

**Comment by Djeramon** [comment]
I can confirm, that the issue went away since I reported it for plotly.py 4.14.1. I just tested it with plotly.py 5.2.1 and it works fine.
