### ISSUE TITLE
Titles are NOT updated correctly with Update Custom Button

### ISSUE THREAD

**Issue by guglielmosanchini** [plotly/plotly.py#3156]
In the custom button doc page (https://plotly.com/python/custom-buttons/), in the **Update Button** example,
the titles ("Yahoo High" and "Yahoo Low") are NOT updated when the buttons are pressed, and I have the similar issue on a personal plot, where  `method="update"` does NOT modify the layout as it should, while `method="relayout"` works.

**Comment by guglielmosanchini** [comment]
But in this reproducible example, it works, I dont understand why
```
p = go.Figure()

y_values = ['label1', 'label2', 'label3']

x_values1 = [1,5,3]
x_values2 = [4,3,5]

p = p.add_trace(go.Bar(x = x_values1, 
                       y = y_values,
                   orientation='h' 
               ))

updatemenus = [{'buttons': [{'method': 'update',
                             'label': 'Values 1',
                             'args': [{'x': [x_values1]},
                                     {'title': {'text': 'Title 1'}}
                                       ]
                                      },
                            {'method': 'update',
                             'label': 'Values 2',
                             'args': [{'x': [x_values2]},
                                       {'title': {'text': 'Title 2'}}
                                     ]
                            }                         
                           ],
                'direction': 'down',
                'showactive': True}]

p = p.update_layout(template = 'plotly_white', 
                    updatemenus=updatemenus
                   )

p.update_layout(title_text = 'Title 1')
p.show()
```

**Comment by berniyh** [comment]
The problem are the annotations. Somehow they mess up the updating. Not sure why.
If you remove the annotations part from the updatemenu dict it'll update the title and also update the traces properly.

**Comment by gvwilson** [comment]
Hi ,
Greetings from Plotly - I started a new gig as manager of the libraries team seven weeks ago, and so far I'm feeling like the longer I'm here, the further behind I am :-) We're thinking about overhauling our charts, and our designer would be grateful for a chance to talk with a few people about what changes they'd like to see - any chance you could spare a bit of time to chat with him online?
Hope you and yours are safe and well,
Greg
