### ISSUE TITLE
Annotated Heatmap is terrible

### ISSUE THREAD

**Issue by julienraffaud** [plotly/plotly.py#3172]
Why is annotated heatmap horrible? Who thought making it like this made sense??? 

![56741516-CC6E-46FC-9EC5-E9F8307B5D24](https://user-images.githubusercontent.com/21250463/115975700-e60c3280-a55e-11eb-8f28-7455c6d22da0.jpeg)

**Comment by nicolaskruchten** [comment]
We do our best. I'm sorry if that's not good enough.

**Comment by nicolaskruchten** [comment]
If you would like to submit a constructive issue with code as text rather than what appears to be a photo along with an actual question, we might be able to help you, but your issue above is not an acceptable way to engage with our community.

**Comment by julienraffaud** [comment]
Very sorry Nicolas - that was so rude. I was frustrated and tired trying to make this function work late on a Saturday night (though that is no excuse)

**Comment by nicolaskruchten** [comment]
Ok, I get frustrated with our library too sometimes (and the lack of time and resources to fix all the shortcomings it has), so I certainly get it! 

If you can provide a minimal example of a dataset and some code that shows us your problem I can try to help you.
