### ISSUE TITLE
Subplot and two or more second axes (multiple axes) cannot be drawn at the same time.

### ISSUE THREAD

**Issue by yakibuta888** [plotly/plotly.py#3173]
Thank you for providing the wonderful drawing module plotly.
It's a good module with a lot of freedom, but there's one thing I can't do.

Subplot and two or more second axes (multiple axes) cannot be drawn at the same time.

`
# sample dataframe
df = pd.DataFrame(
    dict(
        col1=list(range(0,20,2)),
        col2=random.sample(range(100, 200, 10), k=10),
        col3=random.sample(range(-50, 80, 13), k=10),
        col4=random.sample(range(1000, 5000, 400), k=10)
    )
)

# plot
fig = make_subplots(
    rows=2, cols=1,
    row_heights=[0.8, 0.2],
    shared_xaxes=True,
    vertical_spacing=0.01,
    specs=[[{'type': 'xy', "secondary_y": True}],
           [{'type': 'bar'}]]
)

fig.add_traces(
    [
        go.Scatter(
            name='col1',
            x=df.index.tolist(),
            y=df.col1,
            marker_color='blue',
            xaxis='x1',
            yaxis='y1'
        ),
        go.Scatter(
            name='col2',
            x=df.index.tolist(),
            y=df.col2,
            marker_color='orange',
            xaxis='x1',
            yaxis='y2'
        ),
        go.Bar(
            name='col3',
            x=df.index.tolist(),
            y=df.col3,
            marker_color='pink',
            marker_line_width=0,
            xaxis='x1',
            yaxis='y3'
        ),
        go.Bar(
            name='col4',
            x=df.index.tolist(),
            y=df.col4,
            marker_color='green',
            marker_line_width=0,
            xaxis='x2',
            yaxis='y4'
        )
    ],
    rows=[1,1,1,2], cols=[1]*4, secondary_ys=[False, True, True, False]
)

fig.update_xaxes(
    matches='x',
    showspikes=True,
    spikethickness=1,
    spikemode='across',
    spikesnap='cursor',
    showline=False,
    spikedash='solid'
)

fig.update_traces(
    xaxis='x2'
)

fig.update_layout(
    xaxis=dict(
        domain=[0, 0.9],
    ),
    xaxis2=dict(
        tickfont=dict(
            color='darkblue'
        ),
        domain=[0, 0.9],
        anchor='y4'
    ),
    yaxis=dict(
        title='col1',
        titlefont=dict(
            color='blue'
        ),
        tickfont=dict(
            color='blue'
        ),
        anchor='x2',
        showgrid=False,
    ),
    yaxis2=dict(
        title='col2',
        titlefont=dict(
            color='orange'
        ),
        tickfont=dict(
            color='orange'
        ),
        anchor='x2',
        overlaying='y',
        side='right',
        showgrid=False,
    ),
    yaxis3=dict(
        title='col3',
        titlefont=dict(
            color='pink'
        ),
        tickfont=dict(
            color='pink'
        ),
        anchor='free',
        overlaying='y',
        side='right',
        position=1,
    ),
    yaxis4=dict(
        title='col4',
        titlefont=dict(
            color='green'
        ),
        tickfont=dict(
            color='green'
        ),
        anchor='x2'
    ),
    title_text='sample',
    legend=dict(
        font=dict(
            color='black'
        ),
        orientation="h",
        yanchor="bottom",
        y=1.02,
        xanchor="right",
        x=1
    ),
    margin=dict(
        l=70, r=20, t=60, b=60
    ),
    dragmode='pan',
    hovermode='x unified',
    height=540,
    width=960
)
`

![image](https://user-images.githubusercontent.com/80181103/115977928-33b48980-a5b7-11eb-96e0-b962ccd264eb.png)

The result is that col2 and col3 are on the same axis,
The axis label for col4 was displayed as col3 and everything was drawn on the first line instead of the second line of the subplot.

Let's change the program a little.

`
# plot2
fig = make_subplots(
    rows=2, cols=1,
    row_heights=[0.8, 0.2],
    shared_xaxes=True,
    vertical_spacing=0.01,
    specs=[[{'type': 'xy', "secondary_y": True}],
           [{'type': 'bar'}]]
)

fig.add_traces(
    [
        go.Scatter(
            name='col1',
            x=df.index.tolist(),
            y=df.col1,
            marker_color='blue',
            xaxis='x1',
            yaxis='y1'
        ),
        go.Scatter(
            name='col2',
            x=df.index.tolist(),
            y=df.col2,
            marker_color='orange',
            xaxis='x1',
            yaxis='y2'
        ),
        go.Bar(
            name='col3',
            x=df.index.tolist(),
            y=df.col3,
            marker_color='pink',
            marker_line_width=0,
            xaxis='x1',
            yaxis='y4'
        ),
        go.Bar(
            name='col4',
            x=df.index.tolist(),
            y=df.col4,
            marker_color='green',
            marker_line_width=0,
            xaxis='x2',
            yaxis='y3'
        )
    ],
    rows=[1,1,1,2], cols=[1]*4, secondary_ys=[False, True, True, False]
)

fig.update_xaxes(
    matches='x',
    showspikes=True,
    spikethickness=1,
    spikemode='across',
    spikesnap='cursor',
    showline=False,
    spikedash='solid'
)

fig.update_traces(
    xaxis='x2'
)

fig.update_layout(
    xaxis=dict(
        domain=[0, 0.9],
    ),
    xaxis2=dict(
        tickfont=dict(
            color='darkblue'
        ),
        domain=[0, 0.9],
        anchor='y3'
    ),
    yaxis=dict(
        title='col1',
        titlefont=dict(
            color='blue'
        ),
        tickfont=dict(
            color='blue'
        ),
        anchor='x2',
        showgrid=False,
    ),
    yaxis2=dict(
        title='col2',
        titlefont=dict(
            color='orange'
        ),
        tickfont=dict(
            color='orange'
        ),
        anchor='x2',
        overlaying='y',
        side='right',
        showgrid=False,
    ),
    yaxis4=dict(
        title='col3',
        titlefont=dict(
            color='pink'
        ),
        tickfont=dict(
            color='pink'
        ),
        anchor='free',
        overlaying='y',
        side='right',
        position=1,
    ),
    yaxis3=dict(
        title='col4',
        titlefont=dict(
            color='green'
        ),
        tickfont=dict(
            color='green'
        ),
        anchor='x2'
    ),
    title_text='sample',
    legend=dict(
        font=dict(
            color='black'
        ),
        orientation="h",
        yanchor="bottom",
        y=1.02,
        xanchor="right",
        x=1
    ),
    margin=dict(
        l=70, r=20, t=60, b=60
    ),
    dragmode='pan',
    hovermode='x unified',
    height=540,
    width=960
)
`

![image](https://user-images.githubusercontent.com/80181103/115978090-31066400-a5b8-11eb-9abe-9ca73b22e5f1.png)

Swapped y3 and y4 of yaxis of add_trace.
I also swapped yaxis 3 and 4 in update_layout.

The result is displayed in two lines of subplort, and col4 is displayed normally.

The problem is that the label for col3 disappears and col2 and 3 are still drawn on the same axis.

The following can be seen from this behavior.
・Col3 specified as multiple axes of the second y-axis must not be a different axis from col2.
・ If multiple axes are specified in subplot,
Only the multi-axis of the second y-axis or the subplot works.

I want to draw as shown below.
![plotly_subp_maxes_want](https://user-images.githubusercontent.com/80181103/115979019-64e48800-a5be-11eb-95ad-1c38691d937a.png)
(This figure was synthesized with image editing software, not drawn with plotly.)
Thank you for your consideration.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
