### ISSUE TITLE
Feature request: possibility to change color/ marker symbol by  dcc.Graph() extendData property 

### ISSUE THREAD

**Issue by mainulquraishi** [plotly/plotly.py#3179]
Hello, 
Let me start by appreciating the work you guys have done and still doing. 

I started to use Plotly to implement a real time analytics dashboard for our company. 

During the exploratory data analysis, I came across a use case where, I wanted to mark newly added data points in different color/ marker-symbol depending on different  condition. Condition can be, "mark the data point as `cross` if a trained model classified that point as positive otherwise `circle`. 

But, with the current implementation of `extendData` of `dcc.Graph()` it is not possible (as far as I know). 

I tried the following code for testing but it does not work, 

```
import dash
from dash.dependencies import Output, Input,State
import dash_core_components as dcc
import dash_html_components as html
import plotly
import random
import plotly.graph_objs as go
import plotly.express as px
import dash
import dash_html_components as html

app = dash.Dash(__name__)

fig = go.Figure(
    data=[go.Scatter(x=[1], y=[1],mode="lines+markers",marker_symbol='cross')],
    layout=go.Layout(
        title=go.layout.Title(text="A Figure Specified By A Graph Object")
    )
)

def serve_layout():
    return html.Div([dcc.Graph(id="live-graph",figure=fig), dcc.Interval(
            id='graph-update',
            interval=5
        )])

app.layout = serve_layout

@ app.callback(Output("live-graph", "extendData"),
        [Input("graph-update", "n_intervals")],
        [State("live-graph", "figure")])
def update_graph_scatter(n_intervals,existing):
    x_new = existing['data'][0]['x'][-1] + 1
    y_new = random.random()
    return dict(x=[[x_new]], y=[[y_new]],marker_symbol='circle'), [0],100


if __name__ == '__main__':
    app.run_server(debug=True)


```

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
