### ISSUE TITLE
LaTeX characters with Kaleido fully offline not working

### ISSUE THREAD

**Issue by tony-zeidan** [plotly/plotly.py#3180]
Hi there, I am using Plotly to generate report quality geospatial graphics. My application render the plot figure into a pdf completely offline. So far I have been using Kaleido, and it works for most cases. I am trying to let users input LaTeX equations on the plot in different areas. I am aware that Kaleido requires both the topojson files and a MathJax bundle to do this. As such I have done:
```python
plotly.io.kaleido.scope.mathjax = <path to file>
plotly.io.kaleido.scope.topojson = <path to topojson files>
```
This is the code I use to make the tick labels:
```python
info['scale-text'] = [f"<span>10<sup>{x}</sup></span>" for x in info['scale-vals']]
```

And when the graph is plotted using .show() it looks like this:
![image](https://user-images.githubusercontent.com/56143916/117206611-1060ba00-adc1-11eb-9763-aab624df8737.png)
 But the image generated in the pdf looks like this:
![image](https://user-images.githubusercontent.com/56143916/117206950-6f263380-adc1-11eb-8861-f86e54e9531c.png)
This is an issue I do not understand whatsoever.

Now if I change the code to generate the tick labels to:
```python
info['scale-text'] = [f"$10^{x}$" for x in info['scale-vals']]
```
and call .show() again another issue arises: I get a blank screen, where the image never loads and the pdf comes out having the tick labels show `$10^0$`, etc..

pdf:
![image](https://user-images.githubusercontent.com/56143916/117207758-4fdbd600-adc2-11eb-80ef-96242a83375e.png)

I have no clue what I am doing wrong, any suggestions?

**Comment by tony-zeidan** [comment]
I have seen that some of the time, the LaTeX characters in the colorbar display properly if and only if the colorbar title is written with LaTeX too.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
