### ISSUE TITLE
Wrapper for vega-lite spec

### ISSUE THREAD

**Issue by jackparmer** [plotly/plotly.py#319]
@cldougl can you check this out after the Conning project?

The goal would be a wrapper in plotly.tools (or somewhere) that takes vega-lite JSON as input and outputs a Plotly chart. There's a fun explorer for the vega-lite spec here (click the wrench icon):

https://github.com/vega/polestar

@ellisonbg Any more starting background info would be helpful as the Plotly Python client contributors aren't super familiar yet with Altair or vega-lite. I learned tons about this from you at Strata, but your review and ideas as we poke along here would be fantastic.

We can see how this goes, but there may be an argument for implementing this at the Plotly.js level eventually so its accessible to any language (R, MATLAB, etc)...

**Comment by jackparmer** [comment]
(Also pinging @fperiz)

**Comment by ellisonbg** [comment]
I think the best starting point is to star to play with polestar to see how
binning/aggregation and groupby works. Those are the main part of the spec
that is a bit subtle.

I am also going to try working on writing some pandas code that expresses
those actions. Here is an issue I opened on vega-lite to get clarification
about these points:

https://github.com/vega/vega-lite/issues/584

I if the binning/aggregation/gropuby can be done in the backend languages,
doing the rest of the transform in JS would be pretty simple I think.

@fperez (was misspelled above)



On Sun, Oct 4, 2015 at 12:54 AM, Jack Parmer <notifications@github.com>
wrote:

> (Also pinging @fperiz)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/plotly/python-api/issues/319#issuecomment-145318058>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by cldougl** [comment]
sounds good @jackparmer
