### ISSUE TITLE
`plotly.express.scatter_geo`: misleading argument type for the `size` argument

### ISSUE THREAD

**Issue by stoufa** [plotly/plotly.py#3195]
The documentation of the function `plotly.express.scatter_geo` [[1]](https://plotly.com/python-api-reference/generated/plotly.express.scatter_geo) states that the `size` argument can be set to an integer.  
When you do that, you'll get an error similar to the following:

```
Traceback (most recent call last):
  File "/path/to/map.py", line 11, in <module>
    fig_map = px.scatter_geo(
  File "/path/to/miniconda3/lib/python3.8/site-packages/plotly/express/_chart_types.py", line 1031, in scatter_geo
    return make_figure(
  File "/path/to/miniconda3/lib/python3.8/site-packages/plotly/express/_core.py", line 1861, in make_figure
    args = build_dataframe(args, constructor)
  File "/path/to/miniconda3/lib/python3.8/site-packages/plotly/express/_core.py", line 1377, in build_dataframe
    df_output, wide_id_vars = process_args_into_dataframe(
  File "/path/to/miniconda3/lib/python3.8/site-packages/plotly/express/_core.py", line 1183, in process_args_into_dataframe
    raise ValueError(err_msg)
ValueError: Value of 'size' is not the name of a column in 'data_frame'. Expected one of ['col_name_1', 'col_name_2', 'col_name_3'] but received: 20
```

After some research, [[2]](https://stackoverflow.com/questions/63877348/how-do-i-set-dot-sizes-and-colors-for-a-plotly-express-scatter-geo) [[3]](https://plotly.com/python/reference/scattergeo/#scattergeo-marker-size) I found out that the correct way of doing this is via the method `fig.update_traces(marker=dict(size=20))`  
So, we need to update the documentation to avoid obsolete and misleading argument types

**Comment by nicolaskruchten** [comment]
Yeah, I should really document both the "integers are interpreted as col names" and "`px.Constant` is a valid input" in the docstrings. Thanks for the nudge :)

**Comment by nicolaskruchten** [comment]
Yes: https://plotly.com/python/hover-text-and-formatting/#disabling-or-customizing-hover-of-columns-in-plotly-express

**Comment by stoufa** [comment]
Thank you @nicolaskruchten.
For reference, using `fig.update_traces(marker=dict(size=20))` instead of `size=px.Constant(20)` is the fastest way to do that.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
