### ISSUE TITLE
non-dynamic textfont color when using continuous color scales

### ISSUE THREAD

**Issue by jarvas24** [plotly/plotly.py#3196]
### Current Behavior (plotly version 4.14.3)
When using the `text` property in a bar trace with a continuous color scale, the `textfont.color` is static; all bars use the same text color, which results in difficult to read text for some bars (far right bar in screenshot).

```python3
import plotly.express as px
x = list(range(1, 10))
px.bar(x=x, y=x, color=x, text=[str(i) for i in x])
```
![image](https://user-images.githubusercontent.com/66141312/118147320-0fd5ae00-b3d5-11eb-9144-63bebc55e777.png)

### Expected/Desired Behavior 
The text font color should be dynamic (dark text on light colored bars, light text on dark bars), just like the hover text. Bar traces with _discrete_ colorscales already have this behavior:
```python3
import plotly.express as px
x = list(range(1, 10))
px.bar(x=x, y=x, color=[str(i) for i in x], text=[str(i) for i in x], color_discrete_sequence=px.colors.sequential.Plasma)
```
![image](https://user-images.githubusercontent.com/66141312/118150644-64c6f380-b3d8-11eb-8330-2bf6ac48fd73.png)

**Comment by ArkaprabhaChakraborty** [comment]
Is anyone working on this? If not then I want to work on this.

**Comment by nicolaskruchten** [comment]
No one is working on it as far as I know, and we'd love the help! The right place to solve this is in the underlying Javascript library Plotly.js. We've actually got code that does this for pie charts and treemaps I believe, so it may be quite straightforward to port it to bars :)

@archmoj or @alexcjohnson can advise.

**Comment by nicolaskruchten** [comment]
Looks like this is getting fixed in https://github.com/plotly/plotly.js/pull/5666 actually :)
