### ISSUE TITLE
alternate yticks disappear in horizontal bar plot

### ISSUE THREAD

**Issue by Ibtastic** [plotly/plotly.py#3197]
The yticks were working fine with horizontal bar chart, and without any change in the code , half of them disappeared.
Plotly version 4.14.3
This is the code I've been using:
fig = go.Figure()
fig.add_trace(go.Bar(
    y=df_purchase.index[-20:].values,
    x=df_purchase['Number of Doses Procured'][-20:].values,
    name='Number of Doses Procured',
    orientation='h',
    marker=dict(
        color='rgba(246, 78, 139, 0.6)',)
))
fig.add_trace(go.Bar(
    y=df_purchase.index[-20:].values,
    x=df_purchase[' Doses intended to be purchased  '][-20:].values,
    name='Doses intended to be purchased',
    orientation='h',
    marker=dict(
        color='rgba(58, 71, 80, 0.6)')
))

fig.update_layout(barmode='stack',yaxis = dict(
        tickmode = 'array',
        ticktext = df_purchase.index[-20:].values
    ))
fig.show()

![](https://i.imgur.com/tRUTmrW.png)

**Comment by nicolaskruchten** [comment]
When there is not enough room to display every ticklabel without overlap, this happens. Your options are to reduce the number of bars, to reduce the font size for the ticklabels, or to increase the height of the figure.
