### ISSUE TITLE
Feature request - Self contained indicator

### ISSUE THREAD

**Issue by Luiscri** [plotly/plotly.py#3199]
I guess indicators are ment to be added to another trace on the figure in order to highlight something. However, it is necessary in some dashboards to show a number or percentage, being the indicator the only trace of the figure. This is tedious since an indicator with mode `number` will fill all the space of the space available for the figure (let's say, all the column height and width).

I will give you a code example:

```
fig = go.Figure(go.Indicator(
    title={
        'text': 'Plazo máximo provisión cuentas<br><sub>Porcentaje de alta/reactivación de una cuenta en plazo</sub>', 
        'font': {'size': 17}
    },
    mode="number+delta",
    value=100,
    number={
        'font': {'size': 40},
        'suffix': '%'
    },
    delta = {
        'reference': 99,
        'relative': True
    },
)).update_layout(
    title={
        'text': 'Han pasado {} días desde la última depuración'.format(6),
        'y': 0.05,
        'x': 0.5,
        'font': {'size': 17}
    }
)
```

and here you are an image with the results.

![indicator](https://user-images.githubusercontent.com/30075565/119160314-6b004400-ba58-11eb-81df-85e94f312cea.png)

I am using the indicator to display a KPI performance. I have added a text under the indicator by using the figure title and placing at the bottom of it. However, as the indicator uses all the available space of the column, the figure title is displayed far away, instead of just close to the value as the indicator title is. This is just a use case, but I am sure there are other situations where this property of indicators is not suitable.

It would be nice if we could select by a property if the indicator should expand to use all the available space, or if we want it to only use the space it needs to be drawn.

**Comment by nicolaskruchten** [comment]
There's no feature right now to auto-scale the font size to fit its bounding box, unfortunately. In this case I would recommend either manually tuning the font size or the figure dimensions.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
