### ISSUE TITLE
add_hline() breaks when axis is shared

### ISSUE THREAD

**Issue by ysmu** [plotly/plotly.py#3209]
I'm currently using `fig.update_xaxes(spikemode='across+marker')` with `fig.update_traces(xaxis='x2')`, as suggested [here](https://github.com/plotly/plotly.py/issues/1677#issuecomment-514661015), to draw spike a line across subplots. It was working great until I added some horizontal lines to my chart.

### `add_hline()` and `update_traces(axis='x2')`
![image](https://user-images.githubusercontent.com/17018576/120080141-61846680-c06c-11eb-89bd-c524f4f0a38a.png)

### `update_traces(axis='x2')` without `add_hline()`
![image](https://user-images.githubusercontent.com/17018576/120080181-811b8f00-c06c-11eb-8812-f8eaaa81fd89.png)

### `add_hline()` without `update_traces(axis='x2')`
![image](https://user-images.githubusercontent.com/17018576/120080123-49144c00-c06c-11eb-8a33-ccb47f8d3691.png)

Repro:
```py
import plotly.graph_objects as go
from plotly.subplots import make_subplots


fig = make_subplots(rows=2, cols=1)

fig.add_trace(go.Scatter(x=[1, 2], y=[1, 2], name='(1,1)'), row=1, col=1)
fig.add_hline(1.5, row=1, col=1)

fig.add_trace(go.Scatter(x=[1, 2], y=[1, 2], name='(1,2)'), row=2, col=1)
fig.add_hline(1.5, row=2, col=1)

fig.update_traces(xaxis='x2')
fig.update_xaxes(spikemode='across+marker')
fig.update_layout(height=600, width=600, title_text='specs examples')
fig.show()
```

Is this a bug or am I not supposed to share axis here?

**Comment by ivzap** [comment]
Having a similar issue with vrect shapes. I have  a multi-row, 1 col subplot with synced xaxis using `fig.update_traces(xaxis=x1)`. But, when I add vrect shapes, they only appear on one subplot despite specifying `rows="all"`. I believe this is due to the synced x-axes.

**Comment by nicolaskruchten** [comment]
Right, so `add_hline()` across multiple subplots is designed to work only with subplots created by `make_subplots` without subsequent modifications to the assignment of traces to axes.

Do you get the behaviour you want if you add the rects/lines *before* updating the traces?

**Comment by ivzap** [comment]
No. Unfortunately the same behavior occurs regardless of when the shapes are drawn. If this is the way it is designed to behave, the row argument of `add_hline()` or `add_vrect()` is misleading. It seems to assign the shape to the axis of the row rather than the row itself.

**Comment by nicolaskruchten** [comment]
Try something like the following, to apply the same transformations to your lines and rects as you are applying to your traces:

```python
fig.update_shapes(selector=dict(type="line"), xref="x2 domain")
fig.update_shapes(selector=dict(type="rect"), xref="x2")
```

**Comment by nicolaskruchten** [comment]
(or whichever axis it is, perhaps `x` and `x domain`)... here's the output I get:

![image](https://user-images.githubusercontent.com/203523/129429171-263ea117-b262-4e91-9b1f-4377328cdbba.png)

**Comment by ivzap** [comment]
Worked like a charm! Thank you so much; looks sick now

**Comment by AlanCPSC** [comment]
@nicolaskruchten, Do you have any insights into why the x-axis is bugging out when I uncomment these lines? 🤔

### Reproducible Code
```
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from datetime import date

trace1 = go.Scatter(x=[date(2023, 1, 15), date(2023, 2, 15), date(2023, 3, 15), date(2023, 4, 15),
                       date(2023, 5, 15), date(2023, 6, 15), date(2023, 7, 15), date(2023, 8, 15),
                       date(2023, 9, 15), date(2023, 10, 15), date(2023, 11, 15), date(2023, 12, 15)],
                    y=[1000, 2000, 3000, 4000,
                       5000, 6000, 7000, 8000,
                       9000, 10000, 11000, 12000],
                    name='trace1')

trace2 = go.Scatter(x=[date(2023, 1, 15), date(2023, 2, 15), date(2023, 3, 15), date(2023, 4, 15),
                       date(2023, 5, 15), date(2023, 6, 15), date(2023, 7, 15), date(2023, 8, 15),
                       date(2023, 9, 15), date(2023, 10, 15), date(2023, 11, 15), date(2023, 12, 15)],
                    y=[10_000, 20_000, 30_000, 40_000,
                       50_000, 60_000, 70_000, 80_000,
                       90_000, 100_000, 110_000, 120_000],
                    name='trace2')

fig = make_subplots(rows=2, cols=1, shared_xaxes=True, vertical_spacing=0.02)

fig.add_trace(trace1, row=1, col=1)
fig.add_trace(trace2, row=2, col=1)

fig.add_annotation(
    xref='x domain',
    yref='y domain',
    x=0,
    y=1,
    text='FIRST ANNOTATION',
    showarrow=False,
    font=dict(size=14, color='blue'),
    row=1, col=1
)

fig.add_annotation(
    xref='x domain',
    yref='y domain',
    x=0,
    y=1,
    text='SECOND ANNOTATION',
    showarrow=False,
    font=dict(size=14, color='red'),
    row=2, col=1
)

# fig.update_traces(xaxis='x')
# fig.update_xaxes(spikemode='across+marker')
# fig.update_shapes(selector=dict(type="line"), xref="x domain")
# fig.update_shapes(selector=dict(type="rect"), xref="x")

fig.update_layout(height=600, width=600, title_text='Example Chart')
fig.show()
```

### Before Uncommenting
![newplot_before](https://github.com/plotly/plotly.py/assets/22120384/91632fac-e8ce-4a30-b54b-9c90d62c7348)

### After Uncommenting
![newplot_after](https://github.com/plotly/plotly.py/assets/22120384/6d777b20-566b-45a8-b585-c3e58e850d1e)

**Comment by Coding-with-Adam** [comment]
Hi @AlanCPSC 
Can you please post this question on [the community forum](https://community.plotly.com/)?

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
