### ISSUE TITLE
Can the point of a 3D scatter be just like a sphere or a ball in plotly

### ISSUE THREAD

**Issue by autowus** [plotly/plotly.py#3225]
hello, recently I use the plotly to draw a 3D scatter figure, I want the points are a ball not a simply circle.
in the web (https://plotly.com/python/reference/#scatter3d-marker-symbol) , I can not find the ball or sphere symbol.

so  I want ask , can the the 3D scatter in plotly support the spere or ball point???
if it can't , do you have any other way to achieve the goal? 

Thanks all of you!
look forward.

best
Wu

**Comment by nicolaskruchten** [comment]
This is not possible at the moment, and isn't really on our roadmap. If you're using Dash, you may want to consider Dash-VTK which uses the VTK library for rendering physically realistic objects including spheres.

**Comment by wusujuan9999** [comment]
> This is not possible at the moment, and isn't really on our roadmap. If you're using Dash, you may want to consider Dash-VTK which uses the VTK library for rendering physically realistic objects including spheres.

Thanks for your information which is important to me. Yes,I will use Dash,  then I will reasearch the Dash-VTK. 

Thank you so much

best
Wu
