### ISSUE TITLE
streaming 3D direction fields

### ISSUE THREAD

**Issue by eulerreich** [plotly/plotly.py#323]
I need to stream 3D direction fields. Without the streaming, I've just been adding a `Scatter3d` object for each direction (drawn as a line segment) to the graph. But this approach doesn't seem like it'd work with streaming.

Is there another approach?

**Comment by jonmmease** [comment]
Closing as this was a question, not an issue report. Feel free to ask open-ended questions on the forum https://community.plot.ly/c/api/python.
