### ISSUE TITLE
Empty template property changes behavior for horizontal bar chart

### ISSUE THREAD

**Issue by Djeramon** [plotly/plotly.py#3239]
**Description:**
When making use of the template property, the labels for horizontal bar charts are being truncated. It doesn't matter what the template property contains, the issue appears even for empty templates.

**Expected behavior:**
The y axis labels should not be truncated, even when using a template.

**System information:**
Plotly.py version: 4.14.3
Tested on Windows 10
Plotted in Jupyter Lab 3.0.16

**Reproducible example:**
```python
import plotly.io as pio
fig = pio.read_json('sample_plotly_with_template_and_long_labels.txt') # Truncated labels
fig = pio.read_json('sample_plotly_without_template_and_long_labels.txt') # Working labels
```

**File without template:**
[sample_plotly_without_template_and_long_labels.txt](https://github.com/plotly/plotly.py/files/6638447/sample_plotly_without_template_and_long_labels.txt)

**Result without template:**
![image](https://user-images.githubusercontent.com/20990315/121688612-f2732d00-cac3-11eb-88c1-15afdd493422.png)

**File with template:**
[sample_plotly_with_template_and_long_labels.txt](https://github.com/plotly/plotly.py/files/6638446/sample_plotly_with_template_and_long_labels.txt)

**Result with template:**
![image](https://user-images.githubusercontent.com/20990315/121688458-c5267f00-cac3-11eb-86a6-b924c843c524.png)

**Comment by nicolaskruchten** [comment]
I believe all that is missing here is to turn on axis automargins.

**Comment by Djeramon** [comment]
You're right. Turning on the automargins worked. Thanks for the feedback.
