### ISSUE TITLE
update `chunked_requests` submodule

### ISSUE THREAD

**Issue by chriddyp** [plotly/plotly.py#324]
hey @theengineear - I just merged a PR in to `chunked_requests` (https://github.com/chriddyp/chunked_requests/pull/5) - how do I update this repo? Are we still doing

```
$ make sync_chunked
```

a la https://github.com/plotly/python-api/blob/master/makefile#L46-L49?

**Comment by theengineear** [comment]
Yep, that should do it, you'll have to also make a commit afterwards since it hangs out as a separate code blob, fyi.
