### ISSUE TITLE
Choropleth map colors outsides of shapes instead of insides.

### ISSUE THREAD

**Issue by JonasDeBoeck** [plotly/plotly.py#3248]
For a project I'm drawing a map of Belgium with all it's provinces.
I use the following geojson file: [https://raw.githubusercontent.com/mathiasleroy/Belgium-Geographic-Data/master/dist/polygons/geojson/Belgium.provinces.WGS84.geojson](url).
When I draw the file on GeoJson.io I get the following image: 
![image](https://user-images.githubusercontent.com/43340565/122210074-8454ae80-cea5-11eb-862a-06f2771063f9.png)
When I draw the map using plotly.express.choropleth I get the following:
![image](https://user-images.githubusercontent.com/43340565/122210126-946c8e00-cea5-11eb-9523-4a5464325493.png)
I use the following code to display the map:
```
import plotly.express as px
import json
import pandas as pd

df = pd.read_csv("data/resulted_data/kmeans/CLUSTER_PROVINCES.csv")
with open('geojson.json') as file:
    be = json.load(file)

fig = px.choropleth(df, geojson=be, locations="PROVINCE", featureidkey="properties.NameDUT", projection="mercator", color="CLUSTER", hover_data=["PROVINCE", "INFECTION_RATE", "HOSPITALISATION_RATE", "TEST_POS_PERCENTAGE", "CLUSTER"])

fig.update_geos(fitbounds="locations", visible=False)

fig.show()
```
I already noticed when I plot 1 province at a time it draws the outline of the province, leaves the province empty and colors the outside. This way every next one overrides the earlier ones.
Is there a way in plotly to ask the method to draw it the way I want?
Or do I have to change my geojson file, if so what do I have to change and how do I do that?

**Comment by nicolaskruchten** [comment]
This can happen if your geojson file is "badly wound"... You can repair it with https://pypi.org/project/geojson-rewind/

**Comment by nicolaskruchten** [comment]
Here's some code I've used in the past to fix this: https://github.com/plotly/plotly.py/issues/2619#issuecomment-728984691

**Comment by JonasDeBoeck** [comment]
I am having troubles installing geopandas on my windows machine using pip so I jsut used the rewind method from geojson on my json object. The result is still the same as before.
