### ISSUE TITLE
Scatter show color value with hover

### ISSUE THREAD

**Issue by eulerreich** [plotly/plotly.py#326]
There isn't a flag for color under `hoverinfo` for `Scatter`, so I figure I can't do it currently. If that's indeed the case, it'd be nice to be able to see this info, especially when color is used for a 3rd dimension.

BTW, the example at https://plot.ly/python/line-and-scatter/ says

```
 Showing the colorscale for scatter plots (like heatmaps) is currently unsupported.
```
but it looks like the color bar is working now for scatter?

**Comment by chriddyp** [comment]
hey @eulerreich - great point. that'd be a cool `hoverinfo` option (cc @etpinard @cldougl ). For now, you'll have to add this as custom text:

`trace['text'] = [color: '+i for i in trace['marker']['color']]`

I'll repoen the other documentation issue in github.com/plotly/documentation/tree/source

**Comment by eulerreich** [comment]
Has this hoverinfo been implemented?

**Comment by chriddyp** [comment]
@eulerreich - it hasn't, but the `text` attribute workaround works for now

**Comment by amellnik** [comment]
I think this should be reopened -- this workaround doesn't work if the `text` field is already being used for something else.

**Comment by devxpy** [comment]
This works.

```
fig = go.Figure(data=go.Scatter(
    x=x, y=y,
    text=z,
    mode='markers',
    marker=dict(
        color=z,
    )
))
fig.show()
```

**Comment by m-crown** [comment]
This doesn't work if you want to have your text field show information independent of the marker colour, but want the colour value to be shown in the hover.
