### ISSUE TITLE
[question] Use jupyter_packaging for packaging python + javascript for jupyterlab 3

### ISSUE THREAD

**Issue by xmnlab** [plotly/plotly.py#3266]
Hi everyone!

Reading `setup.py`, it seems plotly is not using `jupyter_packaging` for packaging. As it is very helpful because it ships the python code and the pre-built javascript code and we wouldn't need to run `jupyter labextension install` anymore, I was wondering if there is any plan to add this feature?

We found an issue here where we don't have permission to install an extension manually to our server, so such a new feature would be very helpful!

Thanks for the attention!

**Comment by nicolaskruchten** [comment]
I just released [version 5.0 of Plotly](https://github.com/plotly/plotly.py/releases/tag/v5.0.0) a few minutes ago and it does now automatically install a federated extension, so there should be no need to manually run `jupyter labextension install` any more :)

**Comment by xmnlab** [comment]
that sounds great! thanks for the fast response!
