### ISSUE TITLE
Plotly Figure and FigureWidget not working in Jupyterlab 2

### ISSUE THREAD

**Issue by massgh** [plotly/plotly.py#3281]
When I updated Jupyterlab to version 2, plotly stopped working there. Old extensions do not work. Is there a workaround in progress for rendering graphs in Jupyterlab 2?

**Comment by nicolaskruchten** [comment]
Please check out our troubleshooting guide here https://plotly.com/python/troubleshooting/ ... We have instructions for JupyterLab 1 & 2 as well as 3 (which is the recommended version now!)

**Comment by massgh** [comment]
Thanks. It worked perfectly. 👍
