### ISSUE TITLE
Line Dash Sequence Issue in Plotly 5.1.0

### ISSUE THREAD

**Issue by lucasjamar** [plotly/plotly.py#3283]
In plotly 4.14.3, specifying category orders on a filtered dataset did not change anything to the line dash sequence. The curves would have still appeared with the dash shape specified in dash line sequence.

![image](https://user-images.githubusercontent.com/39372418/123953109-28ab1a80-d9a7-11eb-9f2e-bf9a6f9e154b.png)

However, in plotly 5.10, specifying category orders on a filtered dataset will lead to the nth category order being mapped to the nth value in line dash sequence even though the other categories in category order do not exist.

![image](https://user-images.githubusercontent.com/39372418/123954366-9b68c580-d9a8-11eb-812f-184bb1fb04a9.png)

Here is the same code run in 4.14.3 and 5.1.0:
```
import plotly.express as px

df = px.data.gapminder().query("country=='New Zealand'")
fig = px.line(df, x="year", y="lifeExp", line_dash='country', line_dash_sequence=["solid", "longdashdot"], category_orders={"country": ["Australia", "New Zealand"]})
fig.write_html("fig.html")
```
Is this behaviour expected in plotly 5.1.0 or a bug? For me, the behaviour in 4.14.3 made more sense.

Cheers :)

**Comment by nicolaskruchten** [comment]
We changed this behaviour intentionally: in 5.x this is a feature, it means that if your category_order is A,B,C, then B always gets the same dash-pattern regardless if A is in the dataset. This makes it easier to reuse the same category_orders across different subsets of the same dataset without B sometimes being dashed and sometimes not. The same applies to color and symbols and facets: if your dataset maps color to continents, say, when you give the same category_order to two different PX calls, the same continent is always the same color across charts, independent of the presence/absence of the others.

**Comment by lucasjamar** [comment]
Thanks for specifying this :) . Closing
