### ISSUE TITLE
Plotly Express: Allow users to always use lists to refer to columns

### ISSUE THREAD

**Issue by samlishak-artemis** [plotly/plotly.py#3284]
I've created a basic Dash wrapper for Plotly Express to allow interactive data exploration of a dataframe, parsing the [docs](https://github.com/plotly/plotly.py/blob/master/packages/python/plotly/plotly/express/_doc.py) for information on how to generate a form for a given plot type (which works surprisingly well, although was a little fiddly to set up). 

Using multi-select dropdowns for column name references, I've had to do some sanitisation of the list returned from that dropdown to avoid errors in Plotly Express:
 - If the list is empty, convert to None
 - If the list is length 1, just pass in first entry
 
Obviously the main use case of Plotly Express is for it to be used programatically, so this isn't a massive deal, but when calling it inside an interactive UI it would be helpful if Plotly Express could handle these transformations itself. I know it isn't as simple as I'm making out as Plotly Express may end up misinterpreting what the user passed in, but I thought I'd at least record the idea here.

An example of the errors that are encountered is below. One point to note is that the `KeyError: 'variable'` error could be made clearer.

```python
df = pd.DataFrame([{"a": x, "b": x**2, "c": x**3} for x in range(400)])

# Plot columns "b" and "c" vs "a", with marker sizes scaled by column "a":
px.scatter(df, x="a", y=["b", "c"], size="a")  # Works

# If we didn't convert len=1 lists into strings:
px.scatter(df, x=["a"], y=["b", "c"], size="a")  # ValueError: Cannot accept list of column references or list of columns for both `x` and `y`.

# If we cleared the dropdown for "y" so it was empty (implicitly plotting against index on the y axis), but didn't convert its value from [] to None:
px.scatter(df, x="a", y=[], size="c")  # KeyError: 'variable'
px.scatter(df, x="a", y=None, size="c")  # Works
```

**Comment by mirianfsilva** [comment]
I'm having the same problem.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
