### ISSUE TITLE
Feature Request: Add Background-Color Option for Text labels on Graphs

### ISSUE THREAD

**Issue by jfarnsworth95** [plotly/plotly.py#3295]
Since `<span style='color: #ff7f0e'>x</span>` works to color the text in a label for a bar graph, I gave the 'background-color' style setting a shot to solve problems where labels aren't easily visible on graphs. To my surprise, that didn't work. 

An example of this would be useful is where the pattern[shape] is set to ".", and the label blends into the background of the graph itself.
The ability to set the background color, or an option to have a bootstrap like badge that defaults to the bar's color would be very helpful albeit situationally. 

I've tried my best to look for a way to do this, but all I found was annotations, which seems needlessly difficult. 
Please do let me know if there is an easier way that I've missed.

**Comment by jfarnsworth95** [comment]
![image](https://user-images.githubusercontent.com/16585546/125113561-7104bf80-e0ae-11eb-9cb4-58ac299cb3b3.png)
Image example of label blending into the background

**Comment by TortoiseHam** [comment]
One thing you could try as an alternative solution is to use the text-shadow tag to draw an outline around the text in an opposing color. For example, to surround a black label with a white border:

`text='<span style="text-shadow: -1px 1px 0 #FFFFFF, 1px 1px 0px #FFFFFF, 1px -1px 0px #FFFFFF, -1px -1px 0px #FFFFFF;">Label Goes Here</span>',`
