### ISSUE TITLE
Discrepancy between install_requires and requirements.txt

### ISSUE THREAD

**Issue by maresb** [plotly/plotly.py#3301]
Question: Should we be pinning `six` at `1.15.0`? Now that `six` is on `1.16.0` this can lead to downgrades.

[From `setup.py`](https://github.com/plotly/plotly.py/blob/17b7c27f9e17b413b6958835ad53dc1aefb90834/packages/python/plotly/setup.py#L551):
```python
install_requires=["tenacity>=6.2.0", "six"],
```
There seems to be no pinning from `setuptools`.

However, [from `requirements.txt`](https://github.com/plotly/plotly.py/blob/17b7c27f9e17b413b6958835ad53dc1aefb90834/packages/python/plotly/requirements.txt#L9):
```python
six==1.15.0
```
(and also `tenacity>=6.2.0`)

I notice that six is slated for removal (#3167), so I hope the pinning is unnecessary, but I'm not sure.

Any guidance on this question would be very helpful over at conda-forge regarding https://github.com/conda-forge/plotly-feedstock/issues/94

**Comment by nicolaskruchten** [comment]
I can't think of a reason to pin it, I think it's just historical. We're planning on removing `six` sometime anyway as we don't support Python 2.7 any more :) See also #3167
