### ISSUE TITLE
fig.to_image does hangs, Windows

### ISSUE THREAD

**Issue by Tooblippe** [plotly/plotly.py#3304]
I have no problemson my Mac and Linux,

Using the python library

On Windows 10, Python 3.6, 3.7, 3.8 in Venv as well as 3.8 in Conda the fig.to_image(format="png", engine='kaleido') just hangs. I have tested inside and outside virtual environment. 

I have searched widely and also se `pio.kaleido.scope.mathjax = None
` to none as some suggests without any luck.

I am unsure what to do. Nothing in Kaleido or web searches have helped.

**Comment by fangniuer** [comment]
Hello, we have encountered the same problem. How did you solve it？thank you！ @ Tooblippe

**Comment by Tooblippe** [comment]
Hi,

We are using plot;y 4.7.1 which seems to work.

Regards

**Comment by fangniuer** [comment]
Thank you for your reply.

Regards

**Comment by nicolaskruchten** [comment]
See https://github.com/plotly/Kaleido/issues/112

**Comment by ronak1009** [comment]
I am also facing the same issue for python 3.9
With Python 3.9, If I try to downgrade kaleido to 0.1.0 -> it fails.
```
Installing collected packages: kaleido, retrying, plotly
ERROR: Could not install packages due to an OSError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Python\\Python39\\Lib\\site-packages\\kaleido\\executable\\version'
Consider using the `--user` option or check the permissions.
```

Also similar issue was found on a headless linux on cloud running centos7 with Python 3.9

**Comment by gvwilson** [comment]
Closing in favor of tickets in Kaleido repo - thank you. @gvwilson
