### ISSUE TITLE
express scatter_3d not showing in jupyter

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [plotly/plotly.py#3306]
Hello there!

So I am trying to create a 3d plot

```python

pca = PCA(dims=3)
points = pca(cluster.state.points)
fig = px.scatter_3d(
    points, x=0, y=1,
    color=res.preds
)
fig.update_traces(marker_size=8)
fig.show()

```

Where points is an `[N,3]` matrix, no output is produced

![image](https://user-images.githubusercontent.com/15908060/126282290-1fbee245-0979-47c4-8d7c-4cfe6170d381.png)

I am using:

```
ubuntu 20.04
python 3.8.10
jupyter-notebook 6.4.0
plotly 5.1.0
```

Thanks!

**Comment by nicolaskruchten** [comment]
For a 3d scatter plot you need to provide `x`, `y` and `z` at least :)

**Comment by FrancescoSaverioZuppichini** [comment]
Ops :) By setting `z=2` it works. Thank you!
