### ISSUE TITLE
Converted IPython2 to Jupyter notebooks not displaying properly

### ISSUE THREAD

**Issue by theengineear** [plotly/plotly.py#331]
> We recently upgraded from IPython2 to IPython4/Jupyter. Although we can display new plot.ly plots in our notebooks, our old notebooks are no longer correctly displaying the old embedded plots.

Related? #322

**Comment by Kirn-Opower** [comment]
I finally figured this issue out. Loading an iframe is considered potentially malicious, so Jupyter doesn't allow it by default. You have to mark the notebook as trusted under File->Trust Notebook. Then the IFrame renders. I'm not sure what criteria Jupyter uses to determine that a notebook is trusted, but it might consider all notebooks from previous releases of IPYNB as untrusted by default.

**Comment by jonmmease** [comment]
Closing as this seems to have been resolved, and I have not seen this issue with modern versions of plotly and jupyter. Feel free to open a new issue against version 3 if there's still a problem
