### ISSUE TITLE
Dropdown menu not updating layout and data

### ISSUE THREAD

**Issue by bitterteriyaki** [plotly/plotly.py#3325]
As the title says, the dropdown menu does not update layout or data values. I am using the latest version of `plotly` and am using it offline.

Code:
```py
specs = [[{'secondary_y': True}]]

fig = make_subplots(specs=specs) # type: ignore
# dataframes is a `Dict[str, Union[Dataframe, NDFrame]]`,
# but this union will not be used in this example.
dataframes = method(self, *args, **kwargs)

buttons: List[Dict[str, Any]] = []

for filename, _dataframe in dataframes.items():
    button: Dict[str, Any] = dict()
    button['label'] = filename
    button['method'] = 'update'

    # The title is not updating to "Sample text", data values are also not updated
    ranges: List[Any] = [{'title': {'text': 'Sample text'}}]
    button['args'] = ranges

    buttons.append(button)

menus: List[Dict[str, Any]] = [dict(buttons=buttons, active=0)]
title_text = f'{title} (None)'

# `menus` variable will have this following format:
[
  {
    'buttons': [
        {
          'label': 'String 1',
          'method': 'update',
          'args': [{'title': {'text': 'Sample text'}}]
        },
        {
          'label': 'String 2',
          'method': 'update',
          'args': [{'title': {'text': 'Sample text'}}]
        }
    ],
    'active': 0
  }
]

fig.update_layout(title_text=title_text, updatemenus=menus) # type: ignore
fig.show() # type: ignore
```

**Comment by forainychen** [comment]
try to change the 'method': 'update' to 'method': 'relayout' to see if it works

**Comment by soukyomi** [comment]
Hi, @forainychen! Thank you for the answer.

I managed to make the title change dynamically but I currently have difficulty updating the chart data:
```py
specs = [[{'secondary_y': True}]]
fig = make_subplots(specs=specs) # type: ignore

buttons: List[Dict[str, Any]] = []

# data: Dict[str, DataFrame]
for filename, dataframe in data.items():
    index = list(dataframe.index) # type: ignore

    button: Dict[str, Any] = {}
    button['label'] = filename
    button['method'] = 'update'

    # I still don't know how to change the chart data.
    # I currently have multi-bar charts (Y-axis) stacked against a period of time (X-axis),
    # all with line chart on a secondary Y-axis. Look at the attached image to understand what I'm saying.

    args: List[Dict[str, Any]] = []
    args.append({}) # for some reason I need to add an empty dict to make dynamic titles work
    args.append({'title': {'text': f'{title} ({filename})'}})
    button['args'] = args

    buttons.append(button)

updatemenus = [{'buttons': buttons}]
fig.update_layout(updatemenus=updatemenus) # type: ignore

fig.update_xaxes(rangeslider_visible=True) # type: ignore
fig.show() # type: ignore
```

Basically what I want to do is change the data on this chart every time I change the menu option. I'm wondering how can i do this?

![image](https://user-images.githubusercontent.com/82721542/134735417-8472025c-2b2d-401c-b3ae-a77da54676f2.png)

**Comment by forainychen** [comment]
As the example shown in the link
https://plotly.com/python/dropdowns/#update-dropdown

The args is a list, the first item (where you put the empty dict) is used to control the data, the second item is used to control the layout. and the method is set to "update" to control both data and layout

args.append({}) # for some reason I need to add an empty dict to make dynamic titles work
args.append({'title': {'text': f'{title} ({filename})'}})

**Comment by soukyomi** [comment]
Hi, @forainychen. Thank you for the answer.

> The args is a list, the first item (where you put the empty dict) is used to control the data, the second item is used to control the layout. and the method is set to "update" to control both data and layout

I understand this part, but I was wondering how do I update the data of each bar and row, and the X axis values ​​can also change, how can I do this?
