### ISSUE TITLE
Animated charts exported to html automatically play when opened

### ISSUE THREAD

**Issue by MaxGhenis** [plotly/plotly.py#3332]
For example, see this from [this notebook](https://colab.research.google.com/drive/1v5phcV9mbRi5huTKSdz6I1xtYSRGB5Mx?usp=sharing); `fig.show()` doesn't autoplay animations, but `fig.write_html()` files do.

![plotly-autoplay](https://user-images.githubusercontent.com/6076111/128140464-a905ea9a-f236-449a-b999-76c55d5f90b0.gif)

That uses the latest plotly, and I've also reproduced it locally opening the html output in a browser rather than a Colab/Jupyter notebook.

Is it possible to prevent the autoplay when exporting?

**Comment by brunolaporais** [comment]
Hi @MaxGhenis, `write_html` receives `auto_play` parameter. You can change it to `False`.
https://plotly.com/python/interactive-html-export/
