### ISSUE TITLE
tick is not well aligned with axis

### ISSUE THREAD

**Issue by Nightmare-n** [plotly/plotly.py#3353]
![plotly_bug](https://user-images.githubusercontent.com/47742823/130311505-66a658a8-8438-44aa-b665-f34c84240a90.png)
see the 71 and 20, and changing the tick line width cannot solves this issue

**Comment by charlesmoatti** [comment]
Same problem here, 
![Screenshot from 2022-10-07 11-32-52](https://user-images.githubusercontent.com/39098157/194523334-df6ad81b-c289-4417-b526-60d5f6dd4be8.png)

The first tick is not well aligned with the y axis, although I have manually set the yaxis_range to [0.88,1]

**Comment by alexcjohnson** [comment]
#3629 was opened later but has more discussion - so I'll close this one as a duplicate.
