### ISSUE TITLE
Performance issues fig.add_vrect

### ISSUE THREAD

**Issue by Sank-WoT** [plotly/plotly.py#3355]
Hello. I have the problem with performance of fig.add_vrect

code
for index, row in dfUpload.iterrows():
print(f’Step {index} addition {time.time() - start_time}’)
fig.add_vrect(x0=row[‘BSTART’], x1=row[‘BEND’],
annotation_text=row[‘nam’], annotation_position=“top right”,
fillcolor=row[‘color’], opacity=0.3, line_width=0)
print(f’Step {index} added {time.time() - start_time}’)

Step 0 addition 6.687209367752075
Step 0 added 6.690212249755859
Step 1 addition 6.690212249755859
Step 1 added 6.695227861404419
Step 2 addition 6.695227861404419
Step 2 added 6.70222806930542
Step 3 addition 6.70222806930542
Step 3 added 6.710227966308594
Step 4 addition 6.710227966308594
Step 4 added 6.7192277908325195
Step 5 addition 6.720227956771851
Step 5 added 6.73122763633728
…
Step 18 addition 7.010226488113403
Step 18 added 7.04421329498291
Step 19 addition 7.04421329498291
Step 19 added 7.080225944519043
Step 20 addition 7.080225944519043
Step 20 added 7.118224143981934
Step 21 addition 7.118224143981934
Step 21 added 7.158225774765015
Step 22 addition 7.158225774765015
Step 22 added 7.200225353240967
Step 23 addition 7.200225353240967
Step 23 added 7.243214845657349
Step 24 addition 7.244225025177002
Step 24 added 7.288224935531616
Step 25 addition 7.288224935531616
…
Step 40 addition 8.189055442810059
Step 40 added 8.263055086135864
Step 41 addition 8.263055086135864
Step 41 added 8.338054895401001
Step 42 addition 8.339054822921753
Step 42 added 8.41605281829834
Step 43 addition 8.41605281829834
Step 43 added 8.495052576065063
Step 44 addition 8.49605417251587
Step 44 added 8.576043367385864
Step 45 addition 8.576043367385864
Step 45 added 8.659053087234497
Step 46 addition 8.659053087234497
Step 46 added 8.744052648544312
Step 47 addition 8.745052576065063
Step 47 added 8.834052085876465
Step 48 addition 8.834052085876465
Step 48 added 8.92204999923706
Step 49 addition 8.923098087310791
Step 49 added 9.013051509857178
Step 50 addition 9.013051509857178
Step 50 added 9.105050802230835
…
Step 80 addition 12.666525840759277
Step 80 added 12.817530393600464
Step 81 addition 12.817530393600464
Step 81 added 12.97252607345581

As you can see from the log, performance down.
step 1
6.690212249755859 - 6.695227861404419 ~ 0.005
step 81
12.97252607345581 - 12.817530393600464 ~ 0.16

the difference is 32 times!!!

I am outputting 82 rectangles in 7 seconds !!!

Please, fix the problem.

**Comment by tamxomdao** [comment]
12,817530393600464

**Comment by tamxomdao** [comment]
4089041062370556

**Comment by nicolaskruchten** [comment]
This is definitely an issue, we'd love it if someone from the community wanted to step in and help optimize the performance here :)

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
