### ISSUE TITLE
Raw data for boxplots in jupyter notebooks

### ISSUE THREAD

**Issue by mys007** [plotly/plotly.py#3376]
I have observed that running `go.Box(...)` in Jupyter Notebooks results in storing all the raw data (x, y) in “application/vnd.plotly.v1+json” JSON fields in .ipynb files. I suppose this means that the actual aggregation only happens in JavaScript and not Python. This is however terribly wasteful for large datasets (huge notebooks which have to be saved or kept loaded in the browser). Ideally, only the necessary values for generating the plots and not the raw data should be stored.

Is there any general way how to do this? Or at least make box plots from statistics and not raw data?

**Comment by nicolaskruchten** [comment]
Yes, you can provide your own precomputed limits: https://plotly.com/python/box-plots/#box-plot-with-precomputed-quartiles

**Comment by mys007** [comment]
@nicolaskruchten Thanks a lot, that's true and that's what I have gone for in the end (see snipped below). But it gets tricky if one wants to exactly reproduce what plotly is drawing because they use a different definition of quartiles than default numpy's percentile. So one would need python implementation thereof, which I haven't found.

Just for anyone looking for an alternative of [grouped box plots](https://plotly.com/python/box-plots/#grouped-box-plots) created with statistics from matplotlib (warning: different definition of quartiles than in plotly):

```python
import plotly.graph_objects as go
from matplotlib.cbook import boxplot_stats

def go_box_from_matplotlib_stats(datadict, **kwargs):
    
    stats = [boxplot_stats(v)[0] for v in datadict.values()]
    sd = [np.std(v) for v in datadict.values()] if 'boxmean' in kwargs and kwargs['boxmean'] == 'sd' else None
    mean = [np.std(v) for v in datadict.values()] if 'boxmean' in kwargs and kwargs['boxmean'] else None
    notchspan = [(d['cihi']-d['cilo'])/2 for d in stats] if 'notched' in kwargs and kwargs['notched'] else None
    
    return go.Box(
        x=list(datadict.keys()),
        q1=[d['q1'] for d in stats],
        median=[d['med'] for d in stats],        
        q3=[d['q3'] for d in stats],
        lowerfence=[d['whislo'] for d in stats],
        upperfence=[d['whishi'] for d in stats],
        sd=sd,
        mean=mean,
        notchspan=notchspan,
        **kwargs
    )


fig = go.Figure()

fig.add_trace(go_box_from_matplotlib_stats(
    {'day 1': [0.2, 0.2, 0.6, 1.0, 0.5, 0.4], 'day 2': [0.2, 0.7, 0.9, 0.1, 0.5, 0.3]},
    name='kale',
    marker_color='#3D9970'
))
fig.add_trace(go_box_from_matplotlib_stats(
    {'day 1': [0.6, 0.7, 0.3, 0.6, 0.0, 0.5], 'day 2': [0.7, 0.9, 0.5, 0.8, 0.7, 0.2]},
    name='radishes',
    marker_color='#FF4136'
))
fig.add_trace(go_box_from_matplotlib_stats(
    {'day 1': [0.1, 0.3, 0.1, 0.9, 0.6, 0.6], 'day 2': [0.9, 1.0, 0.3, 0.6, 0.8, 0.5]},
    name='carrots',
    marker_color='#FF851B'
))

fig.update_layout(
    yaxis_title='normalized moisture',
    boxmode='group'
)

fig.show()
```

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
