### ISSUE TITLE
Update networkx ipython notebook

### ISSUE THREAD

**Issue by jackparmer** [plotly/plotly.py#338]
The plotly networkx / network graphs tutorial is out-of-date. While we're cleaning up the docs, lets update it with this:

https://gist.github.com/jackparmer/d03fb8eec4379fa0d5b8

We should also add plot.ly/python/network-graph to the main docs (and thumbnail)

**Comment by cldougl** [comment]
added to main docs: https://plot.ly/python/network-graphs/
updated nb: https://plot.ly/ipython-notebooks/network-graphs/ (^same)
added emilia's nb: https://plot.ly/ipython-notebooks/networks/
