### ISSUE TITLE
plotly px.choropleth doesn't seem to support small Caribbean countries

### ISSUE THREAD

**Issue by KangboLu** [plotly/plotly.py#3388]
I work for the UN and I am a heavy plotly user. I used the 3 letter country code to plot the data for Caribbean regions, but only a few bigger countries with larger land areas are shown in the default px.choropleth map. Another thing is the Bahamas region has less area than it actually has in plotly choropleth. Same for Cuba. **One island is missing for Cuba**. Cuba won't be happy at all.

I guess I should build my own GeoJSON dataset and plot with GeoJSON instead of using the default px.choropleth map layer? Is plotly going to add more details in the future for choropleth? At least make the existing shown countries complete?

The red circled regions are missing on plotly express choropleth map.

**You can also verify it in the documentation example. If you zoom in to the Caribbean region, you will see those countries** missing. https://plotly.com/python/choropleth-maps/

**Plotly express**
![image](https://user-images.githubusercontent.com/17485959/133634510-f350ebdf-d745-4db4-8ef8-8112a28a3702.png)

**Caribbean map in Google map**
![image](https://user-images.githubusercontent.com/17485959/133633588-885b663c-db35-47d2-a1c1-7c41ca70226f.png)
![image](https://user-images.githubusercontent.com/17485959/133632534-f637a624-3ad9-42b0-a1b8-fe5d304a1d68.png)

Bahamas in plotly vs Bahamas in Google map and GeoJSON:
![image](https://user-images.githubusercontent.com/17485959/133634995-ec86b6af-f824-4c49-9927-1b2e9115faa9.png)
![image](https://user-images.githubusercontent.com/17485959/133634885-04ee3271-14ad-4963-9f6f-069436141a4c.png)
![image](https://user-images.githubusercontent.com/17485959/133635502-535c8d1f-3090-49ca-bb4c-b8d5c1b1c439.png)

**Cuba in plotly vs Cuba in Google map and GeoJSON**
![image](https://user-images.githubusercontent.com/17485959/133636655-6e107e38-8c8f-4061-a92c-c08ffd642cc5.png)
![image](https://user-images.githubusercontent.com/17485959/133636460-b70e7a4f-e2d7-48ce-8ec4-a286a2991f9d.png)
![image](https://user-images.githubusercontent.com/17485959/133636543-13402cee-19ad-41d8-ac01-c900b0b7f0ab.png)

**Comment by nicolaskruchten** [comment]
Yes, we ship two base maps of different resolutions and we default to the coarser one: https://plotly.com/python/map-configuration/#physical-base-maps

There will always be limits to the resolution of the polygons we ship with, and if you need arbitrarily-high resolutions, you'll need to provide your own polygons: https://plotly.com/python/choropleth-maps/#choropleth-map-using-geojson

**Comment by KangboLu** [comment]
@nicolaskruchten I see. Thanks for the info. I will create my own GeoJSON file to have a finer resolution.

**Comment by nicolaskruchten** [comment]
Sounds good. For UN-related use-cases I would definitely recommend making very deliberate choices for maps. For example, *please do not rely on our defaults for disputed areas* like Crimea, Western Sahara etc!
