### ISSUE TITLE
FigureWidget: batch_update: for_each_trace

### ISSUE THREAD

**Issue by ghost** [plotly/plotly.py#3391]
Dear all,

I do have a FigureWidget with multiple traces which "`visible`" parameter is set to "`False`".

Now I want to update the traces parameter "`visible`" with some buttons, which I created with `widgets.Dropdown`.
Using the `updatemenus `functionality of plotly was not a solution as I have multiple dependent dropdowns.

This is the solution I have developed so far which fails to update the figure when using on of the dropdowns:

```
def response(change):

    with fig.batch_update():
                
        if third_sel== "some_value":
            if top_cols_sel.value == "no":
                fig= fig.for_each_trace(lambda trace: trace.update(visible=True) if ((trace.name == first_dropdown.value) | (trace.name == "value")) else (),)
            elif second_dropdown.value == "top 5":
                fig = fig.for_each_trace(lambda trace: trace.update(visible=True) if ((trace.name == str(first_dropdown.value + "_TOP_5")) | (trace.name == "value")) else (),)
            elif second_dropdown.value == "top 10":
                fig= fig.for_each_trace(lambda trace: trace.update(visible=True) if ((trace.name == str(first_dropdown.value + "_TOP_10")) | (trace.name == "value")) else (),)

        elif third_sel== "some_other_value":
            if top_cols_sel.value == "no":
                fig= fig.for_each_trace(lambda trace: trace.update(visible=True) if ((trace.name == first_dropdown.value)) else (),)
            elif second_dropdown.value == "top 5":
                fig= fig.for_each_trace(lambda trace: trace.update(visible=True) if ((trace.name == str(first_dropdown.value + "_TOP_5"))) else (),)
            elif second_dropdown.value == "top 10":
                fig= fig.for_each_trace(lambda trace: trace.update(visible=True) if ((trace.name == str(first_dropdown.value + "_TOP_10"))) else (),)
                
first_dropdown.observe(response, names="value")
second_dropdown.observe(response, names="value")
third_dropdown.observe(response, names="value")
```

Next I put it into a container:

```
container = widgets.HBox([first_dropdown, second_dropdown, third_dropdown])
w = widgets.VBox([container,
                  all_sites],
                  height='100%',width='100%')
```
This generates a nice figure widget which doesn't show any traces. However, when using the dropdowns, the figure doesn't get updated and remains blank.

When I update the traces with the `for_each_trace `functionality and without the `batch_update` (outside the `response `function), it works. It is probably on the `batch_update` functionality, which isn't working correctly with the `for_each_trace` functionality. I already tried to replace the batch_update with update or update_traces. This isn't working as well. Do you have any idea on how to solve this? Using the data of the dataframe itself is no option, as the figure is a map which comes with many custom set parameters.

Happy to hear from you.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
