### ISSUE TITLE
paramater color_discrete_sequence in px.bar doesn't accept value in px.colors.qualitative.swatches()

### ISSUE THREAD

**Issue by vuthanhdatt** [plotly/plotly.py#3398]
in API references of px.bar, paramater **color_discrete_sequence** accept color sequences  available in the `.express.colors` submodules, specifically `plotly.express.colors.qualitative`.
![image](https://user-images.githubusercontent.com/80867452/134774151-3d9b5229-325e-4212-bf95-ec80c1015674.png)
 But when i using swatch in `plotly.express.colors.qualitative`
 
![image](https://user-images.githubusercontent.com/80867452/134774166-e568872a-1a5d-4c95-bbbf-80f0d69ecb11.png)
 px.bar announce an error.
 
![image](https://user-images.githubusercontent.com/80867452/134774227-8f35f0b1-34a1-44f8-82bd-85e5843e8a38.png)

**Comment by nicolaskruchten** [comment]
Right, so you can't just pass names of sequences (unlike with continuous scales!), you have to pass the object itself :

```python
import plotly.express as px
df = px.data.gapminder().query("continent == 'Oceania' and year==2007")
px.bar(df, x="country", y="gdpPercap", color="country",
      color_discrete_sequence=px.colors.qualitative.D3)
```
![newplot](https://user-images.githubusercontent.com/203523/134806529-5e096589-9f6e-4cf5-8f96-63bde7fc1708.png)

**Comment by vuthanhdatt** [comment]
oh, I see, thanks
