### ISSUE TITLE
Add type information for Pylance

### ISSUE THREAD

**Issue by munro** [plotly/plotly.py#3401]
A lot of the Python plotly library produces red squiggles in VS Code for Pylance.

From my experience, Pylance seems to work the best out of the box versus Pyright or mypy, so that seems to be the best tool focus adding support for.

I think one way is to add support without altering the library is adding type information to https://github.com/python/typeshed — but generally for my libraries I try to make use of the `typing` & `typing-extensions` modules as much as I can.  Not sure if that's possible for backwards compatibility though, so `typeshed` may be the way to go.  I've yet to add my own type information for an OS library though, so take all this with a grain of salt.

![image](https://user-images.githubusercontent.com/500774/135156534-98b8031c-4c6f-47d3-b771-221053f85a7e.png)

**Comment by gvwilson** [comment]
Hi ,
Greetings from Plotly - I started a new gig as manager of the libraries team seven weeks ago, and so far I'm feeling like the longer I'm here, the further behind I am :-) We're thinking about overhauling our charts, and our designer would be grateful for a chance to talk with a few people about what changes they'd like to see - any chance you could spare a bit of time to chat with him online?
Hope you and yours are safe and well,
Greg
