### ISSUE TITLE
Fix np.bool dtype deprecation

### ISSUE THREAD

**Issue by jproctor10** [plotly/plotly.py#3403]
https://github.com/plotly/plotly.py/blob/03979d105c65dda3df3a155322eaff18f203b03f/packages/python/plotly/plotly/express/_imshow.py#L349

This line is causing warnings related to https://numpy.org/devdocs/release/1.20.0-notes.html#using-the-aliases-of-builtin-types-like-np-int-is-deprecated

**Comment by nicolaskruchten** [comment]
Closed by #3705.
