### ISSUE TITLE
`TypeError: unhashable type: 'numpy.ndarray'` in `px.bar` when a value of `color` is a `np.array`

### ISSUE THREAD

**Issue by MaxGhenis** [plotly/plotly.py#3410]
When a value in a `DataFrame` passed to `px.bar`'s `color` argument is a `np.array` (e.g. from the `np.array`, `np.where` or other `np` functions), an error arises.

```python
import pandas as pd
import numpy as np
import plotly.express as px

df = pd.DataFrame(dict(x=["a"], y=[-5], color=["blue"]))
px.bar(df, "x", "y", "color")  # Works fine.

df_np_color = pd.DataFrame(dict(x=["a"], y=[-5], color=[np.array("blue")]))
df_np_color  # Prints identically to df.
df_np_color.equals(df)  # True.

px.bar(df_np_color, "x", "y", "color")
```
Returns:
```shell
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-7-0913348771f5> in <module>()
----> 1 px.bar(df_np_color, "x", "y", "color")

5 frames
/usr/local/lib/python3.7/dist-packages/pandas/core/algorithms.py in unique(values)
    397 
    398     table = htable(len(values))
--> 399     uniques = table.unique(values)
    400     uniques = _reconstruct_data(uniques, original.dtype, original)
    401     return uniques

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.unique()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable._unique()

TypeError: unhashable type: 'numpy.ndarray'
```
This error doesn't occur when `x` or `y` are `np.array` type (see [this notebook](https://colab.research.google.com/drive/1JfwaTOpcgYAcZeV6eRfyGV5Xs3ihOzsQ?usp=sharing)).

I'm using the latest `plotly`.

Possibly related: https://github.com/pandas-dev/pandas/issues/43867

**Comment by gvwilson** [comment]
Hi ,
Greetings from Plotly - I started a new gig as manager of the libraries team seven weeks ago, and so far I'm feeling like the longer I'm here, the further behind I am :-) We're thinking about overhauling our charts, and our designer would be grateful for a chance to talk with a few people about what changes they'd like to see - any chance you could spare a bit of time to chat with him online?
Hope you and yours are safe and well,
Greg
