### ISSUE TITLE
Enable custom axis transformation and/or projections (like in matplotlib)

### ISSUE THREAD

**Issue by elastufka** [plotly/plotly.py#3415]
Hello, 

I'd love it if PlotLy could support custom axis transformations (at the minimum) and custom scales and projections (the ultimate goal). This would enable people working with scientific data especially to take full advantage of PlotLy's interactivity. Much scientific data has its own coordinate system (not necessarily geographic!), so the basic axes in data units, category, etc are not sufficient for displaying this data. 

Matplotlib axis transformations seem simple enough to implement, and are documented [here](https://matplotlib.org/stable/tutorials/advanced/transforms_tutorial.html) 

Scales and projections would be super useful for non-geographic or specialized map data (astrophysics, for example), and are documented [here](https://matplotlib.org/stable/devel/add_new_projection.html)

I've tried to do this with Heatmap but have had to rely on faking the transformation by adjusting the axis labels, ticks and hovertext ([see here](https://elastufka.github.io/SAX-XRS_figures/posts/2021/09/15/Displaying_sunpy_maps_with_PlotLy.html)). This isn't a great solution, because when you zoom the ticks and labels don't adapt. If you want the pixels to stay square (or whatever shape they are natively in your coordinate system), setting a scaleanchor on one of the axes affects the shape you can zoom to, which is often inconvenient. The customdata arrays can also get quite large, resulting in a large file when exported to html. 

Thanks and I really hope to see this feature one day!

**Comment by gvwilson** [comment]
Hi ,
Greetings from Plotly - I started a new gig as manager of the libraries team seven weeks ago, and so far I'm feeling like the longer I'm here, the further behind I am :-) We're thinking about overhauling our charts, and our designer would be grateful for a chance to talk with a few people about what changes they'd like to see - any chance you could spare a bit of time to chat with him online?
Hope you and yours are safe and well,
Greg
