### ISSUE TITLE
Quiver plot line color based on direction 

### ISSUE THREAD

**Issue by janosh** [plotly/plotly.py#3416]
Is there a way, perhaps by updating the trace, to color the lines in a quiver plot based on their direction?

## Related

Here's a relatively straightforward way to do this in `matplotlib`: https://stackoverflow.com/a/40026959

**Comment by gvwilson** [comment]
Hi ,
Greetings from Plotly - I started a new gig as manager of the libraries team seven weeks ago, and so far I'm feeling like the longer I'm here, the further behind I am :-) We're thinking about overhauling our charts, and our designer would be grateful for a chance to talk with a few people about what changes they'd like to see - any chance you could spare a bit of time to chat with him online?
Hope you and yours are safe and well,
Greg

**Comment by janosh** [comment]
sure, happy to chat any time next 4 days

**Comment by gvwilson** [comment]
thanks @janosh - I'm on the road next week, so could you please email me (greg.wilson@plot.ly) and we can find a time mid-July? cheers
