### ISSUE TITLE
Suggestion for Parallel Coordinates Plot

### ISSUE THREAD

**Issue by KangboLu** [plotly/plotly.py#3420]
#### plotly express Parallel Coordinates for dataframe data with categorical and numeric data types
I notice the plotly expression version of the parallel coordinates plot doesn't accept category columns.
It would be nice to have support for that when a user has a dataframe with mixed types.  
I know it's possible to have that in the `graph_objects` by creating numeric index for `tickvals`  and set the `ticktext` to the categorical labels, but it's not that convenient. Especially, a user will have mixed data types when visualizing machine learning hyperparameter tuning history. Would it be a good feature to add for future releases?

**Comment by gvwilson** [comment]
Hi ,
Greetings from Plotly - I started a new gig as manager of the libraries team seven weeks ago, and so far I'm feeling like the longer I'm here, the further behind I am :-) We're thinking about overhauling our charts, and our designer would be grateful for a chance to talk with a few people about what changes they'd like to see - any chance you could spare a bit of time to chat with him online?
Hope you and yours are safe and well,
Greg
