### ISSUE TITLE
BUG: plotly.io.show ignoring width and height keyword arguments

### ISSUE THREAD

**Issue by GavinHuttley** [plotly/plotly.py#3422]
First, awesome project! I've been experimenting with it for bioinformatics uses ([as you can see here](https://cogent3.org/doc/draw/index.html)).

Plotly version: 5.3.1
Python version: 3.9.0
OS: macOS 11.6

Environment: Replicated in both JupyterLab and VS Code

The bug is illustrated by contrasting output from
```python
from plotly.io import show
import plotly.graph_objects as go

fig = go.Figure(go.Scatter(x=[1, 2, 3], y=[4, 5, 6]))
size = dict(height=400, width=200)
fig.layout.update(height=400, width=200) # this does affect the plot size
show(fig)
```
with output from
```python
from plotly.io import show
import plotly.graph_objects as go

fig = go.Figure(go.Scatter(x=[1, 2, 3], y=[4, 5, 6]))
show(fig, height=400, width=200) # this does not affect plot size
```
Perhaps the docstring has simply not been updated -- in which case, simple fix!

Otherwise, this is likely a regression since it used to work!

**Comment by gvwilson** [comment]
Hi ,
Greetings from Plotly - I started a new gig as manager of the libraries team seven weeks ago, and so far I'm feeling like the longer I'm here, the further behind I am :-) We're thinking about overhauling our charts, and our designer would be grateful for a chance to talk with a few people about what changes they'd like to see - any chance you could spare a bit of time to chat with him online?
Hope you and yours are safe and well,
Greg

**Comment by GavinHuttley** [comment]
Hi,

happy to chat.

Cheers,

Gavin

On 4 Jul 2024, at 2:45, Greg Wilson wrote:

> Hi ,
> Greetings from Plotly - I started a new gig as manager of the 
> libraries team seven weeks ago, and so far I'm feeling like the longer 
> I'm here, the further behind I am :-) We're thinking about overhauling 
> our charts, and our designer would be grateful for a chance to talk 
> with a few people about what changes they'd like to see - any chance 
> you could spare a bit of time to chat with him online?
> Hope you and yours are safe and well,
> Greg
>
>
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/plotly/plotly.py/issues/3422#issuecomment-2206779439
> You are receiving this because you authored the thread.
>
> Message ID: ***@***.***>


----------------------------------
Professor Gavin Huttley,
Convenor, Masters in Quantitative Biology and Bioinformatics,
Research School of Biology,
ANU College of Science,
RN Robertson Building,
46 Sullivans Creek Road,
The Australian National University
Canberra ACT 2600 Australia

+61 2 6125 5308

CRICOS #00120C

----------------------------------

**Comment by gvwilson** [comment]
thanks @GavinHuttley - I'm on the road next week, so could you please email me (greg.wilson@plot.ly) and we can find a time mid-July?
