### ISSUE TITLE
AttributeError: 'Figure' object has no attribute 'add_vrect'

### ISSUE THREAD

**Issue by km5ar** [plotly/plotly.py#3427]
'add_vrect' doesn't work, even when i try to use it on the example listed on the official guide.

I run it on google colab, my ploty version is 4.4.1
![image](https://user-images.githubusercontent.com/54015474/137776958-4cc90055-eab9-4975-9343-5ca068f020e6.png)

**Comment by gvwilson** [comment]
Hi ,
Greetings from Plotly - I started a new gig as manager of the libraries team seven weeks ago, and so far I'm feeling like the longer I'm here, the further behind I am :-) We're thinking about overhauling our charts, and our designer would be grateful for a chance to talk with a few people about what changes they'd like to see - any chance you could spare a bit of time to chat with him online?
Hope you and yours are safe and well,
Greg
