### ISSUE TITLE
Jupyter Notebook + FigureWidget produces console errors

### ISSUE THREAD

**Issue by t-anyu** [plotly/plotly.py#3428]
Hey,

I'm trying to get FigureWidget to work in Jupyter Notebook environment with the latest all packages. However FigureWidget does not show up. Then I checked browser console and it says:

Couldn't process kernel message Error: Script error for "jupyterlab-plotly"
http://requirejs.org/docs/errors.html#scripterror
    at makeError (require.js?v=d37b48bb2137faa0ab98157e240c084dd5b1b5e74911723aa1d1f04c928c2a03dedf922d049e4815f7e5a369faa2e6b6a1000aae958b7953b5cc60411154f593:168)
    at HTMLScriptElement.onScriptError (require.js?v=d37b48bb2137faa0ab98157e240c084dd5b1b5e74911723aa1d1f04c928c2a03dedf922d049e4815f7e5a369faa2e6b6a1000aae958b7953b5cc60411154f593:1735)
(anonymous) @ main.min.js?v=7af39fe9ec3585e958e8637ace5e96fe0bf3ced51a8b8b5875c571f941299779fe746bf74f02bab0f3c6e08281d6ecadafcb5b08120e98f081c9c7dd824bdfdc:38515

I think somehow the install script thinks I'm in jupyter lab environment?

Anyone has encountered this before?

**Comment by gvwilson** [comment]
Hi ,
Greetings from Plotly - I started a new gig as manager of the libraries team seven weeks ago, and so far I'm feeling like the longer I'm here, the further behind I am :-) We're thinking about overhauling our charts, and our designer would be grateful for a chance to talk with a few people about what changes they'd like to see - any chance you could spare a bit of time to chat with him online?
Hope you and yours are safe and well,
Greg
