### ISSUE TITLE
Add xkcd style template for plotly

### ISSUE THREAD

**Issue by RatanShreshtha** [plotly/plotly.py#3438]
I have been using `plotly.py` for a while now and I love this library as it is a delight to use  and plots are so beautiful.

I recently got know about the themes and templates in `plotly.py` and I wish there was one option for making plots look like [xkcd comics](https://xkcd.com/).

```python
import plotly.io as pio
pio.templates
```
```
Templates configuration
-----------------------
    Default template: 'plotly'
    Available templates:
        ['ggplot2', 'seaborn', 'simple_white', 'plotly',
         'plotly_white', 'plotly_dark', 'presentation', 'xgridoff',
         'ygridoff', 'gridon', 'xkcd', 'none']
```

And can be used in plots like below

```python
import plotly.express as px

df = px.data.gapminder()
df_2007 = df.query("year==2007")

fig = px.scatter(df_2007,
                     x="gdpPercap", y="lifeExp", size="pop", color="continent",
                     log_x=True, size_max=60,
                     template="xkcd", title="Gapminder 2007: 'xkcd' theme")
fig.show()
```

**Comment by gvwilson** [comment]
Hi ,
Greetings from Plotly - I started a new gig as manager of the libraries team seven weeks ago, and so far I'm feeling like the longer I'm here, the further behind I am :-) We're thinking about overhauling our charts, and our designer would be grateful for a chance to talk with a few people about what changes they'd like to see - any chance you could spare a bit of time to chat with him online?
Hope you and yours are safe and well,
Greg
