### ISSUE TITLE
The resource from “https://cdn.jsdelivr.net/npm/plotly.js/dist/plotly.min.js” was blocked due to MIME type (“text/plain”) mismatch (X-Content-Type-Options: nosniff).

### ISSUE THREAD

**Issue by rusdiy** [plotly/plotly.py#3448]
Recently, I get this error when using plotly in html. But weirdly enough, it does not happened in all device/browser.
I use this code to embed the html inside my web program:
`
html = fig.to_html(include_plotlyjs="require", full_html=False, config=config)
`
Image of the Console Error
![Plotly Error](https://user-images.githubusercontent.com/29059106/139866742-8131108c-fd1d-4abe-86e3-be982230b732.png)

**Comment by MartinKolarik** [comment]
Hi, Martin from jsDelivr here. We removed the size limit for that package so it should load now.

**Comment by rusdiy** [comment]
The issue has already been resolved, and it is already worked now. Thank you very much.

**Comment by nicolaskruchten** [comment]
🙈 thanks @MartinKolarik ! 

cc @archmoj @alexcjohnson ;)

**Comment by archmoj** [comment]
Which [version(s) of `plotly.js` ](https://github.com/plotly/plotly.js/releases) cased this issue?

**Comment by MartinKolarik** [comment]
@archmoj v2.6.0 went above 100 MB, which is currently our default limit for the cdn.

**Comment by archmoj** [comment]
Wondering if one could switch to `https://cdn.jsdelivr.net/npm/plotly.js-dist` instead?

**Comment by MartinKolarik** [comment]
> Wondering if one could switch to https://cdn.jsdelivr.net/npm/plotly.js-dist instead?

Quite possibly, but the main package also seems to include localization support and other dist files, which I'm not sure if are available elsewhere.

**Comment by archmoj** [comment]
2.6.0 tar listed to be 84.9MB here https://app.circleci.com/pipelines/github/plotly/plotly.js/5855/workflows/6942be6c-f93f-4c8e-a21c-e5b19efc4b4f/jobs/138828?invite=true#step-110-1114

But strangely 2.6.0 size on `npm` show 107MB here: https://app.circleci.com/pipelines/github/plotly/plotly.js/5855/workflows/6942be6c-f93f-4c8e-a21c-e5b19efc4b4f/jobs/138828?invite=true#step-110-1114

**Comment by MartinKolarik** [comment]
Not sure how the npm cli calculates it but the final version indeed is 107 MB.

**Comment by archmoj** [comment]
I found the source of this problem.
FYI - I opened https://github.com/plotly/plotly.js/issues/6007 and I'll work on the fix for it.

**Comment by archmoj** [comment]
Addressed in https://github.com/plotly/plotly.js/releases/tag/v2.6.1.
