### ISSUE TITLE
Need to change default orientation of 3d plot

### ISSUE THREAD

**Issue by vidhyadhari** [plotly/plotly.py#346]
I need to get a top view of my plot. Attaching the screenshots of default and required orientation. 

I used 

https://plot.ly/javascript-graphing-library/reference/#scene-cameraposition

in my code. But the camera position always remains in the same direction.

Also attaching screenshot of my code.
![code](https://cloud.githubusercontent.com/assets/7133119/11100967/42bcc80a-8882-11e5-8a31-83c2fc280757.png)
![defaultorientation](https://cloud.githubusercontent.com/assets/7133119/11100968/42bdbd8c-8882-11e5-9cf0-1b19da268d79.png)
![desiredorientation](https://cloud.githubusercontent.com/assets/7133119/11100969/42be9040-8882-11e5-8e5d-0955c56f2d54.png)

**Comment by etpinard** [comment]
Use `scene.camera` instead: https://plot.ly/python/reference/#layout-scene-camera

**Comment by etpinard** [comment]
More info here: http://nbviewer.ipython.org/github/etpinard/plotly-misc-nbs/blob/master/3d-camera-controls.ipynb

**Comment by vidhyadhari** [comment]
Thanks for reply and link.

I have tried the example, it works fine. But when I write it in my own code it fails with this error message:
plotly.exceptions.PlotlyDictKeyError: Invalid key, 'camera', for class, 'Scene'.

    Run 'help(plotly.graph_objs.Scene)' for more information.

    Path To Error:
    ['layout']['scene']['camera']

    Additional Notes:
    Couldn't find uses for key: 'camera'

Here is my code:

    camera = dict(
        up=dict(x=0, y=0, z=1),
        center=dict(x=0, y=0, z=0),
        eye=dict(x=0.1, y=0.1, z=2.5)
    )
    layout = dict(
        title = '1202L2 20120402',
        showlegend=True,
        legend=Legend(
            x=0,
            y=100
        ),
        scene=dict(
            camera=camera
        )
    )
    fig = Figure(data=data, layout=layout)
    plot_url = py.plot(fig)

**Comment by etpinard** [comment]
Upgrading your `plotly.py` should solve this:

```
pip install plotly --upgrade
```

**Comment by vidhyadhari** [comment]
Thanks it worked
