### ISSUE TITLE
add_vline position different in write_image

### ISSUE THREAD

**Issue by mvwick** [plotly/plotly.py#3460]
I can not figure out how to properly set the vline position so it shows up in `fig.show()` and `fig.write_image()`. At the moment I use a workaround, by specifying the position separate. With `plot_save=True` it shows up in` write_image()` and with `False `in `show()`.

Here is  an example:
```
import pandas as pd
import numpy as np
import plotly
#import kaleido
import plotly.graph_objects as go

print(f"plotly version: {plotly.__version__}")
#print(f"kaleido version: {kaleido.__version__}")
print(f"numpy version: {np.__version__}")
print(f"pandas version: {pd.__version__}")
```
plotly version: 5.1.0
numpy version: 1.21.2
pandas version: 1.3.4
```
##### change me #######
plot_save=True # True False
#######################

# Example
data = pd.DataFrame(np.random.randint(0,100,size=(10, 10)), columns=np.linspace(0,100,10))
fig = go.Figure()
trace1=go.Heatmap(
    x=data.index,
    y=data.columns,
    z=data,
    colorscale="Greys",
    colorbar={"title":"value"},
    name="background")
fig.add_trace(trace1)

# Issue
if plot_save: # for saving the plot this positions have to be used
    y0_0=0.1;y1_0=0.5

elif plot_save==False: # for showing the plot this positions have to be used
    y0_0=10;y1_0=50

fig.add_vline(x=1,line_width=5, line_color="red",
        y0=y0_0,y1=y1_0, #does not work with write image
        )

if plot_save:  
    fig.write_image(r".\test.pdf")
fig.show()
```

**Comment by nicolaskruchten** [comment]
I'm a little puzzled about the output you're looking for... `add_vline` is intended to be used to create subplot-spanning vertical lines, so setting `y0` and `y1` is a little strange. For what it's worth, for me, I see the same output in both `fig.show()` and `fig.wite_image()` regardless of the setting of `plot_save`. If `True` then the line goes from y=10 to 50 and if `False` then the line is not visible, which is roughly what I would expect, given that when using `add_vline` the `y` value is expected to be between 0 and 1 i.e. expressed as subplot fractions.

**Comment by nicolaskruchten** [comment]
If you're trying to draw a line with defined start and end points that is not intended to span a whole subplot, I would recommend using `add_shape()` and setting all the values explicitly, thereby bypassing some of the assumptions that `add_vline()` makes, for example `add_vline()` sets `yref="y domain"` which is maybe not what you're looking for?

**Comment by mvwick** [comment]
Thank you, I think `add_shape()` is more what I am lokking for.

With my example code above and `plot_save=True` I only see the vline, from y=10 to 50, in my saved image. In my my jupyter notebook it shows up from y=0.1 to 0.5. That seems to be a problem with VSCode, which I use as editor.
When using a different editor, e.g. default editor from the anaconda navigator, it works as you described it.

`add_shape()` works in VSCode like expected, it shows the same line, in the shown and saved image.
