### ISSUE TITLE
ENHANCEMENT: Support for merged candlestick chart and market depth chart

### ISSUE THREAD

**Issue by viper7882** [plotly/plotly.py#3465]
Hi,

I've bumped into Cryptowatch for their merged candlestick chart and market depth chart:

![Cryptowatch merged candlestick chart and market depth chart](https://user-images.githubusercontent.com/28743821/141607112-311a0db8-2c21-43b0-aee9-fa7fe3623a20.png)

Based on my experience of using Plotly.py, I suspected that the merged charts aren't supported currently. Please feel free to correct me if my understanding is incorrect as well as share some insights on how to create this merged charts. Else I would like to request for your team to consider providing this support into Plotly.py.

Basically the merge is to combine candlestick chart with a bar chart with the caveat that bar chart is an overlay with the label on the Y-axis. Based on my research from the web, I couldn't find any vendor rendering this support in Python platform. If Plotly.py is considering adding this support, Plotly.py could be the very first entity to provide this feature in the market. I believe it is a great feature for many users to pursue should this support is added into Plotly.py as it provides a consolidated and intuitive view for those who are working in financial charts.

I would appreciate if you could help to relay my request above to your team for their consideration.

Thank you for your attention.

**Comment by nicolaskruchten** [comment]
This is basically a little subplot with a shared Y-axis, and it should be fairly straightforward to build a figure like this using our subplots and secondary axes features: https://plotly.com/python/multiple-axes/ :)

**Comment by viper7882** [comment]
Cool, glad to hear that @nicolaskruchten. Let me spend some time to look into multiple axes and subplot. I'm familiar with subplot but not multiple axes.

Quick check with you, multiple axes with subplot allow overlapping Y-axis as shown in the screenshot?

**Comment by nicolaskruchten** [comment]
Yes, there are basically no overlap restrictions.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
