### ISSUE TITLE
Heatmap borders

### ISSUE THREAD

**Issue by janosh** [plotly/plotly.py#3475]
Would be cool if `plotly.figure_factory.create_annotated_heatmap` had the option to specify borders around heatmap tiles as in this plot:

[![pheatmap_default-1024x1024](https://user-images.githubusercontent.com/30958850/142214898-fcc4b4d8-166e-4319-80dd-d5ec67afd298.png)](https://davetang.org/muse/2018/05/15/making-a-heatmap-in-r-with-the-pheatmap-package)

**Comment by apatange-source** [comment]
Try `create_annotated_heatmap(xgap=1, ygap=1)`

**Comment by janosh** [comment]
Gaps and borders are different things.

**Comment by nicolaskruchten** [comment]
Yes, but the visual effect is largely the same, and this is the recommended approach at this time :)

**Comment by janosh** [comment]
I'm already using gaps:

https://github.com/janosh/ml-matrics/blob/3e931f2a2a3ef64a0a9529e4a1484479f5efdc68/ml_matrics/elements.py#L455-L456

I disagree that the visual effect is largely the same:

Plotly with no border
https://github.com/janosh/ml-matrics/blob/3e931f2a2a3ef64a0a9529e4a1484479f5efdc68/assets/ptable_heatmap_plotly.svg
Matplotlib with gaps and border
https://github.com/janosh/ml-matrics/blob/3e931f2a2a3ef64a0a9529e4a1484479f5efdc68/assets/ptable_heatmap.svg

**Comment by nicolaskruchten** [comment]
Indeed, if you want gaps and borders, it's not the same. But just using gaps with a grey plotting area will give you largely the same effect as the heatmap you posted at the top of the issue :)

**Comment by janosh** [comment]
> But just using gaps with a grey plotting area will give you largely the same effect as the heatmap you posted at the top of the issue :)

Fair enough. Maybe a bad example as I'm actually plotting with transparent background.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
