### ISSUE TITLE
Changing the chart_orientation of px.bar changes the order of the rows.

### ISSUE THREAD

**Issue by apatange-source** [plotly/plotly.py#3479]
Setting the parameter 'v' works well with with px.bar but as soon as I change the parameter to 'h', the order of the axis changes.
![image](https://user-images.githubusercontent.com/83966389/142571910-af7b9e6d-8875-411a-914e-cd5ec46684bf.png)

![image](https://user-images.githubusercontent.com/83966389/142571870-970d6b30-1716-4789-9f91-61e40e7b8b26.png)

**Comment by nicolaskruchten** [comment]
Did you find the source of this behaviour or ...?
