### ISSUE TITLE
scipy.cluster.hierarchy.linkage not working with plotly.figure_factory.create_dendrogram() [LABELS]

### ISSUE THREAD

**Issue by apatange-source** [plotly/plotly.py#3485]
I'm trying to plot a dendrogram using scipy's hierarchy clustering. 

When I try to add the dataframe columns as the labels for the create_dendrogram() function, 
![image](https://user-images.githubusercontent.com/83966389/143008285-d16e00a3-3b63-42d4-b813-3d5b4b97b3dd.png)

Is there any way for me to make it work? 

It works well with scipy's inbuilt dendrogram() function.

**Comment by apatange-source** [comment]
Also there is a difference between the plolty dendrogram and the scipy dendrogram when I try to plot the plotly one without the label
![Screenshot from 2021-11-23 15-48-27](https://user-images.githubusercontent.com/83966389/143009595-967b6a61-1cb3-4f55-8ec1-9d63113fd715.png)
s.

**Comment by sheepshaker1011** [comment]
@apatange-source I met the same problem, how did you fix it?

**Comment by apatange-source** [comment]
> @apatange-source I met the same problem, how did you fix it?

Try using this: 
`x = np.transpose(df.isnull().astype(float))


    fig = ff.create_dendrogram(
        X=x,
        orientation=orientation,
        labels=df.columns.to_list(),
        linkagefun=lambda x: hierarchy.linkage(x, method),
    )

`

**Comment by sheepshaker1011** [comment]
> > @apatange-source I met the same problem, how did you fix it?
> 
> Try using this: `x = np.transpose(df.astype(float))`
> 
> `fig = ff.create_dendrogram( X=x, labels=df.columns.to_list(), linkagefun=lambda x: hierarchy.linkage(x, method), )`

Thanks!
