### ISSUE TITLE
Offline mode doesn't seem to work out of the box

### ISSUE THREAD

**Issue by coffenbacher** [plotly/plotly.py#349]
![image](https://cloud.githubusercontent.com/assets/245867/11222197/fff7542c-8d1d-11e5-9662-06b178c0bc16.png)

It just hangs here for me. Kernel information:

Python 2.7.10 |Continuum Analytics, Inc.| (default, Oct 19 2015, 18:04:42) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
IPython 4.0.0 -- An enhanced Interactive Python.

Trusted Notebook

**Comment by chriddyp** [comment]
Thanks for reporting @coffenbacher ! Taking a look at it right now.

**Comment by chriddyp** [comment]
hey @coffenbacher - I can't replicate the issue yet. is there anything inside your javascript console? Thanks so much for reporting!

**Comment by coffenbacher** [comment]
Interesting - just went back and tried it again and now it works with no changes. I had already restarted kernel, cleared cache etc. first time. Not sure what changed. Closing for now...
