### ISSUE TITLE
define() becomes undefined in Jupyter Notebook JS after init_notebook_mode

### ISSUE THREAD

**Issue by parente** [plotly/plotly.py#350]
After running `plotly.offline.init_notebook_mode()` in Jupyter Notebook, the AMD `define` function becomes undefined. This prevents other JS code in the notebook (e.g., other extensions) from working properly when it tries to lazily load other JS modules.

I see the code and comment here:

https://github.com/plotly/plotly.py/blob/b76c26b7cf3e463141b35237fe8ba68512e8fc24/plotly/offline/offline.py#L50

I'm wondering if there's a less heavy handed workaround. I don't have a solution off the top of my head, but maybe others will.

**Comment by jonmmease** [comment]
`init_notebook_mode` no longer undefines the `define` function
