### ISSUE TITLE
node(x|y) setting is not working

### ISSUE THREAD

**Issue by KunFang93** [plotly/plotly.py#3513]
Hi,

I tried to set nodes position with the following codes
```
fig = go.Figure(go.Sankey(

    node = {
        "label": abl_sankey_dict['label'],
        "x":abl_sankey_dict['x'],
        "y": abl_sankey_dict['y'],
        'pad':10},  # 10 Pixels
    link = {
        "source": abl_sankey_dict['source'][:3],
        "target": abl_sankey_dict['target'][:3],
        "value": abl_sankey_dict['value'][:3]}))

fig.show()
```
where 
```
abl_sankey_dict['label']: ['NucS3_UpE', 'NucS5_UpE', 'NucS7_UpE', 'NucS9_UpE', 'NucS10_UpE', 'NucS12_UpE', 'NucS13_UpE', 'NucS3_SE', 'NucS5_SE', 'NucS7_SE', 'NucS9_SE', 'NucS10_SE', 'NucS12_SE', 'NucS13_SE', 'NucS3_DownE', 'NucS5_DownE', 'NucS7_DownE', 'NucS9_DownE', 'NucS10_DownE', 'NucS12_DownE', 'NucS13_DownE']
abl_sankey_dict['x']:[0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9, 0.9]
abl_sankey_dict['y']:[0.1, 0.2, 0.30000000000000004, 0.4, 0.5, 0.6, 0.7000000000000001, 0.1, 0.2, 0.30000000000000004, 0.4, 0.5, 0.6, 0.7000000000000001, 0.1, 0.2, 0.30000000000000004, 0.4, 0.5, 0.6, 0.7000000000000001]
abl_sankey_dict['source'][:3]:[1, 1, 1]
abl_sankey_dict['target'][:3]:[8, 10, 11]
abl_sankey_dict['value'][:3]:[1149, 175, 16]
```
I got this figure:
![newplot](https://user-images.githubusercontent.com/15643651/145864239-33db8402-9716-4774-934a-fa5de873905f.png)

however, the position of the nodes is not as what I set in the x|y parameters. I wondered if there is any solution?
The plot I expected is this
<img width="613" alt="Screen Shot 2021-12-13 at 11 56 39 AM" src="https://user-images.githubusercontent.com/15643651/145863886-d4a9afcb-5965-486a-a014-e53abb2f724d.png">

Thanks in advance!
Kun

**Comment by adrienjacob** [comment]
Hi, I recently found out that positionning doesn't work if somes nodes have no connections, or connections with 0 value links... It seems to be the case in your example (nodes without links).
This should be fixed, or at least explained in the docs :).

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
