### ISSUE TITLE
How to export static images in formats other than "png" in the offline mode?

### ISSUE THREAD

**Issue by xiaoweiz** [plotly/plotly.py#352]
Right now, the interactive figure in IPython Notebook provides the option of exporting to the "png" format, e.g. 
<img width="948" alt="screen shot 2015-11-18 at 6 57 52 pm" src="https://cloud.githubusercontent.com/assets/4540215/11239375/74f91446-8e26-11e5-8617-3869f35427d4.png">

I'd like to save it as other formats such as "pdf", "eps", etc. Now what I do is to use the option `save and edit plot in cloud`, log in with my account, and then export as other formats. 

Is there any other way to do it "offline" without going to cloud?

**Comment by chriddyp** [comment]
Hi @xiaoweiz - there isn't right now. Programatic and PDF/EPS image generation for web-based charts requires some pretty sophisticated infrastructure that we're only able to provide through the server/cloud service environment right now.
The image generation API is accessed through

```
import plotly.plotly as py
py.image.save_as(fig)
```

The image servers don't store any data and the data and image are encrypted through SSL.

**Comment by xiaoweiz** [comment]
I c. Thanks.

**Comment by elainethale** [comment]
@chirddyp The camara icon does not work for me in Firefox. I saw a support conversation suggesting it may work in Chrome. Hopefully a fully functioning programmatic option for offline mode will be implemented sometime (soon? fingers crossed). In the meantime, would it be possible to get the offline -> png feature working in multiple browsers? I am using Jupyter notebooks with python.

**Comment by jonmmease** [comment]
Update: Offline programmatic static image export support has been released in 3.2.0: See https://medium.com/@plotlygraphs/plotly-py-end-of-summer-updates-5422c98b9058
