### ISSUE TITLE
Switch off micro and macro average curves in ROC plot for binary classification.

### ISSUE THREAD

**Issue by sorenwacker** [plotly/plotly.py#3526]
Apparently, for binary classification the micro and macro average ROC curves are meaningless. Is there a way to not plot these curves with `plot_model()`?

**Comment by nicolaskruchten** [comment]
I'm not sure what `plot_model()` function you're referring to here... could you expand a bit please?

**Comment by sorenwacker** [comment]
Hey, sorry that's the wrong repository.
