### ISSUE TITLE
No color structure in heatmap with Bluered colormap

### ISSUE THREAD

**Issue by kdpenner** [plotly/plotly.py#3528]
A Mapbox density heatmap with a viridis colormap shows color structure---purple in the wings, yellow in the center. No such structure exists with a bluered colormap. I expect blue in the wings, red in the center.

```python3
import plotly.graph_objects as go


colormaps = ["Viridis", "Bluered"]

fig = go.Figure()

trace1 = go.Densitymapbox(lat=[0]*5, lon=[0]*5, z=[10]*5, radius=20,
                          colorscale="Viridis")
fig.add_trace(trace1)

trace2 = go.Densitymapbox(lat=[1]*5, lon=[1]*5, z=[1]*5, radius=20,
                          colorscale="Bluered")
fig.add_trace(trace2)

lat_cen = 0
lon_cen = 0

fig.layout.mapbox.center = {"lat": lat_cen, "lon": lon_cen}
fig.layout.mapbox.style = "open-street-map"
fig.layout.mapbox.zoom = 5

fig.show()
```

<img width="1318" alt="Screen Shot 2021-12-23 at 4 15 36 PM" src="https://user-images.githubusercontent.com/9297904/147292708-075019c7-597e-41f7-ad72-55a530701c77.png">

plotly version 5.5.0

**Comment by empet** [comment]
This is an intriguing behaviour, but analysing  the two colorscale definitions, provided by plotly.py,
I noticed that  Viridis  has 10 entries (i.e. 10 colors), while Bluered has only two:
```
Bluered= [[0.0, 'rgb(0,0,255)'], [1.0, 'rgb(255,0,0)']]
```
It appears that mapbox cannot interpolate the colors at intermediary normalized values, v, in (0,1).
I interpolated it at 11 normalized values and got:
```
new_bluered=[[0.0, '#0000ff'],
             [0.1, '#1800e6'],
             [0.2, '#3300cc'],
             [0.3, '#4b00b3'],
             [0.4, '#660099'],
             [0.5, '#80007e'],
             [0.6, '#990066'],
             [0.7, '#b3004b'],
             [0.8, '#cc0033'],
             [0.9, '#e60018'],
             [1.0, '#ff0000']]
```
With this definition the density mapbox looks as expected:
![bluered_density](https://user-images.githubusercontent.com/3627253/147704713-eb149308-d7cc-46a0-8883-25254cb65f5d.png)

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
