### ISSUE TITLE
Add offline plotting that doesn't depend on Ipython/Jupyter

### ISSUE THREAD

**Issue by nzjrs** [plotly/plotly.py#353]
It would be good to have two extra ```plotly.offline``` API entry points that return the rendered html for a given plot, and a second that rendered a given plot in a standalone local server.

```python
def plot_html(figure_or_data)
    pass

class PlotServer(object):
    #starts a simple python http server to serve the plotly js / html
    def plot(figure_or_data, return_url=False, open_url=True):
        pass
```

**Comment by SnowRipple** [comment]
Silly question:

How can I view the plot (object IPython.core.display.HTML ) without using ipython notebook?

**Comment by nzjrs** [comment]
Ummmm, that's why I filed this issue.

**Comment by SnowRipple** [comment]
A ok.. I misundersood, thanks!  Btw is it possible to sent my output  to already running notebook from different terminal?

**Comment by chriddyp** [comment]
Great suggestion @nzjrs . I've reserved `offline.plot` for this functionality, to mimic the `py.iplot`/`py.plot` duality.

I think that I'd like to keep this server-less, and just embed all of the JS inside HTML page. That way, it's easier to share stand-alone HTML files (inside of a zipped collection)

**Comment by nzjrs** [comment]
Sounds good - although I would refer that function to have an argument that controls the embedding behaviour to be either

* standalone+embedded javascript
* standalone+CDN javascript,
* just the plot javascript+html fragment

**Comment by chriddyp** [comment]
@nzjrs yeah, that's a great idea. That way, folks can control the size of the bundles that they are sharing. 

By default, I think it should be standalone so there are no surprises when they try to open their documents in the absence of an internet connection.

**Comment by jackgolding** [comment]
I agree with nzjr with the question I asked here https://github.com/plotly/plotly.py/pull/358#issuecomment-161541472, would be really useful for us.

**Comment by brovercleveland** [comment]
Hi @chriddyp , plot.ly has been a great tool for displaying interactive 3d data for me, thanks to you and your team! I also would like to chime in and request a standalone offline feature that does not depend on ipython, it would be extremely helpful.  I am currently using a hack i grabbed from @pm8k here:
https://github.com/pm8k/get_plotly_html/blob/master/Utilizing%20Plotly%20Offline.ipynb

**Comment by nzjrs** [comment]
The changes are trivial and I will get to making them over Christmas.

However anyone is free to pick up the branch and finish it off. It's really only and hours work, max.

**Comment by chriddyp** [comment]
Here's a PR: https://github.com/plotly/plotly.py/pull/378
