### ISSUE TITLE
nbconvert --to slides compatability offline mode

### ISSUE THREAD

**Issue by bendichter** [plotly/plotly.py#355]
I'd like to create a plotly figure in an ipython notebook in offline mode, export it using nbconvert --to slides, and view it using reveal.js. I think this is in principle possible because it works with mpld3:

Put the following in a cell in slides mode:
```python
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import mpld3

mpld3.enable_notebook()

fig, ax = plt.subplots(subplot_kw=dict(axisbg='#EEEEEE'),figsize=(6,6))
ax.grid(color='white', linestyle='solid')

N = 50
scatter = ax.scatter(np.random.normal(size=N),
                     np.random.normal(size=N),
                     c=np.random.random(size=N),
                     s = 1000 * np.random.random(size=N),
                     alpha=0.3,
                     cmap=plt.cm.jet)

ax.set_title("D3 Scatter Plot", size=18);
```

Then run:
```
ipython nbconvert Untitled.ipynb --to slides --post serve
```

and you can use the plot interactively. This also works with bokeh, though I'd prefer to use plotly. I tried the following analogous code to generate a plotly graph:

```python
import plotly
from plotly.offline import download_plotlyjs, init_notebook_mode, iplot
init_notebook_mode() # run at the start of every ipython notebook to use plotly.offline
iplot([{"x": [1, 2, 3], "y": [3, 1, 6]}],show_link=False)
```

This works in the notebook, but I when I try to export to slides get "Drawing..." displayed instead of the actual figure.

**Comment by chriddyp** [comment]
Hey @bendichter - did you end up finding a solution to this? Thanks for reporting!

**Comment by bendichter** [comment]
yeah, I was being dumb. It actually works great if you put it in a layout with specified width

**Comment by thhancock** [comment]
Can you elaborate on your solution for this?

I am able to export as HTML just fine, but cannot get nbconvert slides to work.

**Comment by thhancock** [comment]
Ah.  Just solved what was going wrong for me by simply placing a plotly.js file in the directory I am running nbconvert in.

Hope that helps for anyone having this issue in the future.

**Comment by gacafe** [comment]
I can't get it to work. What does the plotly.js file need to include? All I get is the code to that makes the plot :(

**Comment by Juanlu001** [comment]
Is this supposed to be a bug or a feature? It would be great to have `autosize=True` work in the slides, but perhaps there's some limitation on the nbconvert side?

cc @tarokiritani @empet from https://github.com/plotly/plotly.py/issues/750
