### ISSUE TITLE
Cannot export png on plotly 5.5.0 with kaleido 0.2.1 on some Windows systems

### ISSUE THREAD

**Issue by mauricio-fernandez-l** [plotly/plotly.py#3559]
# Question

I am trying to export a plot as a png. Somehow, I am able to do this in some Windows systems and on some not. Is there a dependency on the Windows version? Or can it depend on the underlying graphics processing?

## Minimal Python example

I am testing this on two Windows laptops, private and work, with respectively a fresh environment `conda create -n test python=3.9` followed only by `pip install plotly kaleido` (environment yml files at the end). The minimal Python example is given in the code below (generates html and png on my private laptop, but does NOT generate a png on my work laptop)

    # %%
    
    # The following two lines do nothing
    # import plotly.io as pio
    # pio.kaleido.scope.mathjax = None
    
    import os
    import datetime
    import plotly.graph_objects as go
    now = datetime.datetime.now
    
    # %%
    
    # Delete old files
    for ext in ["html", "png"]:
        path = f"plot.{ext}"
        if os.path.isfile(path):
            print(f"Deleting {path}")
            os.remove(path)
    
    # Create plot
    fig = go.Figure()
    fig.add_trace(
        go.Scatter(
            x=[0, 2, 5],
            y=[10, 8, 13]
        )
    )
    # fig.show()
    
    # html
    print("Writing html")
    t1 = now()
    fig.write_html("plot.html")
    t2 = now()
    print(t2-t1)
    
    # png
    print("Writing png")
    t1 = now()
    fig.write_image("plot.png")
    t2 = now()
    print(t2-t1)

On my private laptop it runs, the png generation takes around 5-7 seconds. 

<img width="900" alt="screenshot_private" src="https://user-images.githubusercontent.com/49274070/150148963-e7144254-c81e-40fd-9312-d8e471aa756c.png">

On my work laptop only the html is generated, I have left it running for minutes but no png is generated. 

![screenshot_work](https://user-images.githubusercontent.com/49274070/150149056-e29cc358-3256-43da-9b98-b4df7029dbe0.png)

Am I missing something???

## Environment files

I have create new environments in private and work laptops with conda. The environments yml file contents are identical (up to the prefix, of course):

Private laptop

    name: test
    channels:
      - defaults
    dependencies:
      - ca-certificates=2021.10.26=haa95532_2
      - certifi=2021.10.8=py39haa95532_2
      - openssl=1.1.1m=h2bbff1b_0
      - pip=21.2.4=py39haa95532_0
      - python=3.9.7=h6244533_1
      - setuptools=58.0.4=py39haa95532_0
      - sqlite=3.37.0=h2bbff1b_0
      - tzdata=2021e=hda174b7_0
      - vc=14.2=h21ff451_1
      - vs2015_runtime=14.27.29016=h5e58377_2
      - wheel=0.37.1=pyhd3eb1b0_0
      - wincertstore=0.2=py39haa95532_2
      - pip:
        - kaleido==0.2.1
        - plotly==5.5.0
        - six==1.16.0
        - tenacity==8.0.1
    prefix: C:\Users\Mauricio\miniconda3\envs\test

Work laptop

    name: test
    channels:
      - defaults
    dependencies:
      - ca-certificates=2021.10.26=haa95532_2
      - certifi=2021.10.8=py39haa95532_2
      - openssl=1.1.1m=h2bbff1b_0
      - pip=21.2.4=py39haa95532_0
      - python=3.9.7=h6244533_1
      - setuptools=58.0.4=py39haa95532_0
      - sqlite=3.37.0=h2bbff1b_0
      - tzdata=2021e=hda174b7_0
      - vc=14.2=h21ff451_1
      - vs2015_runtime=14.27.29016=h5e58377_2
      - wheel=0.37.1=pyhd3eb1b0_0
      - wincertstore=0.2=py39haa95532_2
      - pip:
        - kaleido==0.2.1
        - plotly==5.5.0
        - six==1.16.0
        - tenacity==8.0.1
    prefix: C:\Users\mauriciof\Miniconda3\envs\test

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
