### ISSUE TITLE
Changing fontsize does not update margins and leads to overlapping label and ticks.

### ISSUE THREAD

**Issue by sorenwacker** [plotly/plotly.py#3569]
Using 

```
        fig = px.scatter(
            data_frame=df,
            x=x,
            y=y,
            color=color,
            size=size,
            facet_row=facet_row,
            facet_col=facet_col,
            facet_col_wrap=facet_col_wrap,
        )

        figure_font = dict(
            size=15,
            color="black"
        )

        fig.update_layout(
            autosize=True,
            height=300 * n_rows + 200,
            showlegend=False,
            margin=dict(l=50, r=10, b=200, t=50, pad=0),
            hovermode="closest",
            font=figure_font
        )
```

Leads to the following situation:

![image](https://user-images.githubusercontent.com/3391614/151073801-54e37367-aa74-4974-8101-f5a558ef9840.png)

**Comment by nicolaskruchten** [comment]
In this case you are forcing the margins yourself, and none of the auto-layout routines will override this, so if you want margins to automatically take into account font-size you'll need to un-specify them.

**Comment by sorenwacker** [comment]
You mean this line ?

`margin=dict(l=50, r=10, b=200, t=50, pad=0),`

**Comment by sorenwacker** [comment]
Ok, got it. I removed that and added auto-margin for both axes.
