### ISSUE TITLE
Issue displaying mixed 2d and 3d subplots

### ISSUE THREAD

**Issue by brovercleveland** [plotly/plotly.py#357]
Hi all, excellent work with plotly!

I have an issue regarding subplots, here is the question I had posted to stackexchange (http://stackoverflow.com/questions/33878581/3d-and-2d-subplots-in-plotly):

I'm trying to produce 3d and 2d subplots on plotly.  In a simple test case, I generate two subplots, where the first has two wireframe plots, and the second has a heatmap characterizing the difference between the two 3d plots.

When I attempt to plot either the first (3d) or the second (2d) subplot without the other one, they display correctly.  But when I attempt to plot both subplots, I get the following error (offline mode in ipython):

    Javascript error adding output!
    TypeError: Cannot read property 'overlaying' of undefined
    See your browser Javascript console for more details.

Here is the code I used to generate the plots:

    #! /usr/bin/env python
         
    from plotly import tools 
    import plotly.plotly as py
    import plotly.graph_objs as go
    from plotly.offline import download_plotlyjs, init_notebook_mode, iplot
    import numpy as np
 
    init_notebook_mode()
         
    # Creating the data
    x = np.linspace(-5, 5, 50)
    y = np.linspace(-5, 5, 50)
    xGrid, yGrid = np.meshgrid(y, x)
    R = np.sqrt(xGrid ** 2 + yGrid ** 2)
    z = np.sin(R)
    z2 = np.cos(R)
     
    line_marker = dict(color='#0066FF', width=2)
    line_marker2 = dict(color='green', width=2)
     
    scene=dict(
     xaxis=dict(
         gridcolor='rgb(255, 255, 255)',
         zerolinecolor='rgb(255, 255, 255)',
         showbackground=True,
         backgroundcolor='rgb(230, 230,230)'
     ),  
     yaxis=dict(
         gridcolor='rgb(255, 255, 255)',
         zerolinecolor='rgb(255, 255, 255)',
         showbackground=True,
         backgroundcolor='rgb(230, 230,230)'
     ),  
     zaxis=dict(
         gridcolor='rgb(255, 255, 255)',
         zerolinecolor='rgb(255, 255, 255)',
         showbackground=True,
         backgroundcolor='rgb(230, 230,230)'
     )
    )
     
    fig = tools.make_subplots(rows=1,cols=2,specs=[[{'is_3d':True},{'is_3d':False}]])
    #comment this out and subplot 2 works
    for i, j, k in zip(xGrid, yGrid, z): 
        fig.append_trace(go.Scatter3d(x=i, y=j, z=k, mode='lines', line=line_marker,name='wire1'),1,1) 
    for i, j, k in zip(xGrid, yGrid, z2): 
        fig.append_trace(go.Scatter3d(x=i, y=j, z=k, mode='lines', line=line_marker2,name='wire2'),1,1)

    #comment this out and subplot 1 works
    fig.append_trace(go.Heatmap(x=x, y=y, z=np.sqrt((z-z2)**2)),1,2) 
    fig['layout'].update(title='3d with heatmap',height=600,width=1000,showlegend=False)
    plot_url = iplot(fig)

Second question:

Assuming this can be handled, is there any way to have both subplots respond to hovermouse actions? (e.g. mouse hovering over some space in x-y on the 3d plot also highlights the corresponding box on the heatmap?)

**Comment by etpinard** [comment]
plotly.js doesn't support subplots of different types yet. 

See our release notes for more information: https://github.com/plotly/plotly.js/releases/tag/v1.0.0

**Comment by brovercleveland** [comment]
Alright, thanks.  I'll have to make do for now.
