### ISSUE TITLE
scatter_matrix is incorrect when using color and non-sorted index

### ISSUE THREAD

**Issue by shane-kercheval** [plotly/plotly.py#3577]
related to https://github.com/plotly/plotly.py/issues/3576

```
df = pd.DataFrame({
        'A': [1, 2, 3, 4],
        'B': [1, 2, 3, 4],
        'C': [1, 2, 3, 4],
    },
    index=[3, 2, 1, 0]
)
px.scatter_matrix(df)
px.scatter_matrix(df, color='C')
```

`px.scatter_matrix(df)` produces:

![Screen Shot 2022-01-31 at 9 51 05 AM](https://user-images.githubusercontent.com/14278527/151846342-2e9a5809-03b4-4738-b7f6-adb0f73b6e1f.png)

`px.scatter_matrix(df, color='C')` produces:

![Screen Shot 2022-01-31 at 9 49 30 AM](https://user-images.githubusercontent.com/14278527/151846131-0c76b1c7-1ce5-496e-b834-814b6795a436.png)

**Comment by MarcoGorelli** [comment]
Hi @shane-kercheval 

Is this your expected output

![Image](https://github.com/user-attachments/assets/3061dbca-af4c-4377-83c3-35b4d72fccb0)


?

**Comment by shane-kercheval** [comment]
Yes, thank you!
