### ISSUE TITLE
bar graph labels

### ISSUE THREAD

**Issue by mandar-avhad** [plotly/plotly.py#3579]
Hi, I'm plotting a bar graph using plotly's Figure.
But my y axis labels are long, hence they're getting cropped in some cases. So I need to know if we can change/rename the y axis labels without affecting/changing the hover labels or the hover info.

Below is my image. In this, when I hover on the bars, I get to see the y axis labels along with its values. I need to keep it as it is.
Just want to change the y axis label names. Please suggest a logic or a reference. Thanks!
![image](https://user-images.githubusercontent.com/61730638/152220020-b3b9c0b2-4874-4c4c-8b61-f594cb130d94.png)

`trace = {
                'name': '',
                "text": "",
                "type": "bar",
                "x": df["values"],
                "y": df["features"],
                "marker_color": df["color"],
                "orientation": "h"
            }
         
layout = {'title': 'Local explanation' + added_string,
          'xaxis': {
              "showgrid": True,
              "zeroline": True,
              "showticklabels": True,
              "title": {"text": "Contributions/Weights"},
              'linecolor': 'black'},
          'yaxis': {
              "showgrid": True,
              "zeroline": True,
              "showticklabels": True,
              "title": {"text": "Features"},
              'linecolor': 'black'},
          'paper_bgcolor': 'rgba(0,0,0,0)',
          'plot_bgcolor': 'rgba(0,0,0,0)',
          # 'showlegend': True,
          "barmode": "relative",
          "autosize": True,
          "bargap": 0,
          "bargroupgap": 0.10,
          "legend": {"font": {"size": 12}},
          "titlefont": {"size": 20},
          "annotations": [dict(
              x=df['values'].max() + df['values'].std(),
              y=df['features'].tolist()[-1],
              xref='x',
              yref='y',
              showarrow=False,
              text=table_annotation,
              yshift=20)],
          }
     

from plotly.graph_objs import Data, Figure
fig = Figure(data=Data([trace]), layout=layout)`

**Comment by mandar-avhad** [comment]
`trace = {
'name': '',
"text": "",
"type": "bar",
"x": df["values"],
"y": df["features"],
"marker_color": df["color"],
"orientation": "h"
}

layout = {'title': 'Local explanation' + added_string,
'xaxis': {
"showgrid": True,
"zeroline": True,
"showticklabels": True,
"title": {"text": "Contributions/Weights"},
'linecolor': 'black'},
'yaxis': {
"showgrid": True,
"zeroline": True,
"showticklabels": True,
"title": {"text": "Features"},
'linecolor': 'black'},
'paper_bgcolor': 'rgba(0,0,0,0)',
'plot_bgcolor': 'rgba(0,0,0,0)',
# 'showlegend': True,
"barmode": "relative",
"autosize": True,
"bargap": 0,
"bargroupgap": 0.10,
"legend": {"font": {"size": 12}},
"titlefont": {"size": 20},
"annotations": [dict(
x=df['values'].max() + df['values'].std(),
y=df['features'].tolist()[-1],
xref='x',
yref='y',
showarrow=False,
text=table_annotation,
yshift=20)],
}

from plotly.graph_objs import Data, Figure
fig = Figure(data=Data([trace]), layout=layout)`

**Comment by debaghosh** [comment]
Hey! I am new to Plotly, but here are some solutions that I think you may use:

1. You may try changing the dataframe's column names itself with pandas, thereby modifying the bar-graph's y-axis as per your needs.
2. You may use a [Graph Object](https://plotly.com/python/graph-objects/) where after putting the x-values from the df's "values" column, you can explicitly mention the y-values as per your need. Check the [Horizontal Bar Chart with go.Bar section
](https://plotly.com/python/horizontal-bar-charts/)

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
