### ISSUE TITLE
Choropleth: animation_frame does not working with geojson

### ISSUE THREAD

**Issue by Yuri-Nassar** [plotly/plotly.py#3594]
Hello all!
I am facing a problem with Cloropleth when I try to use the animation_frame and geojson together.
If I run the code using the geojson on the colab, it generates the graph. However, if I try to animate it, the colab runs out of time and does not generate the graph.
Did someone note that?

I am using this code:

```
import pandas as pd
import plotly.express as px
import json
from urllib.request import urlopen

df_corona_brio_clean = pd.read_csv('https://raw.githubusercontent.com/Yuri-Nassar/public_datasets/master/coronavirus/source_brasil_io/caso_covid_brio_filtered.csv',sep=';')
df_corona_brio_clean_2 = df_corona_brio_clean.drop(columns=['is_last','city_ibge_code','confirmed_per_100k_inhabitants'])

df_agrupado_date_state = df_corona_brio_clean_2.groupby(['date','state','country'])['confirmed', 'deaths', 'estimated_population'].sum().reset_index()

url = 'https://raw.githubusercontent.com/Yuri-Nassar/public_datasets/master/geojson/br/brasil_estados.json'
response = urlopen(url)
geojson = json.loads(response.read())

# Choropleth
fig = px.choropleth(df_agrupado_date_state,
                    geojson = geojson,
                    locations='state',
                    color= df_agrupado_date_state["confirmed"],
                    hover_name='state', 
                    hover_data=["state","confirmed", "deaths"], 
                    # animation_frame= df_agrupado_date_state["date"].dt.strftime('%d-%m-%Y'),
                    scope= 'south america',
                    title='Casos ao longo do tempo',
                    color_continuous_scale= 'Reds')
fig.update_layout(autosize=False, width=1000, height=600)
fig.show()
```
It generates this figure:
![newplot](https://user-images.githubusercontent.com/5185413/153316663-21108b33-3938-44c3-8b7a-3917b30e871c.png)

However, if I remove the comment on the animation_frame line, the colab does not generate the graph and just says it runs out of execution.
![Captura de Tela (30) - Copia](https://user-images.githubusercontent.com/5185413/153317522-d2d50310-d246-4ff0-ba1f-c041a015e707.png)

Any idea about it?

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
