### ISSUE TITLE
Colorbar horizontal orientation in plotly Bar not working

### ISSUE THREAD

**Issue by Facenomore23** [plotly/plotly.py#3595]
Hello ! 

First of all thank you for the package and the updates ! I saw that you updated the possibility to have the orientation of the colorbar set as horizontal in a recent build of plotly which is a feature that interests me a lot. It is also now documented in the documentation of plotly.

Unfortunately, after trying it on my own code, I was not able to make it work. Here a simple example of what I have done : 

```
value=[1,10,20,4]
fig = go.Figure(go.Bar( x=["a","b","c","d"], y=value, orientation= "v", marker=dict(colorscale= "viridis",
colorbar=dict(title="bar", orientation="h"),color=value)))

fig.show()
```
Here the result : 
![image](https://user-images.githubusercontent.com/32964159/153433128-5dc14fb4-a175-4ac3-9b82-88d6ae2ccb61.png)

But as you can see on the graph, the colorbar is still in verctical orientation although I have set in horizontal.

The code returns me no error. I have an error only if I set orientation to something else than "v" or "h". I hope it can help.

Thank you !

**Comment by nicolaskruchten** [comment]
Can you you confirm you're using the latest version of Plotly and that you've updated any extensions you need to for your environment? Our troubleshooting page has more details :) https://plotly.com/python/troubleshooting/

**Comment by Facenomore23** [comment]
Yes, I just did the the upgrade after seeing the new feature.

I tried with version 5.6 and 5.5, on both it's not working. Python is in version 3.8.12.

Do I need to check other packages ?

**Comment by empet** [comment]
Have you installed with pip or conda? I've just upgraded to Plotly 5.6.0 , via:
```
pip install plotly --upgrade
```
and ... see the plot below!
But if  you  replaced "v" with "h" and did not swap x with y in `go.Bar` definition, it doesn't work. This is the right code:
```
value=[1,10,20,4]
fig = go.Figure(go.Bar( y=["a","b","c","d"], x=value, orientation= "h", marker=dict(colorscale= "viridis",
colorbar=dict(title="bar", orientation="h", thickness=23), color=value)))
```
![horiz-bar](https://user-images.githubusercontent.com/3627253/153847175-6b667d5f-24ff-4b1f-a409-1308eade0348.png)

**Comment by Facenomore23** [comment]
Thank you for the quick response. 

I did install with pip using ` pip install plotly --upgrade `, and all the packages are up to date.

Seeing that you were able to make it work, I tried to open jupyter in browser with localhost:8888 (anaconda) and could make it work.

In my previous attempts I was using jupyter with Visual Studio Code.

Using exactly the same jupyter notebook with localhost:8888 and VSC, this is what I get :

localhost :
![image](https://user-images.githubusercontent.com/32964159/153849799-9c492e0d-af1e-482e-88ce-fb2e3cb1bf71.png)

VCS: 
![image](https://user-images.githubusercontent.com/32964159/153849888-f2a9734a-4520-4284-b1b0-36107838d745.png)


Do you know why the outcome is different ? Python and Plotly versions are the same, I double checked it.

Thank you !

**Comment by empet** [comment]
I cannot figure out why it is not displayed correctly in VC, but I saw complaints  related to Julia plots, too.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
