### ISSUE TITLE
IPython Notebook's MathJax and Plot.ly's Mathjax conflict

### ISSUE THREAD

**Issue by FunkySayu** [plotly/plotly.py#360]
Hi.

It looks like the plot.ly's Mathjax configuration overwrite the Notebook configuration when you export this as HTML.

In rendered files, MathJax does not render the formula in dollars. In notebook with plotly, all formulas are on the left, which is quite annoying.

Is there any fast-solution to fix this ? My rendering must work on a random computer connected to internet if possible.

**Comment by FunkySayu** [comment]
Here is a little test to understand what I am talking about

![sample tests](https://cloud.githubusercontent.com/assets/5985514/11404753/d7e2287c-93a3-11e5-9d73-e44c0619831e.png)

**Comment by chriddyp** [comment]
Hey @FunkySayu - Yikes! Thanks for reporting. There might be a quick-fix that embeds some javascript in a cell after you run `init_notebook_mode` that re-runs ipython's mathjax config, but I'm not entirely sure of the details right now.

**Comment by FunkySayu** [comment]
I found a *bad* solution which is to edit the rendered file and modify the way plot.ly call mathjax in it. This suxx, but it works as a bad fix for what I am doing.

I just edit the modify the patern in `MathJax.Hub.Config(\(.*\),MathJax.Hub.Configured` by the original Notebook configuration :

    MathJax.Hub.Config({displayAlign:"center",tex2jax:{inlineMath:[["$","$"],["\\(","\\)"]],displayMath:[['$$','$$'],["\\[","\\]"]],processEscapes:true,processEnvironments:true},"HTML-CSS":{styles:{'.MathJax_Display':{"margin": 0}},linebreaks:{automatic:true}}})

This suxx, but as a hotfix for your documents, it can be cool.

**Comment by rgbkrk** [comment]
This definitely makes me wonder about better encapsulation of outputs. Right now any javascript on the page can be affected by javascript from outputs.

**Comment by jonmmease** [comment]
The offline latex/MathJax issues are going to be resolved by plotly/plotly.js#2994 and #1169. Follow along if you're interested!

**Comment by jonmmease** [comment]
Done in #1243 and will be released in version 3.4.0.  When used in the notebook, plotly.js is now configured to not alter the global MathJax configuration.
