### ISSUE TITLE
scattermapbox plot doesn't update with change in pandas dataframe in a callback

### ISSUE THREAD

**Issue by kevalshah90** [plotly/plotly.py#3631]
I am slicing a pandas dataframe based on user input. While the callback runs and I see that the dataframe is updated, the changes aren't reflected on the map. I am passing a pandas series at `lat` and `lon` and the map should be updated with the DataFrame. Below is simplified version of my code: 

```


import dash_bootstrap_components as dbc 
import dash
from dash import dcc
import pandas as pd

import plotly.express as px

df = px.data.carshare()


layout = html.Div([ 

                                  dcc.Graph(id="map"),
                                  dbc.Input(id='input'), 
                                  dbc.Button("Apply", id="show", className="mr-1", n_clicks=0)

               ]) 

# Update map graph
@app.callback(Output("map", "figure"),
                          [

                            Input("Input", "value"),
                            Input("show", "n_clicks")

                         ],
                        )
def update_map(input, btn_nclick):

    # check for triggered inputs / states
    ctx = dash.callback_context

    data = []

    if input:

       df = df[df['peak_hour'] == 11]

       data.append({

                        "type": "scattermapbox",
                        "lat": df['centroid_lat'],
                        "lon": df['centroid_lon'],
                        "mode": "markers",
                        "marker": {
                      
                                            "symbol": "circle",
                                            "size": 9,
                                            "opacity": 0.8,
                     
                            }
                     }
        )

       layout = {

                 "autosize": True,
                 "datarevision": 0,
                 "hovermode": "closest",
                 "mapbox": {

                     "accesstoken": MAPBOX_KEY,
                     "bearing": 0,
                     "center": {
                         "lat": coords[0],
                         "lon": coords[1]
                     },
                     "pitch": 0,
                     "opacity": 0.2,
                     "zoom": zoom,
                     "style": "streets",

                 },

                 "margin": {
                    "r": 0,
                    "t": 0,
                    "l": 0,
                    "b": 0,
                    "pad": 0
                }

    }

   return ({"data": data, "layout": layout})

```

Trying to wrap my head around why the map not being updated with change in pandas DataFrame.

**Comment by Coding-with-Adam** [comment]
Comment from the community member:

> I double-checked and I confirm that the example above works with dash==2.6.1 and dash==2.6.2
> It does not work, however, with dash>=2.7.0.

**Comment by vprzybylo** [comment]
I ran into this same issue with the hover updating but the scatter points in the previous location and switching from dash==2.7.0 to dash==2.8.1 solved it.

**Comment by kevalshah90** [comment]
> 
@vprzybylo good to know. what's your `plotly.js` version?

**Comment by vprzybylo** [comment]
I'm using plotly==5.11.0 in python

**Comment by archmoj** [comment]
> I ran into this same issue with the hover updating but the scatter points in the previous location and switching from dash==2.7.0 to dash==2.8.1 solved it.

Thanks @vprzybylo.
@kevalshah90 could you please try dash==2.8.1 and possibly close the issue if solved?

**Comment by kevalshah90** [comment]
It is not working for me with `dash==2.8.1` and `plotly==5.11.0 | 5.13.0`, the latest version of `plotly`. 

@vprzybylo @archmoj

**Comment by archmoj** [comment]
@kevalshah90 thanks for trying that out.
This is likely a bug in `plotly.js`.
To help us debug the issue, 
would you please make a codepen using your setup as described here: https://github.com/plotly/plotly.js/issues/6444#issuecomment-1414395024 ?

**Comment by fontempa** [comment]
Is this problem already solved? I've been having the exact same problem since last week, and been struggling for two days until I came with this post. I made the test with dash==2.7.0, then dash==2.8.1, and then dash==2.6.2 and gives me the same results: the figure actually gets updated, but the markers are not (however, you can hover over them and see the info of it)

**Comment by artdreamer** [comment]
I'm experiencing the same issue, and I hope someone can help me resolve it. Upon further investigation, I believe this may be related to the recent introduction of the cluster effect in Dash 2.7.0. In addition, I noticed another issue related to the cluster effect: enabling it for scatter plot traces makes the `restyleData` property valid.

**Comment by tomboehling** [comment]
fyi: https://github.com/plotly/plotly.js/issues/6444#issuecomment-1532715524

**Comment by Coding-with-Adam** [comment]
This bug has been fixed in the latest version of Dash (v2.10.2).

**Comment by wknjk** [comment]
In version 2.11.1 of Dash, the dataframe is not being updated when clustering is set to True. However, it works properly when clustering is set to False.

**Comment by ruaridht** [comment]
Regarding the specific issue referenced in the above comment: https://github.com/plotly/plotly.py/issues/3631#issuecomment-1408694360

The update appears to work for me in Dash v2.12.1 and not in v2.13.0. Does anyone else also experience this issue again ?
