### ISSUE TITLE
Unable to save jupyter notebook after displaying a plotly.express figure 

### ISSUE THREAD

**Issue by JovanVeljanoski** [plotly/plotly.py#3635]
Today I stumbled on a potential bug that i've not noticed before. 

After displaying any plot in the Jupyter notebook with `plotly.express` I am not longer able to save the notebook. 
In fact the whole jupyter server (this is the classical server, not jupyter lab), seems to be frozen, until i refresh the page or reset the "offending" kernel. 

Reproducible example:
```python
# cell 1
import plotly.express as px
import numpy as np
import pandas as pd

# cell 2
data = {'x': np.random.normal(scale=3, size=5000),
        'y': np.random.lognormal(0.3, size=5000)
       }
df = pd.DataFrame(data)

# cell 3
px.scatter(data_frame=df, x='x', y='y')
```

I attach the associated notebook.

### Additional information:
- plotly versions: (5.6.0. 5.4.0, 5.3.1)
- python 3.9 (environment manager conda, conda-forge channel)
- OS: Ubuntu 20.04.1 LTS
- jupyter version
```
$ jupyter --version
IPython          : 8.1.1
ipykernel        : 6.9.2
ipywidgets       : 7.6.5
jupyter_client   : 7.1.2
jupyter_core     : 4.9.2
jupyter_server   : not installed
jupyterlab       : not installed
nbclient         : 0.5.13
nbconvert        : 6.4.4
nbformat         : 5.2.0
notebook         : 6.4.9
qtconsole        : 5.2.2
traitlets        : 5.1.1
```

[test.ipynb.zip](https://github.com/plotly/plotly.py/files/8254503/test.ipynb.zip)

**Comment by JovanVeljanoski** [comment]
Update: the console repeatedly prints:

```
[W 16:16:55.976 NotebookApp] Config option `template_path` not recognized by `LenvsHTMLExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 16:16:55.981 NotebookApp] Config option `template_path` not recognized by `LenvsHTMLExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 16:16:55.990 NotebookApp] Config option `template_path` not recognized by `LenvsTocHTMLExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 16:16:55.995 NotebookApp] Config option `template_path` not recognized by `LenvsTocHTMLExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 16:16:56.011 NotebookApp] Config option `template_path` not recognized by `LenvsLatexExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[W 16:16:56.013 NotebookApp] Config option `template_path` not recognized by `LenvsLatexExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
```

When I try to save a notebook, but only if a `plotly.express` figure is present.

**Comment by prateekagrawal06** [comment]
Did the problem solve for you? I am having the same issue

**Comment by caiquanyou** [comment]
I am having the same issue ,any solution ?

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
