### ISSUE TITLE
Zoom feature in px.imshow() plotly 5.6.0 is inconsistent.

### ISSUE THREAD

**Issue by sorenwacker** [plotly/plotly.py#3636]
px.imshow(tmp.apply(log1p), height=1000)

When I run this code a heatmap is generated. When I zoom by pressing the mouse and then moving it horizontally or vertically, I expect to be able to zoom into a horizontal or vertical slice, however, a rectangular box appears and it is not possible to zoom into a vertical or horizontal slice any more. It is also not possible to zoom into a specific spot, because the rectangle aspect is constant. If this is a feature, it should be reversed to the old behaviour. 

How can I have the old (better) behaviour back? And set it systemwide as a default?

[Here](https://plotly.com/python/imshow/) I have the problem with the first plots.

![image](https://user-images.githubusercontent.com/3391614/158478609-727716e2-b73f-4000-82e2-a1c7dd8f11e5.png)

Until this one:

![image](https://user-images.githubusercontent.com/3391614/158478675-74340627-ad4e-4858-8a63-36a790b412df.png)

Here the zoom works as expected. 

What is the reason for this different behaviour?

Then this one:

![image](https://user-images.githubusercontent.com/3391614/158478859-366a6455-2855-4371-8ceb-9b0325500c53.png)

also does not work as expected.

**Comment by laurafroelich** [comment]
@sorenwacker I am running into this same issue. Were you able to figure out how to get the old behavior back?

**Comment by SolomidHero** [comment]
I have same issue. I would like to know if there some hidden parameters which created such behavior. Till now I couldn't find any
