### ISSUE TITLE
Changing subplot titles with slider

### ISSUE THREAD

**Issue by dupinv** [plotly/plotly.py#3646]
Hi, 
I am currently trying to change subplots title (independantly) with a slider with the method "update" in step. But it does not seem to work. Have you any idea of what is wrong with the code below?

Thanks

`
import plotly.graph_objects as go
import numpy as np
from plotly.offline import iplot
from plotly.subplots import make_subplots

N = 10
X= np.linspace(0.,np.pi,100)
fig = make_subplots(rows=1, cols=2, subplot_titles=("Cosinus","Sinus"))

for k in range(N):
    fig.append_trace(go.Scatter(x=X, y=np.cos(k*X), name="COS(kx)", visible=False), row=1, col=1)      
    fig.append_trace(go.Scatter(x=X, y=np.sin(k*X), name="SIN(kx)", visible=False), row=1, col=2)                

steps = []
for n in range(10):
    step = dict(method="restyle", args = [{"visible": [False,False]*N},{"annotations.text":[" "," "]}])
    step["args"][0]["visible"][2*n:2*n+2] = [True,True]
    step["args"][1]["annotations.text"] = [f"Cosinus({n}x)",f"Sinus({n}x)"]
    steps.append(step)

fig.update_layout(width=800, height=800,
                  xaxis_range = [0, np.pi],
                  yaxis_range = [-1, 1],
                  sliders=[{'active': 0, 'steps': steps, 'y': 0, 'currentvalue': {'visible': False}}])

sliders = [dict(active=0, currentvalue={"prefix": "Time:  "}, pad={"t": 50}, steps=steps)]
fig.write_html("plotly_minimal.html", auto_play=False)
`

**Comment by dupinv** [comment]
Hi,
I am currently trying to change subplots title (independantly) with a slider with the method "update" in step. But it does not seem to work. Have you any idea of what is wrong with the code below?

Thanks

``
import plotly.graph_objects as go
import numpy as np
from plotly.offline import iplot
from plotly.subplots import make_subplots

N = 10
X= np.linspace(0.,np.pi,100)
fig = make_subplots(rows=1, cols=2, subplot_titles=("Cosinus","Sinus"))

for k in range(N):
fig.append_trace(go.Scatter(x=X, y=np.cos(kX), name="COS(kx)", visible=False), row=1, col=1)
fig.append_trace(go.Scatter(x=X, y=np.sin(kX), name="SIN(kx)", visible=False), row=1, col=2)

steps = []
for n in range(10):
step = dict(method="restyle", args = [{"visible": [False,False]N},{"annotations.text":[" "," "]}])
step["args"][0]["visible"][2n:2*n+2] = [True,True]
step["args"][1]["annotations.text"] = [f"Cosinus({n}x)",f"Sinus({n}x)"]
steps.append(step)

fig.update_layout(width=800, height=800,
xaxis_range = [0, np.pi],
yaxis_range = [-1, 1],
sliders=[{'active': 0, 'steps': steps, 'y': 0, 'currentvalue': {'visible': False}}])

sliders = [dict(active=0, currentvalue={"prefix": "Time: "}, pad={"t": 50}, steps=steps)]
fig.write_html("plotly_minimal.html", auto_play=False)
``

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
