### ISSUE TITLE
Camera_eye Issue for a large dimensions in 3D models 

### ISSUE THREAD

**Issue by BijanSeif** [plotly/plotly.py#3647]
Hi everyone

Among using Plotly for creating a 3D model according various input values, I saw that if my model have large dimension in each direction, a part of the model do not be shown completely on the screen. So using camera_eye I tried to handle this problem with the below code:

```
def setcamera(fig, xrange,yrange,zrange):
    xmin=xrange[0]
    xmax=xrange[1]
    
    ymin=yrange[0]
    ymax=yrange[1]
    
    zmin=zrange[0]
    zmax=zrange[1]
    
    #Some modification for 2D and 1D models
    if xmax-xmin==0:
        xmax=xmin+max((zmax-zmin),(ymax-ymin))
    if ymax-ymin==0:
        ymax=ymin+max((zmax-zmin),(xmax-xmin))
    if zmax-zmin==0:
        zmax=zmin+max((ymax-ymin),(xmax-xmin))
    
    eyez=1 if max((zmax-zmin)/(xmax-xmin),(zmax-zmin)/(ymax-ymin)) < 1 else 1+(max((zmax-zmin)/(xmax-xmin),(zmax-zmin)/(ymax-ymin))-1)*0.5
    eyex=1.25*eyez
    eyey=1.25*eyez
    eyex=eyex * (1+((ymax-ymin)/(xmax-xmin)-1)*0.7) if ((xmax-xmin)/(ymax-ymin))<1 else eyex

    fig.update_layout(scene_camera_eye=dict(x=eyex, y=eyey, z=eyez),)
```
in above code xmax,xmin,zmax,zmin,ymax,ymin are the model boundary values.
If model has large dimension in Z, the camera position will be set properly with above code and whole model can be seen perfect. 
If model has large dimension in Y, the camera position will be set properly with above code and whole model can be seen perfect.
**But unfortunately If model has large dimension in X, there is no specific rule and program automatically change the camera position to show whole model. It shows the whole model But the position of camera is not perfect and the rule is not clear and maybe there is a bug. because program set the camera position for large X dimension values but doesn't do it nor other directions.**

Please let me know if I'm correct or not? Please let me know if there is another way for this purpose? 

Thanks

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
