### ISSUE TITLE
why no offline.iplot_mpl? 

### ISSUE THREAD

**Issue by arsenovic** [plotly/plotly.py#365]
i just saw the new open-sourced plotly.js, and associate offline mode. i love this. 

at first use i wondered why there was no  `offline.iplot_mpl()` method?
https://github.com/plotly/plotly.py/blob/master/plotly/offline/offline.py#L60

could `offline.iplot` be changed to accept mpl figures? or if not, should `offline.iplot_mpl`  be made with something like?

    from .tools import mpl_to_plotly
    def iplot_mpl(*args,**kw):
        iplot(mpl_to_plotly(*args,**kw))

**Comment by jackparmer** [comment]
Hey @arsenovic , I think we just haven't gotten around to it. It would be awesome to have offline mpl support, feel free to PR your solution if you have time.

**Comment by arsenovic** [comment]
https://github.com/plotly/plotly.py/pull/366

**Comment by cldougl** [comment]
https://github.com/plotly/plotly.py/blob/master/CHANGELOG.md#added
