### ISSUE TITLE
Question: How is the size of the different rectangles calculated in a plotly treemap?

### ISSUE THREAD

**Issue by AlexanderBelfort** [plotly/plotly.py#3664]
Given 50 words and their frequency, I build a tree map using plotly. It creates 50 different rectangles where the most dominant word is the biggest rectangle and so on.

So how is this size relative to the frequency calculated? Are we looking at percentage change / logged difference between the mentions? What is the formula?

**Comment by nicolaskruchten** [comment]
The area of each rectangle (height*width) is proportional to the `values` argument, so if you're passing in word frequencies, then the area will be proportional to the frequency. So if you have one word with a frequency of twice the other, the corresponding rectangle for the first one will be twice as big as the rectangle for the second one.

**Comment by AlexanderBelfort** [comment]
Makes sense. Thank you so much!
