### ISSUE TITLE
Different `scope` or `locationmode` values

### ISSUE THREAD

**Issue by shriphani** [plotly/plotly.py#367]
Hi I've poked around the code a bit. From what I see topojson seems to be loaded but only 3 locationmodes and a handful of scopes are supported. Are there any plans to support more of these (say something like 'China-states')?

:heart: Shriphani

**Comment by Bu3a3a** [comment]
Seems like it hasn't changed in two years (or I just haven't found any references on it). Can you provide more countries with regions or describe a way how someone can write and use with plotly country-like objects splitted in regions? It would be really cool.

**Comment by cldougl** [comment]
Hi there,
- Please note that changes to `locationmode` would be made in our core graphing library: [plotly.js](https://github.com/plotly/plotly.js), so you could open an issue there similar to: https://github.com/plotly/plotly.js/issues/1354.
- As for writing it yourself, you can checkout or county example here: https://plot.ly/python/county-level-choropleth/
You can use our [`scattermapbox`](https://plot.ly/python/reference/#scattermapbox) trace with geojson data of the regions that you would like to draw.
