### ISSUE TITLE
Importing plotly express may fail over its fiddling of the globals object

### ISSUE THREAD

**Issue by matanster** [plotly/plotly.py#3670]
As detailed [here on StackOverflow](https://stackoverflow.com/questions/71752038/plotly-crashing-when-some-entries-on-the-globals-object-are-unexpected?noredirect=1#comment126866612_71752038) there is an interoperability corner case when using pytest, where importing plotly express may [fail over this line of code](https://github.com/plotly/plotly.py/blob/03979d105c65dda3df3a155322eaff18f203b03f/packages/python/plotly/_plotly_utils/colors/colorbrewer.py#L465).

**Comment by matanster** [comment]
I wonder if other people were able to import plotly express in pytest test code at all.

**Comment by nicolaskruchten** [comment]
Yeah, this `globals` thing was pretty lazy. It should be fairly mechanical to fix if someone wants to open a PR though! Basically we just add the `_r`-suffixed scale after each scale.

**Comment by nicolaskruchten** [comment]
That said, yes, we use `pytest` to test Plotly Express, both locally and in CI.

**Comment by nicolaskruchten** [comment]
OK so https://github.com/plotly/plotly.py/pull/3713 should resolve whatever issue you're hitting that I'm not. Even if I can't replicate it, it's good to get rid of this kind of code smell :)

**Comment by matanster** [comment]
Thank you so much for solving this, pytest interoperability is straight now.
