### ISSUE TITLE
[Improve] It's definitely a bad design that `go.Surface` doesn't support directly using `DataFrames` as parameters.

### ISSUE THREAD

**Issue by GF-Huang** [plotly/plotly.py#3679]
**It's definitely a bad design that `go.Surface` doesn't support directly using `DataFrames` as parameters.** 

Imagine you swapped `x` and `y`, for example: `x=df.index, y=df.columns, z=df.values`. 

**You won't notice that your x-axis data isn't fully displayed if you don't scrutinize it carefully.** That's because you reversed `x` and `y`, which gives you the wrong result! 

### In fact, you should do `x=df.columns, y=df.index` rather than `x=df.index, y=df.columns`!!!

**Comment by nicolaskruchten** [comment]
Please try to phrase your issues in a more constructive way than "this is a bad design".
