### ISSUE TITLE
Widgets in offline mode

### ISSUE THREAD

**Issue by aggFTW** [plotly/plotly.py#368]
Hi, is it possible to create a plotly widget in offline mode? I am basically trying to get something like, say: `iplot([{"x": [1, 2, 3], "y": [3, 1, 6]}])` to display in an IPython widget. I see that plotly has support for widgets via the [GraphWidget](https://github.com/plotly/plotly.py/blob/390c09d18d30706a5eb42390beeea103a8837f3d/plotly/widgets/graph_widget.py) and I was wondering if I can basically nest a plotly widget in one of my widgets. 

I learned about this from [this post](http://moderndata.plot.ly/widgets-in-ipython-notebook-and-plotly/) by @chriddyp. The example notebooks in the post are not reachable and I presume they won't be using offline graphs.

Any help would be greatly appreciated! Thanks :)

**Comment by aggFTW** [comment]
Ping @ellisonbg

**Comment by ellisonbg** [comment]
Can you clarify what you mean by "offline" mode? To get plotly to dispaly in an IPython widget you can use the OutputWidget in ipywidgets. Something like this:

```python
from ipywidgets import OutputWidget
ow = OutputWidget()
with ow:
    iplot(...)
```

The `ow` instance can then be nested inside other widgets.

**Comment by aggFTW** [comment]
Thanks @ellisonbg!

I was trying that, executing this:

```
from ipywidgets import Output
ow = Output()
with ow:
    iplot([{"x": [1, 2, 3], "y": [3, 1, 6]}])
ow
```

but there's nothing showing up:

![exampleoutput](https://cloud.githubusercontent.com/assets/654204/11636861/2462e316-9cd3-11e5-97bd-be5d2351e7cc.PNG)

I thought maybe `iplot` didn't work with Output, so I looked into plotly's widget story and discovered that they have a widget that takes in an URL. However, I couldn't find a way to make their widget work in plotly's offline mode (iplot is part of their offline mode module). Hence, my question. 

Do you get the same result with the code I posted?

**Comment by ellisonbg** [comment]
Oh, sorry I made a mistake, try to first diplay the widget in one cell and
then use with to do the plot in the second. The main point is that the
output widget has to be displayed when the plot call is made.

On Mon, Dec 7, 2015 at 11:12 AM, Alejandro Guerrero Gonzalez <
notifications@github.com> wrote:

> Thanks @ellisonbg <https://github.com/ellisonbg>!
>
> I was trying that, executing this:
>
> from ipywidgets import Output
> ow = Output()
> with ow:
>     iplot([{"x": [1, 2, 3], "y": [3, 1, 6]}])
> ow
>
> but there's nothing showing up:
>
> [image: exampleoutput]
> <https://cloud.githubusercontent.com/assets/654204/11636861/2462e316-9cd3-11e5-97bd-be5d2351e7cc.PNG>
>
> I thought maybe iplot didn't work with Output, so I looked into plotly's
> widget story and discovered that they have a widget that takes in an URL.
> However, I couldn't find a way to make their widget work in plotly's
> offline mode (iplot is part of their offline mode module). Hence, my
> question.
>
> Do you get the same result with the code I posted?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/plotly/plotly.py/issues/368#issuecomment-162628162>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by aggFTW** [comment]
Ah, got it! That worked :)

However, how would I then programmatically display graphs within a widget? Say I want to create a library to display a graph in a widget that has just been created. It seems like with this prerequisite, I wouldn't be able to have the widget displayed with a graph from the start.

**Comment by aggFTW** [comment]
I just noticed that in the source, there's a call to the display() method. Let me try that!

**Comment by ellisonbg** [comment]
Great, yes, you would just call display()

On Mon, Dec 7, 2015 at 11:35 AM, Alejandro Guerrero Gonzalez <
notifications@github.com> wrote:

> Closed #368 <https://github.com/plotly/plotly.py/issues/368>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/plotly/plotly.py/issues/368#event-484795977>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by avishapiro** [comment]
I know this is closed but, @aggFTW , could you display the full code "that worked"? Thanks.

**Comment by aggFTW** [comment]
What do you want the code to do @avishapiro? If you just want to display the output and then draw on it, you'd do what's posted above:

```
        import ipywidgets as widgets
        from IPython.display import display
        out = widgets.Output()
        display(out)

        with out:
            print('prints to output widget')"""
```

where they key thing to know is to call `display(out)` before `with out:`

**Comment by avishapiro** [comment]
@aggFTW, I was hoping to see a plot inside a widget with your code:

```
from ipywidgets import Output
from IPython.display import display
import plotly.plotly as py

ow = Output()
display(ow)

with ow:
    print('prints to output widget')
    py.iplot([{"x": [1, 2, 3], "y": [3, 1, 6]}])
```

All I see is the line `prints to output widget` but no plot. If I run the last line of code above alone, I do see the plotly line graph. I wonder if I have a version issue or if this is a Windows problem.

![image](https://cloud.githubusercontent.com/assets/13265109/11921466/4a7eadee-a757-11e5-83da-4d50a463a3cb.png)

**Comment by aggFTW** [comment]
This works for me (notice I'm doing offline mode because I don't have a plotly account):

```
from ipywidgets import Output
from IPython.display import display
from plotly.offline import init_notebook_mode, iplot

init_notebook_mode()

ow = Output()
display(ow)

with ow:
    print('prints to output widget')
    iplot([{"x": [1, 2, 3], "y": [3, 1, 6]}])
```

When executing:

```
import IPython
print(IPython.__name__,IPython.__version__)
import ipywidgets
print(ipywidgets.__name__,ipywidgets.__version__)
import plotly
print(plotly.__name__,plotly.__version__)
import sys
print(sys.version)
```

Result is:
```
('IPython', '4.0.0')
('ipywidgets', '4.2.0.dev')
('plotly', '1.9.0')
2.7.10 |Anaconda 2.3.0 (x86_64)| (default, May 28 2015, 17:04:42) 
[GCC 4.2.1 (Apple Inc. build 5577)]
```

I've tried this on my Windows computer and it works too.

**Comment by avishapiro** [comment]
Thanks @aggFTW . I forgot to switch my code back to offline mode. I confused what I aliased as `iplot` with what you did. My offline code now works. I'll have to work on the online version. Since IPython has changed a lot over the year, many online examples no longer work, especially involving widgets.
