### ISSUE TITLE
Exporting Static Image

### ISSUE THREAD

**Issue by yesdeepakmittal** [plotly/plotly.py#3682]
I am trying to save all of my graphs in the form of .png. I installed both the `orca` & `Kaleido` packages. Even after running my program for more than 15 minutes, none of these engines saved my graphs. Kindly suggest a faster approach to export the graphs in .png form. Thanks.

**Comment by georgehua** [comment]
Hello, I'm facing the same situation, how did you solve the problem? Many thanks!

**Comment by yesdeepakmittal** [comment]
Hi @georgehua , I needed this solution while I was designing my Streamlit app. I returned the image as an object itself. PFB the links for the same

- https://github.com/yesdeepakmittal/COVID19-Pandemic-in-India/blob/master/analysis.py#L51
- https://github.com/yesdeepakmittal/COVID19-Pandemic-in-India/blob/master/app.py#L48

**Comment by georgehua** [comment]
Thank you so much @yesdeepakmittal, really appreciate it!!!
