### ISSUE TITLE
FigureWidget: resizing can only expand but cannot shrink

### ISSUE THREAD

**Issue by martinRenou** [plotly/plotly.py#3689]
When executing the following in a JupyterLab Notebook, increasing the window size results in the plot correctly expanding, but reducing the size of the window does not shrink the plot correctly (see following GIF):

```python
import ipywidgets as widgets

import plotly.graph_objects as go
import plotly.express as px


fig = px.line([1, 2, 3, 4, 6], template='plotly_dark')

fw = go.FigureWidget(fig)

fw
```

![resizing](https://user-images.githubusercontent.com/21197331/164736806-59d97ac4-4abf-436b-809d-ac11e21804fb.gif)

**Comment by Alexboiboi** [comment]
@martinRenou @nicolaskruchten 
When building dashbords with resizable windows and FigureWidgets this is getting quite annoying. Is there any workaround ?

**Comment by martinRenou** [comment]
I never took the time to look deeper into it unfortunately. And I cannot really think of a workaround.

**Comment by Alexboiboi** [comment]
> I never took the time to look deeper into it unfortunately. And I cannot really think of a workaround.

Hi @martinRenou, this hack (https://github.com/plotly/plotly.py/issues/2062) is kinda working

**Comment by Alexboiboi** [comment]
Hi @martinRenou,

looks like the latest release (5.12) solves this issue. 

Worth looking at  [bqplot/bqplot#1531] to adress a similiar issue when the FigureWidget is inside another container.

**Comment by nicolaskruchten** [comment]
Ok great! Let's open a separate issue for any lingering problems plz. No one on the Plotly team is really actively working on the Widget side of things so PRs are very welcome :)
