### ISSUE TITLE
`Mathjax.Hub.config` used for plotly 5.7.0

### ISSUE THREAD

**Issue by AakashGfude** [plotly/plotly.py#3696]
Could not find a duplicate of this issue anywhere so, not sure if anyone else had an issue like this, but when using `plotly` in a sphinx project and creating HTML pages, I get the following js code included in my HTML page:

```
<div class="output text_html">        <script type="text/javascript">
        window.PlotlyConfig = {MathJaxConfig: 'local'};
        if (window.MathJax) {MathJax.Hub.Config({SVG: {font: "STIX-Web"}});}
        if (typeof require !== 'undefined') {
        require.undef("plotly");
        define('plotly', function(require, exports, module) {
            /**
* plotly.js v2.11.1
.....
```

When I have a math block in the same page as a plotly graph, then `window.MathJax` is defined and `MathJax.Hub.Config` gets called. Which throws an error as I am using mathjax v3, which is supported by v5.7.0.

The line `MathJax.Hub.Config({SVG: {font: "STIX-Web"}})` I see written in a bunch of files like:
https://github.com/plotly/plotly.py/blob/master/packages/python/plotly/plotly/io/_base_renderers.py#L240

Is it a legit issue?

**Comment by archmoj** [comment]
You must check the version of MathJax to be v2 e.g. here
```js
if (window.MathJax && (window.MathJax.version || '').split('.')[0] === '2') {MathJax.Hub.Config({SVG: {font: "STIX-Web"}});}
```

**Comment by alexcjohnson** [comment]
@archmoj let's add this to the queue for after the coming plotly.js release, see if you can figure out the equivalent command to switch to when we detect v3.

@AakashGfude thanks for the report!
