### ISSUE TITLE
My plotly bar does not show in my dash codes

### ISSUE THREAD

**Issue by AnnieLei** [plotly/plotly.py#3700]
Hi,

I try to make a bar chart using dash and plotly, but the px.bar does not show. Any suggestion to fix it?
![image](https://user-images.githubusercontent.com/55474074/166125058-695b67c7-3346-46c0-81c6-b934bf266797.png)

`import pandas as pd

import dash
import dash_core_components as dcc
import dash_html_components as html

from dash.dependencies import Input, Output
import plotly.express as px
import plotly.io as  pio

def get_data_from_excle():
    #df=pd.read_excel('supermarkt_sales1.xlsx',header=0,sheet_name='Sales')
    df=pd.read_csv('sales.csv')
    df["hour"]=df["Time"].str.split(":")
    #df["hour"]=df["Time"].str.split(":", expand=True)
    df["hour"]=df["hour"].str[0]

    #df["hour"]=pd.to_datetime(df["Time"],format="%H:%M:").dt.hour
    return df

df=get_data_from_excle()

#df_selection=df.loc[df['City']=='Yangon'].loc[df['Customer_type']=='Normal'].loc[df['Gender']=='Male']
#sales_by_product_line=(
#        df_selection.groupby(by=["Product line"]).sum()[["Total"]].sort_values(by="Total")
#        )

app = dash.Dash(__name__, prevent_initial_callbacks=True) # this was introduced in Dash version 1.12.0

app.layout = html.Div([
    html.Div([
    dcc.Dropdown(id='dropdown_city', options=[
        {'label': i, 'value': i} for i in df.City.unique()
    ], multi=True, placeholder='Filter by City...'),
    dcc.Dropdown(id='dropdown_customer_type', options=[
        {'label': i, 'value': i} for i in df.Customer_type.unique()
    ], multi=True, placeholder='Filter by Customer_type...'),
    dcc.Dropdown(id='dropdown_Gender', options=[
        {'label': i, 'value': i} for i in df.Gender.unique()
    ], multi=True, placeholder='Filter by Gender...'),
    dcc.Graph(id='plot-main')
    ])
    ])

@app.callback(
    Output('plot-main', 'figure'),
    [Input('dropdown_city', 'value'), 
    Input('dropdown_customer_type', 'value'),
    Input('dropdown_Gender', 'value')]
    )

def update_plot(city_value, customer_value, gender_value):
    df_selection=df.loc[df['City']==city_value].loc[df['Customer_type']==customer_value].loc[df['Gender']==gender_value]

    # print(dff[[x_axis,y_axis]][:1])
    sales_by_product_line=(
        df_selection.groupby(by=["Product line"]).sum()[["Total"]].sort_values(by="Total")
        )

    barchart=px.bar(
            sales_by_product_line,
            x="Total",
            y=sales_by_product_line.index,
            orientation="h",
            title="<b>Sales by Product Line </b>",
            color_discrete_sequence=["#008388"]*len(sales_by_product_line),
            template="plotly_white",
            )
    barchart.show()
    return (barchart)

            
if __name__ == '__main__':
    app.run_server(debug=False)`

**Comment by MuhammadArifinHakim** [comment]
**try change** df_selection.groupby(by=["Product line"]).sum()[["Total"]].sort_values(by="Total")
**to**  df_selection.groupby(by=["Product line"])[["Total"]].sum().sort_values(by="Total")

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
