### ISSUE TITLE
name 'NumberValidator' is not defined

### ISSUE THREAD

**Issue by Ascrypto** [plotly/plotly.py#3701]
Hi, 

I keep getting this error "NameError: name 'NumberValidator' is not defined," preceded by a blank figure when using make_subplots().  The code was working just fine before. 
Plotly version:  5.6.0. 

Thank you.

**Comment by Ascrypto** [comment]
Hi, I just stopped using make_subplots(), and it worked just fine with the other functions. I do not know exactly what the problem is.

**Comment by Cookie-YY** [comment]
Maybe I have located the problem.  There is a `eval()` in the source code `_plotly_utils/basevalidators.py`
`validator_class = eval(validator_classname)`

This is indeed a dangerous line of code. `importlib` seems to be a better solution.  Maybe I should simply stop using make_subplots(), too. Thanks!
