### ISSUE TITLE
Custom values for `griddash`, e.g. '10px' don't work (plotly.js 2.12.0)

### ISSUE THREAD

**Issue by LiamConnors** [plotly/plotly.py#3710]
Custom values for `griddash`, e.g. '10px' don't work (plotly.js 2.12.0)

Example:
```
import plotly.express as px
df = px.data.iris()

fig = px.scatter(df, x="sepal_width", y="sepal_length", facet_col="species")
fig.update_xaxes(tickcolor="black", tickwidth=2, ticklen=10, ticklabelmode="period", griddash='10px')
fig.update_yaxes(showgrid=True, gridwidth=1, gridcolor='LightPink')

fig.show()
```
Gives the following error
```
ValueError: 
    Invalid value of type 'builtins.str' received for the 'griddash' property of layout.xaxis
        Received value: '10px'

    The 'griddash' property is a string and must be specified as:
      - One of the following strings:
            ['solid', 'dot', 'dash', 'longdash', 'dashdot',
            'longdashdot']
      - A number that will be converted to a string
```
@archmoj, should it work like this? That throws an error
```fig.update_xaxes(showgrid=True, gridwidth=1, gridcolor='LightPink', griddash='10px')```

_Originally posted by @LiamConnors in https://github.com/plotly/plotly.py/pull/3693#discussion_r865489690_

**Comment by nicolaskruchten** [comment]
It looks like our Python-side validation code for 'dash' strings is too restrictive.

**Comment by archmoj** [comment]
Here is the current plotly.py validator: https://github.com/plotly/plotly.py/blob/d5b341cf73b3b24999237df1f6b996703b237e9a/packages/python/plotly/_plotly_utils/basevalidators.py#L2245-L2324

**Comment by nicolaskruchten** [comment]
Yeah I think that the schema is maybe not quite right in these cases?

Plotly.py is totally happy with the `line.dash` attribute in scatter traces though:

<img width="1393" alt="image" src="https://user-images.githubusercontent.com/203523/167436403-5c38d2e5-3f81-4927-9934-7a91c9e6f98d.png">

**Comment by nicolaskruchten** [comment]
so what's different between `scatter.line.dash` and the new `griddash` in the schema?

**Comment by nicolaskruchten** [comment]
> Could you simply set it to 10px?

yes that works also

**Comment by archmoj** [comment]
What happens if we do not validate by simply dropping `DashValidator` function?

**Comment by archmoj** [comment]
@alexcjohnson your thoughts?

**Comment by nicolaskruchten** [comment]
Well, the whole purpose of `graph_objects` is to add validators, so just dropping them seems like the wrong way to go :)

**Comment by nicolaskruchten** [comment]
The problem isn't the `DashValidator` actually, it's that for attributes like `griddash`, the validator being used is the `StringValidator`, because it looks like the codegen isn't able to figure out it needs to use the `DashValidator`. The `DashValidator` *does* admit numbers and the `StringValidator` does not.

Here is [the code for the `scatter.line.dash` validator](https://github.com/plotly/plotly.py/blob/master/packages/python/plotly/plotly/validators/scatter/line/_dash.py) and here is [the code for the `layout.xaxis.gridddash` validator](https://github.com/plotly/plotly.py/blob/master/packages/python/plotly/plotly/validators/layout/xaxis/_griddash.py).

**Comment by nicolaskruchten** [comment]
Oh, hah, here is why: https://github.com/plotly/plotly.py/blob/master/packages/python/plotly/codegen/utils.py#L184-L201

**Comment by archmoj** [comment]
> Oh, hah, here is why: https://github.com/plotly/plotly.py/blob/master/packages/python/plotly/codegen/utils.py#L184-L201

Can't we instead say every attribute that ends with `dash` should be checked by the dash validator?

**Comment by nicolaskruchten** [comment]
Let's fix this in the next patch release. I'm almost done QA'ing 5.8.0 already.

**Comment by alexcjohnson** [comment]
> The `DashValidator` does admit numbers and the `StringValidator` does not.

FWIW `dash` attributes are the only ones with `valType: 'string'` as well as enumerated `values`:

![Screen Shot 2022-05-09 at 11 57 17](https://user-images.githubusercontent.com/2678795/167449517-5ead1973-77e9-42d7-9d1a-fdd306a7d093.png)

It's certainly nice the way `DashValidator` admits both our enumerated strings and the css length list pattern. But it's a pain to need to explicitly list where to use it. Can't we just delegate to it whenever `valType: 'string'` and a `values` list appear together?

**Comment by alexcjohnson** [comment]
> Maybe string and "has dash and dotted in values" will be more robust?

I like that - hard to think what other case we'd want arbitrary strings plus enumerated values in the future, but if there is one it most likely wouldn't include dash and dot :)

**Comment by nicolaskruchten** [comment]
OK so I went with the "ends in `dash` and is a string" approach instead as it was easier and didn't seem to get anything wrong.
