### ISSUE TITLE
Plotly.express style won't get updated based on the template used

### ISSUE THREAD

**Issue by xin-yang4055** [plotly/plotly.py#3720]
Step1: create plotly.express bar chart with template set as 'none'
The bar in figure will have color `#1F77B4`, which is the default
```python
import plotly.io as pio
pio.templates.default = 'none'

import plotly.express as px
data_canada = px.data.gapminder().query("country == 'Canada'")
ex_fig = px.bar(data_canada, x='year', y='pop')
ex_fig.show()
```

Step2: register test template
```python 
import plotly.graph_objects as go
import plotly.io as pio

test_plotly_template = go.layout.Template(
    layout=go.Layout(
        colorway=['#1aaeba']
))

pio.templates['test'] = test_plotly_template
```

Step3: update the template using update_layout()
the bar color stays the same as `#1F77B4`, instead of the color specified in the template
```python
ex_fig.update_layout(template='test')
```

This behavior is different from what's implemented in `go.bar`. Steps to implement the same using `go.bar`
Step1: create bar chart with template set as 'none'
The bar in figure will have color `#1F77B4`, which is the default
```python
import plotly.graph_objects as go
import pandas as pd

df = pd.DataFrame({
  "Fruit": ["Apples", "Oranges", "Bananas", "Apples", "Oranges", "Bananas"],
  "Number Eaten": [2, 1, 3, 1, 3, 2],
})

go_fig = go.Figure(go.Bar(x=group["Fruit"], y=group["Number Eaten"], name=contestant))
```

Step2: register test template
```python 
import plotly.graph_objects as go
import plotly.io as pio

test_plotly_template = go.layout.Template(
    layout=go.Layout(
        colorway=['#1aaeba']
))

pio.templates['test'] = test_plotly_template
```

Step3: update the template using update_layout()
the bar color will be updated to be `#1aaeba`
```python
go_fig.update_layout(template='test')
```

**Comment by nicolaskruchten** [comment]
This is the intended behaviour. Plotly Express takes into account any template defined *before* a function is called but not after.

**Comment by xin-yang4055** [comment]
but when I set the template to None, would that mean there shouldn't be no default style been set? and I'm free to update it after the visualization?

**Comment by nicolaskruchten** [comment]
No, `none` is still a defined template: Plotly Express must have colours to assign.

**Comment by xin-yang4055** [comment]
and the behavior is inconsistent between plotly.express and go.bar?

**Comment by xin-yang4055** [comment]
and there is no way to change the color after the visualization is done except I explicitly assign it right?

**Comment by xin-yang4055** [comment]
and the only way to use the colors in the test template is to set it as the template before the visualization right?

**Comment by nicolaskruchten** [comment]
The behaviour is the same between the two: if you assign a color in go traces then it no longer responds to template changes. PX simply always assigns a color.

And yes, after PX generates a figure, the only way to change trace colors is explicitly by mutating the figure trace by trace.

**Comment by xin-yang4055** [comment]
right, but in my example, there is no color assigned in the `go` trace, and that's why later I can use the update_layout() function to use my template which displays the color in the template

**Comment by nicolaskruchten** [comment]
Yes. But like I said, PX always assigns a color. You cannot ask it not to :)

**Comment by xin-yang4055** [comment]
yeah. so the inconsistency here is that:
when the template sets to 'none'
go.bar -> assign no color in the trace data
PX -> assign a default color 
which caused the different behavior

**Comment by nicolaskruchten** [comment]
Sure, you can call it an inconsistency if you like. As I said thiugh, it is by design: Plotly Express must and does set the color values explicitly in the underlying GO traces, otherwise it would not be able to generate eg faceted plots.

**Comment by xin-yang4055** [comment]
okay, got it. I think for now I can set the template prior to calling the functions. Thanks for the help!
