### ISSUE TITLE
write_html destroys histogram

### ISSUE THREAD

**Issue by leonhardklein** [plotly/plotly.py#3723]
Hi,

 in this short example the shown plot is fine, whereas the write_html creates a "scatter" plot instead of the histogram:

```
  import plotly.graph_objects as go
  fig = go.Figure()
  fig.add_trace(go.Histogram(x=[0,1,2,3,3,3,4]))
  fig.show()
  fig.write_html('test.html', include_plotlyjs='plotly-basic-2.11.1.min.js')
```

plotly: 5.7.0
python: 3.9.5

Thanks for creating such great software!

**Comment by nicolaskruchten** [comment]
This is because the basic bundle doesn't include support for histograms :)

**Comment by leonhardklein** [comment]
Thanks! That solves it!
 
(Hint for documentation: I couldn't find the list of what is contained in which .js version)

**Comment by nicolaskruchten** [comment]
Sorry about that! The Plotly.js prebuilt bundles are documented here https://github.com/plotly/plotly.js/blob/master/dist/README.md
