### ISSUE TITLE
plotly express animation frame.append method depreciated

### ISSUE THREAD

**Issue by djmcnay** [plotly/plotly.py#3725]
Hi, 

I don't think this has been raised elsewhere (yet) but seems plotly express animations uses frame.append which is throwing the warning:

```
FutureWarning:

The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
```

Assuming it is relatively trivial to replace,
Thanks,
David

**Comment by nicolaskruchten** [comment]
We've just fixed a bunch of deprecation warnings in version 5.8.0 which was released last night... Are you using this version? If not, can you try upgrading to confirm that this warning goes away?

**Comment by djmcnay** [comment]
Brilliant, thanks Nicholas. Perfectly timed release;  I've just upgraded from 5.7 and that seems to have solved the warnings on animations for me.

**Comment by mbuchan-work** [comment]
Oddly I'm seeing the same FutureWarning again using version 5.12.0 with reference to "...express/_core.py:271"
