### ISSUE TITLE
qgrid - plotly conflict

### ISSUE THREAD

**Issue by djchou** [plotly/plotly.py#373]
I'm using plotly offline in a jupyter notebook. I'm coming across an error that i can't seem to debug.

Here is my code:

import qgrid
import Quandl
import plotly
from plotly.offline import download_plotlyjs, init_notebook_mode, iplot

aapl = Quandl.get('yahoo/aapl')
qgrid.nbinstall(overwrite=True)

#works ok
qgrid.show_grid(aapl)

init_notebook_mode()
#no longer works ok
qgrid.show_grid(aapl)

The error message is
"
Javascript error adding output!
TypeError: Cannot read property 's' of undefined
See your browser Javascript console for more details.
"

**Comment by akansal1** [comment]
I am getting javascript type error : require not a function, for custom widget, on import and initialization of plotly in offline mode

**Comment by akansal1** [comment]
I do not understand JS but I think following lines of code in offline.py causing errors:

    display(HTML('<script type="text/javascript">' +
                 # ipython's includes `require` as a global, which
                 # conflicts with plotly.js. so, unrequire it.
                 'require=requirejs=define=undefined;' +
                 '</script>' +
                 '<script type="text/javascript">' +
                 get_plotlyjs() +
                 '</script>'))

**Comment by aggFTW** [comment]
I saw this too, same error. Ideas?

**Comment by djchou** [comment]
One displays tables well, the other displays graphs well.  It makes sense to have both in the same notebook

**Comment by etpinard** [comment]
See https://github.com/plotly/plotly.js/issues/90 for more info.

**Comment by aggFTW** [comment]
Agreed @djchou. I was just wondering if you were building a UI/library that used both or just your own personal notebook :)

We are building a visualization widget for Ipython at https://github.com/jupyter-incubator/sparkmagic/tree/master/remotespark/datawidgets in case you want to take a look!

The intention is to decouple it from the sparkmagic project and put the widget into its own repo :+1:

**Comment by etpinard** [comment]
This issue would be perfect for a community contributor.

In this [block](https://github.com/plotly/plotly.py/blob/master/plotly/offline/offline.py#L64-L71), we need to remove the `require=requirejs=define=undefined;` hack and import plotly.js using the Require.js `require` as done in this plotly-notebook-js [block](https://github.com/plotly/plotly-notebook-js/blob/bc209899e9ca97f0bfe59d288007810889ec1171/src/index.js#L121-L123).
