### ISSUE TITLE
Subplot Sankey Charts Show Random X/Y axes if X/Y-coordinates are referenced in an Annotation

### ISSUE THREAD

**Issue by xinnyuann** [plotly/plotly.py#3738]
Thank you so much as always for the best vizz package! We love Sankey chart, and multiple sankey charts. 

It seems that Plotly doesn't support adding grouped column header yet (for example: https://stackoverflow.com/questions/67540925/plotly-how-to-write-a-text-over-my-sankey-diagram-columns), so I used annotation as suggested. But once annotations are added with reference to X/Y coordinates, X/Y axes randomly show up in some of the subplots (if not all of them, sometimes), even after I updated the overall figure layout with code:
`fig.update_layout(
        xaxis={
        'showgrid': False, # thin lines in the background
        'zeroline': False, # thick line at x=0
        'visible': False,  # numbers below
        'showticklabels': False
        },
        yaxis={
        'showgrid': False, # thin lines in the background
        'zeroline': False, # thick line at x=0
        'visible': False,  # numbers below
        'showticklabels':False
        })` 

![image](https://user-images.githubusercontent.com/18304008/169305931-6e4b6278-88e6-4905-8cb5-c9a5c5914efd.png)

Not sure if this is a bug or I didn't use the methods correctly. Does anyone have the same issue or some work-around? Thank you in advance. 

I'm using: 
**plotly==5.6.0
python==3.8.12**

**Comment by alexcjohnson** [comment]
I posted a response to the [SO post](https://stackoverflow.com/questions/67540925/plotly-how-to-write-a-text-over-my-sankey-diagram-columns/72355193#72355193) showing a couple of better ways to do this. You might also find good answers to questions like this on https://community.plotly.com/ :)
