### ISSUE TITLE
Offline mode only displays 'Drawing . . .'

### ISSUE THREAD

**Issue by icam0** [plotly/plotly.py#374]
I just installed plot.ly on my canopy distribution using python 2.7 . I'm trying to run the demo code for offline graphs but it only displays 'Drawing ...' . I tried to run the standard demo offline plotly code:

    import plotly
    print plotly.__version__            # version 1.9.x required
    plotly.offline.init_notebook_mode() # run at the start of every notebook
    plotly.offline.iplot({
        "data": [{
            "x": [1, 2, 3],
            "y": [4, 2, 5]
        }],
        "layout": {
            "title": "hello world"
        }
    })

This is what my output looks like:

<img width="546" alt="schermafbeelding 2015-12-15 om 13 38 07" src="https://cloud.githubusercontent.com/assets/821612/11810787/26d43a5a-a331-11e5-914f-64eb3d8ce168.png">

**Comment by icam0** [comment]
I did not read it was only possible to get this working inside jupyter notebooks. My bad, you can close this.

**Comment by cldougl** [comment]
Hey @icam0 *now* it is possible to get this working outside of jupyter notebooks.
We've updated the doc here: https://plot.ly/python/offline/
with a simple example:
```
from plotly.offline import plot
from plotly.graph_objs import Scatter

plot([Scatter(x=[1, 2, 3], y=[3, 1, 6])])
```
