### ISSUE TITLE
Orientation of colorbar not working in 5.8.0

### ISSUE THREAD

**Issue by jdtrebbien** [plotly/plotly.py#3741]
I dont if its best practice, but since I have already submitted a stackoverflow question for this I will just link it [here](https://stackoverflow.com/questions/72278374/plotly-colorbar-orientation-not-changing)

In short: I updated my plotly [5.8.0] to use the newly implemented orientation of the colorbar to make it horizontally, but it's not changing in any way.

**Comment by nicolaskruchten** [comment]
Which environment are you running this in? JupyterLab? Dash? Also, if you mouse over the Plotly logo that appears in the top-right, is there a version number for Plotly.js listed there?

**Comment by jdtrebbien** [comment]
I am using JupyterLab and there is no version number appearing when hovering over the plotly logo.

**Comment by nicolaskruchten** [comment]
OK, in that case, you're running `plotly` 5.8.0 but somehow your JupyterLab extension is way behind. Are you running JupyterLab yourself or connecting to a centrally-hosted JupyterHub? And which version of JupyterLab are you running: 2.x or 3.x?

**Comment by janosh** [comment]
Same problem here. Plot looks like this in Jupyter:

![Screenshot 2023-04-04 at 09 56 48](https://user-images.githubusercontent.com/30958850/229863591-5fd000a3-b371-4981-b4d5-64e7a7116288.png)

And like this in the browser after exporting to HTML (with a page loading `<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>`).

![Screenshot 2023-04-04 at 09 56 25](https://user-images.githubusercontent.com/30958850/229863706-5803f941-f0c3-466d-b550-042089ec6f15.png)

I checked the exported HTML. orientation is as expected:

![Screenshot 2023-04-04 at 09 59 38](https://user-images.githubusercontent.com/30958850/229864072-bcd3f82b-74e4-4285-af45-fb119eac46da.png)

**Comment by nicolaskruchten** [comment]
Please note that `plotly-latest.min.js` is in fact not the latest version. We stopped updating that URL when Plotly.js 2.0 came out to avoid breaking users of that URL, which is now forever pinned to v1.58.5

**Comment by janosh** [comment]
Ah, that solved the problem! Now using `<script src="https://cdn.plot.ly/plotly-2.20.0.min.js"></script>`.

Fwiw, I think not updating `plotly-latest.min.js` is _very_ misleading. People using that expect their code to break on major releases. So I don't see a reason to stop updating it.

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
