### ISSUE TITLE
how to trigger callback event on a plotly scattermapbox plot

### ISSUE THREAD

**Issue by GvdDool-SiS** [plotly/plotly.py#3743]
Hi,
I hope that I am not posting the wrong question/report in the wrong location, but I am trying to apply the click events example (https://plotly.com/python/click-events/) on a scattermapbox, and while this works for a scattergeo plot I am not able to trigger a click event on a scattermapbox plot; is this intended behaviour and are click events not available on this plot type?

```
#the scattermapbox call:
data2 = go.Scattermapbox(lat=list(heat_df.ycoord),
                        lon=list(heat_df.xcoord),
                        mode='markers+text',
                        marker=dict(size=1, color='green'),
                        )

#the scattergeo call:
data2a = go.Scattergeo(lat=list(heat_df.ycoord),
                        lon=list(heat_df.xcoord),
                        mode='markers+text',
                        marker=dict(size=20, color='red'),
                        )

layout = dict(margin=dict(l=0, t=0, r=0, b=0, pad=0),
              mapbox=dict(#accesstoken=mapbox_access_token,
                          center=dict(lat=51.6, lon=-0.2),
                          style='light',
                          zoom=8))

#running this with the scattergeo [data2a] will work, using the scattermapbox fails:
f2 = go.FigureWidget(data=[data2], layout=layout);
f2.update_layout(mapbox_style="stamen-terrain"
                        , mapbox_center = {"lat": map_meanY, "lon": map_meanX}
                        , mapbox_zoom= 11
                        #, clickmode='event'
                );
```

**Comment by GvdDool-SiS** [comment]
Found the problem:
mode='markers+text' should be mode='markers'

Could someone point me to the documentation? I found this on a related community post:
https://community.plotly.com/t/selecteddata-in-scattermapbox-doesnt-fire-when-select-markers/54007

**Comment by GvdDool-SiS** [comment]
But this throws in the ValueError:
```
File ~\anaconda3\envs\geemap_test\lib\site-packages\plotly\basedatatypes.py:2637, in BaseFigure._perform_plotly_relayout(self, relayout_data)
   2633         for key_path_str, v in relayout_data.items():
   2635             if not BaseFigure._is_key_path_compatible(key_path_str, self.layout):
-> 2637                 raise ValueError(
   2638                     """
   2639 Invalid property path '{key_path_str}' for layout
   2640 """.format(
   2641                         key_path_str=key_path_str
   2642                     )
   2643                 )
   2645             # Apply set operation on the layout dict
   2646             val_changed = BaseFigure._set_in(self._layout, key_path_str, v)

ValueError: 
Invalid property path 'mapbox._derived' for layout
```

**Comment by yoyrandao** [comment]
If you're not in ipython context, you can use Dash for map interactions. Example here: https://dash.plotly.com/interactive-graphing

I also faced this problem and Dash was the only solution

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Alternatively, if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
