### ISSUE TITLE
pyc compilation errors on Windows 10

### ISSUE THREAD

**Issue by FaustinCarter** [plotly/plotly.py#3745]
While installing plotly from conda-forge on a Windows 10 PC in a python 3.10.4 environment (using mamba, but the same is true for conda), the compilation of pyc files takes a very long time (about 15 minutes), and fails to compile the following files (the compile command is `[...\\python.exe', '-Wi', '-m', 'compileall', '-q', '-l', '-i', 'C]`):

- ...\Lib\site-packages\plotly\validators\scattermapbox\marker\colorbar\_thicknessmode.py
- ...\Lib\site-packages\mpmath\libmp\libintmath.py
- ...\Lib\site-packages\pyface\ui\wx\font_dialog.py
- ...\Lib\site-packages\plotly\validators\scatterpolar\marker\colorbar\tickformatstop\_templateitemname.py

In all cases, the stack traces was the same, and is reproduced below:

```
python_exe_full_path: ...\.conda\envs\scistack2\python.exe
py_full_path: ...\.conda\envs\scistack2\Lib\site-packages\plotly\validators\scattermapbox\marker\colorbar\_thicknessmode.py
pyc_full_path: ...\.conda\envs\scistack2\Lib\site-packages\invoke\vendor\yaml2\__pycache__\scanner.cpython-310.pyc
compile rc: 1
compile stdout:
...\.conda\envs\scistack2>ECHO OFF
*** Error compiling 'Lib\\site-packages\\invoke\\vendor\\yaml2\\scanner.py'...
  File "Lib\site-packages\invoke\vendor\yaml2\scanner.py", line 1421
    except UnicodeDecodeError, exc:
           ^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: multiple exception types must be parenthesized

*** Error compiling 'Lib\\site-packages\\invoke\\vendor\\yaml2\\constructor.py'...
  File "Lib\site-packages\invoke\vendor\yaml2\constructor.py", line 173
    except TypeError, exc:
           ^^^^^^^^^^^^^^
SyntaxError: multiple exception types must be parenthesized

*** Error compiling 'Lib\\site-packages\\invoke\\vendor\\yaml2\\resolver.py'...
  File "Lib\site-packages\invoke\vendor\yaml2\resolver.py", line 172
    re.compile(ur'''^(?:yes|Yes|YES|no|No|NO
                 ^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: invalid syntax

*** Error compiling 'Lib\\site-packages\\invoke\\vendor\\yaml2\\reader.py'...
  File "Lib\site-packages\invoke\vendor\yaml2\reader.py", line 168
    except UnicodeDecodeError, exc:
           ^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: multiple exception types must be parenthesized
```

The installation completes "successfully", but it seems like y'all ought to know that this is happening.

**Comment by alexcjohnson** [comment]
Thanks @FaustinCarter - this is odd. I have no idea how `invoke` is being installed (I don't get it by installing `plotly` on my Mac) or who's calling it (do you get a more complete stack trace?). It's not mentioned in our codebase. Anyway its `yaml2` module is only supposed to be [imported in Py2](https://github.com/pyinvoke/invoke/blob/f34c6c9413146a34ede3a5b529916b4cee649887/invoke/util.py#L26-L29) so it's not surprising that it would fail in Py3. Seems like `compileall` is being a bit over-aggressive, at least for the unusual "vendor all the things" approach that `invoke` seems to have taken.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
