### ISSUE TITLE
Scattermapbox - Line across the pacific

### ISSUE THREAD

**Issue by thomasbtf** [plotly/plotly.py#3748]
Hey there,

I am trying to plot a line between America and Asia. Is it possible to draw the line across the pacific (on the right side) rather than across the continent (so the shortest way)?

Thanks a lot in advance!

```python
edge_trace = go.Scattermapbox(
    mode = "lines",
    lon = [121.462, -118.21646],
    lat = [29.8267, 33.75418],
)
    
fig = go.Figure(
  data=[edge_trace],
)

fig.update_layout(
    margin ={'l':0,'t':0,'b':0,'r':0},
    mapbox = {

        'style': "open-street-map",
        'zoom': 1}
)
fig.show()
```

![image](https://user-images.githubusercontent.com/46334240/170347688-c26a0fb8-e290-4770-82f2-e2325e92c514.png)

**Comment by alexcjohnson** [comment]
Mapbox will interpolate linearly between the longitude values you provide - but you don't have to provide values on [-180, 180], you can use [-360, 360] so:
```
    lon = [121.462, 360-118.21646],
```
will connect the other way around.

**Comment by thomasbtf** [comment]
Aw, so easy. Works like a charm. Thanks a lot for the quick response! 👍 

![image](https://user-images.githubusercontent.com/46334240/170359666-2f2cdf74-83f8-4233-b320-b7503c826f67.png)
