### ISSUE TITLE
[BUG] go.Heatmap making values NaN? px.imshow is correct

### ISSUE THREAD

**Issue by kmcentush** [plotly/plotly.py#3750]
**Issue:**
For some reason, using `go.Heatmap` causes values to be dropped/excluded from the plot. I'm guessing they're being made NaN and filtered out somehow? `px.imshow` correctly includes all values.

See here for the output from the code below: [output](https://i.imgur.com/00l9tNh.png)

**Versions:**
pandas: 1.40
plotly: 5.8.0

**Reproducible code:**
```
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go

df = pd.DataFrame([[438, 160, 2, 3, 2]], index=["AB"], columns=["100015", "500015", "500030", "500039", "500078"])
print(df)
fig1 = go.Figure(
    data=go.Heatmap(z=df.values, x=df.index, y=df.columns, colorbar=dict(title="count"), hoverongaps=False)
)
fig1.show()
fig2 = px.imshow(
    df.values.T,
    labels=dict(color="count"),
    x=df.index,
    y=df.columns,
)
fig2.show()
```

**Comment by nicolaskruchten** [comment]
`px.imshow` actually basically generates the same kind of figure as you have hand-built in `fig1` (you can check by calling .show("json")` on each if you're in JupyterLab). The difference you're seeing in this case is that you're passing in `df.values` in `fig1` and `df.values.T` in `fig2` as far as I can tell...

**Comment by kmcentush** [comment]
@nicolaskruchten Appreciate the response. I understand that the two generate the same plot, but the specific bug I'm talking about is in the visual appearance. Please take a look at the output I linked in the original post: [image](https://i.imgur.com/00l9tNh.png)

**Comment by nicolaskruchten** [comment]
Yes, I looked at it, and as I said, the difference between the two is that in the first figure you're passing in `z=df.values` and in the second figure you're passing in `z=df.values.T` (note the extra `.T`!)

**Comment by kmcentush** [comment]
@nicolaskruchten why does the extra T make values NaN? The go heatmap only shows values for the entry that has 438 count - the color bar acts like it's the only one that exists. None of the 160, 2, 3, 2 values appear. The imshow has values for everything - 438, 160, 2, 3, 2. If both inputs are numpy arrays (albeit, one transposed as you've pointed out), why is the go heatmap losing/ignoring 4 of the 5 counts?

**Comment by nicolaskruchten** [comment]
It doesn't make anything NaN... In your `fig1`, your `x` and `y` are reversed with respect to your dataset (you've transposed `df.values` without swapping `x` and `y`). Try `y=df.index, x=df.columns` instead of `x=df.index, y=df.columns` in your `fig1` call and you'll see.

**Comment by nicolaskruchten** [comment]
(by passing in an `x` of length 1, you're essentially plotting a single-cell heatmap)

**Comment by kmcentush** [comment]
Oh, I finally get it, thank you so much. Setting the axis names with different dimensions than the raw data cuts things off.

Do you think it's worth adding some sort of warning when this happens (i.e. axis dimensions not aligning with input data)? Happy to close the issue if not.

**Comment by nicolaskruchten** [comment]
It would be very challenging to implement this kind of warning at the `graph_objects` level unfortunately... That said, `px.imshow` actually does provide this warning (try `px.imshow(df.values, x=df.index, y=df.columns)`) and this kind of thing is one of the reasons it's generally recommended to use `px` wherever possible :)
