### ISSUE TITLE
Passing a float in the interval [0, 1] to the "Opacity" property in plotly express scatter_3d function but still getting error 

### ISSUE THREAD

**Issue by shalini-maiti** [plotly/plotly.py#3751]
I'm trying to concatenate a column of floats to an existing dataframe and then pass it to the opacity property of the opacity property of the plotly express's scatter_3d function.

opacity= visibility.repeat(2)
visibility_mask = pd.DataFrame({'visibility': opacity}).astype("float")
cols = total_pandata.columns.to_list() + visibility_mask.columns.to_list()
total_pandata = np.concatenate([total_pandata, visibility_mask], axis=1)
total_pandata = pd.DataFrame(total_pandata, columns=cols)
total_pandata["visibility"] = pd.to_numeric(total_pandata["visibility"], downcast="float")

fig1 = px.scatter_3d(
    x=total_pandata[0], # ie [0, 1, 2, 3]
    y=total_pandata[1], # ie [0, 1, 2, 3]
    z=total_pandata[2], # ie [0, 1, 2, 3]
    color=total_pandata.index,
    size_max=1,
    hover_name=total_pandata.type,
    opacity = (total_pandata.visibility + 1)/2,
    # facet_col="type"
    )

Error -
Name: visibility, Length: 158, dtype: float32      The 'opacity' property is a number and may be specified as:       
- An int or float in the interval [0, 1]

Please note that I checked the type, minimum and maximum value in the dataframe column -
1) min((total_pandata.visibility + 1)/2)
-> 0.5
2) max((total_pandata.visibility + 1)/2)
-> 1.0
3) type((total_pandata.visibility + 1/2).iloc[0])
-> <class 'numpy.float32'>

**Comment by nicolaskruchten** [comment]
the `opacity` argument accepts a **scalar**, not a vector as you're passing in, unfortunately.

**Comment by shalini-maiti** [comment]
Could you give me an example? I'm sorry I do not understand the difference.

**Comment by nicolaskruchten** [comment]
So you're passing in a data frame column right but you should be passing in a single value like 0.5 or something. Its not possible to set an opacity per point, just for the whole plot.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
