### ISSUE TITLE
[FEATURE REQUEST] `matplotlibify` and `save_and_plot` helper functions for academia

### ISSUE THREAD

**Issue by sgbaird** [plotly/plotly.py#3752]
Plotly is amazing. However, I think most academics won't be able to use plotly figures directly in their manuscripts. It's generally preferred for academic manuscript figures to be square, for example (in the simplest case of a single plot, e.g. a single histogram). There are some [medium post guidelines](https://medium.com/swlh/formatting-a-plotly-figure-with-matplotlib-style-fa56ddd97539) for making a plotly figure look more like matplotlib, which is generally a lot more compatible with the format expected for academic journals.

Eventually, I made a helper function called `matplotlibify` largely based on the above linked medium post that I've iterated on over the course of publishing several academic manuscripts in the last 2 years.

Note the difference between the original and `matplotlibify`-ied outputs https://github.com/sparks-baird/xtal2png/issues/38:
### Great for interactive visualization, scales with browser size, etc. would raise eyebrows 🤨 and probably be a cause for requested changes if used directly in academic manuscript
![image](https://user-images.githubusercontent.com/45469701/171062162-5253df3a-e79e-400a-94d6-dfb8ac70fbde.png)

### matplotlibified version, not as great for visualization, but pretty ideal for a lot of academic journals
produced via `matplotlibify()`, see below
![image](https://user-images.githubusercontent.com/45469701/171062256-43c265bc-bc24-4ce5-a378-ce65ab11fc86.png)

# `matplotlibify`
```python
from typing import Union
import plotly.graph_objs as go

def matplotlibify(
    fig: go.Figure,
    size: int = 24,
    width_inches: Union[float, int] = 3.5,
    height_inches: Union[float, int] = 3.5,
    dpi: int = 142,
    return_scale: bool = False,
) -> go.Figure:
    """Make plotly figures look more like matplotlib for academic publishing.

    modified from: https://medium.com/swlh/fa56ddd97539

    Parameters
    ----------
    fig : go.Figure
        Plotly figure to be matplotlibified
    size : int, optional
        Font size for layout and axes, by default 24
    width_inches : Union[float, int], optional
        Width of matplotlib figure in inches, by default 3.5
    height_inches : Union[float, int], optional
        Height of matplotlib figure in Inches, by default 3.5
    dpi : int, optional
        Dots per inch (resolution) of matplotlib figure, by default 142. Leave as
        default unless you're willing to verify nothing strange happens with the output.
    return_scale : bool, optional
        If true, then return `scale` which is a quantity that helps with creating a
        high-resolution image at the specified absolute width and height in inches.
        More specifically:
        >>> width_default_px = fig.layout.width
        >>> targ_dpi = 300
        >>> scale = width_inches / (width_default_px / dpi) * (targ_dpi / dpi)
        Feel free to ignore this parameter.

    Returns
    -------
    fig : go.Figure
        The matplotlibified plotly figure.

    Examples
    --------
    >>> import plotly.express as px
    >>> df = px.data.tips()
    >>> fig = px.histogram(df, x="day")
    >>> fig.show()
    >>> fig = matplotlibify(fig, size=24, width_inches=3.5, height_inches=3.5, dpi=142)
    >>> fig.show()

    Note the difference between
    https://user-images.githubusercontent.com/45469701/171044741-35591a2c-dede-4df1-ae47-597bbfdb89cf.png # noqa: E501
    and
    https://user-images.githubusercontent.com/45469701/171044746-84a0deb0-1e15-40bf-a459-a5a7d3425b20.png, # noqa: E501
    which are both static exports of interactive plotly figures.
    """
    font_dict = dict(family="Arial", size=size, color="black")

    # app = QApplication(sys.argv)
    # screen = app.screens()[0]
    # dpi = screen.physicalDotsPerInch()
    # app.quit()

    fig.update_layout(
        font=font_dict,
        plot_bgcolor="white",
        width=width_inches * dpi,
        height=height_inches * dpi,
        margin=dict(r=40, t=20, b=10),
    )

    fig.update_yaxes(
        showline=True,  # add line at x=0
        linecolor="black",  # line color
        linewidth=2.4,  # line size
        ticks="inside",  # ticks outside axis
        tickfont=font_dict,  # tick label font
        mirror="allticks",  # add ticks to top/right axes
        tickwidth=2.4,  # tick width
        tickcolor="black",  # tick color
    )

    fig.update_xaxes(
        showline=True,
        showticklabels=True,
        linecolor="black",
        linewidth=2.4,
        ticks="inside",
        tickfont=font_dict,
        mirror="allticks",
        tickwidth=2.4,
        tickcolor="black",
    )
    fig.update(layout_coloraxis_showscale=False)

    width_default_px = fig.layout.width
    targ_dpi = 300
    scale = width_inches / (width_default_px / dpi) * (targ_dpi / dpi)

    if return_scale:
        return fig, scale
    else:
        return fig
```

I've been iterating and using this so often across so many projects, that I at the point where I'd prefer to create my own Python package with this functionality rather than keep copy-pasting it as slowly changing "boilerplate" code. However, the thought crossed my mind to open up an issue instead and probe the interest in incorporating this into `plotly.py` itself. If this is out of scope for plotly's vision, that's fine and I'll proceed with making a separate package called `plotly-for-academics` or something like that (open to suggestions if that's the route to go down). There's another function that's also a staple for me (sorry, not fully documented) that fits right along with this because my desire is to create an interactive version, a publication version, and a version I can load and modify ad-hoc. The `update_legend` part could probably move inside `matplotlibify`:
```python
def plot_and_save(fig_path, fig, mpl_kwargs={}, show=False, update_legend=False):
    if show:
        offline.plot(fig)
    fig.write_html(fig_path + ".html")
    fig.to_json(fig_path + ".json")
    if update_legend:
        fig.update_layout(
            legend=dict(
                font=dict(size=16),
                yanchor="bottom",
                y=0.99,
                xanchor="right",
                x=0.99,
                bgcolor="rgba(0,0,0,0)",
                # orientation="h",
            )
        )
    fig = matplotlibify(fig, **mpl_kwargs)
    fig.write_image(fig_path + ".png")
```
Aside: for `fig.to_json(fig_path + ".json")` it hasn't ever seemed to actually save it, and I haven't been bothered enough to figure out why because I've always had the workaround of re-running my plotting scripts and regenerating the figures if I need to make some change. Might open a bug report on this

Lmk what you think. Happy to discuss and eventually make a PR if needed.

**Comment by nicolaskruchten** [comment]
Thanks for sharing! I don't think this is something we would want to support on an ongoing basis within the `plotly` module itself but I'm glad you were able to build it! Please let us know if there are any features in the main library which would make this kind of thing easier or if there is anything missing in the main library preventing you from doing something you'd like to.

PS: `fig.to_json()` returns a string, and `fig.write_json()` writes it to a file ;)

**Comment by nicolaskruchten** [comment]
PPS: most of the changes in your function could be baked into an easy-to-register-and-reuse `template` (https://plotly.com/python/templates/) I think, meaning that only stuff like the size calculation really needs to be in a an executable function

**Comment by sgbaird** [comment]
> Thanks for sharing! I don't think this is something we would want to support on an ongoing basis within the `plotly` module itself but I'm glad you were able to build it! Please let us know if there are any features in the main library which would make this kind of thing easier or if there is anything missing in the main library preventing you from doing something you'd like to.

Sure thing! No worries, I really appreciate the prompt reply.

> PS: `fig.to_json()` returns a string, and `fig.write_json()` writes it to a file ;)

Ah! Thank you!

> PPS: most of the changes in your function could be baked into an easy-to-register-and-reuse `template` (https://plotly.com/python/templates/) I think, meaning that only stuff like the size calculation really needs to be in a an executable function

This looks great. Thank you for sharing! I may use this. https://plotly.com/python/templates/#saving-and-distributing-custom-themes

Is there a place for people to make custom templates available? If not, will probably still package it on PyPI and Anaconda to reduce boilerplate code.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for several years, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Thanks for your help - @gvwilson
