### ISSUE TITLE
dataset is deprecated - use new one

### ISSUE THREAD

**Issue by Coding-with-Adam** [plotly/plotly.py#3810]
On [this page of the plotly docs](https://plotly.com/python/pca-visualization/#visualize-a-subset-of-the-principal-components), the code under `Visualize a subset of the principal components` uses the Boston dataset. 

A few seconds after the page loads, an error is displayed. Here's a portion of it:

    /home/circleci/project/doc/venv/lib/python3.7/site-packages/sklearn/utils/deprecation.py:87: FutureWarning:

    Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

**Comment by LiamConnors** [comment]
The example was updated recently to use a different dataset so the warning is no longer there
