### ISSUE TITLE
Replace data set used in one of the PCA Visualization examples of the docs

### ISSUE THREAD

**Issue by Coding-with-Adam** [plotly/plotly.py#3815]
hi @LiamConnors 
We need to update the following example to use a different data set: [Visualize a subset of the principal components](https://plotly.com/python/pca-visualization/#visualize-a-subset-of-the-principal-components). If you load the page, you will see an alert about the boston dataset not be ethical.

> Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2. The Boston housing prices dataset has an ethical problem. You can refer to the documentation of this function for further details.

**Comment by LiamConnors** [comment]
This was replaced a while ago but the issue was never closed
