### ISSUE TITLE
create_table in FigureFactory is non performant on large datasets

### ISSUE THREAD

**Issue by aggFTW** [plotly/plotly.py#383]
I noticed that anything above 100 rows takes a long time to render a table. I looked at the code in https://github.com/plotly/plotly.py/blob/master/plotly/tools.py#L2659 and noticed that the _Table object is being created two times.

Moreover, a heatmap is being created, which we have no use for.

Are there plans to make plotly more performant with medium-large datasets?

**Comment by aggFTW** [comment]
Did some perf analysis, and the bottle neck seems to be in the Javascript side of the code, not on the Python side. It takes ~42 seconds for a table of 60 rows to be rendered after calling `iplot()`.

ping @etpinard for plotly js knowledge

**Comment by jonmmease** [comment]
Plotly now supports a first class [table trace](https://plot.ly/python/table/). This is the recommended approach and it has much better performance characteristics than the figure factory.
