### ISSUE TITLE
BUG: rangebreaks for datetime axises, the value+dvalue doesn't work with bounds

### ISSUE THREAD

**Issue by qianyun210603** [plotly/plotly.py#3830]
It looks that the `value+dvalue` mode doesn't work well with the `bounds` mode for `rangebreak` parameter of the datetime axis. Below is an simple example to replicate the issue:

#### packages import and data preparation:
```python
import numpy as np
import pandas as pd
from pandas.tseries.offsets import CustomBusinessHour, BusinessDay
from pandas.tseries.holiday import USFederalHolidayCalendar
import plotly.offline as py
import plotly.graph_objs as go

x = pd.bdate_range('2020-12-15', '2021-01-15', freq=CustomBusinessHour(calendar=USFederalHolidayCalendar()))
y = np.sin(np.arange(len(x))/3)
```

#### Scenario I, bounds only to exclude non-business hours and weekends
```python
layout1=go.Layout(xaxis=dict(tickangle=45, rangebreaks=[
    dict(pattern='hour', bounds=[17, 9]),
    dict(bounds=['sat', 'mon'])
]))
fig1 = go.Figure(data=go.Scatter(x=x, y=y), layout=layout1)
fig1.show()
```
![image](https://user-images.githubusercontent.com/18441788/181880574-4cb403e2-c28f-4180-add8-04777985fd0a.png)
We see the discontinuity on business-day holidays 2020-12-25, 2021-01-01 as expected.

#### Scenario II, trying to exclude the holidays with `values` dict
```python
missing_date2 = list(set(pd.bdate_range('2020-12-15', '2021-01-15')) - set(x.normalize()))

layout2=go.Layout(xaxis=dict(tickangle=45, rangebreaks=[
    dict(values=missing_date2),
    dict(pattern='hour', bounds=[17, 9]),
    dict(bounds=['sat', 'mon']),
]))
fig2 = go.Figure(data=go.Scatter(x=x, y=y), layout=layout2)
fig2.show()
```
![image](https://user-images.githubusercontent.com/18441788/181880755-3e5fc340-ee32-405a-814f-4bde64c7a3f7.png)
We see the plot get messed.

#### Scenario III, use `values` for day level only:
Even I don't use `bounds` for weekends, it still faces same problem:
```python
missing_date3 = list(set(pd.date_range('2020-12-15', '2021-01-15')) - set(x.normalize()))

layout3=go.Layout(xaxis=dict(tickangle=45, rangebreaks=[
    dict(values=missing_date3),
    dict(pattern='hour', bounds=[17, 9]),
]))
fig3 = go.Figure(data=go.Scatter(x=x, y=y), layout=layout3)
fig3.show()
```
![image](https://user-images.githubusercontent.com/18441788/181882291-29c81869-03fb-46bf-820d-39df10324617.png)

Can someone help take a look please?

**Comment by TianMingZhiZi0000** [comment]
出现了同样的问题
调整了代码的先后顺序
将需要截断的日期放在了时间的前面,将带有规则的代码放在了指定时间的代码前面
得到了正确的图
例如:
```python
rangebreaks=[
    dict(bounds=[11.6, 13.4], pattern="hour"),
    dict(bounds=[15.1, 20.9], pattern='hour'),
    dict(bounds=[23.1, 8.9], pattern='hour'),
    dict(bounds=[6, 1], pattern='day of week'),
    dict(values=需要删除时间序列),
]
```
改为
```python
rangebreaks=[
        dict(bounds=[6, 1], pattern='day of week'),
        dict(values=需要删除时间序列),
        dict(bounds=[11.6, 13.4], pattern="hour"),
        dict(bounds=[15.1, 20.9], pattern='hour'),
        dict(bounds=[23.1, 8.9], pattern='hour'),
]
```
貌似坐标轴范围截断的原理是坐标轴前移,如果顺序不正确,坐标轴就会前移两次,造成重叠
修改后,重叠的坐标轴就能恢复正常
![image](https://user-images.githubusercontent.com/125286632/236845991-3d5752e7-f15d-45dc-bb82-35144c981a73.png)

**Comment by qianyun210603** [comment]
Thanks @TianMingZhiZi0000 
revisited and looks I excluded less than needed timepoints.
