### ISSUE TITLE
subplots with legend in one of the plots does not work

### ISSUE THREAD

**Issue by orena1** [plotly/plotly.py#384]
This does not work, the problem is the legend

`````` python
from plotly import tools
import plotly.plotly as py
import plotly.graph_objs as go


fig = figure()
ax3 = subplot2grid((2,2),(0,1),rowspan=2)
ax1 = subplot2grid((2,2),(0,0))
ax2 = subplot2grid((2,2),(1,0))



ax1.plot([1,2],[5,2])
ax2.plot([1,2],[2,3])
ax3.plot([4,2],[7,3])
ax3.legend('dfsdf')## Without this line it does work
suptitle(Cell1)

plot_url = py.plot_mpl(fig)```
``````

**Comment by tarzzz** [comment]
The Legends are not being converted properly. We might need to re-write the legend specific parsing code in `mplexporter`..

**Comment by tarzzz** [comment]
@cldougl This one is handled by #416 
Although it may or may not convert the legend properly ( that depends on how the mpl figure is defined), but it will ensure that the conversion does not fails. Please feel free to review and comment, 

Here is the diff (it's a minor update): https://github.com/plotly/plotly.py/commit/92d55671d7d57bb8d634203ea8c6727c91d93abe

**Comment by birnstiel** [comment]
I think I have the same issue. What about that fix? When does it make it into a release?
