### ISSUE TITLE
pattern_shape_map doesn't work in plotly.express

### ISSUE THREAD

**Issue by LasseVDHeydtQC** [plotly/plotly.py#3849]
See a minimal example below. While color maps work fine, the **pattern map is ignored**.

```
import pandas as pd
import plotly.express as px  #version 5.9.0

dummy_data = pd.DataFrame({"A":[2,3,4,3,2,5],"B":[3,6,4,6,5,1]})
px.bar(dummy_data,pattern_shape_map={"A":".","B":"+"}, color_discrete_map={"A":"green","B":"blue"})
```
![Screenshot 2022-08-14 at 12 15 08](https://user-images.githubusercontent.com/103608900/184532388-bf39ef9c-658c-4924-81c1-5630b45bb379.png)

**Comment by nicolaskruchten** [comment]
This is because when you just pass in a data frame, x/y/color are inferred automatically but not pattern_shape. You'll need to explicitly set `pattern_shape="variable"` here I believe.

**Comment by nicolaskruchten** [comment]
There's also something odd about your example here: the discrete color map is set to green/yellow but the image you pasted has green/blue :)

**Comment by LasseVDHeydtQC** [comment]
I see, that works 🚀.
