### ISSUE TITLE
Errors positioning annotations

### ISSUE THREAD

**Issue by yotkadata** [plotly/plotly.py#3854]
Building an animated map with `choropleth_mapbox` I discovered a bug trying to position an annotation. For the annotation I create multiple PNG files and then stitch them together. Since every PNG file represents one day, I would like to have the current date appear at the right side of the figure, but moving downwards step-wise with every day. To get that effect, I calculate the vertical position based on the date. Basically I calculate the time frame of all dates in seconds and then divide the difference of the current date to the first date by that value:

```
# Calculate position of the date
total_seconds = (last_date_total - first_date_total).total_seconds()
now_seconds = (date - first_date_total).total_seconds()
date_position = 1 - (now_seconds / total_seconds)
```
That correctly creates values that linearly change. I then use that value to position the date. The expected behavior is that the date 'slides' downwards only. But that doesn't happen: On some days (for example, 19 Nov 2020) the date jumps up a little bit (not very much, but enough to note it clearly).

I reported the problem in the [Plotly community](
https://community.plotly.com/t/difficulties-setting-annotation-position-accurately/66899/3) and was asked to file a bug report here.

Here is a **minimal reproducible example**. Stripping down the code I noticed I could even reproduce the error in an empty figure:

```
import pandas as pd
import plotly.graph_objects as go
import datetime as dt
import imageio
import pathlib

# Create folder for export
path = 'export/png/' + str(dt.datetime.now().strftime('%Y%m%d-%H%M%S'))
export_path = pathlib.Path(path)
export_path.mkdir(parents=True, exist_ok=True)

# Create a list for the image paths
image_files = []

# Set min and max dates of the whole dataset (usually this comes from the dataframe)
first_date_total = pd.to_datetime('2020.03.01')
last_date_total = pd.to_datetime('2022.04.30')

# Create date ranges to plot
dates = pd.date_range(start='2020.11.01', end='2020.11.30')

# Loop through dates
for date in dates:

    # Calculate position of the date
    total_seconds = (last_date_total - first_date_total).total_seconds()
    now_seconds = (date - first_date_total).total_seconds()
    date_position = 1 - (now_seconds / total_seconds)

    # Create an empty figure
    fig = go.Figure()

    # Add some info to it
    fig.update_layout(
        autosize=False,
        height=800,
        width=1000,
        annotations=[
            dict(
                xref='paper',
                yref='paper',
                x=1,
                y=date_position,
                showarrow=False,
                text='<b>' + str(date.strftime('%d.%m.%Y')) + '(' + str(round(date_position, 5)) + ')</b>',
            ),
        ]
    )

    # Export fig as PNG
    file = str(export_path) + '/' + date.strftime('%Y-%m-%d') + '-' + '.png'
    fig.write_image(file, width=1000, height=800)
    image_files.append(file)

# Create a list for the images to be stitched together
images = []

# Loop through images from above and append them
for file_name in image_files:
    images.append(imageio.v2.imread(file_name))

# Create an animation
gif_path = str(path) + '/animation.gif'
imageio.mimsave(gif_path, images, fps=7)
```

This is the result of the code above:
![plotly-error-mre](https://user-images.githubusercontent.com/7913590/184971907-11b05e11-6c19-4319-bd9d-03180904f23f.gif)

**Comment by empet** [comment]
I updated your code as follows:
```
fig.update_layout(xaxis_autorange=False, yaxis_autorange=False)
```
and removed `autosize=False`
In each annotation I set the text anchors:
```
yanchor="bottom",
xanchor="right",
```
and  `y=round(date_position, 3)`, because (I guess)  plotly.js cannot put a text at a position with so many digits.
 Also I added `scale=1` in fig.write_image:
```
fig.write_image(filename, width=1000, height=800, scale=1)
```
and this the result with fps=5, and font_size=14, just to see that it works:
![forum-annot3](https://user-images.githubusercontent.com/3627253/184988069-db7d5ae4-be9e-47ba-b725-bc2a7a6ac6d8.gif)

**Comment by yotkadata** [comment]
Thanks @empet! It seems that simply adding

```
yanchor="bottom",
xanchor="right",
```

is enough. I don't really understand why that is necessary, but it solves the problem.
