### ISSUE TITLE
How to translate the modebar tooltips to another language?

### ISSUE THREAD

**Issue by SebBanDev** [plotly/plotly.py#3873]
I have tried:
`locale.setlocale(locale.LC_ALL , 'de_DE')`
and
```python
config = {
    'locale': 'de-DE'
}
fig.show(config=config)
```
But the modebar tooltips are still in English
![image](https://user-images.githubusercontent.com/51693106/187193822-685b2be0-23b0-4602-a2d0-9597c3542281.png)

Is there any way to translate them?

**Comment by AaronStiff** [comment]
Hi @SebBanDev. This issue in `plotly.js` looks like it answers your question: plotly/plotly.js#4468
