### ISSUE TITLE
`go.Image`doesnt have showlegend attribute

### ISSUE THREAD

**Issue by chrismit3s** [plotly/plotly.py#3887]
`go.Scatter` (and `go.Bar`, `go.Pie` and many other) graph objects have a property [`showlegend`](https://plotly.github.io/plotly.py-docs/generated/plotly.graph_objects.Scatter.html#:~:text=showlegend) to control whether it appears in the legend. `go.Image` is missing it (see [the docs](https://plotly.github.io/plotly.py-docs/generated/plotly.graph_objects.Image.html)).

**Comment by alexcjohnson** [comment]
Needs to be addressed in plotly.js https://github.com/plotly/plotly.js/issues/4632
