### ISSUE TITLE
Warning "Cannot find reference 'Bar' in '__init__.py" in IntelliJ IDEA

### ISSUE THREAD

**Issue by osya** [plotly/plotly.py#389]
To fix it please add the line `__all__ = ['AngularAxis', 'Annotation', 'Annotations', 'Area', 'Bar', 'Box', 'Choropleth', 'ColorBar', 'Contour', 'Contours', 'Data', 'ErrorX', 'ErrorY', 'ErrorZ', 'Figure', 'Font', 'Heatmap', 'Histogram', 'Histogram2d', 'Histogram2dContour', 'Histogram2dcontour', 'Layout', 'Legend', 'Line', 'Margin', 'Marker', 'Mesh3d', 'Pie', 'RadialAxis', 'Scatter', 'Scatter3d', 'Scattergeo', 'Scattergl', 'Scene', 'Stream', 'Surface', 'Trace', 'XAxis', 'XBins', 'YAxis', 'YBins', 'ZAxis']` in the file `plotly\graph_objs\__init__.py`

**Comment by cldougl** [comment]
Hey @osya can you let us know what issue this is causing for you?

**Comment by osya** [comment]
In IntelliJ IDEA, PyCharm the following warning appeares: "Caannot find reference 'Bar' in  @__init__.py"
![plotly_warning](https://cloud.githubusercontent.com/assets/998657/13521979/9f8a03e8-e1fd-11e5-8ed9-84d9af3e3479.png). Adding line __all__ = ... in __init__.py solves this warning

**Comment by grrttedwards** [comment]
I encountered this issue, and was able to move past it by adding the line noted in the OP.

Is this something that other users don't have a problem with? I was unable to use `graph_obj.Bar`.

**Comment by theengineear** [comment]
Resolved in `1.13.0`
