### ISSUE TITLE
Adjusting data resolution of plots

### ISSUE THREAD

**Issue by dakenblack** [plotly/plotly.py#3902]
Hi,

I'd like to request a feature (or a way to create my intended scenario).

**Painpoint:** 

At times I want to visualise a lot of data (timeseries). When the charts are rendered (I usually render it inline in Jupyter lab) the browser slows down (I assume due to the number of individual elements on the chart). I've attached a small example as a plotly json file, most of my usecases will have more traces though. 

[test.txt](https://github.com/plotly/plotly.py/files/9642144/test.txt)

When I create charts, I usually undertake 2 steps of analysis

1. From the complete data set I identify areas of interest
2. I zoom in to the areas of interest to interrogate the data in more detail.

If I did not preprocessing and just used the detailed data set, step 1 will be slow to render due to the number of data points.

**Current solution:** To avoid this, I have decided to first reduce the resolution of the data (from 1h to 1day for example) and then conduct step 1 and then plot the detailed (original resolution) data set for only the areas of interest.

**Desired solution:** 
Is there a way to plot the detailed dataset such that it is of a lower resolution (ideally something that can be configured) and then when zoomed in the datapoints return to its original resolution.

**Alternative solution:**
Alternatively I can also conduct the resampling in Python and create 2 datasets (of higher and lower resolution). I would then plot both traces but hide one based on the zoom level. Is something like this possible in Plotly?

I understand that this is most likely a rare usecase, so I understand that a new feature in plotly is unreasonable but I would like some guidance to improve my own workflow.

Great job on the plotly project by the way, My work has considerably improved because of this project. Thank you for remaining open source.

Thanks for your assistance,
Jabez

**Comment by dakenblack** [comment]
Update:

I was mistaken, the problem was not with the high resolution, but with a combination of bar-chart+line-chart+matched x-axis and large resolution. Here is a actual slow chart:
[test.txt](https://github.com/plotly/plotly.py/files/9642257/test.txt)

**Comment by nicolaskruchten** [comment]
Depending on what's happening here, you may have some luck with https://github.com/predict-idlab/plotly-resampler as a dynamic solution.

**Comment by dakenblack** [comment]
Wow, that looks like the solution I'm looking for. Thanks so much.

Jabez
