### ISSUE TITLE
Subplot with facet_col_wrap has unexpected behavior when referring to rows

### ISSUE THREAD

**Issue by valankar** [plotly/plotly.py#3903]
Not sure what the problem here is but it is very confusing. I'm trying to add a hline to a subplot using facet_col_wrap. When I specify the row to add_hline(), it doesn't actually add it to the proper row.

The code I have is as follows:

```python
#!/usr/bin/env python3
"""Test plot."""
import pandas as pd
import plotly.express as px


def main():
    """Test plot."""
    test_df = pd.read_csv('test.csv', index_col=0, parse_dates=True,
                          infer_datetime_format=True)
    line = px.line(
        test_df, x=test_df.index, y=test_df.columns, facet_col='variable', facet_col_wrap=2,
    )
    line.add_hline(y=100000, row=3, col=1)
    with open('test.html', 'w', encoding='utf-8') as out_file:
        out_file.write(line.to_html())


if __name__ == '__main__':
    main()
```

Here is a screenshot of the web page generated:

![subplot](https://user-images.githubusercontent.com/31250800/192303037-fb9c08c1-a52f-46ca-99cb-569589dd5160.jpg)

As you can see, the line gets added to row 1 instead of row 3.

The input CSV file is attached:

[test.csv](https://github.com/plotly/plotly.py/files/9647116/test.csv)

**Comment by valankar** [comment]
Ah, I see. Thanks!

**Comment by nicolaskruchten** [comment]
Clarification: in Plotly *Express* they're numbered from the bottom, because PX calls `make_subplots` internally with `start_cell='bottom-left'`

**Comment by valankar** [comment]
I see, thanks. I think this is mainly what confused me, because I was also using make_subplots directly and expected the same behavior with Plotly Express.
