### ISSUE TITLE
Angular axis in polar charts doesn't have the title parameter

### ISSUE THREAD

**Issue by AAnzel** [plotly/plotly.py#3904]
I am not sure if this is a bug or a feature request. As the title says, the title of the angular axis can't be changed or set as a parameter. I can change the radial axis title, but not the angular one. There is also no parameter in the documentation [https://plotly.com/python/reference/layout/polar/#layout-polar-angularaxis](https://plotly.com/python/reference/layout/polar/#layout-polar-angularaxis). The code for the redefinition of my chart is below.

```
chart_result.update_layout(
        polar = dict(
            sector=[0, 180],
            angularaxis=dict(
                #thetaunit = "degrees",
                dtick=10,
                #rotation=270,
                direction="counterclockwise",
                #tickmode="array",
                tickvals=list_angular_ticks,
                ticktext=list_angular_labels,
            ),
        ),
        height=600
    )
    
    chart_result.update_polars(
        radialaxis_title_text='Normalized STD',
    )
```

**Comment by alexcjohnson** [comment]
That's correct, there's no title for an angular axis. Where would we draw it? I'll close this issue, but if you have an example or proposal for what this should look like feel free to open a new issue in https://github.com/plotly/plotly.js as that's where this would need to be implemented (then it will automatically be included here in the next release)

**Comment by AAnzel** [comment]
Thank you for your comment. I will open a new issue in [https://github.com/plotly/plotly.js](https://github.com/plotly/plotly.js).
