### ISSUE TITLE
Scattergl yaxis title is not being centered

### ISSUE THREAD

**Issue by rminnett** [plotly/plotly.py#391]
See the modified example from https://plot.ly/python/webgl-vs-svg/:
![image](https://cloud.githubusercontent.com/assets/1182698/12443371/4a4ba76a-bf0c-11e5-85fd-5b0ce8db1d49.png)

**Comment by chriddyp** [comment]
thanks for reporting @rminnett ! I've just reposted an issue in the javascript library that plotly.py uses here: https://github.com/plotly/plotly.js/issues/198

**Comment by rminnett** [comment]
Great, thanks!
