### ISSUE TITLE
Add support for line width and opacity for parallel coordinates plot

### ISSUE THREAD

**Issue by ccaloian** [plotly/plotly.py#3916]
I would like to be able to control the line width for parallel coordinates plot, and this doesn't seem to be supported currently. As for other figure types, I would like to be able to set the line width and opacity as in the code below.

```python
import plotly.graph_objects as go

fig = go.Figure(
    data=go.Parcoords( 
        dimensions=[
            dict(range=[0, 1], label="A", values=[0.1, 0.4, 0.5, 0.3]),
            dict(range=[3, 5], label="B", values=[3.8, 4.2, 4.9, 3.2]),
            dict(range=[0, 2], label="C", values=[0.1, 0.4, 1.5, 1.3]),
        ],
        line=dict(
            color="darkred",
            width=3,
            opacity=0.7,
        ),
    )
)

fig.show()
```

Current behaviour results in the following error

```
ValueError: Invalid property specified for object of type plotly.graph_objs.parcoords.Line: 'width'
```

**Comment by empet** [comment]
The trace type, `parcoords`, has been devised with a constant line width to ensure high performance for large parcoords plots. There is an opened issue here [https://github.com/plotly/plotly.js/issues/4504](https://github.com/plotly/plotly.js/issues/4504), you can follow for eventual updates.
To see what are the actual   parcoords line attributes, inspect them, displayed by:
`help(go.parcoords.Line)`.

**Comment by ccaloian** [comment]
Thanks @empet and @alexcjohnson. I'm closing this issue and follow plotly/plotly.js#2573.
