### ISSUE TITLE
Line plot with category_orders draws the line in the wrong order

### ISSUE THREAD

**Issue by ba-tno** [plotly/plotly.py#3920]
I am trying to plot a pandas DataFrame with a column that contains the month as a string:

```
df = pd.DataFrame({"month": ["feb", "mar", "jan", "apr"], "value": [20, 3, 10, 4]})
df
```
|    | month   |   value |
|---:|:--------|--------:|
|  0 | feb     |      20 |
|  1 | mar     |       3 |
|  2 | jan     |      10 |
|  3 | apr     |       4 |

If I just feed this to `px.line` the x-axis is in alphabetical order (feb, mar, jan, apr):

```
px.line(df, x="month", y="value")
```
![newplot](https://user-images.githubusercontent.com/52008464/195650618-76baeeca-423a-4d85-b0d0-81780db7c498.png)

Luckily px.line has [a `category_orders` argument][pxline]:

```
px.line(df, x="month", y="value", category_orders={"month": ["jan", "feb", "mar", "apr"]})
``` 
It changes the x-axis order, but it draws the line in the original order: from feb to mar to jan to apr

![newplot (1)](https://user-images.githubusercontent.com/52008464/195651078-7bd8e47a-7a66-4a0b-b1ac-ca64276315de.png)

Should I call the px.line in another way when I want to use that argument? Because the current behaviour seems incorrect.

I can work around it by first sorting my DataFrame and then plotting, but it would be more convenient if the `category_orders` argument could be able to take care of it.

```
monthdict = {"jan": 1, "feb": 2, "mar": 3, "apr": 4}
df.sort_values(by="month", inplace=True, key=lambda x: x.map(monthdict))
px.line(df, x="month", y="value")
```
![newplot (2)](https://user-images.githubusercontent.com/52008464/195652393-43d37340-e034-43ff-95f1-90b1a1e5d1e7.png)

I founde #3645, but that seems to be in combination with the `facet_col` argument. I am experiencing this issue with a "plain" line.

Version of plotly is 5.10.0.

[pxline]: https://plotly.com/python-api-reference/generated/plotly.express.line.html#:~:text=in%20each%20frame.-,category_orders,-(dict%20with%20str

**Comment by nicolaskruchten** [comment]
The current behaviour is as designed: lines connect points in the order they are given in the input data frame, and the category_orders controls the axis order only, independent of the data frame order.
