### ISSUE TITLE
JupyterLab (base) -> plotly (project-env): FigureWidget not working

### ISSUE THREAD

**Issue by h-vijayakumaran** [plotly/plotly.py#3924]
Hi
Use-Case:
I have `jupyterlab=3.4.5` installed on my `base` environment. For any environment I create for a project, let us call it `project-env`, I install `ipykernel` in it so that the `jupyterlab` launched from `base` environment can find the `project-env` in the list of kernels. This keeps my `project-env` minimal and it makes using `jupyterlab` simultaneously for multiple projects easy - as I can have one instance of `jupyterlab` launched from `base` and multiple notebooks within it that could be run on different kernels.

Problem:
1. I created a minimal conda environment `plotly-env` to test plotly. This has `plotly=5.10.0`, `ipykernel`, `ipywidgets = 7.7.1` installed in it.
2. Launched `jupyterlab` from `base` and chose `plotly-env` as my kernel. Ran the following lines:
```
import plotly.graph_objects as go

fig = go.FigureWidget()

fig
```
This gives me the following error: "Error displaying widget: model not found". Could this be fixed somehow?

---

P.S: Note that I tried creating another environment `plotly-env2` with `jupyterlab>=3`, `plotly=5.10.0`, `ipywidgets = 7.7.1` installed in it. I launched `jupyterlab` from `plotly-env2`, and the above code doesn't throw an error. But unfortunately, this solution is not a convenient solution for my problem.

**Comment by skabbit** [comment]
Got absolutely the same issue on `jupyterlab==3.4.8`.

**Comment by nicolaskruchten** [comment]
This is pretty much as expected, and I would expect it to happen with any third-party widget... The widget code must be installed in the same environment as `jupyterlab` itself, not just the kernel.
