### ISSUE TITLE
[BUG] Sign modifier does not work with floats in hovertemplate format strings

### ISSUE THREAD

**Issue by JamesVarndell** [plotly/plotly.py#3937]
Using plotly==5.10.0, I've encountered an issue when using hovertemplates containing plus signs with floats (e.g. `:+.1f`). See the following example:

```
import plotly.graph_objects as go

fig = go.Figure()
fig.add_scatter(y=[-1.55, 0, 1.55], hovertemplate="%{y:+.1f}")
```

The hovertemplate format `%{y:+.1f}` should result in hovertemplate with y values rounded to 1 decimal place, and with a plus sign preceding any positive values. However, not only does the plus sign not appear, but the number of decimal places is not respected either (see hovered point in the top right corner):

![image](https://user-images.githubusercontent.com/36902610/197977183-0d5e0563-20a7-41cd-8941-acd5708aa89c.png)

This formatting has definitely worked for me in Plotly version 4.x in the past.

Many thanks.

**Comment by AaronStiff** [comment]
This looks to be a `d3` related issue, and thus more suited to `plotly.js`
