### ISSUE TITLE
init_notebook_mode() breaks conversion of notebook to slides

### ISSUE THREAD

**Issue by llambourne** [plotly/plotly.py#394]
Hi,

If I try and convert a test notebook to slides using 
`jupyter nbconvert --to slides test.ipynb --post serve`

if the notebook contains a call to plotly.init_notebook_mode() then the resulting slides are just a blank page and I get the following javascript error:
`TypeError: require is not a function`
from where the require function is called at the bottom of the test.slides.html file that nbconvert produces. 

the issue seems to be as a result of the javascript:
`require=requirejs=define=undefined;`
in init_notebook_mode()

**Comment by jonmmease** [comment]
`require=requirejs=define=undefined` is no longer performed in `init_notebook_mode()`
