### ISSUE TITLE
Artifacts on line scatter plot when the first item is None

### ISSUE THREAD

**Issue by spartako** [plotly/plotly.py#3959]
Take the example from docs: https://plotly.com/python/line-charts/

Connect Data Gaps
```
import plotly.graph_objects as go

x = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]

fig = go.Figure()

fig.add_trace(go.Scatter(
    x=x,
    y=[None, 20, None, 15, 10, 5, 15, None, 20, 10, 10, 15, 25, 20, 10],
    name = '<b>No</b> Gaps', # Style name/legend entry with html tags
    connectgaps=True, # override default to connect the gaps
    mode='lines',
))
fig.add_trace(go.Scatter(
    x=x,
    y=[None, 15, None, 10, 5, 0, 10, None, 15, 5, 5, 10, 20, 15, 5],
    name='Gaps',
    mode='lines',
))

fig.show()
```

Modify `y` and substitute the first value with `None`. Run it and then pan/zoom on the plot. Parts of the second scatter
plot will get "stuck".

![image](https://user-images.githubusercontent.com/5825885/202687099-065d91cb-4bf7-4807-9760-62f1e80257ee.png)

**Comment by AaronStiff** [comment]
What version of plotly are you on? I can't seem to reproduce this issue with `plotly 5.13`
