### ISSUE TITLE
Cannot see plots in saved ipython notebook

### ISSUE THREAD

**Issue by entron** [plotly/plotly.py#396]
I used plotly offline in an ipython notebook, the plots look very nice. However, when I saved the notebook and reopened the plots are not showing there. Is there a bug?

Here is my notebook: 

https://github.com/entron/entity-embedding-rossmann/blob/master/embedding_visualization_plotly.ipynb

**Comment by yankev** [comment]
Did you open the notebook on your computer, or on github?

**Comment by yankev** [comment]
Also if you want to share your notebook online you can paste the link of your notebook here:
http://nbviewer.jupyter.org/

For example this is your notebook: http://nbviewer.jupyter.org/github/entron/entity-embedding-rossmann/blob/master/embedding_visualization_plotly.ipynb

**Comment by entron** [comment]
If I open on the same computer I wrote the notebook then the plots will be displayed correctly. If I open it on a different computer or in github, the plots are not shown.  However the method you suggest works nicely! Any reason why I have to use http://nbviewer.jupyter.org/ ?

**Comment by yankev** [comment]
@entron: It's because Plotly charts need to be rendered in a browser in order to be displayed, and because github doesn't run your ipynb like nbviewer does, the plots won't show up.
