### ISSUE TITLE
FF ternary_contour - add cliponaxis

### ISSUE THREAD

**Issue by is95t** [plotly/plotly.py#3960]
Would it be possible to add the cliponaxis (as has been implemented for scatter ternary plots - see issue #1385 https://github.com/plotly/plotly.js/issues/1385). This would allow the markers not to be cut off by the plot area when the showmarkers tag is set to true. 
Currently I have a plot like so:

![image](https://user-images.githubusercontent.com/95185273/202932413-c1d6b776-a92b-4f04-b037-097322d8e2af.png)

However, as he edge markers are cut off, it looks like I have less points. The plot below shows which points are plotted:

![image](https://user-images.githubusercontent.com/95185273/202932180-072d6cd9-f95d-480e-a23d-60aeb54424f1.png)

It would be really great to add this tag to the ff.ternary_contour plot, as it is so useful in the scatter ternary. If there is also a work around that I have missed, please let me know (I have had a go at this but can't find any way to get the markers not to be cut off).

Thanks

**Comment by alexcjohnson** [comment]
`fig.update_traces(cliponaxis=False)` after making the figure?

**Comment by is95t** [comment]
@alexcjohnson thanks for the suggestion, unfortunately this doesn't work (the code will run but the cliponaxis is not implemented). I believe this is to do with the fact the ternary_contour plot is part of the figure factory set and therefore might need to be implemented directly in the ff backend?

**Comment by alexcjohnson** [comment]
Ah, I see - looks like whatever we did to create those contour lines includes lines around the border that don't really add any value... and to compensate we clip them and add border lines. If we undo that, you can see the unclipped markers. Here's one of the examples from https://plotly.com/python/ternary-contour/ but taking that out and adding `cliponaxis=False`:

```py
import plotly.figure_factory as ff
import numpy as np
Al, Cu = np.mgrid[0:1:7j, 0:1:7j]
Al, Cu = Al.ravel(), Cu.ravel()
mask = Al + Cu <= 1
Al, Cu = Al[mask], Cu[mask]
Y = 1 - Al - Cu

enthalpy = (Al - 0.5) * (Cu - 0.5) * (Y - 1)**2
fig = ff.create_ternary_contour(np.array([Al, Y, Cu]), enthalpy,
                                pole_labels=['Al', 'Y', 'Cu'],
                                ncontours=20,
                                coloring='lines',
                                showmarkers=True)
fig.update_traces(cliponaxis=False)
ax_override = dict(min=0, linewidth=0)  # the figure factory includes min=0.01, linewidth=2
fig.update_layout(ternary_aaxis=ax_override, ternary_baxis=ax_override, ternary_caxis=ax_override)
```
<img width="407" alt="Screenshot 2022-11-21 at 14 05 24" src="https://user-images.githubusercontent.com/2678795/203138497-bac419e3-d53a-4cf7-96b3-6f08ef46319f.png">

I haven't looked into how hard it would be to remove those so this gives the exact behavior you want.

**Comment by is95t** [comment]
Ah that's good to know. I was using the line mode to see the points more clearly, however, filling the contours makes the lines on the edge less noticeable. I have then added a scatter over the top using your solution:

`fig = ff.create_ternary_contour(np.array([SiO2, MgO, CaO]), comps['d_num'],
                                pole_labels=['SiO<sub>2', 'MgO', 'CaO'],
                                interp_mode='cartesian',
                                ncontours=10,
                                colorscale='Viridis',
                                showscale=True,
                                width=865, height=600,
                                showmarkers=True
                               )

fig.update_traces(cliponaxis=False)
ax_override = dict(min=0, linewidth=0)
fig.update_layout(ternary_aaxis=ax_override, ternary_baxis=ax_override, ternary_caxis=ax_override)

fig.add_trace(go.Scatterternary({
    'mode': 'markers',
    'a': comps['SiO2'],
    'b': comps['MgO'],
    'c': comps['CaO'],
    'marker': {
        'color': 'black', # 'cornflowerblue',
        'size': 7,
        'line': {'width': 1}
        }
    },
cliponaxis=False,
))

fig.show()` 

Here is the final output which looks great:

![image](https://user-images.githubusercontent.com/95185273/203155384-ea8b5ddc-38b3-403e-a0a8-e13687060be4.png)

I think this is a workable solution, so I'm happy to close this. Thanks for the help and quick responses @alexcjohnson
