### ISSUE TITLE
Hover window gets cropped on top

### ISSUE THREAD

**Issue by q-wertz** [plotly/plotly.py#3967]
Not sure if that belongs here or in [plotly.js](https://github.com/plotly/plotly.js)…

### Summary

When creating a plot with lots of traces and enabling the hover information it gets cropped (at the top).

![image](https://user-images.githubusercontent.com/20948931/203963608-a0bf8e83-18f6-4665-b1c3-9f8724ba8ebc.png)

### Reproducible Code Example

```Python
import plotly.express as px
import numpy as np

x = np.linspace(0.0, 19.0, 20)
y = []
for i in range(10):
    y.append(np.ones(shape=(20))*i)

fig = px.line(x=x, 
              y=y,
              height=300)
fig.update_layout(hovermode="x unified")

fig.show()
```

### Steps To Reproduce

1. Run `python test.py`
2. Hover in the plotly graph

### Expected Behavior

The hover window is an overlay and not cropped.

Moved here from: https://github.com/streamlit/streamlit/issues/5764

**Comment by AaronStiff** [comment]
Not sure if this should be considered a bug, or just a natural result of having so many traces with that much hover information...

But an easy workaround would be to increase `height` to at least `700`.

**Comment by q-wertz** [comment]
I would consider it a bug as it is quite counterintuitive to just crop the hover window on top. 

A nice feature would be if it is would be scrollable.
