### ISSUE TITLE
Heatmap not rendering as expected

### ISSUE THREAD

**Issue by ChrisJaunes** [plotly/plotly.py#3969]
I encountered an unexpected rendering situation when drawing a heat map in jupyter.
Note that in the picture below, there is only one point at 304 and 318, but the rendering covers ([260,313], [316,321]), why is this?
<img width="572" alt="image" src="https://user-images.githubusercontent.com/28571176/204476942-aebe1b80-c93f-4f1d-9c1d-ddbc9b20a100.png">
code：

```python
import pandas as pd
import plotly.graph_objects as go

df = pd.DataFrame([[ 260,  304, 2554],
[ 343,  302, 2823],
[ 334,  296, 2206],
[ 304,  318, 2270],
[ 342,  302, 2813],
[ 240,  305, 2669],
[ 243,  304, 3371],
[ 313,  303, 2264],
[ 355,  313, 2498],
[ 347,  310, 3199],
[ 163,  285, 2767],
[ 165,  286, 3781],
[ 164,  284, 3334],
[ 164,  286, 3567],
[ 165,  283, 2273],
[ 164,  283, 2250],
[ 167,  286, 2552],
[ 165,  287, 2775],
[ 166,  284, 3111],
[ 164,  285, 3766]],
columns=["x","y","z"])
fig=go.Figure()
fig.add_trace(go.Heatmap(
    name='HeatMap',
    x=df["x"],
    y=df["y"],
    z=df["z"],
))
fig.update_layout(height=600, width=600)
fig
```

**Comment by empet** [comment]
You are not  plotting an usual heatmap. Your x and y values are categories.
With a layout defined  like this one:
```
fig.update_layout( plot_bgcolor="rgba(0,0,0, 0)",height=500, width=500,
                  xaxis_type="category", yaxis_type="category" )
```
the heatmap is displayed as you expect.
![heatmap-categ-axes](https://user-images.githubusercontent.com/3627253/204517830-088ce0b9-0014-4d4d-9fb4-956695144edb.png)

**Comment by ChrisJaunes** [comment]
Thanks a lot, I've figured out why this is happening through your answer.

I read the [documentation of graph_objects.Heatmap](https://plotly.github.io/plotly.py-docs/generated/plotly.graph_objects.Heatmap.html). "In the case where z is a 1D list, the x and y coordinates must be provided in x and y respectively to form data triplets." misunderstood me, I thought Z was a 1D representation consistent with 2D, plotted figures are all sequential and equally spaced.

I accomplished my desired effect by creating a 2D matrix. Thank you very much for your answer

> What’s going on here is we take your irregularly spaced x and y values and try to chop up the x and y axes into irregularly spaced grids, with your data points close to the middle of their corresponding boxes. But because of the irregular spacing your data won’t be quite at the middle. So for x=304, the next smaller x is 260, and we draw the boundary halfway between them at 282. The next larger x is 313, so we draw the boundary halfway between at 308.5. Then for y=318, the next largest is 313 so we draw the boundary halfway between at 315.5, and because 318 is the largest y, since we have no other information we draw the outer boundary the same distance away in the other direction, or 320.5. So the bounding box for that brick is [[282, 308.5],[315.5, 320.5]]. In the y direction the data point is at the brick center, but in the x it’s nearer the right side, just because the next larger x is so much closer than the next smaller one.
> 
> Now the question is, what behavior did you have in mind? There are a lot of things you might want here, but without knowing what this data set means it’s hard to recommend one. A scatter chart with z as marker color? A contour plot where we interpolate between all these z values? A 2d histogram where we sum nearby z values?
