### ISSUE TITLE
Plotly.py releases info on GitHub?

### ISSUE THREAD

**Issue by nehalecky** [plotly/plotly.py#397]
Hey plotly team. First, thanks for this amazing piece of software, plotly is grand. :fist: 

I was browsing releases listed here in this GitHub repo, and was surprised to see that the [most recent release](https://github.com/plotly/plotly.py/releases/tag/1.6.12) (1.6.12) doesn't actually match that [available on pipy](https://pypi.python.org/pypi/plotly) (1.9.5 at the time of this writing). 

It seems you've stopped releasing using GitHub, which is fine as we all understand GitHub has its limitations! However, it's a little bit difficult to track what issues are being targeted and fixed with a particular release. IMHO, this is helpful for open source development along with the casual user browsing by to see momentum in tackling any particular effort. 

A few thoughts on this:
- Can we assume that the master HEAD the state of the most current release?
- As we're not using the releases, can we make [the release notes / changeling](https://github.com/plotly/plotly.py/blob/master/CHANGELOG.md) be front and center in the README?
- Is there anyway we can get the versions tagging (at least) synced up with the underlying git repo?

I would be glad to help with these, but wanted to hear thoughts before I dove in. Have a great Friday and thanks! :smile:

**Comment by theengineear** [comment]
Thanks for the note (and for using plotly!), we're attempting to be better about making a release on GH for each new PyPI release.

>Can we assume that the master HEAD the state of the most current release?

Nope, this is not a good assumption.

>As we're not using the releases, can we make the release notes / changeling be front and center in the README?

You should check the `CHANGELOG.md` file, it *should* be up to date. The things in the `Unreleased` section are what's in master but *not yet* on PyPi.
