### ISSUE TITLE
Plotly 5.11.0-pyhd8ed1ab_1 forces downgrade of various python widget packages

### ISSUE THREAD

**Issue by pythonic2020** [plotly/plotly.py#3978]
In a conda env running Python 3.9, the latest plotly build (**5.11.0-pyhd8ed1ab_1**) from conda-forge repo forces the downgrade of several packages related to jupyter widgets:

```
The following packages will be UPDATED:

plotly                                5.11.0-pyhd8ed1ab_0 --> 5.11.0-pyhd8ed1ab_1

The following packages will be DOWNGRADED:

  ipywidgets                             8.0.2-pyhd8ed1ab_1 --> 7.7.2-pyhd8ed1ab_0
  jupyterlab_widgets                     3.0.3-pyhd8ed1ab_0 --> 1.1.1-pyhd8ed1ab_0
  widgetsnbextension                     4.0.3-pyhd8ed1ab_0 --> 3.6.1-pyha770c72_0
```

Is this expected behavior?

**Comment by Alexboiboi** [comment]
Hi @pythonic2020 , this is expected since ipywidgets>=8 is not yet compatible with plotly.

See wip here: https://github.com/plotly/plotly.py/pull/3930

**Comment by pythonic2020** [comment]
Ok, thank you.
