### ISSUE TITLE
px.choropleth inverts polygon fill

### ISSUE THREAD

**Issue by strokovnjaka** [plotly/plotly.py#3979]
I was trying to show some regions with `px.choropleth()`, but most of the regions were colored inverted, i.e. the outside of the polygons were filled (the regions can be found [here](https://raw.githubusercontent.com/stefanb/gurs-rpe/master/data/OB.geojson)).

Here is a minimal example:
```
import geopandas as gpd
import plotly.express as px
import io

gdf = gpd.read_file(io.StringIO("""
{
    "type": "FeatureCollection",
    "name": "polies",
    "features": [{
            "type": "Feature",
            "properties": {
                "name": "poly1"
            },
            "geometry": {
                "type": "Polygon",
                "coordinates": [[
                        [13.9329914, 45.9451589],
                        [13.821011, 45.8507284],
                        [14.1229608, 45.8653449],
                        [13.9761061, 45.928769],
                        [13.9329914, 45.9451589]
                ]]}}]}
"""))
fig = px.choropleth(gdf, geojson=gdf, color="name", locations="name", featureidkey="properties.name")
fig.update_geos(fitbounds="locations", visible=False)
fig.update_layout(margin={"r": 0, "t": 0, "l": 0, "b": 0})
fig.show()
```

The result is

![reg_inverted](https://user-images.githubusercontent.com/15386238/206857151-799bb3d4-cdbd-4860-bd20-4f8dffd0e458.png)
 

If I remove the middle (3rd) point (everything else is the same), the result is correct:

```
import geopandas as gpd
import plotly.express as px
import io

gdf = gpd.read_file(io.StringIO("""
{
    "type": "FeatureCollection",
    "name": "polies",
    "features": [{
            "type": "Feature",
            "properties": {
                "name": "poly1"
            },
            "geometry": {
                "type": "Polygon",
                "coordinates": [[
                        [13.9329914, 45.9451589],
                        [13.821011, 45.8507284],
                        [13.9761061, 45.928769],
                        [13.9329914, 45.9451589]
                ]]}}]}
"""))
fig = px.choropleth(gdf, geojson=gdf, color="name", locations="name", featureidkey="properties.name")
fig.update_geos(fitbounds="locations", visible=False)
fig.update_layout(margin={"r": 0, "t": 0, "l": 0, "b": 0})
fig.show()
```

![reg_regular](https://user-images.githubusercontent.com/15386238/206857252-f2b6ee6b-a105-4bec-911d-49f0776beb00.png)

Note that `px.choropleth_mapbox()` renders the data correctly.

**Comment by strokovnjaka** [comment]
Correcting the geometries orientation fixes the problem,  e.g. with

```
gdf['geometry'] = gdf['geometry'].apply(lambda geo: shapely.geometry.polygon.orient(geo, -1))
```

As I haven't noticed any info regarding geometry orientation in the API docs (or elsewhere), I would suggest either to solve this, or, as a bare minimum, a note added to docs.

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Alternatively, if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
