### ISSUE TITLE
Hoverformat fails to apply when showticklabels=False

### ISSUE THREAD

**Issue by jameszuccollo** [plotly/plotly.py#398]
When setting a `hoverformat` on an axis, the format is not applied unless `showticklabels=True`. For example, the following `hoverformat` silently fails to apply:

````python
from plotly.graph_objs import Scatter, Layout, YAxis, Figure
import plotly.plotly as py

data = [Scatter(x=[1, 2, 3],
                 y=[0.12345, 0.23456, 0.34567])]
layout = Layout(yaxis=YAxis(showticklabels=False,
                            hoverformat=",.2r",))
figure = Figure(data=data, layout=layout)
py.iplot(figure)
````

**Comment by yankev** [comment]
@jameszuccollo So this might be an issue with the javascript backend. I've posted this issue in the `plotly.js` repo: [https://github.com/plotly/plotly.js/issues/261](url).

**Comment by cldougl** [comment]
fixed w/ https://github.com/plotly/plotly.js/pull/267
