### ISSUE TITLE
`add_layout_image` won't work when X-axis's value is timestamp-like

### ISSUE THREAD

**Issue by zifeiYv** [plotly/plotly.py#3982]
`plotly` version: `5.10.0`

I want to change the image position by setting `xref='x'` and `x='2022-12-23'` since my xaxis's values are something like `['2022-12-20', '2022-12-21', ...]`, but it doesn't work. Below is my code:

```python
import plotly.graph_objects as go
import pandas as pd

fig = go.Figure()
# ↓ it shows no difference whether I map timestamp into str
x = pd.date_range(start='2022-12-20', end='2022-12-30').map(lambda i: i.strftime("%Y-%m-%d")).tolist()
fig.add_trace(go.Scatter(x=x, y=list(range(len(x)))))

fig.update_layout(template="plotly_white")
fig.update_xaxes({'tickformat': '%Y-%m-%d', 'dtick': 'D1'})
fig.add_layout_image(dict(
    sizing="stretch",
    source="https://images.plot.ly/language-icons/api-home/python-logo.png",
    xref='x', yref='y',
    x=x[0], y=2,
    yanchor='bottom',
    sizex=0.5, sizey=0.5,
))
fig.show()
```
Set `xref='paper'` could show the image,  which, however is not my preferred(it cannot align image conveniently).

**Comment by empet** [comment]
When you have a date type  xaxis, the  image `sizex` is given in miliseconds.
A  single day has 24*60*60*1000  miliseconds.  Your  image, `"python-logo.png"`,    has the resolution 100x100. By trial and error you can set `sizex` and `sizey` such that to display this image as a square:
```
fig.add_layout_image(dict(
    sizing="stretch",
    source="https://images.plot.ly/language-icons/api-home/python-logo.png",
    xref='x', yref='y',
    x=x[0],
    y=0,
    yanchor='bottom',
    sizex= 3*24*60*60*1000, 
    sizey=5,
))
```
`sizey` depends on your layout `width` and `height`.
 For width=600, height=450 and `sizey=5`
you get:
![bgimage-datexaxis](https://user-images.githubusercontent.com/3627253/207832827-104579ae-95e8-42c8-81e2-01c80db9ca76.png)

but for default width and height (like in your definition), sizey=7 leads to a square background image.
At the first sight you can say that the background image does not start from the date x[0]. It does, but the its original background contains a few pixels, and the leftmost pixels are located at x[0].

**Comment by zifeiYv** [comment]
@empet Wow! Thank you for nice reply and I can show the images correctly  by following your statement.

By the way, I don't really understand why the image sizex is given in miliseconds when xaxis' type is date. It doesn't seem intuitive. I almost googled everywhere and find no documents to explain why.

**Comment by empet** [comment]
We are measuring the distance  between two locations in km, m, cm, mm, while the time distance is measured in years, months, days, hours, minutes, seconds and milisecondes. By Wikipedia [https://en.wikipedia.org/wiki/Millisecond](https://en.wikipedia.org/wiki/Millisecond) milisecond is the  time unit in SI.

**Comment by alexcjohnson** [comment]
> why the image sizex is given in miliseconds when xaxis' type is date

This is just inherited from JavaScript - where internally dates are represented as milliseconds since 1970, so the natural way to represent time deltas is milliseconds.

**Comment by zifeiYv** [comment]
OK, now I understand and thanks again for all of your patient explanation. @empet @alexcjohnson 

This issue should be closed.

**Comment by mmarras** [comment]
> We are measuring the distance between two locations in km, m, cm, mm, while the time distance is measured in years, months, days, hours, minutes, seconds and milisecondes. By Wikipedia https://en.wikipedia.org/wiki/Millisecond milisecond is the time unit in SI.

This is of course wrong or at least highly misleading: the [base SI unit for time](https://en.wikipedia.org/wiki/SI_base_unit) is `second`  and yes therefore millisecond is also a derived SI unit. But there is nothing special in terms of SI with regards to milliseconds vs microseconds or kiloseconds and so on. Thus, SI unit is not the explanation for why one has chosen milliseconds as a base here.
