### ISSUE TITLE
get unknow trace in background

### ISSUE THREAD

**Issue by yinssl** [plotly/plotly.py#4001]
hi everyone, i get some bug in plotly , see the picure, get unknow trace, but it seen like in backgraoud. I use dash in django.
![捕获](https://user-images.githubusercontent.com/48947900/209638115-3e99be4f-bb8c-4000-91b6-5315f0a11059.PNG)

**Comment by alexcjohnson** [comment]
Maybe the same as https://github.com/plotly/plotly.js/issues/6407? If that's it you should be able to downgrade to plotly.py v5.10.0 or before until we fix the underlying problem.

**Comment by alexcjohnson** [comment]
I'm going to assume https://github.com/plotly/plotly.js/pull/6429 fixes this, but if you're still seeing it with plotly.py v5.13 please reopen or make a new issue.
