### ISSUE TITLE
ImportError: Please install ipywidgets>=7.0.0 to use the FigureWidget class

### ISSUE THREAD

**Issue by tfmark** [plotly/plotly.py#4020]
Off the back of https://github.com/plotly/plotly.py/issues/3686 being merged/released I wanted to revisit jupyterlite + ipywidgets + plotly, but I'm immediately failing.

Using the jupyterlite deployed [here](https://jupyterlite.readthedocs.io/en/latest/_static/lab/index.html) with a simple example, I get this error (which suggests ipywidgets is not installed):

![image](https://user-images.githubusercontent.com/80677094/212690556-3f8ffa1c-7ee0-41d1-a363-a0b84c891519.png)

Note that this example is taken from the issue above.

```py
import micropip

await micropip.install("ipywidgets")
await micropip.install("plotly")

###

from ipywidgets import widgets

import plotly.graph_objects as go

widgets.VBox([
    widgets.HTML("<p>Start</p>"),
    go.FigureWidget(go.Scatter(x=[1, 2, 3], y=[1, 4, 9])),
    widgets.HTML("<p>End</p>"),
])
```

I feel like I must be doing something wrong, but don't understand what.

**Comment by nicolaskruchten** [comment]
I'm not sure what the status is of our widget with JupyterLite... has it ever worked? I.e. with Plotly 5.11 and ipywidgets 7.7? I'm not sure how JupyterLite handles federated extensions like ours :)

**Comment by jtpio** [comment]
> I'm not sure what the status is of our widget with JupyterLite... has it ever worked? I.e. with Plotly 5.11 and ipywidgets 7.7? I'm not sure how JupyterLite handles federated extensions like ours :)

Yes it worked at some point: https://github.com/jupyterlite/jupyterlite/issues/110#issuecomment-866077035/

But currently seems broken: https://github.com/jupyterlite/jupyterlite/pull/950

JupyterLite handles federated extensions the same way, and I don't think there is anything special to Plotly happening somewhere.

Not sure if a later version of `plotly` changed something, maybe how the renderers are detected.

**Comment by nicolaskruchten** [comment]
so `fig.show()` doesn't use our ipywidget pipeline... are you sure that `FigureWidget` renderered in the past or just `Figure`?

**Comment by jtpio** [comment]
Yes that was the case in these PRs, and for quite a while after:

- https://github.com/jupyterlite/jupyterlite/pull/129
- https://github.com/jupyterlite/jupyterlite/pull/220#issuecomment-874880142 

Just tried with `FigureWidget` but getting the following:

```
Uncaught ReferenceError: require is not defined
```

![image](https://user-images.githubusercontent.com/591645/229130499-991047c5-b9c5-49da-8a8a-44a94faf3759.png)


A guess could be it tries to load the assets as if it was in the classic notebook. But `requirejs` is not available in lab / lite.

**Comment by nicolaskruchten** [comment]
I'm not sure what's happening in the screenshot above, but `fig.show()` always invokes our mime-type renderer, never our widget pathway, even on the `FigureWidget` class (confusing :( ). The only way to actually use our widget is to have a `FigureWidget` instance as the output of a cell, which is not what `fig.show()` does.

**Comment by jtpio** [comment]
Right, but the plotly mimetype used to be rendered fine before.

For a while we had to set `os.environ['PLOTLY_RENDERER'] = 'jupyterlab'` so it renders in JupyterLite. Although with a later version of `plotly` it was not necessary anymore.

Maybe we can try to find which version of `plotly`triggers the `require` error and see if there is any related change.

**Comment by nicolaskruchten** [comment]
Yeah, we should separately find out why the mimetype renderer is failing. I'm still unsure whether the widget ever worked though: do you remember ever seeing a cell containing just `plotly.graph_objects.FigureWidget()` render an output? In addition to a cell equivalent to just `plotly.graph_objects.Figure().show()`?

**Comment by jtpio** [comment]
> do you remember ever seeing a cell containing just `plotly.graph_objects.FigureWidget()` render an output? In addition to a cell equivalent to just `plotly.graph_objects.Figure().show()`?

Not sure, but can do some digging. Happy to track that in a new issue if it is more convenient.

**Comment by jtpio** [comment]
> Happy to track that in a new issue if it is more convenient.

Opened https://github.com/plotly/plotly.py/issues/4143 to continue looking into this.

**Comment by pioneerRick** [comment]
The problem is still live, my code`agent.train(n_steps=200, n_episodes=2, save_path="agents/")` occur the problem below: ` Please install ipywidgets>=7.0.0 to use the FigureWidget class`.

I try many methods to solve this proble, including upgrade my pip version、upgrade ipywidges、re-install in conda command.

If any process , I'll show my solve plan
