### ISSUE TITLE
Can't use `color` in go.Histogram

### ISSUE THREAD

**Issue by fabiopedrosa** [plotly/plotly.py#4039]
Why can I use `color` to create different categories in the express version of histogram: `px.histogram(x=x, y=y, color=c)` 

But can't on the class version?
`go.Figure(data=go.Histogram(x=x, y=y, color=c)`

I get a:
`ValueError: Invalid property specified for object of type plotly.graph_objs.Histogram: 'color'`

**Comment by nicolaskruchten** [comment]
This type of limitation in `graph_objects` is exactly why `express` exists actually... Each `go.Histogram` trace can only be one color, so when `px` sees `histogram(..., color=...)` it does a `groupby` on your data and iterates and creates one trace per group.
