### ISSUE TITLE
Horizontal Legend Stays Vertical

### ISSUE THREAD

**Issue by exeLocates** [plotly/plotly.py#4042]
Hello, I wasn't able to find a current closed or open issue with my problem so here it is:

I'm trying to set my legend to horizontal over my candlestick but it keeps staying vertical, I've changed the legend names to be very short "1" "2" "3" etc to see if its a name issue and it still stays vertical.

this is the code I'm using: 

> fig.update_layout(legend=dict(orientation="h", yanchor="top", y = 1.03, xanchor="left", x = 0.01))

Can anyone point me in the right direction?

**Comment by AaronStiff** [comment]
Could you provide a simplified version of the entire code, including the code for making the candlestick chart?

**Comment by exeLocates** [comment]
```
the candlesticks are loaded from data into arrays and passed into the add trace
# make plot for graphs
fig = make_subplots(
    rows=2,
    cols=2,
    shared_xaxes="columns",
    shared_yaxes=False,
    column_width=[0.8, 0.2],
    row_heights=[0.8, 0.2],
    horizontal_spacing=0.3,
    vertical_spacing=float(0.1),
)


#add candlesticks
fig.add_trace(
    go.Candlestick(
        x= time_data,
        open= open_data,
        high= high_data,
        low= low_data,
        close= close_data,
        showlegend= False,
        legendgroup= "Candlesticks"
    ),
    row=1,
    col=1
    )


#add volume chart 
fig.add_trace(
go.Bar(
    x=time_data,
    y=volume_data,
    showlegend=False,
    marker = dict(color=volume_colors),
    marker_line_width=0,
    opacity=0.95,
    name="Volume",
    hoverinfo="x+y",
),
col=1,
row=2,
)
```

**Comment by AaronStiff** [comment]
Hm... the legend is horizontal for me. I had to set `showlegend` to `True` of course in your example.

What versions of `plotly.py` and `plotly.js` are you on? Also, perhaps a screenshot of the issue would be helpful.

**Comment by exeLocates** [comment]
Plotly 5.11 Python 3.11

I set showlegend to True in the candlesticks and it is horizontal for me now too somehow, I don't want the candlesticks on the legend however.  I have 4 scatter traces I want on the legend only, is it not possible to just have those?

**Comment by gvwilson** [comment]
Hi - we are trying to tidy up the stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. Alternatively, if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
