### ISSUE TITLE
Trace fragments in pdf given tickvals and margin 

### ISSUE THREAD

**Issue by MarekWadinger** [plotly/plotly.py#4043]
When I visualize my data with sampling T=2min and NaNs I get trace fragments in the saved figure.
Everything's normal in HTML format or when visualized in Jupyter notebook. Any other saved format produces the fragments.
Traced the problem down to a combination of 2 layout attributes: xaxis_tickvals and margin.
The minimum example is below. Use this file [bug.csv](https://github.com/plotly/plotly.py/files/10543255/bug.csv) to replicate the behavior. 

```python
import pandas as pd
import plotly.graph_objects as go

df = pd.read_csv("bug.csv", index_col=0)

fig = go.Figure()
fig.update_layout(
    xaxis_tickvals=["2022-03-03 00:00:00+00:00", "2022-03-04 00:00:00+00:00"],
    margin=dict(b=10),
)

fig.add_trace(
    go.Scatter(
        x=df.index, y=df[col]
        )
    )

fig.write_image("bug.pdf")
```

Thank you for helping me with this problem

Library versions:
- kaleido                  0.2.1
- pandas                  1.4.4
- plotly                     5.11.0

![bug](https://user-images.githubusercontent.com/50716630/215677753-f4eca061-e85e-41cc-8940-5f750ff913db.png)

**Comment by AaronStiff** [comment]
Could you please provide a screenshot of the trace fragments (the link to the .csv file doesn't work), as well as the version of `plotly.py` and `plotly.js` you're using?

**Comment by MarekWadinger** [comment]
> Could you please provide a screenshot of the trace fragments (the link to the .csv file doesn't work), as well as the version of `plotly.py` and `plotly.js` you're using?

Updated original post

**Comment by nicolaskruchten** [comment]
Can you confirm that this happens with v5.13?

**Comment by MarekWadinger** [comment]
Yes this version has the bug fixed, thank u @nicolaskruchten  ^^
