### ISSUE TITLE
Axes range behavior changes when overlaying scatter on heatmap

### ISSUE THREAD

**Issue by tomas16** [plotly/plotly.py#4049]
**Description**

With `px.imshow`, or using `go.Heatmap` and some manual axes manipulation, I can plot an image with aspect ratio = 1 and the axes range exactly matching the size of the image. As soon as I try to overlay a scatter plot over the image, the range of one of the axes isn't respected.

Actually, this may be a more general problem with a scatter plot. I've never been able to figure out how to exactly control the axes range.

**Example**

```python
import plotly.graph_objects as go
import numpy as np

np.random.seed(100)

# create image of given size
imsz = (64, 128)
img = np.random.rand(*imsz)

# -0.5 because (0, 0) is center of top-left pixel
range_x = np.array([0, imsz[1]]) - 0.5
range_y = np.array([0, imsz[0]]) - 0.5

# create data for scatter plot
num_pts = 30
xy = np.random.rand(num_pts, 2) * imsz[::-1] - 0.5

fig = go.Figure()
fig.add_traces([
    go.Heatmap(z=img),
    go.Scatter(x=xy[:, 0], y=xy[:, 1], mode='markers', marker_symbol='cross', marker_color='#00ff00')
])
fig.update_layout(
    xaxis=dict(anchor='y', range=range_x, constrain='domain'),
    yaxis=dict(anchor='x', scaleanchor='x', scaleratio=1, range=range_y, autorange='reversed', constrain='domain'),
    autosize=False
)
```

Using only heatmap:

![newplot-9](https://user-images.githubusercontent.com/8531909/216187121-e3b4568a-b74a-4e4d-b6c6-383ec76b3247.png)

Using both heatmap and scatter:

![newplot-8](https://user-images.githubusercontent.com/8531909/216187190-1a0d1ad9-0d97-41e9-8f68-8a0c7c82f89f.png)

Using scatter only:

![newplot-10](https://user-images.githubusercontent.com/8531909/216187222-a6d88364-4a48-434d-981a-871b9d81bee1.png)

**Versions**
* plotly = 5.13.0
* python = 3.7.15

**Comment by AaronStiff** [comment]
Somehow `autorange='reversed'` is messing things up. Without it, the ranges are respected.

**Comment by alexcjohnson** [comment]
If you use `autorange` (and it’s not `False`) any `range` you specify will be ignored. But you should be able to get the same result with `range=[max, min]`

**Comment by tomas16** [comment]
I can confirm that works, thanks!

I think you can close this. (Unless you want to use it to update documentation)
