### ISSUE TITLE
scattergl function doesn't handle pandas.Series correctly

### ISSUE THREAD

**Issue by ellayunyun** [plotly/plotly.py#405]
``` python
x_axis = pandas.Series([pandas.to_datetime(date) for date in x_axis])
trace = Scattergl(x=x_axis,y=y,mode='markers+lines',name=varName)
# this plots gives different plots comparing to 
trace = Scatter(x=x_axis,y=y,mode='markers+lines',name=varName)
```

I have taken a close look at the plot, it seems that scattergl didn't handle the x_axis correctly.... quite some points are where they should not be.
An example can be seen in the attached image
![report](https://cloud.githubusercontent.com/assets/8613222/13071996/423307d0-d497-11e5-8202-1bfcc3f6ec1e.png)

**Comment by yankev** [comment]
@ellayunyun Hi, can you possibly share your data or provide a link to your plots?

**Comment by ellayunyun** [comment]
see https://plot.ly/~ellayunyun/3/raw-data/

**Comment by jonmmease** [comment]
Closing as I believe this is no longer a problem in recent versions of plotly/scattergl.  Feel free to open a new issue against version 3 with a reproducible example if this is not the case.
