### ISSUE TITLE
Plotly figures are cropped in JupyterLab 4 (currently in preview)

### ISSUE THREAD

**Issue by fcollonval** [plotly/plotly.py#4066]
That rule will not have the proper effect in the upcoming major JupyterLab:

https://github.com/plotly/plotly.py/blob/92ce5bce770dc5390bda0f44a9b6b033d4f2c39e/packages/javascript/jupyterlab-plotly/style/index.css#L26

You should set `height` directly. See https://github.com/jupyterlab/jupyterlab/issues/13227 for more details.

**Comment by alexcjohnson** [comment]
And now 4.0.0 is released - thanks for the heads up @fcollonval @jtpio, we'll get this addressed shortly.

**Comment by alexcjohnson** [comment]
In the meantime, explicitly setting the figure height works: `fig.layout.height = 360` to match the previous default.

**Comment by alexcjohnson** [comment]
Closed by #4227

**Comment by jtpio** [comment]
Nice, thanks!
