### ISSUE TITLE
How to make the marker's text on a px.scatter_mapbox() always visible?

### ISSUE THREAD

**Issue by jakhon77** [plotly/plotly.py#4067]
![github](https://user-images.githubusercontent.com/65193742/220964955-890d2ad8-be48-4b75-8f0c-f85979e49904.JPG)
Hello,

I am using px.scatter_mapbox() to plot my locations. When my locations are close to each other, the text on my markers are disappearing when I zoom out. I did try ```textposition``` property of ```update_traces``` but it didn't help resolve my issue completely. There were still some markers without text values. 
 Is there a way of making the texts static so they are always visible even if I zoom out, even if they overlap? Thanks so much in advance!

**Comment by AaronStiff** [comment]
Hi @jakhon77. Could you move your description of the issue into the description field and add a title in its place? Also, if you could provide a simplified version of your code, that will help us understand what you are asking. Thanks!

**Comment by jakhon77** [comment]
Hi @AaronStiff,
I'm sorry, but I don't see a description section there.
![123](https://user-images.githubusercontent.com/65193742/219800670-c53af3ab-c226-42df-8a39-efcbe1e990ab.JPG)

**Comment by AaronStiff** [comment]
Currently your description is "Thanks for your interest...". If you click the three dots in the top right corner, there should be an option to "Edit".

**Comment by empet** [comment]
To get displayed the text, via `go.Scattergeo`, , just add the attribute `text`, as a list of strings, and eventually give each string position:
```
import plotly.graph_objects as go
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/2011_february_us_airport_traffic.csv')

fig = go.Figure(data=go.Scattergeo(
        lon = df['long'][:5],
        lat = df['lat'][:5],
        text = [f'Text{k}' for k in range(1,6)],
        mode = 'markers+text',
        textposition='bottom right'
        ))

fig.update_layout(
        title_text = 'Scattergeo with markers and text', title_x=0.5,
        geo_scope='usa', font_color="black")
```

**Comment by jakhon77** [comment]
Hello @AaronStiff and @empet,
Sorry! I have updated my question with more clarification. Can someone please take a look at it? Many thanks for considering my request!

**Comment by AaronStiff** [comment]
Thanks @jakhon77. That helps a lot!

Currently it look like there's a duplicate issue in the `plotly.js` repo: https://github.com/plotly/plotly.js/issues/5145.

Also, this is a feature which would have to be implemented in `plotly.js`, so is it okay if I go ahead and close this?
