### ISSUE TITLE
Disappearing bars in horizontal barplot

### ISSUE THREAD

**Issue by ale-xyt** [plotly/plotly.py#4073]
I am trying to create a horizontal bar chart with two x-axes. Adding the second x-axis cause all the bars corresponding to the first x-axis to disappear. Problem was not observed in case of vertical bar plot.

Code reproducing the problem (blue bars disappeared):

```
import plotly.graph_objects as go

fig = go.Figure(
    data=[
        go.Bar(
            name="data 1",
            x=[11, 12, 13],
            y=["a", "b", "c"],
            xaxis="x",
            offsetgroup=1,
            orientation="h",
        ),
        go.Bar(
            name="data 2",
            x=[1, 2, 3],
            y=["A", "B", "C"],
            xaxis="x2", # If you comment out this line, blue bars will be shown, but there will be no second x-axis
            offsetgroup=2,
            orientation="h",
        ),
    ],
    layout={
        "xaxis": {"title": "1st x-axis"},
        "xaxis2": {"title": "2nd x-axis", "side": "top"},
    },
)
fig.update_layout(
    barmode="group",
)
fig.show()
```

![plotly_bug](https://user-images.githubusercontent.com/120449451/220288652-cb1c6753-72d2-4d36-a687-ab1524f1e116.png)

**Comment by empet** [comment]
To get displayed  the  blue bars, just add one more attribute to `xaxis2`, namely `"overlaying": "x"`:
```
 layout={
        "xaxis": {"title": "1st x-axis"},
        "xaxis2": {"title": "2nd x-axis", "side": "top", "overlaying": "x"},
    }
```
For more details call/display  `help(go.layout.YAxis.overlaying)`

**Comment by ale-xyt** [comment]
@empet Thank you, it is working perfectly. I am closing the issue.
