### ISSUE TITLE
Annotations: arrowhead is ignored when using arrowside="start"

### ISSUE THREAD

**Issue by kvanderwijst** [plotly/plotly.py#4074]
The arrowhead cannot be changed when using arrowside="start". It works with arrowside="end" and arrowside="start+end" though.

```
from plotly.subplots import make_subplots

fig = make_subplots()

fig.add_annotation(
    showarrow=True,
    arrowhead=6,
    arrowside="start"
)
```

shows:
![image](https://user-images.githubusercontent.com/863938/220372498-e41aec36-20c3-4839-97f6-c2ca78c056c8.png)

(I'm using Plotly version 5.13.0)

**Comment by AaronStiff** [comment]
Hi @kvanderwijst. `arrowhead` sets the style of the "end" of the arrow. To change the style of the "start" of the arrow, use `startarrowhead`

**Comment by kvanderwijst** [comment]
Hi Aaron, thanks a lot! Oops, my mistake. I looked for "arrowstarthead" but not "startarrowhead".

**Comment by AaronStiff** [comment]
No problem!
