### ISSUE TITLE
create_scatterplotmatrix  subplots not connected to legend

### ISSUE THREAD

**Issue by sorenwacker** [plotly/plotly.py#4088]
Hi, is there a better way to create a pairplot? 

The problem with `[plotly.figure_factory](https://plotly.com/python-api-reference/generated/plotly.figure_factory.html#module-plotly.figure_factory).create_scatterplotmatrix[¶](https://plotly.com/python-api-reference/generated/plotly.figure_factory.create_scatterplotmatrix.html#plotly-figure-factory-create-scatterplotmatrix)` is that the subplots are not connected to legend.

![image](https://user-images.githubusercontent.com/3391614/222314369-eb0ae446-dc89-4f52-847d-184c139d7e4d.png)

As you can see in the plot only one subplot is reactin to the selection in the legend.

**Comment by AaronStiff** [comment]
Hi @sorenwacker. Could you provide a reproducible example?

**Comment by sorenwacker** [comment]
import pandas as pd
import numpy as np

from plotly.figure_factory import create_scatterplotmatrix

df = pd.DataFrame(np.random.random(size=(10,3)))

df['Label'] = 'A'

create_scatterplotmatrix(df, diag='box',  index='Label')

**Comment by nicolaskruchten** [comment]
We're not really maintaining the `figure_factory` module these days, and for scatterplot matrices we generally recommend folks use the `splom` trace or `px.scatter_matrix()` but neither of those makes it easy to put something like box-plots on the diagonal.

Clearly this figure-factory doesn't do a great job linking together the multiple traces into the same legend-group to make it such that clicking on the legend applies to all subplots, but here is a little recipe that does a little surgery on the figure to place all the traces into a legendgroup with all the other traces with the same marker color...

```python
import pandas as pd
import numpy as np

from plotly.figure_factory import create_scatterplotmatrix

df = pd.DataFrame(np.random.random(size=(10,3)))

df['Label'] = ['a']*5 + ['b']*5

fig = create_scatterplotmatrix(df, diag='box',  index='Label')

# set the legendgroup equal to the marker color
for t in fig.data:
    t.legendgroup=t.marker.color
```

**Comment by sorenwacker** [comment]
`px.scatter_matrix` has the issue with the diagonals. They contain x-y plots using the same variable. So, they cary no information. if the diagnonals could be changed to densities or boxplots, or at least could be removed from the plot alltogether, that would be great.

**Comment by sorenwacker** [comment]
Perfect! Amazing!!
