### ISSUE TITLE
hoverinfo='text' fails in plotly.offline when hovermode='x'

### ISSUE THREAD

**Issue by jameszuccollo** [plotly/plotly.py#409]
This fails to display the hovertext.
````python
import plotly.offline as po
from plotly.graph_objs import *

po.init_notebook_mode()

traces = Scatter(x=[0, 1, 2, 3], 
                 y=[2, 3, 4, 5], 
                 text='text',
                 hoverinfo='text')
fig = Figure(data=Data([traces]), 
             layout=Layout(hovermode='x'))
po.iplot(fig)
````
If `hovermode` is changed to `y` or `closest`, the hovertext shows up again. Plotting through the plotly server or in [plotly.js](http://codepen.io/anon/pen/wMbGMg) does not generate the error. However, since `hovermode='x'` is the default, this crops up every time `hoverinfo='text'`.

**Comment by etpinard** [comment]
What version of plotly.py are you using?

Updating to the latest should resolve your problems.

**Comment by jameszuccollo** [comment]
No change, sorry. I'm on 

 - plotly 1.9.5
 - jupyter 1.0.0
 - python 3.5.1

Basically, the latest available through conda, or pypi for plotly. Would I need to pull the latest source from github to get the bugfix for this?

**Comment by cldougl** [comment]
Sorry about that @jameszuccollo - plotly.offline was using an older version of plotly.js so as soon as that's updated https://github.com/plotly/plotly.py/pull/411 you can update to plotly 1.9.6 and `hoverinfo='text'` will work.
Thanks for letting us know!

**Comment by jameszuccollo** [comment]
Great, thanks so much @cldougl, looking forward to it.

**Comment by cldougl** [comment]
All set @jameszuccollo 
`pip install plotly --upgrade` and you should get v 1.9.6 

I'm going to close this issue - but let us know if you have any other problems!
