### ISSUE TITLE
scattermode="group" not working

### ISSUE THREAD

**Issue by theopavlove** [plotly/plotly.py#4094]
Hi. The `scattermode="group"` parameter does not work for `px.scatter` both in 5.12 and 5.13 versions. Also tried python versions 3.10 and 3.11.

Below is the [example from the documentation](https://plotly.com/python/line-and-scatter/#grouped-scatter-points), which is not working as intended on my end.

<img width="839" alt="image" src="https://user-images.githubusercontent.com/19343834/223426067-82fd9edd-6bf9-44b4-b843-aae55b46a49c.png">

**Comment by nicolaskruchten** [comment]
Can you tell us which environment you're running this in? VSCode or Collab or...? I don't recognize it offhand :) Also, if you mouse over the logo that appears in the top-right of the figure when the cursor is over the figure, what is the Plotly.js version number listed there?

**Comment by theopavlove** [comment]
> Can you tell us which environment you're running this in? VSCode or Collab or...? I don't recognize it offhand :) Also, if you mouse over the logo that appears in the top-right of the figure when the cursor is over the figure, what is the Plotly.js version number listed there?

Yep, this is VSCode 1.76.0. The Plotly.js version is 2.13.3.

**Comment by nicolaskruchten** [comment]
OK, so the problem there is that VSCode loads its own version of Plotly.js, not the one that ships with Plotly.py, and their version is behind (we're at 2.18 now). You'd need to file a bug report with the VSCode Python/Jupyter team to get them to upgrade again :)

**Comment by theopavlove** [comment]
> OK, so the problem there is that VSCode loads its own version of Plotly.js, not the one that ships with Plotly.py, and their version is behind (we're at 2.18 now). You'd need to file a bug report with the VSCode Python/Jupyter team to get them to upgrade again :)

Nice. Okay, will do. Thanks you for the quick response)
