### ISSUE TITLE
Gibberish / malformed / strange negative y-axis values 

### ISSUE THREAD

**Issue by valankar** [plotly/plotly.py#4118]
```python
#!/usr/bin/env python3
"""Test negative bug."""

from plotly.subplots import make_subplots

fig = make_subplots(rows=1, cols=1)
fig.add_bar(x=[1, 2, 3], y=[-4, 5, -6], row=1, col=1)
fig.update_layout(height=400, width=500, showlegend=True)

with open('web/negative.html', 'w', encoding='utf-8') as index_file:
    index_file.write(fig.to_html(full_html=False))
```

This results in:

![neg](https://user-images.githubusercontent.com/31250800/226539050-24bbeaa0-32f7-4d76-b6f8-5048d4021f75.jpg)

When I change to `full_html=True`, it works properly:

![pos](https://user-images.githubusercontent.com/31250800/226539122-1e677043-725b-41fd-95ea-fd5f68116eee.jpg)

This seems to be a recent bug because it worked fine before I upgraded Plotly. I’m using this version from conda-forge:

`plotly 5.13.1 pyhd8ed1ab_0 conda-forge`

More details on this issue:

https://community.plotly.com/t/gibberish-malformed-negative-y-axis-values-in-plotly-charts-in-python/71924/1

**Comment by AaronStiff** [comment]
@alexcjohnson is this related to the changes to `write_html` made in `5.13.0` (#4019) or this something different?

**Comment by valankar** [comment]
It seems like this is fixed now?

**Comment by 5j9** [comment]
I have the same issue with plotly.js v2.25.2.
![image](https://github.com/plotly/plotly.py/assets/1055747/bb2df4d1-8d13-4b0c-840e-b70115a2e171)

**Comment by RomFR57** [comment]
It worked for me when i added this line to the html file : 

`<meta charset="utf-8">`

Python code :
```
import plotly.offline as offline

template = """
<meta charset="utf-8">
<head>
<body style="background-color:#111111;">
</head>
<body>
{plot_div:s}
</body>""".format(plot_div=offline.plot(fig, config=config, output_type='div'))
with open('fig.html', 'w', encoding="utf-8") as fp:
    fp.write(template)
```

**Comment by Coding-with-Adam** [comment]
Thanks for the advice, @RomFR57 .
This seems to be fixed to me as well. I also tried the code provided by the original poster and it works. 

Closing this issue for now. If we rediscover a bug, I can reopen.
