### ISSUE TITLE
Feature request - dual renderer

### ISSUE THREAD

**Issue by KaareZ** [plotly/plotly.py#4121]
# The problem

Whenever you have an interactive figure in a Jupyter notebook, the plot will not show if notebook is exported to pdf using nbconvert or if notebook is uploaded to an environment such as Github.

This can be solved by inserting `pio.renderers.default = "png"`, and then execute all cells again. But then interactivity is lost...

It's undesirable having to switch the default renderer back and forth all the time. 

# Partial solution

A partial solution is to render everything twice:

```Python
fig.show(renderer='png')
fig.show()
```

Then notebooks on Github or exported to pdf, will appear with static rendered figures, but in an interactive environment everything will appear twice. This, is obviously not desirable either, and causes bloat.

# Proposal

It would be nice if one could display a figure with something like this:

```Python
fig.show(renderer=['plotly_mimetype', 'png'])
```

I'm not fully into how Jupyter cell-output works, and what is possible, but I could imagine it being something like this:

Plotly would either:
- Somehow render the interactive figure on top of the static figure cell-output.
- Or, render in separate cell-outputs, but have the interactive figure hide the static figure.

As said, I don't know if this is possible, or maybe this request is not possible within plotly, but should be posted on IPython/Jupyter.

**Comment by nicolaskruchten** [comment]
Have you tried the existing Multiple Renderers option and it doesn't work for you? https://plotly.com/python/renderers/#multiple-renderers

**Comment by KaareZ** [comment]
> Have you tried the existing Multiple Renderers option and it doesn't work for you? https://plotly.com/python/renderers/#multiple-renderers

I don't know how I overlooked that. Pretty much what I asked for. Sorry for the inconvenience!

**Comment by nicolaskruchten** [comment]
Bo problem! Does it indeed do what you want in your context? It was meant to at the time we built it but sometimes these things break as parts of the ecosystem evolve...

**Comment by KaareZ** [comment]
Yes it does, thank you.

I put
```Python
pio.renderers.default = "plotly_mimetype+png"
```
in the init-cell in the top of the notebook, and every figure appears interactive in VS-Code, and static on Github and nbconvert.
Everything seems to work as expected :)
