### ISSUE TITLE
plotly-express fig.update_traces(root_color="black") has no effect

### ISSUE THREAD

**Issue by ouryperd** [plotly/plotly.py#4131]
Graph renders with default charcoal root colour irrespective of colour set in update_traces(root_color='some color')
![stonks_plotly1](https://user-images.githubusercontent.com/29674819/228482509-08d741b2-bd32-4a19-a103-1aedd4b63df8.png)

**Comment by AaronStiff** [comment]
Hi @ouryperd. [As per the docs](https://plotly.com/python/reference/treemap/#treemap-root-color), setting `root_color` has no effect when using a colorscale.

**Comment by ouryperd** [comment]
Ahh, I missed that. Thank you.
