### ISSUE TITLE
adding symbol causes line to disappear in polar plot

### ISSUE THREAD

**Issue by ziyanwu10** [plotly/plotly.py#4167]
Hi, I am using px.line_polar to make my polar plots. I try to set symbol=True to assign markers different shapes while I find the line will disappear if I do so. 

The code is shown below.

import pandas as pd
import plotly.express as px

d = {'col1':[1,2,3,4],
     'col2':['a','b','c','d'],
     'col3':['x1','x2','x3','x4']}
df=pd.DataFrame(data=d, index=[0,1,2,3])
df

fig_without_symbol = px.line_polar(df, r="col1", theta="col2",
                                   markers=True, 
                                   line_close=True,)
fig_without_symbol.show()
![newplot-2](https://user-images.githubusercontent.com/91446712/233198709-f0b09ecf-23b9-4dc6-b86b-5683c2e47fcf.png)

fig_with_symbol = px.line_polar(df, r="col1", theta="col2",
                                   markers=True, 
                                   symbol='col3',
                                   line_close=True,)
fig_with_symbol.show()
![newplot](https://user-images.githubusercontent.com/91446712/233198720-9ba78cd7-8899-41bc-b84a-e3c8b8b88b6d.png)

**Comment by nicolaskruchten** [comment]
PX creates one line per symbol, and in the dataset above you only have one point per symbol, so there is nothing to connect up with lines.

**Comment by ziyanwu10** [comment]
Thanks so much for your answer!
