### ISSUE TITLE
Feature request: Double box plot

### ISSUE THREAD

**Issue by hrushikesh-s** [plotly/plotly.py#4169]
The current implementation of the Box plot in plotly.express.box and plotly.graph_objects.plot only allows for vertical or horizontal plotting, but not both simultaneously. I'd like to plot walltimes on the x-axis against algorithm performance on the y-axis for different algorithms. Additional context and inspiration for this feature can be found on the referenced [website](https://tomizonor.wordpress.com/2013/03/15/double-box-plot/).

Example of a double box plot generated using the R package - **boxplotdbl**:
![image](https://user-images.githubusercontent.com/111614145/233445143-523a4cec-1b69-419b-a02a-e2c71b61a24f.png)

**Comment by alexcjohnson** [comment]
That's interesting, I'd never seen that before. The outliers look funny though, they're not just "all the data points outside the rectangle defined by the fence bars" which is what I might have expected, rather they appear to be "all the outliers as calculated for each 1D box plot, drawn at the median of the other dimension."

There are other ways to summarize 2D distributions that give some information about the correlation between x and y, for example https://datavizcatalogue.com/blog/multidimensional-boxplot-variations/ and  https://www.thaiscience.info/Journals/Article/SONG/10986951.pdf

What you've drawn above could be created today as a combination of multiple traces - it would be fairly clunky and tricky to get the hover to show the kind of info you want, but I think it would be doable. If there was enough interest (particularly if someone wanted to contribute a PR) we could consider making a new plotly.js trace type for this, just be aware that that's a fairly big lift.

**Comment by hrushikesh-s** [comment]
Thanks @alexcjohnson!
