### ISSUE TITLE
Label aliases does not work at MacOS

### ISSUE THREAD

**Issue by MorozovG** [plotly/plotly.py#4173]
The example provided in the documentation for Label Aliases does not work as expected at MacOS.
```
import plotly.express as px
import pandas as pd

df = px.data.tips()
df = df[df.day.isin(['Sat', 'Sun'])].groupby(by='day', as_index=False).sum(numeric_only=True)

fig = px.bar(df, x="day", y="total_bill")
fig.update_xaxes(labelalias=dict(Sat="Saturday", Sun="Sunday"))

fig.show()
```
This is how it should look like:
![image](https://user-images.githubusercontent.com/10847969/233835748-64f2e0ac-56c7-48e2-83e1-9d73998d842c.png)
And what it looks like when I run the code:
<img width="1368" alt="image" src="https://user-images.githubusercontent.com/10847969/233835940-4c7e3ec2-ee5b-4f93-9222-9a31ab5b4a69.png">
Plotly version - 5.14.1. Python 3.11.3

**Comment by joseabautista** [comment]
I have this same problem.

Tested on a MacOS Ventura 13.3.1 with an M1 chip, both on a Jupyter notebook and through Plotly.js (integrated with Dash). Both Python and JS versions of Plotly are the latest available (5.14.1 for Python, and 2.21 for JS). Python version is 3.10.8.

**Comment by alexcjohnson** [comment]
Works for me, in Jupyter on a Mac, Py3.10. Note that the `plotly.js` version that's currently included in `plotly.py` is `2.20.0` but that's sufficient to support `labelalias`:
<img width="318" alt="Screenshot 2023-04-26 at 09 45 21" src="https://user-images.githubusercontent.com/2678795/234597145-b3b371a8-9b1e-4463-b559-14197fc145b0.png">
<img width="264" alt="Screenshot 2023-04-26 at 09 54 10" src="https://user-images.githubusercontent.com/2678795/234598390-412a5635-e5e6-421a-a9f3-3ed2f79ab9c6.png">


I know it's frustratingly unclear which version of a package you'll load in Jupyter, can you confirm that you indeed have the latest?

**Comment by MorozovG** [comment]
Yes. The problem was in vscode. It uses an old version of plotly.js. This is what helped:
```
import plotly.io as pio
pio.renderers.default = 'notebook'
```
https://github.com/plotly/plotly.py/issues/3488#issuecomment-980001758
https://github.com/microsoft/vscode-jupyter/issues/8373

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
