### ISSUE TITLE
px.histogram(log_x=True) doesn't work

### ISSUE THREAD

**Issue by FlorinAndrei** [plotly/plotly.py#4176]
Dataset:

[train.csv](https://github.com/plotly/plotly.py/files/11336631/train.csv)

Code:

```python
import numpy as np
import pandas as pd
import plotly.express as px

train_df = pd.read_csv("train.csv")

px.histogram(
    train_df[train_df["RoomService"] > 0]["RoomService"],
    log_x=True,
    width=1000,
    height=500,
)

px.histogram(
    np.log10(train_df[train_df["RoomService"] > 0]["RoomService"]),
    log_x=False,
    width=1000,
    height=500,
)
```

The first `px.histogram()` fails silently (the graph is drawn, but there are no bars in it), even though there are no 0 values in the data. The second call works without any errors or warnings, which shows that the first call should also work.

Python 3.11.3
Plotly 5.14.1
Jupyter Notebook

**Comment by varunponda** [comment]
Hi @FlorinAndrei , You have filtered out the zeros from the column but the column still has null values/empty cells. To remove all null values from a DataFrame in Pandas, you can use the `dropna()` method. 

`train_df.dropna(inplace=True)`
Hope I addressed your issue, if issue persists please let me know.

**Comment by FlorinAndrei** [comment]
NaN values are not the actual problem.

`px.histogram()` works just fine with the same data if I simply pass `log_x=False`. It also works if I filter the data with `np.log10()`. It also works if I do both of these things.

Furthermore, the Plotly histogram function works just fine with the NaN-riddled data.

The only thing that does not work with the NaN data is `px.histogram(log_x=True)`.

All of the above, combined, shows pretty clearly the issue is not the NaN data, but the way `px.histogram()` handles it when you request `log_x=True`.

**Comment by varunponda** [comment]
when you set `log_x =True`  the x-axis is displayed on logarithmic scale, So logarithm of a number less than equal to 0 is undefined. Therefore it does not display the plot. But you already filtered out that by using this  `train_df["RoomService"] > 0]`. It might be possible that it is treating the NaN value as undefined. As you told plotly can work with NaN riddled-data but only when x-axis is displayed on linear scale (`log_x = False`). just try removing the NaN values. If issue persists there might be a problem in how the plotly library plots histogram when `log_x = True`.

**Comment by FlorinAndrei** [comment]
Dropping the NaN values makes no difference. The histogram still doesn't work in logarithmic mode even after dropping the NaN. I.e. this also fails to draw the bars:

```python
px.histogram(
    train_df[train_df["RoomService"] > 0]["RoomService"].dropna(),
    log_x=True,
    width=1000,
    height=500,
)
```

If you switch to `log_x=False` then it works just fine.

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
