### ISSUE TITLE
[bug] Trendline is missing from the scatter plot

### ISSUE THREAD

**Issue by zhimin-z** [plotly/plotly.py#4183]
Not sure if this is bug or misconfiguration, I attempt to plot the dots with a trendline added, but it just fails to show up in the figure. My code is written as follows
The code is:
```
import os
import pandas as pd
import plotly.express as px

df = pd.read_json('general.json')

# Plot median solved time against mean solved time for each topic using count ratio as size
fig = px.scatter(df_topics, y="Challenge median solved time", x="Challenge mean solved time",
                 color="Challenge topic", hover_name="Challenge topic", size="Challenge count", trendline="ols")
fig.update_layout(
    width=2000,
    height=1000,
    margin=dict(l=0, r=0, t=0, b=0))
fig.write_image('Challenge median vs mean solved time.png')
```
The output is:
![image](https://user-images.githubusercontent.com/8592144/235308913-ef3a189e-0828-4fe9-b85b-9d0ceaf6ebf6.png)
I am using the latest version of `plotly==5.14.1` on Python `3.10.1`

**Comment by jbeyer16** [comment]
IIRC the trendline will be fit to each grouping by color. It sorta seems from your data that each point is its own group - so then there'd only be one data point to fit to for each trendline. One way to check this is try the same plot function but remove the `color` arg and see what happens?

```python
fig = px.scatter(
    df_topics,
    y="Challenge median solved time",
    x="Challenge mean solved time",
    hover_name="Challenge topic",
    size="Challenge count",
    trendline="ols")
```

**Comment by jbeyer16** [comment]
Try passing `trendline_scope="overall"`

(docs on this page: https://plotly.com/python/linear-fits/)

**Comment by zhimin-z** [comment]
> Try passing `trendline_scope="overall"` (adding the `color` arg back in)
> 
> (docs on this page: https://plotly.com/python/linear-fits/)
It works!
![image](https://user-images.githubusercontent.com/8592144/235782115-2c9ad328-d6bb-4ad7-b51b-c097aa3e09e2.png)
