### ISSUE TITLE
How to add standard deviation to violin plots?

### ISSUE THREAD

**Issue by Zackhardtoname** [plotly/plotly.py#4187]
```Python
fig.add_trace(go.Violin(
                y=df,
                points=False,
                meanline={"visible": True}
            ))
```

This only gives the median & mean. Is there a way to get standard deviation too? I see in boxplot, there is `boxmean='sd'`, but the `go.violin.Box` doesn't take such an argument.

Thank you so much for your help!

**Comment by gvwilson** [comment]
Hi - we are tidying up issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. For tech support and "how-to" questions, please post in our community forum https://community.plotly.com/. Thank you - @gvwilson

**Comment by dinukajayalath** [comment]
I had the same issue, but there is a workaround by adding a scatter plot for mean and std with error bars. When doing this, make sure you add legendgroup for both the violin trace and the scatter trace, the same (pass the same groups), so legend group hide/show at the same time when toggling legend items, including the error bars. Hope this helps.
