### ISSUE TITLE
kernel crash after updating pandas to the latest version

### ISSUE THREAD

**Issue by zhimin-z** [plotly/plotly.py#4195]
I am using plotly for plotting the scatters but the kernel crashes again and again when I update pandas to `2.0.1`, my previous pandas is `1.3.5`.
Here is my code:
```
df = pd.read_json(os.path.join(path_challenge, 'statistics.json'))

# Plot median solved time against mean solved time for each topic using count ratio as size
fig = px.scatter(df, y="Challenge unsolved rate", x="Challenge median solved time",
                 color="Challenge macro topic", hover_name="Challenge macro topic", size="Challenge count", trendline="ols", trendline_scope="overall", trendline_color_override="black")
fig.show()
fig.update_layout(
    width=1500,
    height=750,
    margin=dict(l=0, r=0, t=0, b=0))
fig.write_image(os.path.join(
    path_challenge_difficulty, 'Challenge unsolved rate vs median solved time.png'))

# Plot median solved time against mean solved time for each topic using count ratio as size
fig = px.scatter(df, y="Challenge median solved time", x="Challenge mean solved time",
                 color="Challenge macro topic", hover_name="Challenge macro topic", size="Challenge count", trendline="ols", trendline_scope="overall", trendline_color_override="black")
fig.show()
fig.update_layout(
    width=1500,
    height=750,
    margin=dict(l=0, r=0, t=0, b=0))
fig.write_image(os.path.join(
    path_challenge_difficulty, 'Challenge median vs mean solved time.png'))
```
The expected results:
![Challenge median vs mean solved time](https://user-images.githubusercontent.com/8592144/236974457-82f8eaee-cd80-4734-bf23-f10a79b967f2.png)
![Challenge unsolved rate vs median solved time](https://user-images.githubusercontent.com/8592144/236974474-9a9fcd63-fef2-4f03-8989-e9c7f5adf651.png)
The error log:
```
Canceled future for execute_request message before replies were done
The Kernel crashed while executing code in the the current cell or a previous cell. Please review the code in the cell(s) to identify a possible cause of the failure. Click [here](https://aka.ms/vscodeJupyterKernelCrash) for more info. View Jupyter [log](command:jupyter.viewOutput) for further details.
```

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
