### ISSUE TITLE
Saving images uses some kind of cache

### ISSUE THREAD

**Issue by leviska** [plotly/plotly.py#4202]
Example code:

```python
for i in range(5):
    print(i, end=' ')
    for side in ["bid", "ask"]:
        fig = go.Figure()
        fig.add_trace(go.Scatter(x=[1,2], y=[2, 3], name=f"{i} {side}"))
        fig.update_layout(width=1500, title=f'ob {i} {side}')
        fig.write_image(f"../images/2/ob_{i}_{side}.png", scale=2)
```
Gives this pictures:
`ob_0_bid.png` (my guess, that this is the image from previous run or something)
![ob_0_bid](https://github.com/plotly/plotly.py/assets/14099557/4e11ad64-e0fc-4f83-961a-a433817e56b1)
`ob_0_ask.png`
![ob_0_ask](https://github.com/plotly/plotly.py/assets/14099557/e749344c-1698-4e72-b7ee-47c140e5932d)
`ob_1_bid.png`
![ob_1_bid](https://github.com/plotly/plotly.py/assets/14099557/ea06c867-1eed-4247-9365-4d7decdd237b)
`ob_1_ask.png`
![ob_1_ask](https://github.com/plotly/plotly.py/assets/14099557/ea641127-e827-441c-8dbe-56388348e0f6)

The problem is that file name does not corresponds to the image (plot title)

I've rechecked everything, deleted all the files, and it still keeps happening
Also some time before I've noticed the same thing with 
`display(Image(fig.to_image(format="png", scale=2)))` instead of `fig.write_image`

I'm running inside Visual Studio Code Notebook

```
> python --version
Python 3.8.10

> pip install plotly
Requirement already satisfied: plotly in /home/leviska/.local/lib/python3.8/site-packages (5.14.1)
Requirement already satisfied: packaging in /home/leviska/.local/lib/python3.8/site-packages (from plotly) (23.0)
Requirement already satisfied: tenacity>=6.2.0 in /home/leviska/.local/lib/python3.8/site-packages (from plotly) (8.2.2)

> pip install -U kaleido
Requirement already up-to-date: kaleido in /home/leviska/.local/lib/python3.8/site-packages (0.2.1)
```

It feels that plotly writes an older/cached image instead of new, but I have no idea whatsoever how can this happen

**Comment by leviska** [comment]
Running at the end of the cycle
```python
print(fig.layout.title)
display(Image(fig.to_image(format="png", scale=2)))
```
Gives 
![image](https://github.com/plotly/plotly.py/assets/14099557/7da54ac2-d00e-40fd-a853-1fdbbb3d2f7d)

**Comment by leviska** [comment]
Restarting the kernel fixes the issue until you run the code and interrupt it
It seems that interrupting the code while it draws triggers the bug

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
