### ISSUE TITLE
Responsive plots

### ISSUE THREAD

**Issue by Fractally** [plotly/plotly.py#421]
Hey guys

I've noticed that when I embed an online plot from plotly into a local html file on my PC, it is responsive and changes beautifully with my browser width. I also noticed the following:

1. When I generate a plot in Python and save it to file (output_type='file') and afterwards embed the plot into my local html file, the size changes only when I reload my local html file. 
2. When I generate a plot in Python and save it to div (output_type='div') and afterwards embed the plot into my local html file, the size is completely fixed. 

Now I am currently embedding the plots with an iframe like this:
```javascript
<div class="chart-stage">
            <iframe width="100%" height="480px" frameborder="0" scrolling="no" src="https://plot.ly/~jackp/10002.embed"></iframe>
</div>
```
How can I get the offline plots to be responsive like the online plotly plots that I embed? I'm asking just in case there is already functionality for this that I might have missed. What is the preferred way to get these offline plots to behave like the online plots?

**Comment by Fractally** [comment]
Update: My issue was related to cufflinks. By using a custom layout, I could fix the issue I was having.

**Comment by tdrobbin** [comment]
Fractally, could you elaborate on how you were able to generate responsive charts with cufflinks?
