### ISSUE TITLE
Interpolation for 3d data in plotly

### ISSUE THREAD

**Issue by vidhyadhari** [plotly/plotly.py#423]
I need a way to create a smooth representation of 3d curves in plotly. Currently I have a set of points when I plot them I get step-wise points in plotly. Is there a way to avoid the step-wise variance in the plots and get a smooth curve?

I have thought of interpolation but it is smoothing out the curve completely by avoiding all the outliers.

Attaching the images. 

![screen shot 2016-03-11 at 2 54 39 pm](https://cloud.githubusercontent.com/assets/7133119/13714142/cecd8e66-e79a-11e5-90ff-f51a449328d0.png)
The blue line in this plot needs to be smoothed. It has lot of outliers which create that step effect when I plot that data.

Here is the output of interpolation:
![5kdok](https://cloud.githubusercontent.com/assets/7133119/13714174/04566986-e79b-11e5-832e-5502c2db70be.png)
Before Interpolation.

![tvndq](https://cloud.githubusercontent.com/assets/7133119/13714184/13454296-e79b-11e5-887b-ce157d4423f2.png)
After Interpolation.

Any help on this would be great. Thanks.

**Comment by tarzzz** [comment]
You can set the line properties to spline in the trace:

Example:
~~~
import plotly.plotly as py
import plotly.graph_objs as go
import numpy as np

x = np.linspace(1,10,num=50)
y = np.random.rand(1,50)

trace = go.Scatter(x=x,y=y[0],mode='lines', line=go.Line(shape='spline')) # Line shape is 'spline' here ..
py.plot([trace])
~~~

This is how it renders: https://plot.ly/~tarzzz/1874/ 
:)

**Comment by vidhyadhari** [comment]
@tarzzz : Thanks for the reply.

But the problem is the line.shape property is present in only 2d plots. I need a similar one for 3d line plots. 

In 3d I used Scatter3d function instead of just Scatter and the line object doesn't have shape object in it.

**Comment by jackparmer** [comment]
See:

> no `line.shape`

In this issue: https://github.com/plotly/plotly.js/issues/130#issue-122750686
