### ISSUE TITLE
jupyterlab-plotly on_selection callback doesn't provide proper selected ranges on traces with extra axis

### ISSUE THREAD

**Issue by pavel-rosputko** [plotly/plotly.py#4241]
https://github.com/plotly/plotly.py/blob/981ace849c9749ff9e600a9f0ac1ac97b14c202d/packages/javascript/jupyterlab-plotly/src/Figure.ts#LL1140C3-L1140C22 function always assumes that `range` contains `y` axis

but https://github.com/plotly/plotly.js/blob/e6d0fe3d0cf494f8452c93ef85458672dd57aa5f/src/components/selections/select.js#LL1511C10-L1511C28 `makeFillRangeItems` function provides a range object with full axis names. 

https://github.com/plotly/plotly.js/blob/e6d0fe3d0cf494f8452c93ef85458672dd57aa5f/src/components/selections/select.js#L1518
```
            var id = ax._id; <-- can be x, y, or y2!
            var axLetter = id.charAt(0);
```

then `range[id]` can assign to y2

not sure whether there should be a change here in jupterlab-plotly or in plotly.js

**Comment by gvwilson** [comment]
thanks @nikita-zamaraev-loginom - I'll add it to our backlog, though I suspect it will be quite a while before anyone can get to it :-(
