### ISSUE TITLE
marker symbol "y-[up, down, left, right]" doesnt work.

### ISSUE THREAD

**Issue by Laser-Cho** [plotly/plotly.py#4243]
```
import plotly.graph_objects as go

fig = go.Figure()

symbol = "circle"
new_scatter = go.Scatter(x=[1,2,3], y=[1,2,3], mode="markers", marker=dict(symbol=symbol) )
fig.add_trace(new_scatter) # no-problem

symbol = "y-up"
new_scatter = go.Scatter(x=[4,5,6], y=[4,5,6], mode="markers", marker=dict(symbol=symbol) )
fig.add_trace(new_scatter) # it doesn't show

fig.update_layout(    autosize=False,    width=500,    height=500)
fig.show()
```

The symbol "y-up" shows nothing.
I tried it in two envs, [“plotly.version, jupyterlab.version == (‘5.15.0’, ‘3.0.0’)” , “plotly.version, jupyterlab.version == (‘5.13.1’, ‘4.0.1’)”] , and result is same. 

This problem is cross checked by Adam Schroeder.
https://community.plotly.com/t/the-marker-symbol-y-up-down-leftm-right-doesnt-show-up/76015/4?u=lasercho

https://plotly.com/python/reference/scatter/?_gl=1*u3qwjg*_ga*NDE5OTk2NjIzLjE2ODEzODc4NDg.*_ga_6G7EE0JNSC*MTY4NjU4Nzk2Ny4zLjEuMTY4NjU4ODA1Ny4wLjAuMA..#scatter-marker-symbol

**Comment by TillerBurr** [comment]
This exactly. 
> It concerns all symbols that are not filled. They are invisible as long as `marker_line_width` defaults to zero. 

The symbols here are numbered 33-44, 133-144, 233-244 and 333-344. The 0's are regular marks, the 100's are "-open", the 200's are "-dot" and the 300's are "-open-dot".

For reference:
<table>
<tr>
 <td>symbol number
 <td>symbol name
<tr>
 <td>33
 <td>cross-thin
<tr>
 <td>34
 <td>x-thin
<tr>
 <td>35
 <td>asterisk
<tr>
 <td>36
 <td>hash
<tr>
 <td>37
 <td>y-up
<tr>
 <td>38
 <td>y-down
<tr>
 <td>39
 <td>y-left
<tr>
 <td>40
 <td>y-right
<tr>
 <td>41
 <td>line-ew
<tr>
 <td>42
 <td>line-ns
<tr>
 <td>43
 <td>line-ne
<tr>
 <td>44
 <td>line-nw
</table>

This behavior is in line with plotly.js. One potential way to fix it is to add the `marker.line.width` setting to any of these marker numbers. Another would be to change the upstream behavior. Specifically this line: https://github.com/plotly/plotly.js/blob/4390b0dc5ba93e7dc015b079f6c3c02b545524c5/src/traces/scatter/marker_defaults.js#L66. This line sets the width to 0 if the plot isn't a bubble type plot.

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
