### ISSUE TITLE
Introducing Templates/Themes

### ISSUE THREAD

**Issue by tarzzz** [plotly/plotly.py#425]
Going through the discussion in this thread: https://github.com/plotly/plotly.py/issues/217

We can add template functionality to the API Libraries. Some pointers:
- `py.plot(fig, template='ggplot')`. Template can be a keyword ( 'ggplot', 'seaborn' etc.) or a `Figure` instance. This way a user can copy the theme from an existing chart the user has access to (which many people have been asking about, in support queries).
- Copying the template from an existing Plotly chart will only work in online mode (inbuilt template can be used offline as well).
- saving user's custom templates as JSON in `.plotly/user_templates` directory, and built-in templates in `.plotly/plotly_templates` directory.
- Adding new built-in templates will require a valid `template.json` and a reference in a `templates.py` file.
- A Template Parser, which will load template files, and convert them to `Figure` or `Layout` objects (basically deserialize them).
- A _deep_ `update` method, which can work on Plotly's Graph Objects (as a utility method).

@cldougl @jackparmer @theengineear : please provide comments/suggestions ..

**Comment by theengineear** [comment]
@tarzzz here's some docs on how [themes](https://github.com/plotly/streambed/blob/master/shelly/themes/README.md) are stored in Plotly. Note that the themes need an update to follow our [PlotSchema](https://api-local.plot.ly/v2/plot-schema?sha1).

We settled on having `theme` objects mimic the format of an actual plot. This allows us to treat it as if it were a plot. The downside of this is that applying a theme to a plot with 1000 traces would need 1000 objects.

It'd be cool if the format of themes created Python matched what we're trying to store in the backend. That way they could be sharable.

Also, unless there's a good reason to break from calling things `themes`, we should probably stick with that word over `template`.

**Comment by 1beb** [comment]
Please note, both links above are dead.

**Comment by galpin** [comment]
Has there been any progress on this?

**Comment by jackparmer** [comment]
> Please note, both links above are dead.

They actually link to a private repo that we can't open-source ATM unfortunately

**Comment by chriddyp** [comment]
this has been added in plotly.js: https://github.com/plotly/plotly.js/pull/2761
