### ISSUE TITLE
CDN down

### ISSUE THREAD

**Issue by kkoomen** [plotly/plotly.py#4253]
See https://github.com/plotly/plotly.js/issues/6648

Any updates on this from the team? When will this be fixed?

I am also using the choropleth map locally which needs the world_110m.json file, I can download this from the repo as well, but I don't see a way to use this world_110.json in the plotly express documentation.

**Comment by DanNeidle** [comment]
I tried to find the place in the library code that refererences to the URL, but couldn't find it...

**Comment by alexcjohnson** [comment]
Thanks all - we're working on it.

**Comment by alexcjohnson** [comment]
Please try again, should be working now. Sorry for the inconvenience!

**Comment by renbotha** [comment]
Looks to be fixed on my side now! Great job!

**Comment by kkoomen** [comment]
Works!
