### ISSUE TITLE
All of Choropleth plots are broken, only legends and title are shown, maps are not shown

### ISSUE THREAD

**Issue by rugezhao** [plotly/plotly.py#4254]
I'm on latest version 5.15 and all my plots using choropleth are broken, with only legend and title shown up but the map itself are not shownup. It was working this morning June 20th morning PST.

I then realize even the plots in the documentation itself are not working anymore https://plotly.com/python/choropleth-maps/.
For example, "Polotical candidate voting pool analysis" chart is in the same state where only title and legend shows up.
<img width="958" alt="Screen Shot 2023-06-21 at 1 00 25 AM" src="https://github.com/plotly/plotly.py/assets/13581797/3cf17e7b-d645-423b-8353-ba1f725422f5">

I played around with different browsers (tried chrome and safari) and also tried different ISP and all of them shows the same issue the map part of the plot is not loading.

**Comment by thaisash** [comment]
The exact same thing is happening to me. Does anyone know what's going on?
[](url)
![Captura de tela 2023-06-21 073356](https://github.com/plotly/plotly.py/assets/137285675/3e865382-4d17-4523-a954-e6061915c735)

**Comment by DanNeidle** [comment]
may be because CDN is down - e.g. https://cdn.plot.ly/world_110m.json is unreachable

**Comment by alexcjohnson** [comment]
Thanks - we're working on it. Closing, please see https://github.com/plotly/plotly.js/issues/6648 for updates.

**Comment by thaisash** [comment]
Thanks!
