### ISSUE TITLE
Plotly stop showing figures

### ISSUE THREAD

**Issue by ntitii** [plotly/plotly.py#4256]
Plotly stopped showing any kind of figures. All the figures in my google colab worked just fine until yesterday evening, the code block run successfully but then nothing shows up. I'm using the updated version 5.13.1.

I tried simple code, also I tried using Jupyter Notebook instead of google colab, all figures didn't show up as well.

fig = go.Figure(data=go.Scatter(x=[1, 2, 3], y=[4, 2, 5]))
fig.show()

**Comment by alexcjohnson** [comment]
We had a CDN outage but it’s fixed now, can you try again?

**Comment by ntitii** [comment]
It works now thank you.
