### ISSUE TITLE
How to overlay two surfaces

### ISSUE THREAD

**Issue by JintaoLee-Roger** [plotly/plotly.py#4258]
Hi!

In matplotlib, I can overlay two images/arrays by:
```python
# arr1.shape == arr2.shape == (n1, n2)
plt.imshow(arr1, cmap='gray')
plt.imshow(arr2, cmap='jet', alpha=0.4)
plt.show()
```

So how can I do this in plotly, the first surface is the background and the second surface is the foreground with opacity = 0.4?
If I simply add two traces, the first or the second trace is hided:
``` python
# assume I have x, y, z meshgrids and two surface value arrays: arr1 and arr2
sf1 = go.Surface(x=x, y=y, z=z, surfacecolor=arr1, colorscale='gray')
sf2 = go.Surface(x=x, y=y, z=z, surfacecolor=arr2, colorscale='jet', opacity=0.5)
fig = go.Figure([sf1, sf2])
fig.show()
```
When I set opacity < 1, the figure only shows sf1, and set opacity = 1, the figure only shows sf2.

The reason I need this is that sf2 is the label of sf1, and I want to overlay them to display.

**Comment by JintaoLee-Roger** [comment]
I possible solution is blending the two array with their colormap, obtain the RGBA array. But it seem to raise another problem: 

How can I pass a RGBA color array instead of pass the `surfacecolor` array and `colorscale`? 

This means for each location (xi, yi, zi), I have a rgba color value (r, g, b, a). x, y, z are meshgrids and their shape is (n1, n2), the shape of blended_color array is (n1, n2, 4).

For example:
```python
def blending_color(bg, fg, alpha, bgc='gray', fgc='jet', bgclims=None, fgclims=None):
    if bgclims is None:
        bgclims = [bg.min(), bg.max()]
    if fgclims is None:
        fgclims = [fg.min(), fg.max()]
    norm1 = plt.Normalize(vmin=bgclims[0], vmax=bgclims[1])
    norm2 = plt.Normalize(vmin=fgclims[0], vmax=fgclims[1])

    cmap_rgb1 = plt.get_cmap(bgc)
    cmap_rgb2 = plt.get_cmap(fgc)
    arr1_rgb = cmap_rgb1(norm1(bg))
    arr2_rgb = cmap_rgb2(norm2(fg))

    blended_rgb = arr1_rgb * (1 - alpha) + arr2_rgb * alpha

    return blended_rgb


# (n1, n2, 4),  each row is a rgba value
rgba = blending_color(arr1, arr2, 0.5, 'gray', 'jet')
fig = go.Figure(go.Surface(x=x, y=y, z=z, surfacecolor=rgba)) # cannot realize
fig.show()
```

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
