### ISSUE TITLE
Radar plots: Broken documentation for generating example

### ISSUE THREAD

**Issue by vprusso** [plotly/plotly.py#4259]
The following example in the "Radar chart" [documentation page](https://plotly.com/python/radar-chart/):

```py
import plotly.express as px
import pandas as pd
df = pd.DataFrame(dict(
    r=[1, 5, 2, 2, 3],
    theta=['processing cost','mechanical properties','chemical stability',
           'thermal stability', 'device integration']))
fig = px.line_polar(df, r='r', theta='theta', line_close=True)
fig.show()
```

yields the following error:

```
AttributeError: 'DataFrame' object has no attribute 'append'. Did you mean: '_append'?
```

The reason for this issue is most likely due to the `plotly.express` component not abiding by the [migration guidelines](https://github.com/plotly/plotly.py/blob/master/migration-guide.md#new-figuredata-assignment).

**Comment by alexcjohnson** [comment]
Do you have the latest release, v5.15? This was fixed in https://github.com/plotly/plotly.py/pull/4190

**Comment by vprusso** [comment]
That was it! I was on 5.14.1. Thank you for the quick response, @alexcjohnson !

Closing.
