### ISSUE TITLE
Is Plotly incompatible with streamlit?

### ISSUE THREAD

**Issue by Scoodood** [plotly/plotly.py#4261]
I have the following system configuration:
```
Streamlit version: 1.23.1
Plotly version: 5.15
Python version: 3.11
Operating System: Windows 11 Pro (64 bit)
Browser: Microsoft Edge Version 114.0.1823.58 (64-bit)
Virtual environment: miniconda 23.3.1
```

My problem can be replicated with these steps:

Step 1. Setup a new environment
```
conda create -n test python==3.11
conda activate test
pip install numpy plotly==5.15 streamlit==1.23.1
```

Step 2. Launch Python
```
python
```

Step 3. Create a Plotly chart without importing the streamlit library by running these codes
```
import plotly.graph_objects as go
import numpy as np

t = np.linspace(0, 10, 100)
y = np.sin(t)
fig = go.Figure(go.Scatter(x=t, y=y, mode='markers'))
fig.show()
```
Step 4: My Plotly plot looks like this (expected behavior)
![image](https://github.com/plotly/plotly.py/assets/15989924/47b47b77-4cfb-4d10-b1d7-2ff0ea72b068)

Step 5: Import the streamlit library and re-run the same code.
```
import streamlit as st
import plotly.graph_objects as go
import numpy as np

t = np.linspace(0, 10, 100)
y = np.sin(t)
fig = go.Figure(go.Scatter(x=t, y=y, mode='markers'))
fig.show()
```

Step 6: My plotly chart becomes black and white like this (unexpected behavior)
![image](https://github.com/plotly/plotly.py/assets/15989924/8200e4bf-0b23-445f-a633-4e523b8eac48)

Does anyone know how to fix this?

**Comment by alexcjohnson** [comment]
Apparently Streamlit [overrides the default Plotly theme](https://github.com/streamlit/streamlit/blob/bf20ec6d34d6f68ba69a35cc74c84e71a9c89aef/lib/streamlit/elements/plotly_chart.py#L43) simply by importing their package.

You can reset it with `pio.templates.default = 'plotly'` after the Streamlit import - see https://plotly.com/python/templates/#specifying-a-default-themes

**Comment by Scoodood** [comment]
Thanks. It works!
