### ISSUE TITLE
Plotly introduces errors with magic syntax highlighting in Jupyter

### ISSUE THREAD

**Issue by msftristew** [plotly/plotly.py#427]
It looks like the `init_notebook_mode()` function introduces some conflicts with Jupyter that causes magics syntax highlighting in IPython to not work correctly.  The issue is that Plotly seems to conflict with the mechanism that Jupyter uses for magics syntax highlighting.  

Repro steps:

1. Make a simple IPython wrapper kernel and configure it to use syntax highlighting for a non-Python language in a cell with a particular cell magic, e.g. SQL syntax highlighting after the `%%sql` magic

2.  Run `init_notebook_mode` in a cell

3. Try to run a cell with the `%%sql` magic; syntax highlighting will not work and errors will be logged to the JS console

Here are some screenshots for my machine.  Syntax highlighting gets turned off after I run `init_notebook_mode`:

![image](https://cloud.githubusercontent.com/assets/13972471/13935117/d9709d42-ef72-11e5-93ed-d27848b96de8.png)

When I type `%%sql` in the cell, these errors get logged:

![image](https://cloud.githubusercontent.com/assets/13972471/13935150/02c11d5c-ef73-11e5-806b-44463e6da565.png)

... so it looks like the call to `init_notebook_mode` is interfering with Jupyter's `require.js` machinery in some way.  

I am wondering if this issue is related to [issue 90](https://github.com/plotly/plotly.js/issues/90) or if it happens to have been solved in [this commit](https://github.com/plotly/plotly.py/commit/127ebc5f0be979c52847a6427a2ada3b11fc4352).

**Comment by msftristew** [comment]
CC @aggFTW, @mohael

**Comment by msftristew** [comment]
Running plotly 1.9.6, BTW

**Comment by aggFTW** [comment]
cc. @etpinard @jdfreder 

Thanks!

**Comment by jdfreder** [comment]
Hi @msftristew the commit you referenced should fix it, and that commit has been merged into plotly master

**Comment by msftristew** [comment]
Thanks @jdfreder. When will the next version of plotly be released that will have this fix?

**Comment by watersavvy** [comment]
Hello, I am new to Jupyter as of this week and ran into the same error message. What does "ERROR: Cell magic 'sql' not found." indicate? This syntax based on previous inputs should work:

%%sql
SELECT start_time AS "exam start time"
FROM exam_answers;

Any ideas?

**Comment by msftristew** [comment]
In my screenshot, the %%sql magic doesn't actually exist, I'm just using it as an example to show how this function breaks syntax highlighting.

**Comment by msftristew** [comment]
Ping :) 

Is there an ETA on the new version which will fix this?

**Comment by cldougl** [comment]
updated with: https://github.com/plotly/plotly.py/pull/432

Should work now!

**Comment by msftristew** [comment]
It does! Thank you.
