### ISSUE TITLE
want different colors of plots on one plot

### ISSUE THREAD

**Issue by BareeraSadia** [plotly/plotly.py#4273]
I'm encountering an issue with a size-based graph I'm creating using Plotly Express. I'm using the provided code to generate a scattermapbox figure with dots representing different sentiment types. The goal is to assign colors to the dots based on the maximum sentiment type present at each location.

Here's the relevant code snippet I'm using:

# Create lists to store the latitude, longitude, sentiment, magnitude, and color for each location
latitudes = []
longitudes = []
sentiments = []
magnitudes = []
colors = []
dot_sizes = []

# Find the maximum sentiment type
max_sentiment = max(sentiments, key=lambda x: magnitudes[sentiments.index(x)])

# Iterate over the maximum values dictionary
for location, (sentiment, value) in max_values.items():
    latitudes.append(location[0])
    longitudes.append(location[1])
    sentiments.append(sentiment)
    magnitudes.append(value)

    # Calculate the dot size based on the magnitude
    dot_sizes.append(value / 8)

    # Assign the color based on the sentiment type
    if sentiment == 'infpos':
        colors.append('green' if sentiment == max_sentiment else 'lightgreen')
    elif sentiment == 'infneg':
        colors.append('red' if sentiment == max_sentiment else 'lightpink')
    elif sentiment == 'infneu':
        colors.append('yellow' if sentiment == max_sentiment else 'lightyellow')
The issue I'm facing is that all the dots are being displayed in black color or any one color(e.g blue) which i specify in "go.scattermapbox(marker=dict(color='blue')", regardless of the maximum sentiment type. I want the dots to be displayed in different colors based on the maximum sentiment type at each location (e.g., green for 'infpos', red for 'infneg', and yellow for 'infneu').

I would greatly appreciate any guidance or suggestions on how to resolve this issue. Thank you!

**Comment by alexcjohnson** [comment]
@BareeraSadia I don't see the px command you're using, but anyway this kind of "how-to" question is much better suited to https://community.plotly.com/ - would you be able to re-post over there? We prefer to reserve GitHub issues for bug reports and feature requests.

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
