### ISSUE TITLE
python-igraph was renamed to igraph

### ISSUE THREAD

**Issue by szhorvat** [plotly/plotly.py#4285]
The `python-igraph` package was renamed to simply `igraph`. Support for the earlier name is stopping. See https://pypi.org/project/python-igraph/

Please update the references in plotly.py:

https://github.com/search?q=repo%3Aplotly%2Fplotly.py%20python-igraph&type=code

This is basically changing all the `pip install python-igraph` to `pip install igraph`.

**Comment by LiamConnors** [comment]
Sorry for the delay on this. I've created a new PR for this with just the required changes and we'll get it merged as soon as possible https://github.com/plotly/plotly.py/pull/4383
