### ISSUE TITLE
PerformanceWarning: DataFrame is highly fragmented. for Plotly v5.15.0

### ISSUE THREAD

**Issue by crossingchen** [plotly/plotly.py#4287]
Plotly v5.15.0 on mac, error in Library/Python/3.9/lib/python/site-packages/plotly/express/_core.py, Line 1223.
`PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling frame.insert many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use newframe = frame.copy()`

This happens when trying to plot a line chart from a csv file with a large number of columns. And the chart never appears (...or takes too long to appear and I killed the process). This error does not occur when the number of columns in the csv is limited.

In the csv file, the first column serves as the x-axis and for the rest of the columns, each column is plotted as a line in the line chart.

**Comment by alexcjohnson** [comment]
Being addressed by #4246

**Comment by crossingchen** [comment]
Perfect, thanks for the prompt response. The issue is resolved now.

**Comment by meghanareddyy** [comment]
Hi @crossingchen  and @alexcjohnson , I am also facing the same issue with Plotly. Kindly let me know how it got resolved for you guys.

**Comment by alexcjohnson** [comment]
#4246 will be in the next release

**Comment by matanster** [comment]
Had this same issue with the same version of plotly. 
After upgrading, I can now confirm this is [solved](https://github.com/plotly/plotly.py/releases/tag/v5.16.0), tested on v5.18.0 in my case. At least that warning does not show anymore.
