### ISSUE TITLE
Colorscale only scales to min/max values on 3D Surface

### ISSUE THREAD

**Issue by bc2297** [plotly/plotly.py#431]
It seems that the actual colors in a 3D surface plot scale to the minimum and maximum values in the plot, not to anything dealing with the zmin/zmax or cmin/cmax settings. Same behavior with default colorscale and specified colorscale. Code to reproduce is below. I would expect the colors to scale from cmin to cmax. The colorscale "legend" takes on the values of zmin/zmax visually, but the colors don't scale on the plot as they do in the legend.
```
import plotly.offline as offline
from plotly.graph_objs import Figure, Surface
zValues = [[2,4,6],
           [2,4,6],
           [2,4,6]]
colorscale = [[0, 'rgb(0,0,255)'], [1, 'rgb(255,0,0)']]
data = [Surface(z=zValues,
                zmin=4,
                zmax=7,
                cmin=0,
                cmax=10,
                colorscale=colorscale)]
fig = Figure(data=data)
plot = offline.plot(fig, filename="testout.html")
```

**Comment by jackparmer** [comment]
@bc2297 You need to use `data['surfacecolor']`

Docs:
https://plot.ly/python/3d-surface-coloring/

**Comment by bc2297** [comment]
Thanks! Confirmed this works as I intended with simple code modification as suggested
```
import plotly.offline as offline
from plotly.graph_objs import Figure, Surface
zValues = [[2,4,6],
           [2,4,6],
           [2,4,6]]
colorscale = [[0, 'rgb(0,0,255)'], [1, 'rgb(255,0,0)']]
data = [Surface(z=zValues,
                zmin=4,
                zmax=7,
                cmin=0,
                cmax=10,
                colorscale=colorscale,
                surfacecolor=zValues)]
fig = Figure(data=data)
plot = offline.plot(fig, filename="testout.html")
```
