### ISSUE TITLE
Inconsistent Behaviour Between PlotlyJS and Plotly Python

### ISSUE THREAD

**Issue by msillz** [plotly/plotly.py#4317]
If you take the figure object, the formatting string: '.2%f' will format values as percents when created with the Javascript library, but not with the Python library. '.2%', however, works with both libraries.

**Comment by alexcjohnson** [comment]
Thank you @msillz - what version of plotly.js do you have in graphs you create from Python? This shows if you hover on the Plotly logo in the upper right corner of a graph.

**Comment by msillz** [comment]
@alexcjohnson plotly.js v1.58.5 was cached. I will try it again with a newer version. I will close this.
