### ISSUE TITLE
"ReferenceError: Plotly is not defined" in v. 1.9.7

### ISSUE THREAD

**Issue by javiljoen** [plotly/plotly.py#435]
Example Jupyter notebook content:

```
import plotly
plotly.offline.init_notebook_mode()
plotly.offline.iplot({
        "data": [{
                "x": [1, 2, 3],
                "y": [4, 2, 5]
            }],
        "layout": {
            "title": "hello world"
        }
    })
```

In Plotly 1.9.7, when exported to HTML with `jupyter nbconvert --execute test.ipynb` and opened in Firefox or Chrome, there is no visible plot and the JS console says
```
ReferenceError: Plotly is not defined | test.html:253:85
```

With Plotly 1.9.6, it loads as expected.

Probably solved with #434?

**Comment by cldougl** [comment]
Thanks for reporting - this should be corrected now with v. 1.9.9
Please let us know if you're still having a problem!
