### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by Kripishit** [plotly/plotly.py#4355]
Im learning to use plotly and wanted to know some stuff about it,
is it possible to make a exe app with plotly inside?, by this i mean, is it possible to make a standalone software without depending on html or any web services to run plotly modules?.

And othe question, wich library could be usefull to combine with plolty and make a Gui for the software?, since tkinter doesnt work with plotly i read about dash but it needs constant internet connection and is opened via browser and im looking to make a no internet or browser required standalone app.
Ty.

**Comment by alexcjohnson** [comment]
Hi @Kripishit - welcome! This kind of question is best addressed to the community forum https://community.plotly.com/ but the short answer is both plotly.py and Dash need to be rendered by a browser context, but neither one needs a connection to the internet, they can serve everything they need from within your own computer. I'll close this issue but feel free to follow up on the forum :)

**Comment by Kripishit** [comment]
Thanks. :)
