### ISSUE TITLE
Add a function to save animations as mp4 files.

### ISSUE THREAD

**Issue by robbymumo** [plotly/plotly.py#4366]
Dear Plotly Express Community,

I hope this message finds you well. I am an enthusiastic user of Plotly Express, and I have a feature suggestion that I believe would greatly enhance the utility of this fantastic library: the ability to save animations as MP4 files.

Currently, Plotly Express provides several functions to export visualizations in various formats, such as JPEG, PNG, and HTML, which are incredibly useful for static plots. However, there is no direct function available to save animations as MP4 files.

I believe that adding this feature would be a significant step forward for Plotly Express for the following reasons:

**Enhanced Presentation:** Saving animations as MP4 files would greatly facilitate their integration into presentations, whether it's for PowerPoint, educational materials, or other media.

**Wider Audience:** Many platforms and tools support MP4 videos, making it easier to share your visualizations with a broader audience, especially those who might not be familiar with Plotly or its interactive features.

**Professional Look:** MP4 animations offer a professional and polished look, which can be crucial in contexts like business presentations and academic lectures.

I propose adding a new function to Plotly Express that enables users to save animations in the following way:

fig.save_animation("file_path/file.mp4")

This function would simplify the process of exporting animations and make Plotly Express an even more versatile tool for data visualization.

I would like to encourage the Plotly Express community and developers to consider this feature suggestion seriously. I believe it would be a valuable addition to an already exceptional library and would benefit countless users who rely on Plotly Express for their data visualization needs.

If you have any questions or need further clarification on this feature suggestion, please feel free to reach out. I am more than willing to provide additional details or assist in any way possible to help implement this feature.

Thank you for your time and consideration.

Sincerely,
Robinson Mumo

**Comment by empet** [comment]
In the meantime you can use `moviepy` to save   the animation  as gif or mp4 files.
Here are two examples, but the second one is simpler to get an idea on how plotly+moviepy work:
[https://github.com/empet/MoviePy-gifs-and-videoclips-from-Plotly-plots](https://github.com/empet/MoviePy-gifs-and-videoclips-from-Plotly-plots).
For animations is recommended to work with  `plotly.graph_objects`, which is much more customizable than Plotly express.

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
