### ISSUE TITLE
version with latest revisions?

### ISSUE THREAD

**Issue by tfg250** [plotly/plotly.py#437]
When will the next version of plotly.py (that includes recent updates to plotly.js) be released?

**Comment by yankev** [comment]
@tfg250 : It's up now, you can now update the version on pip.

**Comment by tfg250** [comment]
I just installed version 1.9.8 and the features identified as closed on the plotly.js [changelog](https://github.com/plotly/plotly.js/blob/master/CHANGELOG.md), (items [405](https://github.com/plotly/plotly.js/pull/405) and [408](https://github.com/plotly/plotly.js/pull/408))  don't seem to be working, also html files generated with plotly.offline no longer open.
