### ISSUE TITLE
Offline mode: Uncaught ReferenceError: require is not defined

### ISSUE THREAD

**Issue by ricleal** [plotly/plotly.py#439]
Hello all,

I just updated to plotly from 1.9.5 to 1.9.8 and the offline mode is not working anymore...

Now I have a javascript error:
`Uncaught ReferenceError: require is not defined`

Which arises from the rendered code:
```javascript
require(["plotly"], function(Plotly) {
    window.PLOTLYENV = window.PLOTLYENV || {};
```
Note that in version 1.9.5, the `require(["plotly"], function(Plotly) {` did not exist!

Any workaround this issue?

Thanks in advance!

**Comment by yankev** [comment]
Can you provide some more detail of what you're trying to do (ie: the code that generated this error).

**Comment by ricleal** [comment]
I'm embedding plotly in Django.

I generate the javascript as:
```python
    fig = go.Figure(data=data, layout=layout)
    plot_div = plot(fig, output_type='div', include_plotlyjs=False)
```

In my html I have:
```html
<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>

<!-- Renders the plot_div variable -->
<div >{{plot_div|safe}}</div>
```

It used to work in version 1.9.5...

Any javascript I could include for the `require` function?

Thanks

**Comment by cldougl** [comment]
This should work for you now with 1.9.9 -- but please let us know if you're still having an issue!

**Comment by cldougl** [comment]
Closing due to update. @ricleal feel free to let us know if you're still having issues with the newest version (currently 1.12.7)

**Comment by gerard0315** [comment]
@cldougl hi I'm using plotly 2.0.9 but still having this issue. I was using plotly to render a static matplotlib chart, in [nteract/display-area](https://github.com/nteract/nteract/tree/master/packages/display-area).
