### ISSUE TITLE
Colorscale NaN values

### ISSUE THREAD

**Issue by bonfire27** [plotly/plotly.py#4393]
Feature request:

You don`t have currently a way to set the color or the behavior of nan values in go.Heatmap (cells become transparent) and go.scatter (markers become black).

it would be nice to have a property to set like
marker_colornan="lightgray"

or 

nancolor="black"

**Comment by alexcjohnson** [comment]
Yep, this would be a great feature. Has been discussed before though, eg https://github.com/plotly/plotly.js/issues/975, so I'll close this one. Thanks!
