### ISSUE TITLE
Version 1.9.8

### ISSUE THREAD

**Issue by tfg250** [plotly/plotly.py#442]
I just installed version 1.9.8 and the features identified as closed on the plotly.js [changelog](https://github.com/plotly/plotly.js/blob/master/CHANGELOG.md), (items [405](https://github.com/plotly/plotly.js/pull/405) and [408](https://github.com/plotly/plotly.js/pull/408))  don't seem to be working, also html files generated with plotly.offline no longer open.

**Comment by yankev** [comment]
That last issue should be corrected with the latest update of the python api (version 1.9.9)

**Comment by tfg250** [comment]
Looks like version 1.9.9 has fixed both of those items  (items [405](https://github.com/plotly/plotly.js/pull/405) and [408] (https://github.com/plotly/plotly.js/pull/408)) in offline mode, but they are not working in online mode.

**Comment by cldougl** [comment]
Both of those issues should be working online now. Plotly.js is updated periodically for our online workspace and APIs' online functionality.
