### ISSUE TITLE
'update_layout(yaxis_gridcolor, xaxis_gridcolor) to px.bar() with facet_row option' is on doesn't work

### ISSUE THREAD

**Issue by hanseolization** [plotly/plotly.py#4434]
<img width="1555" alt="image" src="https://github.com/plotly/plotly.py/assets/22539723/11d17be7-ea6d-4306-ac98-72ed47946a59">

**Comment by Coding-with-Adam** [comment]
Thanks for opening this issue, @hanseolization . I was able to replicate the bug with this code snippet:

```
import plotly.express as px
df = px.data.tips()
fig = px.bar(df, x="sex", y="total_bill", color="smoker", barmode="group",
             facet_row="time",
             category_orders={"day": ["Thur", "Fri", "Sat", "Sun"],
                              "time": ["Lunch", "Dinner"]})
fig.update_layout(yaxis_gridcolor='black', xaxis_gridcolor='black')
fig.show()
```
![image](https://github.com/plotly/plotly.py/assets/32049495/acf5c9d6-0846-4978-bec4-9d159dfb425f)

**Comment by alexcjohnson** [comment]
This is not a bug - `xaxis_gridcolor` updates the color only of the axis named `xaxis`, but when the plot is faceted there are multiple axes of each type. So if you wanted to do this with `fig.update_layout` you'd need to include `xaxis2_gridcolor`, `xaxis3_gridcolor`, etc... repetitive and you'd need to know how many axes exist.

This is why `fig.update_xaxes` and `fig.update_yaxes` exist. See eg https://plotly.com/python/axes/#styling-grid-lines
