### ISSUE TITLE
Converting ipynb to html using latex and plot.ly does not work properly

### ISSUE THREAD

**Issue by jaschwer** [plotly/plotly.py#444]
I am using jupyter to write a notebook using latex and plotly.
Within the notebook everything is fine and I can see both properly, but after converting the notebook into a html (no matter if I download it via the menu or use a nbconvert in the terminal), I do see the plot, but the equations are shown in the normal markdown code. You can see the result [here](https://github.com/jaschwer/Third_Assignment/blob/master/test2.html).

The notebook can be found [here](https://github.com/jaschwer/Third_Assignment), named test2

I have the latest mathjax version and I did not find any suggestions using google. Not including the plotly packages nor the plot I get the latex equations right.

Can anybody help me?

Problem arised both on mac and windows.

**Comment by cldougl** [comment]
refer to https://github.com/plotly/plotly.py/issues/515 for updates in this issue
