### ISSUE TITLE
Plotly conflict with latex in notebook

### ISSUE THREAD

**Issue by jcr-lyxor** [plotly/plotly.py#445]
Hi all,

When I use plotly in a notebook with latex mardown, all the latex formula jump from center to left.
I think there is a conflict between them. There is no issue with matplotlib.

Thanks

**Comment by cldougl** [comment]
@jcr-lyxor can you share an example notebook and mention if you're using plotly online or offline as well?

**Comment by jonmmease** [comment]
The offline latex/MathJax issues are going to be resolved by plotly/plotly.js#2994 and #1169. Follow along if you're interested!

**Comment by jonmmease** [comment]
Fixed in #1243 and will be released in version 3.4.0.
