### ISSUE TITLE
Map boundaries are not showing

### ISSUE THREAD

**Issue by mgorjis** [plotly/plotly.py#4450]
I opened the documentation, and for this page, I don't see the map boundaries. I also tried with multiple browsers

https://plotly.com/python/lines-on-mapbox/#lines-on-mapbox-maps-using-plotly-express

running the code in python also has the same issue

![image](https://github.com/plotly/plotly.py/assets/11069763/6894656e-d054-46f1-baef-2cc782dbbdd6)

**Comment by alexcjohnson** [comment]
Right, Stamen put their maps behind a paywall - we've added support for this in [plotly.js v2.27.1](https://github.com/plotly/plotly.js/releases/tag/v2.27.1) but @LiamConnors I suppose we'll want to update the docs to only use non-Stamen/Stadia maps?

**Comment by LiamConnors** [comment]
This feature was included in the latest Plotly.py release, 5.19. The docs now show examples of using a token for the stamen styles
https://plotly.com/python/mapbox-density-heatmaps/#stamen-terrain-base-map-stadia-maps-token-needed-density-mapbox-with-plotlyexpress

Thanks for opening this issue @mgorjis
