### ISSUE TITLE
Broken URL on the 'Static Image Export in Python' page

### ISSUE THREAD

**Issue by chrimaho** [plotly/plotly.py#4458]
There is a broken URL on the website: https://plotly.com/python/static-image-export/

Under the **Write Image File** section.

This is the paragraph:

> If you are running this notebook live, click to [open the output directory](https://plotly.com/python/static-image-export/images) so you can examine the images as they are written.

And as you can see, it refers to this url: https://plotly.com/python/static-image-export/images

Which is no longer existing.

**Comment by Coding-with-Adam** [comment]
Thank you for reporting this, @chrimaho .
cc @LiamConnors

**Comment by LiamConnors** [comment]
This was fixed by https://github.com/plotly/plotly.py/pull/4614
