### ISSUE TITLE
cluster not showing with scatter_mapbox

### ISSUE THREAD

**Issue by erwanmq** [plotly/plotly.py#4466]
Hi!

I have some troubles rendering clusters with scatter_mapbox and I think it's a plotly bug. 
In the documentation I found this code:

```
import plotly.express as px
import pandas as pd

px.set_mapbox_access_token(open(".mapbox_token").read())
df = pd.read_csv(
    "https://raw.githubusercontent.com/plotly/datasets/master/2011_february_us_airport_traffic.csv"
)
fig = px.scatter_mapbox(df, lat="lat", lon="long", size="cnt", zoom=3)
fig.update_traces(cluster=dict(enabled=True))
fig.show()
```
that creates this map:
![newplot (4)](https://github.com/plotly/plotly.py/assets/93351393/b9672532-b83a-467d-9654-409956ce2aeb)

When I do the same on my project I have nothing:
![newplot (5)](https://github.com/plotly/plotly.py/assets/93351393/dd1a8e34-fe0f-4c28-bd8c-7e6e5281d300)

I am with dash==2.14.2 and plotly==5.18.0

I tried with the same version when the cluster was released and it worked. But I can't stay with this old version.

**Comment by Coding-with-Adam** [comment]
hi @erwanmq 
Thanks for reporting. You would actually need your own mapbox token to run these examples. 
The documentation runs these examples by using our own token. See the brief notification at the top of the Plotly scatter_mapbox page:

> To plot on Mapbox maps with Plotly you may need a Mapbox account and a public [Mapbox Access Token](https://www.mapbox.com/studio).

In other words, you would need to replace this line of code:
`px.set_mapbox_access_token(open(".mapbox_token").read())`

with your own token.

**Comment by erwanmq** [comment]
Oh yes of course! I modified it for the screenshot I sent in my previous message. I used mapbox_style='open-street-map' as I remember

**Comment by Coding-with-Adam** [comment]
That is correct. [The built-in Mapbox styles](https://plotly.com/python/reference/layout/mapbox/#layout-mapbox-style) are: basic, streets, outdoors, light, dark, satellite, satellite-streets

```
import plotly.express as px
import pandas as pd

df = pd.read_csv(
    "https://raw.githubusercontent.com/plotly/datasets/master/2011_february_us_airport_traffic.csv"
)
fig = px.scatter_mapbox(df, lat="lat", lon="long", size="cnt", zoom=3)
fig.update_traces(cluster=dict(enabled=True))
fig.update_mapboxes(style="satellite-streets")
fig.update_layout(
    mapbox=dict(accesstoken="my-token")
)
fig.show()
```

**Comment by Coding-with-Adam** [comment]
`mapbox_style='open-street-map'` or other styles (such as carto-darkmatter, carto-positron, open-street-map, stamen-terrain, stamen-toner, stamen-watercolor, white-bg) will work with `px.choropleth_mapbox`, but not with `px.scatter_mapbox`.
