### ISSUE TITLE
I have a line of text, for eg. "I am doing really good!"

### ISSUE THREAD

**Issue by sha-shank469** [plotly/plotly.py#4471]
what I want to do is loop through all the words in the sentence and apply different style like color and opacity to each word and show it
on plotly by passing it through callback, I'm unable to get the desired results. any help would be appreciated.

**Comment by Coding-with-Adam** [comment]
hi @sha-shank469 
This seems like the perfect question for the [Plotly forum](https://community.plotly.com/). Can you please post a new topic on there with this question. You are more likely to get a community member to help you if you also post what you've tried so far with your code. 

We'll reopen this issue if you can't find the solution on the forum.
