### ISSUE TITLE
Save order is always wrong

### ISSUE THREAD

**Issue by zhimin-z** [plotly/plotly.py#4481]
I am using Plotly and my Python environment is as follows:
```
python==3.1.6
plotly==5.18.0
```
When I write the following code and execute:
```
import plotly.express as px

# Create multiple figure objects
fig1 = px.scatter(x=[1, 2, 3], y=[4, 5, 6], title="Figure 1")
fig2 = px.bar(x=[1, 2, 3], y=[7, 8, 9], title="Figure 2")
fig3 = px.line(x=[1, 2, 3], y=[10, 11, 12], title="Figure 3")

# Specify the order in which you want to save the figures
figures_to_save = [fig1, fig2, fig3]

# Loop through the figures and save them in the desired order
for i, fig in enumerate(figures_to_save):
    fig.write_image(f"figure_{i+1}.png")
```
The generated figure is misordered as follows:
**figure_1.png**
![image](https://github.com/plotly/plotly.py/assets/8592144/a2e39aaf-0545-49ae-89bc-364fd2e18fd0)
**figure_2.png**
![image](https://github.com/plotly/plotly.py/assets/8592144/e109f910-ebbd-4ba4-87e4-9969a36d71d0)
**figure_3.png**
![image](https://github.com/plotly/plotly.py/assets/8592144/ecad5e9b-bbfb-47a2-ba22-727d73dc08c6)

I wonder why this happens and how I can fix it?

**Comment by Coding-with-Adam** [comment]
hi @zhimin-z 
I ran your code and got all the graph images to save in the right order with the correct graph title. Probably doesn't make a difference, but I'm using Python==3.10
