### ISSUE TITLE
Barchart string labels not displayed after 1001th

### ISSUE THREAD

**Issue by silicium14** [plotly/plotly.py#450]
- Plotly python version : 1.9.5

When a barchart has 1001+ string labels, the labels after the 1001th are not displayed on the axis.
Here is a capture of the top of the graph generated by the python script below.

![graph top missing labels](https://cloud.githubusercontent.com/assets/13800015/14882856/35885a12-0d3b-11e6-866a-9b4daa98cc2f.png)

```python
import plotly.offline
import plotly.graph_objs as go

n = 1005
trace = go.Bar(
    y=["Label {}".format(i+1) for i in range(n)],
    x=[1.0]*n,
    orientation="h",
)
layout = go.Layout(
    height=30*n,
	width=600
)

plotly.offline.plot(
    go.Figure(data=[trace], layout=layout),
)

```

**Comment by etpinard** [comment]
@silicium14 Thanks for writing in.

This is an issue with plotly.js; please subscribe to https://github.com/plotly/plotly.js/issues/484 for the latest development info.
