### ISSUE TITLE
FutureWarning in _core.py

### ISSUE THREAD

**Issue by ramedina86** [plotly/plotly.py#4505]
Using `plotly==5.18.0` and `pandas==2.2.0`.

I get the following `FutureWarning`

```
.venv/lib/python3.12/site-packages/plotly/express/_core.py:2065: FutureWarning: When grouping with a length-1 list-like, you will need to pass a length-1 tuple to get_group in a future version of pandas. Pass `(name,)` instead of `name` to silence this warning.
  sf: grouped.get_group(s if len(s) > 1 else s[0])
```

I can suppress the warning by fixing a line in `get_groups_and_orders()`

`sf: grouped.get_group(s if len(s) > 1 else s[0])`

to

`sf: grouped.get_group(s if len(s) > 1 else (s[0], ))`

In my case, this only happens when I include color, which seems to trigger the grouping by tuple:

This doesn't work: `fig = px.bar(main_df, x='role', y='count', color='role')`
This works: `fig = px.bar(main_df, x='role', y='count')`

**Comment by Coding-with-Adam** [comment]
Thanks for reporting, @ramedina86 . Adding a similar report: https://github.com/plotly/plotly.py/issues/4500

**Comment by MarcoGorelli** [comment]
@LiamConnors I think this is should be addressed now, trying this out I get no warning

**Comment by LiamConnors** [comment]
Thanks @MarcoGorelli. I think it was just never closed out when it was originally fixed
