### ISSUE TITLE
Plotly.rs call for maintainers

### ISSUE THREAD

**Issue by igiagkiozis** [plotly/plotly.py#4511]
Hello chaps,

I've started and maintained [plotly.rs](https://github.com/igiagkiozis/plotly). As the name suggests, this library builds on top of the excellent work by the plotly.py community.

However, due to a change of circumstances I can no longer actively maintain and manage the project or the community. The library is quite well regarded in the the rust ecosystem with about 910 github stars, has [good documentation](https://igiagkiozis.github.io/plotly/content/getting_started.html) that follows closely the plotly.py documentation and it would be a shame to be left unmaintained which would force people to create forks that would only serve to split the collective effort.

Therefore I would be more than happy to donate the project (including [crates.io/plotly](https://crates.io/crates/plotly) naturally) to you guys if you'll have it.

**Comment by alexcjohnson** [comment]
@igiagkiozis thanks so much for creating this package and taking it as far as you have! It's obvious just from a quick perusal that it gets a lot of use and is well loved. We don't have much Rust experience on the Plotly staff, but it's just a matter of giving the repo a home and others in the community are able to take on maintenance (which seems to be the case based on the discussion in https://github.com/igiagkiozis/plotly/issues/177) we would be more than happy to bring it into our GitHub org. Feel free to send me a note alex@plot.ly if you'd like to discuss details.
