### ISSUE TITLE
Update to plotly.js 2.29.0

### ISSUE THREAD

**Issue by qchenevier** [plotly/plotly.py#4513]
Hi all,

First of all, many thanks for the great work on this library. I've been using it for years !

On all arm-based (M1, M2, M3) macs, time series scatterplots are broken for more than 1000 points, it's an issue know with plotly.js (<2.28) and webgl on macs: https://github.com/plotly/plotly.js/issues/6820

Of course, we can still disable webgl by using the parameter `rendermode="svg"` for some graphs. But for many points, it becomes very laggy. 

It has been solved in plotly.js version 2.28: https://github.com/plotly/plotly.js/pull/6830

It would be great to be able to update the version of plotly.js in plotly.py to be able to benefit of this fix, as it would solve several reported issues:
- https://github.com/plotly/plotly.py/issues/4298
- https://github.com/plotly/plotly.py/issues/4388

**Comment by BlastoiseBlue** [comment]
I believe there's already a PR to upgrade plotly.js to 2.29.0: https://github.com/plotly/plotly.py/pull/4476

**Comment by qchenevier** [comment]
Solved with the release of v5.19.0: https://github.com/plotly/plotly.py/releases/tag/v5.19.0

Thank you all !
