### ISSUE TITLE
Sankey align plotly v5.19.0, initial issue #6800

### ISSUE THREAD

**Issue by gaetpinon** [plotly/plotly.py#4528]
Hi everyone, I saw an 'align' property was added in plotly v5.19.0 to solve this issue. Unfortunately I can't make it work. I can try any of the 4 values ['center', 'right', 'left', 'justify'], but nothing will change. I tried with the same example as in the [plotly sankey tutorial](https://plotly.com/python/sankey-diagram/#node-alignment). I have the latest plotly version v5.19.0

Do you have any idea of what could be the reason for this problem?

Thank you for your help
@adamreeve @archmoj

**Comment by LiamConnors** [comment]
Hi @gaetpinon, what kind of environment are you running the example in? A notebook or some particular IDE?
What version of Plotly.js do you see if you hover over the Plotly logo? 

<img width="930" alt="image" src="https://github.com/plotly/plotly.py/assets/12749831/f26bf82a-573b-4707-bd7b-84007c926a11">

**Comment by gaetpinon** [comment]
Hi @LiamConnors. I am running it on VS code in a jupyter Notebook. I have plotly.js v2.20.0. How can I upgrade it to yours?

**Comment by LiamConnors** [comment]
Hi @gaetpinon, VS Code has its own version of Plotly.js so it needs to be updated by VS Code
This issue provides more context: https://github.com/plotly/plotly.py/issues/4181
