### ISSUE TITLE
Time Series and Date Axes in Python

### ISSUE THREAD

**Issue by wangsan1988** [plotly/plotly.py#4532]
https://plotly.com/python/time-series/

![image](https://github.com/plotly/plotly.py/assets/30817233/5c9357ad-939f-452d-9afa-8565abbbfb1c)
as seen above，auto-sets the axis type to a date format . i want to kown ,can we modify the format , such as  jan 2018 --->2018-01, cause jan jul.. is not friendly for user non-English-speaking country,especially for my leader.
thank you

**Comment by Coding-with-Adam** [comment]
hi @wangsan1988 
Good question. You should be able to [modify the tick text/values](https://plotly.com/python/tick-formatting/#tickmode--array). 

Let us know if this doesn't work.
