### ISSUE TITLE
only the last 8 figures shown when using for-loop

### ISSUE THREAD

**Issue by Koliham** [plotly/plotly.py#4533]
I have a jupyter-notebook, where I plot several plotly scatter figures via a for-loop:

```
for i in myColumnList:
    for j in myColumnList
        fig = px.scatter(dft, x=i, y=j)
        fig.show()
```

As soon as more than 8 figures are shown, the older ones start to vanish.
How can I fix this?

plotly==5.16.0
jupyter==1.0.0
jupyter-client==6.1.12
jupyter-console==6.4.2
jupyter-contrib-core==0.4.2
jupyter-server==1.24.0
jupyter_core==5.3.1
jupyterlab_server==2.24.0

**Comment by Coding-with-Adam** [comment]
hi @Koliham 
Can you please post this on the [plotly forum](https://community.plotly.com/). 
And provide the full code and data so we can replicate this error locally on our computer? 

Thank you,
