### ISSUE TITLE
Bug: Recently added cornerradius/barcornerradius not functioning

### ISSUE THREAD

**Issue by jacquex17** [plotly/plotly.py#4535]
Hi,

In the most recent update, trace.marker.cornerradius and layout.barcornerradius were added to add rounding to bar charts.

This has been a **long** awaited feature and I'm excited it's here! Unfortunately when trying to implement this to my own code, it didn't appear to do anything - and when testing using the code in the docs, the same problem occurs.

Steps to reproduce:
- Create new virtual environment
- pip install plotly, pandas
- Ensure plotly is on latest version, 5.19.0
- Use any of the examples found at https://plotly.com/python/bar-charts/#rounded-bars

The charts produced have no rounded corners, and changing the value of cornnerradius/barcornerradius has no effect.

Expected:
![image](https://github.com/plotly/plotly.py/assets/115947475/2158bcfb-0d3d-4639-9d6c-a6bb590b5b26)

Actual:
![image](https://github.com/plotly/plotly.py/assets/115947475/426716a0-56fc-45fd-b0cc-8c70f6ab6aee)

**Comment by LiamConnors** [comment]
Hi @jacquex17, what kind of environment are you running the example in? A notebook or some particular IDE?
What version of Plotly.js do you see if you hover over the Plotly logo?

<img width="951" alt="image" src="https://github.com/plotly/plotly.py/assets/12749831/ffffe013-1ec0-47cd-957d-fae2f403474e">

**Comment by jacquex17** [comment]
> Hi @jacquex17, what kind of environment are you running the example in? A notebook or some particular IDE? What version of Plotly.js do you see if you hover over the Plotly logo?
> 
> <img alt="image" width="951" src="https://private-user-images.githubusercontent.com/12749831/308994628-ffffe013-1ec0-47cd-957d-fae2f403474e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyMjcyOTgsIm5iZiI6MTcwOTIyNjk5OCwicGF0aCI6Ii8xMjc0OTgzMS8zMDg5OTQ2MjgtZmZmZmUwMTMtMWVjMC00N2NkLTk1N2QtZmFlMmY0MDM0NzRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI5VDE3MTYzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkZGI3MjE5OGFkNDJkMmE2OTQ2ZjI4MWY3NzExZjRlZTQ3N2FiNGYzMDZhMjE2MWJjNGNhMmNiMTkxYmZhZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LG_7PPNR_Kk3SQs-5mPE3tzAnDdG54IlpFb_-HleGyg">

Hey @LiamConnors, thanks for getting back so quickly - sounds like this might be user error!

I'm running this in a notebook, on Plotly.js v2.20.0 - which I'm guessing is too old?

**Comment by LiamConnors** [comment]
Yeah, it would need to be 2.29.1. it sounds like the notebook isn't picking up the Plotly.js version in the Plotly.py you have installed. Some IDEs use their own built in version of Plotly.js. For example, VS Code. This issue gives a bit more context
https://github.com/plotly/plotly.py/issues/4181

**Comment by jacquex17** [comment]
> Yeah, it would need to be 2.29.1. it sounds like the notebook isn't picking up the Plotly.js version in the Plotly.py you have installed. Some IDEs use their own built in version of Plotly.js. For example, VS Code. This issue gives a bit more context #4181

Interesting, is there still no way for VSCode to dynamically pick up plotly.js from the plotly installation?

I can confirm that this **does** work when running through Jupyter Notebooks - so I suppose I'll create my graphs there
