### ISSUE TITLE
Some symbols aren't displayed properly in 3d-plots

### ISSUE THREAD

**Issue by vlas-sokolov** [plotly/plotly.py#454]
I am having problems rendering some specific marker symbols in 3d-scatter mode. In particular, stars  do not seem to work in both [online](https://plot.ly/~vlas-sokolov/3/) or offline (below) modes.

In the example below, both _green_ and _orange_ data points _should be rendered as stars_ - and the green ones do get displayed correctly in the legend - but in the scatter plot they seem to be broken.
![no-stars](https://plot.ly/~vlas-sokolov/3.png)

``` python
import plotly
import numpy as np
import pandas as pd

df_circ = pd.DataFrame(np.random.randn(50,3),  columns=list('XYZ'))
df_star1 = pd.DataFrame(np.random.randn(5,3)*5,columns=list('XYZ'))
df_star2 = pd.DataFrame(np.random.randn(5,3)*5,columns=list('XYZ'))

data_circles = dict(x=df_circ['X'], y=df_circ['Y'], z=df_circ['Z'],
                    mode = 'markers', type = 'scatter3d', opacity=0.5,
                    marker=dict(symbol='circle'))

data_stars1 = dict(x=df_star1['X'], y=df_star1['Y'], z=df_star1['Z'],
                  mode = 'markers', type = 'scatter3d',
                  marker=dict(symbol='star'))
data_stars2 = dict(x=df_star2['X'], y=df_star2['Y'], z=df_star2['Z'],
                  mode = 'markers', type = 'scatter3d',
                  marker=dict(symbol=['star']*len(df_star2)))

fig = dict(data=[data_circles, data_stars1, data_stars2])
# Use py.iplot() for IPython notebook
url = plotly.offline.plot(fig, filename='no-stars')
```

Can this be looked into?

**Comment by etpinard** [comment]
Not all SVG marker symbols are available in 3D plots. See full list [here](https://plot.ly/python/reference/#scatter3d-marker-symbol).

That said, we should output better than `undefined`. Thanks for bringing this up.

**Comment by vlas-sokolov** [comment]
Ah, I didn't find the proper docs for it then, thanks a bunch! 

I'm leaving the issue open in case you want to  reference some PRs on top - feel free to close it otherwise.
