### ISSUE TITLE
not all hoverdata are displayed when there is a large amount of data

### ISSUE THREAD

**Issue by AlesyaSeliazniova30032012** [plotly/plotly.py#4541]
hi. I have big dataframe with shape (37363, 18). 
Use go.Scatter plot for data visualization, mode - 'markers+lines'
some part of my code:
`
fig = go.Figure()
group_by = 'timestamp'
param = 'profit'
cumulative_sum = df.groupby(group_by)[param].sum().reset_index()
fig.add_trace(go.Scatter(x=cumulative_sum[group_by], y=cumulative_sum[param], mode='lines', name=param, showlegend=True,
                            marker=dict(color=color, size=8), hovertemplate='<extra></extra>')) 
for _, row in cumulative_sum.iterrows():
            group = row[group_by]
                plot_data = df[df[group_by] == group]
                hover_data = "<br>".join([f"{col1} £{col2}@{col3} [{param}] [{col4}] [{col5}, {col6}]" 
                                        for col1, col2, col3, param, col4, col5, col6 
                                        in zip(plot_data[col1], plot_data[col2], plot_data[col3], plot_data[param], plot_data[col4], plot_data[col5], plot_data[col6])])
                fig.add_scatter(x=[group], y=[row[param]], mode='markers', name='', showlegend=False,
                            text=hover_data, marker=dict(color=color))  

fig.update_layout(
       xaxis_title=group_by,
        yaxis_title='profit',
        legend=dict(x=1, y=1, traceorder='normal'),
        xaxis=dict(type='category'),
        height=800
    )
    fig.show()`

as a result, if there is not much timestamp data, it is displayed when you hover over the marker, if there is a lot, then not. Is it possible to solve this somehow? Thanks
![image](https://github.com/plotly/plotly.py/assets/116648459/786dcdb1-9ada-41de-aaa3-86f76e135798)
![image](https://github.com/plotly/plotly.py/assets/116648459/9384a6aa-b65c-4ddb-8387-2202bf4128cd)

**Comment by AlesyaSeliazniova30032012** [comment]
I found intermediate solution: set hovermode="x unified"
`
fig.update_layout(
        xaxis_title=group_by,
yaxis_title='profit',
legend=dict(x=1, y=1, traceorder='normal'),
xaxis=dict(type='category'),
height=800,
        hovermode="x unified"
    )`
but it is difficult to figure out where what data belongs.

**Comment by AlesyaSeliazniova30032012** [comment]
And can someone tell me how to modify the code above to call Scatter once with mode='lines+markers' so that the graphs are drawn correctly

**Comment by Coding-with-Adam** [comment]
hi @AlesyaSeliazniova30032012 
Can you please post this question on the [community forum](https://community.plotly.com/).

Just make sure to share your data as well so we can [reproduce this locally](https://community.plotly.com/t/how-to-write-a-minimal-reproducible-example-mre/61502).
