### ISSUE TITLE
Parallel coordinates mixed categrical and numerical values

### ISSUE THREAD

**Issue by MaAl13** [plotly/plotly.py#4558]
I have the following problem that i want to use the parallel coordinates plot for a dataframe where some columns are categorical (strings) and others are numerical. In my case the categorical ones are just ignored for the plotting. How can i fix this?

**Comment by Coding-with-Adam** [comment]
hi @MaAl13 
These questions are usually best asked and answered on the forum. 
I would also recommend you share sample data and some code that shows what you've tried so far. Something that we can replicate locally.
