### ISSUE TITLE
multiple Legends not working in VS code 

### ISSUE THREAD

**Issue by Camilochiang** [plotly/plotly.py#4560]
with plotly 5.20.0 , [addding multiple legend 1](https://plotly.com/python/legend) within VSCode version 1.87.2 (Windows_NT x 64) do not produce the expected results (a.k.a it only show one legend) when either using the default render (a.ka. fig.show()) or vscode render (a.ka render = ‘vscode’)

this behaivor can be solve with [renderer = ‘png’](https://plotly.com/python/renderers/) but the full idea of using plotly is to have interactive figures, so for me this is a bug.

I will not add code as this can be tested with the example code from multiple legend

also, when using an invalidad argument (a.ka. “render”) and not “renderer”, fig.show do not give an error and just ignore the argument. shouldn’t the function check for non valid arguments?

**Comment by ndrezn** [comment]
This possibly will be solved once a version of VSCode including: https://github.com/microsoft/vscode-notebook-renderers/pull/195 is released. Right now VSCode is running an older version of Plotly.js by default which means it's not using the latest renderer.

**Comment by ndrezn** [comment]
You can also see @LiamConnors's workaround here, where you specify a renderer on `fig.show()`: https://github.com/plotly/plotly.py/issues/4549#issuecomment-1999781656

```python
fig.show(renderer='notebook')
```
