### ISSUE TITLE
Add HTTPS support for streaming

### ISSUE THREAD

**Issue by BRONSOLO** [plotly/plotly.py#457]
@chriddyp @theengineear @Kully

**Comment by chriddyp** [comment]
Does setting the port to `443` work? https://github.com/chriddyp/chunked_requests/blob/master/chunked_requests/chunked_request.py#L8

**Comment by BRONSOLO** [comment]
@chriddyp It seems that port is not configurable from the wrapper. We are hardcoding `80` https://github.com/plotly/plotly.py/blob/2594076e29584ede2d09f2aa40a8a195b3f3fc66/plotly/plotly/plotly.py#L485, correct?

**Comment by theengineear** [comment]
^^ Yah. I think we talked about allowing it as a setting at one point or another but didn't have a use case? Does it make sense in our config files?

**Comment by chriddyp** [comment]
I think like plotly's streaming wasn't https for a while, which is why we hard coded it

**Comment by BRONSOLO** [comment]
Cool! For our config file, wouldn't it be easy to look for the `HTTPS` or `HTTP` protocol for the streaming domain and set the port accordingly? We could default to `HTTP` if nothing is specified.

**Comment by BRONSOLO** [comment]
I'm going to tackle this if nobody has started yet!

**Comment by chriddyp** [comment]
@BRONSOLO yeah, but we don't store the protocal, it's just like `stream.plot.ly`

**Comment by BRONSOLO** [comment]
@chriddyp couldn't we just start handling the protocol if it's included in the domain? So if the streaming domain is specified as `stream.plot.ly` ---> we default to port 80, `http://stream.plot.ly` ---> port 80, `https://stream.plot.ly` ---> port 443. Sorry if i'm missing something : )

**Comment by BRONSOLO** [comment]
@chriddyp @theengineear this is a little more involved than simply setting the port. We'll need to modify `chunked_requests` so that it uses `HTTPSConnection` when SSL is enabled.
