### ISSUE TITLE
why isn't fig.update_zaxes implimented

### ISSUE THREAD

**Issue by whitequill** [plotly/plotly.py#4571]
yes. this is a feature request.  Why isn't **update_zaxis** implemented?  I want to run `fig.update_zaxes(type="log")` but, I can't cause it doesn't exist. why?

**Comment by gvwilson** [comment]
Hi - we have a long list of feature requests, so unfortunately we are not able to address all feature requests. If you would like to submit a PR, we will try to review it promptly. Thanks - @gvwilson
