### ISSUE TITLE
Making Radar Charts: make_trace_kwargs uses df.append which has been deprecated in pandas 2.0

### ISSUE THREAD

**Issue by RoshnikRahat** [plotly/plotly.py#4582]
Hello,

While making a radar chart using code from the pIotly documentation 

**Relevant Code:** 
fig = px.line_polar(df, r='max-age', theta='category', line_close=True)
fig.update_traces(fill='toself')
 
I got the error:
**AttributeError**: 'DataFrame' object has no attribute 'append'. Did you mean: '_append'?

which came from the \plotly\express\_core.py and the make_trace_kwargs() function, corresponding to line:

**trace_data = trace_data.append(trace_data.iloc[0])**

**Comment by Coding-with-Adam** [comment]
Hi @RoshnikRahat 
Could you please share the full reproducible code with us?

**Comment by phyto-cosmosis** [comment]
Experienced same issue, see example code from https://plotly.com/python/radar-chart/
`import plotly.express as px
import pandas as pd
df = pd.DataFrame(dict(
    r=[1, 5, 2, 2, 3],
    theta=['processing cost','mechanical properties','chemical stability',
           'thermal stability', 'device integration']))
fig = px.line_polar(df, r='r', theta='theta', **line_close=True**)
fig.show()`

Changing argument to false will fix error but leave line open.

**Comment by Coding-with-Adam** [comment]
hi @phyto-cosmosis 
I get this result when I do `line_close=False`. You get something different?

![image](https://github.com/plotly/plotly.py/assets/32049495/c4d4ccde-110b-41df-900d-d35b8c459a27)

**Comment by phyto-cosmosis** [comment]
> hi @phyto-cosmosis I get this result when I do `line_close=False`. You get something different?
> 
> ![image](https://private-user-images.githubusercontent.com/32049495/341790972-c4d4ccde-110b-41df-900d-d35b8c459a27.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkwMDQ2NDQsIm5iZiI6MTcxOTAwNDM0NCwicGF0aCI6Ii8zMjA0OTQ5NS8zNDE3OTA5NzItYzRkNGNjZGUtMTEwYi00MWRmLTkwMGQtZDM1YjhjNDU5YTI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIxVDIxMTIyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzYzIwYTBlZmY2Y2JjZjMxNWQ4M2FmZTkxZDhhNDZkN2U2NzExNjViNDkyMTk3YzczNjJhMDUyZDNkZmVmNTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.a0ZBtNtgODQ1aawX3YkxTWj7ZlyZNXuLD-8O6QqfQjI)

Hi @Coding-with-Adam, yeah that’s what I get with set to false. Circumvents the error but has the obvious impact of line now not being closed. Dependency issue? Pandas?

**Comment by Coding-with-Adam** [comment]
hi @phyto-cosmosis 
I'm not getting this error: " 'DataFrame' object has no attribute 'append'. Did you mean: '_append'?"

Can you share what version of Plotly and pandas you're using?

**Comment by gvwilson** [comment]
Hi - we are tidying up stale issues and PRs in Plotly's public repositories so that we can focus on things that are still important to our community. Since this one has been sitting for a while, I'm going to close it; if it is still a concern, please add a comment letting us know what recent version of our software you've checked it with so that I can reopen it and add it to our backlog. If you'd like to submit a PR, we'd be happy to prioritize a review, and if it's a request for tech support, please post in our community forum. Thank you - @gvwilson
