### ISSUE TITLE
zorder doesn't work on version 5.21.0

### ISSUE THREAD

**Issue by khisr0w** [plotly/plotly.py#4583]
The `zorder` attribute was added recently. However, the following code does not work as expected (exact code as [here](https://github.com/plotly/plotly.py/issues/2345#issuecomment-2064818826)):
```python
import plotly
import plotly.graph_objects as go

fig = go.Figure(
    go.Bar(
        x=[0, 1, 2],
        y=[1, 2, 3]
    ),
)
fig.add_trace(
    go.Scatter(
        x=[0, 1, 2],
        y=[3, 2, 1],
        zorder=-2
    )
)

fig.update_layout(
    title=dict(text=f"{plotly.__version__ = }")
)
fig.show()
```
Expected Behavior: Bar chart should have a higher z-order, meaning it should be at the front.
Instead, the code produces the following:
![image](https://github.com/plotly/plotly.py/assets/16806141/b6a57fa1-f4fa-4c74-a7e0-9ecbebf4c638)

**Comment by Farkites** [comment]
Hi @khisr0w I'm not able to reproduce the issue that you have mentioned. Using your code I get the behaviour is as expected:
![newplot (3)](https://github.com/plotly/plotly.py/assets/35932204/ec9e9f88-4b3c-4b27-a3de-52eaea53b4c4)

**Comment by khisr0w** [comment]
@LiamConnors As a matter of fact, yes. The JS version seems to lower than what is shown in your case:
![image](https://github.com/plotly/plotly.py/assets/16806141/ea4c9579-2ce1-4b83-9b7c-acc095629df3)
Is there a specific issue with VS Code?

**Comment by LiamConnors** [comment]
@khisr0w yeah, it can be an issue in VS Code as by default it uses its own bundled version of Plotly.js

This page gives a bit more detail.
https://plotly.com/python/troubleshooting/#vscode-notebook-nteract-and-streamlit-problems

If you call `fig.show` while setting the `renderer` to `'notebook'`, it should use the Plotly.py install version instead.

```
fig.show(renderer='notebook')
```

**Comment by khisr0w** [comment]
Worked like a charm. Thanks, @LiamConnors :)
