### ISSUE TITLE
Shared X-axis spike remove tick marks from other subplots in Plotly?

### ISSUE THREAD

**Issue by AlanCPSC** [plotly/plotly.py#4584]
When I attempt to create a shared hover spike across multiple subplots, I immediately lose the xticks on those subplots. 

Is there any way I can fix this? I want to see the xtick labels on ALL of my subplots.

## Reproducible Code
```
from plotly.subplots import make_subplots
import plotly.graph_objects as go

fig = make_subplots(rows=3, cols=1,
                    shared_xaxes=True,
                    vertical_spacing=0.10)

fig.add_trace(go.Scatter(x=[0, 1, 2], y=[10, 11, 12]),
              row=3, col=1)

fig.add_trace(go.Scatter(x=[2, 3, 4], y=[100, 110, 120]),
              row=2, col=1)

fig.add_trace(go.Scatter(x=[3, 4, 5], y=[1000, 1100, 1200]),
              row=1, col=1)

fig.update_layout(height=600, width=600,
                  title_text="Stacked Subplots with Shared X-Axes")

fig.update_layout(
    xaxis_showticklabels=True,
    xaxis2_showticklabels=True,
    xaxis3_showticklabels=True,
)

# Uncomment these lines to draw the shared hover spike
# fig.update_traces(xaxis='x')
# fig.update_xaxes(spikemode='across+marker')

fig.show()
```

## Before and After Chart
[![enter image description here][1]][1]

[1]: https://i.stack.imgur.com/kkOHH.png

**Comment by Coding-with-Adam** [comment]
Thanks for reporting @AlanCPSC . This looks like a bug. 
@archmoj here is [the code](https://codepen.io/charming-data/pen/JjqjJzj).

**Comment by archmoj** [comment]
I am not sure we should call this a bug there is only one "used" `xaxis` in the @Coding-with-Adam's codepen.

**Comment by archmoj** [comment]
Please see this codepen: https://codepen.io/MojtabaSamimi/pen/pomorYo
It looks one could make use of `anchor: 'free'` and position the overlaying axis to achieve the desired behaviour.

**Comment by Coding-with-Adam** [comment]
thanks @archmoj .
Closing this issue as solved. @AlanCPSC if you still have questions, please let us know.
