### ISSUE TITLE
Wrong setting of histnorm in the method  make_hist, FigureFactory.create_distplot

### ISSUE THREAD

**Issue by empet** [plotly/plotly.py#459]
`FigureFactory.create_distplot` is intended to compare the  histogram of a data set with  the kde estimation of the probability density function, and more. But Plotly Histogram can create  5 types of histograms, each one set via the key `histnorm`.
 The method `create_hist` has a drawback. It does not choose the right value for the histnorm key.  Its default  value is `histnorm='probability'`:
[https://github.com/plotly/plotly.py/blob/master/plotly/tools.py#L5084](https://github.com/plotly/plotly.py/blob/master/plotly/tools.py#L5084),  and this  is contrary to the theoretical definition of this kind of histogram, and that of the  probability density function (pdf).

When `histnorm='probability'`, the height  of a bar in histogram equals the probability that data fall within the corresponding bin.  Comparing the kde estimation of the pdf with such a histogram means that we admit that the pdf takes only values in [0,1], and this  is not right.

 In a histogram plotted with histnorm='probability density', the height `h`   of a bar is such that h*bin_size=probability that data fall in that bin=bar area. The bar area approximates the area under the pdf graph above that bin.
Hence the probability density function (pdf) or its kde estimation should be compared to the Plotly Histogram corresponding to `histnorm='probability density'`.
I illustrate below the  plot of the pdf of  Beta distribution over the two types of histograms, to point out the drawback of the `make_hist` method.
![beta_probability](https://cloud.githubusercontent.com/assets/3627253/15268520/7694b5a8-19ea-11e6-88cc-8c7f022f13f4.png)
![beta_probability_density](https://cloud.githubusercontent.com/assets/3627253/15268521/7b43e4c0-19ea-11e6-9911-4f6f4eac030f.png)

 See also in [https://plot.ly/~chelsea_lyn/11601/group-1-group-2-group-3-group-4-group-1-group-2-group-3-group-4-group-1-group-2-/](https://plot.ly/~chelsea_lyn/11601/group-1-group-2-group-3-group-4-group-1-group-2-group-3-group-4-group-1-group-2-/)  how distant from the corresponding histograms are the  last two pdfs.
Here [http://nbviewer.ipython.org/0f42b607de8f0d0c50b0ffb0ccfdff08](http://nbviewer.ipython.org/0f42b607de8f0d0c50b0ffb0ccfdff08)  is the updated plot with `histnorm='probability density'`.

**Comment by yankev** [comment]
@empet: Did you use plotly to make your beta distribution examples? I was trying to make something similar with a beta(2,5) distribution, and the estimated density curve doesn't turn out the way you would expect (thus there might be an issue with this as well).
![screen shot 2016-05-17 at 12 52 08 pm](https://cloud.githubusercontent.com/assets/12302455/15333230/d747e278-1c36-11e6-926d-afc66f5a7655.png)

**Comment by empet** [comment]
@yankev:  Here are my experiments [http://nbviewer.jupyter.org/gist/empet/1bf38aea056f1d60481e600fc68c21be](http://nbviewer.jupyter.org/gist/empet/1bf38aea056f1d60481e600fc68c21be). 

Since in `create_distplot` `histnorm` is set as ` 'probability'`, it's clear that it doesn't work well.

**Comment by erikerlandson** [comment]
I'm also having this problem.  Change the bin size, and it alters the displayed density values on the y axis:
http://erikerlandson.github.io/assets/html/distplot_bug.html

**Comment by jackparmer** [comment]
Closing via https://github.com/plotly/plotly.py/pull/473
