### ISSUE TITLE
update development instructions for MacOS

### ISSUE THREAD

**Issue by gvwilson** [plotly/plotly.py#4591]
Following instructions in `contributing.md` on MacOS Sonoma 14.4.1 on Apple M3 with Apple clang version 15.0.0 installed via Xcode:

- `pip install -r packages/python/plotly/optional-requirements.txt` fails while trying to install `pyzmq` if the conda environment has been created with Python 3.12. Fix: use `conda create -n plotly-dev python=3.11.8`.
- The instructions in `contributing.md` leave the environment with `pytest==3.5.1`, which fails to run. Fix: install `pytest=8.1.1`.
- `pytest packages/python/plotly/plotly/tests` produces failures in `packages/python/plotly/plotly/tests/test_optional` and `packages/python/plotly/plotly/tests/test_orca`. The latter may be caused by `orca` not being installed (`which orca` produces nothing). However, `conda install -c plotly plotly-orca` produces a `PackagesNotFound` error.
  - Temporary solution is to install `orca` manually (download .zip file etc.)
  - Had to `conda install poppler` as well (suggested by error messages that came up while running tests)
  - But still get errors from `orca` tests

**Comment by emilykl** [comment]
I was wondering why such an old version of Pytest gets installed... just realized it's **pinned** in `optional-requirements.txt` 😳 :

`pytest==3.5.1`

That's an easy fix and we should do ASAP.

Related issue: https://github.com/plotly/plotly.py/issues/4570
