### ISSUE TITLE
Plotly offline will not work upon page reload or from another client; will not work with ipywidgets

### ISSUE THREAD

**Issue by aggFTW** [plotly/plotly.py#463]
Hi,

We found out that the following PR: https://github.com/plotly/plotly.py/pull/379
ends up breaking plotly offline on page refreshes.

Upon first execution:
![plotly0](https://cloud.githubusercontent.com/assets/654204/15309866/7e62f356-1b9f-11e6-9690-2fae940ec51c.PNG)

And upon refresh:
![plotly1](https://cloud.githubusercontent.com/assets/654204/15309869/85838de4-1b9f-11e6-804e-80a2d5bf1369.PNG)

It seems like what we really should do is have an `if` statement on javascript that re-registers `Plotly`. 

At the same time, if we want to use plotly with ipywidgets in an `output` widget, that check on `__PLOTLY_OFFLINE_INITIALIZED` in that PR would make it impossible to re-register `Plotly` from `init_notebook_mode` by any other browser connected to the same kernel or the same browser on a refresh. Again, this check to not re-register should be done on the javascript side, because it is the front end that knows whether `Plotly` is defined or not, not the server.

Thanks!
Alejandro

cc @msftristew @ellisonbg @tc0312

**Comment by aggFTW** [comment]
Cell 1:
```
from plotly.offline import init_notebook_mode
from plotly.graph_objs import Pie, Figure, Data
from plotly.offline import iplot

import plotly as plt
plt.__version__
```

Cell 2:
```
init_notebook_mode()
```

Cell 3:
```
data = [Pie(values=[1,2,3])]
fig = Figure(data=Data(data))
iplot(fig, show_link=False)
```

**Comment by aggFTW** [comment]
We suspect this is related: https://github.com/plotly/plotly.py/issues/458

**Comment by yankev** [comment]
@aggFTW Yea, it appears that removing the `check` in PR #379, like you said, fixes the issue.

**Comment by aggFTW** [comment]
@yankev well, removing the check + adding the javascript `if` statement would be the right thing, it seems like. Are you working on it?

**Comment by yankev** [comment]
@aggFTW yep, @mdtusz and I are looking at it right now.

**Comment by aggFTW** [comment]
Ok, thanks! :smile:

**Comment by aggFTW** [comment]
@tc0312 and I were looking at this and we think the python check should be removed and the javascript should look something like this (we haven't tested it):

```
display(HTML("<script type='text/javascript'>" +
	"if (typeof window.Plotly === 'undefined') {" +
	"define('plotly', function(require, exports, module) {" +
	"get_plotlyjs()" +
	"});" +
	"require(['plotly'], function(Plotly) {" +
	"window.Plotly = Plotly;" +
	"});" +
	"}" +
	"</script>"))
```

We hope it helps!

**Comment by mdtusz** [comment]
Yep! [This PR](https://github.com/plotly/plotly.py/pull/466) will solve it - just cleaning up a few things then it will be merged in.

**Comment by msftristew** [comment]
Great stuff, thanks @mdtusz.
