### ISSUE TITLE
feat: absolute draw order / rank property

### ISSUE THREAD

**Issue by gvwilson** [plotly/plotly.py#4676]
Currently, there is no way to set an absolute draw order for traces. It would be very useful to have a property to determine the global draw order, e.g. to give a trace the value of 1 to make sure it is always drawn on top of all other traces and another trace the value of 9999 to make sure it is drawn behind all other traces.

**Comment by gvwilson** [comment]
Let me break down the current behavior a little:
(0) in SVG, there's no concept like `z-index` in HTML; items later in the DOM are always on top of items earlier in the DOM.
(1) if you have multiple sets of x or y axes overlaying each other, all the traces on the same axes are grouped together and either in front or behind other axes. I would need to verify the details, but I believe higher-index x axes are in front, and for the same x axis higher-index y axes are in front, ie x2y2>x2y>xy2>xy.
(2) Traces of different type have a fixed order, as we put them all in different "layer" groups:
```
    traceLayerClasses: [
        'imagelayer',
        'heatmaplayer',
        'contourcarpetlayer', 'contourlayer',
        'funnellayer', 'waterfalllayer', 'barlayer',
        'carpetlayer',
        'violinlayer',
        'boxlayer',
        'ohlclayer',
        'scattercarpetlayer', 'scatterlayer'
    ],
```
Meaning scatter traces are always on top, image traces are always on bottom, everything in between is as in this list.
(3) After that, traces of the same type are ordered by their index in `data`.

So with all of that in mind, which of these three categories describes your use cases?

It would be fairly easy to add an attribute to change (3) - the ordering of traces of the same type on the same axes, but hard to add a way to change the other orderings (different types, or on different axes).

But there's a workaround: make extra axes - that can be set to be overlaying and matching the main axes and with all their marks disabled, so really their only effect is to change the layering - and put the traces intended to be in back on lower-numbered axes, traces in front on higher-numbered axes.

**Comment by gvwilson** [comment]
See great progress: https://github.com/plotly/plotly.js/pull/6918

**Comment by archmoj** [comment]
We could possibly close this one as `zorder` is implemented. No?

**Comment by gvwilson** [comment]
agreed
