### ISSUE TITLE
matplotlib example: plotly.exceptions.PlotlyError: Uh oh, an error occurred on the server.

### ISSUE THREAD

**Issue by rlrosa** [plotly/plotly.py#470]
hi, i'm trying to run the [matplotlib example](https://plot.ly/matplotlib/) and i get this error:

    Traceback (most recent call last):
      File "ply-demo.py", line 20, in <module>
        plot_url = py.plot_mpl(fig)
      File "/usr/local/lib/python2.7/dist-packages/plotly/plotly/plotly.py", line 315, in plot_mpl
        return plot(fig, **plot_options)
      File "/usr/local/lib/python2.7/dist-packages/plotly/plotly/plotly.py", line 241, in plot
        res = _send_to_plotly(figure, **plot_options)
      File "/usr/local/lib/python2.7/dist-packages/plotly/plotly/plotly.py", line 1429, in _send_to_plotly
        raise exceptions.PlotlyError(r['error'])
    plotly.exceptions.PlotlyError: Uh oh, an error occurred on the server.

how can i get more info about what's wrong?

i'm running plotly ```1.9.13```.
thanks.
salú

**Comment by yankev** [comment]
@rlosa did you run the entire block of code as is?

**Comment by rlrosa** [comment]
yes. i made a script with the code from the example:

    import matplotlib.pyplot as plt
    import matplotlib.mlab as mlab
    import numpy as np
    import plotly.plotly as py
    
    py.sign_in('DemoAccount', 'lr1c37zw81')
    
    n = 50
    x, y, z, s, ew = np.random.rand(5, n)
    c, ec = np.random.rand(2, n, 4)
    area_scale, width_scale = 500, 5
    
    fig, ax = plt.subplots()
    sc = ax.scatter(x, y, c=c,
                    s=np.square(s)*area_scale,
                    edgecolor=ec,
                    linewidth=ew*width_scale)
    ax.grid()
    
    plot_url = py.plot_mpl(fig)

called it ```pex.py``` and ran it from the command line ```python pex.py```.

**Comment by cldougl** [comment]
Hey @rlrosa looks like you didn't add *your* credentials to the `py.sign_in()` function.
However, we recommend using `plotly.tools.set_credentials_file()` over `py.sign_in()`
```
import plotly 
plotly.tools.set_credentials_file(username='YOUR_USERNAME', api_key='YOUR_API_KEY')
```

You can see our [getting started page](https://plot.ly/python/getting-started/) if you need additional information
and you can create and account [here](https://plot.ly/feed/) if you don't have one already.

**Comment by rlrosa** [comment]
@cldougl worked now, thanks. i thought first example was self contained and associated with some dummy/demo credentials.
thanks!
salú
