### ISSUE TITLE
Plotly 5.23.0, Hover on Subplots Only Work on one subplot

### ISSUE THREAD

**Issue by luweiming** [plotly/plotly.py#4701]
Hi All,

I'm using the latest Plotly 5.23.0 

I've been trying days to make the Hover on Subplots work, and it turns out it didnt even work from the example/code listed on the plotly site https://plotly.com/python/hover-text-and-formatting/.

Anyone also encounter with the same issue? How to fix this? Thanks.

I'm using Windows 11, VScode, Jupyter Notebook or Python environment, none worked.

import plotly.graph_objects as go
import pandas as pd
from plotly import data

df = data.stocks()

layout = dict(
    hoversubplots="axis",
    title="Stock Price Changes",
    hovermode="x",
    grid=dict(rows=3, columns=1),
)

data = [
    go.Scatter(x=df["date"], y=df["AAPL"], xaxis="x", yaxis="y", name="Apple"),
    go.Scatter(x=df["date"], y=df["GOOG"], xaxis="x", yaxis="y2", name="Google"),
    go.Scatter(x=df["date"], y=df["AMZN"], xaxis="x", yaxis="y3", name="Amazon"),
]

fig = go.Figure(data=data, layout=layout)

fig.show()

**Comment by LiamConnors** [comment]
Hi @luweiming, if you hover over the Plotly logo in the graph, what version of Plotly.js do you see?

<img width="555" alt="image" src="https://github.com/user-attachments/assets/ed94541f-489b-4846-a503-22263ab8b8bc">

VS Code doesn't use the installed Plotly.py version of Plotly.js by default. It uses its own bundled Plotly.js, which can often be behind the latest in Plotly.py. The hover on subpplots feature was introduced in Plotly.js 2.31.0.

This gives some more context on the issue https://plotly.com/python/troubleshooting/#vscode-notebook-nteract-and-streamlit-problems 

Setting the renderer on `fig.show` to `"notebook"` is a workaround if you see it's not using the latest Plotly.js

```
fig.show(renderer="notebook")
```

**Comment by luweiming** [comment]
Hi @LiamConnors, Thanks so much for the help, this is interesting and no wonder I have so many weird issues on Plotly. My Plotly.js was 2.29.1.
