### ISSUE TITLE
bad performance when realtime incremental updating charts

### ISSUE THREAD

**Issue by code1704** [plotly/plotly.py#4704]
I use plotly to draw realtime stock prices in jupyter.  The data is updated every second and there are multi plotly charts.

```
# pseudocode
fig = go.FigureWidget(
    data=[..],
    layout={..},
)

async def update():
        while True:
            data = .. fetch data here
            with fig.batch_update():
                for i in range(len(data_row)):
                    self._chart.data[i].x += (data[i].datetime,)
                    self._chart.data[i].y += (data[i].price,)
            await asyncio.sleep(1.0)
```

When there are more than 10+ charts, the performance becomes very bad. seems plotly does not do incremental update, instead, it re-render whole chart every second?

Is there any way to improve the performance? How to make it do incremental update?

**Comment by gvwilson** [comment]
Thank you for your interest in plotly - for how-to / support questions like this, you will probably get a response more quickly in our forums (https://community.plotly.com/). Cheers - @gvwilson
