### ISSUE TITLE
Parallel Coordinates Plot is not working.

### ISSUE THREAD

**Issue by Spogis** [plotly/plotly.py#4729]
Parallel Coordinates Plot is not working. Also in the examples (https://plotly.com/python/parallel-coordinates-plot/)!

![image](https://github.com/user-attachments/assets/1b30aaa6-c8ff-483c-b976-1002dde03193)

**Comment by alexcjohnson** [comment]
Presumably this is in Chrome 128? That's tracked in https://github.com/plotly/plotly.js/issues/7130, being worked on in https://github.com/plotly/plotly.js/pull/7131

**Comment by Spogis** [comment]
> Presumably this is in Chrome 128? That's tracked in [plotly/plotly.js#7130](https://github.com/plotly/plotly.js/issues/7130), being worked on in [plotly/plotly.js#7131](https://github.com/plotly/plotly.js/pull/7131)

I'm using Microsoft Edge Version 128.0.2739.42 (Official build) (64-bit)
The problem also occour with Chrome.

**Comment by Spogis** [comment]
I really don't understand what happened. On Monday, my code was running without errors and generating the parallel coordinates chart without any issues.

I didn't update any libraries, not even Plotly or any other. And on Tuesday, the chart stopped being generated.

Question: If I didn't update Plotly, how did this happen? Does the library by any chance send my data to some external server? Is there a serious data security risk if this is happening?

@gvwilson , would you have any thoughts on this?

Best regards,

Nicolas

**Comment by gvwilson** [comment]
@Spogis we believe this is a bug in Chrome 128 - can you please try it in (for example) Firefox and let us know?

**Comment by alexcjohnson** [comment]
FYI Edge uses the same rendering engine as Chrome, so Edge 128 can be expected to have similar bugs to Chrome 128

**Comment by gvwilson** [comment]
```
This is now fixed by Chromium 128.0.6613.113:
https://chromium.googlesource.com/chromium/src/+/refs/tags/128.0.6613.113
```

@Spogis can you please update to the latest Chromium and let us know if that fixes your issue?

**Comment by Spogis** [comment]
@gvwilson and @alexcjohnson , thanks for your reply

![image](https://github.com/user-attachments/assets/a052f13a-0624-4257-b4ae-4a43e38b7d99)
Not working in Edge

![image](https://github.com/user-attachments/assets/8d9cb4cf-0364-47d8-94ec-f2a762d46a38)
Not working in Chrome

![image](https://github.com/user-attachments/assets/dec9e1f2-6ca0-413f-9497-f3c36390b886)
Working fine in Firefox!

Do you know if it is possible to update my Edge and Chrome browsers? There might be a bug in these browsers.

Thank you very much in advance!

**Comment by gvwilson** [comment]
@Spogis can you please post the full version numbers of your Chrome and Edge browsers? cc @archmoj

**Comment by Spogis** [comment]
> @Spogis can you please post the full version numbers of your Chrome and Edge browsers? cc @archmoj
![image](https://github.com/user-attachments/assets/4b750677-2a3e-49a7-99f3-a6f80c05cd8b)

Just Update my Chrome and now is FINE!
![image](https://github.com/user-attachments/assets/8680580b-3710-4532-a935-c0a054c169b0)

Only having problems with Edge yet.

**Comment by raul7gs** [comment]
Already works for me in edge after latest update (at least for me). Thanks for the fast track of the bug, you really solve a lot of headaches hehehehe.

**Comment by Spogis** [comment]
> @Spogis can you please post the full version numbers of your Chrome and Edge browsers? cc @archmoj

![image](https://github.com/user-attachments/assets/1516ddd4-2059-409e-a63f-4f7cf51cc318)

![image](https://github.com/user-attachments/assets/f76d2131-925a-41be-80a3-200de9afcff3)

@gvwilson @alexcjohnson : Running fine in Edge now! Fixed in this new version. Thank you very very much for your support. 

Best regards,

Nicolas
