### ISSUE TITLE
Unrecognized Data Structures

### ISSUE THREAD

**Issue by flynn-ryder44** [plotly/plotly.py#4750]
Hello! I've been stuck on this problem for a few days and was hoping to find out if there was some news on this front. I'm attempting to create a scatter plot with OLS trendline via plotly.express and I am receiving this error:

'''
ValueError: unrecognized data structures: <class 'pandas.core.arrays.floating.FloatingArray'> / <class 'numpy.ndarray'>
'''

I've attempted using modin.pandas as well, but it seems like that creates an issue with using a float data type? Even when converting to a Numpy array, I still receive the error:

'''
AttributeError: 'Float64Dtype' object has no attribute 'byteorder'
'''

Is the problem with the fact that one of my axes is a float object? This is unfortunately a requirement for the data I am working with.

Appreciate any help that anyone can provide on this! I've pasted a screenshot of my code below. Fwiw, the statsmodels.api model summary outputs as expected.

![Screenshot 2024-09-04 212111](https://github.com/user-attachments/assets/89f6e45b-3104-4f77-9d73-a54a46e49a93)

**Comment by flynn-ryder44** [comment]
Also, forgot to mention that everything works fine and outputs perfectly when I don't include the trendline in the scatter plot!

**Comment by gvwilson** [comment]
Hi @flynn-ryder44 - we are tidying up issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community, so for tech support and "how-to" questions, please post in our community forum https://community.plotly.com/. Thank you - @gvwilson
