### ISSUE TITLE
empty fig using new px.choropleth_map (even with code example)

### ISSUE THREAD

**Issue by lopezj1** [plotly/plotly.py#4751]
Using version 5.24.0. New px.choropleth_map was not working for me with my data, so decided to run the code snippet from the plotly example. This also did not work in jupyter notebook.

Source:
[Example](https://plotly.com/python/tile-county-choropleth/)

Code:
```
from urllib.request import urlopen
import json
with urlopen('https://raw.githubusercontent.com/plotly/datasets/master/geojson-counties-fips.json') as response:
    counties = json.load(response)

import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/plotly/datasets/master/fips-unemp-16.csv",
                   dtype={"fips": str})

import plotly.express as px

fig = px.choropleth_map(df, geojson=counties, locations='fips', color='unemp',
                           color_continuous_scale="Viridis",
                           range_color=(0, 12),
                           map_style="carto-positron",
                           zoom=3, center = {"lat": 37.0902, "lon": -95.7129},
                           opacity=0.5,
                           labels={'unemp':'unemployment rate'}
                          )
fig.update_layout(margin={"r":0,"t":0,"l":0,"b":0})
fig.show()

```
Output:
<img width="391" alt="px choropleth_map-output" src="https://github.com/user-attachments/assets/73210e2c-3d35-4794-abe0-f07cf8efa00e">

**Comment by archmoj** [comment]
@LiamConnors Would you please have a look at this and possibly create a plotly.js codepen?

**Comment by LiamConnors** [comment]
@lopezj1 what environment are you running the jupyter notebook in? Is it a Jupyter notebook within an IDE like VS Code?
What version of Plotly.js do you see when you hover over the plotly logo in the top right corner of the empty fig that renders for you.

<img width="1138" alt="image" src="https://github.com/user-attachments/assets/a6242d99-9ee6-47a6-ade5-6826723b9bfb">

**Comment by lopezj1** [comment]
@LiamConnors I am running an iteractive window within VSCode and this shows Plotly.js (v2.29.1).  

But `print(plotly.__version__)` shows plotly 5.24.0 is being used

<img width="960" alt="px choropleth_map-ide" src="https://github.com/user-attachments/assets/cc30ea09-8f43-4c40-8cf5-a6f6cd21080d">

**Comment by LiamConnors** [comment]
@lopezj1 VS Code uses its only bundled Plotly.js, so sometimes the latest features won't work immediately there. This page in the docs gives a bit more detail
https://plotly.com/python/troubleshooting/#vscode-notebook-nteract-and-streamlit-problems

Setting the `renderer` on `fig.show` to "notebook" is a workaround if you see it's not using the latest Plotly.js

`fig.show(renderer="notebook")`

**Comment by lopezj1** [comment]
@LiamConnors oh ok that makes sense.  Actually I wanted this to work in streamlit, which it didn't, so tried the vscode notebook.  But looks like both are affected per the link.  

Is there an alternate renderer for streamlit?
