### ISSUE TITLE
init_notebook_mode() flushes the math in markdown to left

### ISSUE THREAD

**Issue by r-parhizkar** [plotly/plotly.py#476]
In Jupyter notebook, once I call `init_notebook_mode()` and save and close the notebook and reopen it, all the math formula (in markdown) which were centered before, are flushed to the left. I am using python 2.7, plotly version 1.9.10 and Jupyter 4.1.0! 

Here is an example: 
Cell 1:
```
import plotly
print plotly.__version__
plotly.offline.init_notebook_mode()
```

Cell 2:
```
$$x = y$$
```

**Comment by jackparmer** [comment]
Duplicated of https://github.com/plotly/plotly.py/issues/445
