### ISSUE TITLE
Typo in documentation

### ISSUE THREAD

**Issue by pearlchompunoot** [plotly/plotly.py#4773]
Hi 
I think this one highlighted in the picture has a typo
it should say "`lonaxis.range` and lataxis.range`"

[
![thumbnail_image](https://github.com/user-attachments/assets/628e09ef-d965-4cc5-bc86-88fd5bc7c6a0)
]

**Comment by LiamConnors** [comment]
Thanks @pearlchompunoot for reporting this! It is fixed via https://github.com/plotly/plotly.js/pull/7179 and will be in the next Plotly.py release
