### ISSUE TITLE
Scattermap Class doesn't render

### ISSUE THREAD

**Issue by yusuf-jkhan1** [plotly/plotly.py#4775]
Python 3.10.12
Plotly 5.24.0 and 5.24.1
Tested on Windows 11 and Ubuntu 22.04

`pip install 'plotly==5.24.0'`

```
#Example from docs, https://plotly.com/python/tile-scatter-maps/
import plotly.graph_objects as go

fig = go.Figure(go.Scattermap(
        lat=['45.5017'],
        lon=['-73.5673'],
        mode='markers',
        marker=go.scattermap.Marker(
            size=14
        ),
        text=['Montreal'],
    ))

fig.update_layout(
    hovermode='closest',
    map=dict(
        bearing=0,
        center=go.layout.map.Center(
            lat=45,
            lon=-73
        ),
        pitch=0,
        zoom=5
    )
)

fig.show()
```
Doesn't render anything. It seems like px_scattermap is also having a similar issue.

**Comment by LiamConnors** [comment]
@yusuf-jkhan1 thanks for reporting this. are you running these in a notebook? does the Plotly toolbar show even if the map doesn't? If so, what version of Plotly.js do you see if you hover on the Plotly logo there.

<img width="975" alt="image" src="https://github.com/user-attachments/assets/cbe8d6c3-f75b-490f-8064-b1ba0ccb9fc0">

**Comment by ndrezn** [comment]
Closing in favour of #4827
