### ISSUE TITLE
FigureWidget.show() returns a Figure instead of a FigureWidget

### ISSUE THREAD

**Issue by marthacryan** [plotly/plotly.py#4854]
If you run:
```
fig = go.FigureWidget()
fig.show()
```
you get a _non-interactive_ figure. 
If you run:
```
fig = go.FigureWidget()
fig
```
you get an interactive figure widget. This confused me and could lead to people having issues using `FigureWidget`.

**Comment by gvwilson** [comment]
@marthacryan should this be changed for 6.0 or left for after?

**Comment by alexcjohnson** [comment]
Seems to me more like a bug than a feature

**Comment by marthacryan** [comment]
> Seems to me more like a bug than a feature

@alexcjohnson Yes I would say it is likely a bug

**Comment by marthacryan** [comment]
> [@marthacryan](https://github.com/marthacryan) should this be changed for 6.0 or left for after?

I guess this is technically changing an API, although as Alex said above, I think it's more of a bug than an API. I think it isn't a release blocker but might be slightly better to include in the release? I don't expect this would be very difficult to fix, but I think we might want to give some thought to what behavior we _do_ want in this case. I expected it to be the same as just using the `FigureWidget` object without `.show()`, but we could also choose to add a warning / error or point the user to just calling `fig` instead of `fig.show()`. @ndrezn any opinions?

**Comment by ndrezn** [comment]
I agree that it's a bug but IMO it's not a release blocker.
