### ISSUE TITLE
Setting `category_orders` leads to missing data (master branch)

### ISSUE THREAD

**Issue by LiamConnors** [plotly/plotly.py#4875]
This example from the docs, shows how to define the category orders:

```
import plotly.express as px
df = px.data.tips()
fig = px.bar(df, x="day", y="total_bill", color="smoker", barmode="group", facet_col="sex",
             category_orders={"day": ["Thur", "Fri", "Sat", "Sun"],
                              "smoker": ["Yes", "No"],
                              "sex": ["Male", "Female"]})
fig.show()
```

And renders like this:

![Image](https://github.com/user-attachments/assets/154a7950-364e-4054-9ce5-56dad5040d42)

The same example run with plotly built from master branch, only shows the bars for Sunday:

![Image](https://github.com/user-attachments/assets/1305e617-f703-4a3c-a022-860e33e49c11)

**Comment by MarcoGorelli** [comment]
Thanks for spotting this - I think 

https://github.com/plotly/plotly.py/blob/499e2facd5db337ca9fa9b95ac3951bc5cbe0d31/packages/python/plotly/plotly/express/_core.py#L2443

is the issue:
```python
(Pdb) p orders
{'day': ['Thur', 'Fri', 'Sat', 'Sun'], 'smoker': ['Yes', 'No'], 'sex': ['Male', 'Female']}
(Pdb) p grp_to_idx
{'day': 0, 'smoker': 1, 'sex': 2}
```

**Comment by MarcoGorelli** [comment]
thanks for spotting this, and sorry for having missed - I think I see the issue, fix incoming
