### ISSUE TITLE
error when building docs: `make: *** [Makefile:40: build/html/2019-07-03-2D-Histogram.html] Error 1`

### ISSUE THREAD

**Issue by MarcoGorelli** [plotly/plotly.py#4883]
Hey - I'm trying to build the docs from source to check whether any of the generated plots looks different from how they do on the latest release (to check for any other regressions not caught by the test suite)

I've:
- got a Python3.10 virtual environment
- from `packages/python/plotly/` i've done 
  ```
  uv pip install -r requirements.txt -r test_requirements/requirements_310_optional.txt
  pip install -e . -e ../chart-studio/ -e ../plotly-geo/
  ```
- and then from `doc` I did
  ```
  uv pip install -r requirements.txt
  ```
- created a mapbox token which I pasted in `python/.mapbox_token`

If I then do `make` from `docs` folder, I get
```
$ make
[nbconvert]  build/ipynb/2D-Histogram.ipynb
make: *** [Makefile:40: build/html/2019-07-03-2D-Histogram.html] Error 1
```

Is there a step I've missed? Any way to get more verbose output?

**Comment by gvwilson** [comment]
Unfortunately, building the docs is much more complicated than it should be - I'll send you a note by email. Until we clean up the build process, I think it's best to leave it to our CI job…
