### ISSUE TITLE
Bar plot barmode has changed

### ISSUE THREAD

**Issue by MarcoGorelli** [plotly/plotly.py#4884]
I've tried comparing
- 5.24.1+19.g673c19c4e (commit 2bc6a0fedfd5a3d2c4e9846810032d3ec564102a)
- 5.24.1+496.g2bc6a0fed (commit 673c19c4eb83709d4344e87976e9fdee697919d3)

in
```python
import plotly.express as px

long_df = px.data.medals_long()

fig = px.bar(long_df, x="nation", y="count", color="medal", title="Long-Form Input")
fig
```

and the outputs now differ

![Image](https://github.com/user-attachments/assets/5cb17d6b-71ec-4435-961a-0b29f753fe63)

![Image](https://github.com/user-attachments/assets/3fd6ba92-8ea1-4ef5-acfb-fdb7c16a3152)

I guess it's probably due to #4790 - taking a  look

**Comment by MarcoGorelli** [comment]
looks like this is the same root issue as the histogram plot in https://github.com/plotly/plotly.py/issues/4863 - closing in favour of that one then

**Comment by MarcoGorelli** [comment]
Can confirm that this is now fixed 👍

**Comment by emilykl** [comment]
Just saw this — thanks for opening this issue @MarcoGorelli !
