### ISSUE TITLE
3d graph tick length

### ISSUE THREAD

**Issue by korantir** [plotly/plotly.py#4887]
Maybe I don't understand something, but it looks bugged.

`ticklen` parameter of `XAxes` can be changed from 0 to inf according to the documentation. And it is so in 2d plots. However, plotted in 3D, ticks cannot be longer than some value. Debug shows that ticklen parameter changed. But rendered result stays intact.
For example, 

```
import plotly.graph_objects as go

import pandas as pd

# Read data from a csv
z_data = pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/api_docs/mt_bruno_elevation.csv')

fig = go.Figure(data=[go.Surface(z=z_data.values)])

fig.update_layout(title=dict(text='Mt Bruno Elevation'), autosize=False,
                  width=2000, height=1000,
                  margin=dict(l=50, r=50, b=50, t=50))

fig.update_scenes(xaxis_tickmode='linear', xaxis_tick0=0, xaxis_dtick=5, xaxis_ticks ='outside')

fig.update_xaxes(
    ticklen=140
)

fig.show()
```

Thanks in advance! Hope I didn't miss something obvious. I tried to change `tickwidth` for example. And it works perfectly fine.

**Comment by gvwilson** [comment]
Hi - we are tidying up issues and PRs in Plotly's public repositories so that we can focus on things that are most important to our community. For tech support and "how-to" questions, please post in our community forum https://community.plotly.com/. Thank you - @gvwilson
