### ISSUE TITLE
GraphWidget doesn't show any plot in Jupyter

### ISSUE THREAD

**Issue by napjon** [plotly/plotly.py#490]
Hi guys,

From this tutorial,

http://nbviewer.jupyter.org/gist/chriddyp/9827cb5086cfab8da092/Widgets%20-%20Contour%20Plotter.ipynb

I execute this code snippets in Jupyter

``` Python
import plotly.plotly as py
from plotly.graph_objs import *
import plotly.tools as tls

import json
import numpy as np
import math
from IPython.display import display
from plotly.widgets import GraphWidget


contour_plot = GraphWidget('https://plot.ly/~bronsolo/63')
line_plot = GraphWidget('https://plot.ly/~chris/2150')

display(contour_plot)
display(line_plot)
```

But it doesn't show any plot in Jupyter. In fact, any graphwidget that I created also didn't show any plot in Jupyter. Please advice. Thanks!

**Comment by Kully** [comment]
@napjon

Try running the code in blocks:

```Python
import plotly.plotly as py
from plotly.graph_objs import *
import plotly.tools as tls
```

```Python
import json
import numpy as np
import math
from IPython.display import display
from plotly.widgets import GraphWidget
```

```Python
contour_plot = GraphWidget('https://plot.ly/~bronsolo/63')
line_plot = GraphWidget('https://plot.ly/~chris/2150')
```

```Python
display(contour_plot)
```

```Python
display(line_plot)
```

I get two visible plots in the two different outputs:
-first one looks fine
-second plot is has no data in it

If you actually visit 'https://plot.ly/~chris/2150', you'll notice the plot is empty, so I think that's the reason why no trace is visible

Let me know if you have any other questions. Someone at Plotly will be happy to help!

**Comment by napjon** [comment]
Hi @Kully,

Thank you for your help. I still don't have any plot showing from your advice. Maybe it's related to Jupyter version?

* My Jupyter version is 4.0.6
* My ipython/notebook version is at 4.2.0

Let me know if you have the same version as me. Thank you.

**Comment by yankev** [comment]
@napjon I've got it running on ipython version 4.1.1.

**Comment by napjon** [comment]
Hi,

I can confirm that notebook version 4.2.1 doesn't resolve this issue. Unfortunately, there is no way to debug this. Please advice. Thanks.

**Comment by andrea0286** [comment]
Same problem here. Tried to downgrade packages. But no success.
Display is working and showing only widgets but no GraphWidget.
Anyway I can use GraphWidgets only running with jupyter.
If I try with python I get an error saying:

```
ShimWarning:
The `IPython.html` package has been deprecated. You should import from `notebook` instead. `IPython.html.widgets` has moved to `ipywidgets`.
```

**Comment by brovercleveland** [comment]
Same issue, just updated jupyter, can no longer display GraphWidgets.  Currently trying to downgrade.  My GraphWidgets were displaying with iPython 4.2.0, jupyter-core-4.0.6, ipykernel-4.1.1, notebook 4.0.6.  Currently attempting to downgrade to my previous versions, but unable to find the magic combo.

**Comment by bwalsh** [comment]
same problem

**Comment by msschwartz21** [comment]
I am still encountering this issue. Is there a solution that doesn't involve downgrading packages?

**Comment by CermakM** [comment]
Same issue in jupyter 4.4.0
