### ISSUE TITLE
Plotly express process_dataframe_timeline expects datetime as strings

### ISSUE THREAD

**Issue by Trollgeir** [plotly/plotly.py#4913]
If the user supplies a dataframe with correct dtypes (datetime), it will err as it's trying to cast them from string.

https://github.com/plotly/plotly.py/blob/master/packages/python/plotly/plotly/express/_core.py#L2125-L2129

It would be better if the casting is conditional, because right now I have to cast my datetime back to string, just for the function to cast it back to datetime.

plotly version 6.0.0rc1

**Comment by MarcoGorelli** [comment]
Wonderful, thanks @Trollgeir for trying out the prerelease, really appreciate it!

Indeed, here's reproducible example:
```python
import plotly.express as px
import polars as pl

# Example dataset
data = {
    "Task": ["Research", "Design", "Implementation", "Testing", "Deployment"],
    "Start": ["2024-01-01", "2024-02-01", "2024-03-01", "2024-04-15", "2024-05-01"],
    "Finish": ["2024-01-31", "2024-02-28", "2024-04-14", "2024-04-30", "2024-05-15"],
    "Resource": ["Team A", "Team B", "Team A", "Team C", "Team B"]
}

# Convert to a DataFrame
df = pl.DataFrame(data).with_columns(pl.col('Start', 'Finish').str.to_date())

# Create the timeline
fig = px.timeline(
    df,
    x_start="Start",
    x_end="Finish",
    y="Task",
    color="Resource",
    title="Project Timeline",
    labels={"Resource": "Team Assigned"}
)

# Update layout for better appearance
fig.update_yaxes(categoryorder="total ascending")  # Order tasks by start date
fig.show()
```

`.str.to_datetime` should only be called if Start / Finish aren't already of Datetime dtype
