### ISSUE TITLE
plotly.express.scattermatrix displays no color if supplied a pandas.DataFrame with a DataTime index

### ISSUE THREAD

**Issue by Noskario** [plotly/plotly.py#4917]
The color does not get diplayed when using a DataFrame with a DateTime index.

Have a look at the following example:
```
import pandas as pd
import plotly.express as px
df = pd.DataFrame({
        "x":[1,2,3,4],
        "y":[10,20,10,20],
        "z":[-1,-2,-3,-4],
        "color":[1,2,3,4]
    })
df.index = pd.DatetimeIndex(["1/1/2020 10:00:00+00:00", "2/1/2020 11:00:00+00:00", "3/1/2020 10:00:00+00:00", "4/1/2020 11:00:00+00:00"])
px.scatter_matrix(df, color = "color")
```

![Image](https://github.com/user-attachments/assets/21cc3663-79a9-4ab2-a6ea-242ba6853b4e)

There are no problems when you comment out the line `df.index = ...`.

Maybe this issue is related to https://github.com/plotly/plotly.py/issues/4788

**Comment by MarcoGorelli** [comment]
Hi @Noskario 

is this your expected output?

if so, I might have a fix

![Image](https://github.com/user-attachments/assets/3ae6194c-3a7b-4cf2-98e7-b4f92731e7c1)

**Comment by Noskario** [comment]
Yes, absolutely!
