### ISSUE TITLE
In 3D plots, Latex cannot be displayed in axis title.

### ISSUE THREAD

**Issue by dingxiong** [plotly/plotly.py#496]
3D plot cannot display some math in the axis title, but it can display Latex in the legend correctly. Is this a bug or a problem with my code ?

See the x and y in this [simple exmple](https://plot.ly/~dingxiong/4/theta/).

**Comment by yankev** [comment]
@dingxiong This appears to be an issue with `plotly.js`. I've opened an issue in that repo: https://github.com/plotly/plotly.js/issues/608.

**Comment by dingxiong** [comment]
@yankev Thanks.
