### ISSUE TITLE
Sharing data between JS and Python?

### ISSUE THREAD

**Issue by choldgraf** [plotly/plotly.py#500]
Is it possible to pass data between the WebGL instance and python?

For example, I'd like to make a 3D plot, then rotate the camera, then call a function that returns the camera angle corresponding to that view. Something like [this example](http://www.mathworks.com/help/matlab/ref/camva.html).

More complicated tasks would be, e.g., clicking several points and having it return the 3D coordinates in an array, or something like this.

**Comment by hyliu1989** [comment]
I assume you are using IPython notebook.
Partially answer to this question: try the following in JavaScript
    var s = 'True'
    IPython.notebook.kernel.execute("python_code_here = " + s)
This allows you to pass the string in JavaScript back to Python. But caution needs to be taken: this line is executed after the current cell in IPython notebook

**Comment by choldgraf** [comment]
Hmmm, I see...so, could that be used to, for example, pass an array from JS back to python?

E.g., open a scatterplot, click on 10 points, on each click save the x/y location of the point in an array. Now in another cell I run "xy = get_xy_from_js()" and it calls javascript that dumps that list back into python? Or another usecase might be to do something in python after every click in a plotly window.

**Comment by hyliu1989** [comment]
For this particular example, I would do the following
`IPython.notebook.kernel.execute( "__GLOBALVAR_ARR = []" )`
And for each click, execute the following
`IPython.notebook.kernel.execute( "__GLOBALVAR_ARR.append( ("+x.toString()+","+y.toString()+") )" )` Ugly but it might work.

**Comment by choldgraf** [comment]
OK cool - I'll think about how to do this kind of thing in the next couple
of weeks hopefully. I'll ping here if anything comes up.

**Comment by choldgraf** [comment]
I've got some simple data passing working in plotly.js, but now I'm running into trouble actually accessing the plots that are passed to JS from plotly.py. It looks like the call to `iplot` generates a random ID for the new plot. Is there a way to access the data you've passed to JS without knowing that ID?

E.g., I'd like to:
1. Create a 3-D plot in python, plot with the offline `iplot` method
2. Rotate the 3-D plot to an arbitrary position
3. With a function call in python, pull the values of the camera position and pass those back to python

**Comment by choldgraf** [comment]
I've been looking into this a bit more, and it sounds (at least as of last December) that this isn't actually possible. According to [this post](http://community.plot.ly/t/click-events-in-python-offline-mode/298), plotting in offline mode w/ python doesn't expose the plot in the same way that it does in online mode (I believe this is an iframe). So perhaps this is just not possible right now?

**Comment by monfera** [comment]
@choldgraf I don't have information on the `python` binding but wanted to jot down that `plotly.js` has two methods for sharing information with the caller:

- event callback: for example, `restyle` and `relayout` events output pertinent variables; `camera` transform data are emitted etc.
- data side effects on the `graph` `DIV` object - could in theory be checked upon a raised `plotly.js` event, or polled periodically, although the latter isn't too elegant

**Comment by jmodica1** [comment]
@choldgraf curious if you ever figured out a way to achieve the above?

**Comment by choldgraf** [comment]
I was never able to get this working, largely because I don't have much javascript skills. Maybe there's been development on the plotly side?

**Comment by chriddyp** [comment]
This is possible with the latest `GraphWidget` https://medium.com/@plotlygraphs/introducing-plotly-py-3-0-0-7bb1333f69c6 as well as within Dash - https://dash.plot.ly/interactive-graphing
