### ISSUE TITLE
TypeError: must be string or buffer, not None

### ISSUE THREAD

**Issue by SatoshiReport** [plotly/plotly.py#503]
Hi, I could use your help.  Thanks in advance.  Here is what i did...

I am trying to save an image locally and have not logged into the remote server.  I have ran "sudo pip install --upgrade plotly" successfully.  

I use the example from: [](https://plot.ly/python/offline/)

I am running on ubuntu remotely with no display/monitor.

The code is:

```
from plotly import __version__
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot

print __version__ # requires version >= 1.9.0                                                                                                                                                                                                   

import plotly.plotly as py
from plotly.graph_objs import Bar, Layout, Figure                                                                                                                                                                                                     

trace = Bar(x=[1,2,3],y=[4,5,6])
data = [trace]
layout = Layout(title='My Plot')
fig = Figure(data=data,layout=layout)

py.image.save_as(fig, 'my_plot.png')

```

and the result is:

> 1.12.0
> Traceback (most recent call last):
>   File "test.py", line 17, in <module>
>     py.image.save_as(fig, 'my_plot.png')
>   File "/usr/local/lib/python2.7/dist-packages/plotly/plotly/plotly.py", line 791, in save_as
>     f.write(img)
> TypeError: must be string or buffer, not None

Not sure why I have this error or how to resolve.

**Comment by yankev** [comment]
Hi, are you running this from within an IPython Notebook?

**Comment by SatoshiReport** [comment]
No, I am not running it within ipython notebook

**Comment by yankev** [comment]
I wasn't able to reproduce your error using the newest version:`Plotly 1.12.1`. Are you still getting this error?

**Comment by SatoshiReport** [comment]
No, I am not, thank you.
