### ISSUE TITLE
link_text does not update given config settings

### ISSUE THREAD

**Issue by BRONSOLO** [plotly/plotly.py#505]
It seems link_text isn't actually getting set as intended: https://github.com/plotly/plotly.py/blob/master/plotly/offline/offline.py#L154-L158
@chriddyp

**Comment by yankev** [comment]
@BRONSOLO With the latest updates I think that code chunk got moved. But you're talking about this section right? https://github.com/plotly/plotly.py/blob/master/plotly/offline/offline.py#L189-L204

Just need to add `config['linkText'] = link_text` after line 204 correct?

**Comment by yankev** [comment]
Resolved in #508
