### ISSUE TITLE
Fluid Resizing with plotly.py

### ISSUE THREAD

**Issue by GrainsofSalt** [plotly/plotly.py#512]
Hey guys,

I was wondering if it would be possible to get the charts made by plotly.py to be retroactively resized with the browser window. As of now, it seems that there is only a js implementation for the minified version. It would be really convenient if the height and width attributes could take a percentage instead of a pixel value. This way, with a percentage set, one could use css to fluidly resize the entire structure of the webpage. Resizing the container of the chart would cause the chart to automatically resize. Not sure how difficult this would be, but since the plotly.py commands are not run within js, it makes fluid resizing very difficult. 

I hope I haven't overlooked some super simple solution, and if I have please let me know! I am trying to adapt my web app for more than just desktop use. I would really like to make it mobile. I love how powerful plotly is with all of its graphing functionality, so I would prefer to continue with its use in the web app. 

Thanks

**Comment by GrainsofSalt** [comment]
Is it possible that in future updates charts will be able to fluidly resize with view ports as opposed to having a strict pixel height and width?

**Comment by jessexknight** [comment]
I was struggling to do this too, but I may have found a "super simple solution" :)
`dcc.Graph( ... , style={'width':'100%'})`
This yields fluid resizing of the div containing the chart, and auto-resizing of any charts within that. 

Perhaps this issue can be closed?

**Comment by jonmmease** [comment]
Closing as plots displayed using `FigureWidget` in the classic notebook or JupyterLab do autoresize with their container, as do offline iplot figures in JupyterLab using the [@jupyterlab/plotly-extension](https://github.com/jupyterlab/jupyter-renderers/tree/master/packages/plotly-extension).  Resizing for offline `iplot` figures in the classic notebook is going to be looked at for version 3.4 (https://github.com/plotly/plotly.py/pull/970).
