### ISSUE TITLE
howto: colorbar in FigureFactory.create_trisurf()

### ISSUE THREAD

**Issue by ntfrgl** [plotly/plotly.py#517]
For many applications, a colour bar is essential for visual interpretation, but I couldn't find a parameter or example in the documentation indicating how to add one to a `trisurf` rendering. Based on the documentation on [trisurf](https://plot.ly/python/trisurf/), [surface coloring](https://plot.ly/python/3d-surface-coloring/) and [meshes](https://plot.ly/python/3d-mesh/), I guessed that adding a colour bar dict into the `Mesh3d` data could do the job, but this was ineffectual. What would be the right way?

Below is an example for `ipython notebook` using a mesh from the [FAUST](http://faust.is.tue.mpg.de/) dataset, the [trimesh](https://github.com/mikedh/trimesh) library and the default `trisurf` colouring (`z`-value). The line before the last is my failed attempt.

``` python
import trimesh
mesh = trimesh.load_mesh('tr_reg_003.ply')
x, y, z = mesh.vertices.T
size = (mesh.vertices.max(axis=0) - mesh.vertices.min(axis=0)).T

import plotly.offline as py
import plotly.graph_objs as go
from plotly.tools import FigureFactory as ff
py.init_notebook_mode()
fig = ff.create_trisurf(
    x=x, y=y, z=z, simplices=mesh.faces, colormap='Viridis',
    aspectratio={'x': size[0], 'y': size[1], 'z': size[2]})
fig.data[0].update(colorbar=go.ColorBar(title='z'))
py.iplot(fig)
```
Also, an option for `create_trisurf()` setting the aspect ratio based on the mesh extent (as done above manually) would be useful.
![no_colorbar](https://cloud.githubusercontent.com/assets/5596210/16587692/2cbc7870-42cc-11e6-8e0b-1bd1003f10b9.png)

**Comment by Kully** [comment]
@ntfrgl I am looking at it now. I swear I remember a colorbar already being in `create_trisurf`. I think I may be able to add it.

**Comment by ntfrgl** [comment]
Any news on this?

**Comment by Kully** [comment]
Hi there, I think I already added the colorbar. Just download the latest package of plotly and it should be there. I apologize for not responding to this sooner.

**Comment by ntfrgl** [comment]
Could you please be more specific, e.g. pointing to a commit? The example still doesn't produce a colorbar, and I couldn't find a new relevant option or documentation example for ``create_trisurf()``.

**Comment by Kully** [comment]
Hi again. Yes, the PR was this: https://github.com/plotly/plotly.py/pull/518

A test related to the 2d-density part of it is still failing, so I have to tend to it. I don't know if that has anything the colorbar not showing up (it should be there) but I'll figure it out hopefully today.

**Comment by ntfrgl** [comment]
I see, thank you.

Unfortunately, this still doesn't solve my problem, because ``create_trisurf()`` hasn't been touched by this PR. Looking at the new ``_make_linear_colorscale()``, I tried the following, in analogy to the failed approach shown above:
``` python
fig.data[0].update(colorscale=ff._make_linear_colorscale(ff._validate_colors('Viridis', 'rgb')))
```
And again, although the ``mesh3d`` data structure is augmented, no colorbar is displayed. So what I hope for is the following:
- A way to manipulate the data structure s.t. a colorbar is shown. There seems to be some glue missing between the Python API and the JS API.
- A simple parameter for ``create_trisurf()`` to do exactly this.
- Documentation for these.

**Comment by Kully** [comment]
A PR is on the way. Tests need to pass first. https://github.com/plotly/plotly.py/pull/531

**Comment by Kully** [comment]
@ntfrgl  ^^^^

**Comment by Kully** [comment]
@ntfrgl Alright, version 1.12.5 is available now with a visible colorbar in `create_trisurf: `
