### ISSUE TITLE
plotly.py (Download plot as png) NOT WORKING

### ISSUE THREAD

**Issue by GrainsofSalt** [plotly/plotly.py#519]
Tested in all browsers, including chrome.

The "Download plot as png" button on the action bar is not working. 
I get the message "Taking snapshot - this may take a few seconds" directly followed by "Sorry there was a problem downloading your snapshot!"

Any ideas?

**Comment by cldougl** [comment]
Hi @GrainsofSalt -- just tested it out and it seems to be working for me. Could you let me know if it's a specific plot that you're having trouble with? Where is the plot that you can't download as a png (i.e. embedded in a jupyter notebook/in your organize folder/ etc)? Can you also let me know if you're plotting online or offline?

**Comment by GrainsofSalt** [comment]
Sure, sorry for being so vague.

	Chart = plotly.offline.plot({
		"data": [Bar(x=["Hello", "World", "How Are", "You?"], y=[12, 7, 5, 1]), Scatter(x=["Hello", "World", "How Are", "You?"], y=[12, 19, 24, 25])],
		"layout": Layout(title="", autosize=False, width=500,
		height=500,
		margin=go.Margin(
			l=50,
			r=50,
			b=50,
			t=50,
			pad=4
		))
	},output_type="div", show_link="False",include_plotlyjs="Flase",link_text="")

The plot is offline, and I am generating it as a div to display within some html. I am not sure if that is where the conflict is coming from. Even though I am not generating it as a picture, I still need to have the options to export it as one.

**Comment by cldougl** [comment]
Great- looking into it. Can you also confirm you're working with our latest release? 
```
import plotly
plotly.__version__
```
should show 1.12.2

**Comment by GrainsofSalt** [comment]
For sure.

Just tested, I am working with the latest release (1.12.1).

**Comment by cldougl** [comment]
Cool - so the latest version is actually 1.12.2 and there was a fix related to image downloading in there: https://github.com/plotly/plotly.py/blob/master/CHANGELOG.md#updated
could you update and let me know if you're still having the issue?

**Comment by GrainsofSalt** [comment]
You are my favorite person.

Updated the module and it is working.
I guess I should have tried that first assuming such a major bug would be patched relatively quickly. 
Thanks again.

On a side note, there wouldn't be a way to name the graphs as they are saved by chance?

**Comment by cldougl** [comment]
Excellent 🎉 
We do have a filename parameter: `plot([go.Scatter(x=[1, 2, 3], y=[3, 2, 6])], filename='my-graph.html')`

**Comment by GrainsofSalt** [comment]
Perfect. Thank you for everything!

Have a good one
