### ISSUE TITLE
box plot and whiskers

### ISSUE THREAD

**Issue by francica** [plotly/plotly.py#522]
I want the box plot to show its maximum and minimum instead of IQR correspond to the box' edges in the graph.
So in the reference, it said 

> "By default, the whiskers correspond to the box' edges +/- 1.5 times the interquartile range (IQR = Q3-Q1), see "boxpoints" for other options."

But  "boxpoints" did not talk about whiskers

> boxpoints (enumerated: "all" | "outliers" | "suspectedoutliers" | False ) 
> default: "outliers" 
> If "outliers", only the sample points lying outside the whiskers are shown If "suspectedoutliers", the outlier points are shown and points either less than 4"Q1-3"Q3 or greater than 4"Q3-3"Q1 are highlighted (see `outliercolor`) If "all", all sample points are shown If "False", only the box(es) are shown with no sample points

**Comment by jonmmease** [comment]
Going to close this here as any changes to trace options would need to be handled in the Plotly.js project (https://github.com/plotly/plotly.js).  Feel free to open an issue there if you're still interested.
