### ISSUE TITLE
More fine-grained exceptions

### ISSUE THREAD

**Issue by astrofrog** [plotly/plotly.py#524]
At the moment, an authentication error gives a generic `PlotlyError` but it would be helpful to have more fine-grained exceptions such as `PlotlyAuthenticationError` and so on:

```
PlotlyError: Aw, snap! You tried to use our API as the user 'BANANA', but the supplied API key doesn't match our records. You can view your API key at plot.ly/settings.
```

**Comment by theengineear** [comment]
We did a revamp of the exceptions raised from network requests in `2.0.0`. I'm going to close this since I think that things are (in general) more organized now.
