### ISSUE TITLE
plotly connects to server by default

### ISSUE THREAD

**Issue by pdknsk** [plotly/plotly.py#527]
``` Python
import plotly # HTTPS connection
```

This isn't mentioned in the [documentation](https://plot.ly/python/getting-started/#initialization-for-offline-plotting). It should be disclosed to the user. Or make it connect lazily. I assume the connection is not needed when only offline features are used.

**Comment by MaximilianR** [comment]
Any updates here? This causes a material slow down when frequently starting new processes.

And while I'm sure you have the best of intentions, I imagine many people would not be OK with connecting to external services without notifying them

**Comment by theengineear** [comment]
Yep, we're planning to change this behavior 👍

**Comment by theengineear** [comment]
Resolved in `1.13.0`
