### ISSUE TITLE
Bug: incorrect filename in error message

### ISSUE THREAD

**Issue by astrofrog** [plotly/plotly.py#528]
In the authentication error message, the name of the config file is wrong (should be ``.credentials``):

```
Aw, snap! You tried to use our API as the user 'BANANA', but the supplied API
key doesn't match our records. You can view your API key at plot.ly/settings.
```

**Comment by cldougl** [comment]
Hey @astrofrog can you clarify what's wrong w/ the message exactly? Or where you're seeing the config file?
We want you to go to https://plot.ly/settings/ to check your registered username/api key

**Comment by astrofrog** [comment]
Apologies for the noise, I mis-read the error message!

**Comment by cldougl** [comment]
No problem @astrofrog  -- don't hesitate to let us know if you find something else incorrect or confusing!

**Comment by akell47** [comment]
I am having a similar problem - just getting set up with plotly for python.  I see the API key in the settings in my profile - the series of dots.  I copy and paste those dots into ```import plotly 
plotly.tools.set_credentials_file(username='akell47', api_key='••••••••••')

py.sign_in("akell47", "••••••••••")```

And get the error message ```You tried to use our API as the user 'akell47', but the supplied API key doesn't match our records. You can view your API key at plot.ly/settings.````

But I did retrieve my api key though

**Comment by cldougl** [comment]
Hi @akell47 -- we protect your API key so that each time you need to view it, you must regenerate it. If you select the `Regenerate key` the key will be displayed rather than the dots, then you can copy and paste it (you can't copy and paste the dots :/ )

**Comment by akell47** [comment]
Yes that was the issue *Rookie mistake*!
