### ISSUE TITLE
Ability to `fold in` or hide date gaps.

### ISSUE THREAD

**Issue by oars** [plotly/plotly.py#529]
This would be ideal for financial data. For example to hide weekends while still being able to use a date formatted xaxis.

For now I am working around this by strtime formatting all of the date types that I have and then using an array categoryorder.

Is there a better way of doing this?

**Comment by cldougl** [comment]
We don't have a better workaround, this feature is not part of our graphing library at the moment.

**Comment by tsando** [comment]
Do you know if there has been an update on this recently? This was raised in this other thread https://github.com/plotly/plotly.js/issues/99 and this has been closed, which maybe means a solution has been found?

**Comment by Jax89** [comment]
Would also like to know if there is still planed to implement this feature? 

The only work around i know so far is using a category axis which doesn't play nice with axis formating and zoom if the data is actually numeric.

**Comment by chriddyp** [comment]
Tracking in https://github.com/plotly/plotly.js/issues/1382
