### ISSUE TITLE
go.Histogram nbinx & nbiny does not work

### ISSUE THREAD

**Issue by molofishy** [plotly/plotly.py#532]
In line with [this comment](http://community.plot.ly/t/plotly-histogram-nbinx-does-not-provide-the-right-number-of-bins-in-python/1126), the number of bins does not respond correctly to what is input by the user.
I have tried nbiny = 10, and nbiny = 20. Both of these work. But when ones does nbiny = 19 or nbiny = 15, the number of bins in the histogram is 10.

**Comment by molofishy** [comment]
There seems to be a [fix](https://github.com/plotly/plotly.js/issues/614).

**Comment by cldougl** [comment]
Yes, and just to clarify: 
as noted on the reference page, [`nbinsy`](https://plot.ly/python/reference/#histogram-nbinsy), the value will be used algorithmically to calculate bin sizes.
