### ISSUE TITLE
Violin plots print subplot grid information by default

### ISSUE THREAD

**Issue by pjbull** [plotly/plotly.py#535]
1. Create a violin plot, e.g.:
   https://plot.ly/python/violin-plot/#multiple-violins

Result:
 Grid information is printed to stdout and can't be turned off:

```
This is the format of your plot grid:
[ (1,1) x1,y1 ]  [ (1,2) x2,y1 ]  [ (1,3) x3,y1 ]  [ (1,4) x4,y1 ]  [ (1,5) x5,y1 ]
```

Expected:
 No grid information to print, or a setting to control verbosity.

Possible fix:
- Pass `print=False` explicitly to `make_subplots`
- Make `print=False` the default parameter to `make_subplots`
- Switch to logging rather than print statements so output can easily be controlled/redirected.

Here are the violin plot calls where `print=True`, though `True` is also the default parameter"
https://github.com/plotly/plotly.py/blob/master/plotly/tools.py#L2730
https://github.com/plotly/plotly.py/blob/master/plotly/tools.py#L2798
https://github.com/plotly/plotly.py/blob/master/plotly/tools.py#L2899

**Comment by Kully** [comment]
This is issue has been fixed (along with the subplot grid info printing that occurs in `FF.create_scatterplotmatrix` and will be available in the next pip package of plotly
