### ISSUE TITLE
plotting on images

### ISSUE THREAD

**Issue by Nimda1482** [plotly/plotly.py#540]
Hello. I'm new to plotly but i love it, really nice plotting tool. I want to plot bubble charts on images. how should i do this ?I didn't find anything related to setting background for plots.Thank you.

**Comment by cldougl** [comment]
Hi there, we have a tutorial on adding images here: https://plot.ly/python/images/#add-a-background-image

In the future, questions like this may be best handled in our community forum: http://community.plot.ly/
