### ISSUE TITLE
dropdownmenus not working in version 1.12.5 while documentation claims it does.

### ISSUE THREAD

**Issue by aravindhsampath** [plotly/plotly.py#542]
Documentation for dropdown menus claims to be working 1.12.4+ [Source: https://plot.ly/python/dropdowns/]

But, I run 

import plotly
plotly.__version__
'1.12.5'

Yet, I get :

PlotlyDictKeyError: 'updatemenus' is not allowed in 'layout'

Path To Error: ['updatemenus']

Valid attributes for 'layout' at path [] under parents []:

    ['orientation', 'paper_bgcolor', 'scene', 'height', 'radialaxis',
    'titlefont', 'images', 'hovermode', 'font', 'boxmode', 'autosize',
    'title', 'plot_bgcolor', 'dragmode', 'smith', 'width', 'bargap',
    'xaxis', 'bargroupgap', 'hidesources', 'direction', 'hiddenlabelssrc',
    'showlegend', 'separators', 'hiddenlabels', 'barmode', 'boxgap',
    'angularaxis', 'geo', 'legend', 'yaxis', 'annotations', 'shapes',
    'barnorm', 'ternary', 'boxgroupgap', 'margin']

Run `<layout-object>.help('attribute')` on any of the above.
'<layout-object>' is the object at []

Feature itself seems to have checked in to "1.16.0" [source: https://github.com/plotly/plotly.js/pull/770]

Documentation needs to be corrected? 

P.S I'm running on a hosted Jupyter server that I don't have access to upgrade packages.

**Comment by cldougl** [comment]
Hi there,
Are you using plotly offline? The plotly.js version used with our offline python package was recently updated: https://github.com/plotly/plotly.py/blob/master/CHANGELOG.md#updated

I will update the documentation accordingly(12.6+), though online will work with versions 12.4+
