### ISSUE TITLE
Colorbar in FF.create_trisurf  always displays the interval [0,1]

### ISSUE THREAD

**Issue by empet** [plotly/plotly.py#544]
I upgraded plotly to 1.12.6 and tested  `FF.create_trisurf` in order to see how it works with the colorbar.
The role of  colorbar in data visualization  is to point out the mapping of data values into a colormap/coloscale, but the colorbars associated to trisurfs are a kind of pseudo-colorbars, because they always  display   the interval [0,1], instead of the range of `mean_dists`.

I suggest to replace the actual colorbar defined as a `Mesh3d` by:

    colorbar=Scatter3d(x=x[:2],
                                    y=y[:2],
                                    z=z[:2],
                                    mode='markers',
                                    marker=dict(size=0.1, 
                                                       color=[min_mean_dists, max_mean_dists], 
                                                       colorscale=colorscale, showscale=True),
                                    hoverinfo='None'
                                 )
 [Here](https://plot.ly/~empet/13943/trisurf-with-a-colorbar-displaying-the-right-range-of-mean-dists/)   is an example.

I know that the colorbar defined as a `Scatter3d` instance is not appropriate in the case when the user gives the list of colors for each simplex. In my opinion, users can give such a list only if they have already triangularized the surface, and there are a small  number of simplices.
However of interest for plotting trisurfs along with the corresponding colorbar are the other two cases dealt with in the static method  `_trisurf`. Why do we compromise these  cases,  attaching them pseudo-colorbars,  for  a case in which the colorbar is meaningless? See  [this example](https://plot.ly/~AdamKulidjian/582/trisurf-plot/).

**Comment by Kully** [comment]
resolved with version 1.12.9
