### ISSUE TITLE
graph_reference schema cached in local plotly directory for use in offline mode preventing successful updates 

### ISSUE THREAD

**Issue by aravindhsampath** [plotly/plotly.py#548]
Hello. 

I updated my plotly installation from 1.12.0 to 1.12.7 yesterday to get the support for dropdown menus made available through new plotly.min.js. 

It wouldn't  still work in Ipython because Ipython was still using a locally cached ".graph_reference" file in the user's home directory which was not updated with a pip upgrade of plotly.

I'm filing this issue so the devs can consider invalidating the local cache after version updates or at the least add a notice in the documentation that upgrading plotly involves manual "rm -rf <plotly_dir>/.graph_reference" file.

**Comment by theengineear** [comment]
We're likely going to do-away with that local `.graph_reference` file. See https://github.com/plotly/plotly.py/pull/614. I'll close this down since it's on our list.
