### ISSUE TITLE
autorange='reversed' and range disabled

### ISSUE THREAD

**Issue by FlavienMakesInfographics** [plotly/plotly.py#553]
Hi,
following the example from the [reference](https://plot.ly/python/axes/), it seems that `range` is disabled when `autorange='reversed'`,

```python
import plotly as py
py.offline.init_notebook_mode()
import plotly.graph_objs as go
import numpy as np

x = np.linspace(0, 10, 100)
y = np.random.randint(1, 100, 100)

trace = go.Scatter(x=x, y=y, mode='markers')
data = [trace]
layout = go.Layout(title='Reversed Axis with Min/Max', xaxis=dict(autorange='reversed', range=[0, 6]))

fig = go.Figure(data=data, layout=layout)
py.offline.iplot(fig)
```

Enabling `range` would allow to plot mirrored histograms for example.

Best regards,
F.

**Comment by cldougl** [comment]
Hi there,
The `autorange` attribute is intended to calculate an appropriate range (be it normal or reversed the purpose is the calculation). Setting a range will override the application of the calculated range (this is the intended behavior). If you'd like to apply a reversed range that you set yourself you can simply set that in the `range` as follows:
```
import plotly as py
py.offline.init_notebook_mode()
import plotly.graph_objs as go
import numpy as np

x = np.linspace(0, 10, 100)
y = np.random.randint(1, 100, 100)

trace = go.Scatter(x=x, y=y, mode='markers')
data = [trace]
layout = go.Layout(title='Reversed Axis with Min/Max', xaxis=dict(range=[6, 0]))

fig = go.Figure(data=data, layout=layout)
py.offline.iplot(fig)
```

**Comment by FlavienMakesInfographics** [comment]
Thanks a lot for the explanation. It totally makes sense, I misunderstood the meaning if `reversed`.

**Comment by wtluke** [comment]
Thanks for this. Been struggling with this for a while in a [0,14] range. Never occurred to me that I could have done [14,0]...!

**Comment by rodneyweast** [comment]
This does not work anymore,  If I reverse the order with the range, I get the same plot as when they are in the regular order.  [14,0] gives the same result as [0,14] . It looks like the code has changed over the year...
