### ISSUE TITLE
3D Scatter X's not rendering properly with image.save_as

### ISSUE THREAD

**Issue by stephencwelch** [plotly/plotly.py#558]
I have a 3d scatter plot I need to render a series of images from. Calling image.save_as works perfectly with the exception of the "X"s on my scatter plot. These show up fine within the iPython notebook, but when I call image.save_as, my X's become boxes. Here's the relevant code I'm calling: 

`negatives = Scatter3d(
        x = [0],
        y = [1],
        z = [1], 
        mode = 'markers',
        marker = dict(size = 6, symbol = 'x', color = 'red'),
        showlegend = False
    )`

And my plotting code:

`data = Data([negatives])
layout = Layout(autosize = False, width = 1000, height = 800)
fig = Figure(data=data, layout = layout)`

**Comment by jonmmease** [comment]
I just tried this using the orca image export support introduced in version 3.2, and it works!

![3d_xs](https://user-images.githubusercontent.com/15064365/45917410-81d3e000-be44-11e8-9bde-944d75a91af8.png)
