### ISSUE TITLE
Openning plots from docker container

### ISSUE THREAD

**Issue by jsanchezgarcia** [plotly/plotly.py#559]
Any thoughts about how to use plotly.py within a docker container? I've successfully run plotly inside a docker container, but haven't found a way to open the plot without copy/pasting the url in my host browser. 

If anybody has solved this issue, I'd love to hear about it. If this hasn't been solved but there are some ideas about how to tackle this issue, that would be great to know too.

**Comment by jonmmease** [comment]
I'm going to close this since it's more of a question than an issue. Feel free to post a question to the forums (https://community.plot.ly/c/api/python) if you're still interested in exploring this idea!
