### ISSUE TITLE
Improved Features for displaying 3D Geometry

### ISSUE THREAD

**Issue by brovercleveland** [plotly/plotly.py#560]
Hi plotly,

I have a series of requests and questions, all pertaining to the rendering of 3D physical geometry.  I am attempting to image the shape and density of material through use of scatter3d:
(here is an example: http://pollackscience.com/mu2e_plots/particle_trap_example.html)

This method works fine for now, but it there any way to specify the size of scatter3d markers, such that they are given a fixed size in data coordinates, and thus expand or contract when the user zooms in and out?

Additionally, the above plot is generated by binning the scatter points by material density, then plotting 100s of groups of points, each with an opacity related to the density.  It would be much simpler if the `opacity` key for markers could accept an array-like object, as `size` and `color` do.

I have not yet tried to use mesh3d to display geometry in this manner, but is it recommended to use this for displaying potentially 10k+ rectangular boxes with varying opacity?

Thanks

**Comment by jonmmease** [comment]
Hi @brovercleveland , I'm going to close this here as it's more of a discussion topic than an issue.  Feel free to start a discussion on the forums (https://community.plot.ly/c/api/python) if you're still interested in pursuing this!
