### ISSUE TITLE
Is it possible to save graphs as images in offline mode without Ipython notebook?

### ISSUE THREAD

**Issue by jithurjacob** [plotly/plotly.py#564]
Hi I'm trying to write a script which creates a plot and save it as image. I'm currently using seaborn for this. Can I use plotly instead of seaborn for this?

I tried running in shell it's creating a html file opening it in browser and asking for confirmation. Is there any way we could use plotly to directly save as images?

**Comment by cldougl** [comment]
Hi there,
Unfortunately, we don't have a way to save your graph as only a static file.
If working offline, you can use `plot()` and set `auto_open=False` to avoid the html file opening in the browser. See the [image export documentation](https://plot.ly/python/static-image-export/#export-static-image-offline) for an example.

Additionally, we prefer to answer use-case questions in our [community forum](http://community.plot.ly/) and keep this channel only for issues with the code base.

**Comment by jonmmease** [comment]
Update: Programmatic static image export support has been released in 3.2.0: See https://medium.com/@plotlygraphs/plotly-py-end-of-summer-updates-5422c98b9058
