### ISSUE TITLE
Change angle of Title in Violin Plot

### ISSUE THREAD

**Issue by akansal1** [plotly/plotly.py#569]
In Figure Factory, each violin plot is labeled by Title, if string length of these plots is long or there are high number of violin plots in a single plot, titles end up overlapping each other as shown below:
![newplot](https://cloud.githubusercontent.com/assets/8511760/18434401/83858128-790a-11e6-8c14-b245f09b1336.png)

Is there a solution to it ?

Thanks

**Comment by cldougl** [comment]
Hi there, 
There is not a way to change the angle of those titles. My suggested solution would be to add breaks (`<br>`) to the title text to display the titles on multiple lines or increase the overall width of your plot. 

Typically we'd recommend posting use-case questions like this in our forum: http://community.plot.ly/ !
