### ISSUE TITLE
Surface docs should specify which dimensions correspond to x and y axes

### ISSUE THREAD

**Issue by samuela** [plotly/plotly.py#571]
So, we construct a surface plot with something like

``` python
go.Surface(
  name='Estimated GP mean',
  x=x_points,
  y=y_points,
  z=<... some 2-d numpy array ...>)
```

But it's not clear which dimensions of the numpy array correspond to the x and y axes. In other words, should I be passing in `zs` or `zs.T`. There's no way to tell without manually testing.

I just came across an instance where my plots were inexplicably wrong, and this turned out to be the culprit. It would be nice to have a note about this in the docs somewhere.

**Comment by jonmmease** [comment]
I'm going to close this here for now, because the plotly.py doc strings are auto-generated from the documentation in the Plotly.js library.  Feel free to open an issue against this repo if you're still interested (https://github.com/plotly/plotly.js). Thanks!
