### ISSUE TITLE
layout.shape.layer = 'below' does not work when using plotly.offline.plot

### ISSUE THREAD

**Issue by manihamidi** [plotly/plotly.py#572]
The `layout.shape.layer = 'below'`option works fine when using the plotly.plotly.plot() function. i.e. it puts the rectangle below any plotted traces. 

However, when plotly.offline.plot() is used, irrespective of whether the value of that parameter is set to `'below'` or `'above'`, the shape appears on TOP of the traces... 

I'm just trying to shade a region behind some bar plots... i.e. the equivalent of axhspan in matplotlib. 
```
layout = {
'barmode': 'stack',
'shapes': [
    {
        'type': 'rect',
        'x0': 0,
        'y0': 5,
        'x1': 20,
        'y1': 10,
        'layer': 'below',
        'fillcolor': 'rgba(128, 0, 128, 0.3)'
    }]
}
```

**Comment by cldougl** [comment]
This seems to be working for me, can you confirm that you're running the most update version of our python api? 1.12.9

**Comment by cldougl** [comment]
closed due to inactivity. @manihamidi feel free to reopen if you have a reproducible example.

**Comment by manihamidi** [comment]
sorry you were right... i was running 1.9.6
