### ISSUE TITLE
Change init method for GraphWidget

### ISSUE THREAD

**Issue by quang-ha** [plotly/plotly.py#573]
Can we change the init method for `GraphWidget`:

```
 |  __init__(self, graph_url='https://plot.ly/~playground/7', **kwargs)
 |      Initialize a plotly graph widget
 |      
 |      Args:
 |          graph_url: The url of a Plotly graph
```

Doesn't this go against the purpose of making `plotly` available for offline plotting?

**Comment by rskabelund** [comment]
I am also looking for a way to use GraphWidget in offline mode...

**Comment by dmarx** [comment]
:+1:

**Comment by jonmmease** [comment]
The version 3 `FigureWidget` replaces the `GraphWidget` functionality and is fully offline compatible.
