### ISSUE TITLE
Unknown country code breaks event_data selection in Plotly (R/Shiny)

### ISSUE THREAD

**Issue by HLeviel** [plotly/plotly.py#576]
I'm trying to determine clicked country in a world map displayed in shiny.

I used [this example for click event](https://plot.ly/r/shinyapp-map-click/) and [this one for display](https://plot.ly/r/choropleth-maps/) and this code works:

    library(shiny)
    library(plotly)
    
    ui <- shinyUI(fluidPage(plotlyOutput("plot"),textOutput("text")))
    
    server <- shinyServer(function(input, output) {
        df <- read.csv('https://raw.githubusercontent.com/plotly/datasets/master/2014_world_gdp_with_codes.csv')
        output$text <- renderPrint({
          event.data <- event_data("plotly_click")
          if(!is.null(event.data)) event.data else NULL})
        
    
        output$plot <- renderPlotly({
          plot_geo(df) %>%
            add_trace(z = ~GDP..BILLIONS., color = ~GDP..BILLIONS., text = ~COUNTRY, locations = ~CODE)
       })
    })
    
    shinyApp(ui = ui, server = server)

When I click on one of the countries from the first entries of the dataset:

    Afghanistan,21.71,AFG
    Albania,13.40,ALB
    Algeria,227.80,DZA

I get correct selection, where pointNumber+1 is the row number in the dataset:

      curveNumber pointNumber z 
    1 0           0           21.71

      curveNumber pointNumber z 
    1 0           1           13.4

      curveNumber pointNumber z 
    1 0           2           227.8

But if I click on Angola which is after 2 undisplayed countries :

    American Samoa,0.75,ASM
    Andorra,4.80,AND
    Angola,131.40,AGO

I get wrong selection which actually is American Samoa:

      curveNumber pointNumber z 
    1 0           3           0.75

So I'm guessing that the selection is calculated on a list of coutries that are known by plotly, projected on original dataset (which include unknown countries)

I think that I could use the list of country codes currently known by Plotly as a work-around, but I don't know where to find it

**Comment by cldougl** [comment]
Hi there,
This is the python api repo - you may want to check the [r repo](https://github.com/ropensci/plotly) instead or our [community forum](http://community.plot.ly/)
