### ISSUE TITLE
Can you create choropleth subplots

### ISSUE THREAD

**Issue by bote795** [plotly/plotly.py#580]
I am trying to create two subplots of choropleth maps side by side
But when I append_trace  the choropleth 
I get

    PlotlyDictKeyError: 'yaxis' is not allowed in 'choropleth'

    Z:\Anaconda2\lib\site-packages\plotly\graph_objs\graph_objs.pyc in append_trace(self, trace, row, col)
        934             trace['xaxis'] = ref[0]
        935             trace['yaxis'] = ref[1]
    --> 936         self['data'] += [trace]

It seems as though it assumes it will have a yaxis.
Does this mean that it doesn't support the map in subplots or am i doing something wrong?

My code is as follows:

```py
subplots = [] #sub plot
subplots_titles =[]
for column in columns:
    subplots.append(dict(
     type="choropleth",
     locations= data["state_codes"], #states
     z= data[column],
     locationmode="USA-states",
     colorscale= ['Viridis']
    ))
    subplots_titles.append(column)

fig = tools.make_subplots(rows=1, cols=len(columns), subplot_titles=subplots_titles)
    
for index, subplot in enumerate(subplots, start=1):
    fig.append_trace(subplot,1,index)
```

trying to do this [multiple subplots](https://plot.ly/python/map-subplots-and-small-multiples/) except using map. since that is actually a scattered plot. 

Some other charts use the FigureFactory, but i went through the code and i dont think there is one for the choropleth map type.

Thanks!

**Comment by empet** [comment]
A choropleth is not referenced to a cartesian system of coordinates. Here you can find an example of map subplots: https://plot.ly/python/map-subplots-and-small-multiples/

**Comment by bote795** [comment]
well but isnt that one using a scatter plot which utilizes the yaxis and i assume the choropleth doesn't
which is why it doesn't work?

Sorry I don't know much abt how the choropleth actually works. 
But so then are u saying its not going to be possible. BTW i really appreciate the quick response

**Comment by cldougl** [comment]
Thanks for opening a question in the [forum](http://community.plot.ly/t/can-you-create-choropleth-subplots/2425) @bote795 ! 
I'll continue to answer there, as we'd like to keep this channel open for issues rather than support questions.
