### ISSUE TITLE
Huge/large value badly managed in line plot

### ISSUE THREAD

**Issue by VelizarVESSELINOV** [plotly/plotly.py#585]
When one huge/large value is part of the line and the zoom is done on the interesting part nothing it is displayed:
https://plot.ly/~VelizarVESSELINOV/1/

Reset axes: empty plot, even if the on the points it is outside the zoom area, but the other 2 are in the zoom area
Autoscale: the line it is correctly displayed

**Comment by cldougl** [comment]
Hi there,
Thanks for reporting the issue. This is a bug in our underlying plotly.js library and the relevant issue is reported here: https://github.com/plotly/plotly.js/issues/403
Please follow along there for updates on the fix.
