### ISSUE TITLE
Add support for transform graph objects

### ISSUE THREAD

**Issue by etpinard** [plotly/plotly.py#587]
plotly.js [`v1.18.0`](https://github.com/plotly/plotly.js/releases/tag/v1.18.0) now ships with filter and groupby transforms. Transforms are a new plotly.js abstractions - they are incompatible with the current plotly.py plot-schema-to-graph-object logic.

In brief, any trace can now include a `"transforms"` list where each item is a dict with attributes. See example in js: http://codepen.io/etpinard/pen/dpKLpq

cc @Kully  @theengineear @chriddyp

**Comment by theengineear** [comment]
@etpinard , I know that there's been some back and forth on the current transforms implementation. Should we hold off on adding this to plotly.py or go ahead with it?

**Comment by etpinard** [comment]
> Should we hold off on adding this to plotly.py or go ahead with it?

I'd vote for holding off.

**Comment by flying-sheep** [comment]
I’m confused: there’s this example:

https://plot.ly/python/group-by/

but it sets `validate=False`. does this mean it’s an experimental implementation?
