### ISSUE TITLE
Adding `create_gantt` Start and Finish timestamps to minute precision?

### ISSUE THREAD

**Issue by zuxfoucault** [plotly/plotly.py#590]
Is it possible to add `create_gantt` Start and Finish timestamps to minute precision? (so far the minimum unite is day)
Or if I want to add it in my fork, where should I modify it?

Thanks!

**Comment by Kully** [comment]
Hey there.

Minutes _can_ show up in the gantt charts. My understanding of how this works is that if the range between the earliest `Start` time and latest `Finish` time is sufficiently greater than an hour, than an hour will be the preferred metric that will display in the timeline.

Try running this example:
```
import plotly.plotly as py
from plotly.tools import FigureFactory as FF

df = [dict(Task="Job A", Start='2009-01-01', Finish='2009-01-01 00:33'),
      dict(Task="Job B", Start='2009-01-01', Finish='2009-01-01 00:58')]

fig = FF.create_gantt(df)
py.iplot(fig, filename='Simple Gantt Chart', world_readable=True)
```

As you can see, both events are less than an hour in length and they start at the same time so the smallest unit of time becomes minutes.

Run the same example with this data:

```
[dict(Task="Job A", Start='2009-01-01', Finish='2009-01-01 10:33'),
      dict(Task="Job B", Start='2009-01-01', Finish='2009-01-01 00:58')]
```

and notice how hours are used now. You can always zoom in to a part of the chart to get minutes to show up if you so desire.

**Comment by zuxfoucault** [comment]
Yes, it works! Many Thanks!
