### ISSUE TITLE
Feature Request:  Directed graph figure factory

### ISSUE THREAD

**Issue by keithjjones** [plotly/plotly.py#591]
Please think about adding arrows to line graphs.  That way we can plot DiGraph from NetworkX and have it look right in Plot.ly.  Using the arrows on annotations doesn't work so well.  Thanks for a great tool!

**Comment by zhuang1992** [comment]
Agree. Drawing a directed graph is a really common use case.

**Comment by jonmmease** [comment]
I think the best way forward here would to create a graph/di_graph figure factory.  Arrows could be drawn with annotations, or they could be simulated with `scatter` traces as they are in the [`create_quiver`](https://plot.ly/python/quiver-plots/) figure factory.

If we input a NetworkX graph directly, we could also do some interesting things with the node/edge metadata.  e.g. coloring nodes against a colormap, adding node/edge hover tooltips, etc.

**Comment by jonmmease** [comment]
Some addional notes from #839

---
My idea for implementing the variable edge widths in the figure factory would be to discretize the continuous edge weight values into 10-15 bins.  Then for each binned width value, create one `scattergl` trace that has that width and includes all of the graph edges in that bin.  With this approach, I would expect we could support graphs of over 100k total nodes+edges.

Variable edge colors could be supported in the same way, but discretizing the numeric color values and creating a single trace per binned color value.

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
