### ISSUE TITLE
better support np.timedelta64 display in xaxis

### ISSUE THREAD

**Issue by cailiang9** [plotly/plotly.py#592]
![image](https://cloud.githubusercontent.com/assets/3636844/19684360/6464796a-9ae9-11e6-9f0f-f02c4a4e0680.png)

as shown in the figure, the numpy.timedelta in x-axis is not correctly displayed. It's displayed like xxT but should be in mm:ss format. How to set the format in plot function?

**Comment by cldougl** [comment]
Hi there, can you provide a bit more information about what is not displayed correctly in your plot and the code used to generate your plot?

**Comment by cailiang9** [comment]
edited in original comment.

**Comment by jonmmease** [comment]
Going to close this for now due to inactivity. But feel free to provide a full reproducible example and then I'm happy to reopen. Thanks!
