### ISSUE TITLE
Feature Request:  Table Fonts

### ISSUE THREAD

**Issue by keithjjones** [plotly/plotly.py#594]
Please think about adding the ability to easily change fonts, colors, etc for each cell in a plotted table rather than whole rows or by iterating over annotations.  Changing fonts and colors per row and column would be great.

**Comment by cldougl** [comment]
Hi there,
Thanks for this request. It's unlikely that we'll add additional editing capability (at the cell level) for tables via our python wrapper. 
For these feature requests you can follow this issue: https://github.com/plotly/plotly.js/issues/991 in our plotly.js repo
