### ISSUE TITLE
make_subplots don't support multiple axis on the same track

### ISSUE THREAD

**Issue by VelizarVESSELINOV** [plotly/plotly.py#598]
Mix the https://plot.ly/python/multiple-axes/ and https://plot.ly/python/subplots/.

In a subplot I don't see how to setup several yaxis:

```python
import plotly.graph_objs as go
from plotly import tools

from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot
init_notebook_mode(connected=True)

trace1 = go.Scatter(
    x=[1, 2, 3],
    y=[40, 50, 60],
    name='yaxis data'
)
trace2 = go.Scatter(
    x=[2, 3, 4],
    y=[4, 5, 6],
    name='yaxis2 data',
    yaxis='y2'
)

data = [trace1, trace2]

layout = go.Layout(
    title='Double Y Axis Example',
    yaxis=dict(
        title='yaxis title'
    ),
    yaxis2=dict(
        title='yaxis2 title',
        titlefont=dict(
            color='rgb(148, 103, 189)'
        ),
        tickfont=dict(
            color='rgb(148, 103, 189)'
        ),
        overlaying='y',
        side='right'
    )
)

fig = tools.make_subplots(rows=1, cols=1)

fig.append_trace(trace1, 1, 1)
fig.append_trace(trace2, 1, 1)

# fig = go.Figure(data=data, layout=layout)
iplot(fig)
```

**Comment by cldougl** [comment]
Hi there,
The example here: https://plot.ly/python/multiple-axes/#two-yaxes creates multiple y-axis. The example here: https://plot.ly/python/subplots/#simple-subplot demonstrates how to make side by side subplots: https://plot.ly/python/subplots/#simple-subplot

Unfortunately, issues in this repo are reserved for issues with the API/code rather than graphing support so I'll close this issue, but we do have a community forum where you can ask plotting questions: https://community.plot.ly/ !

**Comment by VelizarVESSELINOV** [comment]
@cldougl, did you manage to read and understand the case above?
I'm not looking for support, I'm flagging missing functionality (because of bug or limited design).

**Comment by cldougl** [comment]
Hm @VelizarVESSELINOV  that doesn't quite seem like the case. Those are 2 separate functionalities so it's not necessary to use the `make_suplots` feature to add y-axes. If you'd like to attach an image of the subplot you're trying to achieve perhaps I can point you in the direction of the documentation.

**Comment by cldougl** [comment]
Perhaps this example in our subplot documentation will help you out: https://plot.ly/python/subplots/#side-by-side-subplot

In the above code you've added you've added 1 row and 1 column to your make subplots function which would result in a single plot. If there's a configuration that you're trying to achieve beyond this  https://plot.ly/python/multiple-axes/#two-yaxes or this: https://plot.ly/python/subplots/#side-by-side-subplot go ahead and attach an image or a description of what you'd like to achieve.

**Comment by VelizarVESSELINOV** [comment]
Please find what kind of plot multiaxis per track can be obtained easily with other packages like Bokeh:
![image](https://cloud.githubusercontent.com/assets/8209940/19825096/204aa2d4-9d2a-11e6-93e5-4b0362a36625.png)

As you can see, each track (subplot) has several traces and each trace can have dedicated axis.

The reason why we are trying to use subplot is in order to share the x axis, range selector and range slider.

If there is a workaround to have individual plots and manage to have shared xaxis, rangeselector and rangeslider, I'm interested.

**Comment by cldougl** [comment]
Great thanks, here's an example on how you can achieve that: https://plot.ly/~chelsea_lyn/13433
You can use multiple axes and define the [`domain`](https://plot.ly/python/reference/#layout-yaxis-domain) and [`overlaying`](https://plot.ly/python/reference/#layout-yaxis-overlaying) attributes

**Comment by VelizarVESSELINOV** [comment]
Thank very much, this help me a lot, a lot of code was needed to build the plot, but at the end it is working (the zoom it is slower than Bokeh, strange).

The order of domain [0 bottom, 1 top], anchors, overlaying, plus numbering system starting from 1 was strange to setup, I hope next time will be easier.
