### ISSUE TITLE
Plotly needs a jupyterlab extension to work with Jupyter Lab

### ISSUE THREAD

**Issue by aggFTW** [plotly/plotly.py#600]
As @tc0312 mentioned in https://github.com/jupyterlab/jupyterlab/issues/1188:

Plotly uses AMD to inject its javascript library to the browser from the kernel: [code](https://github.com/plotly/plotly.py/blob/master/plotly/offline/offline.py#L159)
This's not working in JupyterLab right now because lab.html doesn't load require.js.

Discussion in that issue points to the fact that Jupyter Lab will require packages to load front end code via the lab extensions framework.

cc. @mdtusz and @yankev

**Comment by jasongrout** [comment]
I'm not familiar with the plotly code, but perhaps a good model to follow is the [vega plugin](https://github.com/altair-viz/jupyterlab_vega)

**Comment by rgbkrk** [comment]
As noted in jupyterlab/jupyterlab#1188:

nteract has a [plotly renderer](https://github.com/nteract/nteract/blob/0f14082c6e98bbc86a54ea1d3c33d655b1f252f2/src/notebook/components/transforms/plotly.js) that relies on the [Plotly JSON Chart Schema](http://help.plot.ly/json-chart-schema/) with mimetype `application/vnd.plotly.v1+json`

@chriddyp has initial work for that support in https://github.com/plotly/plotly.py/pull/562 (which would translate to jupyterlab as well with the same mimetype).

**Comment by jasongrout** [comment]
nice, thanks for pointing that out, @rgbkrk.

**Comment by rgbkrk** [comment]
JupyterLab extension for Plotly courtesy @gnestor: https://github.com/gnestor/jupyterlab_plotly

**Comment by sudburyrob** [comment]
cc @cldougl

**Comment by gnestor** [comment]
FYI https://github.com/gnestor/jupyterlab_plotly is moving over to https://github.com/jupyterlab/jupyter-renderers. Classic notebook extension coming soon!

**Comment by Juanlu001** [comment]
@gnestor Is there a place where we can track the progress of the classic notebook extension? Thanks!

**Comment by gnestor** [comment]
We're tracking it here: https://github.com/jupyterlab/jupyter-renderers/issues/3

**Comment by gnestor** [comment]
This can be closed with the addition of @jupyterlab/plotly-extension and plotlywidget 👍
