### ISSUE TITLE
Bad data (scatter) display 

### ISSUE THREAD

**Issue by VelizarVESSELINOV** [plotly/plotly.py#602]
In a normal axis:
![image](https://cloud.githubusercontent.com/assets/8209940/20072742/72c5f2b4-a4de-11e6-810a-58360bbc900c.png)
In range selector: 
![image](https://cloud.githubusercontent.com/assets/8209940/20072890/0d9174ee-a4df-11e6-83ae-e293ea16ec0c.png)

Looks like there is a display problem (**bug**), when I deeply zoom the display is back to normal.

Any workaround to fix this display issue?

**Comment by cldougl** [comment]
Hi there,
Could you attach a code sample or link an example that reproduces this issue?

**Comment by theengineear** [comment]
Going to close this down. Feel free to reopen if you can provide steps to reproduce.
