### ISSUE TITLE
Expose rugplot parameter in `_violinplot` to `create_violin`?

### ISSUE THREAD

**Issue by colinfang** [plotly/plotly.py#603]
Can we config `rugplot` in `create_violin`?

    _violinplot(vals, fillcolor='#1f77b4', rugplot=True)

https://github.com/plotly/plotly.py/blob/86291ffc593048becceb7d430464524f811598a3/plotly/tools.py#L2755

**Comment by Kully** [comment]
Do you just want `rugplot` exposed in the function signature?

**Comment by colinfang** [comment]
Yep. `rugplot` causes too much performance overhead when the dataset is large. Currently, I have to manually strip those traces away in json.
