### ISSUE TITLE
Area Plots not displaying properly on subplots object

### ISSUE THREAD

**Issue by richard-muir** [plotly/plotly.py#606]
Making a stacked area plot in Jupyter, everything is displayed fine, the traces all display properly:
![chart-in-notebook](https://cloud.githubusercontent.com/assets/10999614/20304190/dcfd118c-ab26-11e6-8e20-e18a8ec8aa08.jpg)

However when the same chart is pushed to the Plotly cloud, the traces go a bit weird:
![chart-in-web-app](https://cloud.githubusercontent.com/assets/10999614/20304203/eb045f06-ab26-11e6-968d-71bca7886501.png)

Please let me know if you need any more info; I'm not sure how best to describe this issue.

**Comment by cldougl** [comment]
Hi there,
Are you still experiencing this issue? If so, it would be helpful if you could attach the code you're using to create the subplots.
Thanks!

**Comment by richard-muir** [comment]
Hey,

I've zipped up the data, as well as two images. One image shows the chart that was created with the plotly.offline.iplot(), and the other shows the chart that was created with plotly.plotly.iplot() and plotly.plotly.plot().

`def quintileLegend(n):
    if n == 0:
        return "<br>(Most disadvantaged)"
    elif n == 4:
        return "<br>(Least disadvantaged)"
    else:
        return ""

colours = ['rgb(224,243,219)','rgb(186,228,188)','rgb(123,204,196)','rgb(67,162,202)','rgb(8,104,172)']
barcols = ['Quintile {}'.format(i) for i in range(1,6)]
    
def POLARStackedArea(dataIn, leg):
    data = pd.read_csv("POLAR{}.csv".format(dataIn), index_col = 0)

    scatterTraces = []
    for i in range(5):
        temp = {'type' : 'scatter',
                              'mode' : 'lines',
                              'x' : [j for j in list(data.index) if 'n' not in str(j)],
                              'y' : data.loc[[j for j in range(2004, 2015)]]['Q{}RunTot'.format(i+1)],
                              'showlegend' : False,
                              'text' : data.loc[[round(j) for j in range(2004, 2015)]]['Quintile {}'.format(i+1)],
                              'hoverinfo' : 'text',
                              'fill' : 'tonexty',
                                'fillcolor' : colours[i],
                              'name' : barcols[i],
                              'marker' : {'color' : colours[i]},
                              'line' : {'width' : 0}}
        temp.update({'text' : ["Quintile {}: {}%".format(i+1, round(j*100)) for j in temp['text']]})
        scatterTraces.append(temp)
    return scatterTraces
    

    
layout = {'barmode' : 'stack',
          'width' : 1000,
          'title' : "Share of entrants by institution tariff level",
         'xaxis1' : {'range' : [2003, 2015],
                     'ticktext' : ["'04-05","'09-10","'14-15"],
                    'tickvals' : [ 2004, 2009, 2014 ],
                    'ticklen' : 5,},
                    #'tickangle' : 45},
          'xaxis2' : {'range' : [2003, 2015],
                     'ticktext' : ["'04-05","'09-10","'14-15"],
                    'tickvals' : [ 2004, 2009, 2014 ],
                     'ticklen' : 5,},
                     #'tickangle' : 45},
          'xaxis3' : {'range' : [2003, 2015],
                     'ticktext' : ["'04-05","'09-10","'14-15"],
                    'tickvals' : [ 2004, 2009, 2014 ],
                     'ticklen' : 5,},
                     #'tickangle' : 45},
         'yaxis' : {'tickformat' : ".0%",
                   'hoverformat' : ".0%",
                    "title" : "Share of first degree entrants",
                   'range' : [0,1],},
          'legend' : {'traceorder' : 'reversed + grouped',
                     'tracegroupgap' : 15}
                 }


testfig = tools.make_subplots(rows=1, cols=3, 
                              print_grid=False, 
                              shared_yaxes=True, 
                              subplot_titles=('Low tariff',                       
                                              'Medium tariff',                                                    
                                              'High tariff'),
                             horizontal_spacing = 0.03,)

for d in POLARStackedArea('low',1):
    testfig.append_trace(d, row=1, col=1)
    
for d in POLARStackedArea('med',0):
    testfig.append_trace(d, row=1, col=2)
    
for d in POLARStackedArea('high',0):
    testfig.append_trace(d, row=1, col=3)
    
    
testfig['layout'].update(layout)
for i in range(len(testfig['layout']['annotations'])):
    testfig['layout']['annotations'][i]['font'].update({'size' : 14})

    
po.iplot(testfig)
plotly.iplot(testfig)
[plotly.zip](https://github.com/plotly/plotly.py/files/636415/plotly.zip)
`

**Comment by cldougl** [comment]
Thanks for attaching the script! Everything seems to be running well for me: https://plot.ly/~chelsea_lyn/13646 (<- see ipython notebook )

Could you make sure you're using an updated version of our python package (we're on version 1.12.12 now) and that you can reproduce the issue?
If you're still getting the issue, can you let me know what version of python/ipython you're using?

**Comment by richard-muir** [comment]
Hey Chelsea,

That all seems to be working after updating. Thanks for helping out.
