### ISSUE TITLE
HTTPError 401 when using sharing='secret' plot option

### ISSUE THREAD

**Issue by mgsoccer16** [plotly/plotly.py#607]
I traced the error to the following lines of code in the _add_share_key_to_url_ function:
```
    new_response = requests.patch(url,
                                  headers=_api_v2.headers(),
                                  data={"share_key_enabled":
                                        "True",
                                        "world_readable":
                                        "False"})
```
new_response.content:
`{"errors":[{"code":"UNKNOWN","message":"Bad API key","path":null,"field":null}],"detail":"Bad API key"}`

**Comment by cldougl** [comment]
hey @mgsoccer16 can you include the exact code that failed? 
please note that you must have your credentials set and secret files count towards your private file limit ([1 for community users](https://plot.ly/products/cloud/) / unlimited for personal/pro account users)

**Comment by mgsoccer16** [comment]
Thanks for responding @cldougl.
Here's the exact code that failed.
`fig = go.Figure(data = data,layout=layout)`
`py.iplot(fig,filename = 'scatterplot for key customers',sharing='secret')`

This code runs without an error when using `sharing='private`

I'm using plotly pro through work and haven't changed the credentials.

**Comment by cldougl** [comment]
That looks good, can you let me know which version of the python API you're using (we're currently up to version 1.12.10)?

**Comment by mgsoccer16** [comment]
@cldougl I am using version 1.12.09.

I just tried updating to version 1.12.10 and I still get a similar error.
`HTTPError: 401 Client Error: UNAUTHORIZED for url: https://api.plot.ly/v2/files/mgoti:606`

**Comment by cldougl** [comment]
It looks like the username: mgoti is not a personal/professional account on plot.ly.
Is it possible you're using an on-premise server? If that's the case you can follow these instructions here: https://plot.ly/python/getting-started/#special-instructions-for-plotly-onpremise-users and email our support team if you run into further issues

**Comment by mgsoccer16** [comment]
So I actually have 2 accounts under the same username. One for the on-premise server and the other is just a community plan. 
Could that be causing the issue?

**Comment by cldougl** [comment]
Yes I believe so- it looks like, at the moment, your configuration is pointing to 'plot.ly' (our cloud) which will use your community plan (and you are only allowed 1 private file on your community plan)
You can check your configuration and make sure it is pointed t

**Comment by mgsoccer16** [comment]
It looks like when `sharing='private'` plotly is pointing to the server, but when `sharing='secret'` it then points to 'plot.ly'.

I ran these two lines of code back to back:
`py.plot(data, filename='basic-bar',sharing='private')`
`py.plot(data, filename='basic-bar', sharing='secret')`

The first line returned the correct link to the plot, pointing to the on-premise server. The second line returned the same error as before.
`HTTPError: 401 Client Error: UNAUTHORIZED for url: https://api.plot.ly/v2/files/mgoti:56`

**Comment by cldougl** [comment]
@mgsoccer16 -- seems like the issue was stemming from your configuration file. When using Plotly's python API and an on-premise server, the `plotly_api_domain` must be set for certain features to function correctly. Instructions for setting up domain information can be found here: https://plot.ly/python/getting-started/#special-instructions-for-plotly-onpremise-users

Would you mind confirming that this has been resolved?

**Comment by mgsoccer16** [comment]
That seems to be the issue. Thanks!

**Comment by cldougl** [comment]
Glad it's been resolved!
