### ISSUE TITLE
Scattergl does not render shared_xaxis with make_subplots properly

### ISSUE THREAD

**Issue by ipolaco** [plotly/plotly.py#608]
trace_clicks = go.Scattergl(x=df.date, y=df.clicks, mode='markers+lines', name = 'Clicks')
    trace_impressions = go.Scattergl(x=df.date, y=df.impressions, mode='markers+lines', name = 'Impressions')
    trace_ctr = go.Scattergl(x=df.date, y=df.ctr, mode='markers+lines', name = 'CTR (%)')
        
    fig = tools.make_subplots(rows=3, cols=1, shared_xaxes=True)
        
    fig.append_trace(trace_clicks, 1, 1)
    fig.append_trace(trace_impressions, 2, 1)
    fig.append_trace(trace_ctr, 3, 1)
        
    fig['layout'].update(title=airline_branding)

    py.plot(fig, filename='file_name', auto_open = False)

Example of incorrect rendering:

<img width="768" alt="screen shot 2016-11-18 at 14 18 27" src="https://cloud.githubusercontent.com/assets/11196428/20443206/f09075a2-ad99-11e6-89c3-5cebc5259878.png">

**Comment by jonmmease** [comment]
This appears to be working properly with plotly.py 3.2.1

```python
import plotly.graph_objs as go
from plotly import tools
x = [1, 2, 3, 4]

trace_clicks = go.Scattergl(x=x, y=[1, 2, 3, 4], mode='markers+lines', name = 'Clicks')
trace_impressions = go.Scattergl(x=x, y=[3, 2, 4, 5], mode='markers+lines', name = 'Impressions')
trace_ctr = go.Scattergl(x=x, y=[5, 4, 7, 8], mode='markers+lines', name = 'CTR (%)')
    
fig = tools.make_subplots(rows=3, cols=1, shared_xaxes=True)
    
fig.append_trace(trace_clicks, 1, 1)
fig.append_trace(trace_impressions, 2, 1)
fig.append_trace(trace_ctr, 3, 1)
    
fig['layout'].update(title='airline_branding')
go.FigureWidget(fig)
```
![newplot](https://user-images.githubusercontent.com/15064365/45917739-04ab6980-be4a-11e8-91b1-f005a5c2ab30.png)

Feel free to open a new issue against version 3 if you are still experiencing issues.
