### ISSUE TITLE
Opacity for 3D plots doesn't behave as expected

### ISSUE THREAD

**Issue by cmcneil** [plotly/plotly.py#610]
Hello,
When plotting a 3D surface using iplot, the `opacity` parameter does not behave continuously. Setting it to 1.0 will cause full opacity, and setting it to 0.999999 will cause the surface to be VERY transparent, somewhere around 0.5 opacity. It will behave relatively linearly below this point.
```
surface = Surface(
        x=X,
        y=Y,
        z=Z,
        cmax=-1,
        cmin=1,
        colorscale=[[0, 'rgb(0,0,153)'], [1, 'rgb(0,102,102)']],
        opacity=1.0
)
```

Expected behavior: The opacity parameter should be continuous. A tiny change in the parameter value should be imperceptible.

**Comment by cldougl** [comment]
Hi there,
This is an issue with our underlying plotly.js library so the issue has been moved to: https://github.com/plotly/plotly.js/issues/1206
