### ISSUE TITLE
Downloading malformed `plot-schema.json` can cause `import plotly` to break

### ISSUE THREAD

**Issue by chriddyp** [plotly/plotly.py#613]
See https://github.com/plotly/plotly.py/issues/612 for the original issue that prompted this discussion. 

To make sure that this never happens again, we should either:

- Extend the try / except around the construction of `graph_objs` off of the downloaded `plot-schema.json` and use the cached version if it does not work
- Remove the auto-downloading `plot-schema.json` on import and perform more frequent (weekly) releases of the python library in sync with the plotly.js version updates.

**Comment by etpinard** [comment]
The more radical solution is implemented in https://github.com/plotly/plotly.py/issues/613

**Comment by rcscott** [comment]
I feel strongly that the auto-downloading should be removed. If someone wants the newest features then they can upgrade their plotly version. It's a strange design decision that the library can change automatically even if I have a specific version in my `requirements.txt`.

**Comment by theengineear** [comment]
Removed in 1.13.0.
