### ISSUE TITLE
Violin plots plotted OK offline, display supplementary rugplots online

### ISSUE THREAD

**Issue by empet** [plotly/plotly.py#616]
Example: http://nbviewer.jupyter.org/gist/empet/4d94eda0698c9c38dbc86cb082e0f11b
The same bug is  also exhibited   in the  tutorial destinated to violin plots: https://plot.ly/python/violin-plot/

**Comment by cldougl** [comment]
Thanks for reporting @empet ! The bug causing this issue is in plotlyjs (rather than the python api) so I moved the issue to: https://github.com/plotly/plotly.js/issues/1196
