### ISSUE TITLE
Unable to reproduce widget examples

### ISSUE THREAD

**Issue by brovercleveland** [plotly/plotly.py#627]
I'm attempting to reproduce the drop-down widget as show in this example:
https://plot.ly/python/dropdown-widget/

However, the GraphWidget does not display (the drop-down box does, however).  I'm using a clean virtualenv with `plotly 1.12.11` and `IPython 5.1.0`.

This same issue seems to be present in all widget examples I've tested.

**Comment by mtomassoli** [comment]
This is related to issue #490. I sent PR #641 to fix this.

**Comment by jonmmease** [comment]
Closing since `FigureWidget` has replaced the functionality of `GraphWidget` in version 3. We're still in the process of getting the documentation updated unfortunately.
