### ISSUE TITLE
Export Static Image Offline without opening webbrowser.

### ISSUE THREAD

**Issue by PhML** [plotly/plotly.py#636]
See [this discussion](https://community.plot.ly/t/use-plotly-offline-to-save-chart-as-image-file/408) on Plotly community site.

When using plot with `image` argument, it first plot in the browser, then open a download file dialogue window and need a manual intervention. As I have several images generated, it's not possible to do it manually.

It would be nice to save image files without this dialogue window.

**Comment by cldougl** [comment]
Hi @PhML -- We have removed this dialogue window in version 1.12.10: https://github.com/plotly/plotly.py/blob/master/CHANGELOG.md#11210---2016-11-28

The plot will still open in the browser (this is the intended behaviour and necessary for image generation), but there is no longer a dialogue window, no manual intervention necessary.

**Comment by Midnighter** [comment]
It still is downloaded to the default browser download directory which means I need to move them manually later...

**Comment by jonmmease** [comment]
Update: Programmatic static image export support has been released in 3.2.0: See https://medium.com/@plotlygraphs/plotly-py-end-of-summer-updates-5422c98b9058
