### ISSUE TITLE
can not update offline plot with jupyter in a loop

### ISSUE THREAD

**Issue by eleanor2017** [plotly/plotly.py#638]
Hello,
I am working with jupyter offline and would like to update a plot, not plot another one.
The following code give me 10 plots, not one being updated 10 times :

import time
import numpy as np
from plotly.offline import plot
from plotly.graph_objs import *
for i in range(10):
time.sleep(1)
iplot([Box(y = np.random.randn(50), showlegend=False) for i in range(45)], show_link=False, filename = 'myfile')

Does plotly offer the possibility to update a plot ofline ?
Thank you!

**Comment by mtomassoli** [comment]
I just wrote a widget which lets you draw and update plots completely offline.

For instance, you can write:

    from JSWidget import *
    import plotly.graph_objs as go

and then:

    w = JSWidget()
    display(w)
    w.new_plot([go.Scatter(x=[1,2,3,4], y=[1,2,5,2])])

You can also call new_plot before the widget is displayed.

Let me know if you're still interested. I don't think I'll send a pull request because I don't have time to test my code and document it beyond my needs.

**Comment by gondzo** [comment]
I'm definitely interested. Does it update just the plot data, or replaces the entire plot with a new one ?

**Comment by mtomassoli** [comment]
It has almost full support for the JS API and all the events (you can attach Python callbacks). I even added double-buffering to eliminate flickering with particularly heavy plots. Promises are also supported, i.e. you can specify callbacks to be called as soon as operations have completed.

The code is not complete yet cause I'm quite busy at the time.

**Comment by ldardis** [comment]
Can you share your code to allow a Plot.ly plot to be updated. There are lots of people looking for this feature and would very much appreciate your efforts in solving this!

Thanks, Lee.

**Comment by cldougl** [comment]
@eleanor2017 can you let us know the use case for updating the plot in a jupyter notebook in a for loop? Perhaps you're looking for animations: https://plot.ly/python/animations/#offline-mode

**Comment by ldardis** [comment]
My use case: I have a loop that gathers test data which takes many mins or hours to complete. Currently I have a progress bar to show the time left but I would like to display a plot of the data and update this during the test within the same notebook. I wasn't aware of the animation feature but I don't see how I can use it to update the plot within a loop.

**Comment by cldougl** [comment]
This is true the animation feature wouldn't help in this case. Unfortunately, the only solution that we support at the moment to create and update plots in a loop would be using online (https://plot.ly/python/file-options/#creating-new-files) rather than offline.

**Comment by mtomassoli** [comment]
Here's the widget I wrote for offline plotting: [widget](https://github.com/mtomassoli/JSWidget).

**Comment by jonmmease** [comment]
This functionality is now available in version 3 with `FigureWidget`

**Comment by BijanSeif** [comment]
Hi @jonmmease 

What is the problem on the below codes? why in each loop my figure doesn't update? what should I do till in each loop my figure updates? (I'm using Jupyter notebook)
```
fig=go.FigureWidget()

for i in range(10):
  time.sleep(1)
  fig.update_traces(x=[rnd for i in range(10)])

```
