### ISSUE TITLE
Intermittent image server test errors are slowing us down!

### ISSUE THREAD

**Issue by theengineear** [plotly/plotly.py#649]
Checkout this one, it failed in *one* case intermittently:

https://circleci.com/gh/plotly/plotly.py/1843

One quick fix is to try additional times to make the request (maybe 5 times?) so that we can be pretty confident that it will succeeed *one* of those times.

A better fix is to dig in and actually find out why this is happening...

**Comment by meyer-anders** [comment]
still happening!

**Comment by jonmmease** [comment]
Closing as automatic retrying logic was added to version 3
