### ISSUE TITLE
Create a newer release.  The most recent release is 1.6.12 from March 2015.

### ISSUE THREAD

**Issue by hzclarksm** [plotly/plotly.py#654]

**Comment by etpinard** [comment]
Have you heard of `pip`?

**Comment by hzclarksm** [comment]
Certainly.  What versions are available through pip? For reproducibility purposes I do not necessarily want the latest greatest version.

**Comment by theengineear** [comment]
Thanks @hzclarksm , I've updated with the newest release. As was mentioned above, you can install older versions of pip, but agreed that it's hard to find those tags on PyPI. Closing.
