### ISSUE TITLE
Exporting animations to GIF/PNG/SVG

### ISSUE THREAD

**Issue by EmilienDupont** [plotly/plotly.py#664]
Hello,

The recent animation features are great! However, I was wondering if it is possible to export these animations to e.g. gif format? I had a look through the code and it does not look like this is possible at the moment. Is this something you plan to implement?

Thank you!

**Comment by jackparmer** [comment]
@EmilienDupont Good question. There's no automated, quick way to do this right now through Plotly. You could write a utility in Python that saves each frame as an image, then stitch those images together using Pillow's `gifmaker`:
http://stackoverflow.com/questions/24688802/saving-an-animated-gif-in-pillow

I have tried this myself, but it's the first thing I'd try 👍

**Comment by EmilienDupont** [comment]
Thank you @jackparmer, will give it a try

**Comment by raulf2012** [comment]
Just to add my 2¢, the solution proposed by @jackparmer would presumably not capture the animated transitions between frames

My workaround is to just use a screen capture/GIF making program (ScreenToGif) to manually create a GIF of the animation

Not the most elegant solution but it'll work for now

**Comment by soerendip** [comment]
Yes, that should be build in. :-)

**Comment by FFengIll** [comment]
I used bellow from `https://stackoverflow.com/a/73788157` with a little edit.

```python
import PIL
import io
# generate images for each step in animation
frames = []
for s, fr in enumerate(fig.frames):
    # set main traces to appropriate traces within plotly frame
    fig.update(data=fr.data)
    # move slider to correct place
    fig.layout.sliders[0].update(active=s)
    # generate image of current state
    frames.append(PIL.Image.open(io.BytesIO(fig.to_image(format="png"))))

# append duplicated last image more times, to keep animation stop at last status
for i in range(5):
    frames.append(frames[-1])

# create animated GIF
frames[0].save(
        "test.gif",
        save_all=True,
        append_images=frames[1:],
        optimize=False,
        duration=500,
        loop=0,
    )
```
