### ISSUE TITLE
Q/A on `2.0.0-pre` release.

### ISSUE THREAD

**Issue by theengineear** [plotly/plotly.py#669]
Yay, some needed cleanup and better organizing now exists on master. BUT, it'd be great to get a little testing before we do an official release.

Things I'd like to check in particular:

* Share Key stuff
* `py.plot` calls
* Figure Factory stuff

Most importantly, it'd be really cool if we could just get a few of us to open up recent (or old) notebooks / scripts / etc and see if they still run as expected.

I think the easiest way to install is to just use the `tar.gz` release link:

`pip install https://github.com/plotly/plotly.py/archive/v2.0.0-pre.tar.gz`

**Comment by theengineear** [comment]
@chriddyp @cldougl @Kully if you end up having a couple moments to run some code, I'd really ❤️ it! No pressure though!

**Comment by Kully** [comment]
> @chriddyp @cldougl @Kully if you end up having a couple moments to run some code, I'd really ❤️ it! No pressure though!

Okay, going to do some testing now1

**Comment by Kully** [comment]
Everything I checked looks fine:
-FigureFactories were relocated properly and calling `help(function)` works just fine
-py.plot() calls work fine - I tried a few (violin, scatterplotmatrix, etc)
-secret plots generate a url just fine and the url works (I ran the tutorial scatter and a violin plot iirc in 'secret')

👍  for the no doubt necessary but cool Deprecated messages for using `plotly.tools.FigureFactory`!
@theengineear

**Comment by theengineear** [comment]
@Kully Great! Thanks for taking the time to do that, I really appreciate it!

**Comment by Kully** [comment]
> @Kully Great! Thanks for taking the time to do that, I really appreciate it!

You had already merged into master before my testing right?

**Comment by cldougl** [comment]
ran through most of our getting started / scientific / 3d / animation / axes / offline docs with python 3.4 and everything looked good to me!

**Comment by theengineear** [comment]
Great! Let's :shipit:!
