### ISSUE TITLE
Dendrogram with heatmap example

### ISSUE THREAD

**Issue by ArtyomKaltovich** [plotly/plotly.py#673]
https://plot.ly/python/dendrogram/#plot-a-dendrogram-with-a-heatmap
I am trying to use this example. It works fine, but when I try to use bigger dataset there is a missmatch in dendrogram's and heatmap's label.

 As you can see there is a blank space between Dendrograms and heatmap and labels exceed heatmap.
![image](https://cloud.githubusercontent.com/assets/10615183/22267825/44bb95fe-e296-11e6-8d52-7fb67ec909e4.png)

**Comment by cldougl** [comment]
Hi there,
Unfortunately we cannot help with individual questions and problems in this repo.
For support questions please visit our support site: https://support.plot.ly/
or post in our community forum: https://community.plot.ly/

If you encounter a problem with the library and create an issue here, please include code that demonstrates a minimal reproducible example of the bug.
