### ISSUE TITLE
how can i get plotly pie chart hover output on shiny R

### ISSUE THREAD

**Issue by sachinbanugariya** [plotly/plotly.py#681]
hello,
we used render_plotly for plot pie chart with hover output on shiny R code.
that is working good.
 
pie chart is showing hover when mouse is pass through it.
but we want that hover output link with other, 
means we want to get that event_hover output print or store somewhere which we used for another event.

we are not able to print that hover_event output, like other normal bar example.

so please give example and guide how we get that hovered_data.

thanks.

**Comment by cldougl** [comment]
Hi there,
This repo is for Plotly's [python API](https://plot.ly/python/) and issues are reserved for bug reports. If you have a support question, please check out our support app: https://support.plot.ly/.
