### ISSUE TITLE
Lines are Unaligned after Adding Line Breaks in Text

### ISSUE THREAD

**Issue by zhangallan** [plotly/plotly.py#690]
First off, thanks a lot for a great package!

I'm currently seeing some odd behavior when it comes to adding line breaks into text when the text is "attached" to a given data point, which causes the text between lines to be misaligned.

My understanding is that you are supposed to insert line breaks through `<br>` tags, and this works well for all other elements that I've tried (titles, annotations, etc). However, when I try to add a line break into the text in [this example](https://plot.ly/python/text-and-annotations/#text-font-as-an-array---styling-each-text-element), the resulting lines in the label are misaligned for each city. This seems to be an issue when I try it on the online plot editor as well. So for example changing the text from `"Montreal"` to `"Montreal<br>Montreal"` results in the following:
![image](https://cloud.githubusercontent.com/assets/8095829/22803134/b5f8f372-eee1-11e6-9250-b2a139402256.png)
whereas I would expect to see the lines vertically aligned to the left, for example. It doesn't look like adding in `<span>` tags with CSS styling lets you fix the issue either, at least for the various styles that I tried.

**Comment by jonmmease** [comment]
Going to close this here since this is an issue that would need to be addressed in the Plotly.js library (https://github.com/plotly/plotly.js). Feel free to open a new issue there if you still experience this problem with the current version of plotly.py
