### ISSUE TITLE
Allow users to control autoplay feature on Python animation frames

### ISSUE THREAD

**Issue by richard-muir** [plotly/plotly.py#697]
Hey all,

Loving the new animation functionality you've introduced!

It would be great if you could allow us to decide whether or not we want the animation to autoplay. 

For example, your GapMinder plot created with the Python API [here](https://plot.ly/python/animations/) autoplays, whilst the same plot with .js [here](https://plot.ly/javascript/animations/) doesn't.

Cheers!

**Comment by mikapfl** [comment]
Hi, just a quick comment for a workaround: If you have your plot in the `pl1` object, you can get rid of autoplaying by:
`pl1 = re.sub("\\.then\\(function\\(\\)\\{Plotly\\.animate\\(\\'[0-9a-zA-Z-]*\\'\\)\\;\\}\\)", "", pl1)`

Full example:
```python
pl1 = plot(fig, output_type='div')
pl1 = re.sub("\\.then\\(function\\(\\)\\{Plotly\\.animate\\(\\'[0-9a-zA-Z-]*\\'\\)\\;\\}\\)", "", pl1)
with open(fname, 'w') as fd:
    fd.write("""<html>
<head>
</head>
<body>
{}
</body>
</html>
""".format(pl1))
```

It is of course a hack, but does the job for me

**Comment by nicolaskruchten** [comment]
(bump) this is indeed a bit odd... @jonmmease any insight into why things autoplay and what it might take for them not to? a flag in `iplot()`?
