### ISSUE TITLE
Whisker should not be length of max outlier

### ISSUE THREAD

**Issue by SirExpie** [plotly/plotly.py#701]
What I am trying to achieve is a graph with multiple boxplots where the outliers are not showing so that the y-axis is smaller (y-axis: 0-1000).
I've tried using 'boxpoints=False', but then the whiskers are **automatically updated to the height of the outliers** and the y-axis of the graph is still as high as it is with outliers as points. (y-axis: 0-3000). This should not happend, the whiskers should stay the same.

Because the outliers I have are way higher than the boxplot itself, it makes the boxplot smaller and less comparable with the other boxplots.

**Comment by cldougl** [comment]
Hi @SirExpie - this is the intended behaviour. See: http://codepen.io/plotly/pen/WxrdQX

We currently do not have an option that removes outliers from your chart. Feel free to open a feature issue to expand the `boxpoints` attribute in our plotly.js repo:
https://github.com/plotly/plotly.js/issues?q=is%3Aopen+is%3Aissue+label%3A%22type%3A+feature%22 or the feature request section on our new support page: https://support.plot.ly/feature-requests
