### ISSUE TITLE
Box size % to Dashboards API

### ISSUE THREAD

**Issue by Kully** [plotly/plotly.py#711]
Be able to manually control box percentages and change the size of the dashboard easily

**Comment by Kully** [comment]
Additionally, solve the problem of stacking several plots on top of each other.

Currently with 50%, stacking 8 plots on top of each returns a layout:

![screen shot 2017-03-28 at 4 08 44 pm](https://cloud.githubusercontent.com/assets/10369095/24428256/d4f5edce-13db-11e7-9e93-a9e631ff2a85.png)

**Comment by alexcthompson** [comment]
+1.  I'm trying to create a dashboard programmatically, and I'm ending up reverse engineering the way the splits and sizes are created... tricky.

**Comment by Kully** [comment]
> +1. I'm trying to create a dashboard programmatically, and I'm ending up reverse engineering the way the splits and sizes are created... tricky.

Agreed. It's definitely something I don't think users should need to learn about. And one of the major weak points in the Dashboard API.

**Comment by iveney** [comment]
Is this issue not being fixed?

**Comment by Kully** [comment]
> Is this issue not being fixed?

Thanks for the reminder @iveney . I have other projects that I am working on at the moment so I will be fixing this issue after those.

**Comment by Kully** [comment]
Closing as issue is now fixed and will appear in the next version of plotly.

**Comment by Kully** [comment]
@iveney @alexcthompson 
In case you did not know, this issue is now fixed and dashboards now have an `.insert` feature. See the [CHANGELOG](https://github.com/plotly/plotly.py/blob/master/CHANGELOG.md) for more details on what else is added in the newest version of plotly.
[please +1 this message to confirm I know you received the message]

**Comment by alexcthompson** [comment]
+1 - glad to hear it, good work.
