### ISSUE TITLE
Legend doesn't show when exists one data type

### ISSUE THREAD

**Issue by Enorio** [plotly/plotly.py#718]
Is there any way for enable the legend when a plot only have one data type? For example:

[plot](http://imgur.com/QnZYDZw)

Even when i have **showlegend=True**, the plot doesn't show the legend

**Comment by cldougl** [comment]
Hi there, 
In the future, for support questions please visit our support site: https://support.plot.ly/
or post in our community forum: https://community.plot.ly/

If you encounter a problem with the library and create an issue here, please include code that demonstrates a reproducible example of the bug.

To plot a legend with a single trace you can see the following example:
https://plot.ly/python/legend/#show-legend
