### ISSUE TITLE
[Bug?] fill = "tonexty" reverses legend and fills to previous y

### ISSUE THREAD

**Issue by tchlux** [plotly/plotly.py#722]
Original (unmodified) source code for example is at:
[https://plot.ly/python/filled-area-plots](https://plot.ly/python/filled-area-plots)

When creating a plot, fill=None will order the series in the legend in the same order as they are presented in the plot "data" keyword argument.

For fill="tonexty" and fill="tonextx", the entries in the legend are reversed, and the fill is performed to the next legend entry, which is actually the *previous* data series. 

This is unexpected behavior, either "tonexty" should be "toprevy" or the legend should not be reversed and the fill should actually go to the next series provided in data instead of the previous.

```
import plotly
import plotly.graph_objs as go

trace0 = go.Scatter(
    x=[1, 2, 3, 4],
    y=[3, 5, 1, 7],
    fill='tonexty',
    mode= 'none',
    name='Trace0',
)
trace1 = go.Scatter(
    x=[1, 2, 3, 4],
    y=[0, 2, 3, 5],
    fill='tozeroy',
    mode= 'none',
    name='Trace1',
)

data = [trace0, trace1]
plotly.offline.plot(data, filename='basic-area-no-bound')
```

Expected behavior is that there will be a fill from trace0 -> trace1 and trace1 -> x-axis, yet that is not the case. The series are reversed, the legend is displayed backwards, and the fill goes from trace0 -> x-axis and trace1 -> x-axis. See attached pictures, first "Expected-Behavior" second "Actual-Behavior".

![expected-behavior](https://cloud.githubusercontent.com/assets/7769932/24469423/68b3196c-1489-11e7-8908-2c42190fafc5.png)
![actual-behavior](https://cloud.githubusercontent.com/assets/7769932/24469429/6c375f9e-1489-11e7-8872-13c6cd4e28df.png)

**Comment by fabiangehring** [comment]
just came accross the same issue, when the labels changed the order

**Comment by jonmmease** [comment]
Going to close this here since this is something that would need to be discussed on the plotly.js side (https://github.com/plotly/plotly.js).  Feel free to open an issue there if you're still interested in discussing this!

**Comment by RainfallNZ** [comment]
It is possible to explicitly set the legend's traceorder attribute to 'normal' which stops the reversing of the trace order. See (https://github.com/plotly/plotly.js/issues/2192) .
In python I think this could be done with:
`fig.update_layout(legend_traceorder="normal")`

In R this could be done with:
`plot %>% layout(legend = list(traceorder = 'normal')`
