### ISSUE TITLE
ImportError: No module named 'plotly.graph_objs'; 'plotly' is not a package

### ISSUE THREAD

**Issue by turfaa** [plotly/plotly.py#723]
I use Python 3.5.2 and just installed plotly 2.0.6. Whenever I want to import plotly, this error is always present
```python
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/mnt/data/Documents/Coding/tucil3/plotly.py", line 2, in <module>
    from plotly.graph_objs import *
ImportError: No module named 'plotly.graph_objs'; 'plotly' is not a package
```

How to fix this? Thanks

--
edit : nevermind, I had a file named plotly.py

**Comment by kamrankausar** [comment]
ImportError                               Traceback (most recent call last)
<ipython-input-2-6361d2547ebc> in <module>()
----> 1 import plotly

ImportError: No module named plotly
