### ISSUE TITLE
offline mode does not display hoverinfo on ribbons in filled chord example

### ISSUE THREAD

**Issue by Kruptein** [plotly/plotly.py#724]
Hi, the filled chord example at https://plot.ly/python/filled-chord-diagram/ does not show the hoverinfo when changing the last line to pyplot.offline.plot(...) instead of pyplot.pyplot.plot(...).

The hoverinfo on the ideograms do appear however.

For ease of testing I created a snippet with all the code parts of the page: http://dpaste.com/3EDWAKS
(with small changes for py3 i.e. print() and list(zip()) instead of zip() but it also fails on py2 in offline mode)

plotly version: 1.12.9
OS tested: Win10 and Archlinux

**Comment by Kruptein** [comment]
I noticed my plotly version is still on 1.X because I installed it through conda.
The problem still exists in plotly 2.0.0 and plotly 2.0.6.

**Comment by jonmmease** [comment]
I'm not able reproduce this with version 3, it looks to me like the same hover info is appearing in offline mode now. Feel free to open a new issue against version 3 if you're still having trouble.
