### ISSUE TITLE
Using violin plots in multiplots and adding axis labels to violin plots

### ISSUE THREAD

**Issue by ebridge2** [plotly/plotly.py#725]
is it possible to have violin plots in a multiplot,, and to label the "y" axis? For example, consider the following example:

```
from plotly import offline as pyo
from plotly import tools
from plotly.tools import FigureFactory as ff
import pandas as pd

gr1_df = pd.DataFrame(dict(Score = [0.1, 0.15], Label=['group1', 'group1']))
gr2_df = pd.DataFrame(dict(Score = [2, 25], Label=['group2', 'group2']))
fig1 = ff.create_violin(gr1_df, data_header='Score', group_header='Label', title='Test')
fig2 = ff.create_violin(gr2_df, data_header='Score', group_header='Label', title='Test')
fig = tools.make_subplots(rows=2, cols=1)
fig.append_trace(fig1, 1, 1)
```
Which returned the error:
```
---------------------------------------------------------------------------
PlotlyDictKeyError                        Traceback (most recent call last)
<ipython-input-12-8aeda7755985> in <module>()
----> 1 fig.append_trace(fig1, 1, 1)

/home/eric/anaconda2/lib/python2.7/site-packages/plotly/graph_objs/graph_objs.pyc in append_trace(self, trace, row, col)
   1212                                 "cell got deleted."
   1213                                 .format(r=row, c=col))
-> 1214             trace['xaxis'] = ref[0]
   1215             trace['yaxis'] = ref[1]
   1216         self['data'] += [trace]

/home/eric/anaconda2/lib/python2.7/site-packages/plotly/graph_objs/graph_objs.pyc in __setitem__(self, key, value, _raise)
    426                 if _raise:
    427                     path = self._get_path() + (key, )
--> 428                     raise exceptions.PlotlyDictKeyError(self, path)
    429                 return
    430 

PlotlyDictKeyError: 'xaxis' is not allowed in 'figure'

Path To Error: ['xaxis']

Valid attributes for 'figure' at path [] under parents []:

    ['data', 'frames', 'layout']

Run `<figure-object>.help('attribute')` on any of the above.
'<figure-object>' is the object at []
```

Which makes sense since the violin figure object does not have an xaxis, but I could not think of anything else to try. Note that the "goal" behavior is a standard multiplot layout, where each figure has its own title and axes, but I could not find any other way to do this. 

I tried to correct this with an approach following the tutorials a bit more closely, but as you can see these still do not produce the desired behavior:
```
a = [0.1,  0.15, 2, 25]
b = ['group1', 'group1', 'group2', 'group2']
df = pd.DataFrame(dict(Score=a, Label=b))
fig = ff.create_violin(df, data_header='Score', group_header='Label', title='Test')
pyo.plot(fig, 'test')
```

![image](https://cloud.githubusercontent.com/assets/8883547/24741258/2c6b0c04-1a73-11e7-93ec-b81d64dc2fc0.png)

As you can see, this is not a very informative plot, first of all because there is only one plot (so only one title total), second there is no y axis label, and probably most significantly because the same axes are forced over the two plots (since they are totally different scales, this isn't desirable).

Is there a workaround to get the desired two behaviors (most importantly to have plots with different axes in some sort of subplot layout, and also to label the y axis)? Thanks!

Note: version wise, I am using plotly 1.12.1

**Comment by cldougl** [comment]
Hi there,
You can check out this tutorial: https://plot.ly/python/figure-factory-subplots/ for more information on how to create subplots with figure factory charts.
For future questions, we typically request users post support questions in our [support app](support.plot.ly) or [community forum](community.plot.ly) rather than via issues and reserve issues for bug reports.
