### ISSUE TITLE
`import plotly` creates (possibly) unnecessary credentials

### ISSUE THREAD

**Issue by twocs** [plotly/plotly.py#728]
I was investigating an issue with the plotly/MATLAB-Online API (https://github.com/imatlab/imatlab/issues/13) and found that the Python statement has an undesirable effect for offline plotly:
`import plotly`

Whenever this is encountered, and the files do not yet exist, the folder `~/.plotly` is created and then two files `~/.plotly/.credentials` and `~/.plotly/.config` are also created.

This is annoying if we want to run Plotly offline because these files are unnecessary. But it is also different than `plotly/MATLAB-Online`, which on Windows, does not even use `~/.plotly` as the plotly directory. On Windows, it uses `%APPDATA%\.plotly` instead.

**Comment by jonmmease** [comment]
Done in https://github.com/plotly/plotly.py/pull/1195. With this, the `~/.plotly` directory is not created until credentials are explicitly set.
