### ISSUE TITLE
ERROR: image.save_as - TypeError: the JSON object must be str, not 'bytes'

### ISSUE THREAD

**Issue by nileshmoodley** [plotly/plotly.py#736]
I am trying to use plotly's image servers to create a **static plot**. Here is some generic code that creates this error:

 ```python
import plotly
plotly.plotly.sign_in("myusername", "myapikey")
plotly.plotly.image.save_as(figure, filename=filename)
```
for some pre-defined `figure` and `filename`.

About 80% of the time, I have no issues and the image is generated. However, on occasion, the following error occurs:
```
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.5/site-packages/plotly/plotly/plotly.py", line 703, in get
    return_data = json.loads(res.content)
  File "/opt/anaconda3/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'

During handling of the above exception, another exception occurred: 
    
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.5/site-packages/plotly/plotly/plotly.py", line 787, in save_as
    img = cls.get(figure_or_data, format, width, height, scale)
  File "/opt/anaconda3/lib/python3.5/site-packages/plotly/plotly/plotly.py", line 707, in get
    raise exceptions.PlotlyError("The response "
plotly.exceptions.PlotlyError: The response from plotly could not be translated.
```
On closer inspection of the `res` object from the above traceback:
```
(Pdb) res.content
b'{"errors":[{"code":"UNKNOWN","message":"Unknown Image Server Error","path":null,"field":null}],"detail":"Unknown Image Server Error"}'
(Pdb) res.reason
'INTERNAL SERVER ERROR'
(Pdb) res.status_code      
500
(Pdb) res.url
'https://api.plot.ly/v2/images/'
```
Any assistance would be greatly appreciated, as I am unable to consistently generate this error.

#### Note:
I **do not** want to use the `offline.plot` method with the `image` parameter as outlined at the bottom of this page: [https://plot.ly/python/static-image-export](url), as this involves opening the generated `html` file in order to save the desired `png` file. 

My goal is to **programatically** generate `png` static images, with zero user intervention.

**Comment by jonmmease** [comment]
Closing since programmatic static image export is now supported in version 3.2 through the orca project  🎉   This is now the recommended approach to static image export from plotly.py.
