### ISSUE TITLE
Plot stream data with one update per hour

### ISSUE THREAD

**Issue by ohld** [plotly/plotly.py#742]
Hi everyone! 
I've read all documentation to the streaming methods but still don't know how to solve my problem.

I want to plot stream data with new values received only one per hour. 

My code looks like this:
``` python
import plotly.plotly as py
py.sign_in(username, api_key)
stream = py.Stream(stream_token)
while True:
    stream.open()
    new_value = get_my_value()
    date = datetime.datetime.now()
    stream.write({'x': date, 'y': new_value})
    stream.close()
    time.sleep(60 * 60)
```

If I use that code the plot become empty after about 10 minutes working time. What is happening ? 

See this question in Stackoverflow: http://stackoverflow.com/questions/43635933/stream-with-plotly-for-a-long-time

**Comment by Kully** [comment]
@ohld I don't think your `stream.open()` and `stream.close()` should be in the `while` loop. You want to open a connection (before entering while) and then you want the stream to close after exiting the `while True` loop, i.e. if the script stops running, etc.

**Comment by cldougl** [comment]
For future support questions please see https://support.plot.ly or https://community.plot.ly
