### ISSUE TITLE
Choose Your Own Order for violinPlots.

### ISSUE THREAD

**Issue by PynutCommander** [plotly/plotly.py#745]
i was facing an issue that violin plot categories was forced in alphabetical order, i suggest a small fix that can stop this problem. inside _violin.py we add an extra variable that is set to False, call it forced order. if the user set it to True then it will not sort the categories and will use the order that the user input his violin categories as explicitly. 
here is the function call with the added variable (forcedOrder):
http://imgur.com/s4rc4pz
here is the check that ignored the sort and uses the user order:
http://imgur.com/b7uGgps
Thank you.

**Comment by Kully** [comment]
Great idea. I'll make a PR to fix this problem. Thanks.

**Comment by Kully** [comment]
Closing as issue is solved.

**Comment by Kully** [comment]
CHANGELOG Update: https://github.com/plotly/plotly.py/blob/master/CHANGELOG.md#added
