### ISSUE TITLE
Heatmap gap size inconsistency

### ISSUE THREAD

**Issue by TiemenSch** [plotly/plotly.py#746]
I'm currently working on a project using the Heatmap function of plotly. To get a more readable picture, I tried using the xgap and ygap kwargs. However, when increasing the gap size, I noticed that the gaps of the rows and columns on the edges of the plot are not handled correctly. It looks like it puts too much "gap" on the inside of these and repositioning is off. 

A sample picture: 
![hm_gapsize](https://cloud.githubusercontent.com/assets/7141863/25612377/c1998dca-2f2a-11e7-93c5-cd13e939d66d.png)

```Python
# Create dummy data
dat = np.mat(np.full((11,11), 0, dtype=int))
dat[0, range(1,11)] = 1
dat[1, [2,3,4,5]] = 1
dat[2, 3] = 1
dat[4, 5] = 1
dat[6, [7, 8, 9, 10]] = 1
dat[7, [8, 9, 10]] = 1
dat[9, 10] = 1
for i in range(11):
    for j in range(11):
        if j > i:
            dat[j, i] = dat[i, j]

# Plot heatmap
figsize = 700
dim = dat.shape[0]
gap = 0.8 * figsize / dim
hm = go.Heatmap(z=dat, xgap=gap, ygap=gap)
layout = dict(width=figsize, height=figsize, autosize=False)
figure = go.Figure(data=[hm], layout=layout)
py.iplot(figure, image_width=figsize, image_height=figsize, filename='hm_gapsize', image='png')
```

**Comment by TiemenSch** [comment]
I just checked whether removing the pre-set figure sizing (thus opting for defaults) would solve anything, but it doesn't. The bug prevails.

**Comment by jonmmease** [comment]
Just tried this out on plotly.py 3.2.1 and I don't see this issue anymore.

```python
import numpy as np
import plotly.graph_objs as go
from plotly.offline import iplot, init_notebook_mode
init_notebook_mode()

# Create dummy data
dat = np.mat(np.full((11,11), 0, dtype=int))
dat[0, range(1,11)] = 1
dat[1, [2,3,4,5]] = 1
dat[2, 3] = 1
dat[4, 5] = 1
dat[6, [7, 8, 9, 10]] = 1
dat[7, [8, 9, 10]] = 1
dat[9, 10] = 1
for i in range(11):
    for j in range(11):
        if j > i:
            dat[j, i] = dat[i, j]

# Plot heatmap
figsize = 700
dim = dat.shape[0]
gap = 0.5 * figsize / dim
hm = go.Heatmap(z=dat, xgap=gap, ygap=gap)
layout = dict(width=figsize, height=figsize, autosize=False)
figure = go.Figure(data=[hm], layout=layout)
iplot(figure)
```
![newplot 1](https://user-images.githubusercontent.com/15064365/45918810-64117580-be5a-11e8-941d-7b0666de06db.png)
