### ISSUE TITLE
Plotly offline could work without `init_notebook_mode`

### ISSUE THREAD

**Issue by rgbkrk** [plotly/plotly.py#748]
For frontends that support the plotly json mimetype, they don't need `init_notebook_mode` to run. They could just use:

```
import plotly
from plotly.graph_objs import Scatter, Layout
data = [Scatter(x=[1, 2, 3, 4], y=[4, 3, 2, 1])]
layout = Layout(title="hello world"); z = {"data": data, "layout": layout}

plotly.offline.iplot(z)
```

If they're taking precedence on the plotly JSON mimetype over HTML (as is done in nteract).

**Comment by jonmmease** [comment]
I think this has been true for quite some time. At least I know that it's possible in JupyterLab. Feel free to reopen if this isn't the case for nteract!

**Comment by rgbkrk** [comment]
We're working on the widgets + plotly support @jonmmease!

I'll double check with the latest release, in case the media type (mimetype) plotly stuff isn't there.

cc @jdfreder

**Comment by jonmmease** [comment]
plotly+widgets support in nteract sounds awesome!  I'll reopen until you have a chance to double check that nteract has what it needs in the display bundle from `iplot` when `init_notebook_mode` isn't called.

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
