### ISSUE TITLE
plotly not compatible with nbviewer/nbconvert, slide view

### ISSUE THREAD

**Issue by tarokiritani** [plotly/plotly.py#750]
My plot is rendered nicely when my jupyter notebook is seen with nbviewer as a notebook. However, in the slide mode, the image is very narrow.

Here is [my plot viewed in a slide.](https://nbviewer.jupyter.org/format/slides/github/tarokiritani/testjupyter/blob/master/test%20plotly.ipynb#/)

This looks better when [viewed as a notebook.](https://nbviewer.jupyter.org/github/tarokiritani/testjupyter/blob/master/test%20plotly.ipynb?flush_cash=true)

Is this a problem of plotly or nbconvert? What can I do about this for now?

**Comment by empet** [comment]
@tarokiritani  Insert in the dict `layout` the following keys-values:

    autosize=False,
    width=600,
    height=600

and convert again with:

    jupyter-nbconvert --to slides test-plotly.ipynb --reveal-prefix=reveal.js --post serve

**Comment by tarokiritani** [comment]
Thanks a lot. I now can see the entire figure.

**Comment by Juanlu001** [comment]
Same issue as https://github.com/plotly/plotly.py/issues/750.
