### ISSUE TITLE
Static Image Export in plotly.js does not work for polar charts

### ISSUE THREAD

**Issue by dugagjinll** [plotly/plotly.py#751]
Hi,

The code here 

```
var d3 = Plotly.d3;
var img_jpg= d3.select('#jpg-export');
// Ploting the Graph
var trace={x:[3,9,8,10,4,6,5],y:[5,7,6,7,8,9,8],type:"scatter"};
var trace1={x:[3,4,1,6,8,9,5],y:[4,2,5,2,1,7,3],type:"scatter"};
var data = [trace,trace1];
var layout = {title : "Simple Javascript Graph"};
Plotly.plot(
  'plotly_div',
   data,
   layout)
// static image in jpg format
.then(
    function(gd)
     {
      Plotly.toImage(gd,{height:300,width:300})
         .then(
            function(url)
         {
             img_jpg.attr("src", url);
             return Plotly.toImage(gd,{format:'jpeg',height:400,width:400});
         }
         )
    });
```

is from [Export Javascript plots as jpeg, png,...](https://plot.ly/javascript/static-image-export/) and it works for line charts. 
But if I replace the **x** with **t** and **y** with **r** (at the trace variables) to make it a polar chart:

```
var d3 = Plotly.d3;
var img_jpg= d3.select('#jpg-export');
// Ploting the Graph
var trace={t:[3,9,8,10,4,6,5],r:[5,7,6,7,8,9,8],type:"scatter"};
var trace1={t:[3,4,1,6,8,9,5],r:[4,2,5,2,1,7,3],type:"scatter"};
var data = [trace,trace1];
var layout = {title : "Simple Javascript Graph"};
Plotly.plot(
  'plotly_div',
   data,
   layout)
// static image in jpg format
.then(
    function(gd)
     {
      Plotly.toImage(gd,{height:300,width:300})
         .then(
            function(url)
         {
             img_jpg.attr("src", url);
             return Plotly.toImage(gd,{format:'jpeg',height:400,width:400});
         }
         )
    });
```

 then I don't get the exported image but I get the following error:

> plotly-latest.min.js:66 Uncaught (in promise) TypeError: Cannot read property 'framework' of undefined
    at e.exports (plotly-latest.min.js:66)
    at plotly-latest.min.js:58
    at Promise (<anonymous>)
    at Object.n [as toImage] (plotly-latest.min.js:58)

**Comment by cldougl** [comment]
Hey @dugagjinll looks like you may have found an issue with the plotly.js repo. Would you mind logging it in the plotly.js repo: https://github.com/plotly/plotly.js/issues ?
This repo is for Plotly's python wrapper.

**Comment by dugagjinll** [comment]
My bad I must have been tired that day. I will log the issue in the correct repo this time. 👍

**Comment by cldougl** [comment]
Thank you!
