### ISSUE TITLE
Weird contour behaviour

### ISSUE THREAD

**Issue by MatteoGnudi** [plotly/plotly.py#752]
Hello everybody, I'm kinda new to Plotly, and I'm worried I might be doing something wrong.

Sometimes, contours don't quite match up with the values they're built from. It makes no difference if I use figure_factory.create_2d_density or manually create the Scatter and Histogram2dcontour traces.

An example:
https://pastebin.com/86jM84EG
![2ddensity](https://cloud.githubusercontent.com/assets/22742823/26005474/6c39a088-3739-11e7-84b3-e1c497fe9933.png)

Thanks in advance.

**Comment by cldougl** [comment]
Hey @MatteoGnudi -- we request that you only post issues in this repo if you have a bug that we can replicate, otherwise we use this forum: https://community.plot.ly/ for support and questions. If you have more information on how your result is incorrect please post here. Thanks!

**Comment by MatteoGnudi** [comment]
Hello @cldougl, the code to replicate this is in the pastebin link before the image. I was expecting the contours to be centered on the points (the leftmost contour doesn't even _include_ the corresponding point); if you mean that the misalignment is _not_ a bug, then please close this issue, with my apologies.

**Comment by cldougl** [comment]
@MatteoGnudi thanks, as far as I can tell all of our examples are getting drawn correctly. If you have a simple example that shows that drawing is incorrect please reopen the issue!
