### ISSUE TITLE
Faulty shapes when axis type set to 'category'

### ISSUE THREAD

**Issue by cmuzeau** [plotly/plotly.py#759]
Shapes seem buggy when displayed on a time series plot with axis type set to `'category'` while it is working as expected when set to `'auto'` (date index).  

If you zoom on the shape, you will clearly see that it is not what you intended to plot: it draws a rectangle instead of a vertical line in the case below. I have encountered that problem with different index format (datetime, integer, string) displayed as `'category'`

```python
import pandas as pd
import plotly.graph_objs as go
from plotly.offline import iplot, init_notebook_mode
from datetime import datetime

df = pd.read_csv("https://raw.githubusercontent.com/plotly/datasets/master/finance-charts-apple.csv")

data = [
    go.Scatter(
          x=df.Date,
          y=df['AAPL.Close']
    )
]

layout = go.Layout(
    xaxis=dict(
        type='category', # change this option to _auto_ for a correct shape
    ),
    shapes=[
        dict(
            x0=datetime(2015, 11, 5),
            y0=min(df['AAPL.Close']),
            x1=datetime(2015, 11, 5), # x1 = x0 for a vertical line
            y1=max(df['AAPL.Close'])
        )
    ]
)
fig = go.Figure(data=data, layout=layout)
iplot(fig)
```
Ouput:
![screenshot from 2017-05-23 11-54-51](https://cloud.githubusercontent.com/assets/28804635/26348956/aeb81eb2-3fae-11e7-9ebc-ff1eb50866cd.png)

Zoom on the vertical line:
![screenshot from 2017-05-23 11-51-03](https://cloud.githubusercontent.com/assets/28804635/26348984/c2144bb6-3fae-11e7-8e78-b84c282a9467.png)

**Comment by cldougl** [comment]
Hi there,
Thanks for reporting this issue! It's actually in our underlying javascript library so I've opened an issue in that repo. I will close this issue in favour of: https://github.com/plotly/plotly.js/issues/1720, once that's resolved, you will no longer see the problem with our python api.

**Comment by sb0007** [comment]
is this yet to be fixed?
