### ISSUE TITLE
subplot cannot plot Bar properly when there are integer-like bar name

### ISSUE THREAD

**Issue by heyu91** [plotly/plotly.py#761]
Hello, I am using plotly-2.0.8 in jupyter. 
I try to append trace to a subplot one by one, but I notice if there is integer-like bar name, plotly will convert the string to the integer, which makes plotly cannot work correctly. 

```
import plotly .offline as po
import plotly.graph_objs as go
import plotly.tools as tls

fig = tls.make_subplots(
            rows=1, cols=1,
            print_grid=False,
        )

fig.append_trace(go.Bar(x=['123'],
               y=[1],
               marker={'color':'red'}
              ),
              1, 1)
fig.append_trace(go.Bar(x=['abc'], 
               y=[2],
               marker={'color':'green'}
              ),
              1, 1)

po.iplot(fig)
```

Please advise on how I can fix this. Thanks.

**Comment by cldougl** [comment]
Hi there,
You can set the axis type to category:
![screen shot 2017-05-26 at 4 18 39 pm](https://cloud.githubusercontent.com/assets/2789078/26511230/1e6f5ee6-422f-11e7-831b-a65771001fe4.png)

Please note issues in this repo are reserved for bug reports, in the future, please direct support queries to our support site: https://support.plot.ly
