### ISSUE TITLE
Plotly offline not allowing to save the plot as image without opening the plot in webpage.

### ISSUE THREAD

**Issue by saukol** [plotly/plotly.py#763]
I am trying to save the plot created by plotly.offline as an image instead of html file without opening the plot in a web browser. But this is not working.

**Comment by cldougl** [comment]
@saukol this is not possible using `offline.plot()` and not on the roadmap. To save the image of the plot you must generate the plot.

**Comment by Midnighter** [comment]
That's really a shame. Not being able to programmatically generate figures and save them to file really kills the use of plotly for me.
