### ISSUE TITLE
Plotly AWS LAMBDA permission to home directory error

### ISSUE THREAD

**Issue by adlerlinhares** [plotly/plotly.py#770]
Hello,
im facing some trouble trying to make a plot via aws lambda.
the code wroks fine in my pc, but when i upload to lambda a get this message error:

> /var/task/plotly/tools.py:88: UserWarning:

> Looks` like you don't have 'read-write' permission to your 'home' ('~') directory or to our '~/.plotly' directory. That means plotly's python api can't setup local configuration files. No problem though! You'll just have to sign-in using 'plotly.plotly.sign_in()'. For help with that: 'help(plotly.plotly.sign_in)'.`

> `You` don't have proper file permissions to run this function.: PlotlyError
> Traceback (most recent call last):
> File "/var/task/morizonofplot.py", line 99, in lambda_handler
> tls.set_credentials_file(username='xxx', api_key='xxxxxx') #___plotly tools
> File "/var/task/plotly/tools.py", line 104, in set_credentials_file
> raise exceptions.PlotlyError("You don't have proper file permissions "
> PlotlyError: You don't have proper file permissions to run this function.
> 

```

How can i solve it?

**Comment by cldougl** [comment]
Hi there,
As mentioned in the error message it looks like you don't have read/write permissions in your directory so you cannot create the `.plotly/.credentials` file that is created with the `tls.set_credentials_file()` function. Instead you can sign in with `plotly.plotly.sign_in()` or change the permissions of your directory. Please run `help(plotly.plotly.sign_in)` for more information on the sign-in function.

**Comment by adlerlinhares** [comment]
yeah, i tried to do what you said before but i get this error:
```
[Errno 2] No such file or directory: SSLError
Traceback (most recent call last):
File "/var/task/morizonofplot.py", line 113, in lambda_handler
opexind.plot_scatter2(y1,y2,x1,'rgb(242,28,4)','rgb(41,213,247)','None','None', yn1, yn2, nome, gx, gy,indicador)
File "/var/task/module/opexind.py", line 196, in plot_scatter2
py.plot(fig, filename = path, auto_open=False)
File "/var/task/plotly/plotly/plotly.py", line 188, in plot
res = _send_to_plotly(figure, **plot_options)
File "/var/task/plotly/plotly/plotly.py", line 666, in _send_to_plotly
r = requests.post(url, data=payload)
File "/var/task/requests/api.py", line 94, in post
return request('post', url, data=data, json=json, **kwargs)
File "/var/task/requests/api.py", line 49, in request
return session.request(method=method, url=url, **kwargs)
File "/var/task/requests/sessions.py", line 457, in request
resp = self.send(prep, **send_kwargs)
File "/var/task/requests/sessions.py", line 569, in send
r = adapter.send(request, **kwargs)
File "/var/task/requests/adapters.py", line 420, in send
raise SSLError(e, request=request)
SSLError: [Errno 2] No such file or directory

```
