### ISSUE TITLE
Please try again in 30 seconds

### ISSUE THREAD

**Issue by sohamnavadiya** [plotly/plotly.py#780]
I am running one python script using Jenkins. It is working fine. Today, I got two failure with below error Traceback. the third time it was succeeded. I am creating this ticket so your team can understand the route cause of it.

```
Traceback (most recent call last):
  File "/home/ubuntu/rest_api/scripts/daily_analysis_report.py", line 132, in <module>
    main()
  File "/home/ubuntu/rest_api/scripts/daily_analysis_report.py", line 111, in main
    subplot_chart = pcharts.analytics_subplot_line(past_days_metrics, plot_titles, subplot_title)
  File "/home/ubuntu/rest_api/scripts/plotly_charts/charts.py", line 132, in analytics_subplot_line
    py.image.save_as(fig, filename=file_path)
  File "/home/ubuntu/rest_api/venv/local/lib/python2.7/site-packages/plotly/plotly/plotly.py", line 787, in save_as
    img = cls.get(figure_or_data, format, width, height, scale)
  File "/home/ubuntu/rest_api/venv/local/lib/python2.7/site-packages/plotly/plotly/plotly.py", line 710, in get
    raise exceptions.PlotlyError(return_data['error'])
plotly.exceptions.PlotlyError:
<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>502 Server Error</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Server Error</h1>
<h2>The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.</h2>
<h2></h2>
</body></html>

Build step 'Execute shell' marked build as failure
```

I am using **plotly** version **1.12.9**

**Comment by sohamnavadiya** [comment]
@cldougl Thaks for the reply. With same version(1.12.9), Today I didn't get any error. Anyway, I will let you know If I will get the same again.

**Comment by cldougl** [comment]
@sohamnavadiya great- please let us know if you do receive errors again with our updated version and we will look into our server load again! Thanks for reporting.

**Comment by joltex** [comment]
@cldougl I'm receiving this same error today when trying to save a PNG using version 2.0.12. It sometimes works after many tries.

**Comment by WarwickDS** [comment]
Any guidance here? I receive this error often. I am using the latest version 2.0.12. Eventually, it will work but I can't practically use plotly if I am always waiting to see if I receive server error. 

error:

Error: Server Error
The server encountered a temporary error and could not complete your request.<p>Please try again in 30 seconds.

**Comment by cldougl** [comment]
We've recently added additional image servers to try and reduce these intermittent errors.

**Comment by meyer-anders** [comment]
Happening regularly to me :(

**Comment by cldougl** [comment]
Hey @meyer-anders, could you let me know what version of the API you're using?

**Comment by meyer-anders** [comment]
2.0.14. I’m trying to run the project that’s in my repo (‘CPD_QC’). 12_box_panels.py works some of the time. 16_plot_num_runs hasn’t gone through a single time though the offline version works fine.

Forgive the coding amateurism. I’m an MD, not a computer scientist!

Thanks!
Anders

**Comment by cldougl** [comment]
@meyer-anders you may want to check if the chart is generated (`plot()`) correctly. If the graph is generated correctly but you're still having a hard time getting the image you can send us a reproducible example.

**Comment by FedericoFontana** [comment]
I've been using plotly (now '2.0.15') for the past couple of months (free account) to save charts locally as an image and I always had to deal with the "Please try again in 30 seconds" error message.

@cldougl I'm not able to reproduce the problem as it appears to be not deterministic. In my case, my Python code is supposed to generate and save locally a sequence of 10 images as .png. Every time that I run the code, only a subset of the 10 images are generated, so I need to run the code several times until when all .png are generated.

Is there any chance that the problem is due to the quick sequence of API calls?

**Comment by rsgoldfarb** [comment]
I have this same issue.  I have code that works perfectly fine...SOMETIMES.  About 2 out of 5 runs fails with the error message: "The server encountered a temporary error and could not complete your request.  Please try again in 30 seconds."

I have a paid account.  Is this just a common issue with Plotly?  Are there any known causes - can it be avoided somehow?  My code is attempting to create multiple plotly graphs so it is very difficult to just run it multiple times.  Each time I try, it seems to fail somewhere within the code, but always with the "Please try again in 30 seconds" message.

**Comment by FedericoFontana** [comment]
I'm using plotly to generate offline charts that are sent out within a report. This serious problem has lead to have people complaining about missing updates in the charts. A sequence of try-catch statements as proposed by @rsgoldfarb might work in the short term, but it doesn't seem to be a long term solution as this approach is not guaranteed to return all charts. @cldougl, would you be able to provide an update?

**Comment by cldougl** [comment]
Hi @FedericoFontana,
You should not be receiving a server error if you're generating offline charts (no server is used when using our offline methods). 
This error is related to high activity on our image server (unfortunately this issue is not related to our python API). If you're exporting many images in a loop, we suggest using a try-catch block. We'll likely update our image exporting methods in the future, but I do not have a solid timeline estimation at this time.
