### ISSUE TITLE
multiprocessing and offline mode results in pickle error.

### ISSUE THREAD

**Issue by dsmale** [plotly/plotly.py#786]
Simply setting plotly.offline.init_notebook_mode(connected=True) results in a cPickle.PicklingError.
<pre>
<IPython.core.display.HTML object>
Traceback (most recent call last):
  File "meh.py", line 13, in <module>
    results = pool.map(do_something, ["foo", "bar"])
  File "/usr/local/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/usr/local/lib/python2.7/multiprocessing/pool.py", line 567, in get
    raise self._value
cPickle.PicklingError: Can't pickle <type 'function'>: attribute lookup __builtin__.function failed
</pre>

Example code:
<pre>
import multiprocessing as mp
import plotly

plotly.offline.init_notebook_mode(connected=True)

def do_something(s):
  return s

if __name__ == "__main__":
   pool_size = mp.cpu_count()
   pool = mp.Pool(processes=pool_size)
   results = pool.map(do_something, ["foo", "bar"])
   pool.close()
   pool.join()
   print results

</pre>

**Comment by jonmmease** [comment]
Closed by https://github.com/plotly/plotly.py/pull/1191 with the implementation of pickle support.
