### ISSUE TITLE
Span Tables across updatemenus and legends

### ISSUE THREAD

**Issue by NicoHood** [plotly/plotly.py#790]
I have got a Pie charts with a table below. The updatemenu and the legend take a lot of space, which is fine for the pie chart itself. However the table also gets aligned to this offset. How can I remove it? If this is possible, it would be nice to add it to the examples:
https://plot.ly/python/table/

In the following picture you can see a separate Table (how it should look like) and a Pie chart combined with a table. I want to have it like the first table across the whole page, but within a single chart.

![screenshot_2017-07-05_19-11-33](https://user-images.githubusercontent.com/6888294/27876086-fd19a30e-61b5-11e7-9ee6-06a8852cf241.png)

**Comment by cldougl** [comment]
Hi @NicoHood ,
We request that users post questions in our community forum: https://community.plot.ly/ or support app: https://support.plot.ly/ and reserve this channel for bug reports as we do not offer support via github issues.

**Comment by NicoHood** [comment]
@cldougl I totally understand. However you should change the contribution guidelines. To me this sounds that you are free to also ask questions here:
https://github.com/plotly/plotly.py/blob/master/contributing.md#got-questions

So is this feature possible? Because if not you can keep it open as feature request.

**Comment by cldougl** [comment]
great point- hopefully the [contributing guide](https://github.com/plotly/plotly.py/blob/master/contributing.md#contributing) is more clear now. yep - this feature is possible.
