### ISSUE TITLE
Setting cumulative in go.Histogram doesn't seem to do anything

### ISSUE THREAD

**Issue by claresloggett** [plotly/plotly.py#792]
Creating a histogram with the cumulative flag set seems to produce a non-cumulative histogram.

Based on the reference documentation, I'm setting the flag like so:

```hist = go.Histogram(my_data, cumulative=dict(enabled=True))```

then attempting to plot with `iplot`. It produces a plot, but it is the same plot it would produce if I had not included the `cumulative` parameter (or if I had set `enabled` to `False`). 

This is with version 2.0.6.

**Comment by cldougl** [comment]
Hi there,
We have an example here: https://plot.ly/python/histograms/#cumulative-histogram
Please note that if you're plotting offline you'll have to use a more recent version of the package to get an updated version of plotly.js that include the cumulative attribute (https://github.com/plotly/plotly.py/blob/master/CHANGELOG.md#updated-4)

**Comment by claresloggett** [comment]
@cldougl thanks for your help! I've upgraded to 2.0.12 and that has fixed the issue.
