### ISSUE TITLE
"base" not working as expected in plotly.offline

### ISSUE THREAD

**Issue by jprockbelly** [plotly/plotly.py#794]
The attribute `base` seems to be ignored in `plotly.offline` for a simple bar chart. Example:

```
import plotly.offline as py
import plotly.graph_objs as go

data = [go.Bar(
            x=['x'],
            y=[4],
            base=[2],
    )]

py.iplot(go.Figure(data=data))
```

This produces a bar from 0 to 4, not from 2 to 6 as expected. This issue doesn't appear when using `plotly.ploty` (as far as I can see).

related stackoverflow question:
https://stackoverflow.com/questions/45093563/python-plotly-bar-graph-using-y0-and-dy-offset

**Comment by cldougl** [comment]
Hi there,
Can you please confirm that you're using an upgraded version of Plotly?
With version 2.0.12 you should not see the above issue:
https://plot.ly/~chelsea_lyn/14916

**Comment by jprockbelly** [comment]
hey @cldougl 

Sorry for the late reply.

You are right I was on 2.0.9 still. Upgrading got me half way there. I can confirm that using 2.0.12 fixes this issue when writing to file. i.e. like this:

`py.plot(go.Figure(data=data), filename='test.html')`

But it still doesn't fix it when looking at the plot in a notebook, as per my above example:

`py.iplot(go.Figure(data=data))`

**Comment by cldougl** [comment]
Thanks for the additional information, can you let me know if you're getting an error in the notebook? My above example is in a jupyter notebook. Please note you may have to clear the cache of your notebook after switching/upgrading versions.

**Comment by jprockbelly** [comment]
>clear cache

Good one. All working in jupyter notebook now as well, thanks for the help.
