### ISSUE TITLE
df3.iplot(kind='surface') gives me a three diminsional uncolored graph

### ISSUE THREAD

**Issue by TareqAlshargabi** [plotly/plotly.py#797]
Hi,

The command above in the title gives me a white graph.

I followed all the steps for installation and ran all commands for notebook and for offline use (please see below for commands I used and the output graph). Not sure why the graph is not colored. Could you please help?

where df3 is a dataframe.

![2017-07-20_16-29-54-f128bed31aeb9437a109380693990204](https://user-images.githubusercontent.com/30349651/28479403-4529566e-6e2a-11e7-8fa5-d33a77bfd70f.png)
![2017-07-20_16-27-54-d52058270b48e80117ca7637a0002bd7](https://user-images.githubusercontent.com/30349651/28479408-49fa1066-6e2a-11e7-93d8-b8b73153000c.png)

Many thanks,

**Comment by cldougl** [comment]
Hi there, 
If you're using cufflinks you can create an issue in the cufflinks repo: https://github.com/santosjorge/cufflinks/issues. Otherwise you can find documentation for creating a surface chart with plotly's python api here: https://plot.ly/python/3d-surface-plots/
