### ISSUE TITLE
autorange='reversed' in scatter3d

### ISSUE THREAD

**Issue by lperozzi** [plotly/plotly.py#803]
Hi,

it seems that the option `autorange='reversed'` is not working with scatter 3D. Is there another solution to invert the `zaxis`?

**Comment by cldougl** [comment]
Hi there,
Reversed axes are not supported for 3D (https://community.plot.ly/t/reverse-z-axis-values/1817/2) in our core [plotly.js library](https://github.com/plotly/plotly.js/).

**Comment by lperozzi** [comment]
Ok, got it. The solution (for now), to plot X,Y,Z geospatial data in scatter 3D, with the depth assigned to the `zaxis` and having a depth (Z) increasing from the top of the plot is to make your Z values  negative (e.g, `df['Depth'] = -df['Depth']`)

**Comment by jonmmease** [comment]
Going to close this here since `'reversed'` autorange support would need to be implemented in Plotly.js first (https://github.com/plotly/plotly.js).  Feel free to search the issues there and open a new one if this use case isn't covered yet. Thanks!

**Comment by VelizarVESSELINOV** [comment]
Your colleagues from plotly.js are now managing correctly reversed axis in 3D space https://github.com/plotly/plotly.js/issues/1940. @jonmmease do you need to reopen the issue or we need to create a new issue or automatically plotly.py will benefit from this new functionality?

**Comment by jonmmease** [comment]
Hi @VelizarVESSELINOV, plotly.py will get it automatically (our code generation process automatically picks up new properties like this). Looks like this will make it into plotly.py 3.4.0.

**Comment by WenyinWei** [comment]
Hello guys, to be honest, I also met the problem that the "reversed" setup doesn't work. But my plotly.py is 4.5.2 and it still doesn't work. Would you mind having a check whether the functionality is added and really works?

**Comment by tpeet** [comment]
@WenyinWei , did you modify `layout.zaxis.autorange` or `layout.scene.zaxis.autorange`? Latter should be used for 3D plots. You could try this:

`fig.update_scenes(zaxis_autorange="reversed")`

https://stackoverflow.com/questions/58532088/how-to-switch-direction-of-axis-in-3d-scatterplot-plotly/62672879#62672879
