### ISSUE TITLE
No hover info for thin bars

### ISSUE THREAD

**Issue by karanchaudhri** [plotly/plotly.py#809]
When hovering over thin horizontal bars (Timeline graph scenario), No hover info is displayed.

**Comment by cldougl** [comment]
Hi there,
Do you have a reproducible example? Thanks!

**Comment by karanchaudhri** [comment]
I can attach images confirming the bug.
<img width="486" alt="screen shot 2017-08-02 at 12 33 57 pm" src="https://user-images.githubusercontent.com/7090475/28884452-e937b094-777f-11e7-8496-289e73487acf.png">
The above image has thick as well as thin bars (blue ones). No hover info is displayed for thin bars no matter how close my mouse pointer is to bars.

I have to zoom in enough times to make it appear as shown below - 
<img width="744" alt="screen shot 2017-08-02 at 12 35 23 pm" src="https://user-images.githubusercontent.com/7090475/28884513-28d34132-7780-11e7-809d-2b788d938a7d.png">

Let me know if you need more details

**Comment by cldougl** [comment]
@karanchaudhri yep we'd need some code or a link to an example so we can reproduce the problem
thanks!

**Comment by cldougl** [comment]
Hi there,
It looks like this is an issue with the underlying plotly.js library. You can comment or follow along here: https://github.com/plotly/plotly.js/issues/1093 for updates on a fix.
