### ISSUE TITLE
Bar graph x categories automatically change strings -> numbers

### ISSUE THREAD

**Issue by heath730** [plotly/plotly.py#812]
If a single category on the x axis (I am passing strings) can be converted into a number, then the x axis of the bar graph is re-scaled to be numeric.  This came up in a situation where my x axis contained the first 6 characters of a commit SHA, and when the first 6 digits for a single commit were all digits, the behavior below was observed.

For example, this snippet:
```python
from plotly.offline import download_plotlyjs, init_notebook_mode, plot 
import plotly.graph_objs as go

data = [go.Bar(
            x=['1238ad', '123456', 'a1234b'],
            y=[20, 14, 23]
    )]

plot(data, filename='basic-bar')

```
Produces: 
![capture](https://user-images.githubusercontent.com/5819478/29004612-493b25be-7a98-11e7-82c5-8e7ac800d009.PNG)

While switching the middle x category from `123456` to `12345b` produces:
![capture2](https://user-images.githubusercontent.com/5819478/29004618-7240a506-7a98-11e7-826b-348b3ddfde5d.PNG)

Versions: 
Python - `3.4.2`
Plotly - `2.0.13`

I could add a check whether all of the x categories can be converted into to an int/float without raising a value error before switching the axis. I would be glad to contribute a PR if given some advice on how to best implement it.

**Comment by cldougl** [comment]
Hi there,
In this situation we recommend setting the axis type to category:
`layout = go.Layout(xaxis=dict(type='category'))`
See example here: https://plot.ly/~chelsea_lyn/15214
