### ISSUE TITLE
Mix of Scatter and Scattergl in subplots duplicates axes titles

### ISSUE THREAD

**Issue by arisolt** [plotly/plotly.py#813]
Replacing `go.Scatter` with `go.Scattergl` for `trace1` produces duplicate axes titles in this example:

https://plot.ly/python/subplots/#customizing-subplot-axes

Note that the issue is not present if all traces are changed to `go.Scattergl`.

**Comment by jackparmer** [comment]
`scatter` (SVG) and `scattergl` (WebGL) trace types are not meant to be mixed in subplots at the moment. If this is a necessary use case, one suggestion is to combine the 2 plots side-by-side in a dashboard: https://plot.ly/dashboard/create/

**Comment by arisolt** [comment]
This happens for other SVG trace types too. For example histograms, needed for building density plots (https://plot.ly/python/density-plots/). Thanks for the suggestion.

**Comment by jonmmease** [comment]
`scattergl` and `scatter` traces types are now able to share the same axes.
