### ISSUE TITLE
Shapes object missing in graph_objs

### ISSUE THREAD

**Issue by lucainnocenti** [plotly/plotly.py#817]
Is there any reason why no `Shapes`/`Shape` class is defined in [graph_objs](https://github.com/plotly/plotly.py/blob/master/plotly/graph_objs/graph_objs.py)?
Compare this to for example the existing classes `Annotations`/`Annotation`.

**Comment by jonmmease** [comment]
This class is available in version 3 as `plotly.graph_objs.layout.Shape`
