### ISSUE TITLE
Wrong value shown on hover for small numbers

### ISSUE THREAD

**Issue by lucainnocenti** [plotly/plotly.py#823]
To reproduce, just do:

```
import plotly.offline
import plotly.graph_ojbs as go
import numpy as np
plotly.offline.iplot([go.Scatter(
    y=np.exp(-np.arange(100))
)])
```

Clicking again on the "Compare data on hover" button fixes it, as shown here:
 
![gyrodown](https://user-images.githubusercontent.com/10957113/29568170-67a55f7c-8747-11e7-891d-2b70596aa224.gif)

**Comment by empet** [comment]
To prevent such a behaviour set  in `layout['yaxis']`, eventually in `layout['xaxis']` too,  hoverformat='.7f' .

**Comment by jonmmease** [comment]
Thanks for the GIF, it looks like there was a bug in that the suffix was not being displayed.  Here's the current behavior, which is the intended behavior:

![smallhover](https://user-images.githubusercontent.com/15064365/45919626-5104a280-be66-11e8-9e07-8eb9ce036186.gif)

Note how the SI suffix is appended as the value gets closer and closer to 0.

As @empet mentioned, this can be customized using the `hoverformat` property.
