### ISSUE TITLE
Cannot import name utils 

### ISSUE THREAD

**Issue by ejyoung82** [plotly/plotly.py#825]
I've just installed plotly this morning and even when trying an example like the simple table [here](https://plot.ly/python/table/#new-to-plotly) I get the following ImportError:

import plotly.plotly as py
import plotly.figure_factory as ff

data_matrix = [['Country', 'Year', 'Population'],
               ['United States', 2000, 282200000],
               ['Canada', 2000, 27790000],
               ['United States', 2005, 295500000],
               ['Canada', 2005, 32310000],
               ['United States', 2010, 309000000],
               ['Canada', 2010, 34000000]]

table = ff.create_table(data_matrix)
py.iplot(table, filename='simple_table')
Traceback (most recent call last):

  File "<ipython-input-12-07ea71730d5c>", line 2, in <module>
    import plotly.figure_factory as ff

  File "C:\Users\ejyoung\AppData\Local\Continuum\Anaconda2\lib\site-packages\plotly\figure_factory\__init__.py", line 10, in <module>
    from plotly.figure_factory._distplot import create_distplot

  File "C:\Users\ejyoung\AppData\Local\Continuum\Anaconda2\lib\site-packages\plotly\figure_factory\_distplot.py", line 4, in <module>
    from plotly.figure_factory import utils

**ImportError: cannot import name utils**

I've been looking for solutions but have not found anything.  I have plotly 2.0.15 (also ran --upgrade to update dependencies) and python 2.7.13

Any ideas?

**Comment by Kully** [comment]
Hello @ejyoung82 ,

Can you re-upgrade Plotly to the newest version and tell me if you are still experiencing this bug? We are on version 2.2.1. now. Thanks.

fyi `pip install --upgrade plotly`

**Comment by apal90** [comment]
@Kully  I can testify that this bug still exists. It seems to be a problem with figure factory. I have tried the following two methods of importing FF, and they both give different errors:

import plotly.figure_factory as ff
from plotly.tools import FigureFactory as FF

**Comment by jonmmease** [comment]
As of version 3.2.1, neither of these imports raise import errors for me.

```python
import plotly.figure_factory as ff
from plotly.tools import FigureFactory as FF
```
I'm going to close this for now, but feel free to open a new issue against version 3 if you're still having trouble with this. Thanks!
