### ISSUE TITLE
Line width affects representation of trace in Legend, while the fill (in Filled Area chart) is made less visible

### ISSUE THREAD

**Issue by petergaultney** [plotly/plotly.py#827]
In a filled area chart, the dominant color is obviously the fill color, even when a line color is configured. When no line is displayed, the legend displays only the fill color for each trace. If visible lines are desirable for the display of the data, those colors get placed on the legend as well - which is good.

The issue arises where the line width is configured in the trace to be wider than normal. When this happens, the line color becomes the dominant color for each trace on the legend, even though the fill color is the dominant color on the graph itself. This makes the legend hard to read.

In the example below, you will see that for "UGA" and "SCAR", black is the main color displayed next to the corresponding trace name in the legend, even though the primary color for each trace is red. Similarly, for "TENN" and "UK", the main color displayed in the legend is white, even though it 'ought' to be orange and blue respectively.

<img width="1597" alt="screenshot 2017-09-10 13 25 09" src="https://user-images.githubusercontent.com/549720/30251737-7d623194-962b-11e7-9f6a-d8e131890d23.png">

I have not found any way of directly configuring the contents of the legend, but if such a workaround is possible I would be glad to know about it.

**Comment by cldougl** [comment]
Hi there,
We don't have a work around for configuring line thickness in the legend at this time. This is an interesting point however this change would have to be addressed in our core graphing library: [plotly.js](https://github.com/plotly/plotly.js) so you could open an issue to discuss there.
