### ISSUE TITLE
'slider' is not allowed in 'layout'

### ISSUE THREAD

**Issue by lordlycastle** [plotly/plotly.py#830]
I'm trying to animate a 3D surface plot with the slider. And I'm following the [Gapminder exmple](https://plot.ly/python/gapminder-example/). In the example it says `layout` has two different key `slider` and `sliders`. However when I try to set `figure['layout']['slider']` I get the following error:
```
plotly.exceptions.PlotlyDictKeyError: 'slider' is not allowed in 'layout'

Path To Error: ['layout']['slider']
```

So is the example wrong or am I missing something? If I remove the `slider` dictionary then the figure does have a slider but it doesn't update the plot when the slider is moved.

I can paste the code if that'll help but it creates the slider in the exact same manner as the example does.

Any help is appreciated.

**Comment by cldougl** [comment]
Hi there,
The correct syntax is: `figure['layout']['sliders']`
The documentation page has been updated here: https://plot.ly/python/gapminder-example/ so you should be able to follow along with that example.
Thanks for pointing out that inconsistency!
