### ISSUE TITLE
Customize zoom box colors

### ISSUE THREAD

**Issue by jonperron** [plotly/plotly.py#835]
Hello,

Is there any option to customize the zoom box colors ? By default, the selection is white and what is not selected in grey. I checked the whole documentation and haven't found any reference to this issue.

Thanks in advance.

**Comment by cldougl** [comment]
Hi there, 
Do you have an example of what you'd like to change?

**Comment by cldougl** [comment]
Hi there,
This is not possible at this time. You can open a feature request in the plotly.js (our core graphing library) repo: https://github.com/plotly/plotly.js/issues
