### ISSUE TITLE
Not working with JupyterLab (0.27.0)

### ISSUE THREAD

**Issue by hiramf** [plotly/plotly.py#836]
First example given in offline plotting gives an empty output box.
```
import plotly
from plotly.graph_objs import Scatter, Layout

plotly.offline.init_notebook_mode(connected=True)

plotly.offline.iplot({
    "data": [Scatter(x=[1, 2, 3, 4], y=[4, 3, 2, 1])],
    "layout": Layout(title="hello world")
})
```
![image](https://user-images.githubusercontent.com/26015103/30647493-8f15a194-9de9-11e7-84b5-f0d758c5fde3.png)

**Comment by cldougl** [comment]
Hi there,
are you using: https://github.com/jupyterlab/jupyter-renderers?
https://github.com/plotly/plotly.py/issues/600#issuecomment-323556106

**Comment by hiramf** [comment]
that did the trick! thank you.
