### ISSUE TITLE
Animation doesn't respect the camera's up direction.

### ISSUE THREAD

**Issue by lordlycastle** [plotly/plotly.py#838]
I think this is just a bug. When you set the camera's `up` direction to be something other than (0, 0, 1), and add animations. The camera is going to move to the wrong position when you move to a different frame. I set the `up` direction to be (0, 0, -1) to rotate the plot. Here's a simple example that recreates the issue: https://gist.github.com/lordlycastle/d384d0324eb0d0598b4cda2f5815f76d

Does anyone have any other ways to rotate the camera along the Z axis by 90 degrees? When looking down, I want the (0, 0) for (x, y) to be in the top left corner, and X and Yaxis to be left-right and up-down respectively.

**Comment by lordlycastle** [comment]
Someone on plotly forum pointed out that I need to include the new layout in each frame if I want to rotate with animations. I've tried it out [here](https://gist.github.com/lordlycastle/d384d0324eb0d0598b4cda2f5815f76d). The camera still jumps to the wrong position after each animation. 

To clarify what I meant by rotation about the Z axis. See the plot blow, camera is look down from the top. Its X axis is vertical I want to rotate it by 90 degrees clockwise so it's horizontal and Y axis is vertical. And I want each frame to keep the camera there. 
![rotate-me](https://user-images.githubusercontent.com/11729541/30738711-da3374fe-9f82-11e7-9309-ee549bbf3dfd.PNG)

**Comment by empet** [comment]
@lordlycastle Please don't address the same question here and on the Plotly forum. I gave you an answer there.
