### ISSUE TITLE
daily limit issue

### ISSUE THREAD

**Issue by NickYi1990** [plotly/plotly.py#840]
when I plot, it turn out issue below

PlotlyRequestError: Hi there, you've reached the threshold of 100 combined image exports and chart saves per day. If you need to raise your daily limit, consider upgrading to a Student or Personal Plan

I am confused if this is an open source library, why I can only plot 100 image offline? Is there any method to fix this issue?

**Comment by cldougl** [comment]
Hi there,
The limit is for online chart saves and exports. There is no limit to offline usage. You can check out the [offline documentation](https://plot.ly/python/offline/) for more information.
