### ISSUE TITLE
github latest is 2.0.0 vs pypi latest 2.0.15  how comes?

### ISSUE THREAD

**Issue by jvalhondo** [plotly/plotly.py#841]
According to github, latest is 2.0.0 
However, according to pypi latest is 2.0.15 https://pypi.python.org/pypi/plotly/2.0.15
It is kind of weird and confusing, isn't it?

**Comment by ghisvail** [comment]
Perhaps they just forgot to push the tags, that's all.

**Comment by nehalecky** [comment]
Totally agree. I asked the same thing a while back, #397. No luck. :/

**Comment by jvalhondo** [comment]
Seems this issue is fixed and the tags are pushed.
https://github.com/plotly/plotly.py/tags

I can feel the improvements that are going on, great work! 💪 
I'm closing it.

**Comment by nehalecky** [comment]
tags are indeed pushed, that's great. Still, latest release shows up as 2.0.0:

![image](https://user-images.githubusercontent.com/1455590/44791049-c387a880-ab6e-11e8-9fdf-b8acd96d8010.png)

minor, but still annoying, issue

**Comment by jonmmease** [comment]
Thanks for mentioning that @nehalecky. I've never really paid attention this section in GitHub repos before 🙂 

Do you find it helpful to have the info here in addition to the changelog?  One option would be to add dummy release to the top with a link to the changelog.  But it also doesn't look like it would take much work to copy the changelog entries in here during the release process if it's helpful to folks.

**Comment by jvalhondo** [comment]
@jonmmease & @nehalecky: I would suggest a similar approach to the pandas python library (which I've also seen in most of the cases)
Here I paste the link to pandas releases: https://github.com/pandas-dev/pandas/releases
