### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by Neocurve** [plotly/plotly.py#843]
Hi, 
I have tried to add plotly.py into LaTeX for computing paper. Well, the result was not successful.
I'm wondering if there is a possibility to add Slide graph or animated drawing into LaTeX fr having animated pdf output, like what we are getting in CDF wolfram alpha?

Regards
shahram

**Comment by jackparmer** [comment]
Hi @Neocurve , the closest Plotly technology to Wolframs's CDF is Dash: https://plot.ly/dash/gallery

There are no good options for embedding Plotly (or anything interactive) in PDFs currently.

Since this is more a question than an issue, please ask on community.plot.ly in the future.
