### ISSUE TITLE
North Korean Bug

### ISSUE THREAD

**Issue by carlosvega** [plotly/plotly.py#845]
I _think_, I found a _bug_ in the plot.ly choropleth maps shown in the [docs website](https://plot.ly/python/choropleth-maps/#world-choropleth-map), in which North Korea and South Korea are mistakenly located due to wrong information of the dataset.

https://plot.ly/python/choropleth-maps/#world-choropleth-map

The dataset shows an error, and hence the labels KOR and PRK are mistakenly positioned.

```
Jordan,36.55,JOR
Kazakhstan,225.60,KAZ
Kenya,62.72,KEN
Kiribati,0.16,KIR
"Korea, North",28.00,KOR       <===
"Korea, South",1410.00,PRK   <===
Kosovo,5.99,KSV
Kuwait,179.30,KWT
Kyrgyzstan,7.65,KGZ
Laos,11.71,LAO
Latvia,32.82,LVA
Lebanon,47.50,LBN
Lesotho,2.46,LSO
Liberia,2.07,LBR
```

![bug](https://user-images.githubusercontent.com/1414389/31125816-f354de30-a849-11e7-973d-e2def5d18a2b.png)

**Comment by cldougl** [comment]
thanks for reporting @carlosvega 
fixed in https://github.com/plotly/datasets/commit/26e965de64dcc1ecd5d57c0cb1ce90d03eaf01a6
