### ISSUE TITLE
No barcharts in Jupyter Lab

### ISSUE THREAD

**Issue by hiramf** [plotly/plotly.py#849]
Plotting offline in Jupyter Lab produces a line chart instead of a bar chart.

Using this code in Jupyter Lab (0.27.0): 

```
import plotly.plotly as py
import plotly.graph_objs as go
from plotly.offline import init_notebook_mode, iplot
init_notebook_mode(connected=True)

data = [go.Bar(
            x=['giraffes', 'orangutans', 'monkeys'],
            y=[20, 14, 23]
    )]

iplot(data, filename='basic-bar')
```

**Comment by dhirschfeld** [comment]
That's sn issue with the JupyterLab renderer but is fixed in the latest version 0.10.0
https://github.com/jupyterlab/jupyter-renderers/issues/21

You should just need to update your labextension.

**Comment by jwhendy** [comment]
@dhirschfeld I'm newish to `jupyterlab`; can you confirm exactly what you mean by "update your labextension"?

I was not clear on whether or not it was a separate package or part of `jupyterlab` itself. I've used `pip install --local` for `jupyterlab`, so I checked like this for related packages:
```
find ./.local/ -iname jupyter*
```

I only have `jupyter_core`, and `jupyterlab_launcher`, and `jupyterlab`, hence my suspicion that `labextension` is part of `jupyterlab` itself. I see the binary:
```
$ jupyterlab_labextension
0.28.12 ### looks like newer than 0.10.0 to me??
```

Running @hiramf 's example above:

![2017-11-04_171658](https://user-images.githubusercontent.com/379357/32409936-08d2c3d2-c184-11e7-8267-b39a9c60abb5.png)

Am I still out of date somewhere I'm not checking/aware of?

**Comment by jwhendy** [comment]
Returning to this. Getting to know `labextension` more, I think this was meant to refer to the `plotly` extension. I have things installed locally:

```
$ jupyter labextension install --app-dir=~/.local/share/jupyter/lab @jupyterlab/plotly-extension
$ jupyterextension list --app-dir=~/.local/share/jupyter/lab
JupyterLab v0.28.12
Known labextensions:
   app dir: /home/jwhendy/.local/share/jupyter/lab
@jupyterlab/plotly-extension
        @jupyterlab/plotly-extension v0.11.1  enabled  OK

### relevant packages:
$ pip freeze
bokeh==0.12.10
ipython==6.2.1
jupyter-client==5.1.0
jupyter-console==5.2.0
jupyter-core==4.4.0
jupyterlab==0.28.12
jupyterlab-launcher==0.5.5
```

I get the same blank plot above using the example right out of the [offline instructions](https://plot.ly/python/getting-started/#initialization-for-offline-plotting):
```
import plotly
from plotly.graph_objs import Scatter, Layout

plotly.offline.init_notebook_mode(connected=True)

plotly.offline.iplot({
    "data": [Scatter(x=[1, 2, 3, 4], y=[4, 3, 2, 1])],
    "layout": Layout(title="hello world")
})
```

When using the developer tools console in `chromium`, I see:

![2017-11-05_142016](https://user-images.githubusercontent.com/379357/32418794-c885fd00-c235-11e7-99d3-cad351142d87.png)


If it's of use at all, I've been fiddling with this, `bokeh`, and `altair`. Each seems to have it's own method to enable `jupyterlab` inline rendering. Both this and `bokeh.io.output_notebook()` [are not working for me](https://github.com/bokeh/bokeh/issues/7173). (Same error about `javascript`.)

`altair` works with it's `alt.enable_mime_rendering()`.

**Comment by jwhendy** [comment]
Closing the loop here. I was having issues with `jupyter lab` in general related to [this](https://github.com/jupyterlab/jupyterlab/issues/3136#issuecomment-338791916) yesterday.

I had been using the `--dev-mode` option as mentioned, but just went through and did `jupyter lab build` as described [here](https://github.com/bokeh/bokeh/issues/7173#issuecomment-342007807) and all is well for me now.

**Comment by fperez** [comment]
I can confirm that with current JupyterLab, and installing the extension via

```
jupyter labextension install @jupyterlab/plotly-extension
```

the following code:

```python
import plotly.offline as py

from plotly.graph_objs import *
import plotly.graph_objs as go

py.init_notebook_mode()

trace = go.Heatmap(z=[[1, 20, 30],
                      [20, 1, 60],
                      [30, 60, 1]])
data = [trace]
py.iplot(data, filename='basic-heatmap')
```

renders fine:

![image](https://user-images.githubusercontent.com/57394/37444772-bde6edea-27d0-11e8-821b-1994c98649bd.png)

I've been testing more complex plots, including interactive controls:

![image](https://user-images.githubusercontent.com/57394/37444823-170a1fb4-27d1-11e8-933c-a4d5db1030b1.png)

and 3-d plots:

![image](https://user-images.githubusercontent.com/57394/37444836-35b44fb6-27d1-11e8-85c3-8a9237a5a413.png)

and everything is working without a glitch.

I'm going to close this one for now as I think it's resolved, feel free to ping if it shouldn't.
