### ISSUE TITLE
Heatmap animation stops after pausing in subplots

### ISSUE THREAD

**Issue by lordlycastle** [plotly/plotly.py#853]
I have a figure with a mix of Heatmaps, and 3D plots. I also have play and pause buttons which control the animations and a slider. When I pause the animations once and press play, all the 3D surface plots continue but heatmaps don’t change. Same with using the slider, heatmaps don't update. If I don’t press pause, the heatmaps continue to update.

Any idea what might be the cause of this?

[Here is the code I use.](https://gist.github.com/lordlycastle/bbdf4c39f8df00fc8f30152eb4b4562e)

**Comment by lordlycastle** [comment]
I've noticed one thing, if I click `Reset Views` on the top left corner the heatmaps update to the correct frame but they still don't animate when I press Play or go to different frame on the slider.

**Comment by jonmmease** [comment]
Hi @lordlycastle, are you still interested in working through this?  If so, could up update your code with version 3.2+ and post it here? (The gist link in your original post is broken now).  If you're not interested that's fine and we can go ahead and close this.  Thanks!
