### ISSUE TITLE
Interactive tooltip order

### ISSUE THREAD

**Issue by mathbeal** [plotly/plotly.py#855]
Plotly version 2.1.0

When you have stacked bars with values equals to zero or almost, interactive tooltips are ordered in an random way. It would be nice to have them displayed according to the stack order (yellow, orange, blue).

![image](https://user-images.githubusercontent.com/23397421/31535657-2a409f06-affc-11e7-9b4f-05946c24206d.png)

**Comment by jonmmease** [comment]
@alexcjohnson I feel like this has been discussed recently on the plotly.js side but I can't find the issue. Does this ring a bell?

**Comment by alexcjohnson** [comment]
Yes, a fix for this (including bar charts) was included with the stacked area PR https://github.com/plotly/plotly.js/pull/2960 (https://github.com/plotly/plotly.js/commit/2fde3dc183522879aaacca41f9aa6a453ea31162, https://github.com/plotly/plotly.js/pull/2960#discussion_r215002702). That was merged in plotly.js v1.41.

**Comment by jonmmease** [comment]
Great! So that will come along in plotly.py 3.3

**Comment by jonmmease** [comment]
Done in upgrade to plotly.js 1.41.3 in #1202 
![screen shot 2018-09-26 at 3 28 41 pm](https://user-images.githubusercontent.com/15064365/46104281-01451480-c1a1-11e8-8b49-17cedcebf507.png)
