### ISSUE TITLE
Feature request: legend.title

### ISSUE THREAD

**Issue by bluprince13** [plotly/plotly.py#857]
It'd be useful to specify a legend title. Currently, this is only possible via annotations.

See [this question](https://stackoverflow.com/questions/45555266/plotly-legend-title).

**Comment by cldougl** [comment]
Hi there,
Features such as this would be added to Plotly via our Plotly javascript library: [plotly.js](https://github.com/plotly/plotly.js). Our python API is a wrapper around this library. You can follow up on this feature in this issue: https://github.com/plotly/plotly.js/issues/689
