### ISSUE TITLE
Candlestick hoverinfo (OHLC)

### ISSUE THREAD

**Issue by aking7** [plotly/plotly.py#858]
It would be nice to choose which data to show in the hoverlabel: Open, Low, High, or Close. You either get all of them or none at the moment, and it is rather messy with all four.

**Comment by cldougl** [comment]
Hi there,
OHLC & candlestick charts are now official [plotly.js trace types](https://github.com/plotly/plotly.js/blob/master/CHANGELOG.md#1180----2016-10-13)! We first built these charts as wrappers around our scatter and boxplots in python, but now they're supported in our core graphing library: [plotly.js](https://github.com/plotly/plotly.js) 
Therefore, changes or additions to these charts should be handled in the plotly.js repo: https://github.com/plotly/plotly.js/issues so you can open an issue there for further discussion.

In the meantime, if you'd like to edit the labels shown on hover of your python chart you could use the `text` attribute like this:

```
import plotly.plotly as py
import plotly.graph_objs as go

import pandas_datareader.data as web
from datetime import datetime

hovertext=[]
for i in range(len(df.Open)):
    hovertext.append('Open: '+str(df.Open[i])+'<br>Close: '+str(df.Close[i]))

df = web.DataReader("aapl", "google", datetime(2007, 10, 1), datetime(2009, 4, 1))

trace = go.Ohlc(x=df.index,
                open=df.Open,
                high=df.High,
                low=df.Low,
                close=df.Close,
                text=hovertext,
                hoverinfo='text')
data = [trace]
py.iplot(data, filename='ohlc_custom_hover')
```
