### ISSUE TITLE
3D Support for Streamline/Quiver Plots

### ISSUE THREAD

**Issue by SterlingButters** [plotly/plotly.py#861]
Is *subject line* easily implementable or might it currently be in development?

**Comment by jackparmer** [comment]
3D `streamtubes` and `cone` plots are currently development in [plotly.js](https://github.com/plotly/plotly.js/
), here is a preview:

![image](https://user-images.githubusercontent.com/1865834/31839635-fa7cf3e6-b5af-11e7-88d7-0cd1e2d7016a.png)

![image](https://user-images.githubusercontent.com/1865834/31839690-39fe97b8-b5b0-11e7-8e47-548cd1413ce7.png)

If your company is available cosponsor this effort, [please reach out](https://plot.ly/products/consulting-and-oem/)

**Comment by SterlingButters** [comment]
Im sorry, I guess I forgot to mention that I am using Python, is development for the above for JS AND Python platforms? If development for Python platform is happening currently, where might I access the source code?

**Comment by jackparmer** [comment]
@SterlingButters the Python platform is simply an interface to the JS platform, so everything developed in Plotly.js you get for free as a Python user.

**Comment by SterlingButters** [comment]
Ahhh I see, so as I understand, cone plots and streamtubes are not in the current Plotly 2.1.0 release so how might I obtain them? Are they just hidden in GitHub somewhere and I just cant seem to find them?

**Comment by jackparmer** [comment]
I apologize, I should have been more clear - these charts are in development in a private project. They won't be added to plotly.js (and thus plotly.py) until early next year. I just wanted to let you know that these charts are currently in active development, but are not available for early access yet.

**Comment by SterlingButters** [comment]
No problem, I guess it's a good thing they are in development at least. By early next year do you mean ~January 2018? Is early access a popular thing for in-development features?

**Comment by jackparmer** [comment]
> By early next year do you mean ~January 2018? 

Probably more like March realistically.

> Is early access a popular thing for in-development features?

Not really.

If you're at a company and need to speed this along, we have [programs for that](https://plot.ly/products/consulting-and-oem/), but otherwise it's just not a big priority now unfortunately.

Thanks for your interest! I'll keep this issue open and updated as things progress.

**Comment by SterlingButters** [comment]
Awesome! thank you for your time in answering my questions :)

**Comment by zach-nervana** [comment]
Is this still going to be released soon?

**Comment by jackparmer** [comment]
Yes. Uniform grids work great, but we're currently trying to improve the
output for *nonuniform* grids. Expect an update in 3 weeks.

**Comment by bombrun** [comment]
Many thanks for plotly, I discovered it one year ago and use the 3d plot functionality in Jupyter notebook. I am looking for the 3d quiver functionality to explore the last Gaia data release (see  https://gea.esac.esa.int/archive/). I am not sure that you can expect a lot of money from the astronomer community but some enthusiastic users yes ;-)

**Comment by jackparmer** [comment]
Folks interested in 3d quiver plots should follow updates here: https://github.com/plotly/plotly.js/pull/2641

**Comment by jackparmer** [comment]
@zach-nervana @bombrun @SterlingButters 
I'm happy to report that 3d cones have finally made it to the Python library:

![image](https://user-images.githubusercontent.com/1865834/41301876-171e045a-6e37-11e8-8f30-834ef50f74fa.png)

@empet has example usage on her Plotly profile:
https://plot.ly/~empet#/

Streamlines and tubes will be released next week or the week after. Please subscribe to this PR for updates: 
https://github.com/plotly/plotly.js/pull/2658

Looking forward to see what you make. Closing this issue in lieu of https://github.com/plotly/plotly.js/pull/2658

**Comment by jackparmer** [comment]
Streamtubes are now released:

Python: https://plot.ly/python/streamtube-plot/
R: https://plot.ly/r/streamtube-plot/

![image](https://user-images.githubusercontent.com/1865834/43371191-f8b09070-935a-11e8-804a-867cef0b5fdf.png)

https://plot.ly/~empet/14958
