### ISSUE TITLE
[QUESTION]: Credentials file not working.

### ISSUE THREAD

**Issue by sadan** [plotly/plotly.py#865]
I've set the credentials file properly as per the documentation, but whenever I try to make a graph it keeps saying **You must be authenticated to generate an image via json.**

I've installed plotly in a virtualenv. I enabled my env and started python console and then created the credentials file using the commands in documentation. Is there anything else i need to do?

**Comment by empet** [comment]
To send your plot to Plotly cloud you should authenticate as follows:

```
import plotly.plotly as py
py.sign_in('username', 'api_key')

```
To get an `api_key`, access your Plotly account, click `Settings->Api Keys-> Regenerate Key`. Copy the generated key and save it on your system for a later use.

Please address any other question on Plotly Forum: [https://community.plot.ly/](https://community.plot.ly/).

**Comment by sadan** [comment]
Thank you. Do I have to sign in before creating every chart?

**Comment by sadan** [comment]
One more thing. I was facing this issue on my staging server. I don't have to do the sign in thing on my local system. It works just with the credential file.

**Comment by empet** [comment]
Yes, any time when you want to generate an online plot, you should insert the two lines of code to sign in.

**Comment by sadan** [comment]
Thank you but I am still confused why it's working for my local system without signing in.
