### ISSUE TITLE
svg export of gantt chart should not contain the date range selector

### ISSUE THREAD

**Issue by akhmerov** [plotly/plotly.py#869]
Not entirely sure whether the issue belongs here or in https://github.com/plotly/plotly.js

To reproduce:
```
import plotly.offline as py
import plotly.figure_factory as ff
py.init_notebook_mode()

df = [dict(Task="Job A", Start='2009-01-01', Finish='2009-02-28'),
      dict(Task="Job B", Start='2009-03-05', Finish='2009-04-15'),
      dict(Task="Job C", Start='2009-02-20', Finish='2009-05-30')]

fig = ff.create_gantt(df)
py.iplot(fig, filename='gantt-simple-gantt-chart', image='svg')
```

Verify that the resulting svg looks like this:
![image](https://user-images.githubusercontent.com/2069677/32146124-31c88214-bcd3-11e7-9821-cb35ef6278be.png)

and specifically that it contains the inactive selector of the date range.

Expected behavior: the date range selector does not appear in the exported svg because it plays no role anymore.

**Comment by cldougl** [comment]
Hi there,
Thanks for posting! 
- Please note a discussion on the issue of automatically removing  is better suited for our plotly.js repo https://github.com/plotly/plotly.js as we won't be able to address the removal of figure aspects on export from this repo. 
- In general, you can remove the buttons from the gannt chart like so:
```
import plotly.offline as py
import plotly.figure_factory as ff
py.init_notebook_mode()

df = [dict(Task="Job A", Start='2009-01-01', Finish='2009-02-28'),
      dict(Task="Job B", Start='2009-03-05', Finish='2009-04-15'),
      dict(Task="Job C", Start='2009-02-20', Finish='2009-05-30')]

fig = ff.create_gantt(df)
fig.layout.xaxis.rangeselector={}

py.iplot(fig, filename='gantt-simple-gantt-chart', image='svg')
```

**Comment by akhmerov** [comment]
Perfect, thanks for the solution.
