### ISSUE TITLE
Unable to zoom/pan and diagram cut off with Sankey

### ISSUE THREAD

**Issue by millertime145** [plotly/plotly.py#871]
Hello,

I have a lot of nodes and links that I'm trying to plot. Unfortunately the bottom half of the Sankey diagram is not visible (when orientation set to h, right half missing when orientation set to v). I've tried increasing the plot's height and width with no success. I was hoping I could utilize the pan/zoom in the modeBar but the default modeBar for Sankey does not have them. I've added the zoomIn2d, zoomOut2d, pan2d, etc. to the modeBar but they don't do anything. I've also tried other configs and layout options: autosizable, autosize, fillframe, dragmode, scrollzoom, etc.

I'm hoping to get some help and support for these two issues:
1. display the entire Sankey diagram in the plot
2. utilize the modeBar zoom/pan features

I appreciate any help and support!

**Comment by cldougl** [comment]
Hi there,
Thanks for writing in however we don't offer individual support from github and prefer to keep issues reserved for bug reports.
You can always post questions in our community forum: https://community.plot.ly
or check out our support site: https://support.plot.ly/

Re 1. You may want to check out our docs here: https://plot.ly/python/sankey-diagram/
Re 2. We do not offer zoom and pan functionality on the sankey charts.

**Comment by laserjeyes** [comment]
Well, let's turn this into a bug report, then. The problem from 2017 persists and it is not possible to change the height of the plot because `plotly.graph_objects.Sankey` has no attribute `height` and having it within a `go.Figure` with layout option `height` just stretches the cut-off plot. Could you please re-open?
![test](https://user-images.githubusercontent.com/42718519/73668609-64548e80-46a6-11ea-8726-f02666d833a3.png)

**Comment by alexbrower** [comment]
+1 I'm facing this same issue right now with Plotly.js.

**Comment by Kyoshido** [comment]
I have exactly the same issue with the Sankey graph in plot_ly(). With a few nodes, it is a perfect solution, but with more nodes, it starts being chaos, and the zoom feature would bring that on another level.
I am glad for this thread because I now know that solution does not exist.

**Comment by sid0rina** [comment]
Hi there! What helped me is to set `margin_b` parameter in `fig.update_layout()`, like this:

`fig.update_layout(title_text=title, font_size=10, width=2200, height=700, margin_b=150)`

**Comment by j-mcnerney** [comment]
+1 I'm having this issue as well. Being able to zoom in and out would be incredibly useful.
