### ISSUE TITLE
Inconsistent make_subplots print_grid output for subplot with rowspan and colspan

### ISSUE THREAD

**Issue by lordlycastle** [plotly/plotly.py#873]
When I try to make subplots as shown below, the printed grid is wrong.
```
figure = tools.make_subplots(rows=3,
                                 cols=3,
                                 specs=[[{'is_3d': True}, {'rowspan': 3, 'colspan': 2, 'is_3d': False}, None],
                                        [{'is_3d': True}, None, None],
                                        [{'is_3d': False}, None, None]]
                                 )
# Output
[ (1,1) scene1 ]  [ (1,2) x1,y1            -       ]
[ (2,1) scene2 ]         |              (empty)     
[ (3,1) x2,y2 ]          |                 |        
```

That `(empty)` should not be there.

**Comment by cldougl** [comment]
Hi there,
I'm note sure I can tell what type of subplot you're intending to create based on the specs listed above. 
Can you provide a reproducible example with traces added?

**Comment by lordlycastle** [comment]
How does it matter what type of plot? I'm just setting up the figure and `make_subplots` function returns incorrect subplot information.

**Comment by jonmmease** [comment]
Just to clarify, you're pointing out that the printed grid information in this case has a cell labeled `(empty)` rather than `|`?

**Comment by lordlycastle** [comment]
@jonmmease Yes.

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
