### ISSUE TITLE
Y axis labels have wrong formatting

### ISSUE THREAD

**Issue by AndriiMazur** [plotly/plotly.py#877]
I wanted to use custom Y axis labels, and have found that the labels with numbers are shifted somehow, 
below is a sample code that demostrates the strange behaviour. Is there any build-in formatting based on the labels names or some secret tags for formatting?

    import plotly.plotly as py
    import plotly.graph_objs as go
    from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot
    import datetime

    yTickValues = list(range(8)) 
    yTickNames = ['StartSendingSsp0', 'OrganizedTxSsp0', 'I2cRwHandler', 'GpsParser', 'SSP1_IRQn', 'USART0_IRQn', 'RTC_IRQn', 'I2C_IRQn']

    xaxis = [datetime.datetime(2000, 1, 1, 0, 0, 0, 686002), 
         datetime.datetime(2000, 1, 1, 0, 0, 0, 686008), 
         datetime.datetime(2000, 1, 1, 0, 0, 0, 686045), 
         datetime.datetime(2000, 1, 1, 0, 0, 0, 686176), 
         datetime.datetime(2000, 1, 1, 0, 0, 0, 686192), 
         datetime.datetime(2000, 1, 1, 0, 0, 0, 686523), 
         datetime.datetime(2000, 1, 1, 0, 0, 0, 686530)]

    yaxis = list(range(8))

    # Create a trace
    trace = go.Scatter(
    x = xaxis,
    y = yaxis,
    mode = 'markers'
    )

    layout = dict(title = 'Tracer',
                yaxis = dict(
                            tickvals = yTickValues,
                            ticktext = yTickNames, 
                            showticklabels = True,
                            )
        )

    data = [trace]

    fig = dict(data=data, layout=layout)

    plot(fig, filename='example')

**Comment by cldougl** [comment]
Hi there, 
Running the code you've provided above, I see the intended behaviour that the labels are right aligned. You can increase the margin size to avoid labels getting cut off (https://plot.ly/python/reference/#layout-margin). If that doesn't address the issue you're seeing can you include a screenshot highlighting the issue?

**Comment by AndriiMazur** [comment]
At the picture above you can see that formatting is different for all labels
![2egpd](https://user-images.githubusercontent.com/22343598/32739003-f18f0312-c89e-11e7-9925-a1f719ef86ec.jpg)

**Comment by cldougl** [comment]
Great, so that example looks different than the code you've included above:
![screen shot 2017-11-13 at 12 30 17 pm](https://user-images.githubusercontent.com/2789078/32739623-712b7438-c86e-11e7-963c-b483a0096f03.png)

In order for us to be able to tell what the issue is we'll need a reproducible example.
