### ISSUE TITLE
[question] Funnel charts don't show long text all

### ISSUE THREAD

**Issue by binghaobhw** [plotly/plotly.py#879]
This is the result of the [example](https://plot.ly/python/funnel-charts/), it works well.
![image](https://user-images.githubusercontent.com/2618234/32766563-32056a72-c8d5-11e7-9a86-0a66aa1016ce.png)

When text gets longer, it doesn't show long text all. Changing the width of layout didn't work.
![image](https://user-images.githubusercontent.com/2618234/32766639-7a434796-c8d5-11e7-9da7-1cadd9f4c2d7.png)

**Comment by cldougl** [comment]
Hi there,
You will have to edit the margin of the chart: https://plot.ly/python/reference/#layout-margin-l

**Comment by wuzhe94** [comment]
I don't want to receive the emails from plotly, especially the Q&A emails.
How can I cancel that?

2017-11-15 8:43 GMT+08:00 Chelsea <notifications@github.com>:
