### ISSUE TITLE
Single bar datum does not display with barmode='overlay'

### ISSUE THREAD

**Issue by radumas** [plotly/plotly.py#881]
I'm creating a bar plot with multiple categories and I wanted to colour each category differently, even though the categories don't overlap. Multiple rows display fine using `barmode='overlay'`, but if there's only one row in a category, it doesn't display:

![image](https://user-images.githubusercontent.com/10623872/32966277-4f0b132c-cba7-11e7-8def-2201a592ff75.png)

If I don't split the data, it displays fine (different street, same issue):

![image](https://user-images.githubusercontent.com/10623872/32965930-33870df0-cba6-11e7-8181-d96b989ea219.png)

If I change `barmode='relative'` then it displays fine:
![image](https://user-images.githubusercontent.com/10623872/32966397-b2e0439a-cba7-11e7-8841-be1466882ee6.png)

**Comment by jackparmer** [comment]
Hey @radumas I think this may be a Plotly.js issue. Can you please submit this report in that repo?
https://github.com/plotly/plotly.js/issues
This Python library is simply a Python interface to Plotly.js.
