### ISSUE TITLE
Sparkline FigureFactory (Discussion)

### ISSUE THREAD

**Issue by Kully** [plotly/plotly.py#882]
Recreation of the Stephen Few Sparklines Charts

Current strategy is to create a subplot to contain the bullet charts, text columns, line charts, etc.

![image](https://user-images.githubusercontent.com/10369095/33042035-74d980ca-ce0e-11e7-874b-9141ba4d6244.png)

![image 2](https://user-images.githubusercontent.com/10369095/33042040-773777fa-ce0e-11e7-8107-b1892eee2c6b.png)

![image 1](https://user-images.githubusercontent.com/10369095/33042044-79962d84-ce0e-11e7-9033-54af7903e484.png)

**Comment by Kully** [comment]
Some Discussion:

For the bullet charts, I think it would be very tedious for users to have all the information in their dataframes/list of dictionaries that contain all their chart information to have all the bar lengths, blue bar lengths, etc.

I'm voting having a users' data structured as just a bunch of columns:

  | adam | andrew | michael | chris | jack | robin
-- | -- | -- | -- | -- | -- | --
5 | 2 | 9 | 6 | 2 | 3
6 | 5 | 4 | 5 | 1 | 4
4 | 7 | 6 | 7 | 6 | 5
8 | 8 | 3 | 3 | 3 | 2
2 | 9 | 5 | 1 | 11 | 12
7 | 10 | 1 | 4 | 7 | 8
2 | 4 | 5 | 8 | 13 | 14
1 | 1 | 2 | 2 | 12 | 5
17 | 3 | 5 | 1 | 11 | 10
12 | 8 | 8 | 6 | 4 | 14

and users then need to run a param like `column_types` which is a list of the order and type of columns they want in their subplots.
eg. `['name', 'bullet', 'line', 'avg']`

As for the bullet chart, I don't know of any canonical values for the measures bars and range bars, but perhaps:
the marker -> the avg of values + st dev
performance bar (thick bar in bkgd) -> the avg
measure bar (thin bar) -> the last value in the list of values in column

@jackparmer any thoughts?

**Comment by jackparmer** [comment]
@Kully yep, that is about what I was thinking. We can start with some sensible defaults in the style of the Few sparklines and extend later as needed.

**Comment by gvwilson** [comment]
Hi - this issue has been sitting for a while, so as part of our effort to tidy up our public repositories I'm going to close it. If it's still a concern, we'd be grateful if you could open a new issue (with a short reproducible example if appropriate) so that we can add it to our stack. Cheers - @gvwilson
