### ISSUE TITLE
Getting min and max dates as values

### ISSUE THREAD

**Issue by orkun** [plotly/plotly.py#884]
Hi,
I looked at "Simple Candlestick with Pandas"
I wonder how we can assess the min and max dates as values after zooming
 in code?
I mean min and max dates of dynamically modified new axes as variable
Is it possible?
Regards

**Comment by jackparmer** [comment]
Since this is a usage question and not an issue, can you please ask at https://community.plot.ly/c/python? Thanks! Closing for now.
