### ISSUE TITLE
Legend click causes immediate inappropriate scroll

### ISSUE THREAD

**Issue by su79eu7k** [plotly/plotly.py#886]
**[env information]**
python 3.6.3
plotly 2.2.2

(tested on dash too)
dash 0.19.0
dash-core-components 0.15.1
dash-html-components 0.8.0
dash-renderer 0.11.1

![image](https://user-images.githubusercontent.com/6040191/33226366-71e920e0-d1cf-11e7-8aec-70337549cf4b.png)

```
import string
import numpy as np
from plotly.offline import plot
import plotly.graph_objs as go

_name = string.ascii_lowercase + string.ascii_uppercase
_x = list(range(0, 20))
_y = np.random.rand(40, 20)

data = [go.Scatter(x=_x, y=_y[n], name=_name[n] * 10) for n in range(0, 40)]

plot(data)
```
Hello, thanks for the great library.

To reproduce the issue, I made a simple example above. In the example, say you want to click the legend 'zzzzzzzzzz' to make other 39 lines fade out. But when you click it, due to the unintended legend scroll immediately happens, I always forced to click 'KKKKKKKKKK'.

And If I have more than 40 lines(which means longer legend, longer scroll), I cannot escape from '**infinite-forced-misclick**'.  For example, if I click 'KKKKKKKKKK' for correction, unintended scroll happens again, I forced to click another thing.  

The issue described also here(forum): https://community.plot.ly/t/clicking-legend-entry-causes-legend-to-scroll/3361/3

Do you think I have a solution for this? Thank you.

**Comment by jackparmer** [comment]
Hi @su79eu7k , do you mind moving this issue over to the [plotly.js repo](https://github.com/plotly/plotly.js)? This has to be investigated and solved at the plotly.js level; there's not much the Python library can do for this.
Thanks!
