### ISSUE TITLE
Optimize 3D scatter plots 

### ISSUE THREAD

**Issue by thusithaC** [plotly/plotly.py#893]
Hi, 

I raised the same question in the Plotly forum, but re-posting so it might reach a different audience. 

I use the plotly python api (Scatter3d) method to create 3D scatter plots. I love how plotly will export the generated graph into html and saves a temp file. I use the api in the offline mode.

The problem I have is when loading the saved html file (which is around 2-3 Mb with 100-200 points), after chrome renders the graph axis, the whole image freezes for a few seconds.

This is only noticed in certain computers.

*I dont mind waiting for the loading but I would like the graph to be completely loaded once the axis appears. My client does not like the ‘freezing’ effect when he tries to move the 3d plot.
just using the python api, how can i make the exported html as lean and optimized as much as possible?
*Changing the browser didn’t help. Are there any other workarounds when viewing the scatter plots?
Is there anything we can do to optimize the graphs and reduce the freezing observed at the start?
*Are there 3D alternatives to scattergl and pointcloud?

Thanks,
TC

**Comment by jackparmer** [comment]
Answered on the forum

**Comment by 0joshuaolson1** [comment]
Link?

**Comment by jackparmer** [comment]
https://community.plot.ly/t/optimize-exported-html-of-3d-scatter-plots/7233
