### ISSUE TITLE
Histogram with colorscale non working properly

### ISSUE THREAD

**Issue by ghtmtt** [plotly/plotly.py#895]
Hi all,

if this isn't the right place where to open this issue, sorry. 

The problem rises when I try to use a default numerical array as colorscale for Histograms. Super simple example:
```

import plotly
import plotly.graph_objs as go

f1 = [4,5,6,2]
f2 = [10,20,30,40]
trace1 = go.Histogram(
x = f1,
marker = dict(
    color = f2
    )
)

data = [trace1]
fig = go.Figure(data=data)
plotly.offline.plot(fig) 
```

in this case the color array is not taken into account while the same settings work perfectly with Bar and other plots:

```

import plotly
import plotly.graph_objs as go

f1 = [4,5,6,2]
f2 = [10,20,30,40]
trace1 = go.Bar(
x = f1,
marker = dict(
    color = f2
    )
)

data = [trace1]
fig = go.Figure(data=data)
plotly.offline.plot(fig) 
```

It seems that for Histogram I have to define manually rgb color values, without having all the nice colorscale colors defined, e.g.:
```
import plotly
import plotly.graph_objs as go

f1 = [4,5,6,2]
c = ['rgb(0,12,255)', 'rgb(100,0,20)',  'rgb(20,250,30)', 'rgb(20,250,30)']

trace1 = go.Histogram(
x = f1,
y = f2,
mode = 'markers',
marker = dict(
    color = c,
)
)

data = [trace1]
fig = go.Figure(data=data, layout = layout)
plotly.offline.plot(fig)
```

**Comment by cldougl** [comment]
Hi there,
You can follow this issue for more information: https://github.com/plotly/plotly.js/issues/1984

**Comment by ghtmtt** [comment]
Thanks! I was not aware of this discussion
