### ISSUE TITLE
Sd calculation in Box plot is wrong

### ISSUE THREAD

**Issue by carlaxin2** [plotly/plotly.py#898]
I am looking into the Box plot with mean and sd in python. But I found the sd calculation is wrong. The point is the denominator should be 'n-1' rather than 'n'.

The following code could verify.

`
import plotly.graph_objs as go

import plotly

y0 = [1,2,3,3.5]

trace0 = go.Box(
    x=y0,
    boxpoints=False,
    jitter=0.3,
    pointpos=-1.8,
    boxmean = 'sd',
    showlegend = True,
    hoverinfo = 'all',
    orientation = 'h',
    name = 'test1'
)

data = [trace0]
plotly.iplot(data)

# calculate the std by pandas
import pandas as pd
pd.Series(y0).std()

# manually calculation std
## n-1 ## same result with pandas std
import numpy as np
import math
math.sqrt(np.square(pd.Series(y0) - pd.Series(y0).mean()).sum() / 3)

## n ## same result with box plot
import numpy as np
import math
math.sqrt(np.square(pd.Series(y0) - pd.Series(y0).mean()).sum() / 4)
`

Thank you so much

**Comment by cldougl** [comment]
Hi there,
The box plot calculation occur in our plotly.js repo: https://github.com/plotly/plotly.js/blob/master/src/traces/box/calc.js
rather than this repo. You can open an issue there to discuss your issue- thanks!
