### ISSUE TITLE
Supporting GraphWidget serialization

### ISSUE THREAD

**Issue by jackparmer** [plotly/plotly.py#899]
Since it looks like April of this year, widget state can now be serialized for publication in notebooks or HTML. It's really cool!

[`GraphWidget`](https://github.com/plotly/plotly.py/blob/master/plotly/widgets/graph_widget.py) needs some upgrades to serialize in the way nbviewer will recognize.

For example, in [this notebook](http://nbviewer.jupyter.org/gist/jackparmer/af7f315d1d6b28883e71b956446a5d8d) on nbviewer, a serialized FloatSlider displays fine, but trying to display a GraphWidget in the [same notebook](http://nbviewer.jupyter.org/gist/jackparmer/686e51dc8908424747f112a2cd7f1a3b) does not work.**

At a minimum, it seems [graphWidget.js](https://github.com/plotly/plotly.py/blob/master/plotly/package_data/graphWidget.js) needs to be moved from [plotly/package_data](https://github.com/plotly/plotly.py/tree/master/plotly/package_data) to an npm package:

![image](https://user-images.githubusercontent.com/1865834/33869083-f24412ba-ded4-11e7-874c-d29253f5b4ea.png)
 
The IPython widget docs have a [few notes](http://ipywidgets.readthedocs.io/en/stable/embedding.html#the-case-of-custom-widget-libraries) on how to ensure custom widget libraries render on nbviewer. Probably will have to look at the [cookiecutter widget example](https://github.com/jupyter-widgets/widget-cookiecutter) to figure out where things go. @SylvainCorlay or @jasongrout, if you have any tips to get [GraphWidget](https://github.com/plotly/plotly.py/blob/master/plotly/widgets/graph_widget.py) working with serialization, would definitely appreciate any pointers!

***

** Here's how the output of this notebook should look:

![image](https://user-images.githubusercontent.com/1865834/33868802-2a8e1a00-ded3-11e7-98e3-9f9acd273bc7.png)

**Comment by jasongrout** [comment]
Hi Jack!

Does the graph widget work with ipywidgets 7? You're also right that the appropriate js code needs to move to an npm for this rendering to work.

**Comment by jackparmer** [comment]
Yeah, looks like I'm using `ipywidgets` 7.0.5 and everything works great locally ([notebook](http://nbviewer.jupyter.org/gist/jackparmer/686e51dc8908424747f112a2cd7f1a3b)).

Moving our JS assets to npm instead of the local [package_data](https://github.com/plotly/plotly.py/tree/master/plotly/package_data) folder now.

**Comment by jackparmer** [comment]
FYI for anyone interested in this issue, this work is continuing over here: https://github.com/jmmease/ipyplotly

**Comment by jonmmease** [comment]
This is now possible with `FigureWidget` (The version 3 replacement for `GraphWidget`)
