### ISSUE TITLE
Issue with plotting dates 

### ISSUE THREAD

**Issue by flyingBurman** [plotly/plotly.py#901]
I am plotting end of the month data as followed. 

![image](https://user-images.githubusercontent.com/7884934/33905535-e7a4e1ae-df4c-11e7-8410-4e255dca66bb.png)

The above shows Jan 2017 even though the real date is 2016-12-31.  Now, it kind of makes sense; but, also somewhat misleading.

Is there a way to plot the real date as I intended. 

![image](https://user-images.githubusercontent.com/7884934/33905420-966d3b7e-df4c-11e7-8ad3-bbcf108192bc.png)

Here is the code. 

{'data': [{'line': {'color': 'rgba(255, 153, 51, 1.0)',
    'dash': 'solid',
    'width': 1.3},
   'mode': 'lines',
   'name': 'Title',
   'text': '',
   'type': 'scatter',
   'x': ['2015-09-30',
    '2015-10-31',
    '2015-11-30',
    '2015-12-31',
    '2016-01-31',
    '2016-02-29',
    '2016-03-31',
    '2016-04-30',
    '2016-05-31',
    '2016-06-30',
    '2016-07-31',
    '2016-08-31',
    '2016-09-30',
    '2016-10-31',
    '2016-11-30',
    '2016-12-31',
    '2017-01-31',
    '2017-02-28',
    '2017-03-31',
    '2017-04-30',
    '2017-05-31',
    '2017-06-30',
    '2017-07-31',
    '2017-08-31',
    '2017-09-30'],
   'y': array([ 0.00493,  0.00491,  0.00513,  0.00456,  0.00443,  0.00496,
           0.00521,  0.00577,  0.00545,  0.0051 ,  0.00536,  0.00548,
           0.00513,  0.00533,  0.00539,  0.0054 ,  0.00526,  0.0052 ,
           0.00547,  0.00556,  0.00561,  0.00832,  0.00994,  0.01012,  0.01182])}],
 'layout': {'legend': {'bgcolor': '#F5F6F9', 'font': {'color': '#4D5663'}},
  'paper_bgcolor': '#F5F6F9',
  'plot_bgcolor': '#F5F6F9',
  'titlefont': {'color': '#4D5663'},
  'xaxis1': {'gridcolor': '#E1E5ED',
   'showgrid': True,
   'tickfont': {'color': '#4D5663'},
   'title': '',
   'titlefont': {'color': '#4D5663'},
   'zerolinecolor': '#E1E5ED'},
  'yaxis1': {'gridcolor': '#E1E5ED',
   'showgrid': True,
   'tickfont': {'color': '#4D5663'},
   'title': '',
   'titlefont': {'color': '#4D5663'},
   'zerolinecolor': '#E1E5ED'}}}

**Comment by cldougl** [comment]
Hi there,
That looks like the real date is plotted. Do you mean you'd like the label text to reflect your dates? If that's the case you can use: `tickmode='array'` (https://plot.ly/python/reference/#layout-xaxis-tickmode) and `tickvals` (https://plot.ly/python/reference/#layout-xaxis-tickvals).

Please note we request users only post issues with Plotly's python API in this channel and use our community forum: https://community.plot.ly/ or support app: https://support.plot.ly/ for individual questions.

**Comment by flyingBurman** [comment]
Thanks... I actually used python to generate the attached code like this `historical_series.iplot(kind="scatter",asFigure=True)`
