### ISSUE TITLE
Site.json for Jupyter Notebook Tutorial 404's

### ISSUE THREAD

**Issue by sherl0cks** [plotly/plotly.py#902]
Can't seem to find the file in this repo, but the link used in https://plot.ly/python/ipython-notebook-tutorial/ is https://raw.githubusercontent.com/ottlngr/2016-15/ottlngr/ottlngr/sites.json which 404's

**Comment by cldougl** [comment]
Hi there,
The link has been updated. Thanks for pointing that out- if you run into any other doc issues feel free to post in our documentation repo: [https://github.com/plotly/documentation/issues](https://github.com/plotly/documentation/issues)
