### ISSUE TITLE
Interactivity of Shapes

### ISSUE THREAD

**Issue by chantisnake** [plotly/plotly.py#904]
Hi, our application requires to plot the word frequency in the a text corpus, and in order to give user a better understanding of the text, we need to place a visual marker on the start of each chapter in the graph.

The first thought we had is to use Plotly shape to graph the marker as vertical straight line. But Plotly shapes does not have the ability to be interactive like the traces. For example: when you hover over a trace you will see the trace's name and the trace's x-y coordinate; and when you click the label of the trace, all the other trace will be hidden.

Is there anyway we can add interaction to plotly shapes? Or is there an better alternative than plotly shape that we can use to solve our problem?

**Comment by cldougl** [comment]
Hi there,
Plotly shapes to not have an interactive hover element.
We ask users to post individual questions in our community forum: [http://community.plot.ly/](http://community.plot.ly/) and reserve issues for issues and bugs with Plotly's python API. Thanks!
