### ISSUE TITLE
offline.py blocks some config keys

### ISSUE THREAD

**Issue by t-morley** [plotly/plotly.py#907]
Passing config = {'staticPlot': True} to offline.plot() does not have any effect.
I think this is because 'staticPlot' is not included in configkeys in _plot_html() in offline.py
showAxisRangeEntryBoxes and showAxisDragHandles are also missing, there may be others.
I am not sure whether these are deliberately omitted from config keys or if they should be added.

**Comment by mandos9** [comment]
Indeed t-morley,  'staticPlot' is not included in configkeys in _plot_html() in offline.py 
If you do include, then it works just fine. No idea why the disable it, maybe it is unstable under certain conditions?

**Comment by jonmmease** [comment]
All config keys area available as of https://github.com/plotly/plotly.py/pull/1065/
