### ISSUE TITLE
Hover Label Flicker when it contains a link 

### ISSUE THREAD

**Issue by sim-ware** [plotly/plotly.py#911]
Hi Plotly Community!

I’m having a couple of issues using the Python API for Plotly. Basically I have a Bar Chart, and some information I want to present about it in Hover Labels. However, when one of these pieces of information is presented as a hyperlink, the label itself starts to flicker when moused over. I’ve attached a gif for reference. Do you, the community, have any suggestions?
![hoverflicker](https://user-images.githubusercontent.com/17985061/34676923-5f3324e4-f486-11e7-93d7-d34545b5af91.gif)

**Comment by cldougl** [comment]
Hi there,
We currently don't recommend or support adding hyperlinks to hovertext. You can follow this issue: https://github.com/plotly/plotly.js/issues/998 in our core graphing library [plotly.js](https://github.com/plotly/plotly.js) for updates on the feature. Thanks!

**Comment by sim-ware** [comment]
Hi cldougl,
Thanks for your quick help! Will keep an eye peeled for updates on the feature, in the future. In the meantime we'll think about working round this in the short-term. Thanks again Plotly!

**Comment by newuser357** [comment]
Has there been an update to the solution?

**Comment by pkstacey** [comment]
There's a similar attempt here: [https://chart-studio.plotly.com/~chris/2540/hover-over-the-points-to-see-the-link/#/code
](https://chart-studio.plotly.com/~chris/2540/hover-over-the-points-to-see-the-link/#/code
)

I'm trying something similar to you, but neither mailto nor javascript protocols seem to be supported within the 'text' property of a dash/plotly tooltip. Any luck?
