### ISSUE TITLE
Scattergl not showing "Compare data on hover" option

### ISSUE THREAD

**Issue by andd64** [plotly/plotly.py#912]
If I try to use webgl to plot either scatter or scatter with line, I don't see an option available to compare data on hover.  Only a single point on hover is shown.

SVG allows this.

Is there any way to use webgl to show all points on hover?

**Comment by cldougl** [comment]
Hi there,
This is not currently an option. We're working on a `scattergl` update which you can follow in our [plotly.js repo](https://github.com/plotly/plotly.js) :) All changes to interactivity of the graphs will be handled in that repo. Specifically, you can follow this issue: [https://github.com/plotly/plotly.js/issues/130](https://github.com/plotly/plotly.js/issues/130) for updates on the new scattergl implementation.
