### ISSUE TITLE
More precious on gantt plot xaxis?

### ISSUE THREAD

**Issue by zeruitle** [plotly/plotly.py#914]
Hi all,

For gantt plot, the datetime format is 2017-10-30 20:19:04, precious at seconds.

But for my application, some events interval in milliseconds, like this:

2017-10-30 20:19:04.152517 - [Send To Dev]
2017-10-30 20:19:04.477342 - [Recv From Dev]

so is it possible to handle this small interval?

Thank you

**Comment by cldougl** [comment]
yes this is possible: https://plot.ly/~chelsea_lyn/16382/gantt-chart/

If you have questions please post in our community forum: https://community.plot.ly/ as this channel is reserved for issues and bug reports.
