### ISSUE TITLE
Bug in Time Series With Rangeslider plot. Wrong display of time

### ISSUE THREAD

**Issue by AlexGrig** [plotly/plotly.py#916]
Hi, I am trying to plot a time point on a timeseries plot with a rangeslidar, but the result is shifted back by 3 hours. Here is the minimal example:

```python
# Imports
import pandas as pd
import plotly
from dateutil import parser

import plotly.graph_objs as go
#plotly.offline.init_notebook_mode(connected=True) # if jupyter 
iplot = plotly.offline.iplot

## Layout
layout = dict(
    title='Some title',
    xaxis=dict(
        rangeselector=dict(
            buttons=list([
                dict(count=1, label='1h', step='hour', stepmode='backward'),
                dict(count=1, label='1d', step='day', stepmode='backward'),
                dict(step='all')
            ])
        ),
        rangeslider=dict(),
        type='datetime'
    )
)

## Define 3 time points and 3 corresponding datasets
w5_end = parser.parse('16-09-2017 23:00'); 
w6_end = parser.parse('18-09-2017 01:00');
w7_end = parser.parse('19-09-2017 08:00');

y_windows = [0, 0.04]
w5 = go.Scatter( x=[w5_end, w5_end], y=y_windows, mode = 'lines', line = dict( color = 'rgb(0, 255, 0)' ))
w6 = w5.copy(); w6['x'] = [w6_end, w6_end]
w7 = w5.copy(); w7['x'] = [w7_end, w7_end]

# Plot only one dataset (same result is plot others or all)
fig = dict(data=[w6,], layout=layout)
iplot(fig, filename = "Title")
print(w6)
```
![3_hour_diff](https://user-images.githubusercontent.com/8289883/35043460-6f5dea00-fb95-11e7-9c19-6e486aa98f5e.png)

The vertical line on '18-09-2017 01:00' must be plotted, but instead, we get a line at '17-09-2017 22:00'. So it is shifted back by 3 hours.

**Comment by cldougl** [comment]
Hi there,
Running the code you've included above resulted in the expected plot for me:
![screen shot 2018-01-17 at 1 34 10 pm](https://user-images.githubusercontent.com/2789078/35060084-3b4d0ebc-fb8b-11e7-9b0c-5a1b5dbd3288.png)
see notebook: https://plot.ly/~chelsea_lyn/16319
You may want to check that you're running an updated version of Plotly's python api (current version = 2.2.3)?

**Comment by cldougl** [comment]
closing this issue but feel free to reopen with a reproducible example using an updated version of the library!
