### ISSUE TITLE
Feature Request: add support for scatterpolar

### ISSUE THREAD

**Issue by JeffSolomon** [plotly/plotly.py#920]
https://github.com/plotly/plotly.js/pull/2200 fixes a number of issues with polar plots, but adds a new trace type (scatterpolar) that cannot currently be created through plotly.py

**Comment by cldougl** [comment]
Hi there- you can now upgrade to [version 2.3.0](https://github.com/plotly/plotly.py/blob/master/CHANGELOG.md#230---2018-01-25) of this library to use those features offline (as with plotly.js)
