### ISSUE TITLE
Scatter() allows x and y of different lengths without complaining

### ISSUE THREAD

**Issue by lebigot** [plotly/plotly.py#922]
Scatter() allows x and y of different lengths without complaining: this is very error-prone, as this should never happen with meaningful data. I would suggest to raise an exception so as to alert the user that there is a problem.

**Comment by cldougl** [comment]
Hi there,
This check would occur at the [plotly.js](https://github.com/plotly/plotly.js) (our core graphing library) level. There is an open discussion here: https://github.com/plotly/plotly.js/issues/1998 where you can follow along or contribute.
