### ISSUE TITLE
pip plotly version outdated

### ISSUE THREAD

**Issue by AfroMetal** [plotly/plotly.py#927]
https://pypi.python.org/pypi/plotly has only plotly 2.2.3, it prevents using newest `plotly.py` with pip and requirements.txt for dependency management.

**Comment by cldougl** [comment]
Hi there,
As of this morning plotly 2.2.3 was the latest version. [2.3.0](https://github.com/plotly/plotly.py/blob/master/CHANGELOG.md#230---2018-01-25) has just been added so you can now upgrade with `pip install plotly --upgrade`
