### ISSUE TITLE
How to display plotly outputs on Github?

### ISSUE THREAD

**Issue by purvithakor** [plotly/plotly.py#931]
I have plotly charts on a jupyter python notebook. Plotly charts work fine on my local system in the notebook. However, plotly charts are not displayed when I uploaded the same notebook to my github page. 

Does anyone know how to display plotly charts on github?

**Comment by empet** [comment]
@purvithakor  It appears that you are working with an old version of jupyter notebook. Since your version requires to set the `NotebookApp.iopub_data_rate_limit`, but you didn't it (see the warning IOPub data rate exceeded), the plot cannot be displayed.
Upgrade both jupyter and notebook.

**Comment by hassenmorad** [comment]
I'm having this same problem despite updated jupyter notebook & lab. Any suggestions?

**Comment by jonmmease** [comment]
Hi @purvithakor, the issue is that github performs a static render of the notebooks and it doesn't include the embedded HTML/JavaScript that makes up a plotly graph.  See https://help.github.com/articles/working-with-jupyter-notebook-files-on-github/

One nice option is to paste the link to your GitHub notebook into http://nbviewer.jupyter.org/, which will present a rich view of the notebook.

Hope that clear things up!

**Comment by hassenmorad** [comment]
Thanks, @jonmmease :)

**Comment by anthonymakela** [comment]
@jonmmease There seems to be a problem also with nbviewer, it's not rendering the plotly graphs when using R kernel? https://nbviewer.jupyter.org/github/anthonymakela/Traffic-accidents-Finland/blob/master/traffic_accident_analysis_finland.ipynb

**Comment by murilobellatini** [comment]
Hello, are there no updates on this issue?

I was keen to write a personal `quick-and-dirty` solution considering `plotly.io`'s `to_image` and `cufflinks` `iplot`, but wasn't so far even able to have both packages working together due to incompatible versioning...

Does anyone have a better approach?

**Comment by nicolaskruchten** [comment]
Yes, this works: https://github.com/nicolaskruchten/plotly_img_test/blob/master/Untitled.ipynb

**Comment by nicolaskruchten** [comment]
Full documentation about our renderer framework is here: https://plot.ly/python/renderers/ and this approach requires Orca to be installed, docs here: https://plot.ly/python/static-image-export/

**Comment by gndoshi** [comment]
> Full documentation about our renderer framework is here: https://plot.ly/python/renderers/ and this approach requires Orca to be installed, docs here: https://plot.ly/python/static-image-export/

Can you please share how you did it? I don't seem to understand what to do to override the renderer.

**Comment by nicolaskruchten** [comment]
Yes, check out the notebook I mentioned above: https://github.com/nicolaskruchten/plotly_img_test/blob/master/Untitled.ipynb you just call `fig.show("png")` or `fig.show("svg")`

**Comment by AnuragMishra2311** [comment]
> Hi @hassenmorad , the issue is that github performs a static render of the notebooks and it doesn't include the embedded HTML/JavaScript that makes up a plotly graph. See https://help.github.com/articles/working-with-jupyter-notebook-files-on-github/
> 
> One nice option is to paste the link to your GitHub notebook into http://nbviewer.jupyter.org/, which will present a rich view of the notebook.
> 
> Hope that clear things up!

Thanks @jonmmease

**Comment by amr-ssj** [comment]
> Hi @hassenmorad , the issue is that github performs a static render of the notebooks and it doesn't include the embedded HTML/JavaScript that makes up a plotly graph. See https://help.github.com/articles/working-with-jupyter-notebook-files-on-github/
> 
> One nice option is to paste the link to your GitHub notebook into http://nbviewer.jupyter.org/, which will present a rich view of the notebook.
> 
> Hope that clear things up!

Hi @jonmmease , I did what you had suggested, and pasted the Github link in the nbviewer link as well. The notebook has come just fine and perfect. But is there a way to apply this setting in Github as well? I mean the display of complete plotly images?

**Comment by jonmmease** [comment]
There's no way to cause GitHub to render embedded HTML in notebooks, so the two options I'm aware of are:
  - View the notebook through nbviewer
  - Save the figures in the notebook as static images using the `png` renderer (See https://plotly.com/python/renderers/#static-image-renderers). The figures won't be interactive, but they should show up fine on GitHub.

**Comment by empet** [comment]
To ensure plots rendering in your github posted notebook don't use `fig.show()`.
`nbviewer` displays your plot:
1)  when you call `plotly.offline.iplot(fig)` [https://nbviewer.jupyter.org/github/empet/US-Presidential-Election-2020/blob/master/Pew-Research-Preference-Vote-Aug.ipynb](https://nbviewer.jupyter.org/github/empet/US-Presidential-Election-2020/blob/master/Pew-Research-Preference-Vote-Aug.ipynb);
2) when you send your plot to chart studio:

```
import chart_studio.plotly as py
py.iplot(fig)
```

**Comment by nicolaskruchten** [comment]
`plotly.offline.iplot()` is deprecated, and in fact uses the same machinery as `fig.show()` internally, so they should be equivalent. Calling `init_notebook_mode(connected=True)` is also unnecessary now. The recommended pattern which will work on NBViewer but not Github is:

```python
import plotly.io as pio
pio.renderers.default = "notebook_connected"

fig = ...

fig.show()
```

The recommended pattern for rendering on Github in SVG but not interactive is to replace `notebook_connected` with `svg` in the above.

Here are two notebooks in Github and NBViewer for comparison:
1. using the SVG approach: [Github](https://github.com/nicolaskruchten/plotly_img_test/blob/master/Untitled.ipynb), [NBViewer](https://nbviewer.jupyter.org/github/nicolaskruchten/plotly_img_test/blob/master/Untitled.ipynb)
2. using the notebook_connected approach: [Github](https://github.com/nicolaskruchten/plotly_img_test/blob/master/Untitled2.ipynb), [NBViewer](https://nbviewer.jupyter.org/github/nicolaskruchten/plotly_img_test/blob/master/Untitled2.ipynb)

Note: unfortunately in JupyterLab while developing, the `notebook_connected` approach doesn't render, so you'll have to change the default renderer right before publishing or something...

**Comment by empet** [comment]
I created this repo [https://github.com/empet/Patterns-by-mixed-operations](https://github.com/empet/Patterns-by-mixed-operations), just now, to illustrate which method works and which doesn't display the interactive plot via nbviewer.

In README there are  three links. The first one is the link to the notebook, where only `fig.show()` is called, and no pio renderer is set.

The second one uses the deprecated method that still works.  It was deprecated long time before I created the notebook with Pew Reaserch poll, but I continued to use it as the proven method that works.

The third notewook  sets `pio.renderer` as @nicolaskruchten  mentioned above.

**Comment by nicolaskruchten** [comment]
(the third link doesn't work for me) ... The reason the deprecated method works is that it does the same thing as the pio method :)

**Comment by nicolaskruchten** [comment]
Here is what the code for `init_notebook_mode` does: https://github.com/plotly/plotly.py/blob/03979d105c65dda3df3a155322eaff18f203b03f/packages/python/plotly/plotly/offline/offline.py#L285-L288

(so really, my recommendation should have been to use both renderers like this instead of just `notebook_connected`, so that it would work in JupyterLab as well!)

The point I'm trying to make here btw is that "don't use `fig.show()`" runs counter to our current development philosophy for this library: we are trying to funnel everything through `fig.show` and we've stripped out all mentions of `plotly.offline` from the docs because the online/offline distinction has historically really confused and scared folks :)

**Comment by empet** [comment]
The third  notebook is not rendered because of this issue https://github.com/jupyter/nbviewer/issues/916 . From my experience after a while nbviewer can display it.

**Comment by Caldass** [comment]
> `plotly.offline.iplot()` is deprecated, and in fact uses the same machinery as `fig.show()` internally, so they should be equivalent. Calling `init_notebook_mode(connected=True)` is also unnecessary now. The recommended pattern which will work on NBViewer but not Github is:
> 
> ```python
> import plotly.io as pio
> pio.renderers.default = "notebook_connected"
> 
> fig = ...
> 
> fig.show()
> ```
> 
> The recommended pattern for rendering on Github in SVG but not interactive is to replace `notebook_connected` with `svg` in the above.
> 
> Here are two notebooks in Github and NBViewer for comparison:
> 
> 1. using the SVG approach: [Github](https://github.com/nicolaskruchten/plotly_img_test/blob/master/Untitled.ipynb), [NBViewer](https://nbviewer.jupyter.org/github/nicolaskruchten/plotly_img_test/blob/master/Untitled.ipynb)
> 2. using the notebook_connected approach: [Github](https://github.com/nicolaskruchten/plotly_img_test/blob/master/Untitled2.ipynb), [NBViewer](https://nbviewer.jupyter.org/github/nicolaskruchten/plotly_img_test/blob/master/Untitled2.ipynb)
> 
> Note: while both of the above work in "classic notebook", unfortunately in JupyterLab while developing, the `notebook_connected` approach doesn't render, so you'll have to change the default renderer right before publishing or something...

The SVG approach requires me to install psutil library so that's why I'm asking and not testing myself:

If I to the SVG approach, plots wont be interactive in github, but will they be interactive in my notebook still?

**Comment by nicolaskruchten** [comment]
No, the SVG renderer does not yield interactive charts in notebook.

**Comment by nschloe** [comment]
For anyone interested, I published the browser extension [xdoc](https://github.com/nschloe/xdoc) the other day which let you display (interactive) plotly charts in GitHub READMEs, Wikis etc. 

![screenshot](https://user-images.githubusercontent.com/181628/122748781-df631880-d28c-11eb-8e25-48fd0be0ed46.png)

This works by supplying the plot data as JSON in a `plotly` code block,
````markdown
```plotly
{
  "data": [ ... ],
  "layout": { ... }
}
```
````

**Comment by ngupta23** [comment]
> Yes, check out the notebook I mentioned above: https://github.com/nicolaskruchten/plotly_img_test/blob/master/Untitled.ipynb you just call `fig.show("png")` or `fig.show("svg")`

This did not work for me. I had to use `fig.show("notebook")` to make the plots show up on GitHub.

**Comment by ChukwudiAsibe** [comment]
> Hi @hassenmorad , the issue is that github performs a static render of the notebooks and it doesn't include the embedded HTML/JavaScript that makes up a plotly graph. See https://help.github.com/articles/working-with-jupyter-notebook-files-on-github/
> 
> One nice option is to paste the link to your GitHub notebook into http://nbviewer.jupyter.org/, which will present a rich view of the notebook.
> 
> Hope that clear things up!
I tried your procedure it worked, but how do we place it back to github.

**Comment by rwarren** [comment]
Not sure if this is the current best way (I landed on this issue while searching to see if there is a better way), but I am able to get interactive notebooks in jupyterlab **_AND_** plots rendered in GitHub by configuring plotly to use [multiple renderers](https://plotly.com/python/renderers/#multiple-renderers) before doing any plotting.  This combo does the trick:

```python
import plotly.io as pio
pio.renderers.default = "jupyterlab+png"
```

The `png` renderer is what results in embedded images that basic GitHub viewing can render, while the `jupyterlab` renderer gives the interactive charting in a jupyterlab environment.  You could also use `vscode` or any other renderer instead, depending on your use case.

Anyone know of a better way to achieve this? This solution does render twice, and you see both render phases for slower plots (although the interactive plot replaces the static plot), but the final result is exactly what is needed.
