### ISSUE TITLE
Rescale y-axis for graphs with x-axis rangeslider (Python)

### ISSUE THREAD

**Issue by JuanRedondoHernan** [plotly/plotly.py#932]
Related with the closed issue [#912](https://github.com/ropensci/plotly/issues/912#issuecomment-363142955), I haven't found the functionality on Python Plotly library.
I haven't been able neither to implement something similar as they did in R in the aforementioned issue. I would like to keep everything in Python since I do other parts of analysis and it is intended to be modified by other users. I would appreciate any hit about how to do it.

**Comment by cldougl** [comment]
Hi there,
The range slider is intended to update the range of the control axis, the behaviour does not adjust the overall zoom or rescale the y-axis so this issue would not be considered a bug (please note we ask users to reserve this channel for issues and bugs with Plotly's python api). 

As mentioned in the R issue-  the range slider functionality is handled in our core graphing library: [plotly.js](https://github.com/plotly/plotly.js) so changes to this feature could be discussed there.

Alternatively, you may be interested in implementing [Dash](https://plot.ly/dash/), this is a python tool similar to Shiny for R (mentioned in R issue that you noted above). Specifically you could take a look at the [interactive graphing section](https://plot.ly/dash/interactive-graphing) to see how you can implement events based on zooming on the graph.

Don't forget you can always post questions and get feedback about individual projects that you're working on in our community forum: https://community.plot.ly which is free and open to all users!

**Comment by kamal264** [comment]
Hi , 
I am also looking for similar functionality in python-django.
I am working on finance application in django and using plotly to draw stock price.
And want to enable auto range for y-axis else graph is not making any sense in my scenario.
![image](https://user-images.githubusercontent.com/8677429/43976401-0cbe9998-9cfe-11e8-94cc-ec25847da448.png)

After narrowing x-axis range- not able to analyse any price movement

![image](https://user-images.githubusercontent.com/8677429/43976455-3ff5ab94-9cfe-11e8-9f1a-16d054124a87.png)

**Comment by gersteing** [comment]
I struggled with getting this to work so I developed a code example to share. Example provides automatic updates to the yaxis range when and x range slider is updated. Y axis is set to show only price range of bars that are in the chart with a two tick padding. This worked well for me and I can potentially add any number of trace overlays that I want on top of the chart. Plus, I can run it locally without having to use plotly services. See gitub repo here:

https://github.com/gersteing/DashCandlestickCharting

For whom ever wants to try it out. Runs locally using Flask. Enjoy

**Comment by cadab** [comment]
I've ran into this same issue using the plotly js library.

I created a simple workaround using the relayout event. Its specific to the ohlc chart type, but can easily modify to work with the other chart types.

[Plotly OHLC Rescale yAxis](https://gist.github.com/cadab/a86995ba37d570255ad383854acfe6e8)

Hope it helps someone.

**Comment by ernestocr** [comment]
Any update on this request?

**Comment by gioxc88** [comment]
please update this
the chart is unusable without auto scaling of y axis

**Comment by vinerich** [comment]
I'd also like to have this feature in the main plotly.js.
I have several x-range synchronized graphs that display varying data. Without scaling of y axis this is rather not usable depending on the data-range of the graph.

Atm I also use nearly the same workaround as @jamescoverdale to implement this by myself.

**Comment by tumkik** [comment]
I got some issue similar to this one when create candlestick chart using plotly.
The problem is the rangeslider itself.
To fix the issue, you simply remove the rangeslider.
After that y axis will automaically scalling when you zoom. (however, you cannot use rangeslider anymore, but in my case, drag zoom works just fine for me)

just add below code for removing rangeslider in the 'layout' 
xaxis:{'rangeslider': {'visible': False}}

**Comment by wuxian08** [comment]
Just to add some more information, I noticed that there was a community discussion (https://community.plotly.com/t/y-axis-autoscaling-with-x-range-sliders/10245) regarding to this and the proposed method (an 'xaxis.range' event  registered in layout) seemed outdated. 

This would be very appealing in some use cases

**Comment by peter-hartmann** [comment]
Setting yaxis fixedrange to false will allow to zooming while having a range slider.  It's not autoscaling but it's easy and much better over having no zoom at all.

Hope this helps someone.

Credits: https://stackoverflow.com/a/52816021/10689649
```
{
    yaxis: {
      fixedrange: false
    }
}
```

**Comment by eightbit** [comment]
Try
`fig.update_yaxes(fixedrange=False)`

**Comment by eightbit** [comment]
Single line:
`fig.update_yaxes(fixedrange=False)`

**Comment by valankar** [comment]
Is there still no way to do this with rangeselector/slider and HTML plots? I do not want to use Dash.

**Comment by Thomas-Heniart** [comment]
I am also looking for an easier solution 🙏

**Comment by LucaZiegler** [comment]
Please fix that
![image](https://github.com/plotly/plotly.py/assets/36471502/49461afe-cab7-46cc-b36f-deebaa86e6ce)

**Comment by secsilm** [comment]
Still no solu?
