### ISSUE TITLE
Curves coming from different data, each filtered by different buttons on the same graph

### ISSUE THREAD

**Issue by JuanRedondoHernan** [plotly/plotly.py#933]
I haven't found so far a method for displaying lines coming from two data sources (each one with a button for selecting what is to be ploted. In my case, I want to show the historical quantiles of a time series, and over it one specific time series. I would like to have one button for selecting the quantiles calculated on different historical periods, and another button for selecting a specific time series from a list of a few.
The alternative I tried is putting just one button for the different historical periods, making always visible all the specific time series. The selection of the specific series would be done clicking on the legend, but it is quite cumbersome since every time I click change the quantiles for a different historical period all the specific time series reappear.
I haven't found in my search this (from my point of view) useful functionality neither in other interactive plotting libraries for python, which makes me think that it not easy to do.

Please, let me know if it is something already done or a workaround that solves this limitation.

**Comment by cldougl** [comment]
Hi there- 
you may be interested in checking out Dash - https://plot.ly/dash/ to add interactive elements such as buttons to your chart/application.

Please note that we ask users to only post issues and bugs with Plotly's python api in this repo. If you have general questions about your project please post in our community forum: [https://community.plot.ly](https://community.plot.ly)
