### ISSUE TITLE
scatterplotmatrix: setting marker symbol completely throws of scattermatrix plots

### ISSUE THREAD

**Issue by albalu** [plotly/plotly.py#934]
This works fine:

import plotly
import plotly.figure_factory as FF
import numpy as np
import pandas as pd

dataframe = pd.DataFrame(np.random.randn(100, 3),
                         columns=['Column A', 'Column B', 'Column C'])

fig = FF.create_scatterplotmatrix(dataframe, diag='box',
                                  colormap='Portland', colormap_type='seq',
                                  height=800, width=800, size=5,
                                  # marker=dict(symbol=25)
                                  )
plotly.offline.plot(fig, filename='test', auto_open=True)

Now if you uncomment the marker=dict(symbol=25), the resulting plot is completely messed up (even the order of plots change). I am using Python 3.6.4 and Plotly 2.3.0

**Comment by empet** [comment]
@albalu  Your figure representing a scatterplotmatrix consists in 9 subplots. You should update the marker only in some of them.
The list `fig['data']` contains 9 dicts. `fig['data'][k]`, k=0,1,2, ..8, is a dict describing data assigned to the corresponding subplot.
Hence to update the marker type you should specify the data dicts to be updated:
```
data_idx=[1, 2, 3, 5, 6, 7]
for k in data_idx:
    fig['data'][k].update(marker=dict(symbol=25))
iplot(fig) 
```  
From now on, please address questions on the Plotly forum [https://community.plot.ly/](https://community.plot.ly/), and open an issue only your are sure that it is a real  issue, not only a missunderstanding of the Plotly object you are working with.

**Comment by albalu** [comment]
@empet , thanks for your help! Sure, I will use the forum. It looked like an issue as I wasn't getting any warning passing marker symbol for 'histogram' or 'box' mode; it just silently changed the plots on the diagonal as well.
