### ISSUE TITLE
GraphWidget not loading properly

### ISSUE THREAD

**Issue by CermakM** [plotly/plotly.py#935]
Hello, 

I am having an issue similar to #490, I also commented on this. 
But I think the description of the issue does not fully match my issue.

Initializing the GraphWidget in Jupyter such as:

```python
g = GraphWidget(url)
print(g)
```

The output is:
```python
GraphWidget()
```

Feels like it creates an empty object. `display(g)` also does not display anything. Attaching log file.

Thank you for any help!

[jupyter-graphwidget.log](https://github.com/plotly/plotly.py/files/1703030/jupyter-graphwidget.log)

**Comment by jonmmease** [comment]
Hi @CermakM , thanks for taking the time to report this. I'm going to close this since the functionality of `GraphWidget` has since been replaced by the much more capable `FigureWidget` in version 3.  Thanks!
