### ISSUE TITLE
x-axis range issue

### ISSUE THREAD

**Issue by ebbpy** [plotly/plotly.py#936]
```
import plotly.offline as py
import plotly.graph_objs as go

py.offline.init_notebook_mode(connected=True)

US_GDP = go.Bar(x = US_GDP_pctchange.index,
                y = US_GDP_pctchange['US_GDP Percentage change'],
                name='GDP change',
                marker=dict(
                    color='rgb(124, 252, 0)',
                    line=dict(
                        color='rgb(0,100,0)',
                        width=1)
                    ),
                opacity=0.6)


ISM_PMI = go.Scatter(x = ISM_raw_df.index,
                    y = ISM_raw_df['ISM/MAN_PMI - Index'],
                    yaxis='y2',
                    name='PMI data',
                    line=dict(
                        color = ('rgb(205, 12, 24)'),
                        width=1)
                   )

data = [US_GDP, ISM_PMI]
layout = dict(
    title='US GDP Percentage Change',
    xaxis=dict(
        rangeselector=dict(
            buttons=list([
                dict(count=20,
                    label='20y',
                    step='year',
                    stepmode='backward'),
                dict(count=30,
                    label='30y',
                    step='year',
                    stepmode='backward'),
                dict(step='all')
            ]),
        ),
        rangeslider=dict(),
        type='date'
    ),
    yaxis=dict(
        title='US GDP growth (%)',
    ),
    yaxis2=dict(
        title='ISM PMI data (%)',
        overlaying='y',
        side='right')
)

fig = dict(data=data, layout=layout)
py.iplot(fig)
```
This is my first post on GitHub, please point out any issues you see with my formatting so I can improve subsequent posts.

I have been playing around with the plotly.py charting libraries and have come across a peculiar feature. The code above yields the following graph. 

![newplot](https://user-images.githubusercontent.com/32223462/36141174-b6f940c4-109b-11e8-9fe6-432005e9b6f2.png)

When attempting to add markers to the line, I used the following code which works, but raises a problem.

```
ISM_PMI = go.Scatter(x = ISM_raw_df.index,
                    y = ISM_raw_df['ISM/MAN_PMI - Index'],
                    mode="lines+markers",
                    yaxis='y2',
                    name='PMI data',
                    line=dict(
                        color = ('rgb(205, 12, 24)'),
                        width=1)
```
By making this change, the x-axis range extends by a seemingly random amount. It's not really a major issue, but I'm concerned that I'm unable to manually adjust the x-axis range and I'm struggling to work out why. The image below highlights the issue.

![newplot 1](https://user-images.githubusercontent.com/32223462/36141405-7e9ebe74-109c-11e8-92f4-e10ede476ece.png)

Thanks in advance.

**Comment by cldougl** [comment]
Hi there,
(and welcome to github!)
I understand that this seems like an odd result but it's actually the intended behavior. 
As noted in [this issue](https://github.com/plotly/plotly.js/issues/205#issuecomment-173720224) in the [plotly.js repo](https://github.com/plotly/plotly.js) (our core graphing library) the autorange of the axis expands by a function of the marker size. 
If you do not like that axis extension you can set [autorange](https://plot.ly/python/reference/#layout-xaxis-autorange) to false and manually define the range of your axis: https://plot.ly/python/reference/#layout-xaxis-range

**Comment by ebbpy** [comment]
Thanks for your help, I understand now.
