### ISSUE TITLE
Python 3.6.4 offline plot

### ISSUE THREAD

**Issue by paolocavagnolo** [plotly/plotly.py#937]
Hello,
I've noticed a problem while following [this](https://plot.ly/python/2d-projection-of-3d-surface/) tutorial and plotting in **offline** mode.

I'm using python 3.6.4 on windows and running the example above return this error:
`TypeError: Object of type 'range' is not JSON serializable`

I've fixed it changing line 184 of "\offline\offline.py" 
from:
```
jlayout = _json.dumps(figure.get('layout', {}),
                          cls=utils.PlotlyJSONEncoder)
```
to:
```
jlayout = _json.dumps(list(figure.get('layout', {})),
                          cls=utils.PlotlyJSONEncoder)
```

...i understood its a problem between python 2 and python 3.. but i'm not so into it..

**Comment by jonmmease** [comment]
Thanks for the report @paolocavagnolo.  Yeah, that tutorial needs to be updated for Python 3. I've opened an issue in the documentation repo here https://github.com/plotly/documentation/issues/1099. Thanks again!
