### ISSUE TITLE
rename `offline_mode` param from ff.create_choropleth

### ISSUE THREAD

**Issue by Kully** [plotly/plotly.py#944]
Enabling `offline_mode` modifies the centroid points that are plotted in a choropleth to include the parameters `selected` and `unselected` which change the visibility of these points upon dragbox hover. This feature did not exist before merging the choropleth figure factory, meaning these keys could only pass with a plotly fig if: 1) offline mode and 2) validate=False

Now these keys are part of the plotly reference:
https://plot.ly/python/reference/#scatter-selected
https://plot.ly/python/reference/#scatter-unselected

I vote for removing this param completely,

**Comment by cldougl** [comment]
+1

**Comment by Kully** [comment]
After inspection of the code, it makes more sense to rename the variable.

**Comment by jonmmease** [comment]
@Kully , can we close this, or is there anything more to do here?

**Comment by Kully** [comment]
> @Kully , can we close this, or is there anything more to do here?

Yes we can closed. Already addressed.
