### ISSUE TITLE
Retry requests to Plotly in our Python API

### ISSUE THREAD

**Issue by Kully** [plotly/plotly.py#949]
Original Issue: https://github.com/plotly/streambed/issues/10634
I'm going to deal with this starting next Tuesday. Can do some preliminary look/testing/discussion today.

cc: @scjody @jackparmer

**Comment by cldougl** [comment]
@Kully this should help the intermittent test failures as well

**Comment by Kully** [comment]
Good resource I just found for the issue: https://www.peterbe.com/plog/best-practice-with-retries-with-requests

**Comment by scjody** [comment]
The `retrying` library is a more general solution. The backend already uses it for some Google Cloud Storage requests as well as imageserver requests. The imageserver request PR is here: https://github.com/plotly/streambed/pull/10614/files

**Comment by jonmmease** [comment]
This has been implemented in #942 and will be released as part of 3.0.0

**Comment by jonmmease** [comment]
Done!
