### ISSUE TITLE
Cannot Login

### ISSUE THREAD

**Issue by chasen-bettinger** [plotly/plotly.py#950]
I am trying to get started wth Plotly but cannot log in to my account! I tried to create an account through the form but was denied and then I created an account through Github and it went through because I received an e-mail. However, when I try to log in with Github, the authorization fails, every time.

**Comment by cldougl** [comment]
Hi there,
You can contact accounts@plot.ly for issues with your account. This repo is reserved for issues with Plotly's python api
Thanks!
