### ISSUE TITLE
multiline category labels aren't centered

### ISSUE THREAD

**Issue by thandls** [plotly/plotly.py#951]
In horizontal barcharts with multiline labels (using HTML <br> tags) the lables are aligned as if they would consist of only one line, i. e. they aren't centered vertically. 

![image](https://user-images.githubusercontent.com/36252196/36828861-40de7dbe-1d57-11e8-99be-b7243a2f8d53.png)
![image](https://user-images.githubusercontent.com/36252196/36828869-481ee9ba-1d57-11e8-9bad-1b162c695a1c.png)

**Comment by cldougl** [comment]
Hi there,
It's not possible to center these labels with Plotly at this time.
You can follow this issue: https://github.com/plotly/plotly.js/issues/1137 in our plotly.js repo (core graphing library) for progress on the feature.
