### ISSUE TITLE
How do I set default order of my sankey diagram?

### ISSUE THREAD

**Issue by chankuyeo** [plotly/plotly.py#960]
Whenever I display my sankey diagrm(sankey chart) with python plotly,
the order of nodes change depending on some unknown rules.
How do i fix the order of the nodes?

**Comment by cldougl** [comment]
Hi there,
It is not possible to set default ordering at this time. You can see the list of available sankey attributes here: https://plot.ly/python/reference/#sankey
The attributes of the sankey chart are determined in our [plotly.js repo](https://github.com/plotly/plotly.js) (plotly's core graphing library).
We ask users to reserve issues in this repo for bugs with Plotly's python api, if you have additional plotting questions feel free to post in our community forum: https://community.plot.ly/

**Comment by lrlucchini** [comment]
@cldougl could you shed some light into the logic to determine the ordering of the nodes? How is it decided which ones are rendered on top?

**Comment by chriddyp** [comment]
This is done automatically by plotly.js. Custom ordering is currently being worked on in https://github.com/plotly/plotly.js/pull/3583.

**Comment by aesharpe** [comment]
Hi! Is this still not possible? It seems like defining node order would be a great feature (I'm currently trying to make my sankey more static)

**Comment by lrlucchini** [comment]
I don't think it's possible yet, unfortunately.

**Comment by theophile-dh** [comment]
I don't know if it's still relevant, but you can actually drag and drop them on the UI. Far from perfect, but it will save you if you have a presentation to make quickly ;)

**Comment by lucasrodes** [comment]
Any updates?

**Comment by thenineteen** [comment]
I have to agree this is very disappointing as half the value of a Sankey diagram is in its presentation and being able to eyeball trends. For example, if the first level is by Year, a random order is not useful for deciphering patterns.

**Comment by chriddyp** [comment]
@thenineteen et al - As mentioned above, can you please create a new issue in the plotly.js repo and comment when you do so? That’s where the rendering work is done for plotly.py. A new issue will get more attention than one that’s been closed for 2.5 years :) https://github.com/plotly/plotly.js/issues

**Comment by blolt** [comment]
Ridiculous
