### ISSUE TITLE
Plotly.js version?

### ISSUE THREAD

**Issue by rskabelund** [plotly/plotly.py#961]
Is it possible to update to a later plotly.js version?

I would like to be able to take advantage of this fix:
https://github.com/plotly/plotly.js/pull/2094

Especially the Box trace text attribute to show custom text on hover.

Regards,

-Randy

**Comment by cldougl** [comment]
Hi there,
Looks like that pr was added in [plotly.js version 1.32.0](https://github.com/plotly/plotly.js/blob/master/CHANGELOG.md#1320----2018-01-11)  
[`plotly.min.js`](https://github.com/plotly/plotly.py/blob/master/plotly/package_data/plotly.min.js) was updated to version plotly.js 1.33.1 in [version 2.3.0](https://github.com/plotly/plotly.py/blob/master/CHANGELOG.md#230---2018-01-25) of plotly.py so you should be able to take advantage of that fix after upgrading to version 2.3.0 or above (we're currently on version 2.4.1).

Note the plotly.js update handled in this repo is specifically for plotly.offline (the online update is handled in a closed repo). 

You can expect `plotly.min.js` to be updated to version 1.35.x later this week :)

**Comment by rskabelund** [comment]
Ah, thank you for linking the changelog I had not seen that before.  That is why I couldn't tell what js version was being used.  I am on version 2.2.1.  Looks like I can upgrade to see the fix, great, thanks!

**Comment by cldougl** [comment]
Great! we'll update the changelog again later this week when we update `plotly.min.js` to the latest: version 1.35.0
