### ISSUE TITLE
Problem on the release 3.0.0rc1 : No module named 'plotly.datatypes'

### ISSUE THREAD

**Issue by frugeles** [plotly/plotly.py#963]
The release 3.0.0rc1 has a problem on the code /plotly/graph_objs/graph_objs.py and gives the following error when you load the package : 
ModuleNotFoundError: No module named 'plotly.datatypes'

To fix this error you should copy the following code: https://github.com/plotly/plotly.py/blob/master/plotly/graph_objs/graph_objs.py

Please fix this error for the following release.
Thanks!

**Comment by Juanlu001** [comment]
Affected by this as well. Also, perhaps I didn't look well enough but I don't see this version in the GitHub source tree?

**Comment by rmarren1** [comment]
Broken for me too, downgraded to 2.5.1 to fix

**Comment by jonmmease** [comment]
Closing as this was fixed before 3.0.0 final was released
