### ISSUE TITLE
A large amount of data is printed when I run Plotly from command prompt on Windows

### ISSUE THREAD

**Issue by pjandrews** [plotly/plotly.py#969]
Env info:
Plotly version 2.4.1 with Python.
Python 3.6.4 :: Anaconda, Inc.
Windows 7

Whenever I run a script from command prompt a whole bunch of data is printed on the screen. I wasn't seeing this with previous versions. Is there any way to stop this from happening?

Here are my imports:
import cufflinks as cf
from plotly.offline import plot
cf.go_offline()

Here is the beginning of the data (thousands of characters long):
{'text/html': '<script type=\'text/javascript\'>if(!window.Plotly){define(\'plotly\', function(require, exports...

and the end:
...(!Array.isArray(u)){if(!s[u])return void(a.enabled=!1);s[u]=0}var f,p=t.aggregations||[],m=a.

Thanks!
Paul

**Comment by cldougl** [comment]
Hi there,
Can you include a full, reproducible example of the code you're running. 
Please note that cufflinks is handled in a separate repo: [https://github.com/santosjorge/cufflinks](https://github.com/santosjorge/cufflinks) so it would be ideal to include an example using just Plotly's Python API.

**Comment by pjandrews** [comment]
Thanks, I tried removing cufflinks and the problem went away so I'll open a ticket with them.

**Comment by gjeusel** [comment]
Hey there,

Actually it isn't a cufflinks issue.
Just run & see:
> ``python -c "import plotly; plotly.offline.init_notebook_mode()"``

Seems like the culprit is [line 147 of offline/offline.py](https://github.com/plotly/plotly.py/blob/e932378d33a55a78c8f02ceec93cfa1565049f05/plotly/offline/offline.py#L147).
I'll let you finish the investigation ;)

**Comment by cldougl** [comment]
thanks @gjeusel - `plotly.offline.init_notebook_mode()` is specific for plotting offline in jupyter. 
If you're experiencing a different problem feel free to open a new issue with a reproducible example!

**Comment by citcheese** [comment]
have this same issue. On my computer garbage text eventually ends and script continues running. On colleague's computer garbage text seems to loop. Any ideas hwo to fix?

**Comment by pjandrews** [comment]
When i removed:

cf.go_offline()

The problem went away. The good news is that i dont think i need that line anyways in any of my code.
