### ISSUE TITLE
Polar Chart in offline mode renders categorical angular axis in the wrong way

### ISSUE THREAD

**Issue by JosPolfliet** [plotly/plotly.py#972]
Hi all,

Thanks for this great library.

When copypasting the code from https://plot.ly/python/polar-chart/ > Categorical Polar Chart I would expect to see 
![image](https://user-images.githubusercontent.com/12380065/37398200-0283708e-277e-11e8-80dd-375edcc8c6d0.png)

When I change the lines
```python
fig = go.Figure(data=data,layout=layout)
py.iplot(fig, filename='polar/category')
```
to
```python
import plotly.offline as offline
offline.iplot(data,layout)
```
the angular axis is off on the first plot for the second trace
![image](https://user-images.githubusercontent.com/12380065/37398267-3ee365fc-277e-11e8-9df8-942b670536f1.png)

The hover values of the second trace show the correct value, but their position is wrong. The rotation of the radial axis changes too, although I don't particularly mind. Might be related.

Any ideas on how to solve that?

**Comment by cldougl** [comment]
Hi there,
Can you please make sure you're using an updated version of the python api (i.e. 2.5.0):

![screen shot 2018-03-23 at 12 53 15 pm](https://user-images.githubusercontent.com/2789078/37842712-39eb103c-2e99-11e8-9046-4d5ae38c0cdb.png)

**Comment by cldougl** [comment]
closing this issue, @JosPolfliet please feel free to reopen/comment if you confirm you're using an updated version of the library. Thanks!
