### ISSUE TITLE
Subplot font size is hardcoded to 16pt

### ISSUE THREAD

**Issue by jisaacso** [plotly/plotly.py#985]
See https://github.com/plotly/plotly.py/blob/master/plotly/tools.py#L1336. Large font leads to overcrowding when plotting multiple subplots with titles. 

It would be better to have `make_subplots` accept a `kwargs` parameter like `font_size=8` or, more general, to have a `kwargs` parameter like `font=graph_objs.Font(size=8, color=...)`

**Comment by jjnurminen** [comment]
Seconded.

**Comment by jjnurminen** [comment]
>You guys probably already know how to update the fonts of subplots created by make_subplots

I had no idea. Tried googling for 'plotly subplot title font size' etc. but could not find a solution. I guess the key point here is that subplot titles are annotations.  

```
for i in fig['layout']['annotations']:
    i['font'] = dict(size=10,color='#ff0000')
```

Yep, that works great. Of course one can simply write `i['font']['size'] = 10`. Maybe this should be in the example gallery?

**Comment by jisaacso** [comment]
Same, I didn't realize that subplot titles are annotations. 

While it would still be nice to pass this in as a param to `make_subplots()` during initialization, this solves the problem for now, so I'll close. Thanks!
