### ISSUE TITLE
Sankey Diagram

### ISSUE THREAD

**Issue by devm2024** [plotly/plotly.py#986]
Hi,
I am trying to create a Sankey diagram using the tutorial provided in the below link
https://plot.ly/python/sankey-diagram/
I have the data in the same format as given in the tutorial, however, the diagram fails to load. It keeps showing Loading Graph

**Comment by cldougl** [comment]
Hi there,
Unfortunately we don't offer support for individual projects via this repo but we do have a community forum where we can help with individual problems: https://community.plot.ly/
