### ISSUE TITLE
Texture mapping or raw webgl API?

### ISSUE THREAD

**Issue by jiangzhongshi** [plotly/plotly.py#988]
Hi Plotly,

Thank you for the great library. I work with 3D geometry and am familiar with OpenGL (and know few about js) and trying to move my workflow to more cluster-based. 

For what I need, for now, the only thing that's not clear to me is how to do texture mapping with plotly, is it supported here? Or is there any WebGL API exposed so that I can manage to workaround?

**Comment by cldougl** [comment]
Hi there,
All of our webgl code can be found in our open-source graphing library repo: https://github.com/plotly/plotly.js

**Comment by jiangzhongshi** [comment]
Sorry for not being clear, what I'd like to know is how can I run raw WebGL in plot.py in the context of say, jupyter. Thanks!

**Comment by cldougl** [comment]
The plotly.js repo will handle all of the graph rendering so we don't support running raw webgl via the functionality of this repo for now.
