### ISSUE TITLE
How to create node groups and attach header for each node group in plotly sankey?

### ISSUE THREAD

**Issue by HemangLakhani** [plotly/plotly.py#990]
Hello,
I am working to create sankey diagram showing Term by Term courses mapping. 
for ex: Term 1 courses mapping to Term 2 courses, Term 2 courses mapping to Term 3 courses...up to 8 terms.
Here i the screenshot of what i want?
![sankey-snap](https://user-images.githubusercontent.com/12647516/38823749-3edcada0-4175-11e8-942e-e8cad975b64c.JPG)
 
You can find [the link here.](http://studentflows.unm.edu/?year=2011&college=ALL&major=N%2FA)

I want to display term by term mapping and also title for each node group in plotly. Can someone please help me out?

Thanks in advance.
I am using Pandas and python.

**Comment by cldougl** [comment]
Hi there,
Unfortunately we don't offer personal support via this channel (as it's reserved for issues and bugs with this repo) but we do have a community forum: https://community.plot.ly/ and support plan: https://support.plot.ly/ for this type of help!
