### ISSUE TITLE
Can an option for color_threshold be made available in Plotly dendrogram figure_factory?

### ISSUE THREAD

**Issue by paulamool** [plotly/plotly.py#995]
Plotly figure_factory create_dendrogram() clustering threshold is default and no option seems available to change this. This function is commonly used and very helpful to view large dendrogram clusters based on a colored distance threshold. `enhancement`

An attempt was made to update plotly/figure_factory/_dendrogram.py with a "color_threshold" (attached file) but it failed on CircleCI pull request "Added color_threshold to dendrogram #983", which is now closed.
[dendrogram.zip](https://github.com/plotly/plotly.py/files/1941377/dendrogram.zip)

Any help would be greatly appreciated.

**Comment by jonmmease** [comment]
Work underway by @Elpiro in https://github.com/plotly/plotly.py/pull/1075.  Please take a look if you have a chance. Thanks!

**Comment by jonmmease** [comment]
Done in #1214 and will be released in version 3.4.0.. Thanks @paulamool
