### ISSUE TITLE
Investigate http:base.domain vs. https:base.domain grid creation failure. 

### ISSUE THREAD

**Issue by BRONSOLO** [plotly/plotly.py#996]
I've experienced that grid creation fails with the following error when my base domain is specified to use HTTP instead of HTTPS. 

![screen shot 2018-04-24 at 11 22 30 am](https://user-images.githubusercontent.com/1909107/39200720-e81b7004-47ba-11e8-9002-897b576424e6.png)

We should investigate why this occurred and look to add better handling of HTTP vs. HTTPS config file specifications. 

Perhaps we should warn a user if they have specified HTTP?

@Kully @cldougl

**Comment by Kully** [comment]
> Perhaps we should warn a user if they have specified HTTP?

How often do requests use HTTP over HTTPS anyways? If it's substantial then a warning might be a good idea. Coercing to HTTPS doesn't ever seem like a good idea to me.

**Comment by BRONSOLO** [comment]
@Kully no requests should be made over HTTP / all requests should be made over HTTPS.

**Comment by Kully** [comment]
@BRONSOLO in that case I can write either a warning as you suggested or an error message that pops up before the more vague Plotly Request error to give a heads up. WDYT?

**Comment by BRONSOLO** [comment]
>an error message that pops up before the more vague Plotly Request error to give a heads up

I say go with the error message. @cldougl what do you think? 

I think it would also be useful if someone could investigate/reproduce what I saw in the top comment re: the "Listing all files not supported" when making a POST request to the grid V2 create endpoint when HTTP is specified for the base/api domain in the config file. It might give us more insight into how best to handle this fix.

**Comment by cldougl** [comment]
+1 for error message

@Kully was able to reproduce on etest

**Comment by BRONSOLO** [comment]
Thanks @Kully and @cldougl!

@Kully - were you able to identify why the "Listing all files not supported" error occurred when the POST request to create a grid was made over HTTP?

**Comment by Kully** [comment]
@BRONSOLO No I didn't investigate why.

**Comment by BRONSOLO** [comment]
OK, I suppose it's not so necessary. I'm mostly just curious : )

**Comment by Kully** [comment]
closing as issue is fixed
