### ISSUE TITLE
Blank plot

### ISSUE THREAD

**Issue by LevavasseurYann** [plotly/plotly.py#998]
It's look like an old issue show up again.
Didn't find a way to display plot in Jupyter offline.
![image](https://user-images.githubusercontent.com/10565953/39288188-c5d20c7e-4972-11e8-9255-d86feb846622.png)
an enough big room is left under the cell like the chart is here but still blank
Someone still have this issue ?

**Comment by jonmmease** [comment]
Hi @LevavasseurYann , to display plots in JupyterLab using `iplot` you need to install the `@jupyterlab/plotly-extension` extension. See instructions in the README at https://github.com/plotly/plotly.py for details.  Thanks!
